spinnaker/deck

app/scripts/modules/core/application/modal/newapplication.html

This should have been in all along, not sure how it just came up as an issue today, but it did.

warn users on app creation that dots break load balancer creation

---

app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/newapplication.html

mark required application fields as such

---

app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsExecutionLabel.html
app/scripts/modules/core/pipeline/pipelines.less

also removing old CSS that was only useful in the old executions view

include build number in Jenkins stage label

---

app/scripts/modules/core/insight/insightmenu.directive.html
app/scripts/modules/core/insight/insightmenu.directive.js
app/scripts/modules/core/search/infrastructure/infrastructure.controller.js

Since this is a recurring issue as folks get familiar with Spinnaker, @tomaslin suggested we surface the ability from the Infrastructure actions, which is a good idea.

allow cache refresh from infrastructure page actions

---

app/scripts/modules/core/deploymentStrategy/strategies/custom/custom.strategy.module.js

Also fixes subtle typo in AWS stage.
@anotherchrisberry @duftler PTAL
Needs to go in with https://github.com/spinnaker/orca/pull/652
Tag: https://github.com/spinnaker/spinnaker/issues/585

Enables custom strategy option for GCE in deployment dropdown.

---

app/scripts/modules/amazon/common/footer.directive.html
app/scripts/modules/amazon/common/footer.directive.js
app/scripts/modules/amazon/common/verification.directive.html
app/scripts/modules/amazon/common/verification.directive.js
app/scripts/modules/amazon/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/amazon/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/serverGroup/serverGroup.write.service.js
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/netflix/serverGroup/resize/awsResizeServerGroup.html

- `Rollback` becomes an server group action on enabled server groups

Support an explicit rollback action

---

app/index.html

added oxford comma to welcome messages

---

app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/core/cluster/cluster.service.js
app/scripts/modules/core/cluster/cluster.service.spec.js

include rollback task in running tasks, sort rollback options

---

settings.js

updates to base settings.js file to allow updates via configurator

replace let statements with var statements in settings

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

Not sure if this ever worked, but it doesn't right now and it's causing grief. This fixes it.

move notificationHours binding to ctrl on canary stage

---

settings.js

helps the docker compose story

widen default providers out of the box

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js

Prefer this (PR):
to this (current):

prefer longer branches when drawing pipeline graph

---

app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/azure/instance/details/instanceDetails.html
app/scripts/modules/azure/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/azure/securityGroup/details/securityGroupDetail.html
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.html
app/scripts/modules/cloudfoundry/instance/details/instanceDetails.html
app/scripts/modules/cloudfoundry/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/pipeline/config/actions/pipelineConfigActions.html
app/scripts/modules/core/pipeline/config/createNew.html
app/scripts/modules/core/pipeline/config/stages/core/executionSummary.html
app/scripts/modules/core/search/global/globalSearch.directive.html
app/scripts/modules/google/instance/details/instanceDetails.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/securityGroup/details/securityGroupDetails.html
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html
app/scripts/modules/netflix/feedback/feedback.html
app/scripts/modules/netflix/instance/aws/instanceDetails.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryExecutionSummary.html
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/netflix/templateOverride/pipelineConfigActions.html
app/scripts/modules/titan/instance/details/instanceDetails.html
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.html

Fixes scenarios like this:
So they look like this:
@duftler @gregturn @JargoonPard can you do a quick sanity check on your respective modules? Nothing exciting, more something to be aware of.

append dropdown menus to body

---

app/scripts/modules/netflix/chaosMonkey/chaosMonkeyConfigFooter.directive.html
app/scripts/modules/netflix/chaosMonkey/chaosMonkeyExceptions.directive.html

(netflix-only code)
* also moving region field to be adjacent to the account field, which is consistent with other input views

rename "cluster" field to "detail" in chaos monkey config

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/preconditions/types/expression/additionalFields.html

Added helptext which points to Spring Expression Language so that users understand they can make complex evaluations here.

Add helptext for checkPrecondition expression

---

app/scripts/modules/core/help/helpContents.js

Precondition expressions now longer need to be wrapped within ${ and }

---

app/scripts/modules/core/pipeline/config/preconditions/types/clusterSize/additionalFields.html

@anotherchrisberry @cfieber PTAL

surface all options for preconditions operations

---

app/scripts/modules/core/authentication/authentication.module.js
app/scripts/modules/core/authentication/userMenu/userMenu.directive.html
app/scripts/modules/core/authentication/userMenu/userMenu.directive.js
app/scripts/modules/core/authentication/userMenu/userMenu.directive.spec.js
app/scripts/modules/core/authentication/userMenu/userMenu.less
app/scripts/modules/core/authentication/userMenu/userMenu.module.js
app/scripts/modules/core/bootstrap/spinnakerHeader.html
app/scripts/modules/core/navigation/navigation.less
app/scripts/modules/netflix/feedback/feedback.directive.js
app/scripts/modules/netflix/feedback/feedback.html
app/scripts/modules/netflix/feedback/feedback.less
app/scripts/modules/netflix/templateOverride/spinnakerHeader.html
app/scripts/modules/netflix/whatsNew/whatsNew.directive.html
app/scripts/modules/netflix/whatsNew/whatsNew.directive.js
app/scripts/modules/netflix/whatsNew/whatsNew.directive.spec.js
app/scripts/modules/netflix/whatsNew/whatsNew.less

Currently only displays the logged in users name. Could do more later (eg logout). Does not
show if the authEnabled setting is false.

Add a user-menu

---

app/scripts/modules/core/pipeline/config/stages/checkPreconditions/checkPreconditionsExecutionDetails.html

Tidy up the precondition execution details view a bit

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html

show who canceled a pipeline, if available

---

app/scripts/modules/azure/serverGroup/details/networking/details/disassociateElasticIp.html
app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/core/projects/configure/projectConfig.modal.html
app/scripts/modules/core/task/monitor/taskMonitor.html
app/scripts/modules/netflix/fastProperties/modal/deleteFastProperty.html
app/scripts/modules/netflix/migrator/migrator.modal.submitting.html
app/scripts/modules/netflix/serverGroup/networking/details/disassociateElasticIp.html

Long ago, this was the `auto-focus` directive, but today it's the `autofocus` directive.

fix usage of autofocus directive

---

app/scripts/modules/cloudfoundry/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/CloneServerGroupCtrl.js
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.cf.controller.js
app/scripts/modules/cloudfoundry/serverGroup/serverGroup.transformer.js

* Trim out providerType from being submitted.
* Add support for Clone Server Group.

Fix CF deploy

---

app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/filter/executionFilter.service.js
app/scripts/modules/core/delivery/filter/executionFilter.service.spec.js
app/scripts/modules/core/task/tasks.controller.spec.js
test/mock/mockApplicationData.js

Also clarifying the text around the "Show [x]" field - and fixing the behavior so it makes sense per the label.
@zanthrash for your review

allow 20 executions per pipeline

---

app/scripts/modules/core/history/recentHistory.service.spec.js
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.js
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.spec.js

update instance counts in rolled back project clusters

---

.editorconfig
app/scripts/modules/core/application/config/applicationAttributes.directive.js
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html
app/scripts/modules/netflix/application/netflixCreateApplicationModal.controller.js
app/scripts/modules/netflix/application/netflixEditApplicationModal.controller.js
app/scripts/modules/netflix/help/netflixHelpContents.registry.js
app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/templateOverride/templateOverrides.module.js

Default if undefined is set to true both on create and edit
@anotherchrisberry think you mostly over the shouldered this already but PTAL

Adds legacyUdf attribute to application metadata

---

app/scripts/modules/core/healthCounts/healthCounts.html
app/scripts/modules/core/presentation/main.less

Should make it easier to reuse these icons
@zanthrash please review - this is a prerequisite for instance multiselect, which I'm breaking into a handful of smaller PRs

make health count icon CSS more consistent

---

app/scripts/modules/core/application/applications.controller.js
app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/core/confirmationModal/confirmationModal.controller.js
app/scripts/modules/core/confirmationModal/confirmationModal.controller.spec.js
app/scripts/modules/core/confirmationModal/confirmationModal.service.js
app/scripts/modules/core/pipeline/config/actions/delete/delete.module.js

* splitting service and controller into separate file
* allow users to specify body text and verification text in lieu of an account
@zanthrash please review - this is also part of the multiselect changes...

allow non-account verification in confirmation modals

---

app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/core/application/service/applications.write.service.js
app/scripts/modules/core/task/monitor/taskMonitorService.js
app/scripts/modules/core/task/task.read.service.js

Some of this has been broken (visual cues that the task is running) for a month; some of it has been broken (not actually submitting the create application task) for a day.
@duftler for your review

fix create application state with new task reader API

---

app/scripts/modules/amazon/validation/applicationName.validator.js
app/scripts/modules/core/application/config/deleteApplicationSection.directive.js
app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/core/application/modal/newapplication.html
app/scripts/modules/core/application/service/applications.write.service.js
app/scripts/modules/core/application/service/applications.write.service.spec.js
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/titan/titan.module.js
app/scripts/modules/titan/validation/applicationName.validator.js

Providers will be responsible for setting a valid pattern for application names.
Also removing the specific email error, since it shows up twice - once below the email address, and again at the bottom of the form with the other errors.
cc @duftler

enhanced application name validation - pattern per provider

---

app/scripts/modules/core/pipeline/config/triggers/cron/cron.validator.directive.js
app/scripts/modules/core/pipeline/config/triggers/cron/cron.validator.directive.spec.js
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.module.js

provides a nice English explanation of when the CRON expression is going to run - especially helpful since the Quartz Scheduler is not zero-based, i.e. "1" is "Sunday", which is confusing to a lot of people.
@zanthrash for your review

surface description on valid cron expressions

---

app/scripts/modules/core/deploymentStrategy/strategies/redblack/redblack.strategy.module.js

default maxRemainingAsgs to 2 on redblack

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js

@zanthrash please review when you have a minute
@dzapata this fixes the issues you are seeing with inaccurate stage durations

do not trust stage end times

---

app/scripts/modules/core/delivery/status/executionStatus.controller.js
app/scripts/modules/core/delivery/status/executionStatus.controller.spec.js
app/scripts/modules/core/delivery/status/executionStatus.html

Several folks have asked about this. Shows the parameters that were used when a pipeline ran.

include parameters in execution status header

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/core/instance/instanceListBody.directive.js

protect against instances with no health

---

app/scripts/modules/core/delivery/stageFailureMessage/stageFailureMessage.html
app/scripts/modules/core/pipeline/config/stages/bake/aws/bakeExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/bake/docker/bakeExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/bake/gce/bakeExecutionDetails.html

@duftler does this take care of the issues you're seeing with the bakery?

provide bakery link in errors block if bake failed

---

app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineStage.js

Looks like this was a copy/paste oversight when the stage was originally created from the Jenkins stage.
@tomaslin please review

fix copy/paste bug

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/status/executionStatus.controller.js
app/scripts/modules/core/delivery/status/executionStatus.controller.spec.js

filter parameters when execution is a strategy

---

app/scripts/modules/google/securityGroup/configure/ConfigSecurityGroupMixin.controller.js
app/scripts/modules/google/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/google/securityGroup/details/SecurityGroupDetailsCtrl.js

Requires https://github.com/spinnaker/orca/pull/703 before merging
@duftler PTAL
@anotherchrisberry - FYI

Hooks up generic upsert security group impl for GCE

---

app/scripts/modules/core/instance/details/multipleInstances.controller.js
app/scripts/modules/core/instance/details/multipleInstances.controller.spec.js

avoid NPEs when instances have no health in multiselect mode

---

app/scripts/modules/core/task/monitor/taskMonitorService.js
app/scripts/modules/core/task/task.read.service.js
app/scripts/modules/core/task/task.read.service.spec.js

@zanthrash please review - helps us avoid some more NPEs

handle failure better when waiting for task to match

---

app/scripts/modules/core/cluster/filter/clusterFilter.controller.js
app/scripts/modules/core/cluster/filter/clusterFilter.controller.spec.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.spec.js
app/scripts/modules/core/cluster/filter/filterNav.html

@anotherchrisberry Ok. I think I got all the edge cases.  Plz Review.

Spin 150: Cluster filter filtering on AZ and region

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryDeployment/canaryDeploymentExecutionDetails.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

If there's no link, we probably shouldn't provide a placeholder one that just goes to the Spinnaker home page.

do not provide dead links to canary builds

---

app/scripts/modules/amazon/common/footer.directive.html
app/scripts/modules/amazon/common/footer.directive.js
app/scripts/modules/amazon/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/azure/serverGroup/details/networking/details/disassociateElasticIp.html
app/scripts/modules/azure/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/cloudfoundry/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/task/verification/userVerification.directive.html
app/scripts/modules/core/task/verification/userVerification.directive.js
app/scripts/modules/core/task/verification/userVerification.directive.less
app/scripts/modules/google/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/google/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/netflix/fastProperties/modal/deleteFastProperty.html
app/scripts/modules/netflix/serverGroup/networking/details/disassociateElasticIp.html
app/scripts/modules/netflix/serverGroup/resize/awsResizeServerGroup.html
app/scripts/modules/titan/serverGroup/details/resize/resizeServerGroup.html

Verification will now look like this:
@tomaslin for your review

move user verification to modal footer

---

app/scripts/modules/core/confirmationModal/confirmationModal.controller.js

I forgot how many places we use this thing...

allow submitting confirmation modals when no account provided

---

app/scripts/modules/kubernetes/image/image.reader.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

Fixes warnings @tomaslin pointed out I introduced in #1881.

Placate the linter

---

app/scripts/modules/core/task/verification/userVerification.directive.less

@duftler can you review this when you have a minute?

widen verification input, center align text in input

---

app/scripts/modules/netflix/instance/aws/instanceDetails.html

SPIN-1356: Added the $USER bash variable to to the bastion host on the copy to clipboard link to SSH into the instance.

---

app/scripts/modules/core/pipeline/config/preconditions/modal/editPrecondition.controller.modal.js
app/scripts/modules/core/pipeline/config/preconditions/modal/editPrecondition.html
app/scripts/modules/core/pipeline/config/preconditions/preconditionList.directive.js
app/scripts/modules/core/pipeline/config/preconditions/selector/preconditionSelector.directive.js
app/scripts/modules/core/pipeline/config/preconditions/types/clusterSize/additionalFields.html
app/scripts/modules/core/pipeline/config/stages/checkPreconditions/checkPreconditionsStage.html

Had to get the application object into the scope of this directive, since it was not there to extract the region and cluster information.

Adding Cluster selector to preconditions stage config.

---

app/scripts/modules/core/pipeline/config/stages/findAmi/aws/awsFindAmiStage.js
app/scripts/modules/core/pipeline/config/stages/findAmi/aws/findAmiStage.html

@anotherchrisberry missed one.  Please review.

Adding Cluster Selector to Find AMI stage.

---

app/scripts/modules/netflix/fastProperties/applicationProperties.html

SPIN-867: Be explicit when application has no fast properties

---

app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupIngress.html

Added form validation (taged as required) around the Ingress security group and protocol field to prevent the Create button from being enabled.

SPIN-752: Spinnaker shouldn't allow security group creation with blank ingress security group.

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/healthCheck.html

SPIN-761: Create/Edit New Load Balancer screen should prepend "/" to health check ping path.

---

app/scripts/modules/core/task/task.read.service.js
app/scripts/modules/netflix/migrator/migrator.modal.submitting.html
app/scripts/modules/netflix/migrator/migrator.service.js
app/scripts/modules/netflix/migrator/migrator.service.spec.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.modal.html

Cleaning up the migrator to handle the next round for Netflix (Classic -> VPC).
@claymccoy please review

update migrator to classic->vpc0

---

app/scripts/modules/core/navigation/states.provider.js
app/scripts/modules/core/projects/dashboard/dashboard.html
app/scripts/modules/core/projects/project.controller.js
app/scripts/modules/core/projects/project.html

Also moving `$scope`-bound properties to `vm`.

do not try to initialize project if not found

---

app/scripts/modules/netflix/migrator/migrator.service.spec.js

I should really stop doing this.

fdescribe -> describe

---

app/scripts/modules/amazon/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/amazon/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroup.html
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupProperties.html

Missed this somehow in the migration

fix form scoping on security group modals

---

app/scripts/modules/netflix/migrator/migrator.service.js
app/scripts/modules/netflix/migrator/migrator.service.spec.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.modal.html

@claymccoy HOLD until Tide is ready, but this should handle errors gracefully and surface them to the user, whether Tide or Orca fails.

update pipeline migrator for classic -> vpc0

---

app/scripts/modules/netflix/serverGroup/diff/securityGroupDiff.directive.js

@zanthrash review review review

correctly dismiss security group warning

---

app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.html
app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.modal.less
app/scripts/modules/core/cloudProvider/providerSelection/providerSelector.directive.js

@skim1420 Can you give this a shot? It should render the provider options more gracefully, whether there are two, three, or four options presented.

more dynamic rendering of provider buttons

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/instance/details/details.kubernetes.module.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js

provider/kubernetes: Surface instance details in UI

---

app/scripts/modules/amazon/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
app/scripts/modules/core/serverGroup/configure/common/v2instanceArchetype.directive.html
app/scripts/modules/core/serverGroup/configure/common/v2instanceArchetypeSelector.directive.js

Giving up trying to maintain wizard state based on instance type all over the place and moving to a `$watch`.
@zanthrash for your review

mark instance type page complete when instance type selected

---

app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js

@duftler (this was the problem you were seeing)

provider/kubernetes: Fix bug where clone task source was undefined.

---

app/scripts/modules/kubernetes/instance/details/details.controller.js

provider/kubernetes: Fix link back to server group from instance.

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js

guard against NPE when calculating deprecated region flag

---

app/scripts/modules/titan/serverGroup/details/serverGroupDetails.titan.controller.js
settings.js

fix titan clone

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/image/image.reader.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/namespace/namespaceSelectField.directive.html
app/scripts/modules/kubernetes/namespace/namespaceSelectField.directive.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/containers.html
app/scripts/modules/kubernetes/serverGroup/transformer.js

@duftler 
The docker registry accounts provided in clouddriver populate the image list.
You can pick which namespace to deploy to.

provider/kubernetes: Select image & namespace using docker registry.

---

app/scripts/modules/core/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.spec.js

I can't believe I missed something in that previous 2900 line pull request.

people like to edit pipeline configs

---

app/scripts/modules/core/pipeline/config/stages/bake/aws/awsBakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/aws/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/gce/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/gce/gceBakeStage.js

Move ng-if logic intro controller methods.

---

app/scripts/modules/core/delivery/create/createPipelineModal.controller.js
app/scripts/modules/core/delivery/create/createPipelineModal.controller.spec.js
app/scripts/modules/core/delivery/filter/filterNav.html
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js
app/scripts/modules/core/pipeline/config/actions/delete/delete.module.js
app/scripts/modules/core/pipeline/config/actions/delete/deletePipelineModal.controller.spec.js
app/scripts/modules/core/pipeline/config/actions/rename/rename.module.js
app/scripts/modules/core/pipeline/config/actions/rename/renamePipelineModal.controller.spec.js
app/scripts/modules/core/pipeline/config/createNew.html

more pipeline config fixes

---

app/scripts/modules/core/account/account.service.js
app/scripts/modules/core/application/listExtractor/listExtractor.service.js
app/scripts/modules/core/pipeline/config/stages/findAmi/gce/gceFindAmiStage.js
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js
app/scripts/modules/core/widgets/accountZoneClusterSelector.component.js

Cherry-pick's @zanthrash's commit from his pending PR and adds a couple of additional tweaks.
Would have pushed to the same branch/pr, but I don't have permissions for that fork.

Gce zone selector fix

---

app/scripts/modules/azure/securityGroup/clone/cloneSecurityGroup.controller.js
app/scripts/modules/azure/securityGroup/configure/CreateSecurityGroupCtrl.js
app/scripts/modules/azure/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/azure/securityGroup/configure/createSecurityGroupProperties.html
app/scripts/modules/azure/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/azure/securityGroup/details/securityGroupDetail.html
app/scripts/modules/azure/securityGroup/securityGroup.write.service.js

I have updated onTaskComplete as per Chris'feedback.

Adding functionality to Edit, Delete, and Clone security group for Azure

---

app/scripts/modules/cloudfoundry/cf.module.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/CloneServerGroupCtrl.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupAdvanced.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupArtifactSettings.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupBasicSettings.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupEnvs.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupLoadBalancers.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupServices.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/advanced.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/artifactSettings.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/envs.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/loadBalancers.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/services.html

* Permissions are set wide. A TODO is left to properly secure things after Find/Bake support is added.

Add v2 wizard support for CF

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/loadBalancer/loadBalancer.write.service.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/advancedSettings.controller.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/ports.controller.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/ports.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/wizard.html
app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/loadBalancer/transformer.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html

provider/kubernetes: Display load balancer dialog

---

app/scripts/modules/google/instance/gceInstanceTypeService.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/templateSelection.html

Replace double-quotes with single-quotes to placate linter.

Add GCE Deploy Stage template message.

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/subnet/subnet.renderer.js
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/subnet/subnet.renderer.js

Replace double-quotes with single-quotes to placate linter.
Add GCE Deploy Stage template message.

Dynamically determine whether to show Subnet column in Deploy Stage edit view.

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/loadBalancers.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/loadBalancers.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/replicas.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/securityGroups.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html
app/scripts/modules/kubernetes/serverGroup/transformer.js

provider/kubernetes: Pick SG ports & LBs

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/help/netflixHelpContents.registry.js

Moved the old message to netflix specific file and updated the default message in helpContents.js. This is related to #2008  and #2016 
@anotherchrisberry I had to create this new PR since I messed up the merge in #2008

Moved the old message to netflix specific file and updated the default msg

---

app/scripts/modules/netflix/fastProperties/modal/fastPropertyScopeBuilder.service.js

Fixing the app fetching for the FP wizard.

---

app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html

provider/kubernetes: Populate deploy with prior find image stages.

---

app/scripts/modules/core/application/applicationNav.html
app/scripts/modules/core/core.module.js
app/scripts/modules/core/deploymentStrategy/strategies/custom/custom.strategy.module.js
app/scripts/modules/core/navigation/states.provider.js
app/scripts/modules/netflix/application/applicationNav.html
package.json

Allows pipeline functionality to be disabled by setting the feature flag to `false`.
@ajordens please review

allow pipelines to be explicitly turned off

---

app/scripts/modules/kubernetes/loadBalancer/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/ports.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html
app/scripts/modules/kubernetes/loadBalancer/transformer.js

@duftler 
Needs https://github.com/spinnaker/clouddriver/pull/360

provider/kubernetes: Correctly assign load balancer type

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html
app/scripts/modules/core/pipeline/config/stages/findAmi/kubernetes/findAmiExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/findAmi/kubernetes/kubernetesFindAmiStage.js
app/scripts/modules/core/widgets/accountNamespaceClusterSelector.component.html
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/transformer.js

Fixes deploys from empty templates as well.
@duftler

provider/kubernetes: Renders registry for cloned server groups

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/script/scriptExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/script/scriptStage.html

depends on  https://github.com/spinnaker/orca/pull/747

allow users to specify an alternate location for their stash repos

---

app/scripts/modules/core/cache/deckCacheFactory.js

Whoever said cache invalidation is hard was correct.
Incredibly, our abstraction on top of an abstraction on top of local storage has some edge cases where it breaks. One of those is that we put a proxy in front of our cache to keep it in memory. We need to clear it when we clear the local storage, though, in the event that there's an error putting an item into local storage, and the right way to do that is to bomb it entirely, instead of just deleting the item we're trying to add.
To deal with this old, corrupt data, we need to bomb out the orphaned data. Otherwise, the lower level abstraction (angular cache) will just keep serving up the old data without trying to reset it.
@zanthrash for your review. @duftler this probably fixes what you saw Friday night.

bomb stale data if cache keys somehow get deleted

---

app/scripts/modules/core/pipeline/config/stages/script/scriptStage.js

depends on https://github.com/spinnaker/orca/pull/749

allows script stage to be restarted

---

app/scripts/modules/netflix/fastProperties/modal/wizard/fastPropertyAcaInstanceStrategyForm.directive.html

MAHE is expecting "percent" not "percentage".

Changing "percentage" to "percent" to match up w/ Mahe.

---

app/scripts/modules/core/pipeline/config/stages/findAmi/cf/cfFindAmiStage.js

Needs to include "regions" in the stage context for orca.

Fix Cloud Foundry Find Image

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html

provider/kubernetes: Display YAML for resources.

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/netflix/serverGroup/wizard/serverGroupCommandConfigurer.service.js

Going with this over https://github.com/spinnaker/deck/pull/2053 - we'll disable the user data setting in Netflix mode, and let users make the change by providing a custom service via `serverGroupCommandRegistry`

override user data setting in netflix mode

---

app/scripts/modules/titan/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titan/serverGroup/configure/serverGroupCapacityDirective.html
app/scripts/modules/titan/serverGroup/configure/serverGroupCapacitySelector.directive.js
app/scripts/modules/titan/serverGroup/configure/wizard/CloneServerGroup.titan.controller.js
app/scripts/modules/titan/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.html

depends on https://github.com/spinnaker/clouddriver/pull/378

resize functionality for titus

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/core/serverGroup/configure/common/serverGroupCommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

provider/kubernetes: Enable `edit` server group in deploy stage.

---

app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeStage.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeStage.js
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeStepLabel.html
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/details.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.controller.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.html

Needs https://github.com/spinnaker/orca/pull/757 and https://github.com/spinnaker/clouddriver/pull/381 for the pipeline stage to work correctly.

provider/kubernetes: Resize server group adhoc & pipeline stage

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/triggers/docker/dockerPopoverLabel.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js
app/scripts/modules/core/pipeline/config/triggers/trigger.module.js

provider/docker: Add trigger dialog.

---

app/scripts/modules/titan/serverGroup/configure/wizard/CloneServerGroup.titan.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/ServerGroupBasicSettings.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/ServerGroupCapacity.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/ServerGroupParameters.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/ServerGroupResources.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/titan/serverGroup/configure/wizard/capacity.html
app/scripts/modules/titan/serverGroup/configure/wizard/parameters.html
app/scripts/modules/titan/serverGroup/configure/wizard/resources.html
app/scripts/modules/titan/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.titan.controller.js
app/scripts/modules/titan/titan.module.js

@anotherchrisberry @zanthrash PTAL

use v2 modals for titan server groups

---

app/scripts/modules/core/projects/dashboard/pipeline/projectPipeline.less
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

Also adding some padding between project pipelines
@zanthrash or @tomaslin please review

guard against NPEs when transforming canary stages in project pipelines

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.html
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/core/loadBalancer/AllLoadBalancersCtrl.js

If "isAdd" flag is true, the modal will return the LB object instead of submitting for create. Also the title and button labels will change based on this flag.
This change was done for issue https://github.com/spinnaker/spinnaker/issues/760

Added the ability to get LB info from the LB modal dialog. 

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/probe.directive.html
app/scripts/modules/kubernetes/container/probe.directive.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/details/details.html

provider/kubernetes: Probe dialogs & info being surfaced

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html

provider/docker: Properly surface instance health

---

app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/disableAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/disableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/disableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/disableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/kubernetesDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/disableClusterExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/disableClusterExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/disableClusterStage.html
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/kubernetesDisableClusterStage.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/enableAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/enableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/enableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/enableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/kubernetesEnableAsgStage.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/details.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/rollback/rollback.controller.js
app/scripts/modules/kubernetes/serverGroup/details/rollback/rollback.html

provider/kubernetes: Enable/disable/rollback adhoc & pipeline

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/search/resultFormatter.js

provider/kubernetes: Search results show up for all infrastructure

---

app/scripts/modules/amazon/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
app/scripts/modules/amazon/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/basicSettings/basicSettings.html
app/scripts/modules/azure/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html

@anotherchrisberry @duftler Added form tags for AWS and GCE as well as validation code in AWS controller. GCE already had the check in the html.
PTAL

Fix for missing form tag on server group wizards

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/editLoadBalancer.html

Since the LB is not yet created, editing a LB entry in the pipeline should allow to change the LB name etc. So added the "Location" directive when forPipelineConfig=true.
Added editLoadBalancerTemplateUrl in aws.module.js so that it can be referenced in the LB Stage code instead of referencing it by path (like ../../../../ )

Updated EditLoadBalancer modal to support editing LB in pipeline

---

app/scripts/modules/core/task/taskProgressBar.directive.js

guard against absent error message in task progress bar

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancerProperties.html
app/scripts/modules/amazon/loadBalancer/configure/healthCheck.html
app/scripts/modules/amazon/loadBalancer/configure/listeners.html
app/scripts/modules/amazon/loadBalancer/configure/securityGroups.html

More cleanup based on the wrapper `<form>` tags added over the weekend.
heads up @vjames-bmc - if you are working in these modals right now, you'll want to rebase once I get these changes merged.

remove nested forms from load balancer modal

---

app/scripts/modules/core/instance/instance.write.service.js
app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html

provider/kubernetes: (De)register instance dialogs.

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html

For instance, server group & load balancer.
@duftler

provider/kubernetes: Destroy op dialogs

---

app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/validation/applicationName.validator.js

@ewiseblatt 
Looks like my initial 253 character limit was pretty off.

provider/kubernetes: Fix max length service name

---

app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/kubernetesDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/kubernetesDisableClusterStage.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/kubernetes/kubernetesEnableAsgStage.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.controller.js
app/scripts/modules/kubernetes/serverGroup/details/rollback/rollback.controller.js

@duftler 
Depends on https://github.com/spinnaker/clouddriver/pull/446

provider/kubernetes: Set interesting health providers by stage

---

app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.modal.html

optionally allow classic ingress

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/container/probe.directive.html
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

provider/kubernetes: Specify pod volumes & env vars.

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/securityGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/backend.controller.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/backend.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/rules.controller.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/rules.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/wizard.html
app/scripts/modules/kubernetes/securityGroup/transformer.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/securityGroups.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

provider/kubernetes: Upsert security group

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

Add normalize method for Server Groups

---

app/scripts/modules/core/pipeline/config/stages/destroyAsg/kubernetes/destroyAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/kubernetes/destroyAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/kubernetes/destroyAsgStage.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/kubernetes/destroyAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/kubernetes/kubernetesDestroyAsgStage.js
app/scripts/modules/kubernetes/kubernetes.module.js

@duftler 
Looks like any other stage.

provider/kubenretes: Destroy server group stage in pipeline

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.html
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.js
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.module.js
settings.js

@anotherchrisberry Please find the changes for the "Create Load Balancers" stage.
It is enabled only if the infrastructureStages flag in settings.js is true
I have attached couple of screens showing how it looks running.

Added "Create Load Balancers" stage. 

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
app/scripts/modules/azure/serverGroup/serverGroup.transformer.spec.js

Fixed name assignment for server group

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

initialize the interestingHealthProviderNames array to an empty list for now

add default health providers list to server group

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.html

provider/kubernetes: Specify secret volumes & entrypoint array

---

app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js
app/scripts/modules/core/pipeline/config/pipelineConfigProvider.spec.js
settings.js

@anotherchrisberry - requested by @tomaslin

core: Feature flag triggers

---

app/scripts/modules/netflix/fastProperties/modal/fastPropertyUpsert.controller.js
app/scripts/modules/netflix/fastProperties/modal/wizard/fastPropertyForm.directive.html

- Was just a text input which made adding/editing multiline values difficult.

SPIN-1619: Making the Fast Property Value field an expanding text area.

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

Fixes name rendering in pipelines

Add freeFormDetails to satisfy common functionality

---

app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js

We're guarding on the first part, just not the second

NPE guard in stage config memoize function

---

app/scripts/modules/netflix/fastProperties/applicationProperties.controller.js
app/scripts/modules/netflix/fastProperties/modal/fastPropertyUpsert.controller.js
app/scripts/modules/netflix/fastProperties/modal/wizard/fastPropertyScopeForm.directive.html
app/scripts/modules/netflix/fastProperties/modal/wizard/scope/scopeSingleAppSelector.directive.js

- Fixed and angular module namespace collision that was causing the app selector directive not to render.

SPIN-1624: Fixing regression in the FP strategy wizard.

---

app/scripts/modules/titan/instance/details/instanceDetails.html
app/scripts/modules/titan/serverGroup/configure/ServerGroupCommandBuilder.js

add link to console output unde logs
fix allocateIpValue not being set when cloning

small fixes for titus

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/subnet/subnet.read.service.js

SPIN-1628: Adding subnet details to the loadbalancer details.

---

app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html

@duftler They seem to work out of the box!

provider/kubernetes: Custom strategies

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.spec.js
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html

SPIN-1628: Adding the subnet purpose to the Load Balancer details pane.

---

app/scripts/modules/core/pipeline/config/stages/bake/bakery.service.js

default AWS bakes to HVM

---

app/scripts/modules/amazon/validation/applicationName.validator.js
app/scripts/modules/core/presentation/main.less

Pretty simple stuff, corresponds with https://github.com/spinnaker/deck/commit/d2ff57b8a0dfba445e93f5767139f766e0921bdc to provide a little less surprise to users.

adds warning when creating applications if Classic deployment is locked

---

app/scripts/modules/core/bootstrap/spinnakerHeader.html
app/scripts/modules/core/core.module.js
app/scripts/modules/core/navigation/states.provider.js
app/scripts/modules/core/projects/projects.controller.js
app/scripts/modules/core/projects/projects.controller.spec.js
app/scripts/modules/core/projects/projects.html
app/scripts/modules/core/projects/projects.module.js

Added a "Projects" tab in the main console. See issue https://github.com/spinnaker/spinnaker/issues/822 for details. 
@anotherchrisberry I created this tab since our internal team needed it. This PR has the "Projects" link at the top. We can change it if NetFlix UX recommends a different approach. Also, I am open to other suggestions that UX might have. I am submitting this PR so that we have a reference for discussions. Feel free to reject it if the UX team suggests an entirely different approach.
Thanks

Added a "Projects" view in the main console

---

app/scripts/modules/core/core.module.js
app/scripts/modules/netflix/feedback/feedback.directive.js
app/scripts/modules/netflix/feedback/feedback.html

provider/netflix: move help link to Slack

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/stages/applySourceServerGroupCapacity/applySourceServerGroupCapacityDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/applySourceServerGroupCapacity/applySourceServerGroupCapacityDetails.html
app/scripts/modules/core/pipeline/config/stages/applySourceServerGroupCapacity/applySourceServerGroupCapacityStage.module.js

- This stage is not executable by itself, rather it's synthetically injected after a deploy stage

Execution details view for the 'applySourceServerGroupCapacity' stage

---

app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.html
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.html
app/scripts/modules/core/utils/timeFormatters.js

cc @duftler @cfieber @sthadeshwar 
(don't merge until corresponding backend changes are in place)

use configured timezone instead of hardcoded "PST"

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.html
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.js
app/scripts/modules/core/presentation/less/imports/colors.less

Issue:
https://github.com/spinnaker/spinnaker/issues/685#issuecomment-201213764

Add option to continue pipeline when Jenkins stage fail - issue #685

---

app/scripts/modules/titan/instance/details/instance.details.controller.js

titus: fix instance passed in to enable / disable discovery

---

app/scripts/modules/netflix/fastProperties/fastPropertyDetails.controller.js

Fixes routing error around fast properties.

---

app/scripts/modules/azure/azure.module.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/azureDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/disableAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/disableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/disableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/disableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/azureEnableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/enableAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/enableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/enableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/enableAsgStepLabel.html

Add implementation for enable/disable Azure server groups in pipelines

---

gradle/installViaTravis.sh

let's see if this gets that tag in place before the package starts...

build version info when performing travis install

---

app/scripts/modules/core/authentication/authentication.initializer.service.js

Auth login flow to hit /auth/redirect?to= endpoint

---

app/scripts/modules/core/authentication/authentication.initializer.service.js

Simplify error handling in auth flow.

---

app/scripts/modules/core/cluster/all.html
app/scripts/modules/core/cluster/allClusters.controller.js
app/scripts/modules/core/cluster/categorySelection/categorySelection.html
app/scripts/modules/core/cluster/categorySelection/categorySelection.service.js
app/scripts/modules/core/cluster/cluster.module.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/job/configure/common/jobCommandBuilder.js
app/scripts/modules/core/job/job.write.service.js
app/scripts/modules/kubernetes/cluster/cluster.kubernetes.module.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/job/configure/CommandBuilder.js
app/scripts/modules/kubernetes/job/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/job/configure/wizard/completion.html
app/scripts/modules/kubernetes/job/configure/wizard/wizard.html
app/scripts/modules/kubernetes/job/job.module.js
app/scripts/modules/kubernetes/job/transformer.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
settings.js

@anotherchrisberry @duftler 
This is the create dialog for Kubernetes jobs. I've feature-flagged this, and when enabled, the following dialog pops up when clicking "create server group":
If "job" is selected, the user is shown this dialog:

provider/kubernetes: Run job dialog

---

app/scripts/modules/core/authentication/authentication.initializer.service.js

Prevent flash of content during auth flow

---

app/scripts/modules/titan/serverGroup/serverGroup.transformer.js

provider/titus: placate linter

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/runJob/runJobExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/runJob/runJobStage.html
app/scripts/modules/core/pipeline/config/stages/runJob/runJobStage.js
app/scripts/modules/core/pipeline/config/stages/runJob/runJobStage.module.js

Still requires kubernetes specific job create dialog.

core: Run job pipeline stage

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html

`http` is not a great assumption

provider/aws: do not specify protocol in ELB DNS links

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/core/application/applicationNav.html

also fixing an error in the applicationNav template

(aws) fix platform health passing on instance reboot

---

app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/application/service/applications.read.service.spec.js

(core) ignore lazy sections when checking app.ready()

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/authentication/authentication.module.js

AuthN: add scheduler to re-authenticate periodically. @ttomsu @anotherchrisberry PTAL.

AuthN: add scheduler to re-authenticate periodically.

---

app/scripts/modules/core/application/application.controller.js
app/scripts/modules/netflix/fastProperties/applicationProperties.controller.js
app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyRollouts.html
app/scripts/modules/netflix/fastProperties/dataNav/properties.html

(netflix) fix routes to properties

---

app/scripts/modules/core/job/configure/common/jobCommandBuilder.js
app/scripts/modules/core/job/job.transformer.js
app/scripts/modules/core/job/job.write.service.js
app/scripts/modules/core/pipeline/config/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/runJob/runJobExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/runJob/runJobStage.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/job/configure/CommandBuilder.js
app/scripts/modules/kubernetes/job/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/job/configure/wizard/templateSelection.controller.js
app/scripts/modules/kubernetes/job/configure/wizard/templateSelection.html
app/scripts/modules/kubernetes/job/job.module.js
app/scripts/modules/kubernetes/job/transformer.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/templateSelection.controller.js

provider/kubernetes: run job pipeline stage

---

app/scripts/modules/core/help/helpContents.js

provider/kubernetes: Forgot secret tooltip

---

app/scripts/modules/kubernetes/kubernetes.module.js

provider/kubernetes: Load disable asg module

---

app/scripts/modules/core/deploymentStrategy/strategies/redblack/redblack.strategy.module.js

provider/kubernetes: Enable red/black for k8s

---

app/scripts/modules/core/delivery/executionBuild/executionBuildNumber.directive.html
app/scripts/modules/core/delivery/executionBuild/executionBuildNumber.directive.js
app/scripts/modules/core/delivery/executionBuild/executionBuildNumber.directive.less
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js

Also throwing some one-time bindings in there for good measure

(core) move buildInfo extraction to execution transformer

---

package.json

I see periodic crashes when running locally, which seem to go away with this one weird trick

(core) do not run locally in devtool/eval mode

---

app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/disableClusterExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/disableCluster/kubernetes/disableClusterExecutionDetails.html

provider/kubernetes: Surface disable cluster details

---

app/scripts/modules/titan/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titan/serverGroup/configure/wizard/parameters.html
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.html

allow users to edit titus labels, depends on https://github.com/spinnaker/clouddriver/pull/633

titus - add labels support

---

app/scripts/modules/core/pipeline/config/stages/optionalStage/optionalStage.directive.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

Show 'SKIPPED' rather than 'UNKNOWN' as the Canary Status

---

app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/azureEnableAsgStage.js

set default port settings for LB to 80 (HTTP)
change default storage for server group disk images to premium
bypass "platformHealthOnly" check when targeting azure

Azure default settings: LB port, storage, health

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/authentication/authentication.module.js

All the goodies needed in the UI to make https://github.com/spinnaker/gate/pull/230 work well. The Gate PR needs to be merged before this one.
@anotherchrisberry PTAL. Commits will be squashed upon submission.
@spinnaker/google-reviewers FYI

Google oauth merge

---

app/scripts/modules/amazon/vpc/vpcTag.directive.js
app/scripts/modules/amazon/vpc/vpcTag.directive.spec.js

Fix borked suff. rolling back for now

Rolling back SPIN-1772

---

app/scripts/modules/azure/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/azure/serverGroup/configure/wizard/basicSettings/ServerGroupBasicSettings.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.html
app/scripts/modules/azure/serverGroup/configure/wizard/securityGroup/serverGroupSecurityGroupsSelector.directive.html

Fixed a bug in deploy SG stage: "basic settings" was improperly marked as dirty causing the final validation to fail unless it was re-selected.
Fixed couple minor issues in the create server group modal: LB and security group controllers were too long.
Fixed couple minor bug in load balancer details: typo in the DNS handling, delete LB should be disabled if server groups are still attached to the load balancer.

Azure related bug fixes

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerPopoverLabel.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.html

docker trigger - sort fields

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html

Load only first N Docker images in Deck for Kubernetes provider. @lwander PTAL

Load only first N Docker images in Deck for Kubernetes provider

---

app/scripts/modules/core/authentication/authentication.service.js
app/scripts/modules/core/delivery/manualExecution/inlinePropertyScope.filter.js
app/scripts/modules/core/delivery/manualExecution/inlinePropertyScope.filter.spec.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

Adds the ability to edit multiple Fast Properties key/value pairs for all
Fast Property stage when manually triggering a pipeline.
Also adds the ability to create a new Fast Property stage from an existing
one.
Cleaned up some whitespace.

SPIN-1768 Manual Trigger Fast Property.

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

Remove the placeholder values that were used to deploy while waiting on bake to be implemented

Azure Deploy - Remove placeholder script language values

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executionGroup/executionGroup.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.js

* adding back `active` class when stage is selected (accidentally deleted it)
* ensuring stages have a min width of 50px so they can properly render durations
* including FAILED_CONTINUE as a valid state

(core) clean up formatting on stage durations

---

app/scripts/modules/core/delivery/filter/executionFilter.model.js

I botched the original cut, fixing now

(core) persist stage duration selection

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.less

only set min-width when stage duration is checked.

---

app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html

Fixes required fields in server group modal.
The UI did not indicate that the wizard was incomplete if zone was left unselected.
@lwander @duftler PTAL

Fixes required fields in server group modal. 

---

app/scripts/modules/amazon/applicationProviderFields/awsFields.html
app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/core/application/modal/applicationProviderFields.component.html
app/scripts/modules/core/application/modal/applicationProviderFields.component.js
app/scripts/modules/core/application/modal/applicationProviderFields.component.spec.js
app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/newapplication.html

Adds support to New/Edit Application dialog for provider-specific settings.
This PR includes an AWS setting because the setting is desired (and demonstrates the directive's usage), but I can pull it out.
@lwander @anotherchrisberry PTAL

 Adds support to New/Edit Application dialog for provider-specific settings

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

Utilized with https://github.com/spinnaker/echo/pull/90

Add ability to use regex for docker tag

---

app/scripts/modules/amazon/applicationProviderFields/awsFields.html
app/scripts/modules/core/application/modal/applicationProviderFields.component.js
app/scripts/modules/core/application/modal/applicationProviderFields.component.spec.js
settings.js

- Adds support for global provider settings
- Integrates with application-level provider settings (global settings are defaults on the create application modal).
@duftler @anotherchrisberry PTAL

Add support for global provider settings

---

app/scripts/modules/kubernetes/loadBalancer/transformer.js

- added instance health status to load balancer ui
@lwander PTAL

added instance health status to load balancer ui

---

app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js

provider/kubernetes: Correctly populate default secret

---

app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.html

provider/kubernetes: Typo causing volume grief

---

app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

(core) add stageCounter if missing from pipeline config

---

settings.js

Some people look at this value as the correct example, and it's not.

Update NFLX auth endpoint

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/serverGroup/configure/common/v2instanceArchetype.directive.html
app/scripts/modules/core/serverGroup/configure/common/v2instanceArchetypeSelector.directive.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/instance/gceInstanceType.service.js
app/scripts/modules/google/serverGroup/configure/serverGroup.configure.gce.module.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.gce.service.js
app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
app/scripts/modules/google/serverGroup/configure/wizard/instanceType/instanceType.html
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html

(gce) Add support for custom machine types 
@duftler PTAL

(gce) Add support for custom machine types 

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

when the organization is null. 
Also fix getTags throwing js errors.
and lint warning around repositories not used.

docker trigger - fix bug where images are not loaded 

---

app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.gce.service.js
app/scripts/modules/netflix/alert/alertHandler.js

Fix linter warnings

---

app/scripts/modules/amazon/serverGroup/details/securityGroup/editSecurityGroups.modal.controller.js
app/scripts/modules/amazon/serverGroup/details/securityGroup/editSecurityGroups.modal.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/serverGroup/serverGroup.write.service.js

depends on https://github.com/spinnaker/orca/pull/868

(aws) modal to update security groups in VPC server groups

---

app/scripts/modules/core/application/application.controller.js
app/scripts/modules/core/application/application.module.js
app/scripts/modules/core/application/applicationNav.html
app/scripts/modules/core/application/modal/pageApplicationOwner.html
app/scripts/modules/core/application/modal/pageApplicationOwner.modal.controller.js
app/scripts/modules/core/application/service/applications.write.service.js
app/scripts/modules/netflix/application/applicationNav.html

Support paging of the application owner

---

app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

Forgot we had a custom template on the Netflix end...

(netflix) allow security group editing on VPC server groups

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

This fix assumes an outdated version of echo. There is a simpler fix I have staged that doesn't need this PR, so I'm reverting it to keep the code clean.

Revert "provider/kubernetes: Fix docker trigger"

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

Needed by orca to determine when a trigger is valid. (Orca PR incoming).

(kubernetes) Add account to trigger image info

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

Reverts spinnaker/deck#2360
@duftler (don't make fun of me)

Revert "Revert "provider/kubernetes: Fix docker trigger""

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/cloudfoundry/instance/details/instanceDetails.html
app/scripts/modules/core/application/modal/applicationProviderFields.component.spec.js
app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/newapplication.html
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html
app/scripts/modules/netflix/instance/aws/instanceDetails.html
settings.js

@duftler @danielpeach PTAL
Seems like this only affects AWS right now, but I assume it'll be relevant other providers later. Once we include the custom links feature, it will definitely come into play.

(core) allow user-specified default port for applications

---

app/scripts/modules/google/gce.module.js
app/scripts/modules/google/instance/custom/customInstance.filter.js
app/scripts/modules/google/instance/custom/customInstanceBuilder.gce.service.js
app/scripts/modules/google/instance/details/instanceDetails.html
app/scripts/modules/google/serverGroup/configure/serverGroup.configure.gce.module.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

(gce) added filter for formatting custom instances
@duftler  PTAL

(gce) added filter for formatting custom instances

---

app/scripts/modules/google/instance/custom/customInstance.filter.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/serverGroup.transformer.js

provider/google: Respect regionalEnabled when editing Deploy stage in pipeline.
provider/google: Fix up display of zones in parens next to region in Deploy stage execution details.

provider/google: Add missing semicolon.

---

app/scripts/modules/google/instance/details/instance.details.controller.js

@duftler PTAL. I tested this on top of chris's PR (#2364) and it fixed the problem.

(gce) fixed baseIpAddress in instance details controller

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instance.details.controller.spec.js
app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.js
app/scripts/modules/cloudfoundry/instance/details/instanceDetails.html
app/scripts/modules/core/application/config/applicationConfig.controller.js
app/scripts/modules/core/application/config/applicationConfig.view.html
app/scripts/modules/core/application/config/applicationLinks.component.html
app/scripts/modules/core/application/config/applicationLinks.component.js
app/scripts/modules/core/instance/details/instanceLinks.component.html
app/scripts/modules/core/instance/details/instanceLinks.component.js
app/scripts/modules/core/instance/details/instanceLinks.component.less
app/scripts/modules/core/presentation/main.less
app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/instance/details/instanceDetails.html
app/scripts/modules/netflix/application/applicationConfig.html
app/scripts/modules/netflix/instance/aws/instanceDetails.html
app/scripts/modules/netflix/instance/titan/instanceDetails.html
app/scripts/modules/titan/instance/details/instance.details.controller.js
app/scripts/modules/titan/instance/details/instanceDetails.html

Allows configuration of instance links
(split out from https://github.com/spinnaker/deck/pull/2313)

(core) make instance links customizable

---

app/scripts/modules/kubernetes/job/configure/wizard/wizard.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

@lwander PTAL
(kubernetes) fixes image search for pipelines
The templates were rendering before the command was configured, which was breaking the controllers.

(kubernetes) fixes image search for pipelines

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.html
app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.module.js

git trigger - filter by branch

---

app/scripts/modules/core/cluster/filter/multiselect.model.js
app/scripts/modules/core/cluster/filter/multiselect.model.spec.js

I'm not as good at copy/pasting as I used to be.

(core) fix multiselect odd behavior

---

app/scripts/modules/netflix/fastProperties/applicationProperties.html
app/scripts/modules/netflix/fastProperties/dataNav/properties.html

sorry for the reformatting; only change is adding `items-per-page`

(netflix) fix pagination issue on fast property views

---

app/scripts/modules/core/instance/instance.write.service.js
app/scripts/modules/kubernetes/job/details/details.controller.js

(k8s) fixes job termination and console error
@lwander PTAL

(k8s) fixes job termination and console error

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTriggerOptions.directive.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTriggerOptions.directive.js
app/scripts/modules/core/pipeline/config/triggers/docker/selectorTemplate.html
app/scripts/modules/docker/image/image.reader.js

(docker trigger) - allow selection of docker tag on manual deploy

---

app/scripts/modules/kubernetes/job/details/details.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.controller.js

@lwander 
Three small fixes:
1). Fixes user challenge for resizing k8s server group.
2). Shows "Coming soon" under job action dropdown.
3). Fixes console error when attempting to clone.

(k8s) fix user challenge

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/openstack/common/isolateForm.directive.js
app/scripts/modules/openstack/common/selectField.directive.html
app/scripts/modules/openstack/common/selectField.directive.js
app/scripts/modules/openstack/floatingIp/floatingIpSelectField.directive.html
app/scripts/modules/openstack/floatingIp/floatingIpSelectField.directive.js
app/scripts/modules/openstack/loadBalancer/configure/configure.openstack.module.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/createWizard.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/destinations.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/editWizard.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/healthCheck.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/location.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/loadBalancer/details/details.controller.js
app/scripts/modules/openstack/loadBalancer/details/details.html
app/scripts/modules/openstack/loadBalancer/details/details.openstack.module.js
app/scripts/modules/openstack/loadBalancer/loadBalancer.less
app/scripts/modules/openstack/loadBalancer/transformer.js
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/subnet/subnetSelectField.directive.html
app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Initial UI code changes to support CRUD operations of load balancers for OpenStack.
Code is still non-functional pending availability of APIs to list floating IP addresses as well as back-end implementation to list load balancers and subnets (APIs exist, but are not yet functional for OpenStack).

Changes for load balancers.

---

app/scripts/modules/core/pipeline/config/triggers/trigger.directive.js
app/scripts/modules/core/pipeline/config/triggers/trigger.html

(core) allow certain trigger types to disable automatic triggering

---

app/scripts/modules/openstack/cache/configurer.service.js
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/securityGroup/configure/configure.openstack.module.js
app/scripts/modules/openstack/securityGroup/configure/wizard/basicSettings.html
app/scripts/modules/openstack/securityGroup/configure/wizard/createWizard.html
app/scripts/modules/openstack/securityGroup/configure/wizard/editWizard.html
app/scripts/modules/openstack/securityGroup/configure/wizard/rules.controller.js
app/scripts/modules/openstack/securityGroup/configure/wizard/rules.html
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/securityGroup/details/details.controller.js
app/scripts/modules/openstack/securityGroup/details/details.html
app/scripts/modules/openstack/securityGroup/details/details.openstack.module.js
app/scripts/modules/openstack/securityGroup/transformer.js

Creating openstack security groups is done.
Details and Edit functionality are not implemented yet, as backend code is not ready.
Addressed all your comments.

(Openstack) Security Group UI Code.

---

app/scripts/modules/core/deploymentStrategy/strategies/custom/custom.strategy.module.js
app/scripts/modules/core/deploymentStrategy/strategies/redblack/redblack.strategy.module.js
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.html

Also enables custom and red black push strategies.

(titus) - enable and disable server groups. 

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js

'Instance Type' column for Deploy Stage configuration

---

app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/location.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/loadBalancer/details/details.controller.js
app/scripts/modules/openstack/loadBalancer/details/details.html
app/scripts/modules/openstack/loadBalancer/transformer.js
app/scripts/modules/openstack/network/networkSelectField.directive.html
app/scripts/modules/openstack/network/networkSelectField.directive.js

Small naming change for floating ip -> network

changing from floating ip to network because of back end change

---

app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.module.js

cc @tomaslin - same fix as the docker trigger one yesterday...

(core) guard against undefined git trigger branch field

---

app/scripts/modules/openstack/common/selectField.directive.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/destinations.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/network/networkSelectField.directive.js
app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Populate network drop-down in load balancer create/edit with values provided by back-end
Resolves issue #965.

Populate network drop-down in load balancer create/edit

---

app/scripts/modules/openstack/common/selectField.directive.js
package.json

Fix syntax warning and update clipboard dependency to enable development on Windows environments.

Fix syntax warning and update clipboard dependency

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/core/subnet/subnet.read.service.js
app/scripts/modules/core/subnet/subnetTag.component.js
app/scripts/modules/netflix/instance/aws/instanceDetails.html

(aws) show subnet purpose in instance details

---

app/scripts/modules/core/pipeline/config/parameters/parameter.html
app/scripts/modules/core/pipeline/config/parameters/parameters.directive.js
app/scripts/modules/core/pipeline/config/parameters/parameters.html
app/scripts/modules/core/pipeline/config/pipelineConfig.less
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

With one parameter:
With multiple:

(core) allow pipeline parameters to be reordered

---

settings.js

(netflix) change default gate URLs for Netflix development

---

app/scripts/modules/kubernetes/job/configure/wizard/wizard.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.html

@lwander 
(k8s) wizard: styling and volume source fix

(k8s) wizard: styling and volume source fix

---

app/scripts/modules/core/notification/selector/notificationSelector.directive.js

fix issue where exisiting notification address was being set to empty

---

app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js

related changes for https://github.com/spinnaker/clouddriver/pull/767

(aws) include vpcId, accountId on existing ingress rule edits

---

app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js

(kubernetes) don't reject dup lbs in diff namespaces

---

app/scripts/modules/core/application/config/links/applicationLinks.component.js
app/scripts/modules/core/application/config/links/editLinks.modal.html
app/scripts/modules/core/modal/modals.less
app/scripts/modules/core/pipeline/config/actions/json/editPipelineJsonModal.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

Modal will be wider and the textarea will take up as much vertical space as possible.

(core) allow json edit modals to use full screen height

---

app/index.html
app/scripts/modules/core/analytics/analytics.service.js
app/scripts/modules/core/application/applicationNav.html
app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/core.module.js
app/scripts/modules/core/delivery/create/createPipelineButton.html
app/scripts/modules/core/delivery/details/executionDetailsSectionNav.html
app/scripts/modules/core/delivery/executionBuild/executionBuildNumber.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/delivery/filter/filterNav.html
app/scripts/modules/core/delivery/status/executionStatus.html
app/scripts/modules/core/filterModel/filter.tags.html
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancersTag.html
app/scripts/modules/core/pipeline/config/createNew.html
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.directive.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/pipeline/config/stages/core/executionSummary.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/aws/destroyAsgExecutionDetails.html
app/scripts/modules/core/search/global/globalSearch.controller.js
app/scripts/modules/core/search/global/globalSearch.directive.html
app/scripts/modules/core/serverGroup/serverGroup.directive.html
app/scripts/modules/core/utils/clipboard/copyToClipboard.directive.js
app/scripts/modules/netflix/application/applicationNav.html
package.json

Including support for Google Analytics tracking (configured via settings.js).
This PR adds basic navigation support (provided OOB by angulartics), as well as tracking support for most clickable things on the pipeline and pipeline config views. I did not touch actual stage implementations, since there is way too much code there and I would like to get a feel for how this looks and if the metrics are going to be useful as-is before diving in any further.

(core) support analytics: pipelines/config

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

(k8s) copy template fix
@lwander PTAL

(k8s) copy template fix

---

app/scripts/modules/core/modal/wizard/wizardSubFormValidation.service.js
app/scripts/modules/core/modal/wizard/wizardSubFormValidation.service.spec.js
app/scripts/modules/core/projects/configure/configureProject.modal.controller.js
app/scripts/modules/core/projects/configure/configureProject.modal.html
app/scripts/modules/core/projects/configure/projectApplications.modal.html
app/scripts/modules/core/projects/configure/projectClusters.modal.html
app/scripts/modules/core/projects/configure/projectConfig.modal.html
app/scripts/modules/core/projects/configure/projectPipelines.modal.html
app/scripts/modules/core/validation/validation.module.js
app/scripts/modules/google/serverGroup/configure/wizard/capacity/capacity.html
app/scripts/modules/google/serverGroup/configure/wizard/capacity/zones.html
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/location/basicSettings.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/kubernetes/job/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js

(core) sub form validation service
@lwander @duftler fyi, this should fix a lot of outstanding wizard issues in kubernetes and gce. I've manually tested the wizards for clone and create and in pipelines.

(core) sub form validation service

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/projects/dashboard/dashboard.controller.js

- also clean up some whitespace

Add Lodash back to Dashboard Ctrl

---

app/scripts/modules/core/pipeline/config/stages/wait/waitStage.html

This is a hack. This should be pulled out into a component.  Needed to get this in so the shakti project cn build.

Quick fix to allow SpEL in the wait time field

---

app/scripts/modules/google/loadBalancer/details/hostAndPathRules/hostAndPathRules.controller.js
app/scripts/modules/google/loadBalancer/details/hostAndPathRules/hostAndPathRules.modal.html
app/scripts/modules/google/loadBalancer/details/hostAndPathRules/hostAndPathRules.service.js
app/scripts/modules/google/loadBalancer/details/hostAndPathRules/hostAndPathRulesButton.component.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@duftler @jtk54 please review
(gce) host and path rules modal

(gce) host and path rules modal

---

app/scripts/modules/core/application/application.less
app/scripts/modules/core/pipeline/config/stages/wait/waitStage.html
app/scripts/modules/core/pipeline/config/stages/wait/waitStage.module.js
app/scripts/modules/core/widgets/index.js
app/scripts/modules/core/widgets/spelText/numberInput.component.js
app/scripts/modules/core/widgets/spelText/spelText.decorator.js

This is a component that allows for the toggling between a number input field and text input field that allows for the entry of of SpEL.

Number Input to SpEL input component.

---

app/scripts/modules/core/securityGroup/securityGroup.write.service.js
app/scripts/modules/openstack/cache/cacheConfigurer.service.js
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/search/resultFormatter.js
app/scripts/modules/openstack/securityGroup/configure/wizard/basicSettings.html
app/scripts/modules/openstack/securityGroup/configure/wizard/createWizard.html
app/scripts/modules/openstack/securityGroup/configure/wizard/editWizard.html
app/scripts/modules/openstack/securityGroup/configure/wizard/rules.html
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/securityGroup/details/details.controller.js
app/scripts/modules/openstack/securityGroup/details/details.controller.spec.js
app/scripts/modules/openstack/securityGroup/details/details.html
app/scripts/modules/openstack/securityGroup/details/details.openstack.module.js
app/scripts/modules/openstack/securityGroup/securityGroup.reader.js
app/scripts/modules/openstack/securityGroup/transformer.js

Please review my code for edit and delete functionality.

Openstack Security Group Edit and Delete

---

app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/wizard/zones/regionalSelector.directive.html

provider/google: Drop regionalEnabled flag.

---

app/scripts/modules/core/delivery/service/execution.service.js

(core) re-fix execution filters

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageStage.html
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageStage.js
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageStage.module.js

Simple pipeline stage in support of image tagging (aws-only right now)

---

app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.html

It's only a little better but it's definitely better IMO
_current_
_with this change_

(core) add some space between buttons on manual judgment

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

(gce) disable l7 load balancer edit

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/migrator/migratedLoadBalancers.component.js
app/scripts/modules/netflix/migrator/migratedSecurityGroups.component.js
app/scripts/modules/netflix/migrator/migrationLoadBalancers.component.js
app/scripts/modules/netflix/migrator/migrationWarnings.component.js
app/scripts/modules/netflix/migrator/migrator.less
app/scripts/modules/netflix/migrator/migrator.modal.submitting.html
app/scripts/modules/netflix/migrator/migrator.service.js
app/scripts/modules/netflix/migrator/migrator.service.spec.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.modal.html
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.modal.html

Using the new Clouddriver migration features instead of Tide.

(netflix) use new migrate features for VPC0 migration

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/netflix/migrator/migrator.modal.submitting.html
app/scripts/modules/netflix/migrator/migrator.service.js

Also added a completely unrelated change, fixing opacity on the load balancers dropdown menu when the server group is disabled.

(netflix) better monitoring status on migration modal

---

app/scripts/modules/core/loadBalancer/filter/LoadBalancerFilterCtrl.js
app/scripts/modules/core/loadBalancer/filter/LoadBalancerFilterCtrl.spec.js
app/scripts/modules/core/loadBalancer/filter/filterNav.html
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.model.js
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.model.spec.js

Obviously a lot of overlap between this PR and the last one for the cluster filters... I'd like to hear your take on refactoring some aspects of the two filter models into a single service.

(core) load balancer filter zones and regions by account

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancersTag.html

(core) fix alignment, clean up style on load balancer tag

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.spec.js
app/scripts/modules/amazon/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.js
app/scripts/modules/amazon/serverGroup/configure/wizard/serverGroupWizard.html

(aws) default to first keypair when default not present in new region

---

app/scripts/modules/core/projects/dashboard/pipeline/projectPipeline.less
app/scripts/modules/netflix/migrator/migrator.service.js
app/scripts/modules/netflix/migrator/migrator.service.spec.js

also, (core) fix formatting of build number in project pipeline, because that's the kind of week it is.

(netflix) correctly identify multi-account migrations

---

app/scripts/modules/core/filter/percent.filter.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.js
app/scripts/modules/google/serverGroup/details/serverGroup.details.gce.module.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

@duftler @jtk54 please review. This probably should not be merged before jake's clouddriver PRs have been merged.

(gce) fix l7 support

---

app/scripts/modules/netflix/instance/titus/instanceDetails.html
app/scripts/modules/netflix/instance/titus/netflixTitusInstanceDetails.controller.js
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.titus.controller.js

added link to titus job and instance
removed zones
allow ip address to be copied to clipboard for containers

Changed some links in titus UI based on feedback from MCE

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.js

Manual Judgment support for `propagateAuthenticationContext`

---

app/scripts/modules/core/application/application.less
app/scripts/modules/core/widgets/spelText/numberInput.component.js
app/scripts/modules/core/widgets/spelText/spel.less

- "nests" the button group with in the input field.
- Reverses the state of the button group.  Before the white, "poped-up" button was the one selected.  Now the selected one is in shadow and apears depressed.

Updated number input with toggle for SpEL

---

app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsExecutionDetails.html

- must have reverted a change on the original commit between taking screenshots

Fix `Find Image from Tags` execution details

---

app/scripts/modules/core/notification/notificationList.directive.html
app/scripts/modules/core/notification/notificationList.directive.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.controller.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.html
app/scripts/modules/core/pipeline/config/stages/optionalStage/optionalStage.directive.html
app/scripts/modules/core/pipeline/config/stages/overrideTimeout/overrideTimeout.directive.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

(core) prevents unnecessary pipeline JSON changes when toggling buttons

(core) prevents unnecessary pipeline JSON changes when toggling buttons

---

app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageExecutionDetails.html

Support tagging of multiple images

---

app/scripts/modules/core/pipeline/config/actions/actions.module.js
app/scripts/modules/core/pipeline/config/actions/history/diffSummary.component.js
app/scripts/modules/core/pipeline/config/actions/history/diffView.component.js
app/scripts/modules/core/pipeline/config/actions/history/jsonDiff.service.js
app/scripts/modules/core/pipeline/config/actions/history/showHistory.controller.js
app/scripts/modules/core/pipeline/config/actions/history/showHistory.less
app/scripts/modules/core/pipeline/config/actions/history/showHistory.modal.html
app/scripts/modules/core/pipeline/config/actions/pipelineConfigActions.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/pipeline/config/services/pipelineConfigService.js
package.json

(core) provide diff view for pipeline history

---

app/scripts/modules/core/help/helpContents.js

(gce) Update load balancing policy tooltip text.

---

app/scripts/modules/core/pipeline/config/stages/disableAsg/disableAsgStage.js

lost in a glorious refactor a week ago

include disableAsg controller

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.js
app/scripts/modules/core/delivery/executionGroup/executionGroup.less
app/scripts/modules/core/delivery/triggers/nextRun.component.js
package.json

(core) show next scheduled run for cron triggered pipelines

---

app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.html
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.js
app/scripts/modules/core/projects/dashboard/dashboard.controller.js
app/scripts/modules/core/projects/dashboard/dashboard.html
app/scripts/modules/core/projects/dashboard/regionFilter/regionFilter.component.html
app/scripts/modules/core/projects/dashboard/regionFilter/regionFilter.component.js
app/scripts/modules/core/projects/dashboard/regionFilter/regionFilter.component.less
app/scripts/modules/core/projects/dashboard/regionFilter/regionFilter.service.js

(core) added region / namespace filter in project dashboard view

(core) added region / namespace filter in project dashboard view

---

app/scripts/modules/netflix/templateOverride/pipelineConfigActions.html

Forgot about this template override

(netflix) allow pipelines to be disabled

---

app/scripts/modules/google/instance/custom/customInstanceBuilder.gce.service.js
app/scripts/modules/google/instance/gceVCpuMaxByLocation.value.js

(gce) updated max vcpu list

---

app/scripts/modules/google/loadBalancer/details/healthCheck/healthCheck.component.html
app/scripts/modules/google/loadBalancer/details/healthCheck/healthCheck.component.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

*(gce) health check for each backend in load balancer details
*(gce) server group details does not include non-existent loadBalancingPolicy
@jtk54 please review

(gce) health check for each backend in load balancer details

---

app/scripts/modules/openstack/common/validateType.directive.js
app/scripts/modules/openstack/securityGroup/configure/wizard/basicSettings.html
app/scripts/modules/openstack/securityGroup/configure/wizard/rules.controller.js
app/scripts/modules/openstack/securityGroup/configure/wizard/rules.html
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/securityGroup/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/securityGroup/details/details.html
app/scripts/modules/openstack/securityGroup/transformer.js

Also setting the default values for TCP, UDP and ICMP.

Openstack Security group support for UDP and ICMP

---

app/scripts/modules/netflix/feedback/feedback.html
app/scripts/modules/netflix/templateOverride/spinnakerHeader.html

Also changing the heading from "Feedback" to "Help", since it's not just feedback any more.

(netflix) include link to documentation

---

app/scripts/modules/core/retry/retry.service.js
app/scripts/modules/core/retry/retry.service.spec.js
app/scripts/modules/docker/image/image.reader.js

(core) added retry service, updated docker image reader with retries

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgment.service.js
app/scripts/modules/core/pipeline/config/stages/wait/waitExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/wait/waitExecutionDetails.html

@zanthrash there will probably be a conflict with your PR (execution service), so this can wait until you've got your stuff merged

(core) allow wait stage to be skipped

---

app/scripts/modules/core/serverGroup/configure/common/dirtyInstanceTypeNotification.component.html
app/scripts/modules/core/serverGroup/configure/common/dirtyInstanceTypeNotification.component.js
app/scripts/modules/core/serverGroup/configure/common/instanceArchetypeSelector.js
app/scripts/modules/core/serverGroup/configure/common/instanceTypeDirective.html
app/scripts/modules/core/serverGroup/configure/common/v2instanceArchetype.directive.html
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
app/scripts/modules/google/serverGroup/configure/wizard/instanceType/instanceType.html

@duftler please review, @anotherchrisberry any concerns? 
- fixed issue with instance type chicklet turning grey after selecting zone.
- updated error message to indicate machine mismatch with either image or location.  
- added error message for custom machine selection.

(gce) fix wizard instance type selection

---

app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/AccessSettings.controller.js
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js

@jcwest @anotherchrisberry 
I didn't remove the alerts since they'll disappear once the rest of the UI work for openstack is done.

Cleanup some linter warnings

---

.gitignore
package.json
webpack.config.js

Playing around with https://github.com/amireh/happypack and finding it speeds up local builds quite a bit (from ~60s to ~15s).
Curious if it plays well with Travis or makes any difference...let's find out!

(core) use HappyPack plugin to speed up local builds

---

app/scripts/modules/google/cache/cacheConfigurer.service.js
app/scripts/modules/google/httpHealthCheck/httpHealthCheck.reader.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.js
app/scripts/modules/google/serverGroup/serverGroup.transformer.js

provider/google: Add support for configuring AutoHealering during create/clone.

provider/google: Cache http health checks.

---

app/scripts/app.js
app/scripts/modules/docker/docker.module.js
app/scripts/modules/google/gce.module.js

(docker) add templates to template cache

---

webpack.config.js

(core) consider env variables when validating HappyPack cache

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/listeners.html
app/scripts/modules/amazon/loadBalancer/loadBalancer.transformer.js

Adds a new select box for certificate types 'iam' and 'acm' to build the full certificate ARN when creating/editing an elb.

adds support for aws acm ssl certificates for elbs

---

app/scripts/modules/netflix/serverGroup/wizard/advancedSettings/advancedSettings.html

Partially related to spinnaker/deck#2615

`Task Completion` wasn't showing up with `netflixMode: true`

---

app/scripts/modules/netflix/application/applicationNav.html
app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/tableau/application/appTableau.controller.js
app/scripts/modules/netflix/tableau/application/appTableau.html
app/scripts/modules/netflix/tableau/states.js
app/scripts/modules/netflix/tableau/summary/summaryTableau.controller.js
app/scripts/modules/netflix/tableau/summary/summaryTableau.html
app/scripts/modules/netflix/tableau/tableau.less
app/scripts/modules/netflix/templateOverride/spinnakerHeader.html

Nothing fancy - deferring everything to Tableau.
@zanthrash PTAL - I can show you what it looks like tomorrow

(netflix) include analytics dashboards

---

app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.html
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsStage.module.js

Companion to https://github.com/spinnaker/orca/pull/951

(core) allow user to skip remaining execution window

---

app/scripts/modules/kubernetes/pipeline/stages/findAmi/kubernetesFindAmiStage.js

(kubernetes) ImageNamePattern is not required

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

(kubernetes) replace image name spaces with dashes

---

app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.html
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.html
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/container/arguments.component.html
app/scripts/modules/kubernetes/container/arguments.component.js
app/scripts/modules/kubernetes/container/commands.component.html
app/scripts/modules/kubernetes/container/commands.component.js
app/scripts/modules/kubernetes/container/environmentVariables.component.html
app/scripts/modules/kubernetes/container/environmentVariables.component.js
app/scripts/modules/kubernetes/container/volumes.component.html
app/scripts/modules/kubernetes/container/volumes.component.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/namespace/selectField.directive.html
app/scripts/modules/kubernetes/namespace/selectField.directive.js
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobExecutionDetails.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html

(k8s) run container as run job stage

---

app/scripts/modules/core/delivery/status/executionStatus.html

* alter displayed timestamp to be human readable
* add timestamp tooltip to display real (original) timestamp.

(core) update pipeline trigger timestamp

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

(k8s) run job remove stack and detail fields, added validators

---

app/scripts/modules/kubernetes/event/event.directive.html
app/scripts/modules/kubernetes/event/event.directive.js
app/scripts/modules/kubernetes/serverGroup/details/details.html

@danielpeach 
Looks a little better now IMO

(kubernetes) Update event directive & add SG events

---

app/scripts/modules/core/snapshot/diff/snapshotDiff.modal.controller.js
app/scripts/modules/core/snapshot/diff/snapshotDiff.modal.html
app/scripts/modules/core/snapshot/snapshot.write.service.js

Created a restore service which starts a restore snapshot stage in orca. Surfaced the functionality to restore a snapshot from the diff view. PTAL @lwander @duftler @danielpeach

provider/core: Surfaced ability to restore snapshots from diff view

---

app/scripts/modules/core/snapshot/diff/snapshotDiff.modal.controller.js
app/scripts/modules/core/snapshot/diff/viewSnapshotDiffButton.component.js

@duftler please review, @nwwebb fyi
Fixes a few issues with the snapshot diff view.

(gce) update snapshot diff view

---

app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.html

Clarified rollback behavior

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

(kubernetes) image pull policy dialog

---

app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/container/environmentVariables.component.html
app/scripts/modules/kubernetes/container/environmentVariables.component.js
app/scripts/modules/kubernetes/container/volumes.component.html

Updated server group wizard and run job stage. @lwander please review

(k8s) secrets as envVars

---

app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

(google) allow server groups with discovery to be enabled

---

app/scripts/modules/core/help/helpField.directive.html
app/scripts/modules/core/help/helpField.directive.js

It's an open question whether folks look at the help fields - let's see...
@icfantv @zanthrash PTAL

(core) track help contents views

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTriggerOptions.directive.js

* back out #2654 due to https://github.com/spinnaker/clouddriver/pull/990 fix

(deck) revert docker tag de-duping

---

app/scripts/modules/core/application/application.module.js
app/scripts/modules/core/application/inferredApplicationWarning.service.js
app/scripts/modules/core/application/inferredApplicationWarning.service.spec.js
app/scripts/modules/core/navigation/states.provider.js

@ttomsu @anotherchrisberry please review

(core) warn user when application not configured

---

app/scripts/modules/core/instance/instance.write.service.js

(aws) send adjustMinIfNecessary flag on terminateAndShrink

---

app/scripts/modules/openstack/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/openstack/serverGroup/details/resize/resizeServerGroup.controller.spec.js
app/scripts/modules/openstack/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/openstack/serverGroup/details/serverGroup.details.module.js
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js

Added functionality for resizing server groups for openstack

---

app/scripts/modules/core/widgets/spelText/spelText.decorator.js

fixes spinnaker/spinnaker#1109

(core) do not apply contenteditable to radio or checkboxes

---

app/scripts/modules/core/loadBalancer/filter/loadBalancerDependentFilterHelper.service.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html

@lwander please review, @skim1420 fyi
- (k8s) display external ip in lb detail panel
- guard against load balancers without instances when filtering

(k8s) display external ip in lb detail panel

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.html
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.js
app/scripts/modules/core/pipeline/config/stages/overrideFailure/overrideFailure.component.html
app/scripts/modules/core/pipeline/config/stages/overrideFailure/overrideFailure.component.js
app/scripts/modules/core/pipeline/config/stages/stage.html
app/scripts/modules/core/pipeline/config/stages/stage.module.js

Allow failure behavior to be overridden on a stage by stage basis

---

app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.html
app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.js
app/scripts/modules/core/application/modal/newapplication.html

@ttomsu @anotherchrisberry please review

(core) specify group membership in app config

---

app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/loadBalancer/configure/createLoadBalancerProperties.html
app/scripts/modules/azure/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/azure/serverGroup/configure/serverGroup.configure.azure.module.js
app/scripts/modules/azure/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/azure/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.html
app/scripts/modules/azure/serverGroup/configure/wizard/networkSettings/ServerGroupNetworkSettings.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/networkSettings/ServerGroupNetworkSettingsSelector.directive.html
app/scripts/modules/azure/serverGroup/configure/wizard/networkSettings/ServerGroupNetworkSettingsSelector.directive.js
app/scripts/modules/azure/serverGroup/configure/wizard/networkSettings/networkSettings.html
app/scripts/modules/azure/serverGroup/configure/wizard/securityGroup/serverGroupSecurityGroupsSelector.directive.html
app/scripts/modules/azure/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

Add implementation support for selecting an existing virtual network and subnet when creating a load balancer (ApplicationGateway) or server group.

Add implementation for selecting from an existing vnet and subnet

---

app/scripts/modules/google/loadBalancer/configure/http/editStateUtils.service.js
app/scripts/modules/google/loadBalancer/httpLoadBalancer.write.service.js

(gce) removed instances from upsert http lb payload

---

app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineStage.html
app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineStage.module.js
app/scripts/modules/core/widgets/spelText/spel.less
app/scripts/modules/core/widgets/spelText/spelSelect.component.js

This was created for SPIN-1956, which allows the Pipeline Parameters in a Pipeline stage to use and show SpEL for paramgers that have mulple options.
This simply a component <spel-select></spel-select> tha can wrap a ui-select or regular select field.

SpEL / ui-select toggle widget

---

app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.html
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js
app/scripts/modules/titus/titus.module.js

Titus as a runjob stage

---

app/scripts/modules/openstack/loadBalancer/configure/wizard/listeners.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/loadBalancer/details/details.html
app/scripts/modules/openstack/loadBalancer/transformer.js

provider/openstack: remove internalProtocol from create lb and lb details

---

app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html

fix width of region field in titus run job

---

webpack.config.js

@anotherchrisberry @danielpeach PTAL

Adds https as configurable option in dev server

---

app/scripts/modules/core/widgets/spelText/spelText.decorator.js
app/scripts/modules/openstack/serverGroup/configure/serverGroup.configure.openstack.module.js
app/scripts/modules/openstack/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/advanced/advancedSettings.component.html
app/scripts/modules/openstack/serverGroup/configure/wizard/advanced/advancedSettings.component.js
app/scripts/modules/openstack/serverGroup/configure/wizard/advanced/advancedSettings.html
app/scripts/modules/openstack/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/openstack/serverGroup/serverGroup.transformer.js

Also modifed the spel listener to allow it to not be attached to an input when the class 'nospel' is added to the input.

provider/openstack: adding advanced config with user data textarea to server group create/clone

---

app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.html
app/scripts/modules/google/loadBalancer/configure/http/editStateUtils.service.js
app/scripts/modules/google/loadBalancer/configure/http/healthCheck/healthCheck.component.html

(gce) allow hyphenated backend service and health check names

---

app/scripts/modules/core/application/modal/applicationProviderFields.component.js
app/scripts/modules/core/application/modal/applicationProviderFields.component.spec.js

(core) guard for application.cloudProviders type change

---

app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.controller.js

(titus) guard against missing fields on failed job run

---

app/scripts/modules/core/serverGroup/serverGroup.write.service.js
app/scripts/modules/openstack/common/appCacheBackedMultiSelect.template.html
app/scripts/modules/openstack/common/appCacheBackedMultiSelectField.directive.js
app/scripts/modules/openstack/instance/osInstanceTypeSelectField.directive.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/securityGroup/securityGroup.reader.js
app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/accessSettings.html
app/scripts/modules/openstack/serverGroup/configure/wizard/instance/ServerGroupInstanceSettings.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/instance/instanceSettings.html
app/scripts/modules/openstack/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.html
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js

Clean up server group actions. Make load balancer optional during create. Fix various bugs.

Openstack: server group actions

---

app/scripts/modules/core/search/infrastructure/infrastructure.controller.js

(core) route to search result if deep link includes "route=true"

---

app/scripts/modules/core/instance/instance.write.service.js

@danielpeach 
semi-required here: https://github.com/spinnaker/clouddriver/pull/1017

(core/instance) pass server group name alongside asg name in discovery ops

---

app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.html

titus - pull job details update inside the stateChange listener. Otherwise job details were not being updated

titus - update job status on job change

---

.gitignore
test/google/README.md
test/google/config.json
test/google/e2e/pages/cluster.page.js
test/google/e2e/pages/loadBalancer.page.js
test/google/e2e/pages/loadBalancerTypeChoice.page.js
test/google/e2e/pages/loadBalancerWizard.page.js
test/google/e2e/pages/serverGroupWizard.page.js
test/google/e2e/tests/cloneServerGroup.e2e.js
test/google/e2e/tests/createNetworkLoadBalancer.e2e.js
test/google/e2e/tests/createServerGroup.e2e.js
test/google/google_int.sh
test/google/package.json
test/google/protractor.conf.js
test/google/tasks/createApp/index.js
test/google/tasks/createApp/job.js
test/google/tasks/createApp/task.js
test/google/tasks/createServerGroup/index.js
test/google/tasks/createServerGroup/job.js
test/google/tasks/createServerGroup/task.js
test/google/tasks/deleteApp/index.js
test/google/tasks/deleteApp/job.js
test/google/tasks/deleteApp/task.js
test/google/tasks/index.js
test/google/tasks/monitorTask.js
test/google/tasks/orchestrator.js
test/google/tasks/runTask.js
test/google/tasks/utils/findImages.js

(gce) e2e tests for create and clone server group, create load balancer.

---

app/scripts/modules/netflix/tableau/application/appTableau.controller.js
app/scripts/modules/netflix/tableau/summary/summaryTableau.controller.js
app/scripts/modules/netflix/tableau/tableau.less
app/scripts/modules/netflix/templateOverride/spinnakerHeader.html

don't need to ajax out to get a token now

(netflix) update tableau configuration, initialization

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/replicas.html
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/transformer.js

@danielpeach 
Requires https://github.com/spinnaker/clouddriver/pull/1033

(kubernetes) autoscaler render details & deploy

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.js
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.spec.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.js
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagManager.service.js
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagSelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagSelector.component.js
app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagSelectorGenerator.component.js

(gce) specify target tags for security groups in server group wizard

---

app/scripts/modules/google/instance/details/instance.details.controller.js

(gce) fixed instance tags tooltips

---

app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineExecutionDetails.html
app/scripts/modules/core/projects/dashboard/pipeline/projectPipeline.directive.html

this is definitely the last one

(core) fix execution link from projects view

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/bake/bakeExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/bake/bakeStage.html
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

Implemented Openstack Bake and Deploy Steps.
We can execute Bake without software.

Openstack Bake and Deploy stage

---

package.json

(core) update to Typescript 2

---

app/scripts/modules/kubernetes/autoscaler/autoscaler.write.service.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.controller.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.html

(kubernetes) upsert autoscaler in resize screen

---

package.json

fix docker build

---

app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.js

I verified that the server group wizard creates the correct JSON payload for create and clone operations and in pipeline stages.

(gce) configure autohealer maxUnavailable in server group wizard

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTriggerOptions.directive.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/BasicSettings.controller.js

@lwander 
fixes k8s image lookup in wizard.
fixes docker trigger modal.

(k8s & docker) fixes for rxjs update

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/kubernetes/loadBalancer/details/details.html

@lwander @skim1420 fyi
(k8s) add anchor tags for load balancer ips

(k8s) add anchor tags for load balancer ips

---

app/scripts/modules/core/cache/infrastructureCacheConfig.js
app/scripts/modules/google/cache/cacheConfigurer.service.js
app/scripts/modules/google/certificate/certificate.reader.js
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/basicSettings.component.html
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/basicSettings.component.js
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/certificateSelector.component.html
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/certificateSelector.component.js
app/scripts/modules/google/loadBalancer/configure/http/createHttpLoadBalancer.controller.js
app/scripts/modules/google/loadBalancer/configure/http/port.html

(gce) add certificate selector for http load balancer wizard

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/pipeline/config/stages/core/executionSummary.html

display details of who restarted a pipeline and when.
PTAL @icfantv

make it clearer pipeline was restarted

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/openstack/serverGroup/configure/wizard/advanced/advancedSettings.component.html

Related to https://github.com/spinnaker/clouddriver/pull/1067

(openstack) reorganizing and improved wording on advanced server group settings

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/loadBalancerAvailabilityZoneSelector.directive.html

Also require that some AZ is selected before creating the load balancer

(aws) filter availability zones based on target subnet

---

webpack.config.js

(core) webpack config s/rx/rxjs

---

app/scripts/modules/netflix/fastProperties/fastProperty.dataSource.js

(netflix) do not enable properties tab if netflix mode is disabled

---

app/scripts/modules/openstack/common/appCacheBackedMultiSelectField.directive.js
app/scripts/modules/openstack/loadBalancer/loadBalancerSelectField.directive.js
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/resizeAsg/openstackResizeAsgStage.js
app/scripts/modules/openstack/pipeline/stages/resizeAsg/resizeAsgExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/resizeAsg/resizeAsgExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/openstack/pipeline/stages/resizeAsg/resizeAsgStepLabel.html
app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/instance/ServerGroupInstanceSettings.controller.js
app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Add support for resize server group pipeline stage in openstack.
Enable edit of server groups in deploy pipeline stage configuration.

(Openstack) Add resize server group pipeline stage + edit of server groups in deploy config

---

app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.html
app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.less
app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/delivery/delivery.dataSource.js
app/scripts/modules/core/loadBalancer/loadBalancer.dataSource.js
app/scripts/modules/core/securityGroup/securityGroup.dataSource.js
app/scripts/modules/core/serverGroup/serverGroup.dataSource.js
app/scripts/modules/netflix/fastProperties/fastProperty.dataSource.js
app/scripts/modules/netflix/tableau/tableau.dataSource.js

(core) include descriptions of data sources

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/destroyAsg/destroyAsgStage.html
app/scripts/modules/openstack/pipeline/stages/destroyAsg/destroyAsgStepLabel.html
app/scripts/modules/openstack/pipeline/stages/destroyAsg/openstackDestroyAsgStage.js

close https://github.com/spinnaker/spinnaker/issues/1126

provider/openstack: Added pipeline destroy server group stage

---

settings.js

@ttomsu @anotherchrisberry PTAL

Set fiatEnabled through the FIAT_ENABLED env var

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js

(core) fix provider selection in deploy stage

---

app/scripts/modules/openstack/instance/details/instance.details.controller.js
app/scripts/modules/openstack/instance/details/instanceDetails.html
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/serverGroup/serverGroup.transformer.js

Will work correctly when https://github.com/spinnaker/clouddriver/pull/1102 is merged.
@spinnaker/reviewers

(openstack) adding instance details view and operations

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/disableAsg/disableAsgStage.html
app/scripts/modules/openstack/pipeline/stages/disableAsg/disableAsgStepLabel.html
app/scripts/modules/openstack/pipeline/stages/disableAsg/openstackDisableAsgStage.js

closes https://github.com/spinnaker/spinnaker/issues/1128

provider/openstack - disable servergroup pipeline ui

---

app/scripts/modules/core/delivery/executions/executions.less

(core) align Start Manual Execution button with pipeline headers

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/disableCluster/disableClusterExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/disableCluster/disableClusterExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/disableCluster/disableClusterStage.html
app/scripts/modules/openstack/pipeline/stages/disableCluster/openstackDisableClusterStage.js
app/scripts/modules/openstack/pipeline/stages/enableAsg/enableAsgExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/enableAsg/enableAsgExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/enableAsg/enableAsgStage.html
app/scripts/modules/openstack/pipeline/stages/enableAsg/enableAsgStepLabel.html
app/scripts/modules/openstack/pipeline/stages/enableAsg/openstackEnableAsgStage.js

Openstack pipeline stage for Enable Server Group and Disable Cluster.

Openstack-Pipeline: Enable Server Group and Disable Cluster.

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/findAmi/findAmiExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/findAmi/findAmiExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/findAmi/findAmiStage.html
app/scripts/modules/openstack/pipeline/stages/findAmi/openstackFindAmiStage.js

closes spinnaker/spinnaker#1130

(Openstack) added find image from cluster in pipelines

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/ci/build.read.service.js
app/scripts/modules/netflix/ci/ci.controller.js
app/scripts/modules/netflix/ci/ci.controller.spec.js
app/scripts/modules/netflix/ci/ci.dataSource.js
app/scripts/modules/netflix/ci/ci.html
app/scripts/modules/netflix/ci/ci.less
app/scripts/modules/netflix/ci/ci.module.js
app/scripts/modules/netflix/ci/detail/detail.controller.js
app/scripts/modules/netflix/ci/detail/detailTab/detailTab.controller.js
app/scripts/modules/netflix/ci/detail/detailTab/detailTabView.html
app/scripts/modules/netflix/ci/detail/detailView.html
app/scripts/modules/netflix/ci/states.js
app/scripts/modules/netflix/netflix.module.js

Adding an optional CI tab for Netflix's internal CI project

(netflix) introduce ci tab

---

app/scripts/modules/amazon/pipeline/stages/bake/bakeExecutionDetails.html

This is now available in the bake results.

(aws) show image name in bake results

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/azure/loadBalancer/details/loadBalancerDetail.controller.js

We need to wait for the application security groups to be ready before attaching security groups.

(aws, azure) wait for app ready to initialize load balancer details

---

.gitignore
app/scripts/modules/core/application/application.model.ts
app/scripts/modules/core/application/service/applicationDataSource.registry.ts
app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts
app/scripts/modules/core/delivery/executionBuild/buildDisplayName.filter.ts
app/scripts/modules/core/delivery/status/executionUser.filter.ts
app/scripts/modules/core/domain/health.ts
app/scripts/modules/core/domain/loadBalancer.ts
app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
app/scripts/modules/core/pipeline/config/stages/deploy/clusterName.filter.ts
app/scripts/modules/core/presentation/anyFieldFilter/anyField.filter.ts
app/scripts/modules/core/task/displayableTasks.filter.ts
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
karma.conf.js
package.json
tslint.json
webpack.config.js

* add linting to ts build
* fix existing warnings in code base

(core) adding typescript linting

---

app/scripts/modules/core/chaosMonkey/chaosMonkey.help.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.ts
app/scripts/modules/google/loadBalancer/configure/http/templates.ts
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
tsconfig.json

* correct errors spit out by tsc

(core): correct tsc errors

---

app/scripts/modules/core/delivery/triggers/nextRun.component.js

Who knows what kind of thinking led to the bug being fixed here...

(core) correctly calculate next run after 6pm

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

(gce) realign load balancer details

---

app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js

(core) warn if parameter is missing name

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/scaleDownCluster/openstackScaleDownClusterStage.js
app/scripts/modules/openstack/pipeline/stages/scaleDownCluster/scaleDownClusterExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/scaleDownCluster/scaleDownClusterExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/scaleDownCluster/scaleDownClusterStage.html
app/scripts/modules/openstack/pipeline/stages/shrinkCluster/openstackShrinkClusterStage.js
app/scripts/modules/openstack/pipeline/stages/shrinkCluster/shrinkClusterExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/shrinkCluster/shrinkClusterExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/shrinkCluster/shrinkClusterStage.html
app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/clusterSettings.html

Add openstack support for shrink cluster and scale down cluster.
Fix bug in clone of server group.
Allow a server group to be created with zero instances.
FYI: Code was reviewed internally by @gadresushrut at Veritas.

Add openstack support for shrink cluster and scale down cluster.

---

app/scripts/modules/google/loadBalancer/configure/http/httpLoadBalancer.write.service.js
app/scripts/modules/google/loadBalancer/details/deleteModal/deleteModal.controller.ts
app/scripts/modules/google/loadBalancer/details/deleteModal/deleteModal.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

Gce delete health checks option

---

app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.js
app/scripts/modules/google/loadBalancer/configure/http/commandBuilder.service.js
app/scripts/modules/google/loadBalancer/configure/http/healthCheck/healthCheck.component.js
app/scripts/modules/google/loadBalancer/configure/http/listeners/listeners.html

@jtk54 
Turns out there were some bugs. They showed up when I tried to refresh backend services or health checks when a bes/hc wasn't fully configured.

(gce) fixed http lb wizard refresh bugs

---

app/scripts/modules/titus/serverGroup/configure/ServerGroupCommandBuilder.js

* adding patch for handling a corner case where hard/soft constraints
could come down as null/undefined (as interpreted by JS).

(titus): corner case for constraints

---

app/scripts/modules/core/modal/wizard/modalWizard.service.js

SPIN-2065
Upgraded lodash 4 _.filter signature changed ever so slightly.

(netflix) Fixes Fast Property Strategy selection.

---

app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/cloneServerGroupExecutionDetails.controller.js
app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/cloneServerGroupExecutionDetails.html
app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/cloneServerGroupStage.html
app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/cloneServerGroupStepLabel.html
app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/openstackCloneServerGroupStage.js

Clone Server Group Pipeline stage.

Openstack-Pipeline: Clone Server Group.

---

app/scripts/modules/core/delivery/service/execution.service.js

A bunch of fields we don't care about (i.e. we never look at in code and never render) consume a significant portion of the processor when handling pipeline executions.
The problem is two-fold (well, it's three-fold): we call `JSON.stringify` on each executions and store that as the `stringVal` field on each execution to determine if it's changed between refresh cycles, which leaves us with 50+MB strings sitting around in memory for the browser to manage. We're also retaining all those instance fields in our stages as fields, since they've been deserialized into objects.
I tried removing those same fields during the JSON parsing of the raw response (via the `transformResponse` field), but that seemed to add a couple of seconds to the processing time.
For our larger applications at …

(core) drop instances, asg fields from executions

---

app/scripts/modules/core/delivery/details/executionDetails.controller.js
app/scripts/modules/core/delivery/details/executionDetails.controller.spec.js
app/scripts/modules/core/pipeline/config/stages/stage.module.js

(core) warn on restarting a running pipeline

---

typings.json
webpack.config.js

* update typings file versions to latest (except angular)
* suppress known TS compiler issues on typings files

(core): update typings versions

---

app/scripts/modules/core/delivery/service/execution.service.js

Fixes a horrible flash users are seeing on running pipelines because I shouldn't write code at 1am and the merge it at 7:30.

(core) clean single execution before adding to application

---

app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
app/scripts/modules/openstack/loadBalancer/configure/wizard/location.html
app/scripts/modules/openstack/serverGroup/configure/wizard/serverGroupWizard.html

Closes spinnaker/spinnaker#1212 + spinnaker/spinnaker#1121
Fixes loadBalancerTag by adding more checks for undefined variables
Returns original submit button logic to create server group (no longer is always valid)
Create loadbalancer now requires stack and detail parameters to be filled in

(Core/Openstack) Fixes for a few small bugs

---

app/scripts/modules/core/api/api.service.js

@anotherchrisberry @duftler please review.
It would be better to check if `Content-Length : 0`, but Angular does not seem to expose content length in the `headers` function.

(core) add additional check for html in api service error-handling

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

Aligns with the changes in https://github.com/spinnaker/orca/pull/1013/files

s/12 hours/72 hours

---

app/scripts/modules/core/notification/modal/editNotification.controller.modal.js
app/scripts/modules/core/notification/modal/editNotification.html

This change enables us to specify a custom message that gets appended to Slack or Email notifications. Echo changes in place already.

SPIN-2076 allow custom message on stage / pipeline notifications

---

app/scripts/modules/core/delivery/service/execution.service.js

We'd originally written this using `$http` to avoid Restangular; however, by doing so, we miss a lot of the nice interception we get around authentication.
@zanthrash @icfantv PTAL - I believe this is what is behind the flurry of errors we've been seeing today.

(core) fetch executions via API service

---

app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.html
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.js
app/scripts/modules/netflix/help/netflixHelpContents.registry.js
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/securityGroup/securityGroupPicker.component.ts

(titus) add help text, improve job missing fields label

---

app/scripts/modules/titus/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/serverGroup/configure/wizard/ServerGroupParameters.controller.js
app/scripts/modules/titus/serverGroup/configure/wizard/constraints.ts
app/scripts/modules/titus/serverGroup/configure/wizard/parameters.html
app/scripts/modules/titus/serverGroup/serverGroup.transformer.js

(titus) make constraints selectable

---

app/scripts/modules/core/authentication/authentication.initializer.service.ts
app/scripts/modules/core/authentication/authentication.module.ts

couple little things:
* `then` returns an `ng. IHttpPromiseCallbackArg`, so we need to handle that (`success` returns the data itself)
* converting the service to a class means we need to wrap function calls

(core) fix reauthentication method

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/AccessSettings.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/accessSettings.html
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.html
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js
app/scripts/modules/openstack/serverGroup/serverGroup.transformer.js

(openstack) adding in support for assigning floating ips to asg members

---

app/scripts/modules/titus/serverGroup/serverGroup.transformer.js

(titus) do not touch security groups in transformer

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html

(core) force rebake alignment for manual execution

---

app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html
app/scripts/modules/netflix/application/netflixCreateApplicationModal.controller.js
app/scripts/modules/netflix/application/netflixEditApplicationModal.controller.js
app/scripts/modules/netflix/pagerDuty/pagerDuty.read.service.ts
app/scripts/modules/netflix/pagerDuty/pagerDutySelectField.component.ts

- Added directive with the dropdown of services from backend

Add PagerDuty dropdown list of services

---

app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.transformer.js

Fixing the ACA Task Stage status transformation

---

app/scripts/modules/core/application/modal/validation/applicationName.validator.js
app/scripts/modules/core/utils/waypoints/waypoint.service.js

These messages are just noise and add confusion when trying to help users with actual issues.

(core) remove/downgrade severity of commonly-logged debug messages

---

app/scripts/modules/netflix/application/applicationAttributes.directive.html
app/scripts/modules/netflix/application/netflixEditApplicationModal.controller.js
app/scripts/modules/netflix/pagerDuty/pagerDutyTag.component.ts

- (netflix) Added a new component to display the service name & the api key

Add pager duty tag in application edit mode

---

app/scripts/modules/google/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html

(google) Render autoscaling messages.

---

app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/netflix/ci/build.read.service.js
app/scripts/modules/netflix/ci/ci.controller.js
app/scripts/modules/netflix/ci/ci.dataSource.js
app/scripts/modules/netflix/ci/ci.html
app/scripts/modules/netflix/ci/ci.less
app/scripts/modules/netflix/ci/detail/detail.controller.js
app/scripts/modules/netflix/ci/detail/detailTab/detailTab.controller.js
app/scripts/modules/netflix/ci/detail/detailView.html

* Polling for updates to the status and logs of running builds
* Build details formatting enhancements
* Fix bug in selecting already-selected build

(netflix) Auto-Update Running Builds

---

app/scripts/modules/core/authentication/authentication.initializer.service.ts
webpack.config.js

removing the UglifyJS plugin while I'm in here, since it's horrible for development cadence as it runs every time any file changes

(core) fix typo on reauth call, remove webpack uglify plugin

---

app/scripts/modules/core/authentication/authentication.initializer.service.ts

missed this one on my last pass through

(core) fix reauthentication call

---

app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.js
app/scripts/modules/google/loadBalancer/configure/http/backendService/backendServices.html
app/scripts/modules/google/loadBalancer/configure/http/commandBuilder.service.js
app/scripts/modules/google/loadBalancer/details/backendService/backendService.component.ts
app/scripts/modules/google/loadBalancer/details/healthCheck/healthCheck.component.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/loadBalancer/loadBalancer.transformer.js

@jtk54
- a few changes to make the ILB details render properly.
- also a quick fix to make L7 upsert work properly.

(gce) render backend service and health check in ilb details

---

app/scripts/modules/netflix/ci/ci.controller.js

(netflix) auto-navigate to latest build

---

app/scripts/modules/google/domain/index.ts
app/scripts/modules/google/domain/network.ts
app/scripts/modules/google/loadBalancer/configure/internal/commandBuilder.service.ts
app/scripts/modules/google/loadBalancer/configure/internal/createLoadBalancerProperties.html
app/scripts/modules/google/loadBalancer/configure/internal/gceCreateInternalLoadBalancer.controller.ts
app/scripts/modules/google/loadBalancer/configure/internal/listener.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@duftler or @jtk54 
Allows user to select network and subnet for ILB create wizard. Also includes network and subnet in the load balancer details view.

(gce) select network in ilb wizard

---

app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

This work is to support https://github.com/spinnaker/fiat/issues/36
Fiat auth failure preview
Generic preview:
@danielpeach @anotherchrisberry PTAL

Surfaces pipeline error message when saving fails.

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/pipeline/config/pipelineConfigView.html
app/scripts/modules/core/pipeline/config/triggers/triggers.html

Support for specifying a Pipeline (and Pipeline Strategy) description

---

app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.html
app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.js
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/basicSettings.component.html
app/scripts/modules/google/loadBalancer/configure/http/basicSettings/basicSettings.component.js
app/scripts/modules/google/loadBalancer/configure/http/commandBuilder.service.js
app/scripts/modules/google/loadBalancer/configure/http/healthCheck/healthCheck.component.html
app/scripts/modules/google/loadBalancer/configure/http/healthCheck/healthCheck.component.js
app/scripts/modules/google/loadBalancer/configure/http/listeners/listener.component.html
app/scripts/modules/google/loadBalancer/configure/http/listeners/listener.component.js
app/scripts/modules/google/loadBalancer/configure/http/transformer.service.js

I never had the behavior right for the HTTP(S) load balancer wizard when there are multiple Google accounts (there were a few fields that didn't filter resources properly by account).

(gce) fix http load balancer account change errors

---

app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.html
app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.less
app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.ts
app/scripts/modules/kubernetes/annotation/annotationDetails.component.ts
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/loadBalancer/details/details.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html
app/scripts/modules/kubernetes/serverGroup/details/details.html

(k8s) UI support for kubernetes annotations

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@jtk54 please review. This didn't take much work. 
@anotherchrisberry -- I made a small change to the load balancer tag component.

(google) ssl load balancer details

---

app/scripts/modules/amazon/subnet/subnetSelectField.directive.js

SPIN-2127
If no subnet type is selected on the component object we will pick the first in the list of subnets,
which in our case is "internal (vpc0)" and assign it to the componet.

(netflix) sets "internal (vpc 0)" as the default selected subnet.

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryDeployment/canaryDeploymentExecutionDetails.controller.js
app/scripts/modules/titus/serverGroup/configure/ServerGroupCommandBuilder.js

Fixing some of the JS errors we are getting emailed this week.
@icfantv @anotherchrisberry PTAL

Puts guards around JS Errors

---

app/scripts/modules/core/widgets/spelText/spel.less
app/scripts/modules/core/widgets/spelText/spelText.decorator.js

Changing expressions to use monospace fontface

---

app/scripts/modules/core/application/config/applicationAttributes.directive.html
app/scripts/modules/core/application/config/applicationAttributes.directive.js
app/scripts/modules/core/application/config/applicationAttributes.directive.spec.js
app/scripts/modules/core/application/config/applicationConfig.controller.js
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/netflix/application/applicationAttributes.directive.html

* show all, specified application attributes from edit form on static
view of application attributes on config tab.

(core): update application attributes

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.html
app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineStage.html
app/scripts/modules/core/pipeline/config/stages/script/scriptStage.html

Removes the `Fail Pipeline` checkbox since this functionality is replicated by the `If stage fails` radio buttons in the same stage

removes fail pipeline checkbox

---

app/scripts/modules/core/pipeline/config/stages/checkPreconditions/checkPreconditionsExecutionDetails.html

Suppress expression field from the UI since this is not guaranteed to be pristine in check precondition stage

Remove Expression field for Check Precondition task details

---

app/scripts/modules/docker/image/dockerImageAndTagSelector.component.html
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js

* add the new docker image selector widget to the titus run job stage.
* update docker image selector widget to disable tag field when image
has not been selected.

(titus): docker selector to titus run job stage

---

app/scripts/modules/core/deploymentStrategy/strategies/custom/custom.strategy.module.js

(kubernetes) enable custom stages

---

app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js
app/scripts/modules/titus/serverGroup/configure/serverGroupBasicSettingsDirective.html
app/scripts/modules/titus/serverGroup/configure/wizard/CloneServerGroup.titus.controller.js

* update docker image selector to be more stable around race conditions

(titus): stabilize docker image selector

---

app/scripts/modules/google/loadBalancer/details/healthCheck/healthCheck.component.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js

(google) fix rendering health checks for http(s) load balancer details

---

app/scripts/modules/core/utils/uuid.service.spec.ts
app/scripts/modules/core/utils/uuid.service.ts

(core) fix uuid service

---

app/scripts/modules/core/application/applications.controller.js
app/scripts/modules/core/delivery/delivery.module.js
app/scripts/modules/core/delivery/executionBuild/buildDisplayName.filter.ts
app/scripts/modules/core/delivery/status/executionStatus.directive.js
app/scripts/modules/core/delivery/status/executionUser.filter.ts
app/scripts/modules/core/pipeline/config/stages/core/stage.core.module.js
app/scripts/modules/core/pipeline/config/stages/deploy/clusterName.filter.ts
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.module.js
app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js
app/scripts/modules/core/presentation/anyFieldFilter/anyField.filter.ts
app/scripts/modules/core/presentation/presentation.module.js
app/scripts/modules/core/projects/projects.controller.js
app/scripts/modules/core/task/displayableTasks.filter.ts
app/scripts/modules/core/task/tasks.controller.js
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

* fixed module name export names
* updated references

(core): normalize module names

---

app/scripts/modules/core/account/accountSelectField.directive.js

(core) account select fix

---

app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.module.js
app/scripts/modules/titus/pipeline/stages/cloneServerGroup/titusCloneServerGroupStage.js

fix some issues with bad rebases

(netflix) fix service imports on stages

---

app/scripts/modules/amazon/pipeline/stages/cloneServerGroup/awsCloneServerGroupStage.js
app/scripts/modules/amazon/pipeline/stages/cloneServerGroup/cloneServerGroupStage.html

(aws) block device mappings setting in clone stage

---

app/scripts/modules/amazon/cache/cacheConfigurer.service.js
app/scripts/modules/core/subnet/subnet.read.service.ts

Prevents cache refresh from doing anything from the config page.

(core) do not use local subnet cache

---

app/scripts/modules/core/utils/stickyHeader/stickyHeader.less

this clearly seemed like a good reason, but... it isn't.

(core) do not unset header with when un-fixing

---

app/scripts/modules/core/application/modal/applicationProviderFields.component.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/elSevenOptions/elSevenOptionsGenerator.component.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

@jtk54 or @duftler 
- Allows CONNECTION balancing mode for SSL load balancers (and renders details).
- Fixes bug where backend service selector was not deleted with selected HTTP(S) load balancer.

(google) include CONNECTION option for ssl load balancers

---

build.gradle
package.json

use package.json's node and npm versions in build.gradle

---

app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/pipeline/stages/scaleDownCluster/scaleDownClusterExecutionDetails.controller.js
app/scripts/modules/kubernetes/pipeline/stages/scaleDownCluster/scaleDownClusterExecutionDetails.html
app/scripts/modules/kubernetes/pipeline/stages/scaleDownCluster/scaleDownClusterStage.html
app/scripts/modules/kubernetes/pipeline/stages/scaleDownCluster/scaleDownClusterStage.js
app/scripts/modules/kubernetes/pipeline/stages/shrinkCluster/shrinkClusterExecutionDetails.controller.js
app/scripts/modules/kubernetes/pipeline/stages/shrinkCluster/shrinkClusterExecutionDetails.html
app/scripts/modules/kubernetes/pipeline/stages/shrinkCluster/shrinkClusterStage.html
app/scripts/modules/kubernetes/pipeline/stages/shrinkCluster/shrinkClusterStage.js

(kubernetes) shrink & scale down cluster

---

app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.ts
app/scripts/modules/kubernetes/annotation/annotationDetails.component.ts
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/securityContext/capabilitiesSelector.component.html
app/scripts/modules/kubernetes/container/securityContext/capabilitiesSelector.component.ts
app/scripts/modules/kubernetes/container/securityContext/seLinuxOptionsSelector.component.html
app/scripts/modules/kubernetes/container/securityContext/seLinuxOptionsSelector.component.ts
app/scripts/modules/kubernetes/container/securityContext/securityContextSelector.component.html
app/scripts/modules/kubernetes/container/securityContext/securityContextSelector.component.less
app/scripts/modules/kubernetes/container/securityContext/securityContextSelector.component.ts
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html

(k8s) add ui support for security context

---

app/scripts/modules/core/account/accountSelectField.directive.html
app/scripts/modules/core/application/modal/editApplication.controller.modal.js
app/scripts/modules/netflix/application/editApplication.modal.html

Another mind-blowing frontend contribution from yours truly.

Adding ability to edit application accounts

---

app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.ts
app/scripts/modules/core/presentation/autoScroll/autoScroll.directive.ts
app/scripts/modules/core/utils/tsDecorators/directiveFactoryDecorator.ts
app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyFilter.directive.ts

This is to make (re)writing directives in TypeScript less horrible.

Adding a Directive Factory Decorator

---

app/scripts/modules/core/pipeline/config/pipelineConfigurer.html

change copy stage icon to glyphicon duplicate

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

Fixes https://github.com/spinnaker/spinnaker/issues/1314

(core) fix details toggling on pipeline view

---

app/scripts/modules/kubernetes/serverGroup/details/details.html

@duftler @danielpeach @lwander

sets k8s server group actions order same as gce

---

app/scripts/app.js
app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/cache/cacheConfigurer.service.ts
app/scripts/modules/appengine/domain/IAppengineAccount.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/appengine/serverGroup/configure/wizard/serverGroupWizard.less
app/scripts/modules/appengine/serverGroup/details/appengine.details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html
app/scripts/modules/appengine/serverGroup/transformer.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/domain/serverGroup.ts
settings.js

@lwander or @duftler or @anotherchrisberry

(appengine) create server group

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/loadBalancer/transformer.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/domain/instanceCounts.ts
app/scripts/modules/core/domain/loadBalancer.ts

(appengine) load balancer transformer

---

package.json
update_node.sh

script for clean install with package.json node version

---

app/scripts/modules/amazon/pipeline/stages/resizeAsg/awsResizeAsgStage.js
app/scripts/modules/amazon/pipeline/stages/resizeAsg/resizeAsgStage.html

Orca already supports this, just need to add the field.
Will require a coordinated pipeline config update to avoid triggering the dirty check on existing pipelines, which I'll do separately this weekend (and can happen before this is released).

(aws) allow target percent configuration in resize stage

---

app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts

(google): correctly set default region value

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

Forgot we had this link in a separate section of the details panel
cc @jeyrschabu

(aws) show Scaling Activities in Logs section

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/loadBalancer/configure/wizard/createLoadBalancerMessage.component.html
app/scripts/modules/appengine/loadBalancer/configure/wizard/createLoadBalancerMessage.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.controller.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.html
app/scripts/modules/appengine/loadBalancer/loadBalancer.module.ts

(appengine) create lb message

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/cache/cacheConfigurer.service.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/loadBalancer/details/details.controller.ts
app/scripts/modules/appengine/loadBalancer/details/details.html
app/scripts/modules/appengine/loadBalancer/loadBalancer.module.ts

(appengine) load balancer details

---

app/scripts/modules/appengine/domain/IAppengineLoadBalancer.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/advancedSettings.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/allocationConfigurationRow.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/basicSettings.component.html
app/scripts/modules/appengine/loadBalancer/configure/wizard/basicSettings.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/createLoadBalancerMessage.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.controller.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.html
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.less
app/scripts/modules/appengine/loadBalancer/details/details.controller.ts
app/scripts/modules/appengine/loadBalancer/details/details.html
app/scripts/modules/appengine/loadBalancer/loadBalancer.module.ts
app/scripts/modules/appengine/loadBalancer/transformer.ts
app/scripts/modules/core/modal/wizard/wizardSubFormValidation.service.js

@lwander or @duftler please review. 
Depends on https://github.com/spinnaker/clouddriver/pull/1280

(appengine) update load balancer

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/deployment.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/deployment.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

(kubernetes) deployment object deploy screen

---

app/scripts/modules/amazon/instance/awsInstanceType.service.js
app/scripts/modules/amazon/instance/awsInstanceType.service.spec.js

(aws) assume HVM availability for unknown instance families

---

package.json
start.sh

@anotherchrisberry when I added the `clean-install` script, the `update-node` script didn't actually update node. I'm just reverting that.

fix startup script

---

app/scripts/modules/kubernetes/serverGroup/configure/wizard/deployment.controller.js

(kubernetes) fix loading of deployment warning message

---

app/scripts/modules/kubernetes/securityGroup/configure/wizard/upsert.controller.js

(kubernetes) update lb list when sg account changes

---

app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html

This doesn't address showing at a glance which server groups in a cluster are managed by a deployment.

(kubernetes) surface basic deployment details

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/common/conditionalDescriptionListItem.component.ts
app/scripts/modules/appengine/domain/IAppengineInstance.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/appengine/instance/details/details.html

(appengine) instance details

---

webpack.common.js

This is needed to run Deck with SSL in a container.
@danielpeach @anotherchrisberry @icfantv PTAL

Adds ability to set SSL certs

---

app/scripts/modules/core/healthCounts/healthCounts.directive.js
app/scripts/modules/core/healthCounts/healthCounts.html

(core) surface starting instances in health counter

---

app/scripts/modules/appengine/loadBalancer/details/details.controller.ts
app/scripts/modules/appengine/loadBalancer/details/details.html

(appengine) delete load balancer

---

app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/appengine/instance/details/details.html

Also verified that terminating multiple instances simultaneously works from the UI.

(appengine) terminate instance

---

app/scripts/modules/core/domain/IStrategy.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.controller.ts
app/scripts/modules/core/pipeline/config/copyStage/copyStageCard.component.ts

@anotherchrisberry or @duftler please review.

(core) copy strategy stage

---

app/scripts/modules/google/loadBalancer/configure/network/listeners.html

(gce) Warn about IP change if forwarding rule protocol or port range

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.js
app/scripts/modules/core/delivery/filter/executionFilter.service.js

(core) configure strategy button on execution header

---

app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js

(core) warn user if creating strategy with deploy stage

---

app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/instance/details/instanceDetails.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/google/securityGroup/details/securityGroupDetail.html
app/scripts/modules/google/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

@skim1420 or @danielpeach please review.

(google) Update Logs links to reflect api changes.

---

app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/delivery/filter/executionFilter.service.js
app/scripts/modules/core/delivery/filter/executionFilter.service.spec.js

Also ensuring we include them in the filters on the left

(core) sort strategies after pipelines

---

app/scripts/modules/appengine/domain/IAppengineServerGroup.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html

(appengine) destroy server group

---

app/scripts/modules/core/navigation/urlBuilder.service.ts

(core) fix typos in UrlBuilder

---

app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html

(appengine) enable/disable

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/domain/IAppengineStageScope.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/pipeline/pipeline.module.ts
app/scripts/modules/appengine/pipeline/stages/appengineStage.controller.ts
app/scripts/modules/appengine/pipeline/stages/destroyAsg/appengineDestroyAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/destroyAsg/destroyAsgStage.html
app/scripts/modules/appengine/pipeline/stages/destroyAsg/destroyAsgStepLabel.html
app/scripts/modules/appengine/pipeline/stages/disableAsg/appengineDisableAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/disableAsg/disableAsgStage.html
app/scripts/modules/appengine/pipeline/stages/disableAsg/disableAsgStepLabel.html
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.html
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js

The region is read-only, since there's only one region per App Engine account. Disable looks like Destroy.

(appengine) destroy and disable stages

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/pipeline/stages/findImageFromTags/awsFindImageFromTagsStage.js
app/scripts/modules/amazon/pipeline/stages/findImageFromTags/findImageFromTagsExecutionDetails.controller.js
app/scripts/modules/amazon/pipeline/stages/findImageFromTags/findImageFromTagsExecutionDetails.html
app/scripts/modules/amazon/pipeline/stages/findImageFromTags/findImageFromTagsStage.html
app/scripts/modules/core/pipeline/config/stages/baseProviderStage/baseProviderStage.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsStage.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsStage.module.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/pipeline/stages/bake/bakeExecutionDetails.html
app/scripts/modules/google/pipeline/stages/findImageFromTags/findImageFromTagsExecutionDetails.controller.js
app/scripts/modules/google/pipeline/stages/findImageFromTags/findImageFromTagsExecutionDetails.html
app/scripts/modules/google/pipeline/stages/findImageFromTags/findImageFromTagsStage.html
app/scripts/modules/google/pipeline/stages/findImageFromTags/gceFindImageFromTagsStage.js

(google) Implement findImageFromTags.

(amazon) Make findImageFromTags multi-provider.

---

app/scripts/modules/appengine/pipeline/pipeline.module.ts
app/scripts/modules/appengine/pipeline/stages/appengineStage.controller.ts
app/scripts/modules/appengine/pipeline/stages/destroyAsg/appengineDestroyAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/enableAsg/appengineEnableAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/enableAsg/enableAsgStage.html
app/scripts/modules/appengine/pipeline/stages/enableAsg/enableAsgStepLabel.html

(appengine) enable stage

---

app/scripts/modules/core/delivery/stageFailureMessage/stageFailureMessage.component.ts

@anotherchrisberry or @icfantv please review.

(core) stage failure message null check

---

app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js

* fix build due to errant merge conflict resolution

(appengine): fix build

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/pipeline/stages/tagImage/awsTagImageStage.js
app/scripts/modules/amazon/pipeline/stages/tagImage/tagImageExecutionDetails.controller.js
app/scripts/modules/amazon/pipeline/stages/tagImage/tagImageExecutionDetails.html
app/scripts/modules/amazon/pipeline/stages/tagImage/tagImageStage.html
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageStage.js
app/scripts/modules/core/pipeline/config/stages/tagImage/tagImageStage.module.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/pipeline/stages/tagImage/gceTagImageStage.js
app/scripts/modules/google/pipeline/stages/tagImage/tagImageExecutionDetails.controller.js
app/scripts/modules/google/pipeline/stages/tagImage/tagImageExecutionDetails.html
app/scripts/modules/google/pipeline/stages/tagImage/tagImageStage.html

(google) Implement upsertImageTags.

(amazon) Make upsertImageTags multi-provider.

---

app/scripts/modules/appengine/pipeline/pipeline.module.ts
app/scripts/modules/appengine/pipeline/stages/shrinkCluster/appengineShrinkClusterStage.ts
app/scripts/modules/appengine/pipeline/stages/shrinkCluster/shrinkClusterStage.html

(appengine) shrink cluster stage

---

app/scripts/modules/appengine/pipeline/pipeline.module.ts
app/scripts/modules/appengine/pipeline/stages/startServerGroup/appengineStartServerGroupExecutionDetails.controller.ts
app/scripts/modules/appengine/pipeline/stages/startServerGroup/appengineStartServerGroupStage.ts
app/scripts/modules/appengine/pipeline/stages/startServerGroup/startServerGroupExecutionDetails.html
app/scripts/modules/appengine/pipeline/stages/startServerGroup/startServerGroupStage.html
app/scripts/modules/appengine/pipeline/stages/startServerGroup/startServerGroupStepLabel.html
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/appengineStopServerGroupExecutionDetails.controller.ts
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/appengineStopServerGroupStage.ts
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/stopServerGroupExecutionDetails.html
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/stopServerGroupStage.html
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/stopServerGroupStepLabel.html

(appengine) start and stop stages

---

app/scripts/modules/appengine/domain/IAppengineGitTrigger.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/transformer.ts
app/scripts/modules/core/domain/trigger.ts

@lwander or @duftler please review. Depends on https://github.com/spinnaker/orca/pull/1112

(appengine) dynamic branch from webhook

---

app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts

adds missing semicolon

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/core/loadBalancer/loadBalancer.dataSource.js
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancer.html

Nothing exciting here
@icfantv PTAL

(core) add entityTags to load balancers

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html
app/scripts/modules/kubernetes/proxy/ui.service.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
settings.js

This lets you go from here
to here

(kubernetes) Link into kubeUI over kubeproxy

---

app/scripts/modules/appengine/common/conditionalDescriptionListItem.component.ts
app/scripts/modules/appengine/instance/details/details.html
app/scripts/modules/appengine/serverGroup/details/details.html

Mostly just templates out a server group's scaling policy into the details panel.

(appengine) scaling policy details

---

app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js

fixes trailing spaces

---

app/scripts/modules/core/application/config/applicationAttributes.directive.html
app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/newapplication.html
app/scripts/modules/core/delivery/details/executionDetails.controller.js
app/scripts/modules/core/delivery/details/executionDetails.controller.spec.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/application/applicationAttributes.directive.html
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html

@anotherchrisberry @ajordens @robfletcher PTAL

Adding flag to enable restarting running stages (default disabled)

---

app/scripts/modules/appengine/loadBalancer/transformer.ts
app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/core/loadBalancer/loadBalancer.read.service.ts
app/scripts/modules/kubernetes/loadBalancer/transformer.js
app/scripts/modules/openstack/loadBalancer/transformer.js

ensures provider load balancer transformers return promises

---

Dockerfile
docker/ports.conf.gen
docker/run-apache2.sh
docker/setup-apache2.sh
docker/spinnaker.conf.gen

Switch from serving files via npm to apache in the docker image

---

app/scripts/modules/core/utils/timeFormatters.spec.js

might as well test the actual filter

(core) fix duration filter test

---

app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

* remove CMC field from persisted property stage HTML but set behind the
scenes to the current authenticated user.

(netflix): remove CMC from PP stage

---

app/scripts/modules/appengine/domain/IAppengineTriggers.ts
app/scripts/modules/appengine/domain/index.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/dynamicBranchLabel.component.ts
app/scripts/modules/appengine/serverGroup/transformer.ts
app/scripts/modules/core/domain/trigger.ts

(appengine) jenkins triggers

---

app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js

Optionally show all server groups when performing a rollback

---

app/scripts/modules/netflix/instance/titus/instanceDetails.html

titus host is being used for debugging pids. so restoring this

(titus) restore titus host

---

app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html

Fixes a small set of App Engine rendering issues.
@anotherchrisberry I made two small changes in core files.

(appengine) fixes small ui bugs

---

settings.js

fixes bakery detail url

---

app/scripts/modules/core/authentication/authentication.initializer.service.ts
app/scripts/modules/core/authentication/userMenu/userMenu.directive.html
app/scripts/modules/core/authentication/userMenu/userMenu.directive.js
app/scripts/modules/core/authentication/userMenu/userMenu.directive.spec.js
app/scripts/modules/core/authentication/userMenu/userMenu.less

@anotherchrisberry @icfantv adds log out button.
Looks like this:

(core) adds logout button

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/core/entityTag/clusterTargetBuilder.service.ts
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.titus.controller.js

(titus) add alert/notice support

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.html

This is the UI portion of https://github.com/spinnaker/echo/pull/131, and should not be submitted until that PR goes in.
tag: https://github.com/spinnaker/fiat/issues/134
@anotherchrisberry @danielpeach PTAL

Adds 'Secret' field to GitHub trigger.

---

app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

(gce): Fix floating 'ng-if'.

---

app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.titus.controller.js

(titus) actually allow alerts/notices on titus server groups

---

app/scripts/modules/appengine/domain/IAppengineAccount.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/serverGroupWizard.less
app/scripts/modules/appengine/serverGroup/transformer.ts

(appengine) git credentials in deploy wizard

---

app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts

(appengine) placate linter

---

app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagManager.service.js

Fixes console error that occurs when editing a deploy stage with a tag.

(google) fix for deploy stage with a tag

---

app/scripts/modules/appengine/pipeline/stages/startServerGroup/appengineStartServerGroupStage.ts
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/appengineStopServerGroupStage.ts

(appengine) only show start/stop stages for appengine applications

---

app/scripts/modules/core/serverGroup/details/serverGroupWarningMessage.service.spec.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts
app/scripts/modules/netflix/fastProperties/wizard/createFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts
package.json

* pin angular mocks version to unbreak test build

(netflix): fix spelling/compiler errors

---

app/scripts/modules/appengine/domain/IAppengineLoadBalancer.ts
app/scripts/modules/appengine/domain/IAppengineServerGroup.ts
app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/advancedSettings.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/allocationConfigurationRow.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/basicSettings.component.html
app/scripts/modules/appengine/loadBalancer/configure/wizard/basicSettings.component.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.controller.ts
app/scripts/modules/appengine/loadBalancer/configure/wizard/wizard.html
app/scripts/modules/appengine/loadBalancer/transformer.ts
app/scripts/modules/appengine/pipeline/pipeline.module.ts
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/appengineEditLoadBalancerStage.ts
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/editLoadBalancerStage.html
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/loadBalancerChoice.modal.controller.ts
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/loadBalancerChoice.modal.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
settings.js

@jtk54 or @lwander or @duftler please review.
This is a first pass at an App Engine Edit Load Balancer stage. This PR does not include JS/HTML for the execution details.

(appengine) edit load balancer stage

---

app/scripts/modules/core/utils/timeFormatters.js
app/scripts/modules/netflix/fastProperties/domain/property.domain.ts
app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.ts
app/scripts/modules/netflix/fastProperties/domain/propertyPipelineStage.ts
app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/scope/categoryButtonList.component.html
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.component.spec.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.componet.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts

- Fixes SPIN-2303: bad date time format on FP updated on filed.
- adds previous property list to FP adhoc pipeline so we can rollback to last know good state if a pipeline fails or gets canceled.
- Added a Stack Scope picker.

Fast Property: Fix timestamp, add stack scope, & allow for rollback.

---

app/scripts/modules/amazon/subnet/subnetSelectField.component.html

Bad conversion from directive to component, missed the `readOnly` field...

(netflix) show subnet when editing canary clusters

---

app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html

Closes https://github.com/spinnaker/spinnaker/issues/1263
Also fixes bug where Kubernetes load balancer details panel closes on page load.

(k8s) show ingress hostname

---

app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts

Add App Only scope to the FastProperty Scope Selection.

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

@cfieber @duftler @anotherchrisberry FYI

Slim container & bump spinnaker gradle project version

---

Dockerfile

Copied apache configuration files to allow start up - Have tested and is operating as expected. Image can be tested from docker.io/aarondobbing/deck:latest

Corrected deck Dockerfile

---

app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.ts
app/scripts/modules/core/modal/wizard/v2modalWizard.service.ts
app/scripts/modules/core/modal/wizard/v2wizardPage.component.ts
app/scripts/modules/core/pipeline/config/stages/executionWindows/atlasGraph.component.ts
app/scripts/modules/google/loadBalancer/configure/common/healthCheck.component.ts
app/scripts/modules/google/loadBalancer/configure/http/templates.ts
app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
app/scripts/modules/netflix/fastProperties/domain/acaTaskStageConfigDetails.model.ts
app/scripts/modules/netflix/fastProperties/domain/propertyPipeline.domain.ts
app/scripts/modules/titus/migration/titusMigrationConfig.component.ts

* remove extra cruft added accidentally from last PR.

(all): remove extraneous spaces

---

app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/transformer.ts
app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.ts
app/scripts/modules/core/presentation/autoScroll/autoScroll.directive.ts
app/scripts/modules/google/loadBalancer/configure/choice/gceLoadBalancerChoice.modal.ts
app/scripts/modules/google/loadBalancer/configure/http/templates.ts
app/scripts/modules/google/loadBalancer/configure/internal/gceCreateInternalLoadBalancer.controller.ts
app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyFilter.directive.ts
app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyFilterSearch.component.ts
app/scripts/modules/netflix/fastProperties/domain/acaTaskStageConfigDetails.model.ts
app/scripts/modules/netflix/fastProperties/domain/canary.domain.ts
app/scripts/modules/netflix/fastProperties/domain/manualJudgementStage.ts
app/scripts/modules/netflix/fastProperties/domain/property.domain.ts
app/scripts/modules/netflix/fastProperties/domain/propertyPipeline.domain.ts
app/scripts/modules/netflix/fastProperties/domain/propertyStrategy.domain.ts

* removing extra noise from ng2 migration PR

(all): remove string types from variables

---

app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/google/loadBalancer/configure/http/templates.ts
app/scripts/modules/netflix/fastProperties/domain/acaTaskStageConfigDetails.model.ts

* remove extra noise on ng2 PR

(all): remove unnessary string types

---

app/scripts/modules/google/loadBalancer/loadBalancer.setTransformer.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts

(multiple): more code cleanup

---

app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

(google) fix exposed html

---

app/scripts/modules/amazon/instance/details/instanceDetails.html

Cherry-picks https://github.com/spinnaker/deck/pull/3291.

Fix bad if statement

---

app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/appengineEditLoadBalancerExecutionDetails.controller.ts
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/appengineEditLoadBalancerStage.ts
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/editLoadBalancerExecutionDetails.html

@lwander or @duftler or @jtk54 please review.

(appengine) edit load balancer execution details

---

cloudbuild.yaml

GCB tag latest

---

app/scripts/modules/azure/securityGroup/clone/cloneSecurityGroup.html
app/scripts/modules/azure/securityGroup/configure/editSecurityGroup.html

The original modal wizard directives are being killed.  These files where converted to the V2ModalWizard.
Please test and merge this PR as soon as you can.
@spinnaker/microsoft

(azure) Convert to V2ModalWizard

---

build.gradle

FYI @anotherchrisberry @danielpeach.

chore(gradle): Bumps spinnaker-gradle-project version.

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html
app/scripts/modules/core/application/nav/applicationNav.component.js
app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/entityTag/dataSourceAlerts.component.ts
app/scripts/modules/core/entityTag/entityTags.help.ts
app/scripts/modules/core/entityTag/entityUiTags.component.less
app/scripts/modules/core/entityTag/entityUiTags.component.ts
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancer.html
app/scripts/modules/core/securityGroup/securityGroup.html
app/scripts/modules/core/serverGroup/serverGroup.directive.html
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html

* changing notices to flag icons, alerts to the yellow-orange color
* adding analytics to tag hover events

(core) add analytics to alerts/notices, update icons

---

app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/transformer.ts

Depends on https://github.com/spinnaker/clouddriver/pull/1446

(appengine) switched from app.yaml path to general config filepaths

---

app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/serverGroup/details/details.html

https://github.com/spinnaker/spinnaker/issues/1436

(kubernetes) add node-selector

---

app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.html
app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.js
app/scripts/modules/core/authentication/authentication.initializer.service.ts
app/scripts/modules/core/authentication/authentication.service.spec.ts
app/scripts/modules/core/authentication/authentication.service.ts

Allows the possibility for users to check their own roles so it's easier to use the `groupMembership` feature of FIAT.
PTAL @danielpeach @anotherchrisberry @icfantv @jrsquared 
Thanks
Some screenshots:

Add feature for user to check their own roles

---

app/scripts/modules/appengine/common/appengineHealth.ts
app/scripts/modules/appengine/domain/IAppengineStageScope.ts
app/scripts/modules/appengine/pipeline/stages/appengineStage.controller.ts
app/scripts/modules/appengine/pipeline/stages/disableAsg/appengineDisableAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/disableAsg/disableAsgStage.html
app/scripts/modules/appengine/pipeline/stages/enableAsg/appengineEnableAsgStage.ts
app/scripts/modules/appengine/pipeline/stages/enableAsg/enableAsgStage.html
app/scripts/modules/appengine/pipeline/stages/shrinkCluster/shrinkClusterStage.html
app/scripts/modules/appengine/pipeline/stages/startServerGroup/appengineStartServerGroupStage.ts
app/scripts/modules/appengine/pipeline/stages/startServerGroup/startServerGroupStage.html
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/appengineStopServerGroupStage.ts
app/scripts/modules/appengine/pipeline/stages/stopServerGroup/stopServerGroupStage.html
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/transformer.ts

(appengine) surface platform health properly

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@jtk54 or @lwander or @duftler please review.

fix(gce) specify protocol on load balancer links based on ports

---

app/scripts/modules/netflix/fastProperties/wizard/propertyPipelineBuilder.service.ts

Adding pipeline name for Fast Property executions.

---

halconfig/settings.js

Updating hal settings.js to support templating of openstack variables
@lwander PTAL

adding openstack settings for halyard

---

app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.html
app/scripts/modules/netflix/tableau/tableau.states.ts

I broke this when I converted the data source over to TS
Also tweaking the text in the config section to align with the label (data source -> feature)

fix(netflix): restore tableau data source

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.html
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/utils/renderIfFeature.directive.ts
app/scripts/modules/core/utils/utils.module.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/google/securityGroup/details/securityGroupDetail.html
app/scripts/modules/google/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

@icfantv @anotherchrisberry please review.
- Renders AWS server group entity tags outside of Netflix mode.
- Adds feature flags to all the entity tag components.

feat(aws,gce) render entity tags

---

app/scripts/modules/appengine/domain/IAppengineLoadBalancer.ts
app/scripts/modules/core/core.module.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/help/helpField.component.ts
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.html
app/scripts/modules/core/pipeline/config/stages/optionalStage/optionalStage.directive.html
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/widgets/scopeClusterSelector.directive.html
app/scripts/modules/core/widgets/scopeClusterSelector.directive.js
app/scripts/modules/netflix/canary/canaryAnalysisNameSelector.directive.html
app/scripts/modules/netflix/fastProperties/domain/scope.domain.spec.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyStrategy/acaStrategyForm.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canary.less
app/scripts/modules/netflix/pipeline/stage/canary/canaryScore.component.ts
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js
package.json
settings.js

* update canary UI to have a more sensible layout
* fixed various linting issues.
* added debug config option for turning off extraneous console noise
* turn of auto reload of application via WDS.

 (netflix): update canary UI

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.component.ts

Since I'm going on vacation tomorrow and won't be online for two weeks, this is the best time to introduce rendering optimizations in a very complex section of the code that very few people understand.
Instead of re-rendering the entire graph when a user clicks on a stage in the graph, just reset the styles of the link lines and the node itself.
There's a negligible performance improvement on smaller (< 30 stages) pipelines, but a very noticeable improvement on larger pipelines.

perf(pipelines) do not re-render entire graph when view state changes

---

app/scripts/modules/core/domain/serverGroup.ts
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/securityGroup/clone/cloneSecurityGroup.controller.js
app/scripts/modules/google/securityGroup/clone/cloneSecurityGroup.html
app/scripts/modules/google/securityGroup/configure/ConfigSecurityGroupMixin.controller.js
app/scripts/modules/google/securityGroup/configure/createSecurityGroup.controller.js
app/scripts/modules/google/securityGroup/configure/createSecurityGroup.html
app/scripts/modules/google/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/google/securityGroup/configure/createSecurityGroupProperties.html
app/scripts/modules/google/securityGroup/configure/createSecurityGroupSourceFilters.html
app/scripts/modules/google/securityGroup/configure/createSecurityGroupTargets.html
app/scripts/modules/google/securityGroup/configure/editSecurityGroup.controller.js
app/scripts/modules/google/securityGroup/configure/editSecurityGroup.html
app/scripts/modules/google/securityGroup/configure/securityGroup.configure.less
app/scripts/modules/google/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/google/securityGroup/details/securityGroupDetail.html
app/scripts/modules/google/securityGroup/securityGroupHelpText.service.spec.ts
app/scripts/modules/google/securityGroup/securityGroupHelpText.service.ts

Closes https://github.com/spinnaker/spinnaker/issues/1448

feat(gce) adds support for firewall rule source and target tags

---

app/scripts/modules/netflix/availability/availability.directive.html
app/scripts/modules/netflix/availability/availability.directive.ts
app/scripts/modules/netflix/availability/availability.donut.component.ts
app/scripts/modules/netflix/availability/availability.donut.html
app/scripts/modules/netflix/availability/availability.less
app/scripts/modules/netflix/availability/availability.read.service.ts
app/scripts/modules/netflix/availability/availability.trend.component.ts
app/scripts/modules/netflix/availability/availability.trend.html
app/scripts/modules/netflix/availability/availability.trend.popover.html
app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/templateOverride/spinnakerHeader.html
package.json

DO NOT MERGE YET
Just want to get @spinnaker/netflix-reviewers eyes on it before the other backend pieces are in place.

feat(netflix): Availability Gauges

---

app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.html

Revert "fix(core) do not allow free-form text in group membership config"

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.component.ts

* sanitize the stage name in the pipeline graph component to remove XSS
issue.

fix(pipelines): sanitize stage name

---

app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts
app/scripts/modules/netflix/fastProperties/view/fastProperties.controller.js
app/scripts/modules/netflix/fastProperties/view/fastPropertyFilterSearch.component.ts
app/scripts/modules/netflix/fastProperties/view/properties.html

Also fixes SPIN-2429: Pressing 'enter' on the filtering field brings up the "Create New Property" modal.

(netflix) Allow Fast Property substring filtering

---

cloudbuild.yaml

fix(container): Extends timeout to 15m in cloudbuild.yaml file

---

app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js

fix(gce) prevents race condition in how credentials are set on command

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

* remove org validation requirement for docker triggers.

fix(core): make org not required in docker trigger

---

app/scripts/app.module.ts
app/scripts/modules/core/help/helpField.component.ts
app/scripts/modules/core/help/index.ts
app/scripts/modules/core/index.ts
app/scripts/modules/index.ts
tslint.json

* add code to make the help field component work in ng2 components.
* create framework for wiring in upgraded ng1 components.

chore(core/help): make help field work in ng2

---

app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.html
app/scripts/modules/kubernetes/annotation/annotationConfigurer.component.ts
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.html

@dennismartensson FYI
- Cleans up some of the Typescript style.
- Prevents submitting the server group dialogue if any of the key/value pairs are empty.

fix(kubernetes) allows deletion of annotations in deploy stage config

---

app/scripts/modules/amazon/serverGroup/configure/wizard/templateSelection/deployInitializerCtrl.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingProcesses/modifyScalingProcesses.controller.spec.js
app/scripts/modules/azure/serverGroup/configure/wizard/deployInitializerCtrl.spec.js
app/scripts/modules/core/delivery/create/createPipelineModal.controller.spec.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/pipeline/config/actions/rename/renamePipelineModal.controller.spec.js
app/scripts/modules/netflix/instance/aws/netflixAwsInstanceDetails.controller.js
app/scripts/modules/netflix/instance/titus/netflixTitusInstanceDetails.controller.js

* remove unused lodash properties that weren't removed when the lodash
service was removed.

chore(various): cleanup old lodash props

---

app/scripts/modules/google/instance/gceInstanceType.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js

BREAKING CHANGE: (Only for GCE). This PR depends on https://github.com/spinnaker/clouddriver/pull/1522.

feat(gce): fetch disk defaults from clouddriver.

---

app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.html
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.html
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.html
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.spec.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.ts
app/scripts/modules/core/widgets/cluster/clusterMatches.component.ts

* add cluster match functionality/column to chaos monkey config section
in application config.

feat(core/monkey): add cluster match

---

app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.spec.ts
app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.ts
app/scripts/modules/netflix/fastProperties/domain/propertyPipelineStage.ts
app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts
app/scripts/modules/netflix/fastProperties/wizard/deleteFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyReview/propertyReview.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeReadOnly.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeReadOnly.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeUpdatable.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyStrategy/propertyStrategy.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyStrategy/propertyStrategy.component.ts

When creating a Fast Property the user can select multiple scopes and the
property will created for each scope. This will create a Persisted Property stage
for each scope.

(feat, netfilx) Create Fast Property with mutiple scopes

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/container/lifecycleHook.component.html
app/scripts/modules/kubernetes/container/lifecycleHook.component.ts
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/details.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/lifecycleHookDetails.component.ts

Closes https://github.com/spinnaker/spinnaker/issues/1216
I'm going to make the rest of the container details have the same style, but that's for a different PR.

feat(k8s) lifecycle hooks

---

app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js

Solves the backend service part of this bug: https://github.com/spinnaker/spinnaker/issues/1516
@jtk54 or @duftler please review.

fix(gce): render backend services in edit deploy stage

---

app/scripts/modules/core/instance/instanceType.service.ts
app/scripts/modules/core/instance/instanceTypeService.spec.ts
app/scripts/modules/google/instance/gceInstanceType.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js

Closes https://github.com/spinnaker/spinnaker/issues/1516
@anotherchrisberry or @icfantv - this touches the core instance type service.

fix(gce): populate custom instance types in edit deploy stage

---

app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.ts
app/scripts/modules/netflix/fastProperties/view/fastPropertyDetails.controller.ts
app/scripts/modules/netflix/fastProperties/view/fastPropertyDetails.html
app/scripts/modules/netflix/fastProperties/wizard/cloneFastPropertyToNewScopeWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/cloneFastPropertyToNewScopeWizard.html
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.html

Adds the ability to select a FP and then clone it to one or more new scopes.
This will create a new Create Persisted Property stage for each new scope that is
chosen in the clone wizard.  The Property details will not be editable during this action

(netflix) Clone Property with new scope.

---

app/scripts/modules/core/application/application.html
app/scripts/modules/core/application/application.less
app/scripts/modules/core/application/config/applicationAttributes.directive.html
app/scripts/modules/core/application/config/applicationCacheManagement.directive.html
app/scripts/modules/core/application/config/applicationConfig.view.html
app/scripts/modules/core/application/config/applicationNotifications.directive.html
app/scripts/modules/core/application/config/applicationSnapshotSection.component.html
app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.html
app/scripts/modules/core/application/config/deleteApplicationSection.directive.html
app/scripts/modules/core/application/config/links/applicationLinks.component.html
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.html
app/scripts/modules/core/application/nav/applicationNav.component.less
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfig.component.html
app/scripts/modules/core/insight/insight.html
app/scripts/modules/core/modal/wizard/modalWizard.less
app/scripts/modules/core/modal/wizard/v2modalWizard.component.html
app/scripts/modules/core/modal/wizard/v2modalWizard.component.ts
app/scripts/modules/core/pipeline/config/triggers/trigger.html
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/presentation/navigation/pageNavigation.less
app/scripts/modules/netflix/application/applicationAttributes.directive.html
app/scripts/modules/netflix/application/applicationConfig.html
app/scripts/modules/netflix/fastProperties/mainApplicationProperties.html
app/scripts/modules/titus/migration/titusMigrationConfig.component.html

It looks worse than it is (mostly indent changes - use the `?w=1` url trick to see the actual diff).
* fixes double scrollbars on app config page
* handles application header responsiveness for very large application names

fix(ui refresh): grab bag of UI tweaks

---

app/scripts/modules/netflix/fastProperties/scope/categoryButtonList.component.html
app/scripts/modules/netflix/fastProperties/scope/categoryButtonList.component.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.html

This was working at one point.  Something broke.  This fixes it.

(netflix) Fix option to show and select FP Scopes with zero instance counts

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js

@jtk54 or @duftler please review.

fix(gce): dedupe backend service health checks

---

app/scripts/modules/core/cache/cacheInitializer.service.spec.ts
app/scripts/modules/core/cache/infrastructureCacheConfig.ts
app/scripts/modules/google/address/address.reader.ts
app/scripts/modules/google/cache/cacheConfigurer.service.js

@jtk54 or @duftler please review.

feat(gce): adds address reader service

---

app/scripts/modules/netflix/instance/titus/instanceDetails.html

Titus eureka block was out of date, this brings it up to date with aws provider

feat(titus): eureka support should be same as other providers

---

app/scripts/modules/appengine/domain/IAppengineLoadBalancer.ts
app/scripts/modules/appengine/loadBalancer/details/details.controller.ts
app/scripts/modules/appengine/loadBalancer/details/details.html

feat(appengine): render dispatch rules

---

app/scripts/modules/core/entityTag/entityTags.read.service.ts

Just noticed that we sometimes send the same `entityId` multiple times when fetching tags if a thing has the same name in multiple accounts/regions. This probably doesn't make much, if any, actual difference, but it might prevent us from performing an extra fetch periodically (since we collate them into small enough groups to avoid blowing out the URL max size on the server).

refactor(tags): dedupe tagIds before fetching

---

app/scripts/modules/appengine/appengine.module.ts
app/scripts/modules/appengine/validation/applicationName.validator.ts

@lwander or @duftler or @jtk54 please review.

feat(appengine): application name validator

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/core.module.js
app/scripts/modules/core/diffs/changes.html
app/scripts/modules/core/diffs/commitHistory.component.ts
app/scripts/modules/core/diffs/index.ts
app/scripts/modules/core/diffs/jarDiff.component.ts
app/scripts/modules/core/diffs/viewChangesLink.component.ts
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.controller.spec.js
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.html
app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

* add a new item to server group info section that displays a modal
containing all the code and/or JAR changes from the pipeline that
deployed to the selected ASG.
* updated the deploy stage pipeline view to combine commit and JAR
changes to utilize same dialog for viewing the diffs.

feat(aws/netflix): add diff view to ASG details

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts
app/scripts/modules/core/pipeline/config/stages/webhook/webhookExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.html
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.module.ts
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.ts

This PR is the implementation of the UI of the webhook stage discussed in https://github.com/spinnaker/spinnaker/issues/1512
This is a screenshot of the execution details view:
And the stage config:
@spinnaker/reviewers PTAL

feat(stages/webhook) Webhook stage

---

app/scripts/modules/kubernetes/kubernetes.settings.ts
app/scripts/modules/kubernetes/loadBalancer/details/details.controller.js
app/scripts/modules/kubernetes/loadBalancer/details/details.html
halconfig/settings.js
settings.js

Closes https://github.com/spinnaker/spinnaker/issues/1445

feat(kubernetes): makes internal DNS name configurable

---

app/scripts/modules/core/pipeline/config/pipelineConfigurer.html

@anotherchrisberry or @jrsquared or @icfantv please review.

fix(core): fix pipeline stage navigation

---

app/scripts/modules/core/modal/buttons/submitButton.component.ts

fix(core): prevent submit button from auto-clicking.

---

app/scripts/modules/kubernetes/loadBalancer/details/details.html

fix(kubernetes): fixes load balancer annotations details view

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

feat(netflix): include documentation link in canary description

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.component.ts
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.component.html
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.service.ts

Before (current):
After (PR):
@jrsquared PTAL, I think you wrote the graphing code

fix(pipelines): prevent overlapping graph lines

---

app/scripts/modules/core/cluster/cluster.service.spec.ts
app/scripts/modules/core/cluster/cluster.service.ts

For smaller apps, we want to automatically convert cluster filters to a usable state, if supplied.

fix(clusters): convert on-demand params to filter params for small apps

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
app/scripts/modules/amazon/serverGroup/details/advancedSettings/editAsgAdvancedSettings.modal.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

See also https://github.com/spinnaker/clouddriver/pull/1563.
Close spinnaker/spinnaker#1548.

feat(aws/netflix): Add UX for Auto Scaling Group Metrics

---

app/scripts/modules/netflix/fastProperties/view/fastPropertyTable.directive.js

These rows are clickable, just need to change the cursor to indicate they are.

fix(netflix/fp): add clickable cursor to FP row

---

app/scripts/modules/core/domain/ITrigger.ts
app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfig.validator.ts
app/scripts/modules/netflix/ci/ci.dataSource.js
app/scripts/modules/netflix/ci/ci.module.js
app/scripts/modules/netflix/ci/detail/detail.controller.js
app/scripts/modules/netflix/ci/detail/detailTab/detailTab.controller.js
app/scripts/modules/netflix/ci/services/build.read.service.js
app/scripts/modules/netflix/ci/services/scm.read.service.ts
app/scripts/modules/netflix/ci/trigger/ci.trigger.handler.component.html
app/scripts/modules/netflix/ci/trigger/ci.trigger.handler.component.ts
app/scripts/modules/netflix/ci/trigger/manualExecution.handler.ts
app/scripts/modules/netflix/ci/trigger/selectorTemplate.html

Lets users pick a specific commit to use when running a pipeline with a Git trigger.
Feature flagged to only work in Netflix mode, since the endpoints are only available in our internal version of Gate.
@jrsquared or @christopherthielen PTAL
cc @sghill

feat(netflix): allow user to pick commit for git trigger

---

app/scripts/modules/index.ts
app/scripts/modules/netflix/application/applicationAttributes.directive.html
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html
app/scripts/modules/netflix/index.ts
app/scripts/modules/netflix/pagerDuty/index.ts
app/scripts/modules/netflix/pagerDuty/pagerDuty.read.service.ts
app/scripts/modules/netflix/pagerDuty/pagerDutySelectField.component.ts
app/scripts/modules/netflix/pagerDuty/pagerDutyTag.component.spec.ts
app/scripts/modules/netflix/pagerDuty/pagerDutyTag.component.ts

We're bailing out of the ng1-ng2 hybrid app and going to try an ng1-react hybrid app.
I'll be submitting a number of PRs today and tomorrow, converting (or reverting) the ng2 bits back to ng1.
@jrsquared PTAL
@icfantv FYI

chore(netflix): revert pager duty modules to ng1

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/filter/replace.filter.ts

@anotherchrisberry please review. 
Closes https://github.com/spinnaker/spinnaker/issues/1559

feat(core) adds replace filter

---

app/scripts/modules/core/projects/project.less

fix(core): Selected section arrow was offset

---

app/scripts/modules/core/core.module.js

fix(core): allow cancel execution modal to open

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html

fix(aws): prevents NPE in aws view changes link

---

app/scripts/modules/netflix/help/netflixHelpContents.registry.ts
app/scripts/modules/netflix/netflix.module.ts

* convert netflix help module to typescript.

refactor(netflix): convert help module to typescript

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.azure.controller.js
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.html
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.cf.controller.js
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/domain/taskStep.ts
app/scripts/modules/core/serverGroup/details/runningTasks.component.ts
app/scripts/modules/core/task/platformHealthOverrideMessage.component.ts
app/scripts/modules/core/task/platformHealthOverrideMessage.html
app/scripts/modules/core/task/task.module.js
app/scripts/modules/core/task/task.read.service.ts
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html

@anotherchrisberry or @icfantv please review.

feat(core): show hint if wait for up instances task is not completing

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/pipeline/stages/bake/bakeStage.html
app/scripts/modules/core/help/helpContents.js

This flag doesn't do anything any more.

fix(aws/bake) - remove enhanced networking bake flag

---

app/scripts/modules/netflix/fastProperties/view/fastPropertyDetails.html

fix(netflix): fast property label typo

---

app/scripts/modules/amazon/instance/awsInstanceType.service.js

@spinnaker/netflix-reviewers FYI

feat(aws): Changing memory instance type category to r4 family

---

app/scripts/modules/core/pipeline/config/triggers/git/git.trigger.ts

@gardleopard Please give this a shot
fyi @anotherchrisberry

fix(gitTrigger): Add back fiatEnabled check for git triggers

---

app/scripts/modules/google/pipeline/stages/bake/gceBakeStage.js

fix(gce): fixes bake stage validation and execution details

---

app/scripts/modules/core/api/api.service.ts
app/scripts/modules/core/config/settings.ts
app/scripts/modules/core/core.module.js
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/pipeline/config/templates/ConfigurePipelineTemplateModal.tsx
app/scripts/modules/core/pipeline/config/templates/configurePipelineTemplateModal.component.ts
app/scripts/modules/core/pipeline/config/templates/pipelineTemplate.service.ts
app/scripts/modules/core/pipeline/config/templates/template.json

@anotherchrisberry or @jrsquared please review - just some boilerplate for working on DCD UI

feat(dcd): pipeline template boilerplate

---

app/scripts/modules/openstack/common/cacheBackedMultiSelectField.directive.js
app/scripts/modules/openstack/common/selectField.component.js
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js

- unable to destroy server group
- infrastructureCaches error in console
- multiselect drop-downs not working

Fix UI bugs for openstack integration

---

app/scripts/modules/core/account/accountSelectField.directive.js

Unintentionally regressed in spinnaker/deck#3608

fix(*): Fix single select account drop-down

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

@lwander or @ethanfrogers please review.
Yesterday's fix (https://github.com/spinnaker/deck/pull/3602) wasn't quite right.

fix(kubernetes): fixes container copying in server group dialogue

---

app/scripts/modules/kubernetes/image/image.reader.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

fix(kubernetes): adds retry logic to kubernetes image reader

---

app/scripts/modules/core/bootstrap/spinnakerHeader.html
app/scripts/modules/core/config/settings.ts
app/scripts/modules/core/whatsNew/whatsNew.read.service.spec.ts
app/scripts/modules/core/whatsNew/whatsNew.read.service.ts
halconfig/settings.js

@anotherchrisberry or @jrsquared please review.
@lwander FYI

feat(core): render changelog if given in settings.js

---

app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
app/scripts/modules/openstack/subnet/subnet.renderer.js

Fix issues with subnet selection in deploy pipeline stage for openstack

Fix issues with subnet selection in deploy pipeline stage for openstack

---

app/scripts/modules/core/loadBalancer/LoadBalancersTag.tsx

fix(loadbalancers): fix click handling on load balancers tag

---

app/scripts/modules/core/account/accountSelectField.directive.js
app/scripts/modules/core/account/accountSelectField.directive.spec.js

@ajordens thanks for your fix in #3608 and #3609! Sorry about that :/ I have a minor update to optimize the code and added some tests to prevent future regressions
I verified this fix on the edit application dialog and on some Azure dialogs for creating resources (which prompted my original change) and it looks good.
@anotherchrisberry PTAL as well

fix(*): Optimize selected account validation

---

app/scripts/modules/core/serverGroup/serverGroup.component.html
app/scripts/modules/core/serverGroup/serverGroup.component.ts

fixes a minor regression from TS conversion

fix(servergroups): highlight selected server group

---

app/scripts/modules/core/modal/wizard/v2modalWizard.component.html
app/scripts/modules/core/utils/utils.module.js
app/scripts/modules/core/utils/waypoints/waypoint.directive.js
app/scripts/modules/core/utils/waypoints/waypoint.service.ts

fix(core): Fix scrolling in modal highlighting navigation

---

app/scripts/modules/core/utils/stickyHeader/stickyHeader.less

fix(headers): restore sticky header styles

---

app/scripts/modules/core/pipeline/config/preconditions/preconditionList.directive.html
app/scripts/modules/core/pipeline/config/preconditions/preconditionList.directive.js
app/scripts/modules/core/pipeline/config/preconditions/preconditionList.directive.less

@anotherchrisberry or @jrsquared

fix(core): prevent overflow in check preconditions stage config

---

app/scripts/modules/core/account/accountTag.less
app/scripts/modules/core/delivery/executionGroup/executionGroup.less

Missed these two cases earlier

fix(core): hide empty account tag, show tags inline in header

---

app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts

fix(gce): send `name` in SSL upsert payload

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/history/recentHistory.service.ts
app/scripts/modules/core/navigation/state.provider.ts

The visualizer can be useful to diagnose problems.  By adding a url trigger, we can share links with the visualizer enabled.

feat(core/visualizer): Allow visualizer toggle from URL query param `?vis=true`

---

app/scripts/modules/core/cluster/all.html
app/scripts/modules/core/cluster/filter/clusterFilter.component.ts
app/scripts/modules/core/delivery/executionGroup/ExecutionGroups.tsx
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/delivery/filter/executionFilter.model.ts
app/scripts/modules/core/delivery/filter/executionFilter.service.ts
app/scripts/modules/core/filterModel/FilterTags.tsx
app/scripts/modules/core/filterModel/filter.model.service.js
app/scripts/modules/core/filterModel/filterTags.component.ts
app/scripts/modules/core/loadBalancer/LoadBalancers.tsx
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.component.ts
app/scripts/modules/core/securityGroup/all.html
app/scripts/modules/core/securityGroup/filter/securityGroup.filter.component.ts
app/scripts/modules/core/securityGroup/filter/securityGroupFilter.model.ts

* react2angular instead of angular2react
* standardizing on `groupsUpdated` from the *FilterService over `groupsUpdatedStream`

refactor(core): convert filter tags to React

---

app/scripts/modules/core/cluster/filter/clusterFilter.component.ts
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/filterModel/FilterTags.tsx
app/scripts/modules/core/loadBalancer/LoadBalancers.tsx
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.component.ts
app/scripts/modules/core/securityGroup/filter/securityGroup.filter.component.ts

Addressing @jrsquared 's comments from a prior PR

refactor(filtertags): address PR comments

---

app/scripts/modules/core/modal/buttons/SubmitButton.tsx

fix(core): fix reference to ButtonBusyIndicator

---

app/scripts/modules/core/modal/modalPage.directive.js
app/scripts/modules/core/search/global/globalSearch.controller.js
app/scripts/modules/core/search/global/globalSearch.directive.js
app/scripts/modules/core/search/global/globalSearch.module.js
app/scripts/modules/core/utils/jQuery.js
app/scripts/modules/core/utils/utils.module.js

just cleaning up some cruft, also fyi you need to require jquery in js files, `import * as $ from 'jquery'` doesn't work...

fix(search): require jquery instead of importing it

---

app/scripts/modules/oracle/instance/details/instance.details.controller.js
app/scripts/modules/oracle/instance/details/instanceDetails.html
app/scripts/modules/oracle/oraclebmcs.module.js

Adds basic instance details information to server groups view.

feat(provider/oraclebmcs): Add instance details to server groups

---

app/scripts/modules/core/src/cluster/ClusterSearchResultFormatter.ts

fix(clusters): fix search result heading for clusters

---

app/scripts/modules/docker/package.json
app/scripts/modules/docker/src/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/docker/tsconfig.json
app/scripts/modules/docker/webpack.config.js

refactor(docker): enable library build of docker module

---

app/scripts/modules/core/src/serverGroup/serverGroup.module.js

fix(aws): restore scaling activities link

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/core/src/delivery/create/CreatePipelineModal.tsx
app/scripts/modules/core/src/delivery/executionGroup/ExecutionGroup.tsx
app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancer.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancerPod.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancerServerGroup.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancers.tsx
app/scripts/modules/core/src/modal/buttons/SubmitButton.tsx
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
app/scripts/modules/core/src/pipeline/config/templates/VariableMetadataHelpField.tsx
app/scripts/modules/core/src/reactShims/index.ts
app/scripts/modules/core/src/reactShims/ngReact.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/core/src/reactShims/react.module.ts
app/scripts/modules/netflix/fastProperties/view/history/FastPropertyHistory.tsx

@jrsquared less offensive to you?

chore(core): move angular2react components to separate class

---

app/scripts/modules/oracle/helpContents/oracleHelpContents.ts
app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/stages/destroyAsg/destroyAsgStage.html
app/scripts/modules/oracle/pipeline/stages/destroyAsg/destroyAsgStage.js
app/scripts/modules/oracle/pipeline/stages/destroyAsg/destroyAsgStepLabel.html

A small change adding the destroy server group pipeline stage for Oracle BMCS.

feat(provider/oraclebmcs): Add destroy server group stage

---

app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.html
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts

also stretching the input to full width

fix(netflix): handle FP category result with no stack/cluster

---

app/scripts/modules/core/src/core.module.js
app/scripts/modules/core/src/entityTag/entityTags.module.ts

Also fell out in that large refactor the other day

fix(core): add entityTags module

---

app/scripts/modules/core/src/modal/modals.less

Cleaning up old styles from v1 modal wizard; making section heading styles consistent (dark text, light blue background)

fix(modals): fix style on modal headings

---

app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/instance/details/instanceDetails.html

fix(gce): prevent instance register for non-network load balancers

---

app/scripts/modules/amazon/src/loadBalancer/configure/securityGroups.html

fix(amazon): fix ng-if in security group refresh dom element

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

chore(core/amazon): rev package.json versions

---

app/scripts/modules/core/src/pipeline/config/stages/stage.html

feat(pipelines): auto-focus stage type field on new stage

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/stages/scaleDownCluster/scaleDownClusterExecutionDetails.html
app/scripts/modules/oracle/pipeline/stages/scaleDownCluster/scaleDownClusterStage.html
app/scripts/modules/oracle/pipeline/stages/scaleDownCluster/scaleDownClusterStage.js

Implement scale down cluster pipeline stage for Oracle BMCS provider.
Once our initial code is merged in, I'll refactor it all to TypeScript.

feat(provider/oraclebmcs): Implement scale down cluster pipeline stage

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/oracle/pipeline/stages/bake/bakeExecutionDetails.html
app/scripts/modules/oracle/pipeline/stages/bake/bakeStage.html
app/scripts/modules/oracle/pipeline/stages/bake/bakeStage.js

Implement BMCS bake stage pipeline step

feat(provider/oraclebmcs): Implement bake stage pipeline

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/stages/shrinkCluster/shrinkClusterStage.html
app/scripts/modules/oracle/pipeline/stages/shrinkCluster/shrinkClusterStage.js

Implements the shrink cluster stage for Oracle BMCS provider.

feat(provider/oraclebmcs): Implement shrink cluster pipeline stage

---

app/scripts/modules/core/package.json

chore(core): bump core package version

---

app/scripts/modules/core/src/delivery/details/singleExecutionDetails.html

feat(core): add a button to navigate to the pipeline configuration from executions view

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/stages/disableAsg/disableAsgStage.html
app/scripts/modules/oracle/pipeline/stages/disableAsg/disableAsgStage.js
app/scripts/modules/oracle/pipeline/stages/disableAsg/disableAsgStepLabel.html

Adds the ability to disable a server group as a pipeline stage.

feat(provider/oraclebmcs): Implement disable ASG pipeline stage

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

chore(core): rev version

---

app/scripts/modules/core/package.json

chore(core): rev core version

---

app/scripts/modules/core/package.json

chore(core): rev package

---

app/scripts/modules/core/src/api/api.service.ts

feat(core): Common ratelimit http header

---

app/scripts/modules/core/package.json

chore(core): rev version to 0.0.14

---

app/scripts/modules/core/src/pipeline/config/stages/optionalStage/optionalStage.directive.html
app/scripts/modules/core/src/widgets/spelText/spelText.decorator.js

Should not be merged until spinnaker.github.io becomes spinnaker.io.

chore(expression-docs): change expression docs link

---

app/scripts/modules/core/src/entityTag/notifications/GroupedNotificationList.tsx
app/scripts/modules/core/src/entityTag/notifications/NotificationList.tsx
app/scripts/modules/core/src/entityTag/notifications/notifications.popover.less
app/scripts/modules/core/src/presentation/Markdown.tsx
app/scripts/modules/core/src/presentation/index.ts

Add `<Markdown message={markdownstring} />` component

feat(core/entityTag): Render tagline for alerts, if present

---

app/scripts/modules/core/src/delivery/create/CreatePipelineModal.tsx
app/scripts/modules/core/src/delivery/create/ManagedTemplateSelector.tsx
app/scripts/modules/core/src/delivery/create/TemplateDescription.less
app/scripts/modules/core/src/delivery/create/TemplateDescription.tsx
app/scripts/modules/core/src/delivery/create/createPipelineModal.less
app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigView.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigView.js
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/src/pipeline/config/services/pipelineConfig.service.ts
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.spec.ts
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.ts
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.html
app/scripts/modules/core/src/pipeline/config/templates/pipelineTemplate.service.ts
app/scripts/modules/core/src/pipeline/config/templates/validators/list.validator.ts
settings.js

@jrsquared or @anotherchrisberry please review.
@robzienert fyi

feat(pipeline-templates): config view

---

app/scripts/modules/docker/src/pipeline/stages/bake/bakeStage.html

feat(bake/docker) add rebake flag to docker bakes

---

app/scripts/modules/core/package.json

chore(core) rev package to 0.0.17

---

app/scripts/modules/amazon/package.json
app/scripts/modules/docker/package.json

chore(docker): rev package to 0.0.3

---

app/scripts/modules/kubernetes/container/environmentVariables.component.html
app/scripts/modules/kubernetes/container/environmentVariables.component.js

Closes https://github.com/spinnaker/spinnaker/issues/1732

feat(provider/kubenretes): Support downward API env vars

---

app/scripts/modules/core/src/application/applications.controller.js
app/scripts/modules/core/src/application/applications.html

As much as we neglect the applications list view, it's pretty useful and we might as well make it slightly more useful by including the descriptions people enter and making them filterable.

feat(core): include description in applications list view

---

app/scripts/modules/core/src/loadBalancer/filter/loadBalancer.filter.service.ts

If multiple exist, append the type to the header/key of the load balancer pod.
foo-load-balancer (classic)
foo-load-balancer (application)

fix(provider/amazon): Fix key collisions when an ALB and classic LB existed with the same name

---

app/scripts/modules/core/src/pipeline/config/templates/TemplatePlanErrors.tsx
app/scripts/modules/core/src/pipeline/config/templates/Variable.spec.tsx
app/scripts/modules/core/src/pipeline/config/templates/VariableMetadataHelpField.tsx
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.ts
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.html
app/scripts/modules/core/src/pipeline/config/templates/pipelineTemplate.module.ts
app/scripts/modules/core/src/pipeline/config/templates/pipelineTemplate.service.ts
app/scripts/modules/core/src/pipeline/config/templates/templatePlanErrors.component.ts

@jrsquared or @anotherchrisberry please review.

fix(pipeline-templates) fix rendering issues for errors and help fields

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/bootstrap/spinnaker.component.ts

It's only being used in our internal build, but needs to be there.
fyi @christopherthielen

fix(core): include "feature" on spinnaker component ctrl

---

app/scripts/modules/google/src/help/gce.help.ts

chore(provider/google): Update auth scopes tooltip.

---

app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/kubernetes.settings.ts
app/scripts/modules/kubernetes/proxy/ui.service.js
halconfig/settings.js
settings.js

Closes https://github.com/spinnaker/spinnaker/issues/1739

feat(kubernetes) instance links

---

app/scripts/modules/core/src/entityTag/notifications/notificationCategories.ts

@jrsquared @anotherchrisberry @icfantv

feat(core/entityTag): Tweak alert category descriptions

---

app/scripts/modules/core/src/entityTag/notifications/CategorizedNotifications.tsx
app/scripts/modules/core/src/entityTag/notifications/NotificationCategory.tsx
app/scripts/modules/core/src/entityTag/notifications/notificationCategories.ts
app/scripts/modules/core/src/entityTag/notifications/notifications.less

@jrsquared @anotherchrisberry 
After further discussion with Jeremy and Astrid, we changed the labels yet again

feat(core/entityTag): Tweak alert category descriptions (again)

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/pipeline/config/stages/canary/CanaryScore.tsx

chore(core): bump package to 0.0.21

---

app/scripts/modules/google/src/loadBalancer/loadBalancer.setTransformer.ts

fix(gce): cast load balancers to pacify TS compiler

---

app/scripts/modules/core/package.json

chore(core): bump to 0.0.22

---

app/scripts/modules/google/src/loadBalancer/configure/internal/gceCreateInternalLoadBalancer.controller.ts

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

fix(gce): placate linter

---

app/scripts/modules/core/src/delivery/executionGroup/ExecutionGroup.tsx

@anotherchrisberry or @jrsquared 
Not sure exactly how it happens, but it happens sometimes.

fix(core) dedupe execution account labels

---

app/scripts/modules/core/src/delivery/details/singleExecutionDetails.component.ts
app/scripts/modules/core/src/entityTag/notifications/NotificationsPopover.tsx

fix(core/entityTag): Clone more fields in UI when editing an entity tag

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/deploymentStrategy/rollingPush.strategy.ts

not sure what happened but GH was unhappy with that last PR...

fix(aws): change "deprecated" to "not recommended" on rolling push

---

app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html

fix(gce): minor formatting change for user data input field

---

app/scripts/modules/google/src/serverGroup/configure/serverGroup.configure.gce.module.js
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/CustomInstanceConfigurer.tsx
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceConfigurer.component.ts

@duftler 
Values can just be typed into the dropdowns now.

feat(gce): better custom instance selector

---

app/scripts/modules/core/src/modal/modals.less

The little X clear button is way off. @anotherchrisberry or @jrsquared.

fix(core): fixes ui-select clearable X button

---

app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/core/src/presentation/standalone.view.html

Scrolling is currently broken on standalone views.

fix(core): fix scroll on standalone views

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

chore(amazon, core): rev packages

---

app/scripts/modules/google/src/loadBalancer/configure/internal/listener.html

@jtk54 please review. I've manually tested this, and there don't seem to be any problems.

feat(gce): allow ILB port update

---

app/scripts/modules/core/src/utils/debug.ts
app/scripts/modules/core/src/utils/index.ts
package.json

- Also bumped @uirouter/react-hybrid version
These decorators can be used to do perf analysis.

feat(core/utils): Add timing debug decorators

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/core/package.json
app/scripts/modules/core/src/diffs/changes.html
app/scripts/modules/core/src/diffs/viewChangesLink.component.ts
app/scripts/modules/core/src/domain/IBuildDiffInfo.ts
app/scripts/modules/core/src/domain/IJenkinsInfo.ts
app/scripts/modules/core/src/domain/IStageContext.ts
app/scripts/modules/core/src/domain/index.ts
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js

* add build info, if available, to changes dialog.

feat(core/amazon): add build info to changes

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/loadBalancer/configure/application/listeners.html
app/scripts/modules/amazon/src/loadBalancer/configure/classic/listeners.html
app/scripts/modules/core/package.json

Because the field is very narrow for ELBs, I added a tooltip.
Also rev'ing amazon, core packages because we're going to release this right away...
@jrsquared PTAL

feat(aws): allow search on LB listener cert select

---

app/scripts/modules/amazon/package.json

* guard against missing `buildInfo` in server group details

chore(aws): bump package version

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/google/package.json

* update package configs to add task for cleaning and change
`prepublish` to `prepare` to fix deprecation warning when publishing.

chore(core/amazon/docker/google): update configs

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/core/src/deploymentStrategy/deploymentStrategy.module.ts
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/additionalFields.html
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/rollingredblack.strategy.ts
app/scripts/modules/core/src/forms/numberList/numberList.component.less
app/scripts/modules/core/src/help/help.contents.ts

feat(core) - ui for rolling red black push
