spinnaker/deck

app/scripts/modules/core/pipeline/config/stages/bake/aws/awsBakeStage.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.spec.js

This might be a little too opinionated, but until we get integration with other CI services, I'm going with it. It won't actually prevent a pipeline from being saved - or executed. It just warns the user that maybe this is not a great idea.

validate jenkins stage exists before bake

---

app/scripts/modules/google/cache/cacheConfigurer.service.js

@duftler I'm going to merge this in - the only side effect is the list of load balancers for GCE will be lazy-loaded the first time it's needed, but that should get rid of the 429s folks are seeing when the app starts up without GCE enabled.

do not initialize gce load balancers on app start

---

app/scripts/modules/core/cache/cacheInitializer.js
app/scripts/modules/core/templateOverride/templateOverride.registry.js
app/scripts/modules/google/cache/cacheConfigurer.service.js
app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/templateOverride/templateOverrides.module.js
settings.js

@ajordens your idea of initializing caches only if the provider is actually configured on the backend is a good one.
Also adding a feature flag to enable the netflix module overrides (cc @zanthrash). Ideally, we'd be dealing with both these issues by changing app.js, but I don't see that happening any time soon and this won't be hard to unwind when we get to that point.

selectively apply netflix module, init cache on configured providers

---

app/scripts/modules/core/forms/checklist/checklist.directive.html
app/scripts/modules/core/forms/checklist/checklist.directive.js
app/scripts/modules/core/forms/checklist/checklist.directive.spec.js

If all items in a list are selected, we're left with an unhelpful "Select All" button. This changes that button to a "Deselect All" if every item is already selected. If only some of the items are selected, it remains "Select All".

Change 'Select All' button to 'Deselect All' when all items are selected

---

app/scripts/modules/core/filterModel/filter.model.service.js

Fixes an issue where filtering on a pipeline with a comma in its name will erroneously be translated into a filter on two separate pipelines, which may or may not (but probably don't) exist.

encode commas when storing as filter model objects in url

---

app/scripts/modules/core/pipeline/config/stages/bake/aws/bakeStage.html

The "Use Enhanced Networking" label expanded to two lines because of its length. Shortening it to "Enhanced Networking" puts it one line.
**Before**
---
**After**
---
**With proper bootstrap class**

Shorten field name so it fits on one line

---

app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/amazon/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/cloudfoundry/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/core/application/modal/platformHealthOverrideCheckbox.directive.html
app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/core/pipeline/config/health/stagePlatformHealthOverride.directive.js
app/scripts/modules/core/pipeline/config/health/stagePlatformHealthOverrideCheckbox.directive.html
app/scripts/modules/core/pipeline/config/pipelineConfig.module.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/disableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/gce/disableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableCluster/aws/disableClusterStage.html
app/scripts/modules/core/pipeline/config/stages/disableCluster/gce/disableClusterStage.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/aws/enableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/gce/enableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/resizeAsgStage.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/gce/resizeAsgStage.html
app/scripts/modules/google/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/google/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/netflix/serverGroup/resize/awsResizeServerGroup.html

Not as much going on here as the 500+ line changeset implies.
Two main things re: the directive itself:
1. Split the `<platform-health-override>` directive into two separate directives: one that is used generically to render the checkbox and label, and a second, `<stage-platform-health-override>`, to generically apply the directive in stage config.
2. Remove the left-side label from the `<platform-health-override>` directive. The whole column management thing is a mess carried over from some other directives (i.e., don't blame the person who wrote this directive, blame the person who wrote the original directives the pattern was copied from).
The other thing (and the original reason I went into this code) is to put the platform health override before the account verification, which should …

refactor platformHealthOverride directive; place consistently in modals

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/application/service/applications.read.service.spec.js
app/scripts/modules/core/pipeline/config/stages/bake/aws/awsBakeStage.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/awsDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/resizeAsg/cf/cfResizeAsgStage.js

Missed these in a prior refactoring.
Also adding some tests around setting default regions/credentials, since we have next to no test coverage on the applicationReader. There should be a lot more tests, considering the complexity of that operation, but I think we want to refactor it quite a bit, which would be a good opportunity to add some test coverage.
@duftler please review

fix defaultRegions usage

---

settings.js

These settings have been moved to Clouddriver, so are no longer needed in settings.js
cc @JargoonPard - can you review this and verify everything is still working as expected?

remove extraneous settings fields from azure block

---

app/scripts/modules/core/application/modal/platformHealthOverride.directive.js

These fields were refactored out, but never removed from the directive definition.

clean up platformHealthOverride definition

---

app/scripts/modules/amazon/serverGroup/details/resize/resizeServerGroup.html

Missed this on a previous PR - the footer directive's API changed, renaming "resize" to a generic "action".

fix submit button on AWS resize modal

---

app/scripts/modules/google/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/google/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/google/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.html

@ttomsu: This will fail with `enableDisableGoogleServerGroupDescription.zone.empty` until (I think) `orca/AbstractServerGroupTask.convert()` properly sets `zone` on GCE server group operations.
@ajordens fyi

Add support for Rollback operation on Google server groups.

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instance.details.controller.spec.js
app/scripts/modules/amazon/serverGroup/configure/wizard/ServerGroupBasicSettings.controller.js
app/scripts/modules/azure/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js
app/scripts/modules/cloudfoundry/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js
app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.controller.spec.js
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.spec.js
app/scripts/modules/core/scheduler/scheduler.service.js
app/scripts/modules/core/search/infrastructure/infrastructureSearch.service.js
app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.js
app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.spec.js
app/scripts/modules/core/utils/jQuery.js
app/scripts/modules/core/utils/lodash.js
app/scripts/modules/core/utils/rx.js
app/scripts/modules/google/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js
app/scripts/modules/titan/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js

Trying to get away from passing scope objects into the application object by providing `Observable`s that controllers can subscribe to in order to react to application refresh events.
The code feels a little more verbose (we have to remember to dispose of the subscription when the controller $scope is destroyed), but seems more correct than having the application manage the events when it refreshes. It also feels a lot cleaner than using `$rootScope.$broadcast` everywhere.
Also starting to refactor the `applicationReader` service into more manageable (i.e. non-200-line) methods.
I am not very familiar with RxJS, so any feedback is welcome here.

refactor application reader; rx replacing $broadcast

---

app/scripts/modules/core/projects/dashboard/cluster/inconsistentBuilds.tooltip.html
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.html
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.js
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.spec.js
app/scripts/modules/core/projects/service/project.read.service.js

The current implementation always takes the latest build in any region, which misses the scenario where multiple builds are deployed in the same region, which turns out to be a valid scenario.
@duftler or @zanthrash please review when you have a minute

better surface inconsistent builds in project clusters

---

app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/resizeAsgStage.html

Before:
After:
Aligns with the way the incremental label looks like:

fix label for resize-percentage

---

app/scripts/modules/core/account/account.service.js

Two reasons this should never have been memoized in the first place:
* there's no key resolver (second argument to `_.memoize`), so the application will just be `toString()`ed to get the key, so it'll always be `[object Object]`, regardless of which application is passed in
* the result of the function could change if the application's `cloudProviders` attribute changed, so it's really just a bad idea to memoize it in the first place.
@JargoonPard please review - thanks for catching this

do not memoize listProviders method

---

app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/application/service/applications.read.service.spec.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/netflix/alert/alertHandler.js

Turns out `onError` terminates any subscriptions, so that's not what we want to do on load failures.

do not call onError from an Observable

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/delivery/service/execution.service.spec.js

We're seeing a race condition, where Orca acknowledges the cancel/delete operation, but the new status is not always reflected when we immediately grab the executions.
This mimics the behavior of the `startPipeline` action by polling the appropriate endpoint until the expected state is reached, then reloading the application's executions to update the view.

poll executions before completing cancel/delete operation

---

app/scripts/modules/core/presentation/details.less
app/scripts/modules/core/search/global/globalSearch.directive.html
app/scripts/modules/netflix/feedback/feedback.html

Top-level menu items don't use the ui-bootstrap dropdowns, so maybe we shouldn't wreck their rendering.

revert overzealous dropdown menu styling

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js
app/scripts/modules/netflix/templateOverride/templateOverrides.module.js

fixes netflix template override for server group capacity; calculate last phase after uniq-ing child nodes for pipeline graph

graph perf fix; correct netflix override template

---

app/scripts/modules/core/application/config/applicationAttributes.directive.html

Removes a duplicate `<div class="col-md-7">` that was squashing the content.
This is on the `/#/applications/{application}/config` page.

Fix Application Attributes style 

---

package.json

NPM v3.x was not loving the arbitrarily keyed dependencies. Resolved this by running `npm install --save ${gitUrl}` on each `git://` dependency.

update package.json to allow install via npm v3.x

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/bake/aws/awsBakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/aws/bakeExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/bake/bakeExecutionLabel.html
app/scripts/modules/core/pipeline/config/stages/bake/bakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/bakeStage.transformer.js
app/scripts/modules/core/pipeline/config/stages/bake/bakeStage.transformer.spec.js
app/scripts/modules/core/pipeline/config/stages/bake/docker/dockerBakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/gce/gceBakeStage.js

* provide visual clues that a previous bake was returned on a bake operation
* allow users to request a rebake when triggering a pipeline with a bake stage
* refactored the ManualPipelineExecutionCtrl to use the `vm` pattern
* added a pile of tests
dependent on https://github.com/spinnaker/orca/pull/678
@zanthrash @duftler please review when you have time

surface rebake option on manual execution, include details in pipeline

---

app/scripts/modules/core/region/regionSelectField.directive.html
app/scripts/modules/core/region/regionSelectField.directive.spec.js

How this bug has been in the wild for at least three weeks without anyone seeing it is a mystery. I guess maybe folks just don't notice it, since it doesn't seem to affect the actual model values.
Basically, what's happening now is that the displayed value in the select box is always the first option, even if the second or third option were selected. That's not really true: I am seeing the third option being surface, just not the fourth option, which makes even less sense. For example: with options [`us-east-1`, `us-west-1`, `us-west-2`, `eu-west-1`], if `eu-west-1` is pre-populated, the select box shows `us-east-1`; if `us-west-2` is pre-populated, the select box shows `us-west-2`. Why? What kind of world do we live in?
Whatever. This fixes it. 
@zanthrash can you review?

fix initial selection on regionSelectField

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html

Current:
PR:
Parameters are still ugly because the names tend to be longer; this makes the modal layout a little less ugly.

move rebake control above parameters in manual pipeline execution modal

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/listeners.html
app/scripts/modules/amazon/loadBalancer/loadBalancer.transformer.js

We get a lot of people asking how to format ARNs for their SSL certificates coming from Lemur. This change allows them to simply specify the SSL certificate name and formats it correctly as an ARN.

Added the ability to specify certificate name instead of ARN

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/whatsNew/whatsNew.directive.html
app/scripts/modules/netflix/whatsNew/whatsNew.less

We lost some style attributes on a recent refactor of the `whatsNew` directive. This PR:
* fixes padding and an overflow issue with the "last updated" label
(current)
(this pr)
* sets the icon color to yellow on smaller screens when there are unread messages
cc @riltsken

fix styling on whats-new directive when unread updates present

---

app/scripts/modules/core/task/task.write.service.js
app/scripts/modules/core/task/task.write.service.spec.js
app/scripts/modules/core/task/tasks.controller.js
app/scripts/modules/core/task/tasks.controller.spec.js

We currently do not refresh the list of tasks on the tasks view after deleting or canceling a task.
With this PR, we poll the task, waiting for the expected state:
* for canceled tasks, wait until the status is CANCELED
* for deleted tasks, wait until we get a 404 when querying the task
then reload the tasks.

wait until task state is recorded, then refresh the view

---

app/scripts/modules/core/projects/dashboard/cluster/inconsistentBuilds.tooltip.html
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.controller.spec.js
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.html
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.js
app/scripts/modules/core/projects/dashboard/cluster/projectCluster.directive.spec.js
app/scripts/modules/core/projects/dashboard/dashboard.controller.js
app/scripts/modules/core/projects/dashboard/dashboard.html
app/scripts/modules/core/projects/service/project.read.service.js

We have a shiny new endpoint to retrieve all project cluster info in one call, instead of coordinating dozens (or hundreds) of async calls, which cleans up a lot of logic that was previously in this controller.
This depends on https://github.com/spinnaker/gate/pull/167 getting pushed to prod, which I'll do shortly.
@zanthrash for your reviewing pleasure

refactor project cluster loading to use new endpoint

---

app/scripts/modules/core/ci/jenkins/igor.service.js

Fixes: https://github.com/spinnaker/spinnaker/issues/605
Depends on: https://github.com/spinnaker/gate/pull/161

Update gate Jenkins endpoint

---

app/scripts/modules/core/pipeline/config/stages/bake/aws/awsBakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/aws/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/bakery.service.js
app/scripts/modules/core/pipeline/config/stages/bake/docker/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/docker/dockerBakeStage.js
app/scripts/modules/core/pipeline/config/stages/bake/gce/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/gce/gceBakeStage.js

This PR needs to be merged after https://github.com/spinnaker/gate/pull/166 and https://github.com/spinnaker/orca/pull/687
Google/AWS base OS options:
Rosco disabled (Netflix-only) base OS options:
Error screenshot if specified base OS is not found:
@spinnaker/reviewers
Tag: https://github.com/spinnaker/spinnaker/issues/597

Makes  use newly exposed endpoing on Gate to get base OS options.

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/validation/applicationName.validator.js
app/scripts/modules/core/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/application/modal/newapplication.html
app/scripts/modules/core/application/modal/validation/applicationName.validator.js
app/scripts/modules/core/application/modal/validation/applicationName.validator.spec.js
app/scripts/modules/core/application/modal/validation/applicationNameValidationMessages.directive.html
app/scripts/modules/core/application/modal/validation/applicationNameValidationMessages.directive.js
app/scripts/modules/core/application/modal/validation/exampleApplicationName.validator.js
app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.js
app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.spec.js
app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.js
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/fastProperties/modal/wizard/fastPropertyForm.directive.html

Provides a mechanism for any provider to specify warning and error conditions for application names.
For example: due to AWS's kinda severe restrictions on load balancer names, we warn users about very long names. That should not be a concern for users who are not using AWS.
I've left the character restrictions in place (`ng-pattern` - alphanumeric + dot + underscore) because we use the application name everywhere and don't want to have to URL-encode the names of components.
@zanthrash @duftler please review when you have time

implement provider-specific validation mechanism for application name

---

app/scripts/modules/core/cluster/filter/clusterFilter.model.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.spec.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.spec.js
app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/instance/details/multipleInstanceServerGroup.directive.html
app/scripts/modules/core/instance/details/multipleInstanceServerGroup.directive.js
app/scripts/modules/core/instance/details/multipleInstanceServerGroup.directive.less
app/scripts/modules/core/instance/details/multipleInstances.controller.js
app/scripts/modules/core/instance/details/multipleInstances.controller.spec.js
app/scripts/modules/core/instance/details/multipleInstances.view.html
app/scripts/modules/core/instance/instance.module.js
app/scripts/modules/core/instance/instance.write.service.js
app/scripts/modules/core/instance/instance.write.service.spec.js
app/scripts/modules/core/instance/instanceList.directive.html
app/scripts/modules/core/instance/instanceList.directive.js
app/scripts/modules/core/instance/instanceListBody.directive.js
app/scripts/modules/core/navigation/states.provider.js
app/scripts/modules/core/serverGroup/serverGroup.directive.html
test/mock/mockApplicationData.js

Note: this is for review only right now. I'd like to get @ttomsu 's https://github.com/spinnaker/deck/pull/1809 in first, then rebase against it and clean up the write operations (remove launch time, maybe more?).
This PR adds the ability to perform a handful of actions against multiple instances at the same time. To enable this behavior, the "with details" checkbox must be selected in the clusters view, then the user must click the individual checkboxes next to each instance (or click the "select all" checkbox in the table header for a given server group).
There are five components responsible for managing the state of selection:
* `clusterFilterService`: removes selected instances when the user changes filters, causing an instance to no longer be present on the screen, or instances …

enable multiselect actions on instances

---

app/scripts/modules/core/help/helpContents.js

Adds an example of a weekly job, provides clarification around the start of the week.

clarify help text on CRON expressions

---

app/scripts/modules/core/delivery/details/executionDetails.less
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.directive.html
app/scripts/modules/core/pipeline/config/stages/core/executionSummary.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryExecutionSummary.html

Two things:
1. Include the duration of the overall stage in the summary view
2. Render the graph labels _after_ all the links have been drawn to make sure the links never overlap the labels
_Current_
_With this PR_
@dzapata does this look reasonable?

Execution tweaks

---

app/scripts/modules/core/search/global/globalSearch.controller.js
app/scripts/modules/core/search/global/globalSearch.directive.html

Right now, if you click in the search box and paste some text, nothing happens. If you select the text and cut it, first of all, why are you doing that, second, fine, we should handle that gracefully. Also, if you are using the tab key to navigate the results, we should hide them if you navigate away from the menu altogether.
@zanthrash or @duftler please review if you have a minute.

handle cut/paste/blur events on global search

---

app/scripts/modules/core/scheduler/scheduler.factory.js

If the scheduler is disposed, but there is a pending run, we should cancel that.

cancel any pending run when disposing of scheduler

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html

When manually executing a pipeline, we should not reorder the parameters - it's often the case users have configured the parameters in a specific order, e.g. putting those without defaults first.
Not sure if we need to warn users in that dialog that the parameter order may have changed or not - I would hate to have someone enter the wrong thing due to muscle memory - but I'm not sure how big a concern this should be.

preserve pipeline parameter order when running manual execution

---

app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsExecutionDetails.html

If the Jenkins job failed because the job couldn't be started, we need to surface that in lieu of the other failure message, which is defined by the `jenkinsExecutionDetailsController`.
@tomaslin for your review - this corresponds with the Igor changes made here: https://github.com/spinnaker/igor/pull/60

show orca error if present on failed jenkins stage

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/core/help/helpField.directive.html

There shouldn't need to be a trigger to allow the user to force a rebake - just a bake stage in the pipeline.
Also updating the help field expanded view so it shows HTML as HTML instead of escaping it (not used in this PR, just noticed it while playing around with the formatting).
@duftler for your review

allow force-rebake when no trigger present

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js

Somehow, the quick patch stage always has a `null` start time, which messes up duration calculations. Until we can figure out _why_ that is the case, this will set its start time (and the start time of other stage summaries) to the min value of any child stage.
@zanthrash @ajordens please review

generate start time of stage summary from child stages

---

app/scripts/modules/amazon/serverGroup/details/scalingProcesses/autoScalingProcess.service.js
app/scripts/modules/amazon/serverGroup/details/scalingProcesses/autoScalingProcess.service.spec.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/presentation/details.less
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/netflix/serverGroup/networking/networking.controller.js
app/scripts/modules/netflix/serverGroup/networking/networking.directive.html
app/scripts/modules/netflix/serverGroup/networking/networking.directive.js
app/scripts/modules/netflix/serverGroup/networking/networking.module.js

This started as a small pull request to change this:
to this:
I started down the path of breaking up the sections in the details panel into separate directives, but that would have made this a 1000+ line change, so I settled for converting it to ES6.
The core changes are moving the logic for extracting the scaling processes into the `autoScalingProcessService`, and adding that band along the bottom of the header when the server group is disabled - that's the first couple of files here, as well as the top part of the controller. After that, it's just converting to ES6.
@duftler @gregturn @JargoonPard I did not touch anything but the AWS components - not sure what's involved in determining _when_ a server group was disabled for each provider. Ideally, we'd move this …

show date AWS server group was disabled

---

app/scripts/modules/core/cluster/rollups.less

instead of pixelated garbage like this:
get normal looking checkboxes like this:
cc @cfieber

use font-size instead of scale to size checkboxes

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/amazon/serverGroup/details/scalingProcesses/autoScalingProcess.service.js

It's the *advanced* settings screen, where users would expect to have this level of control over their ASG configuration.

allow users to configure scaling processes when creating new ASG

---

app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.controller.spec.js
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.html
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.js

If the job is parameterized via templating, we should not override its value.

handle job parameterization in Jenkins stage

---

app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/core/help/helpContents.js

The AWS deploy accepts an optional field "base64UserData" in the pipeline's JSON. This just adds that field to the UI so that users don't need to edit the JSON manually. The "Advanced Settings" tab seemed appropriate for this. The help text informs the users that the string must be base64 encoded.

Add userdata field to the UI

---

app/scripts/modules/core/instance/details/console/consoleOutputLink.directive.js
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/task/verification/userVerification.directive.js

I have no idea why this started blowing up today, but it did, giving the following error:
```
Error: [$compile:nonassign] Expression 'undefined' used with directive 'userVerification' is non-assignable!
```
I am guessing there will be more PRs like this in the next few days.
Also fixing a fairly insignificant CSS bug from https://github.com/spinnaker/deck/pull/1889

Non expression fixes

---

app/scripts/modules/core/application/listExtractor/listExtractor.service.js
app/scripts/modules/core/task/verification/userVerification.directive.spec.js
app/scripts/modules/core/widgets/index.js
app/scripts/modules/core/widgets/scopeClusterSelector.directive.html
app/scripts/modules/core/widgets/scopeClusterSelector.directive.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.html
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.js

Both the region list and cluster list are derived from the what account is
selected. The cluster list starts off with all clusters available.  Once an
account is selected the region and cluster list are filter to show only
those regions and clusters in the account. Once the region is selected the cluster list will filter down to show only clusters in that region.
Changing either the account or region selections will remove the selected
cluster item if there was one.
Also removed the focus on a test that accidentally got checked in.
@anotherchrisberry cleaned up, plz review

SPIN-247:  Add cluster selector with some smarts.

---

app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/azure/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/core/core.module.js
app/scripts/modules/core/deploymentStrategy/strategies/custom/customStrategySelector.directive.html
app/scripts/modules/core/projects/configure/configureProject.modal.controller.js
app/scripts/modules/core/projects/configure/projectApplications.modal.html
app/scripts/modules/core/utils/infiniteScroll.directive.js
app/scripts/modules/core/utils/utils.module.js
package.json

So...it turns out the angular-infinite-scroll-with-ui-select trick doesn't _really_ work with ng-infinite-scroll OOB. The demonstrated working version is hacked together.
This PR brings that hacked-together version into Deck and fixes our uses of it throughout the codebase. I've tested all locations we're currently using it, and it now works as expected.
Also changing the way editing ingress rules works when editing a security group. There's rarely ever a case when it makes sense to change the name of security group, while retaining ports. So we just show the name as a read-only value.
@zanthrash please review...

used hacked up infinite scroller

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js

Also run all the tests.
Tracking by `$index` causes grief because we need to add `$watch`es all over the place to make sure we don't bork the view when new items enter the execution group.

track executions by $id, not $index

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html

Previously when the <enter> key was hit the close button was 'clicked' because it was the first in the DOM, unless the 'Run' key had focus.
I added a type="button" to the cancel button which Chrome, FF, Safari (only ones tested) will ignore it and use the type="submit" for the <enter> key event.
@anotherchrisberry plz review

SPIN-1353: Make hitting <enter> key will run the execution.

---

app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html

Populate accountName and id for ingress so that CloudDriver understands exactly which security group is specified.
Fix links to cross account security group details.
Display account on cross account security groups in detail and edit views.

Enable edit of security group with cross account ingress.

---

app/scripts/modules/core/application/listExtractor/listExtractor.service.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/aws/awsDestroyAsgStage.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/aws/destroyAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/awsDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/disableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/disableCluster/aws/awsDisableClusterStage.js
app/scripts/modules/core/pipeline/config/stages/disableCluster/aws/disableClusterStage.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/aws/awsEnableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/aws/enableAsgStage.html
app/scripts/modules/core/pipeline/config/stages/modifyScalingProcess/modifyScalingProcessStage.html
app/scripts/modules/core/pipeline/config/stages/modifyScalingProcess/modifyScalingProcessStage.js
app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/awsResizeAsgStage.js
app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/resizeAsgStage.html
app/scripts/modules/core/pipeline/config/stages/scaleDownCluster/aws/awsScaleDownClusterStage.js
app/scripts/modules/core/pipeline/config/stages/scaleDownCluster/aws/scaleDownClusterStage.html
app/scripts/modules/core/pipeline/config/stages/shrinkCluster/aws/awsShrinkClusterStage.js
app/scripts/modules/core/pipeline/config/stages/shrinkCluster/aws/shrinkClusterStage.html
app/scripts/modules/core/widgets/scopeClusterSelector.directive.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.html
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.js

Also fixing a bug that surfaced in the deployed quick patch stage where a saved cluster name was getting marked undefined upon stage load.
This fixes the QIP stage and all the other stages that use the cluster selector.
The cluster filter was also extracted into a factory function that can be used across all stages.

SPIN-1418: Add Cluster selector to pipeline stages that require selecting a cluster.

---

app/scripts/modules/amazon/serverGroup/configure/wizard/serverGroupWizard.html

prefix slash in capacity/zones heading with whitespace

---

app/scripts/modules/netflix/fastProperties/modal/deleteFastProperty.controller.js

When the verification directive was added the logic got messed up for enabling  the submit button, preventing any FP from being deleted.
This fixes the logic.

SPIN-1433: Fixing Fast Property delete regression.

---

app/scripts/modules/core/delivery/status/executionUser.filter.js

If authentication is disabled, the user will be `[anonymous]`, even if not triggered by a parent pipeline.
cc @tomaslin

executionUser filter: do not throw NPE if no parent execution

---

app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js

It is hard for me to imagine a scenario where `$scope.securityGroup` would be `undefined` at this point in the code, but apparently there is one, so let's not throw an NPE if we get there.

get provider, vpcId from configured security group

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgment.service.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.js

Add support for branching after a manual judgment stage as discussed in issue [#688.](https://github.com/spinnaker/spinnaker/issues/688)  At design time, a user may add a series of inputs values to manual judgment stage.
Those values will then populate a searchable drop down in the manual judgment at runtime.  If no values were entered at design, this will not appear.
By doing this, several parallel pipeline paths can be branched after a manual judgment.  Each of those paths would then start with a Check Precondition Stage.  That stage would look for the input value selected in the manual judgment.

Issue 688 branching

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/modal/modals.less
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgmentStage.html

Minor style and wording changes to supplement https://github.com/spinnaker/deck/pull/1929
Configuration view
* Do not show "Instructions" heading if no instructions present
* Expanded help text to provide more context
* Tweak alignment of table elements
Execution view
* Add some padding between ui-select and Stop/Continue buttons
* Fixed position of clearing `x` in ui-select
@bfarrell I figured this would be easier than asking you to make all these little changes in your PR.

style tweaks to judgment inputs

---

app/scripts/modules/core/cluster/filter/clusterFilter.model.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.spec.js
app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/instance/details/multipleInstances.controller.js
app/scripts/modules/core/instance/instanceListBody.directive.js

The current behavior around multiselect is really confusing: users have to click the checkbox next to an instance to enable multiselect, but a lot of users assume they should click on that checkbox to see details for a single instance, so they're confused when they just see "1 Instance" in the heading and a very limited view of that instance's details.
Also, trying to close the details panel in multiselect mode doesn't do anything - it just pops right back up.
Finally, it's really unintuitive that clicking the checkbox and clicking elsewhere in the row result in totally different details view.
This PR addresses most of these concerns. The row and the checkbox behave the same way: they select the instance in multiselect mode. However, if just one instance is selected, we show the …

SPIN-1447: multiselect UX improvements

---

app/scripts/modules/netflix/canary/canary.read.service.js
app/scripts/modules/netflix/canary/canaryConfigSelector.directive.html
app/scripts/modules/netflix/canary/canaryConfigSelector.directive.js
app/scripts/modules/netflix/canary/index.js
app/scripts/modules/netflix/fastProperties/modal/wizard/fastPropertyAcaConfigForm.directive.html

This selector gets a list of all previous Canary Configs for a given app.   When the user selects a previous confg it populates the Canary Config form with the values.
This can eventually go into the ACA pipeline stage I just want to get it out there and get some feedback from users.

SPIN-1453: Adding new ACA Config selector to FP ACA screen.

---

app/scripts/modules/core/cache/collapsibleSectionStateCache.js
app/scripts/modules/core/cache/deckCacheFactory.js

Our current strategy to only clear out the infrastructureCaches if there is an exception thrown on insert.
As the app has grown we have added more and more to Local Storage resulting in the possibility of exhausting the 5MB of space given in most browsers.
This change simply evicts the entire local storage (restricted to the namespace of the url), when there is an insert exception.
This change also reduces the TTL of the 'collapsible section cache' from 30 days to 7 days.
@anotherchrisberry Please review.

SPIN-1415:  Evict Local Storage if there is an exception on setItem

---

app/scripts/modules/core/modal/modals.less
app/scripts/modules/core/modal/wizard/modalWizard.less
app/scripts/modules/core/modal/wizard/v2modalWizard.directive.html
app/scripts/modules/core/modal/wizard/v2wizardPage.directive.html

Providing a nominally better modal wizard experience on smaller screens by removing the steps on the side and including the state indicator in the header.
Also removing some padding from the header across modals and restoring the rendering of the close button on v2 wizards.

improve usability in v2 modal wizards on small screens

---

app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/details/details.controller.js
app/scripts/modules/kubernetes/serverGroup/details/details.html
app/scripts/modules/kubernetes/serverGroup/details/details.kubernetes.module.js

Only basic information is currently displayed (name, creation time, health, resource requests, image names), but more will be added as I make the server group more customizable.

provider/kubernetes: Render basic server group information on "cluster" screen

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.spec.js

The code currently looks at all the regional images to pick the virtualization type, which, while usually correct (for some reason - this code is three months old), it is not always correct, and is definitely unintentional. This picks up the virtualizationType value from the matching image.

set virtualizationType on aws command based on image match

---

app/scripts/modules/core/application/service/applications.read.service.spec.js
app/scripts/modules/core/cluster/cluster.service.spec.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/delivery/filter/filterNav.html
app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/delivery/service/execution.service.spec.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.js
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.spec.js
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.less
app/scripts/modules/core/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.js
app/scripts/modules/core/pipeline/pipelines.less
app/scripts/modules/core/presentation/less/imports/colors.less
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/task/monitor/taskMonitorService.spec.js
app/scripts/modules/core/task/task.read.service.spec.js
app/scripts/modules/core/task/tasks.controller.spec.js
app/scripts/modules/core/task/tasks.fixture.js
app/scripts/modules/core/task/tasks.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStatus.directive.js

@spinnaker/netflix-reviewers this change means we'll always be retrieving 50 executions per pipeline (but still potentially rendering a subset of those, based on user filters).
@ajordens yea or nay

allow rendering of up to 50 executions per pipeline

---

app/scripts/modules/core/delivery/details/executionDetails.less
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/delivery/filter/filterNav.html
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.js
app/scripts/modules/core/pipeline/pipelines.less
app/scripts/modules/core/presentation/less/imports/colors.less
app/scripts/modules/core/task/task.read.service.spec.js
app/scripts/modules/core/task/tasks.html
app/scripts/modules/netflix/canary/canary.less

A minor CSS fix, a minor data ordering fix, and a couple of bigger functionality fixes:
* (bigger) "Failed" is now "Terminal" to better align with Orca's status values
* (bigger) Removing a filter tag will reload executions
* (minor) Much more sensible ordering of synthetic child stages (for @ajordens )
* (minor) Fixed the CSS on the canary score box so the number is centered and the box is positioned more cleanly (@zanthrash - you'll want to check this on the fast property rollouts to make sure it looks fine there)
@zanthrash or @ajordens please review when you have a minute

fix canary CSS, Failed->Terminal, fix sub-stage ordering

---

app/scripts/modules/netflix/feedback/feedback.modal.html

It's pretty frustrating when the feedback submit fails and all the content goes away. This leaves it on the screen so the user can try to submit again, and, if it keeps failing, can at least copy/paste the content out of the modal.

do not destroy feedback modal when submit fails

---

app/scripts/modules/netflix/feedback/feedback.modal.html

The div showing the success message is otherwise wrapped in a section that is hidden once the form is submitted successfully, which is not very helpful.

add closing div tag to feedback modal

---

build.gradle

Previously apache2 was added as "Depends" in the control file (through build.gradle). Because of this, the actual deployment of apache2 was happening only after the deck files are laid out. This resulted in the index.html file being overwritten by the one from apache2.
Fix was to add apache2 as Pre-Depends instead of Depends in the debian control file thereby making sure that apache2 is installed and configured fully before deck is installed.

Fix for "The deck debian package does not install apache2 in the right order" Issue#723

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancerProperties.html
app/scripts/modules/amazon/loadBalancer/loadBalancer.transformer.js

1. The checkbox for isInternal appears only for vpc.
2. Updated loadBalancer.transformer.js to have isInternal flag.

Adding support for internet-elb v2.

---

app/scripts/modules/core/securityGroup/securityGroup.read.service.js
app/scripts/modules/core/securityGroup/securityGroup.read.service.spec.js

prevents eager reloading of security groups when they are in the process of loading

only attach security groups when they have been indexed

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/delivery/service/execution.service.spec.js

It doesn't make sense to poll all executions for an application when waiting for one to appear canceled or deleted - we just need to query that particular execution.

poll single execution for cancel/delete status changes

---

app/scripts/modules/core/pipeline/config/stages/findAmi/aws/findAmiExecutionDetails.html

The controllers are identical, which is why this has been working without issue.

use correct controller for aws find image details

---

app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.html
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.html

The Quick Patch stage uses `clusterName` instead of `cluster`, and a single `region` instead of `regions`. To maintain backwards compatibility with scripts and existing stages, I am leaving the quick patch stage as-is, although we may want to update the `clusterName` field at some point to be consistent with other stages.

adapt acct-reg-cluster-selector to work with quick patch stage

---

app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupAdvanced.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupArtifactSettings.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupBasicSettings.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupEnvs.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupLoadBalancers.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/ServerGroupServices.controller.js

heads up @gregturn - getting a bunch of linter warnings about unused arguments - just commenting these out for now to keep the command line output cleaner

fix linter warnings in cf module

---

app/scripts/modules/core/forms/forms.module.js
app/scripts/modules/core/forms/mapEditor/mapEditor.component.html
app/scripts/modules/core/forms/mapEditor/mapEditor.component.js
app/scripts/modules/core/forms/mapEditor/mapEditor.component.spec.js

Pretty simple Angular 1.5 component to allow editing of a map as simple key-value pairs. Provides options for `onChange` events, customizing labels for table, and allowing empty values.
Usage:
```html
<map-editor model="stage.extendedAttributes"></map-editor>
```
@tonyrzhang give this a shot - I think it will handle what you need for the extended attributes work...

component to allow editing of objects as key-value pairs

---

app/scripts/modules/core/pipeline/config/stages/destroyAsg/aws/destroyAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/aws/destroyAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/cf/destroyAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/cf/destroyAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/gce/destroyAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/gce/destroyAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/determineTargetReference/determineTargetReferenceDetails.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/disableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/aws/disableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/cf/disableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/disableAsg/gce/disableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/aws/enableAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/aws/enableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/cf/enableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/enableAsg/gce/enableAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/resizeAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/resizeAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/cf/resizeAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/cf/resizeAsgStepLabel.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/gce/resizeAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/gce/resizeAsgStepLabel.html

Since we allow these operations to act on multiple regions, it would be nice to include the region in the step labels in the execution details so users don't have to click on each step to figure out where it was operating.
Also cleaning up some references to `asgName`, which should be `serverGroupName` now.
@duftler can you verify this works on GCE when you have a minute?

include region in *AsgStage label

---

app/scripts/modules/core/scheduler/scheduler.factory.js
app/scripts/modules/core/task/tasks.controller.js

* Allow schedulers to be constructed with different polling intervals
* Stop throwing NPEs when an application is not found on the tasks view

Custom scheduler/NPE fix on Tasks controller

---

app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js

Since `cloudProvider`/`cloudProviderType` are used in the lookup operation, we need to include that in the key that lodash uses when performing the memoization.
@duftler this should fix what you're seeing - PTAL

consider all relevant fields when memoizing stage config lookup

---

app/scripts/modules/netflix/help/netflixHelpContents.registry.js

Surprise, we were adding the Netflix-specific help contents to every build. This allows it to operate as an optional override.
@vjames-bmc Sorry! This is why you're seeing what you're seeing in https://github.com/spinnaker/deck/pull/2008. Once I get this merged, go ahead and rebase, then update that PR as I was suggesting.

Netflix help registry

---

app/scripts/modules/core/forms/mapEditor/mapEditor.component.html
app/scripts/modules/core/forms/mapEditor/mapEditor.component.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/google/serverGroup/configure/serverGroupAdvancedSettingsDirective.html
app/scripts/modules/google/serverGroup/configure/serverGroupAdvancedSettingsSelector.directive.js
app/scripts/modules/google/serverGroup/configure/serverGroupAdvancedSettingsSelector.directive.spec.js
app/scripts/modules/google/serverGroup/configure/wizard/CloneServerGroupCtrl.js

Define addButtonLabel on map-editor to override default 'Add Field' text.

Use fancy new map-editor instead of hand-rolling GCE Instance Metadata.

---

app/scripts/modules/core/presentation/refresher/componentRefresher.directive.html

In its current state, the tooltip shifts up and down as the refresh icon spins. We can avoid this horrible behavior by attaching the tooltip to the parent anchor tag.

include tooltip on anchor, not spinning icon

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/core/serverGroup/configure/common/serverGroupCommandBuilder.js
app/scripts/modules/kubernetes/cache/configurer.service.js
app/scripts/modules/kubernetes/container/configurer.directive.html
app/scripts/modules/kubernetes/container/configurer.directive.js
app/scripts/modules/kubernetes/image/image.reader.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/loadBalancer/transformer.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js
app/scripts/modules/kubernetes/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/templateSelection.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/templateSelection.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

This enables template selection in the pipeline deploy view, and starts the work needed to be able to select an image from among multiple "Find Image" stages. The reason why I allow multiple find image stages is because a single instance (pod) can house multiple containers. In order to disambiguate the "Find Image" stages, the current pipeline details are now passed into `serverGroupCommandBuilder.buildNewServerGroupCommandForPipeline` to discover all upstream "Find Image" stages. Presenting these stages to the user in the Server Group configuration, and sending the details to Orca will come in a later PR, namely, after I've generalized deploymentDetails.
@duftler 
@anotherchrisberry since I'm touching some of the `core` module, could you PTAL?

provider/kubernetes: Start work on deploy pipelines

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/modal/wizard/modalWizard.less
package.json
webpack.config.js

Splitting into separate bundles to reduce the bundles from one huge (~9MB) file to two very large (~4 and ~5MB) files.
Also bringing over the remaining styles needed from `angular-wizard` to remove that dependency.

bundle most vendor files into separate chunk

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.azure.controller.js
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.cf.controller.js
app/scripts/modules/google/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/titan/serverGroup/details/serverGroupDetails.titan.controller.js

If a user follows a deep link to a server group, it's possible the details load before the server groups for the application, leaving the `account` field unpopulated on the server group object, which can cause problems in any modal actions because we've (possibly unwisely) chosen to expect the `account` field (which comes from the summary object found in either the application's `serverGroups` or `loadBalancers`) instead of the `credentials` field, which comes from the details endpoint.
There are three ways to fix this problem:
1. Set the `account` field based on the URL path parameter (`accountId`)
2. Do not try to retrieve the server group details until the application's server groups are loaded
3. Change the `account` references to `credentials` everywhere
(1) is the easiest, which is …

backfill serverGroup account from parameters

---

app/scripts/modules/core/cache/infrastructureCaches.js
app/scripts/modules/core/cache/infrastructureCaches.spec.js
app/scripts/modules/core/history/recentHistory.service.js
app/scripts/modules/core/history/recentHistory.service.spec.js
app/scripts/modules/core/search/infrastructure/infrastructure.less
app/scripts/modules/core/search/infrastructure/project/infrastructureProject.directive.less

Who would have guessed that mucking with the cache internals might cause problems?
As it turns out, the angular cache factory's `removeAll` method does not call `remove` against each key in the underlying cache. So the intermediate cache I put in ten days ago (which keeps a cache of local storage items in memory to avoid the disk read penalty) never actually gets cleared when the cache is supposed to get cleared - so the old item just gets put right back into the local storage cache.
Also cleaning up the recent items on the infrastructure page to only show the most recent five items. Anything more involves scrolling, which is probably a non-starter for most users. We don't actually have metrics around this right now, so it's based on a guess and not actual data.

fix cache clearing; trim recent items to fit in container

---

app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.controller.spec.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.spec.js
app/scripts/modules/core/task/tasks.controller.js
app/scripts/modules/core/task/tasks.controller.spec.js
app/scripts/modules/netflix/fastProperties/modal/fastPropertyScopeBuilder.service.js

Removes some boilerplate and provides a simple promise that resolves when a section's content is loaded, or resolves immediately if it's already loaded. At the application level, it will resolve when all content is loaded.
@zanthrash this might be cleaner for the fast property scope builder - can you give it a shot?

add ready() method to application and sections

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js

Since we are setting the certificateId to whatever this method returns, we need to return the original value if we don't change it. Otherwise, we are going to remove certificates when people try to change their ELB and get a validation error, like Adam did, bringing down our UI for ten minutes.

do not overwrite explicitly configured certificate ARN

---

app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/azure/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/cloudfoundry/securityGroup/details/SecurityGroupDetailsCtrl.js
app/scripts/modules/core/account/accountSelectField.directive.html
app/scripts/modules/google/securityGroup/details/SecurityGroupDetailsCtrl.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

Three small things:
1. Use the larger modal size when editing canary clusters, since they are using the v2 modals
2. Allow editing and refresh of standalone security groups
3. Fixed a very old bug where account is not displayed in read-only mode when using `account-select-field directive`

Friday fixes

---

app/scripts/modules/core/modal/wizard/v2modalWizard.directive.js

Not sure how this happens exactly, but sometimes a waypoint gets snapshotted on a page that's either been removed or doesn't exist. This simply guards against that scenario causing an NPE by ensuring the page exists and is registered before trying to mark it as the current page.

do not try to set current page if it does not exist

---

app/scripts/modules/core/projects/project.controller.js

This is a better guard for an invalid project, or if Front50 or Gate is failing.

do not initialize project if no config found

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.directive.html
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.less
app/scripts/modules/core/pipeline/pipelines.less

Dealing with a handful of little things:
* Angular keeps fixing, then regressing, on this weird scenario where using `ng-class` and `class` on the same node with more than one interpolation (i.e. using `{{}}`) in the `class` causes the `ng-class` to stop working after the first application. So we're dropping it here and sticking with `class` for everything in this particular case.
* Fixing a navigation error where clicking on the active stage would throw an exception trying to navigate to a parent state in standalone mode
* Fixing styles for labels in the execution summary view in standalone mode
* Adding a little transition to stage labels and bar segments in the graphs. I think it looks nice but it may be annoying, in which case we can always remove it.

style tweaks, avoid state exception when toggling details

---

README.adoc

Changed the build folder name from dist to "build" since the npm run build command puts the file under build folder.

Fixed the build folder name

---

app/scripts/modules/core/projects/dashboard/pipeline/projectPipeline.directive.html

Fix for Issue#768. Pipelines displayed under Project don't show Judgement stage in yellow color. It shows correctly when opened in the application context. So a user wouldn't know that something needs attention by just looking at the project dashboard.
cc @anotherchrisberry

Fix for Issue#768 - Project pipeline status is incorrect

---

app/scripts/modules/core/cache/deckCacheFactory.js

Another case where local storage caches get corrupted somehow.

handle case where keys are emptied but data is not

---

app/scripts/modules/core/account/account.service.js

I realized the above function won't extract an attribute that doesn't have a `.name` field.

core/account: properly handle generic behavior in `getUniqueAttributeForAllAccounts`

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instance.details.controller.spec.js
app/scripts/modules/azure/instance/details/instance.details.controller.js
app/scripts/modules/azure/instance/details/instance.details.controller.spec.js
app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.js
app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.spec.js
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.spec.js
app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/instance/details/instance.details.controller.spec.js
app/scripts/modules/titan/instance/details/instance.details.controller.js

Deep linking to an instance almost never works right now, because we expect the server groups and load balancers to be there. If they're not (and, again, they almost always not), the details panel closes, assuming the instance is gone.
This changes that behavior by waiting for any supporting data sources (server groups, load balancers) to be ready before trying to initialize the instance details.
@robfletcher this fixes what we were seeing earlier this afternoon with deep links not working to instances.

do not instantiate instance details until application is loaded

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancerProperties.html
settings.js

A couple of changes:
1. Move the checkbox for "Internal" below the VPC/Subnet select field. Since the checkbox only appears after the user selects a subnet, the checkbox should not be above the select field.
2. Make the checkbox optional via a configuration setting. This is a feature needed at Netflix, since we've traditionally assigned the `internal` flag value based on the purpose or name of the subnet.

make internal flag for load balancers configurable

---

package.json

This is to fix the following warnings that appear when you run "npm install"
npm WARN package.json deck@0.0.0 No repository field.
npm WARN package.json deck@0.0.0 No license field.

Fix license and repo warning for "npm install"

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.html
app/scripts/modules/google/loadBalancer/configure/createLoadBalancer.html

Just wrapping the template in a `<form name="form">` tag so the submit button will actually disable when the form is invalid. This is a nice little regression nobody noticed until @vjames-bmc yesterday.
(If you tack `?w=1` to the end of the URL of this pull request, you can see that I really did just wrap the template)

validate load balancer form

---

app/scripts/modules/amazon/serverGroup/configure/wizard/advancedSettings/advancedSettings.html
app/scripts/modules/amazon/serverGroup/configure/wizard/capacity/zones.html
app/scripts/modules/amazon/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/amazon/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/azure/serverGroup/configure/wizard/basicSettings/basicSettings.html
app/scripts/modules/azure/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/google/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html

Having a form element in the basicSettings.html is causing a conflict with the newly added form tag in the ServerGroupWizard.html file which resulted in the call into the naming service not being executed.
This changes the form in basic settings to a div and adds a novalidate attribute to the form element on ServerGroupWizard.html.
@anotherchrisberry @duftler PTAL I have validated the Azure and AWS fix but I don't have a GCE account.  I also noticed that several of the other child pages in Google also have form elements but the remaining AWS pages do not (nor do the Azure). So there may yet be some side affects, particularly in Google.

Fix duplicate form elements causing naming failure

---

app/scripts/modules/core/account/account.service.js
app/scripts/modules/core/pipeline/config/stages/bake/bakery.service.js

Someone asked earlier today why the regions in the AWS bake stage are always `us-east-1`, `us-west-1`, `us-west-2`, and `eu-west-1`. I couldn't bring myself to say "look at L12 of bakery.service.js, and you'll see that we hard-coded it that way, but we return a promise to make you think we're getting them from some external data source", even if that is true. I didn't even respond at all. I made Tomás do it.
In a perfect world, where we never had users, this PR would be basically one line: replacing the `getRegions` method in the bakery service with:
```javascript
accountService.getUniqueAttributeForAllAccounts('regions')(provider).then(regions => regions.sort());
```
But in our world, we have users who have seen those four regions in that order for over a year, so they've probably gotten …

extract regions for AWS bake stage from credentials

---

app/scripts/modules/amazon/serverGroup/configure/wizard/serverGroupWizard.html

need this to keep Angular from blowing up, since the controller has a reference to the form, which is currently nested in an `ng-if`'d element which seems to cause grief on instantiation of the modal.

make form top-level node in AWS clone server group modal

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js
app/scripts/modules/kubernetes/serverGroup/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

The user can now specify which trigger corresponds to which image in Deck.
@duftler

provider/kubernetes: Populate deploy images with triggers

---

app/scripts/modules/core/pipeline/config/stages/disableAsg/kubernetes/kubernetesDisableAsgStage.js

_someone_ misspelled 'namespaces'.

provider/kubernetes: Fix namespace validation

---

app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/core/forms/autofocus/autofocus.directive.js
app/scripts/modules/core/task/verification/userVerification.directive.html
app/scripts/modules/core/task/verification/userVerification.directive.js

I had to change the `autofocus` directive, since it collides with the `autofocus` attribute, which is just part of the HTML spec.
This is one of those PRs that's best viewed with the ignore whitespace flag (i.e. `?w=1`) set in your URL.

autofocus account confirm box, allow enter to submit confirm modal

---

app/scripts/modules/core/confirmationModal/confirmationModal.controller.js

Yet another followup to the earlier pull request, which made it easier to submit a confirmation modal without clicking on anything, which also made it really easy to submit the same task multiple times. This really fixes that last part.

prevent repeated submits when user presses enter on confirm dialog

---

app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js

This is a temporary solution until I switch from `namespace` to `location`, making these operations more generic.
@duftler

provider/kubernetes: Load balancer orca stage needs to know which zones to refresh

---

app/scripts/modules/amazon/instance/details/instanceDetails.html

This adds a `TAGS` section to the instance details UI for AWS instances. This is similar to how the cluster tags are currently displayed for AWS ASGs. This is using data that was already available from the API; it just wasn't being exposed.

Show AWS instance tags on instance details.

---

app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/kubernetes/securityGroup/reader.js

Turns out it's needed to render security groups in the UI
@duftler

provider/kuberenetes: Added missing security group reader

---

app/scripts/modules/core/delivery/create/createPipelineModal.controller.js
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/pipeline/config/triggers/triggers.html

Added a checkbox in the configuration stage to ask users if pipelines in queue need to be cancelled. This is related to the issue https://github.com/spinnaker/spinnaker/issues/805 and orca PR https://github.com/spinnaker/orca/pull/767
This checkbox is shown only if the concurrent execution is enabled by checking the first check box.
Also added tooltip help.

Added a checkbox in the config stage to handle pipleines in queue

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/resizeAsg/kubernetes/resizeStage.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js

Cluster size and region were missing the deploy details, and the entire resize details pane were missing in Kubernetes pipelines. 
@duftler

provider/kubernetes: Fix fields missing from pipeline details

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/addScalingPolicyButton.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/scalingPolicy.write.service.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/scalingPolicySummary.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/scalingPolicySummary.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/simple/simplePolicyAction.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/simple/simplePolicyAction.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.less
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.less
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/modal/modals.less
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/task/monitor/taskMonitor.directive.js
app/scripts/modules/core/task/monitor/taskMonitor.directive.less
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

Initial cut of create/edit/delete operations for AWS scaling policies.
As long as you're not reusing alarms across policies, and not attaching multiple alarms to a policy, you are probably going to like this. Still need to add warnings for those scenarios.
If you're mostly using metrics that are scoped to an ASG, this is also going to be in your wheelhouse.
I will add more comments to this PR tomorrow. My laptop is shutting itself down every couple of minutes, so I am just going to get this PR started.
@zanthrash PTAL. I know it's too big to be legitimately reviewed.

create/edit/delete AWS scaling policy feature

---

app/scripts/modules/titan/serverGroup/configure/wizard/CloneServerGroup.titan.controller.js
app/scripts/modules/titan/serverGroup/configure/wizard/serverGroupWizard.html

We have a race condition the _second_ time a pipeline deployment command for titan is initialized: the command is ready immediately, which is before the wizard is initialized, so we get NPEs. This "fixes" that scenario by avoiding it altogether - the pages will automatically be marked as complete on render, so there's no need for the initialization block.

remove unneeded wizard state init code from titan

---

app/scripts/modules/core/securityGroup/securityGroup.read.service.js
app/scripts/modules/core/securityGroup/securityGroup.read.service.spec.js

In theory, this shouldn't happen, but if security group caches are out of sync, or we're not caching an account, or we don't know about a security group, we shouldn't throw exceptions when trying to attach inbound rules, so fallback to using the security group ID.

fallback to security group id when ingress rule not matched

---

app/scripts/modules/netflix/application/netflixCreateApplicationModal.controller.js
app/scripts/modules/netflix/chaosMonkey/chaosMonkeyConfig.directive.js

Change default Chaos Monkey meanTimeBetweenKillsInWorkDays from 5 days to 2
days, for consistency with existing Chaos Monkey behavior.

Update default chaos monkey config options

---

app/scripts/modules/azure/instance/details/instanceDetails.html
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.html

Cleanup VPC references in server group and instances details since these are not relevant when displaying Azure resource details

Cleanup VPC references in server group and instances details

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.less
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.spec.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/popover/scalingPolicyPopover.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.less
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/simple/simplePolicyAction.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/simple/simplePolicyAction.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.html
app/scripts/modules/core/help/helpContents.js

- adding legend to graph to provide more context about what the lines are
- including y-scale in popover graph
- changed text on "convert to step policy" action to clarify it does not persist the change immediately
- "Add action" is now "Add step"
- switching direction of threshold, e.g. `<` to `>`, clears existing steps
- step markers are presented in a more human readable format
- graph updates when statistic changes
- added help text and inline text to clarify dimensions and metrics/namespaces in advanced search view
- default adjustment step to "1"

various tweaks to scaling policies per user feedback

---

app/scripts/modules/core/pipeline/config/stages/resizeAsg/aws/awsResizeAsgStage.js

currently switching the control to 'scale to exact size' then back to 'scale up/down/to cluster size' leaves the resizeType as exact (unless the user goes and specifically changes that). This changes two things:
1) only figure out that we are in 'exact' mode if the action is unspecified. That change was in to handle the case of a pre-November 2015 created pipeline where exact was not an action
2) when selecting one of the other resize actions, ensure we always specify a resizeType (it falls through to increment by 0 as a default)
@spinnaker/netflix-reviewers PTAL

fixes population of default values when swapping between exact and incremental resize types

---

app/scripts/modules/netflix/report/reservationReport.directive.html
app/scripts/modules/netflix/report/reservationReport.directive.js
app/scripts/modules/netflix/report/reservationReport.directive.spec.js
app/scripts/modules/netflix/report/reservationReport.read.service.js
app/scripts/modules/netflix/serverGroup/resize/awsResizeServerGroup.html
app/scripts/modules/netflix/serverGroup/wizard/capacity/awsServerGroupCapacity.html
test/helpers/customMatchers.js

* Use v2 reservation report endpoint
* Differentiate between classic and VPC reservations
* Update report when account, region, zones, instance type, or VPC flag changes
* Avoid over-fetching reservation report when above values change
@ajordens for your review

differentiate between vpc and classic reservations in report

---

app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.spec.js

* adds a custom validator type for pipeline stages
* adds a `skipValidation` option for validator configurations, allowing a particular validator to not run if the function returns `true`
Utilizing the `skipValidation` method for Cloud Foundry server groups, so they don't throw warnings without a `findImage` or `bake` stage preceding them. If there are multiple clusters in the deploy stage and one of them is _not_ CF, it'll still show the warning.
Should fix https://github.com/spinnaker/spinnaker/issues/639

add skipValidation, custom validator functions to pipeline config

---

app/scripts/modules/core/modal/modals.less
app/scripts/modules/core/presentation/main.less

The issue was that the scroll bar in the modal cluster view (clone, create, edit in pipeline) was covering the delete icon for the load balancer and security group multiselect box.
I trimed the width down by 10px and styled the scrollbar in the modals to be thinner and not expand on hover.

Adding some right hand room to the multiselect ui-select box

---

app/scripts/modules/core/presentation/collapsibleSection/collapsibleSection.directive.html
app/scripts/modules/core/presentation/collapsibleSection/collapsibleSection.directive.js
app/scripts/modules/core/presentation/main.less
app/scripts/modules/kubernetes/container/configurer.directive.html

Recently, a change broke the collapsible sections I was using in the create server group dialog. I've been meaning to make the collapsible sections used inside the dialogs looks different (less bold than the modal wizard subheadings), so I used this time to both fix the collapsible sections to create a separate collapsible "subsection".
Before:
After:
@duftler @anotherchrisberry

core & kubernetes: Collapsible subheadings

---

app/scripts/modules/core/pipeline/config/stages/findAmi/aws/findAmiStage.html
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js

This is need for the findAmi stage to show all the regions, not just the ones that have a cluster deployed in them.
The default is "false" for this flag.

Adding show-all-regions flag on accountRegionClusterSelector component.

---

app/scripts/modules/core/application/listExtractor/listExtractor.service.js
app/scripts/modules/core/application/listExtractor/listExtractor.service.spec.js
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js

Occasionally a undefined cluster get passed into the filter throwing an error whenever the filter inspects it.
This is mainly for the for the account-region-cluster-selector component on the findAmi stage.
- also added a sort call on the get regions so they come back in a consistant order.

This is to prevent some JS errors that can happen on the cluster filters

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancerProperties.html
app/scripts/modules/amazon/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/amazon/securityGroup/configure/CreateSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupProperties.html
app/scripts/modules/amazon/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/amazon/subnet/subnetSelectField.directive.html
app/scripts/modules/amazon/subnet/subnetSelectField.directive.js

Adds the ability to restrict deployments to EC2 Classic for applications based on their creation date via Front50.
The locking functionality *only* kicks in when it's configured _and_ the application's `createTs` attributes is equal to or after the configured timestamp.

provider/aws: add feature to lock out EC2 Classic deployments

---

app/scripts/modules/amazon/logo/aws.logo.less
app/scripts/modules/cloudfoundry/logo/cf.logo.less
app/scripts/modules/core/cloudProvider/cloudProviderLogo.less
app/scripts/modules/google/logo/gce.logo.less
app/scripts/modules/kubernetes/logo/kubernetes.logo.less
app/scripts/modules/titan/logo/titan.logo.less

Turns out the CSS `mask` property is not supported yet in Firefox, IE, or Edge. Instead of seeing this nice provider icons like this:
users of those browsers see:
This changes that, so all users see the actual icon, not just the block of color.
Some would argue the approach to making this happen (inverting the color, adding a sepia filter to get it into the color spectrum, then rotating the hue of the resulting color) is a huge hack. That is obviously true, and if there's a better way to accomplish the same thing, I'm all for it - with the constraint being that providers only need to supply a black SVG icon.

color provider icons via CSS filters, not mask

---

app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.spec.js
app/scripts/modules/core/delivery/filter/executionFilter.service.js
app/scripts/modules/core/delivery/filter/executionFilter.service.spec.js
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.service.js
app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.service.spec.js
app/scripts/modules/core/securityGroup/filter/securityGroup.filter.service.js
app/scripts/modules/core/securityGroup/filter/securityGroup.filter.service.spec.js
package.json

Sadly, the update I made to angular-ui-bootstrap this morning uses a `debounce` attribute, which collides with a directive that the `debounce` module also includes.
So goodbye, debounce module. All hail lodash.

favor _.debounce over debounce

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/help/helpField.directive.html
app/scripts/modules/core/help/helpField.directive.spec.js

`popover` now supports HTML, so we can get rid of the template override

use built-in support for HTML popover contents

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/popover/scalingPolicyPopover.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.html
app/scripts/modules/amazon/serverGroup/serverGroup.transformer.js
app/scripts/modules/amazon/serverGroup/serverGroup.transformer.spec.js

Couple of things:
1. The popovers are getting the same, more human-readable treatment the edit modal got.
2. The steps are not guaranteed to return in a sensible order, so we need to sort them up front to avoid having what was configured as the last step potentially show up in the middle or beginning of the list of steps.
Current (edit modal, steps out of order, not showing threshold on last step):
Fixed:
Current (popover, less readable, unsorted):
Fixed:

fix step policy rendering inconsistency between popover and edit modal

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/serverGroup/serverGroup.transformer.js
app/scripts/modules/azure/azure.module.js
app/scripts/modules/cloudfoundry/cf.module.js
app/scripts/modules/core/cluster/allClusters.controller.js
app/scripts/modules/core/loadBalancer/AllLoadBalancersCtrl.js
app/scripts/modules/core/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.js
app/scripts/modules/core/securityGroup/AllSecurityGroupsCtrl.js
app/scripts/modules/google/gce.module.js
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/titan/titan.module.js

All providers have migrated to the v2 wizards, so this is no longer needed - nice job, everyone!

remove v2wizard flag

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/kubernetes/kubernetes.module.js

Prevents the warning message when adding a deploy stage to a pipeline when the user is only deploying to Kubernetes and there is no bake or find image stage before it.
@lwander PTAL

skip upstream check on kubernetes deployment clusters

---

app/scripts/modules/core/notification/notificationTypeConfig.provider.js
app/scripts/modules/core/notification/selector/notificationSelector.directive.js
app/scripts/modules/core/notification/selector/notificationSelector.html
app/scripts/modules/core/notification/types/email/additionalFields.html
app/scripts/modules/core/notification/types/hipchat/additionalFields.html
app/scripts/modules/core/notification/types/slack/additionalFields.html
app/scripts/modules/core/notification/types/sms/additionalFields.html
settings.js

Allow configuration of which notifications are available, and let users configure the name of the bot for HipChat and Slack that will send notifications, so they know who to invite into private rooms.
Also updating the notification directive to be a little more modern (replacing `$scope` with `vm`, using `bindToController`).
Corresponding PRs:
* echo: https://github.com/spinnaker/echo/pull/83
* spinnaker: https://github.com/spinnaker/spinnaker/pull/850

make notification options configurable

---

app/scripts/modules/azure/azure.module.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/azureDestroyAsgStage.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/destroyAsgExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/destroyAsgExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/destroyAsgStage.html
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/destroyAsgStepLabel.html
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js

This change enables the destroy server group operation for Azure through a pipeline. For that I followed mostly the AWS current implementation with some additional small tweaks. 
@anotherchrisberry can you please take a look?

Add implementation for Azure Destroy Server Group pipeline stage

---

app/scripts/modules/amazon/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/amazon/securityGroup/configure/CreateSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroup.html
app/scripts/modules/amazon/securityGroup/configure/createSecurityGroupIngress.html
app/scripts/modules/amazon/securityGroup/configure/editSecurityGroup.html
app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.html
app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.js
app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.less

Cross-account security group rules are a thing. We (mostly) support it in Orca/Clouddriver; this adds support to add cross-account ingress rules when creating or editing a security group.
One caveat: we are not supporting the creation of cross-account rules when creating multiple security groups at a time (by selecting multiple regions). There's a fair amount of work that needs to be done in Clouddriver to support this, and it can wait until someone asks for it.
I had bigger intentions of refactoring this code, but there are three functionally separate modals that use a lot of this code - create, edit, clone - and it's a mess. I got around 1500 LOC changed and wasn't close to having anything working, so I abandoned it and ended up with this.

provider/aws: allow creation of cross-account ingress sg rules

---

app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionDetails.controller.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionDetails.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionSummary.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.module.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.transformer.js

Allows a pipeline run an ACA task that does not require a newly deployed baseline or canary cluster.
An ACA Task can be run with a scope type of either query, cluster, and asg.
NOTE: Don't merge until downstream code is in place for ORCA and MINE

Adds a (Generic) ACA Task Stage.

---

app/scripts/modules/core/cluster/cluster.service.js
app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/cluster/filter/clusterFilter.model.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.spec.js
app/scripts/modules/core/cluster/filter/filterNav.html
app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/core.module.js
app/scripts/modules/core/job/job.module.js
app/scripts/modules/core/job/job.transformer.js
app/scripts/modules/kubernetes/job/job.module.js
app/scripts/modules/kubernetes/job/transformer.js
app/scripts/modules/kubernetes/kubernetes.module.js
test/mock/mockApplicationData.js

This is the first of a few PRs to surface jobs among clusters. It looks like this:
(The job has the diagonal lines). 
I still need to report health states correctly (for both the Job and the instances it's made of), as well as allow the user to use filters to select only Jobs or Server groups.
@duftler @anotherchrisberry PTAL

core: Surface job objects among clusters

---

app/scripts/modules/core/cluster/cluster.service.js

If there is a problem with the `jobs` or `serverGroups` endpoint, let's not crash and burn.

guard against failures from jobs/serverGroups endpoints

---

app/scripts/modules/netflix/migrator/migrator.less
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.modal.html
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.modal.html

Give the people their subnet type selection (but in a hard-coded, super opinionated, only going to work at Netflix or if your two subnets are "internal" and "external" way).

(netflix) allow users to select subnets when migrating to VPC

---

app/scripts/modules/core/application/application.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/navigation/navigation.less
app/scripts/modules/core/pipeline/pipelines.less
app/scripts/modules/core/presentation/details.less
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/projects/project.less
app/scripts/modules/core/task/tasks.less
app/scripts/modules/netflix/fastProperties/fastProperties.less

Chrome has supported unprefixed flexbox properties since at least v47 (v50 is current); Safari 9 also does not need the prefix.

remove -webkit prefix for flexbox

---

app/scripts/modules/core/cluster/filter/clusterFilter.service.js

Turns out lodash's `_.find` method will omit items without a supplied property, even if the matcher on that property is `undefined` - which means we are currently recreating every node in the clusters view every time the data refreshes or the user clicks on a deep link within the view, since it thinks every cluster group is new.

guard against missing property when filtering groups

---

app/scripts/modules/amazon/securityGroup/configure/configSecurityGroup.mixin.controller.js

Otherwise, a EC2 Classic security group in a newer application gets a vpcId, which is never correct when editing a security group.

(aws) only apply vpcId to new security groups when classic lock enabled

---

app/scripts/modules/core/presentation/main.less

Starting with Chrome 50, we're seeing this really annoying behavior where the entire screen shifts to the left sometimes, removing any margin present. This fixes that.

use flexbox to center container

---

app/scripts/modules/core/cluster/cluster.service.js
app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.spec.js
app/scripts/modules/core/cluster/filter/multiselect.model.js
app/scripts/modules/core/cluster/filter/multiselect.model.spec.js
app/scripts/modules/core/filterModel/filter.model.service.js
app/scripts/modules/core/job/job.directive.html
app/scripts/modules/core/job/job.directive.js
app/scripts/modules/core/job/job.module.js
app/scripts/modules/core/job/job.read.service.js
app/scripts/modules/core/navigation/states.provider.js
app/scripts/modules/kubernetes/job/details/details.controller.js
app/scripts/modules/kubernetes/job/details/details.html
app/scripts/modules/kubernetes/job/job.module.js
app/scripts/modules/kubernetes/kubernetes.module.js
test/mock/mockApplicationData.js

@anotherchrisberry @duftler 
Allows user to select jobs in cluster screen and brings up a job dialog:
I still need to get filters to work, and make new widgets for completed (failed and succeeded) jobs.

provider/kubernetes: Create job details dialog

---

app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js

This loads the first configured account as a backup when no primary account were selected. Otherwise the create server group dialog fails to load. (Create load balancer & security group already work).

provider/kubernetes: Non primary account failing to load

---

app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js

Canary stages don't have a `provider` field

provider/netflix: support VPC migration when no provider specified on canaries

---

app/scripts/modules/core/application/applicationNav.html
app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/application/service/applications.read.service.spec.js
app/scripts/modules/core/delivery/executions/executions.controller.js
app/scripts/modules/core/delivery/executions/executions.controller.spec.js
app/scripts/modules/core/pipeline/config/actions/delete/deletePipelineModal.controller.spec.js
app/scripts/modules/core/pipeline/config/actions/rename/renamePipelineModal.controller.spec.js
app/scripts/modules/core/task/tasks.controller.js
app/scripts/modules/core/task/tasks.controller.spec.js
app/scripts/modules/netflix/application/applicationNav.html
app/scripts/modules/titan/serverGroup/serverGroup.transformer.js

When an application has a lot of pipelines and a lot of executions of those pipelines, it gets expensive to eagerly load them when the user is not actively looking at the pipelines view.
This change shifts the initialization of those views to their respective controllers (pipelines, tasks). When the user exits those views, the data will be cleared on the next application refresh.
Running against larger applications at Netflix, I am seeing a pretty big drop in memory consumption from the browser. This should also help take some of the load off Orca, since we're not constantly bombing it with data requests.
The downside: when a user navigates to the pipelines or tasks view the first time, the data needs to be fetched before it can be rendered. We'll have to watch this and see if users …

(core) lazy load tasks, executions

---

app/scripts/modules/core/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/pipeline/config/pipelineConfig.controller.spec.js

`pipelineConfigs` are lazy loaded now, so we need to activate that section when loading the config page

fix deep link issue with pipeline configs

---

app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.html
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.modal.html

* infer new pipeline name from current pipeline
* change the "Close" button to "Review {{new name}}"
* if the pipeline has already been migrated, replace "Migrate to VPC0" with a link to "View migrated pipeline"
* don't navigate to the new pipeline config until the user clicks the "Review" button

(netflix) fix pipeline name, navigate to new pipeline on modal close

---

app/scripts/modules/core/cluster/filter/clusterFilter.controller.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/filterNav.html

We're still on lodash v3.10.x, so `_.sortBy` and `_.sortByAll` are different methods.
Also, hide the "Category" filters if there's only one category. Also, display the category if one is present.

hide category filter if only one category; fix cluster sorting

---

app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/loadBalancer/configure/healthCheck.html
app/scripts/modules/azure/loadBalancer/configure/listeners.html
app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/azure/serverGroup/details/serverGroupDetails.azure.controller.js
app/scripts/modules/core/pipeline/config/stages/destroyAsg/azure/azureDestroyAsgStage.js
app/scripts/modules/core/pipeline/config/stages/disableAsg/azure/azureDisableAsgStage.js
app/scripts/modules/core/pipeline/config/stages/enableAsg/azure/azureEnableAsgStage.js

This enable Azure Application Gateway as the Spinnaker Load Balancer when targeting Azure cloud. Only HTTP protocol is supported at the moment (HTTPS will be added later).
Fixed couple issue related to instance health check; we need to shortcut these checks for now.

Use Application Gateway as a Load Balancer for Azure 

---

app/scripts/modules/netflix/chaosMonkey/chaosMonkeyExceptions.directive.js

Don't restrict accounts for Chaos Monkey exceptions to aws. This will enable users to add exceptions for apps running on Titus.

Chaos Monkey exceptions: Don't restrict to aws

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.spec.js
app/scripts/modules/amazon/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.html
app/scripts/modules/amazon/serverGroup/serverGroup.transformer.js
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancersTag.html

AWS allows users to attach any load balancer to any ASG, regardless of its VPC association.
We're taking a more opinionated approach here, only allowing Classic ASGs to attach to VPC load balancers (not letting VPC ASGs attach to Classic ELBs). This is to help folks migrate away from Classic by slowly shifting traffic over to VPC instances.
We don't expect this to be heavily utilized, but it's important for teams that need to migrate over incrementally.
(If the link is clicked, or VPC load balancers have been selected)

(aws) Allow selection of VPC load balancers on Classic ASGs

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

This happens when people only fill out half their canary canary configs

(netflix) guard against garbage canary stages

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionDetails.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.html

This allows pipeline to continue if the canary comes back unhealthy.
Candmium requested this feature b/c they want to put ad a manual judgement after the ACA task stage.
- Aslo fixes long baseline and canary strings from blowing out of their boundries on the ACA task summary view.
- Fixes the link back to the RTA ACA configuration page.
NOTE: Do not merge until downstream ORCA changes are in place.

Adds continureOnUnhealthy to canaryConfig

---

app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.js
app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.spec.js

Adjusting validation regexes to allow $, {, and } chararacters for the stack and details fields.

Fixes SPIN-1772

---

app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.js
app/scripts/modules/core/pipeline/config/stages/optionalStage/optionalStage.directive.html
app/scripts/modules/core/pipeline/config/stages/optionalStage/optionalStage.directive.js
app/scripts/modules/core/pipeline/config/stages/stage.html
app/scripts/modules/core/pipeline/config/stages/stage.module.js

- an expression can be used to govern whether a stage should execute or be skipped

Support for <optional> pipeline stages

---

app/scripts/modules/amazon/vpc/vpcTag.directive.js
app/scripts/modules/amazon/vpc/vpcTag.directive.spec.js

Initial load of the vpcTag was showing "EC2 Classic" as it's label if the vpc data was not pulled down.  Once it was loaded the correct subnet would show.  This was leading to some confusion to users who had recently upgraded to VPC0.
Removed the default "EC2 (Classic)" label and replaced with a spinner.

Fixes SPIN-1797

---

app/scripts/modules/core/presentation/details.less

This is prevent the new longer instance ids from wrapping in the header.

Bumping the font size down 1px for the details h3 tag

---

app/scripts/modules/core/widgets/index.js
app/scripts/modules/core/widgets/spelText/spel.less
app/scripts/modules/core/widgets/spelText/spelText.decorator.js

Decorates the input and textarea directives and detects if the user starts typing a SpEL in the fields (looks for the '${' string).  If detected, it injects a link to the spinnaker.io documentation under the text field.
If the SpEL is removed so is the link.

Adds link to Expression Docs on text inputs

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.spec.js

On initial load of the application the code would attempt to read from the application severGropus before they were loaded causing some asg detail info to go missing (i.e. vpcId)
This was causing the vpcId not to be bound to the asg details on load and in turn display "None (EC2 Classic)" in the VPC field for ASGs that where in vpc0.
This changes leverages the app.ready() promise to verify that all the apps bits are in place before we read them.

Fixes SPIN-1772 Promise-ifying all the things.

---

app/scripts/modules/core/authentication/authentication.initializer.service.js

Prevents an endless stream of messages telling the user they've been logged out.

stop checking authentication after user has been logged out

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/authentication/authentication.service.js

Once authentication has expired, we should stop sending requests to gate, since they're just going to start the redirect-to-auth process.
We already do this before the user has been authenticated, so we just need to return the user object to that same state by setting the `authenticated` flag to false.

hold non-auth calls when auth is expired

---

app/scripts/modules/core/authentication/authentication.interceptor.service.js
app/scripts/modules/core/authentication/authentication.interceptor.spec.js
app/scripts/modules/core/authentication/authentication.module.js
app/scripts/modules/core/authentication/authentication.service.js
app/scripts/modules/core/scheduler/scheduler.factory.js
settings.js

At some point, `pausable` seems to have stopped working altogether - at least the `pause` call has stopped `paus`ing requests, which is the whole point of using `pausable`. It's not hard to mimic the `pause`/`resume` behavior with a local variable, so there.
That's part 1. Part 2 holds pending http requests when the user authentication is older than the refresh window. This should hold calls whenever the authentication check is happening, then allow them through when authentication is successful.

fix scheduler; hold requests when auth is expired

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executions/executions.html
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/delivery/filter/executionFilter.model.js

Adds a checkbox to the top of the page to allow users to see how long each stage took.
Unselected (current behavior):
Selected:

allow user to show stage durations

---

app/scripts/modules/core/task/tasks.controller.js

Either this never worked or we had `$state` on the `$rootScope` and removed it at some point. Probably the latter. Probably my fault. Let's not point fingers, though; the important thing is we're fixing today's problems today.

(core) fix copy-to-clipboard link on task permalink

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/status/executionStatus.html

Because we do this thing where we replace an execution if anything in its JSON changes between refreshes, we don't need to add watches for most fields in the executions view.
We _do_ need watches on the running time (since active stages will increment, even if nothing changes in the JSON of the execution) and the details toggle.
Adding these one-time bindings cuts the number of watches on the executions view by around half and everything consequently feels a little snappier when clicking around on the page, especially with lots of executions showing.

(core) use one-time binding wherever possible in executions view

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js

We currently conflate the alarm `statistic` with the step `metricAggregationType`.
Via the AWS console, a user cannot set the `metricAggregationType` - it's always 'Average' - so we'll follow suit.

(amazon) always use "Average" for metricAggregationType

---

app/scripts/modules/core/delivery/status/executionStatus.html

Id like to see which docker image triggered the pipeline at a quick glance.  Adding it to the execution status like Jenkins does.

Add docker repo:tag to pipeline

---

app/scripts/modules/netflix/alert/alertHandler.js

Errors were not posting to Atlas b/c the Atlas endpoint is http and we are hosted out of https, so error were not being sent because of a Mixed Content error
We are now posting to GATE and letting it post to ATLAS.
Removing the sending via navigator becon b/c it defaults the Contet-Type to text/plain and you cant set headers, so just using the ajax POST.

Fix JS error posting to Atlas Alerts

---

app/scripts/modules/core/pipeline/config/actions/json/editPipelineJson.module.js
app/scripts/modules/core/pipeline/config/actions/json/editPipelineJsonModal.controller.spec.js
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/pipeline/config/services/pipelineConfigService.js

The `stageCounter` doesn't need to exist. We are better off getting the next `refId` for a stage by incrementing the max value of the other stages' `refId`s.

(core) remove stageCounter

---

app/scripts/modules/core/pipeline/config/stages/runJob/runJobStage.js

Run job stage fix: no longer asks for provider choice unnecessarily when adding jobs.
@lwander PTAL (this was more straightforward than I thought).

run job stage fix: provider choice

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.less

This looks 100 times better.
_Before_
After

(core) stage duration dividers are now white

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

Replacing `registry` with `account` broke the trigger logic in Orca. Pointed out by @leelasharma

provider/kubernetes: Fix docker trigger

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.js

Setting the command.adjustentType when the viewState.operator changees.
When the Action operator changed it did not set it's value on the command.adjustmentType; which is what is sent in the POST to /task
This resulted in the task to always post the default "ChangeInCapacity" and now allow "ExactCapacity" to be set on the command object when the "Set to" option was chosen.

Fixes Auto Scaling bug.

---

app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js

(gce) fixes bug that prevented clone wizard instance type population
@duftler PTAL
This line was supposed to clear the instance type when the custom fields are malformed (e.g. when you pick a zone that doesn't support the vCPU count), but the rest of the function handles this logic properly (and doesn't cause the bug).

(gce) fixes bug that prevented clone wizard instance type population

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/instance/gceInstanceType.service.js
app/scripts/modules/google/instance/gceVCpuMaxByLocation.value.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.gce.service.js

(gce) prevent invalid selection of instance types for location
"getAvailableTypesForRegions" is kept as an alias of "getAvailableTypesForLocations" because it is one of the core functions expected of a provider.
@duftler PTAL

(gce) prevent invalid selection of instance types for location

---

app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionDetails.controller.js

Switching b/t 2 ACA tasks stages would display stale detail info.  This was due to a race condition between fetching the canary on stage change and fetching its detail info.

JIRA-1849: Runtime issue with ACA Task stage details.

---

app/scripts/modules/kubernetes/instance/details/details.controller.js

(kubernetes) instance refresh fix
This was preventing instances from being updated. 
It was also the source of the "$scope.$on is not a function" error that Steven reported.
@lwander PTAL

(kubernetes) instance refresh fix

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/cluster/cluster.service.js
app/scripts/modules/core/presentation/collapsibleSection/collapsibleSection.directive.html
app/scripts/modules/core/presentation/collapsibleSection/collapsibleSection.directive.js
app/scripts/modules/core/presentation/details.less
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

We've run into some unfortunate situations where users inadvertently disable autoscaling. This happens when a user resizes a disable ASG, then enables the ASG before the resize completes.
When the resize operation starts, Orca flips on the Launch and Terminate processes. The enable operation enables Launch, Terminate, and AddToLoadBalancer. After the ASG has been resized, Orca flips Launch and Terminate back to their original state.
This PR does two things:
1. Adds a warning icon next to the Scaling Processes and Scaling Policies/Scheduled Actions section heading if Launch or Terminate are disabled and the ASG has scaling policies or scheduled actions
2. Disables the "Enable" action if a resize operation is running
There's still a chance the user can mess this up - if the running tasks do …

(aws) alert user to impedance with suspended processes

---

app/scripts/modules/core/task/monitor/taskMonitorService.js
app/scripts/modules/core/task/monitor/taskMonitorService.spec.js
app/scripts/modules/core/task/tasks.controller.js

Refreshing the running tasks attaches them immediately to the object being operated against, which is nice.
Also fixing the initialization order in the tasks view. Since the tasks are lazy loaded, we need to activate the tasks _before_ we call `ready()` on the section, or it'll always return immediately.

(core) fix load order on task view, refresh tasks when task starts

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/core/serverGroup/serverGroup.directive.js

Part of a series of PR adding build info support for travis integration on AWS
by adding new build_info_url tag to the images in order to be able to full fill the build info correctly for travis.
This PR checks if the build_info_url is present and uses it as ci link
This is the final result
Related PRs
spinnaker/orca#856
spinnaker/rosco#102
https://github.com/spinnaker/clouddriver/pull/652

Travis support for deck

---

app/scripts/modules/netflix/alert/alertHandler.js

Using jQuery's `ajax` method does not pass the request through the authorization interceptor, so auth headers are not included and the request is intercepted by Gate when auth is enabled.

(core) use $http to send exception alert

---

app/scripts/modules/core/application/application.html
app/scripts/modules/core/application/application.less
app/scripts/modules/core/application/applicationNav.html
app/scripts/modules/netflix/application/applicationNav.html

Per discussions with our designer, we're moving the "Page application owner" button to the right edge of the header:
_Current_
_Revised_
Also making the header a little cleaner for smaller screens and longer application names

(core) move page app owner button to the right

---

app/scripts/modules/core/serverGroup/serverGroup.write.service.js

Needed for non-default-bake-account updates
cc @ajordens

(aws) send amiName when updating security groups

---

app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/transformer.js

@danielpeach fyi
The Create/Clone operations were associating the wrong health provider name, causing unhealthy configured pods to deploy correctly. I ignore application-level health config since Kubernetes only exposes platform health, making selecting the health providers redundant.

(kubernetes) Select correct health provider names for k8s

---

app/scripts/modules/core/delivery/service/execution.service.js

When the user clicks the "Clear All" button, `status` is set to `undefined`, so the next call to get filtered executions blows up.

(core) guard against missing filters on executions

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/healthCounts/healthCounts.less
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancersTag.html
app/scripts/modules/core/presentation/main.less

Changes to:
*Multiple load balancers button*
Current:
Revised to:
*Instance counters (unknown/starting icon - blue diamond)*
Current:
Revised to (smaller):

(core) improve readability of health counters/load balancer button

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

@tomaslin PTAL - avoids the NPEs when calling `trim` before the `tag` field has been initialized.

(docker) guard against undefined when clearing trigger tag

---

app/scripts/modules/core/forms/uiSelect.decorator.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/wizard.html

(k8s) require container selection has visual cue
@lwander this is all so that the little dot next to "Basic Settings" is grey instead of green if you haven't picked a container.
@anotherchrisberry PTAL, I had to modify the uiSelect decorator to make required work properly. This seems to be a known bug for ui-select-match. Let me know if you have a better idea.

(k8s) require container selection has visual cue

---

app/scripts/modules/core/confirmationModal/confirm.html
app/scripts/modules/google/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/google/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/google/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/google/serverGroup/details/rollback/rollbackServerGroup.html

@anotherchrisberry small change to core confirmation modal. 
It fixes a little visual bug: if you type in a user confirmation (e.g. in a confirm resize modal), press enter, then press another key, you'll get a something like this:

(core) fixes visual bug in confirmation modal

---

package.json

something is breaking sortable in 1.12.0, which prevents sorting pipelines and links

(core) pin jquery ui to 1.10.5

---

app/scripts/modules/core/delivery/details/singleExecutionDetails.controller.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/scheduler/scheduler.factory.js

With these changes, the `<execution>` directive will more aggressively poll and update (once every two seconds) any running executions, which makes monitoring running executions a little easier.

(core) actively refresh running executions when displayed

---

app/scripts/modules/core/widgets/notifier/notifier.component.less

A user felt that the logged out notification was way too discreet.

(core) increased notifier size

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/service/execution.service.js

1. If the execution is unchanged, leave it be
2. Add the `stringVal` so it doesn't necessarily get swapped out when all the executions are reloaded
3. Make sure to call the `refreshStream.onNext` so that the execution groups are updated

(core) trigger executions refreshStream when replacing

---

app/scripts/modules/kubernetes/container/probe.directive.html
app/scripts/modules/kubernetes/container/probe.directive.js

(k8s) http header support in wizard. Headers are copied properly for cloning and pipelines.
@lwander PTAL

(k8s) http header support in wizard

---

app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.less
app/scripts/modules/core/delivery/manualExecution/notifications.tooltip.html
app/scripts/modules/core/notification/selector/notificationSelector.directive.js

UI changes to go with https://github.com/spinnaker/gate/pull/259
Adds a single notification whenever the pipeline fails or completes, prefilled with the user's email address (if authenticated).
(Updated PR with a less obtrusive view of existing notifications)

(core) allow user to add ad-hoc notification to pipeline execution

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/authentication/authentication.provider.spec.js

Same as https://github.com/spinnaker/gate/pull/257
It should prevent infinite loop when using Github OAuth when no public is defined for the user.
@ttomsu @anotherchrisberry PTAL

Use Username instead of Email to identify authenticated user

---

app/scripts/modules/core/projects/dashboard/dashboard.controller.js
app/scripts/modules/core/projects/dashboard/dashboard.controller.spec.js

@zanthrash @anotherchrisberry 
(core) prevent project dashboard error when no clusters configured

(core) prevent project dashboard error when no clusters configured

---

app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.service.js

Cadmium has a very long pipeline graph that and the overflow-x: auto kicks in.
Due to the change in the fetch interval to 1 second, when every the user scrolls the to the right when the graph repaints it resets the letfScroll on the graph to zero, creating a very frustrating user experience.
This seem to only happen when the pipeline is Running.
This fix adds a mousewheel event (scroll was not firing) on the <pipeline-graph> element.  It then saves the scrollLeft posisiton of the scrollbar off to the pipelineGraphService.
When the svg graph redraws it get the scrollLeft offset from the service and sets it.  This prevents the scroll bar from jumping back to the zero position every second.

SPIN-1900: Track scrollbar position on pipeline graph

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js

We're seeing an issue where the build output from Travis is dropping some `\a` characters from the LineChart.css file. I cannot reproduce this locally. I am crossing my fingers that bringing in the minified version of the CSS will somehow sweep this problem under the rug.

(aws) import minified version of LineChart css file

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/LineChartHack.css
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js

Probably not the worst hack in the application.
Workaround for https://github.com/n3-charts/line-chart/issues/512, which is causing the scaling policy charts to be styled incorrectly.

(aws) hack in CSS fix for n3-charts library

---

app/scripts/modules/netflix/chaosMonkey/chaosMonkeyConfig.directive.js
app/scripts/modules/netflix/chaosMonkey/chaosMonkeyConfigFooter.directive.js

Otherwise, saving, then toggling between tabs quickly might result in the old chaos monkey settings appearing

(netflix) apply chaos monkey config to application after saving

---

app/scripts/modules/core/securityGroup/filter/securityGroup.filter.service.js
app/scripts/modules/core/securityGroup/filter/securityGroup.filter.service.spec.js
app/scripts/modules/core/securityGroup/securityGroup.directive.js
app/scripts/modules/core/securityGroup/securityGroup.html
app/scripts/modules/core/securityGroup/securityGroup.read.service.js
app/scripts/modules/core/securityGroup/securityGroupPod.html

Addressing three problems here:
1. It's hard to tell what VPC a security group is in without clicking on it and looking at the details
2. If there are two security groups with the same name in the same region (e.g. VPC and Classic), their display order is not guaranteed and may change with each application refresh
3. Usage fields are not made unique, since `_.uniq` does not take a comparator as its second argument.

(core) avoid duplicate usages on security group view

---

app/scripts/modules/core/application/application.less
app/scripts/modules/core/cluster/all.html
app/scripts/modules/core/delivery/executions/executions.less

Also tweaking the heading on the clusters view to make it less bad on smaller viewports.

(core) prevent execution headings from bleeding into page headings

---

app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js

Corresponding change in Clouddriver to address https://github.com/spinnaker/spinnaker/issues/1020 here: https://github.com/spinnaker/clouddriver/pull/817

(aws) only set vpcId on cross-account ingress rules

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js

otherwise, when there's a `waitForRequisiteCompletion` stage, we can end up with a stage summary that's running, but it's only running in the sense that it's waiting for its parent stages to complete.

(core) omit initialization stages when generating stage summaries

---

app/scripts/modules/core/task/task.write.service.js

Since the `taskWriter` is a singleton, calls to `getEndpoint` currently stack on top of one another, so Deck tries posting tasks to:
* `applications/app/tasks`, then
* `applications/app/tasks/app/tasks`, then
* `applications/app/tasks/app/tasks/app/tasks`, etc.
cc @zanthrash

(core) allow multiple tasks to be executed in same browser session

---

app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskExecutionDetails.controller.js

prevents "Cannon read property 'canaryDeployments' of undefined" error.

fix JS error

---

app/scripts/modules/core/application/config/applicationConfig.controller.js
app/scripts/modules/core/application/config/applicationConfig.view.html
app/scripts/modules/core/application/config/serializeApplicationSection.component.html
app/scripts/modules/core/application/config/serializeApplicationSection.component.js
app/scripts/modules/core/serialize/serialize.write.service.js
settings.js

Added a section to the config tab to serialize the application. Feature flag for serialize must be set to true in settings.js in order to view the section. PTAL @lwander @duftler @danielpeach

core: added a section to the application config tab to serialize the application infrastructure

---

app/scripts/modules/core/delivery/service/execution.service.js

(core) fixes execution filter refresh
Currently, the query string will include RUNNING even if sortFilter.status = { RUNNING: false }.

(core) fixes execution filter refresh

---

settings.js

Default will still be that running `npm start` will have auth enabled, but can be overridden via `AUTH_ENABLED=false npm start`. 
@tomaslin wants this because something docker blah blah I don't know.

(core) allow auth to be disabled via environment variable

---

app/scripts/modules/google/loadBalancer/details/hostAndPathRules/hostAndPathRules.service.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js

Fixes host and path rules modal.
Allows L7 load balancer details panel to open from the clusters tab. (The approach here isn't great, but the core pieces assume that serverGroup.region === loadBalancer.region. I'll wait until the rest of the L7 pieces are in place before coming up with a better approach.)
@duftler @jtk54 please review.

(gce) fix host and path rules modal

---

app/scripts/modules/core/deploymentStrategy/strategies/highlander/highlander.strategy.module.js
app/scripts/modules/core/deploymentStrategy/strategies/redblack/redblack.strategy.module.js

A user pointed out that the current text is misleading, since highlander and red/black affect all previous server groups, not just the base server group.

(core) clarify that deployment strategies affect all server groups

---

app/scripts/modules/core/cluster/filter/clusterFilter.controller.js
app/scripts/modules/core/cluster/filter/clusterFilter.controller.spec.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.js
app/scripts/modules/core/cluster/filter/clusterFilter.model.spec.js
app/scripts/modules/core/cluster/filter/filterNav.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.js

(core) cluster filters filter zones and regions by account
(e.g., if you click on an account checkbox, it will filter the region and zone checkboxes).
@anotherchrisberry please review, @duftler fyi
I'll make the load balancer filters consistent with this behavior.

(core) cluster filters filter zones and regions by account

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/azure/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/cloudfoundry/loadBalancer/details/LoadBalancerDetailsCtrl.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js

Deep linking doesn't work so great without this, since we extract the load balancer from the application data, then layer in the details.

do not load load balancer details until all app load balancers are ready

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/config/versionCheck.service.js
app/scripts/modules/core/presentation/less/imports/colors.less
app/scripts/modules/core/widgets/notifier/notifier.component.html
app/scripts/modules/core/widgets/notifier/notifier.component.js
app/scripts/modules/core/widgets/notifier/notifier.component.less
app/scripts/modules/core/widgets/notifier/notifier.service.js
app/scripts/modules/core/widgets/notifier/userNotification.component.js

* notifications are objects, with a `key`, `body`, and `position` (top or bottom)
* notifications replace each other via the `key` property, so duplicate notifications don't happen
* top-level notifications have a light orange background to make them more visible
* when the user gets logged out and has multiple tabs open, they no longer have to reload each tab to re-authenticate - logging into a single tab is enough, as we now watch the document visibility and check authentication when a tab becomes visible.

(core) notification enhancements

---

app/scripts/modules/core/authentication/authentication.initializer.service.js

Not the most egregious memory leak, but it's still unnecessary to retain this once authentication has occurred.

(core) dispose visibility watcher once user has authenticated

---

app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js

removes the brief flash of the dry run results when starting the migration

(netflix) clear migration task after dry run

---

app/scripts/modules/amazon/instance/awsInstanceType.service.js
app/scripts/modules/amazon/instance/awsInstanceType.service.spec.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/wizard/CloneServerGroup.aws.controller.spec.js

Newer instance types are only available in VPC, so we should prevent users from attempting to launch VPC-only instances in EC2 Classic.

(aws) filter instance types by VPC

---

app/scripts/modules/core/api/api.service.spec.js
app/scripts/modules/core/projects/service/project.write.service.js
app/scripts/modules/core/task/task.write.service.js

Upserting a project doesn't correctly pull the project name out of the taskCommand when creating the URL for the POST method.  This cases a 405 Method Not Allowed error.
Adding the project to the taskCommand payload to the taskExecutor.  Also checking for project name when constructing the url for the POST call.

SPIN-1921: Fix upsert of projects.

---

app/scripts/modules/openstack/cache/cacheConfigurer.service.js
app/scripts/modules/openstack/common/cacheBackedSelectField.template.html
app/scripts/modules/openstack/common/refresh.tooltip.html
app/scripts/modules/openstack/common/selectField.component.html
app/scripts/modules/openstack/common/selectField.component.js
app/scripts/modules/openstack/instance/openstackInstanceType.service.js
app/scripts/modules/openstack/instance/osInstanceTypeSelectField.directive.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/location.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/loadBalancer/loadBalancerSelectField.directive.js
app/scripts/modules/openstack/network/networkSelectField.directive.html
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/openstack/subnet/subnetSelectField.directive.html
app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Add ability to refresh select fields for openstack cached entities.
Refactor select fields to consolidate common functionality.
Add select field directives for load balancers and instance types.

Add ability to refresh select fields for openstack cached entities

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/instance/instanceList.directive.html
app/scripts/modules/core/instance/instanceList.directive.js
app/scripts/modules/core/instance/instanceListBody.directive.js

The `instanceGroups` get cleared whenever "Edit Multiple" is toggled, so we need to re-fetch it every time we re-render instances.
Also providing some more space for instance ids to accommodate Amazon's new, longer ids.

(core) fix multiselect toggle behavior, handle longer instance ids

---

app/scripts/modules/core/pipeline/config/stages/baseProviderStage/baseProviderStage.js

In the interest of under-engineering until we have a better idea of any similar use cases, expose the docker bake stage via a feature flag.
@duftler PTAL - does this work for you? Would need to set `dockerBake: true` in the `feature` block in settings.js to see this, which ends up exposing the existing docker bake stage.

(docker) allow docker bake stage via feature flag

---

app/scripts/modules/kubernetes/job/configure/wizard/Clone.controller.js

Fixes the job clone wizard (bug surfaces when trying to edit a job in a pipeline). I made a similar fix in the server group wizard controller but forgot to update jobs.
Also updated the markComplete calls, since the job wizard does not have a replicas page.
@lwander PTAL

(k8s) fix job clone wizard

---

app/scripts/modules/core/api/api.service.js
app/scripts/modules/core/api/api.service.spec.js
app/scripts/modules/core/cache/deckCacheFactory.js
app/scripts/modules/core/pipeline/config/services/pipelineConfigService.spec.js

If authentication expires, ajax requests follow the redirect and end up getting a 200 response with the authentication page, so they're not rejected.
This change looks for `<html` as the start string of a response, then triggers reauthentication and rejects the request.
In the cache factory, we won't set an item if it's an http response following a similar pattern.
Tested locally "pretty extensively".

(core) validate response data is not authentication page-like

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/core/pipeline/config/stages/findAmi/findAmiStage.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsExecutionDetails.html
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsStage.html
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsStage.js
app/scripts/modules/core/pipeline/config/stages/findImageFromTags/findImageFromTagsStage.module.js

- Similar to `Find Image from Cluster` but supports scenarios where an image is not currently deployed (but is tagged)
- Relates to the `Tag Image` stage

Find Image from Tags

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/loadBalancer/elSevenUtils.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/elSevenOptions/backendServiceSelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancers.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/openstack/loadBalancer/loadBalancerSelectField.directive.js

@jtk54 please review
- makes backend service, port name mapping, and capacity metrics required in the server group wizard.
- disables deregistering from load balancer if server group is attached to an l7 load balancer.

(gce) more l7 fixes

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.html
app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

- SPIN-1920: Expose option to select the global Atlas dataset for both ACATaskStage and CanaryStage.
- SPIN-1939: Add email recipients to ACATask and Canary Stages, allows for comma seperated list of emails or a SpEL

Expose Global ACA Dataset & Add email recipiants for Canary Stages

---

app/scripts/modules/core/search/global/globalSearch.controller.js
app/scripts/modules/core/search/global/globalSearch.directive.html
app/scripts/modules/core/search/global/globalSearch.less

We had this long ago, but it stopped working with some update and we never restored it. I am guessing the vast majority of users don't know you can just type `/` to get to the global search...

(core) add tooltip to global search

---

app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/instanceType/instanceType.html

(gce) forces user to pick zone before instance type
also fixes a load balancer refresh bug.
@duftler PTAL

(gce) forces user to pick zone before instance type

---

app/scripts/modules/amazon/serverGroup/serverGroup.transformer.js
app/scripts/modules/amazon/serverGroup/serverGroup.transformer.spec.js

First, let me say I am not loving this.
When cloning an ASG that's in a VPC, if the user sets the subnet type to "None (EC2 Classic)", we remove the `subnetType` field altogether.
However, when Clouddriver gets to this line:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy#L138
```groovy
if (ancestorAsg.VPCZoneIdentifier) {
task.updateStatus BASE_PHASE, "Looking up subnet type..."
newDescription.subnetType = description.subnetType != null ? description.subnetType : getPurposeForSubnet(sourceRegion, ancestorAsg.VPCZoneIdentifier.tokenize(',').getAt(0))
task.updateStatus BASE_PHASE, "Found: ${newDescription.subnetType}."
}
```
it replaces the intentionally missing subnet …

(aws) send empty string for subnet type when cloning into Classic

---

app/scripts/modules/core/authentication/authentication.initializer.service.js
app/scripts/modules/core/authentication/loggedOut.modal.controller.js
app/scripts/modules/core/authentication/loggedOut.modal.html
app/scripts/modules/core/authentication/loggedOut.modal.less
app/scripts/modules/core/modal/modals.less

Getting pretty serious about telling people they've been logged out - moving from a top banner to a modal:
@danielpeach @duftler any concerns with this change?

(core) move logged out message to modal

---

app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.js

If the rule already exists, don't try to update the `vpcId` field, since that rule may be from another account, and that account might not be managed by Spinnaker, so we don't know how to reconcile the `vpcId`

(aws) retain vpcId on ingress rules when editing

---

app/scripts/modules/netflix/migrator/migrator.service.js

If they're already in the target, they won't have any `*Migrations` fields, but let's not blow up the migration monitoring.

(aws) guard against clusters already in target when migrating

---

app/scripts/modules/core/account/account.service.js
app/scripts/modules/core/account/account.service.spec.js
app/scripts/modules/core/cloudProvider/providerSelection/providerSelector.directive.js

(core) return providers in alphabetical order

---

app/scripts/modules/core/delivery/triggers/nextRun.component.js

Some horrible people have a CRON trigger that is set to only run in June 2016, which is causing grief for my cool new clock.

(core) verify next run exists

---

app/scripts/modules/core/delivery/triggers/nextRun.component.js

In this cruel world, there are pipelines configured without `triggers`

(core) guard against missing triggers on nextRun tag

---

app/scripts/modules/core/pipeline/config/triggers/docker/dockerTrigger.module.js

noticed this issue when I was using docker registry as trigger. The docker 'organizations' were showing fine, but the 'image' drop down showed nothing. It was because the returned list contains {} elements. This fixes the issue.

guard against undefined while loading docker image

---

app/scripts/modules/cloudfoundry/pipeline/stages/resizeAsg/cfResizeAsgStage.js
app/scripts/modules/cloudfoundry/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/cloudfoundry/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/cloudfoundry/serverGroup/details/resize/resizeServerGroup.html
app/scripts/modules/cloudfoundry/serverGroup/details/serverGroupDetails.html

Expand CF's "Resize" options (at both server group and inside Resize Server Group stage) to also support resizing memory and disk limit.
Depends on https://github.com/spinnaker/clouddriver/pull/910
Resolves: https://github.com/spring-cloud/spring-cloud-spinnaker/issues/55

provider/cf: Allow resizing to include memory and disk

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/widgets/spelText/jsonListBuilder.js
app/scripts/modules/core/widgets/spelText/jsonListBuilder.spec.js
app/scripts/modules/core/widgets/spelText/spel.less
app/scripts/modules/core/widgets/spelText/spelAutocomplete.service.js
app/scripts/modules/core/widgets/spelText/spelText.decorator.js
package.json

Allows for context specific autocomplete for the SpEL in textareas and text inputs
At this time it shows a list of the functions, helper params, and stage names.
Also uses the last execution and walks the json and builds out the paths to the leafs for autocomplete.  
If no execution is found it will use the pipeline config to build the paths to the leafs.
There is context aware autocomplete around the #stage, #judgement helper functions as well as the 'parameters' and 'triggers' helper params.
NOTE:  I have plans to do some refactoring to remove some of the boilerplate.

SpEL autocomplete

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

@danielpeach @leelasharma
Turns out the only invalid character in a docker repo name is the underscore: https://github.com/docker/docker/blob/f63cdf0260cf6287d28a589a79d3f947def6a569/runtime.go#L33 - so we can keep the dash.

(kubernetes) Only strip underscores from names

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html

This is based on feedback from Greg B (SPIN-516).
I don't know the canary functionality well enough to say this is better, but assuming Greg does.
@cfieber or @zanthrash does this seem better to you?

(netflix) clarify label/help text on canary config

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

@danielpeach 
I replace `/` (which appears in repo/image) with a `-` to make the resulting container name more readable.

provider/kubernetes: No slash in container name

---

app/scripts/modules/core/widgets/spelText/spelAutocomplete.service.js

There are `pipelineConfig` objects in the scope of the executions view that are just strings, so we end up making a bunch of invalid calls to get the latest execution.

(core) bind spel autocomplete on pipeline config objects only

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancerProperties.html
app/scripts/modules/google/serverGroup/details/resize/resizeServerGroup.controller.spec.js

If the user has not explicitly toggled the load balancer's `isInternal` flag, try to set it from the purpose.

(aws) automatically set internal flag on load balancer creation

---

app/scripts/modules/core/serverGroup/serverGroup.directive.html
app/scripts/modules/core/serverGroup/serverGroup.directive.js

The vertical spacing of the image list was throwing off the UI a little. I shrunk the image list down to a comma separated list and I think it looks a little better without sacrificing readability: 
@danielpeach @bfarrell PTAL

(docker): Shrink size of image list in buildinfo

---

app/scripts/modules/kubernetes/serverGroup/details/details.html

It's not guaranteed that the details view will receive a replication controller anymore. 
@danielpeach

(kubernetes) Get `kind` from server group object

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/listeners.html

Hide the SSL Certificate Type field if only one listener type is configured.

(aws) make ELB certificate types configurable

---

app/scripts/modules/core/widgets/spelText/jsonListBuilder.js
app/scripts/modules/core/widgets/spelText/jsonListBuilder.spec.js
app/scripts/modules/core/widgets/spelText/spel.less
app/scripts/modules/core/widgets/spelText/spelAutocomplete.service.js
app/scripts/modules/core/widgets/spelText/spelText.decorator.js

- Show the value of the previous execution leaf notes in the dropdown list.
- Dropdown list now has a max height with y-overflow scrolling
- Don't show #judgment function if no Manual Judgment stage found
- Don't show 'parameters' param if no params in pipeline
- Don't show 'scmInfo' param if there is not a Jenkins trigger or Jenkins stage
- Autocomlete now works for "execution", and "deployedServerGroups"
- z-index is fixed for dropdown in modal windows.

Adding more goodness to SpEL autocomplete

---

app/scripts/modules/amazon/subnet/subnetSelectField.directive.js

If `hideClassic` is set and an `onChange` method is configured, we should fire the `onChange` event when auto-selecting a subnet for users.

(aws) trigger onChange when setting subnet initial value

---

app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html

We recently (i.e. earlier today) started correctly returning security group ingress rules that map the same ports via different protocols. However, we currently do not group them nicely, so users see a separate entry with the same IP range or security group for each protocol.
This collapses the entries nicely.

(aws) group security group rules by security group/range

---

angular-loader/index.js

This was useful when the loader was being developed, but it seems to be noise now.

(core) remove warning for missing angular module from loader

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.js
app/scripts/modules/core/delivery/triggers/nextRun.component.js

Nobody has complained about this, but the "next run" calculations are only done when the component first renders, so the calculations (especially the human-readable part) can appear incorrect as time marches forward.

(core) calculate next run on mouseenter

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

This PR https://github.com/spinnaker/clouddriver/pull/957 merged this morning removes the need to format image queries. @danielpeach

(kubernetes) Stop formatting image queries

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/kubernetes/event/event.directive.html
app/scripts/modules/kubernetes/event/event.directive.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/kubernetes/kubernetes.module.js

Render events for kubernetes pods (more resources incoming). 
@danielpeach PTAL, @duftler FYI
Timestamps show on hover-over
Events are listed with how often they occur and brief summary
All details are expanded by clicking the ellipses.

(kubernetes): Render kubernetes events

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.spec.js
settings.js

- Currently only handles {[application}}

Support rudimentary templating in default IAM roles

---

app/scripts/modules/core/application/config/applicationSnapshotSection.component.html
app/scripts/modules/core/snapshot/snapshot.write.service.js

Changed the name from serializeApplication to saveSnapshot. Not too much here because Dan changed most of the names when he added the diff view. PTAL @lwander

provider/core: changed name from serialize application to save snapshot

---

app/scripts/modules/core/widgets/spelText/spelAutocomplete.service.js

If the pipeline has never run, there won't be a `trigger` field, since the `pipeline` will be the pipeline config itself, and we'll get a NPE.

(core) guard against missing trigger in autocomplete

---

app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js

Truthy checks are not great when dealing with optional numbers that can be zero.

(aws) show ingress rules when port is 0

---

app/scripts/modules/core/instance/instanceListBody.directive.js
app/scripts/modules/core/instance/loadBalancer/health.html
app/scripts/modules/core/instance/loadBalancer/instanceLoadBalancerHealth.directive.js

uses the healthState attribute (if available, comes from spinnaker/clouddriver#1003) instead of recomputing meanings of AWS fields on the front end
falls back to using the value of state if healthState is not present, so this should be safely deployable independent of the corresponding clouddriver change that adds that new attribute

updates rendering of up/down flag on load balancer 

---

app/scripts/modules/core/cluster/rollups.less

This fixes an obscure(ish) issue where a cluster has a really long name that stretches to two lines, but does not have any instances reporting health, so there is no instance health counter.

(core) use min-height instead of height on rollup title cell

---

app/scripts/modules/openstack/loadBalancer/configure/wizard/listeners.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/loadBalancer/transformer.js

changed default listener protocol to http
removed ssl reference since it's not an option for externalProtocol

changed size of ssl field so full text for terminated_https displays

---

package.json

Do we need bower installed still? Let's find out...

(core) remove bower preinstall step

---

app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

Bug fix: we are failing to submit the expected configuration when creating the server group using the user selected vnet and subnet.

Azure bug fix: failed to create server group using selected vnet/subnet

---

.travis.yml
karma.conf.js

Not totally in love with caching `node_modules`, but it cuts a couple of minutes off the build.
Using Chromium (it's preinstalled on Travis boxes) cuts another minute or so off the build.

(core) cache node_modules between builds, use Travis's Chromium

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js

In the standalone view, when there are multiple nested pipelines, the pipeline-grap does not update when the execution changes on the scope.

Making the standalone pipeline view refresh the pipeline-graph

---

app/scripts/modules/core/delivery/filter/executionFilter.service.js

Fixes bug where pipelines could not be reordered after application refresh -- a refresh caused pipeline config references to be lost.

(core) allow pipeline reorder after refresh

---

.eslintrc
app/scripts/modules/core/pipeline/config/stages/executionWindows/ExecutionWindowDayPickerComponent.spec.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/daysOfWeek.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowDayPicker.component.html
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowDayPicker.component.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.html
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindows.less
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.html
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsStage.module.js

* add days-of-week selector widget to pipeline execution restriction window

(core) add day selector to execution window

---

app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/azure/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/securityGroup/ServerGroupSecurityGroups.controller.js
app/scripts/modules/azure/serverGroup/configure/wizard/securityGroup/serverGroupSecurityGroupsSelector.directive.html
app/scripts/modules/azure/serverGroup/serverGroup.transformer.js

When creating an azure load balancer and server group, the selected virtual network can be from a different resource group then the one corresponding to the application.

Bug fix - failed to select vnet in arbitrary resource group

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/task/tasks.controller.js

Using classes with private fields means we can't be fancy with our `then` calls.
@zanthrash @icfantv FYI

(core) fix refresh calls on objects

---

app/scripts/modules/core/application/application.controller.js
app/scripts/modules/core/application/application.model.ts
app/scripts/modules/core/application/config/dataSources/applicationDataSourceEditor.component.ts
app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/delivery/filter/executionFilter.model.js
app/scripts/modules/core/history/recentHistory.service.js
app/scripts/modules/core/history/recentHistory.service.spec.js
app/scripts/modules/core/widgets/spelText/spelText.decorator.js

* gracefully handle recent item entries for applications where the user was last on some executions view
* removing invalid hotkey entry
* adding `notFound` as a field on the application and using it to decide if we should initialize the data source config component - config page routes back to `/infrastructure` immediately if it's the case, but the component still initializes and throws a NPE
* correctly set default `activeState` based on `sref`, not `key`

(core) better error handling for new app loading

---

.babelrc
app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/amazon/serverGroup/details/advancedSettings/editAsgAdvancedSettings.modal.controller.js
app/scripts/modules/amazon/serverGroup/details/scalingProcesses/modifyScalingProcesses.controller.js
app/scripts/modules/amazon/serverGroup/details/scheduledAction/editScheduledActions.modal.controller.js
app/scripts/modules/amazon/serverGroup/details/securityGroup/editSecurityGroups.modal.controller.js
app/scripts/modules/cloudfoundry/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/google/securityGroup/configure/editSecurityGroup.controller.js
app/scripts/modules/openstack/serverGroup/details/resize/resizeServerGroup.controller.js

Throwing this out there for discussion.
Much as I love how clean class-level methods are, they don't behave well when called as a result of a promise, e.g.
```javascript
class Foo {
this.bar = 3;
baz() {
console.log(this.bar)
}
}
...
let foo = new Foo();
somePromise().then(foo.baz); // throws an exception: "cannot read property 'baz' of undefined"
```
There are a couple of ways to get around this:
```javascript
// (1) Invoke via anonymous function
somePromise().then(() => foo.baz());
```
or
```javascript
// (2) Declare method using arrow function, binding 'this' to the class instance
class Foo {
this.bar = 3;
public baz = () => {
console.log(this.bar);
}
let foo = new Foo();
somePromise().then(foo.baz); // logs "3"
```
Preferences on (1) vs. (2)? I prefer (2): it's less surprising to me. …

(core) auto-bind this in class-level methods

---

app/scripts/modules/core/securityGroup/securityGroup.read.service.js

@anotherchrisberry @duftler 
A very small change, but I'm not sure what changed to make it necessary. If two server groups share a security group, the security group will be counted twice here: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/securityGroup/securityGroup.read.service.js#L112-L125.

(core) dedupe security groups

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/popover/scalingPolicyPopover.component.html
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/popover/scalingPolicyPopover.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js

@ajordens this should fix the issue we were seeing earlier tonight in two ways:
1. Hide the warmup if the operation is a scale down, since it's confusing to show it
2. Actually remove the warmup field if the operation is a scale down, since AWS will store it unnecessarily.

(aws) remove/hide warmup on scale down step policies

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancersTag.html
app/scripts/modules/core/loadBalancer/loadBalancersTag.directive.js
app/scripts/modules/core/serverGroup/serverGroup.directive.html

When there are a lot of load balancers attached to a single server group, show the health counts for each load balancer, since we already have all that info.
Any concerns or objections?

(core) show instance counts in load balancers menu

---

app/scripts/modules/amazon/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/location/basicSettings.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/instance/ServerGroupInstanceSettings.controller.js

`throttle` and `debounce` became `throttleTime` and `debounceTime` in RxJS 5
heads up @zanthrash @icfantv

(all) move rx throttle to debounceTime

---

app/scripts/modules/core/cluster/filter/multiselect.model.js
app/scripts/modules/core/cluster/filter/multiselect.model.spec.js
app/scripts/modules/core/delivery/executionBuild/executionBuildNumber.directive.html
app/scripts/modules/core/pipeline/config/stages/pipeline/pipelineExecutionDetails.html
package.json

In order to get `reload` to accept and process a string, we have to bump the version of ui-router (the string option was documented in 0.2.5, but not actually implemented until sometime after 0.2.13).
Unfortunately, the `$state.includes` matching is broken when glob-matching on `**.someState.*` due to https://github.com/angular-ui/ui-router/commit/e39b27a2cb7d88525c446a041f9fbf1553202010. We only use that matching check in one spot, fortunately, so it's something to be aware of. I don't expect they'll fix it, as that commit is 20 months old and I don't see any issues in the repo related to it, so we may be the only folks trying to update to a newer version of the router depending on it. And the workaround is pretty simple.

(core) reload pipeline view when navigating between executions

---

app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagManager.service.js

(gce) guard against undefined security group map in tag manager

(gce) guard against undefined security group map in tag manager

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.less
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.html

Lets users zoom into a portion of the graph by holding down the alt key and clicking and dragging to select a portion of the chart.
Unfortunately, the alt key behavior is baked into the chart library, presumably because the library also has a panning option, which relies on clicking and dragging.

(aws) make alarm configuration chart zoomable

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.aws.service.spec.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js

When using an existing server group as a template in a deploy stage, it's almost always the case that the user will want to use the source capacity on subsequent deploys. This sets that as the default.

(aws) default to use source capacity in aws deploy via template

---

app/scripts/modules/core/task/tasks.html

This whole screen needs a rewrite, but for now, let's add in the account and region, if available, to the task summary row on the Tasks tab.

(core) show task account/region if available in tasks view

---

app/scripts/modules/amazon/loadBalancer/configure/editLoadBalancer.html
app/scripts/modules/amazon/loadBalancer/configure/listeners.html

`form.$invalid` doesn't do much when there's no `form`, which is only the case when editing an existing load balancer.
Also fixing alignment of delete button when there are both secure and non-secure listeners.

(aws) require certificate on HTTPS/SSL listeners

---

package.json

0.3.0 drops query parameters that it doesn't know about when navigating to the same state, e.g. if you're on `/clusters?q=v001` and click the Clusters tab, the filters get dropped.
I think we're stuck with 0.2.13 for the foreseeable future, which is not the end of the world, but something to remember.
@zanthrash @icfantv FYI

(core) rollback ui-router to 0.2.13

---

app/scripts/modules/openstack/common/footer.directive.html
app/scripts/modules/openstack/common/footer.directive.js
app/scripts/modules/openstack/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/openstack/serverGroup/details/rollback/rollbackServerGroup.html
app/scripts/modules/openstack/serverGroup/details/serverGroup.details.module.js
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.openstack.controller.js

Closes issue 1114
Rollback functionality details:
Rollback must be done on an enabled server group. After clicking rollback under server group actions, you must select a disabled server group within the same cluster in the drop down. Running rollback will enable the selected disabled server group, resize it to match the size of the active selected server group, and then disable the selected server group.

(Openstack) adding rollback functionality for openstack

---

app/scripts/modules/amazon/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.html
app/scripts/modules/core/securityGroup/securityGroup.read.service.js
app/scripts/modules/core/securityGroup/securityGroup.read.service.spec.js

Addresses a long-standing issue where an upsert task never completes because we're sending an invalid name in ingress rules if we don't know about the account. Orca then tries to match the name with what comes back from Clouddriver, which never happens.

(aws) clean up security group upsert command

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@jtk54 
Help text contents:
Incoming traffic is directed through a named port (e.g., http). The mapping from named port to port number is specified per server group and can be configured within the server group creation dialogue under Port Name Mapping.

(gce) help text for http lb listener named port

---

app/scripts/modules/core/pipeline/config/actions/json/editPipelineJson.module.js
app/scripts/modules/core/pipeline/config/actions/json/editPipelineJsonModal.html
app/scripts/modules/core/pipeline/config/actions/pipelineConfigActions.html
app/scripts/modules/core/pipeline/config/pipelineConfig.less
app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/netflix/templateOverride/pipelineConfigActions.html

- New 'locked' pipeline config attribute
- All locked pipelines must be modified via the API

Support locked (aka not editable via UI) pipelines

---

app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.service.js
app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.service.spec.js
app/scripts/modules/titus/titus.module.js

* add the ability to allow providers to be configured to use the
configuration for a different provider via a new `useProvider` option in
the provider's `securityGroup` property.

(core): add provider deferring capability

---

app/scripts/modules/amazon/securityGroup/clone/cloneSecurityGroup.controller.js

This has been broken for an unknown amount of time.

(aws) set name, credentials on security group clone operation

---

app/scripts/modules/core/pipeline/config/actions/actions.module.js
app/scripts/modules/core/pipeline/config/actions/lock/lock.module.js
app/scripts/modules/core/pipeline/config/actions/lock/lockPipelineModal.html
app/scripts/modules/core/pipeline/config/actions/pipelineConfigActions.html
app/scripts/modules/core/pipeline/config/actions/unlock/unlock.module.js
app/scripts/modules/core/pipeline/config/actions/unlock/unlockPipelineModal.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/netflix/templateOverride/pipelineConfigActions.html

The expanded pipeline config structure is now:
```
locked: {
ui: true,
allowUnlockUi: true, // optional
description: "This pipeline is locked as per xyz" // optional
}
```

Support unlocks via the UI

---

app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.service.js
app/scripts/modules/core/cloudProvider/providerSelection/providerSelection.service.spec.js
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

There is a check for a 'feature' that is suppoesed to then populate the reducedPoviders array.
Later map is called on the array and if the array is undefied bad things happen.
- Also adds some missing simicolons
- and removing fdescribe from a test

Instanciated reducedProviders with empty array.

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.html
app/scripts/modules/amazon/loadBalancer/configure/editLoadBalancer.html
app/scripts/modules/amazon/loadBalancer/configure/listeners.html

* hide SSL cert select table cell using same visibility conditions
as column header.
* hide SSL cert name table cell using same visibility conditions as
column header.
* turn off HTML5 form validation for create/edit load balancer dialog
form.
@anotherchrisberry @zanthrash PTAL
@kmarquardsen it appears you cloned `listeners.html` for openstack, you may be interested in these changes.

(aws) fix cert type table cell visibility

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/azure/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidation.service.spec.js
app/scripts/modules/core/pipeline/config/validation/pipelineConfigValidator.directive.js
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

When a pipeline triggers a child pipeline, and the child pipeline has a bake stage, Orca will look at the parent pipeline's trigger for package information.
We've had this behavior in Orca for about a year, but we never updated the validators in Deck, so folks still get this warning, even though it's not a valid warning, which just trains people to ignore those warnings.
This change allows `stageOrTriggerBeforeType` validators to declare they should `checkParentTriggers`, which will result in the validator fetching the pipeline config for the trigger and add its triggers to the list of things to check.
Not crazy about bringing async behavior into the validator but I don't think there's a way around it, and I think the way I've done it is not intrusive or burdensome for new validators. …

(core) allow stage validator to check parent triggers

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/loadBalancer/details/healthCheck/healthCheck.component.html
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@jtk54 
What do you think about just listing all of the health checks (after deduping, without the "Backend Service Name" header), since the relationship between health checks and backend services should be clear now?

(gce) backend services in load balancer details

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/amazon/securityGroup/configure/ingressRuleGroupSelector.component.js
app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/scalingPolicy/upsert/alarm/alarmConfigurer.component.js
app/scripts/modules/amazon/serverGroup/details/scalingProcesses/autoScalingProcess.service.js
app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/CloneServerGroupCtrl.js
app/scripts/modules/core/application/application.model.ts
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/cluster/filter/multiselect.model.js
app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/instance/details/multipleInstances.controller.js
app/scripts/modules/core/loadBalancer/loadBalancersTag.component.ts
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/manualJudgment/manualJudgment.service.js
app/scripts/modules/core/pipeline/config/stages/wait/waitExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/triggers/pipeline/pipelineTrigger.module.js
app/scripts/modules/core/serverGroup/details/multipleServerGroups.controller.js
app/scripts/modules/core/subnet/subnet.read.service.js
app/scripts/modules/core/task/taskProgressBar.directive.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/netflix/migrator/migrator.service.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/openstack/loadBalancer/details/details.controller.js
app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/serverGroup/configure/wizard/CloneServerGroup.titus.controller.js

Long ago, Chrome didn't support `Array.prototype.find`, and some of us (mostly me) got in the bad habit of destructuring the first item out of a `filter` operation to get around it.
All major browsers now support `find`, so this PR cleans up code for readability.
Also removing an unused parameter that the linter is yelling about.
@zanthrash for you

favor .find to destructuring + .filter

---

package.json

@icfantv I can't run deck without this - did you install it locally, maybe?

(core) include codelyzer dependency

---

app/scripts/modules/core/instance/instances.directive.js

Turns out the Bootstrap tooltip is not exactly like the jQuery UI tooltip - removing via delegation requires a `selector` be passed in on instantiation.
This also cuts down on the number of tooltips we attempt to apply.

(core) correctly destroy tooltips when instances are removed from view

---

app/scripts/modules/core/filterModel/filter.model.service.js

Fixes a bug that's been around for well over a year.
Sometimes, when manually changing the URL through `$location.search`, ui-router does not update its internal state, where it keeps a `location` variable. When Angular eventually broadcasts a `$locationChangeSuccess` event, ui-router resets the `$location.search` to the previous query parameters.
Calling `$urlRouter.update(true)` sets ui-router's `location` to the current URL and prevents the reset.

(core) sync ui-router state when manually changing url

---

app/scripts/modules/titus/serverGroup/configure/ServerGroupCommandBuilder.js

* fix issue in deck whereby the hard and soft constraints come from the
server as arrays, but are modified as comma-delimited strings in the
advanced settings section of cloning a server group.
* also fixed this issue in pipelines for adding a server group in a
deploy stage for when the configuration is copied from an existing titus
server group.

(titus): fix constraint array -> string mapping

---

app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js

@duftler @jtk54 please review.
This was a mistake. Here are my assumptions now:
- The json payload needs to have names of the network load balancers under the key `loadBalancers`.
- Including the name of a url map will cause the operation to fail.
- The listener names only need to be included within the metadata.

(gce) fix network lb association

---

app/scripts/modules/core/pipeline/config/preconditions/selector/preconditionSelector.directive.js

$scope.precondition.cloudProvider was never set during this pipeline stage, so I have added code to set the variable to the proper cloud provider during the "accountUpdated" step.

(core) fixes check precondition for openstack

---

app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyConfigFooter.component.spec.ts
app/scripts/modules/core/chaosMonkey/chaosMonkeyExceptions.component.spec.ts
app/scripts/modules/core/help/helpContents.registry.spec.ts
tslint.json

I bailed on the import ordering because it seems like a pain, and also the opposite of what I think we agreed we want (third-party modules first), since internal modules all come from a directory path, i.e. `./`, which is alphabetically before node modules.
@icfantv @zanthrash @danielpeach PTAL

tweak tslint rules

---

app/scripts/modules/core/task/tasks.html

it's nice that they're there but hard to read when they're all over the place horizontally.
Current:
PR:

(core) put account/region into separate columns in tasks views

---

app/scripts/modules/core/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts

On app creation, when chaos monkey is enabled, set the chaos monkey config values to the defaults.
This restores the behavior to what it was before chaos monkey code was moved from netflix to core.
cc @anotherchrisberry

Set default values for chaos monkey config

---

app/scripts/modules/azure/loadBalancer/loadBalancer.write.service.js
app/scripts/modules/azure/securityGroup/securityGroup.write.service.js
app/scripts/modules/core/loadBalancer/loadBalancer.write.service.js
app/scripts/modules/core/securityGroup/securityGroup.write.service.js
app/scripts/modules/core/task/tasks.controller.js
app/scripts/modules/core/task/tasks.html

As this whole view is in need of a rewrite, I don't want to spend too much time on it. However...
* removing account/region from delete security group/load balancer tasks (since we now display them in the tasks view as columns)
* adding account/region to the searchable fields
* including `cloneServerGroup` and `createServerGroup` in the list of tasks to look for deployed server groups (we switched over to these tasks almost a year ago)
* fixing column widths

(core) task cleanup, search improvements

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/core/api/api.service.js
app/scripts/modules/core/cache/cacheInitializer.js
app/scripts/modules/core/cache/deckCacheFactory.js
app/scripts/modules/core/cluster/filter/clusterFilter.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/status/executionStatus.directive.js
app/scripts/modules/core/pipeline/config/triggers/trigger.html
app/scripts/modules/core/serverGroup/configure/common/basicSettingsMixin.controller.js
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.js
app/scripts/modules/netflix/migrator/pipeline/pipeline.migrator.directive.js
app/scripts/modules/netflix/migrator/serverGroup/serverGroup.migrator.directive.js
app/scripts/modules/titus/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js

Newer browsers allow us to use `String.prototype.includes` and `Array.prototype.includes` instead of having to rely on `indexOf` to determine if a substring is present in a string, or an item is present in an array.
There are going to be several of these pull requests, each taking a different variant of `indexOf` out of the codebase ( `> -1`, `!== -1`, `=== -1`). I'm breaking them up so they're easier to review.
cc @lwander @duftler @danielpeach @zanthrash @icfantv

(all) replace indexOf() < 0 with !includes

---

app/scripts/modules/core/serverGroup/serverGroup.write.service.spec.js
app/scripts/modules/core/task/monitor/taskMonitorService.spec.js
app/scripts/modules/core/task/task.read.service.js
app/scripts/modules/core/task/task.read.service.spec.js
app/scripts/modules/core/task/task.write.service.js
app/scripts/modules/core/task/task.write.service.spec.js
app/scripts/modules/core/task/taskExecutor.js

Apparently the `/applications/{app}/tasks/{taskId}` endpoint in Gate was deprecated 20 months ago in favor of `/tasks/{taskId}`.
For @tomaslin

(core) get tasks from non-deprecated endpoint

---

app/scripts/modules/core/forms/forms.module.js
app/scripts/modules/core/forms/numberList/numberList.component.less
app/scripts/modules/core/forms/numberList/numberList.component.spec.ts
app/scripts/modules/core/forms/numberList/numberList.component.ts
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/serverGroup/configure/wizard/resources.html
app/scripts/modules/titus/serverGroup/serverGroup.transformer.js

Adding a new component to allow entering a list of numbers with validation on min/max.
Supports spEl expressions conditionally based on `no-spel` class presence on parent element.
Tests written against the DOM instead of just the controller to see how that goes with TS. It's not too bad.
Not in love with the position of the spEl toggle so that might change based on feedback.
_`.no-spel` on parent class, invalid number_
_invalid/valid number, delete button_
_spEl-enabled_
_numeric, spEl available_

(titus) allow port entry via number list

---

package.json

Might as well get on the RC1 train for RxJS while we're at it.

(core) remove ng2 dependencies

---

app/scripts/modules/amazon/instance/awsInstanceType.service.js
app/scripts/modules/amazon/instance/awsInstanceType.service.spec.js

Porting sorting work from clouddriver (spinnaker/clouddriver#1128) into deck since the cache doesn't persist ordering. Whoops.
PTAL @ajordens @anotherchrisberry

Sort AWS instance types by family then class size

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.html
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.js
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroups.html
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupsRemoved.directive.html
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupsRemoved.directive.js
app/scripts/modules/core/domain/ICredentials.ts
app/scripts/modules/core/domain/ISecurityGroup.ts
app/scripts/modules/core/domain/IVpc.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/modal/wizard/v2wizardPage.component.ts
app/scripts/modules/netflix/serverGroup/wizard/securityGroups/awsServerGroupSecurityGroups.html
app/scripts/modules/titus/domain/ITitusCredentials.ts
app/scripts/modules/titus/domain/index.ts
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js
app/scripts/modules/titus/securityGroup/securityGroup.read.service.js
app/scripts/modules/titus/securityGroup/securityGroupPicker.component.ts
app/scripts/modules/titus/serverGroup/configure/serverGroupBasicSettingsDirective.html
app/scripts/modules/titus/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/titus/serverGroup/configure/wizard/CloneServerGroup.titus.controller.js
app/scripts/modules/titus/serverGroup/configure/wizard/parameters.html
app/scripts/modules/titus/serverGroup/configure/wizard/securityGroups.html
app/scripts/modules/titus/serverGroup/configure/wizard/serverGroupWizard.html

A modest refactoring of the existing security group selector from the AWS server group modal, repurposing it to work for the Titus server group modal and the Titus run job stage.
I'm trying to not repeat the mistakes of the past with the server group configuration modals, where changes cascade and it's almost impossible to follow what's going on. Instead, I'm moving the logic into distinct components, then using Observables on the command itself to emit changes. 
I think this is going to be a much better pattern when refactoring. I didn't go all-in on changing the AWS command here, since I'd like to test this for a bit and work out design issues.
Adding some interfaces into the domain modules for VPC, Security Group, and Credentials, named based on the doc @icfantv put out last night. I'm …

(titus) allow users to pick security groups from select list

---

app/scripts/modules/core/pipeline/config/createNew.html

I think this dropdown is a little confusing for completely new users -- it's unclear that you would be configuring existing pipelines -- so it looks like a bug if there's nothing there.
Before:
After:

(core) message in pipeline config dropdown if no pipelines exist

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/delivery/service/execution.service.spec.js

When a pipeline execution changes, we replace the entire thing in place, which can cause flickering in the UI, as Angular removes the entire DOM tree for that pipeline and re-renders it. This has been the case for a long time, but it's exacerbated on running pipelines, which refresh every second and are more naturally more volatile.
These changes make the replacement more granular to avoid unnecessary re-rendering of huge swaths of the DOM. We'll still replace the entire execution if its status changes (e.g. goes from not started to started, started to completed), but otherwise we'll just replace the _contents_ of any stage that has changed. By leaving the actual stage object in the execution, we get better performance and much less DOM thrashing (at the cost of added complexity). …

(core) selectively update existing pipelines when changes detected

---

build.gradle

@ewiseblatt 
It seems safest to do it this way. 

(core) added flag for skipping tests for buildDeb

---

app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerType/loadBalancerType.component.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.html
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.js

@jtk54 
For ILBs:
- Load balancer details should render properly
- Server group wizard should render properly
Create & Clone server group seems to work fine with no changes: on the operation description, the ILB name is added to `loadBalancers` and within the `load-balancer-names` metadata.

(gce) integrate ilb into GCE lb details view and server group wizard

---

app/scripts/modules/openstack/pipeline/stages/cloneServerGroup/openstackCloneServerGroupStage.js

Type error, Replaced word Amazon with Openstack

Openstack:Pipeline :: Replaced Amazon with Openstack in Clone Server Group.

---

app/scripts/modules/core/cluster/rollups.less
app/scripts/modules/core/serverGroup/serverGroup.directive.html

@anotherchrisberry let me know what you think about this. If the image has a sha, then the label will always wrap, since there's only room for ~50 characters.
Before:
After:

(core) make room for long image name in server group label

---

app/scripts/modules/google/loadBalancer/elSevenUtils.service.js

L7 check was 'if global or HTTP', since SSL LBs are global, this needs modified. @danielpeach please review.

(google): Fixed L7 type check.

---

app/scripts/modules/core/instance/instanceListBody.directive.js
app/scripts/modules/core/instance/instances.directive.js

Oh the joy of managing the DOM directly, using a framework and two libraries with complementary features.
Right now, if an instance tooltip is visible when the element is removed from the page (typically because the state of the server group has changed), the tooltip sticks to the page, because Bootstrap tooltips attached via the `selector` are basically impossible to get a handle on. I thought I'd fixed this two weeks ago but it's come back, or I was delusional.
The new approach attaches the tooltip on mouseover, stores a reference to the DOM node itself, then removes all of them whenever the contents of the instance list are replaced or removed.

(core) better manage instance tooltip lifecycle

---

webpack.config.js

I tried this some time ago, but it always hung, which I finally traced to the `sourceMap` generation. Disabling that results in a successful (and still fast) build.
The plugin (in this configuration) does a couple of things:
1. removes comments from the output bundles
2. removes unused parameters and unreachable code
Results:
vendor bundle drops from 4.3 MB to 2.9 MB
app bundle drops from 6.1 to 5.2
I'll be curious to see what this ends up at once it's gzipped.

(build) remove comments, unused variables from output code

---

app/scripts/modules/google/loadBalancer/configure/common/sessionAffinityNameMaps.ts
app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.html
app/scripts/modules/google/loadBalancer/configure/http/commandBuilder.service.js
app/scripts/modules/google/loadBalancer/configure/http/transformer.service.js
app/scripts/modules/google/loadBalancer/details/backendService/backendService.component.ts
app/scripts/modules/google/loadBalancer/details/backendService/sessionAffinity.filter.ts
app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js

@duftler or @jtk54 
For ILBs, I made all the options say nice human readable things, rather than having people select and see things like "CLIENT_IP_PORT_PROTO". This PR makes this consistent for the HTTP(S) load balancer wizard and for the load balancer details view.

(gce) makes backend service session affinity more human readable

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html
app/scripts/modules/netflix/instance/aws/instanceDetails.html

Provide a message that the resource is not found, remove it from recent history, and allow the user to navigate back to the home screen.

(aws) handle standalone views when resource not found

---

test/google/README.md
test/google/e2e/tests/createServerGroup.e2e.js
test/google/google_int.sh
test/google/package.json
test/google/tasks/createServerGroup/task.js

Cleans up startup script, adds a sleep for a flaky test. @duftler or @lwander please reivew.

(gce) improve e2e test start-up script

---

app/scripts/modules/google/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html

@duftler 
Swap ui-select field for standard select field. You can't type your choices in, but it also doesn't take 5-10 seconds for the field to open.

(gce) standard select fields for custom instance builder

---

app/scripts/modules/google/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/loadBalancer/details/loadBalancerDetails.html

@jtk54 or @duftler 
Removed zones from load balancer details view, moved region to its own heading. The top detail panel now closely matches the corresponding panel for Kubernetes.

(gce) remove zones from load balancer details view

---

app/scripts/modules/google/serverGroup/configure/wizard/securityGroups/tagManager.service.js

I ran into this when trying to create a server group in a new application that didn't have any security groups yet.

(google) allow user to create server group when no security groups are defined

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.less

Two changes to make pipelines a little more usable when they are extremely large:
1. Replace the `visibility: hidden|visible` with `display: none|inline-block` on the duration tags. Using `visibility` is confusing the browser when the user clicks on the enclosing `div`, preventing navigation when it's significantly smaller than the duration tag.
2. Slow down the auto refresh when there are more than ten stages in a pipeline, slowing it to 2 seconds for pipelines with 11-20 stages, 3 second for 21-30 stages, etc.
@zanthrash PTAL. This makes Cadmium a little more usable in the non-standalone view. It's still kinda laggy but better than current behavior.

(core) fix click target on pipelines with > 40 stages; slow refresh rate based on size

---

app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.html
app/scripts/modules/amazon/serverGroup/configure/wizard/securityGroups/securityGroupSelector.directive.js

nothing exciting or different than we do in several other places, just makes the security group selection tolerable when there are > 300 security groups in the target location

(amazon) paginate scrolling on security group selector

---

app/scripts/modules/core/modal/wizard/modalWizard.less

(core) clean up non-modal wizard navigation style

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

maybe don't call unsubscribe if we never created the scheduler in the first place

(core) avoid NPE on missing scheduler in execution directive

---

app/scripts/modules/google/backendService/backendService.reader.js
app/scripts/modules/google/loadBalancer/configure/http/commandBuilder.service.js

Since the search endpoint for backend services now returns two kinds of services, we need a way to filter them. 

(google) filter backend services by kind

---

app/scripts/modules/google/loadBalancer/loadBalancer.transformer.js

Deck throws an error when it tries to load a Google SSL load balancer without a health check.
@duftler or @jtk54

(google) fix error caused by SSL load balancer in project

---

app/scripts/modules/google/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.js

I'll follow up with a PR that will allow the SSL details to be rendered properly.
Just to be explicit about the payload that Deck is forming: the name of the selected SSL load balancer is included in the `global-load-balancer-names` metadata and under `loadBalancers`.

(google) create / clone / destroy server group with ssl lb

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/titus/securityGroup/securityGroupPicker.component.ts

Now I remember why we didn't paginate this in the first place: for the ui-select options to work, we need to ensure that existing options are not removed by the `filter`.
Rather than remove the filtering, let's double down on the complexity by sorting the existing security groups and making sure they are always first in the array.

(amazon) front-load existing security groups in filtered data

---

app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js

As is, when creating a loadBalancer, the subnets dropdown is not updated to reflect the selected account.

(Openstack) Update loadBalancer subnets to reflect selected openstack acount

---

app/scripts/modules/titus/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/serverGroup/configure/wizard/CloneServerGroup.titus.controller.js

`imageId` is no longer a field we care about - we want to make sure `tag` is selected.
Also fixing initialization of security groups.
@tomaslin PTAL

(titus) fix validation on image selection

---

package.json

This is only to get rid of the anoying missing typescript defenition on chai that is required.

Pins rx.js to beta-1

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html

For some reason, Angular has decided to stop removing the old `execution-marker-{{stage.status.toLowerCase()}}` class when it changes. Instead, it's just adding the new class, so we end up with multiple `execution-marker-xxx` classes on the div when its status changes.
The only thing I can think is it has something to do with removing angular-animate a few days ago. While that doesn't make a lot of sense, I'm less interested in figuring out the root cause of this issue and more interested in "making it work as expected", and this change does that. We also end up with fewer watchers on the page, although I'm not convinced we're saving anything - it could just be that the `ng-class` watcher is more computationally complex.

(core) move class assignment on pipeline stages to ng-class

---

app/scripts/modules/netflix/pipeline/stage/acaTask/acaTaskStage.transformer.js

The ACA Task trasnsformer was not considering the overall result state of the canary
when setting the state of the sage.
This also sets the stage as SUCCEDED when the canary status is marked as competed AND
the overallResult of the canary are SUCCESS.

AcaTask stage correctly fail stage when ACA fails

---

app/scripts/modules/core/application/config/appConfig.dataSource.js
app/scripts/modules/core/application/service/applicationDataSource.registry.ts
app/scripts/modules/core/application/service/applications.read.service.js
app/scripts/modules/core/delivery/delivery.dataSource.js
app/scripts/modules/core/delivery/delivery.dataSource.spec.ts
app/scripts/modules/core/loadBalancer/loadBalancer.dataSource.js
app/scripts/modules/core/securityGroup/securityGroup.dataSource.js
app/scripts/modules/core/serverGroup/serverGroup.dataSource.js
app/scripts/modules/core/task/task.dataSource.js
app/scripts/modules/core/task/task.dataSource.spec.ts
app/scripts/modules/netflix/ci/ci.controller.spec.js
app/scripts/modules/netflix/ci/ci.dataSource.js
app/scripts/modules/netflix/ci/ci.dataSource.spec.ts
app/scripts/modules/netflix/fastProperties/fastProperty.dataSource.js
app/scripts/modules/netflix/netflix.module.js
app/scripts/modules/netflix/tableau/tableau.dataSource.js

We're going to move away from `export default` with the module name, so there will be a number of pull requests like this one.
cc @danielpeach - we'll try to get a TS style guide together in the next week or so to spell this stuff out. I think we have most of the pieces in place, just need to hammer it into a wiki page on GH.

(core) remove default export on applicationDataSourceRegistry

---

app/scripts/modules/openstack/common/cacheBackedMultiSelect.template.html
app/scripts/modules/openstack/common/cacheBackedMultiSelectField.directive.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js
app/scripts/modules/openstack/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/openstack/serverGroup/configure/wizard/Clone.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/AccessSettings.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/accessSettings.html

When creating a server group (or a load balancer), the list of security groups to choose from should be all security groups in that account and region. This allows having common security groups platform services like logging servers, service discovery servers, etc.
To accomplish this, the `appCacheBackedMultiSelect` directive had to be updated to allow passing
in an explicit cache instead of having the directive read the cache via cache key from the application list.

(Openstack) Show all security groups on create server group

---

app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.html
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.js

Same thing we did on the `markUnstableAsSuccessful` flag - use the view state to avoid having the pipeline appear changed based on initialization of `waitForCompletion`, which is `true` if it's undefined.
cc @tomaslin

(core) do not mark jenkins stages as changed when initializing

---

app/scripts/modules/core/application/application.model.ts
app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/delivery/delivery.dataSource.js
app/scripts/modules/core/task/task.dataSource.js
app/scripts/modules/netflix/ci/ci.controller.js
app/scripts/modules/netflix/ci/ci.dataSource.js

A few fixes/improvements:
* Clarifying the `visible` field's role: if set on a data source, it should not contribute to the application's `ready` state, although it should refresh when the application is refreshed. This prevents failure to load the badges from loading the rest of the application.
* Adding an `afterLoad` method to data sources. I noticed the running tasks and executions do not show up on affected server groups for an entire application refresh cycle, since the data is added to the data source _after_ the `onLoad` method is called.
* Setting the CI data source to lazy. There's no need to load the CI data unless the user is on the CI tab.

(core) prevent badges from contributing to app ready, add afterLoad

---

app/scripts/modules/openstack/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/AccessSettings.controller.js
app/scripts/modules/openstack/serverGroup/configure/wizard/access/accessSettings.html
app/scripts/modules/openstack/serverGroup/details/serverGroupDetails.html

The radio button to enable adding a fip to each instance or not did not
clear out the selection. Clouddriver decides to associate a fip based on
that selection being set or not. So, clearing it when choosing not have
one.

(Openstack) Clear floatingNetworkId correctly.

---

app/scripts/modules/core/pipeline/config/triggers/pipeline/pipelineTrigger.html
app/scripts/modules/core/pipeline/config/triggers/pipeline/pipelineTrigger.module.js

Turns out we don't need runAsUser for pipelines triggering pipelines.
@anotherchrisberry @danielpeach 
tag: https://github.com/spinnaker/fiat/issues/114

Removes run as user UI elements in trigger-from-pipeline config

---

package.json
start.sh

If you use the wrong node version, it's not at all obvious why `npm start` fails. If this approach is too heavy-handed, I could just log a loud warning if you're not using the right node version.
@skim1420 fyi

use package.json node version on start up

---

app/scripts/modules/core/pipeline/config/triggers/cron/cron.validator.service.js
app/scripts/modules/core/pipeline/config/triggers/cron/cronPicker.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.less
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.module.js
package.json

Heavy template customization of https://github.com/vincentjames501/angular-cron-gen to allow users to select CRON expressions via the UI, e.g.

(core) allow cron configuration via UI selector

---

app/scripts/modules/amazon/subnet/subnetSelectField.directive.html
app/scripts/modules/amazon/subnet/subnetSelectField.directive.js

Otherwise, the user might think there's a subnet configured when there isn't one.

(aws) do not overwrite subnet in cluster config if read-only

---

app/scripts/modules/core/domain/IPipeline.ts
app/scripts/modules/core/domain/IStage.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.controller.ts
app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.html
app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.less
app/scripts/modules/core/pipeline/config/copyStage/copyStageCard.component.ts
app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/pipeline/pipelines.module.js

@duftler @anotherchrisberry please review.
Allows a pipeline stage to be copied from one pipeline to another.

(core) use pipeline stage as template

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js

This makes deck display the build source for chained pipeline deeper than one level.

Fetch buildInfo.lastBuild.number using recursion

---

build.gradle

Debian and Redhat have different names for apache package.

Modify build.gradle to fix RPM building

---

app/scripts/modules/amazon/subnet/subnetSelectField.directive.js

Fixes an issue where the load balancer's `isInternal` flag was not being displayed when the Create Load Balancer modal first opens
cc @robzienert

(aws) call onChange when subnet selector initialized

---

app/scripts/modules/kubernetes/pipeline/stages/resizeAsg/resizeStage.html
app/scripts/modules/kubernetes/pipeline/stages/resizeAsg/resizeStage.js
app/scripts/modules/kubernetes/pipeline/stages/resizeAsg/resizeStage.less

@lwander or @skim1420 
The new pipeline edit stage layout squashed some of the resize stage fields.

(kubernetes) restyle resize stage selectors

---

app/scripts/modules/amazon/serverGroup/configure/serverGroupConfiguration.service.js

We should not add the dash if there are exactly three parts in the package name, or we won't get the actual package back.

(aws) do not include - in package lookup if exact match found

---

app/scripts/modules/amazon/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/cloudfoundry/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/google/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/openstack/pipeline/stages/resizeAsg/resizeAsgStage.html
app/scripts/modules/titus/pipeline/stages/resizeAsg/resizeAsgStage.html

@duftler or @anotherchrisberry 
The "match capacity" fields are a little too small, and it's hard to see values longer than one digit. I've made the changes for all providers, except Kubernetes, which does not have a comparable set of fields.

makes resize stage match capacity inputs wider

---

app/scripts/modules/core/help/helpField.directive.html
app/scripts/modules/core/help/helpField.directive.js

Need to make the trigger configurable for the fast porperty scope constraints help text.
If no trigger is set on the directive then the previously hardcoded 'mouseenter foucus'  trigger is used.
@icfantv @anotherchrisberry PTAL

Added configurable trigger with sensible defaults for help-field directive.

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/presentation/less/imports/colors.less

Check preconditions and manual judgment stages will still be a darker gray when the judgment was "Stop"

(core) show stopped stages in lighter red

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/azure/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/pipeline/config/graph/pipeline.graph.directive.js
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.service.js
app/scripts/modules/core/pipeline/config/stages/bake/bakeExecutionLabel.html
app/scripts/modules/core/pipeline/config/stages/jenkins/jenkinsStage.js
app/scripts/modules/docker/pipeline/stages/bake/dockerBakeStage.js
app/scripts/modules/google/pipeline/stages/bake/gceBakeStage.js
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

If a Jenkins stage has test results, we add a new line to the stage label in the graph for each set of test results. Also, if it has a build number (and if it has test results, it probably has a build number), we also add a line for that. When we calculate the height of the label (to draw the pipeline graph), we currently don't take those extra lines into consideration, so the labels just bleed on top of each other and you can't see the full results without hovering over the label or clicking on the stage, which kind of defeats the purpose of showing them in the label.
Adding a simple check to stages with custom labels that span multiple lines to take those extra lines into consideration.
This has been bugging for a long time and I've been waiting for someone to complain about it but …

(core) calculate extra label lines on jenkins/bake stages

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

Forgot that people click the "> Details" link in the pipeline header to expand them.

(core) fix expanding pipeline via Details link

---

app/scripts/modules/core/application/application.less
app/scripts/modules/core/utils/stickyHeader/stickyHeader.less

Fixes an issue where un-stuck execution headers sometimes appear shorter.

(core) do not set header to 100% when un-stickying

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

If the user manually halts a canary stage, we currently do not surface the message they enter, so the stage failure message is:
```Monitor Canary failure: Orchestration completed.```
which is not very helpful.
This PR surfaces the message the user entered, so they'll see, e.g.
```Monitor Canary failure: Canary terminated by user. Reason: Bad features metadata jar.```

(netflix) show manual failure message on canary stage

---

app/scripts/modules/core/delivery/details/defaultExecutionDetails.html
app/scripts/modules/core/delivery/details/executionDetails.controller.js
app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/domain/taskStep.ts
app/scripts/modules/core/task/displayableTasks.filter.ts

If a hidden stage (e.g. `determineTargetServerGroup`) fails, it's not surfaced in the UI, and the stage summary has in incorrect status, so it's not marked as terminal (since it's derived from the child stages).
Also providing a very generic default template for stages that have no template, which just surfaces the tasks and any failure message.

(core) display hidden stage if it fails

---

package.json

The latest release (2.1.4) is not compatible with codelyzer. I am honestly not sure what codelyzer is doing, but will investigate later.

pin Typescript to 2.0.9

---

Dockerfile

* with the conversion to at-types, the npm postinstall script is no
longer needed since typings are installed via project dependencies.

(nflx): update dockerfile to remove postinstall

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.controller.spec.js

* `_.has` does not check an object's prototype, so the `onRefresh` was never being configured
* three minutes is a little too short in practice to determine that instances do not register any health, so bumping it to five minutes

Wait for up instances fixes

---

app/scripts/modules/core/pipeline/config/preconditions/selector/preconditionSelector.directive.js
app/scripts/modules/core/widgets/accountNamespaceClusterSelector.component.js
app/scripts/modules/core/widgets/accountRegionClusterSelector.component.js
app/scripts/modules/kubernetes/namespace/multiSelectField.component.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.js

@zanthrash PTAL. I just copied the logic from `accountRegionClusterSelector.component.js` into the other places with similar logic, not sure if this is totally correct.

(core) guard against null cluster in filtering

---

app/scripts/modules/core/cluster/filter/clusterFilter.service.spec.js
app/scripts/modules/core/filterModel/filter.model.service.js

- fixes `Unknown` filter on clusters (and other views that use this filter)
- add missing test to confirm filter works as desired.

(core): fix unknown filter and add test

---

app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.html

Before this patch, group memberships were stored in front50 with a trailing whitespace at the end. cc. @ttomsu

Use newlines so that group memberships doesn't get trailing whitespaces

---

app/scripts/modules/google/loadBalancer/configure/http/backendService/backendService.component.html

Adds checkbox for `enableCDN` for each `backendService`.

(gce) Added 'enableCDN' option for L7 upsert.

---

app/scripts/modules/google/loadBalancer/configure/http/listeners/listener.component.html
app/scripts/modules/google/loadBalancer/configure/http/listeners/listener.component.js

This makes all the forwarding rule attributes read-only after creation for L7 upsert. Certs can still be changed to support rotation.

(gce) Make L7 listeners readonly except for certs.

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/amazon/loadBalancer/configure/listeners.html

* prevent the clobbering of the ELB listener's cert name with the
formatted version if an error occurs during form submission (say,
due to validation).

(core): prevent clobbering of cert name on error

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/common/componentUrlDetails.component.ts
app/scripts/modules/appengine/common/conditionalDescriptionListItem.component.ts
app/scripts/modules/appengine/instance/details/details.html
app/scripts/modules/appengine/loadBalancer/details/details.html
app/scripts/modules/appengine/serverGroup/details/details.html

@duftler or @lwander or @jtk54 please review
Also re-scoped `conditionalDdDt` component as `appengineConditionalDdDt`.

(appengine) url details for server groups and load balancers

---

app/scripts/modules/amazon/loadBalancer/loadBalancer.transformer.js

(aws) fixing regression where ssl cert name was not show when editing a ELB

---

app/scripts/modules/core/pipeline/config/stages/stageConstants.ts

@icfantv or @duftler please review
This fixes the `Target` dropdowns for pipeline stages - they are currently empty.
`Object.freeze` causes errors when Angular tries to mutate the objects - hopefully using getters here is a good enough compromise.

(core) switch stage constants to getters

---

app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.controller.ts
app/scripts/modules/core/pipeline/config/copyStage/copyStage.modal.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.js

@anotherchrisberry @duftler 
Matt brought up a very good point that we shouldn't be able to copy strategy stages into pipeline configs and vice versa.

(core) prevent copying strategies into pipelines and vice versa

---

app/scripts/modules/core/delivery/service/execution.service.js

It's extremely rare, and if we're being honest, I'm not sure how it happens, but sometimes we get an error where `currentSummary` in the code below is null, so the `Object.assign` call barfs. My guess is this happens right when a pipeline starts and we have retrieved it, and there are no stages at all, and thus the `stageSummaries` is empty.

(core) guard against missing summary when synchronizing executions

---

app/scripts/modules/core/presentation/less/imports/animations.less

When a stage is running, there is a CSS animation that makes it glow, but it's very subtle and folks often don't notice is. This change just bumps the contrast to make the running stage more obvious.
Partially addresses https://github.com/spinnaker/spinnaker/issues/1327, but we still want to add some other visual indicator to manual judgment stages that are awaiting judgment.

(core) increase contrast range on running stage opacity animation

---

app/scripts/modules/core/application/service/application.write.service.spec.ts
app/scripts/modules/core/application/service/application.write.service.ts
app/scripts/modules/core/task/taskExecutor.ts

The `IJob` interface is generic and belongs in the taskExecutor (or maybe as a standalone file, but for now, it's at least more appropriate here).

(core) move Job interface to taskExecutor

---

app/scripts/modules/appengine/appengine.module.js
app/scripts/modules/appengine/domain/IAppengineServerGroup.ts
app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html
app/scripts/modules/appengine/serverGroup/writer/serverGroup.write.service.ts

@duftler or @lwander please review. Depends on https://github.com/spinnaker/orca/pull/1103 and https://github.com/spinnaker/clouddriver/pull/1345.
I can't see any use case for stopping a server group that is serving traffic, but it's consistent with what the cloud console UI and gcloud allow. I've included a warning message.

(appengine) start and stop tasks

---

app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html

@lwander correct logic for destroying a server group.

(appengine) correct destroy server group logic

---

app/scripts/modules/core/application/application.model.spec.ts
app/scripts/modules/core/application/nav/applicationNav.component.js
app/scripts/modules/core/application/service/applicationDataSource.ts
app/scripts/modules/core/entityTag/dataSourceAlerts.component.ts
app/scripts/modules/core/entityTag/dataSourceAlerts.popover.html
app/scripts/modules/core/entityTag/entityUiTags.component.ts
app/scripts/modules/core/entityTag/entityUiTags.popover.html

Also adding a timestamp to existing alerts/notices:

(core) surface alerts in data source tabs

---

app/scripts/modules/core/delivery/details/executionDetails.less

Recent CSS updates I made set the width of the `nav` to 260px, which was meant for the side nav; unfortunately, we also use `nav` in the execution steps.

(core) increase CSS selector specificity on execution details tabs

---

app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/core/loadBalancer/loadBalancer.read.service.ts

@anotherchrisberry quick fix - the new load balancer reader assumes that each provider's `normalizeLoadBalancer` function returns a promise, which is only true for a few of the providers.
(Also moved some App Engine error handling logic).

(core) adds check for promise in load balancer reader

---

app/scripts/modules/google/loadBalancer/configure/internal/gceCreateInternalLoadBalancer.controller.ts
app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts

@jtk54 please review.
These controllers relied on the load balancer writer to switch `provider` to `cloudProvider` in the upsert payload. We lost that right here: https://github.com/spinnaker/deck/commit/02f2d60acf75c5fd0d0fe829888405836dacf5bc#diff-948391bc7db35044eb30e399c038f7e4L34

(gce) s/provider/cloudProvider in load balancer controllers

---

app/scripts/modules/core/application/application.model.ts

@anotherchrisberry please review. @ttomsu FYI.
We run into trouble if we don't have accounts from the application config in places like this: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js#L209-L225
If you don't have any running infrastructure and your account isn't the default AND your account name isn't `my-account-name`, then your account won't be set correctly. There's similar logic in the openstack and kubernetes `serverGroupCommandBuilders`, and there might be lots of other places with similar issues.

(core) pull application configured accounts into application accounts

---

app/scripts/modules/core/domain/IOrchestratedItem.ts
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.ts
app/scripts/modules/core/utils/timeFormatters.js
app/scripts/modules/core/utils/timeFormatters.spec.js

When cutting this over to TS, I fixed some really bad code that was returning `NaN` for `runningTimeInMs`, but didn't do a good job testing it against a running pipeline.
Now explicitly short-circuiting and returning null if the item has not started.

(core) return null as runningTimeInMs when item has not started

---

app/scripts/modules/core/securityGroup/securityGroupWriter.service.ts

@icfantv some of the places where `upsertSecurityGroup` is called do not call it with `params`, which causes an error. 
Also, many of the places that do call it with `params` don't match the `ISecurityGroupJob` interface... not sure if you'd prefer I massage the callsites or leave `params` as `any`.

(aws) params should have default value in security group upsert

---

app/scripts/modules/core/loadBalancer/loadBalancer.write.service.ts
app/scripts/modules/google/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

@anotherchrisberry or @icfantv please review.
A load balancer has a property `type` (I see this in the load balancer model in Clouddriver), which is the cloud provider identifier string. This string can override `job.type` in the load balancer writer.
Also I've explicitly set the `cloudProvider` field for Google SSL load balancers, since sometimes that description is not created from the SslLoadBalancer class and does not get the `cloudProvider` getter.

(core) switch assign order in load balancer writer

---

app/scripts/modules/core/entityTag/entityTags.read.service.spec.ts
app/scripts/modules/core/entityTag/entityTags.read.service.ts

We ran into an issue where an application had > 150 server groups (and all had pretty long names), which blew out Gate.
This splits the URL for fetching tags into parallel fetches, then aggregates them.
If any of the calls fail, it will not break the UI - we just won't have the tags loaded, and we'll (at Netflix, at least) be notified of the load failure via the alert handler.

(core) limit URL size when fetching tags

---

app/scripts/modules/core/entityTag/entityTags.read.service.ts

save a trip to the server if there's nothing to fetch; also fix the error message to avoid getting a message of `[object Object]`

(core) do not try to fetch tags if no entities present

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.spec.js
app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/cluster/filter/clusterFilter.service.ts
app/scripts/modules/core/domain/ICluster.ts
app/scripts/modules/core/domain/serverGroup.ts
app/scripts/modules/core/entityTag/addEntityTagLinks.component.ts
app/scripts/modules/core/entityTag/dataSourceAlerts.component.ts
app/scripts/modules/core/entityTag/entityRef.builder.ts
app/scripts/modules/core/entityTag/entityTagEditor.controller.ts
app/scripts/modules/core/entityTag/entityTagEditor.modal.html
app/scripts/modules/core/entityTag/entityTagEditor.modal.less
app/scripts/modules/core/entityTag/entityTags.write.service.ts
app/scripts/modules/core/entityTag/entityUiTags.component.ts
app/scripts/modules/core/serverGroup/serverGroup.dataSource.js
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
test/mock/mockApplicationData.js

Adding the ability to specify a scope when creating a notice/alert. This is specifically targeted to clusters, but could be applied to other entities.
Results in:
(cross-region alert, regional notice)
This lets users create alerts/notices and have them persist across deployments.
I expect this functionality to continue to evolve as internal users provide feedback, hence the lack of tests.

(core) allow alerts/notices to be configured at the cluster level

---

app/scripts/modules/core/application/config/applicationConfig.controller.js

We sometimes get an error when a user deletes an application and the `attributes` do not exist. This prevents that.

(core) do not try to set app instance port on missing application

---

app/scripts/modules/core/delivery/stageFailureMessage/stageFailureMessage.component.ts
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.transformer.js

(netflix) SPIN-2285: Display exceptions when there is an exception when deploying a canary cluster

(core) Fixed issue with around stage error messages not displaying when navigating from one stage to another.

---

app/scripts/modules/core/application/modal/validation/applicationName.validator.spec.ts
app/scripts/modules/core/application/modal/validation/applicationName.validator.ts
app/scripts/modules/core/application/modal/validation/applicationNameValidationMessages.component.ts
app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.spec.ts
app/scripts/modules/core/application/modal/validation/validateApplicationName.directive.ts
karma.conf.js

Gets the list of providers from the account service instead of the provider registry (since all providers are always in the registry, even if the user has not configured them).
Had to make the validator async, which made this a much more involved PR than it would have been otherwise.
Also adding a flag to Chrome so it runs tests quickly, even if the window is in the background.
fixes https://github.com/spinnaker/spinnaker/issues/1379

(core) only validate app name against active providers

---

app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.spec.ts
app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.ts

Otherwise, every stage that succeeds will have an error message if it does any clouddriver operations.

(core) only take kato failure message from failed task

---

app/scripts/modules/core/pipeline/config/triggers/cron/cronPicker.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.module.js
package.json

* pull angular-cron-gen library internally to deck to fix several issues with the library.
* the latest version of the library will not allow angular expressions for the new `template-url` property as it uses the `templateUrl` function which executes before the scope is initialized so any scoped property value is not accessible.  this means that our template value set via a controller property is not accessible.  this is a long-standing issue [in the core library](https://github.com/angular/angular.js/issues/2895) and it doesn't look to be fixed anytime soon.
* an hourly cron trigger set in the UI to execute start at a specific time actually generates a daily cron expression so the portion of the hourly cron trigger that allows starting at a specific time was removed from deck's cron …

(core): pull angular-cron-gen library internally

---

.dockerignore
README.adoc
docker/run-apache2.sh
docker/spinnaker.conf.ssl

Set env variable `DECK_CERT=/pat/to/cert.crt` to configure apache with SSL. Must also set `DECK_KEY=/path/to/key.key`. Without these env vars set, apache starts up normally.
My custom settings.js wasn't getting picked up properly when I started my docker container, so moving settings.js to the directory that the ui is now served from (/opt/deck/html) if a custom file exists in /opt/spinnaker/config.
@lwander take a look please?

Adding SSL docker configuration

---

app/scripts/modules/titus/pipeline/stages/runJob/runJobExecutionDetails.html

Don't show the failure message if the job succeeded; otherwise, look for the failure in the stage context, then look in the completion details.
@tomaslin PTAL

(titus) surface run job failure message

---

app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/amazon/securityGroup/details/securityGroupDetail.html
app/scripts/modules/core/domain/ISecurityGroup.ts
app/scripts/modules/core/domain/serverGroup.ts
app/scripts/modules/core/entityTag/entityRef.builder.ts
app/scripts/modules/core/entityTag/entityTags.help.ts
app/scripts/modules/core/securityGroup/securityGroup.html
app/scripts/modules/core/securityGroup/securityGroupReader.service.ts

Nothing too exciting here. Had to extend the `securityGroup` on the scope to get the tags in place (we follow a similar pattern on instances, server groups, and load balancers).

(aws) add alerts/notices to security groups

---

app/scripts/modules/kubernetes/serverGroup/details/rollback/rollback.controller.js

@danielpeach PTAL 
Looks like this was dropped at some point

(kubernetes) restore namespace in rollback command

---

app/scripts/modules/core/delivery/stageFailureMessage/stageFailureMessage.component.ts
app/scripts/modules/core/entityTag/entityTags.read.service.ts

For whatever reason, this is happening more frequently than I expected. Trying to get more context to see why.
Also guarding against tasks not being present on a failed task, just because

(core) provide more context in error when entity tag load fails

---

app/scripts/modules/core/delivery/status/executionUser.filter.ts
app/scripts/modules/core/domain/IExecution.ts
app/scripts/modules/core/domain/IExecutionTrigger.ts
app/scripts/modules/core/domain/execution.ts
app/scripts/modules/core/domain/index.ts
app/scripts/modules/core/domain/serverGroup.ts

Resolves some confusion about `IStage` and `ITrigger`, where we've accidentally conflated the stage/trigger in the execution with the one in the pipeline config.

(core) implement IExecutionTrigger

---

app/scripts/modules/core/domain/ICluster.ts
app/scripts/modules/core/domain/IRegionalCluster.ts
app/scripts/modules/core/entityTag/entityRef.builder.ts

`region` is not really a field on clusters - it was added for entity tags to allow scoping, but that's not applicable to clusters generally.

(core) use IRegionalCluster for entityRef building

---

app/scripts/modules/core/entityTag/entityTags.read.service.spec.ts
app/scripts/modules/core/entityTag/entityTags.read.service.ts
app/scripts/modules/core/retry/retry.service.spec.ts
app/scripts/modules/core/retry/retry.service.ts
app/scripts/modules/docker/image/docker.image.reader.service.ts

For whatever reason, we get intermittent failures loading entity tags. I don't have good info on why they're failing, but it seems to be transient. Adding a single retry in the event the `GET` fails the first time.
@danielpeach PTAL - I modified the retry service to handle failures, but I am not totally sure that's in line with your intent in that service. If not, I can change my code and add a method that explicitly handles a failure case like the one we're seeing here.

(core) retry tagging before failing; make retryService tolerate failure

---

app/scripts/modules/core/retry/retry.service.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyPipelineBuilder.service.ts

Application name was missing from the FP created ad-hoc pipelines, causing the url for Manual Judgement stage to not properly render.

Add application to Fast Property created pipelines.

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/docker/pipeline/stages/bake/bakeExecutionDetails.html
app/scripts/modules/docker/pipeline/stages/bake/bakeStage.html

These changes are related to (but not dependent on) this PR https://github.com/spinnaker/rosco/pull/172
The motivation here is to add support for specifying common parameters in the docker bake stage. Not quite sure about the fields in `bakeExecutionDetails.html`, so please comment if someone has strong opinions on this.

Adding image name, tag and organization to the docker bake stage

---

app/scripts/modules/core/entityTag/dataSourceAlerts.component.ts
app/scripts/modules/core/presentation/main.less

If there are so many alerts that the popover won't fit on the page, it ends up overflowing off the bottom of the screen, which is...no good. This change restricts the popover to half the screen height and allows scrolling in the event it doesn't fit.

(core) position tab alert on bottom, avoid overflow

---

app/scripts/modules/netflix/fastProperties/domain/propertyPipelineStage.ts

Fixes the submission of 'null' for originalProperties when there is no orignal state for a property e.g. when creating a new one.

Fix Fast Property Create NPE

---

app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.controller.ts
app/scripts/modules/appengine/serverGroup/details/details.html
app/scripts/modules/core/domain/serverGroup.ts

@lwander or @jtk54 or @duftler please review.
Not sure if this is a great idea, but I think there should be a convenient way of deploying into the same cluster for App Engine, even if we can't copy over the rest of the server group's configuration.

(appengine) ad hoc clone server group

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/core/delivery/delivery.states.ts
app/scripts/modules/core/delivery/details/executionDetails.controller.js
app/scripts/modules/core/domain/IEntityTags.ts
app/scripts/modules/core/entityTag/entitySource.component.ts
app/scripts/modules/core/entityTag/entitySource.popover.html
app/scripts/modules/core/entityTag/entityTags.read.service.ts
app/scripts/modules/core/presentation/details.less
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html
app/scripts/modules/titus/serverGroup/details/serverGroupDetails.html

* if present, show the task/pipeline details
* changing "Availability Zones" label to "Zones", which actually fits without spilling into an ellipsis after "Availability"
* allow deep linking to a specific stage via `stageId` parameter on an execution URL
@jrsquared or @zanthrash or @icfantv PTAL

(netflix) display server group provenance if available

---

app/scripts/modules/docker/image/dockerImageAndTagSelector.component.spec.ts
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/netflix/fastProperties/domain/scope.domain.spec.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.component.spec.ts

This was initially a one-line change: moving `this.updateOrganizationsList()` down so it executes after `this.updateRepositoryMap(images)`. This ensures tags are pre-populated when the controller initializes with existing data.
All the other changes are performance optimizations. I wouldn't have even noticed them, but I had my browser console open and noticed, when the modal opens, warnings like this:
```
[Violation] Long running JavaScript task took 974ms
```
It was pretty consistently running between 900 and 1100 ms, and it's blocking. Running the profiler showed almost all of that time being spent in the `all.includes(...)` calls - not what I expected, but I guess it makes sense when there are 35k+ images. 
The easy fix is to jam everything into the array, then remove duplicates at the …

(docker) fix tag initialization, optimize loading

---

app/scripts/modules/amazon/instance/details/instance.details.controller.js
app/scripts/modules/amazon/instance/details/instanceDetails.html
app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/appengine/instance/details/details.html
app/scripts/modules/azure/instance/details/instance.details.controller.js
app/scripts/modules/azure/instance/details/instanceDetails.html
app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.js
app/scripts/modules/cloudfoundry/instance/details/instanceDetails.html
app/scripts/modules/google/instance/details/instance.details.controller.js
app/scripts/modules/google/instance/details/instanceDetails.html
app/scripts/modules/kubernetes/instance/details/details.controller.js
app/scripts/modules/kubernetes/instance/details/details.html
app/scripts/modules/netflix/instance/aws/instanceDetails.html
app/scripts/modules/netflix/instance/titus/instanceDetails.html
app/scripts/modules/openstack/instance/details/instance.details.controller.js
app/scripts/modules/openstack/instance/details/instanceDetails.html
app/scripts/modules/titus/instance/details/instance.details.controller.js

We used to fail silently (confusing) when trying to directly navigate to an instance. This change will keep the instance details panel up, but with a message that the instance could not be found.

(all providers) Show that an instance is not found instead of failing siliently

---

app/scripts/modules/cloudfoundry/loadBalancer/configure/createLoadBalancer.html

The original modal wizard directives are being killed.  These files were converted to the V2ModalWizard.
@gregturn 
Please test and merge this PR as soon as you can.

(cloudfoundry) Convert to V2ModalWizard

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/kubernetes/container/volumes.component.html
app/scripts/modules/kubernetes/container/volumes.component.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/volumes.html

Closes https://github.com/spinnaker/spinnaker/issues/1215
I would like to find a better way to handle the overlap between the Run Job stage config and the Deploy config, but it isn't obvious how to do so since there are a bunch of slight differences (especially in the templates)
.

(k8s) adds support for kuberntes config map as volume source

---

app/scripts/modules/netflix/fastProperties/view/fastProperties.controller.js
app/scripts/modules/netflix/fastProperties/view/fastPropertyFilterSearch.component.ts

Searching for property keys was prominant in the old UI and got forgotten in the new.
This adds it back via the filter mechinism.
It also cleans up the filter tags when a new search is done on the global view.

(netflix) Add back Fast Property key/value search.

---

app/scripts/modules/core/application/config/applicationConfig.controller.js
app/scripts/modules/core/application/config/applicationConfig.view.html
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.html
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.ts
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.help.ts
app/scripts/modules/netflix/application/applicationConfig.html

Companion PR to https://github.com/spinnaker/orca/pull/1178; allows users to declare certain clusters as protected or critical or...basically, clusters that should never be empty, or only have disabled server groups.
I'm mostly looking for feedback on the wording and look-and-feel...

(core) allow users to configure traffic protected clusters

---

app/scripts/modules/appengine/instance/details/details.controller.ts
app/scripts/modules/core/cluster/rollups.less

@icfantv or @anotherchrisberry please review. Not sure if this will render properly for AWS.
Before:
After:

(core) instance details list word break

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/pipeline/stages/bake/bakeStage.html
app/scripts/modules/azure/pipeline/stages/bake/bakeStage.html
app/scripts/modules/google/pipeline/stages/bake/bakeStage.html
app/scripts/modules/openstack/pipeline/stages/bake/bakeStage.html
package.json

* update the bake stage to automatically expand the advanced options
section if any of the advanced options are populated.  This will now
ignore the `showAdvancedOptions` property on the stage object.
* update package.json to downgrade the typings for jasmine to get the
compiler to stop complaining about jasmine's typings file.  This error
goes away in TS 2.1.

(various): update bake stage adv opts visibility

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/cloudfoundry/loadBalancer/configure/CreateLoadBalancerCtrl.js
app/scripts/modules/cloudfoundry/loadBalancer/configure/CreateLoadBalancerCtrl.spec.js
app/scripts/modules/google/loadBalancer/configure/network/createLoadBalancer.controller.js
app/scripts/modules/google/loadBalancer/configure/network/createLoadBalancer.controller.spec.js
app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.spec.js

When creating a load balancer, it would populate the list of load balancers from a local cache that could be out of date.
This change:
* will always refresh the list of load balancers before creating a new one.
* will only compare against application level load balancers. Since we enforce uniqueness of application names and enforce load balancers name start with the application name, no need to compare against the entire list.

(all providers) Stop using local cache for checking name collisions when creating a load balancer

---

app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.html
app/scripts/modules/core/application/config/trafficGuard/trafficGuardConfig.component.ts
app/scripts/modules/core/naming/naming.service.ts

Per user feedback, it would be nice to see what's going to be guarded:

(core) show matched clusters on traffic guard config

---

app/scripts/modules/netflix/blesk/blesk.module.js

* set a `z-index` on the blesk alerts so that the dropdown nav menu will
appear on top of it, instead of behind.

(netflix): set z-index on blesk alerts

---

app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyFilter.directive.ts
app/scripts/modules/netflix/fastProperties/dataNav/fastPropertyFilterSearch.less
app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.html
app/scripts/modules/netflix/fastProperties/view/fastProperties.controller.js
app/scripts/modules/netflix/fastProperties/view/fastPropertyFilterSearch.component.html
app/scripts/modules/netflix/fastProperties/view/fastPropertyFilterSearch.component.ts
app/scripts/modules/netflix/fastProperties/view/fastPropertyPodTable.html
app/scripts/modules/netflix/fastProperties/view/fastPropertyPods.component.js
app/scripts/modules/netflix/fastProperties/view/fastPropertyPods.html
app/scripts/modules/netflix/fastProperties/view/fastPropertyTable.directive.js
app/scripts/modules/netflix/fastProperties/view/properties.html

Reduces the number of watches on a the Propertie tab by using our good friend Mr. innerHtml to
render the list of properties.  This is necessary for applications that have a lot of properties. (I'm looking at you API)
Also made some improvements around the filtering, and the filter tag generation.
Other small cosmetic tweeks:
- increased the max-width on the filter dropdown list
- Added spinners to indicate something was happening.

Fast Property performance improvements

---

app/scripts/modules/core/core.module.js
package.json

This was only sticking around to support the legacy modal wizards.

(core) remove angular-wizard dependency

---

app/scripts/modules/core/application/modal/editApplication.html
app/scripts/modules/core/application/modal/newapplication.html
app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.html
app/scripts/modules/core/pipeline/config/triggers/git/gitTrigger.module.js
app/scripts/modules/netflix/application/createApplication.modal.html
app/scripts/modules/netflix/application/editApplication.modal.html
halconfig/settings.js
settings.js

PR [#153](https://github.com/spinnaker/igor/pull/153) has been opened against Igor.
PR [#137](https://github.com/spinnaker/echo/pull/137) has been opened against Echo.
PR [#346](https://github.com/spinnaker/gate/pull/346) has been opened against Gate.
BitBucket Server (a.k.a. Stash) support already exists. This adds BitBucket Cloud support of pipeline triggers based on BitBucket webhooks and provides Orca the ability to retrieve a list of commits from BitBucket as part of it's GetCommits stage.

Add BitBucket support

---

app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/fastProperties.less
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.spec.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts
app/scripts/modules/netflix/fastProperties/wizard/createFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.componet.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyReview/propertyReview.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

- Impact count calculations now take the selected environment into consideration (SPIN-2330 &  SPIN-2349)
- Scope selectors now start loading as soon as the modal opens vs. after a key/value pair were entered.
- Email address in now prepopulated with logged in users email.
- Small validation and messaging tweaks when CRUDing a FP.
@anotherchrisberry @icfantv @jrsquared PTAL

(netflix) Fast properties impact count on env.

---

app/scripts/modules/netflix/pipeline/stage/properties/create/propertyExecutionDetails.controller.js
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyExecutionDetails.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyExecutionLabel.html

- Added the action type (CREATE, UPDATE, DELETE) to the execution label and added it in the status tab.
- When pipeline fails it will now let the user know that the properties were rolled back and displays the rolled back state.
- Properties that were deleted were not displaying any key/value pairs in the details tab.
@anotherchrisberry @icfantv @jrsquared PTAL

Enhance fast property execution details

---

app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js
app/scripts/modules/titus/serverGroup/configure/serverGroupConfiguration.service.js

Kind of surprised we haven't heard complaints about this before.
When the user switches accounts on a Run Job stage or when configuring a new server group in Titus, we don't update the registry, so they're still picking organizations and images from the previous registry (if the registry is different between the old and new account selection).
Most of the time, this seems to be a non-issue because there's a lot of overlap (at least at Netflix) between the registries - people seems to be publishing most images to both.
However, if they've chosen an organization that's _not_ in both, we'll potentially switch the registry in the run job stage when it initializes after they've saved it. Since the selector component has already started loading the images for the old registry, there's a race …

fix(docker/titus): switch registry when changing accounts

---

app/scripts/modules/netflix/fastProperties/domain/scope.domain.spec.ts
app/scripts/modules/netflix/fastProperties/domain/scope.domain.ts
app/scripts/modules/netflix/fastProperties/scope/categoryButtonList.component.html
app/scripts/modules/netflix/fastProperties/scope/categoryButtonList.component.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.html
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts
app/scripts/modules/netflix/fastProperties/scope/fastPropetyScopeSearch.less
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts

- Downstream orca change needed to make this work (https://github.com/spinnaker/orca/pull/1192), but this can go in before.
- Made changes to the way scopes are laid out.
- Selected scopes can also be edited to allow for scoping Fast Properties to ASGs that have yet to be created.  This is useful for FP that are needed at startup.
@anotherchrisberry @icfantv @jrsquared PTAL

Scope Fast Property to multiple apps

---

app/scripts/modules/core/cancelModal/cancel.html
app/scripts/modules/core/cancelModal/cancel.less
app/scripts/modules/core/cancelModal/cancelModal.controller.ts
app/scripts/modules/core/cancelModal/cancelModal.service.ts
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/service/execution.service.js

* Adds a `force=true` parameter to the backend request if checked
* Corresponds with the following PR’s in Gate and Orca:
* https://github.com/spinnaker/orca/pull/1188
* https://github.com/spinnaker/gate/pull/345
* The checkbox will only show if the execution engine is `v2`

Add a "force" checkbox to the cancel pipeline modal dialog

---

app/scripts/modules/core/application/service/application.write.service.ts

A number of config sections don't send the list of cloud providers to the application writer, so they end up getting overwritten when a user saves them. Really, we should only set the `cloudProviders` field if it's explicitly sent.

fix(appconfig): do not overwrite cloudProviders when editing app

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/titus/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js

- added required ```runtimeLimitSecs``` text field
- default is set to 60s
- This change will ensure this field isn't set to 0, which translates
to a titus container running indefinitely.

(titus) Adding a UI element for runtimeLimitSecs for the titus runJob stage

---

app/scripts/modules/amazon/loadBalancer/details/loadBalancerDetail.controller.js

Without the vpcId, the force cache refresh operation will not evict the load balancer from the cache, because it is looking for a key with the vpcId in it, which isn't supplied, so...the load balancer just gets stuck in the cache until a new redis instance is primed.

fix(aws): send vpcId when deleting load balancers

---

app/scripts/modules/core/pipeline/config/stages/baseProviderStage/baseProviderStage.js
app/scripts/modules/titus/pipeline/stages/bake/titusBakeStage.js
app/scripts/modules/titus/pipeline/stages/runJob/titusRunJobStage.js

The code around multi-provider stages is a mess and needs to be addressed at some point (I'm hoping to refactor it in April). In the meantime, this change will consider the `providesFor` field when selecting the cloud provider implementation for a given stage.
This really only affects Netflix, as we've used this `providesFor` field to handle Titus functionality.

fix(pipelines): consider providesFor field when selecting stage provider

---

app/scripts/modules/core/delivery/service/execution.service.js
app/scripts/modules/core/delivery/service/execution.service.spec.js
app/scripts/modules/core/pipeline/config/graph/pipeline.graph.component.ts

We don't need to watch the entire execution as a deep watch on the pipeline graph - just the status and the extra label lines.

perf(pipelines): only watch status, execution label line counts

---

app/scripts/modules/core/application/modal/groupMembershipConfigurer.component.html

@ttomsu @PerGon please review.
@PerGon this affects the recent work you did on this component. It prevents users from selecting roles they do not have (though the autocomplete functionality still works).

fix(core) do not allow free-form text in group membership config

---

app/scripts/modules/core/serverGroup/details/serverGroupWarningMessage.service.spec.ts
app/scripts/modules/core/serverGroup/details/serverGroupWarningMessage.service.ts

* updated sensitivity around disabling clusters.  specifically, added
checks for corner cases such that a cluster could be disabled and the
user not given added context as to the ramifications of the disable
action.  this change now adds checks for if it's the last active cluster
or if it's the only cluster remaining.

fix(serverGroups): cluster disable warning update

---

app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.spec.ts
app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.ts
app/scripts/modules/netflix/fastProperties/domain/propertyPipelineStage.ts
app/scripts/modules/netflix/fastProperties/wizard/deleteFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyPipelineBuilder.service.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyReview/propertyReview.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeReadOnly.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeUpdatable.component.html
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeUpdatable.component.ts
app/scripts/modules/netflix/fastProperties/wizard/updateFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/updateFastPropertyWizard.html

Once a Fast Property has been set the scope can't be easily updated b/c the key of the
Property is a pipe delimited string of the property key and all the values of its scope.
To get around that limitation we create 2 Persisted property stages.  The first one will
create a new property with the new scope.  Once that completes we follow up with a delete property
stage that cleans up the original property.
When editing the property the user will be shown the original scope and they will be able to select the new scope.  If they choose to update the scope they can remove it and only an upsert property stage will be used.
@anotherchrisberry @icfantv @jrsquared  PTAL

(netflix) Allow Fast property scope to be updated.

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

* some of the numerical data for canaries is stored as strings which
caused the UI to throw JS errors for input fields of type `number`.
added code to properly parse these values for existing canary
configurations.  new canary configurations are not affected.

fix(canary): fix data normalization issue

---

app/scripts/modules/google/domain/autoHealingPolicy.ts
app/scripts/modules/google/domain/index.ts
app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicy.html
app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.ts
app/scripts/modules/google/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js

Pulls out all of the server group wizard-specific pieces from the auto healing policy configurer. There should be no changes in functionality or appearance.
Tested this manually for create/clone/pipeline deploy stages.

refactor(gce) makes autoHealing configurer generic

---

app/scripts/modules/netflix/pipeline/stage/canary/canaryScore.component.ts
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

* add very rudimentary support to indicate the user that they're using
expressions for canary field values but do not allow them to edit it
directly.  rather, we want them to edit via the pipeline JSON editor.
* do not barf on loading canary stages using expressions as canary field
values.

fix(canary): do not break on canary expressions

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

The "Details" toggle in the pipelines tab would open the first time you clicked it and then if
the "Details" link on another pipeline was click all the details sections of all the pipelines would close.
One would then have to re-click the "Details" link to open up the details view.
This fixs the toggle to be inline with expected behavior.

(core, SPIN-2438) Fix Pipeline Details Toggle

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js

Fixes the details toggle when clicking on the stages and stage nodes.

(core, SPIN-2438) Re-fix Pipeline Details Toggle

---

package.json

New version of libraray was causing docker build failures.

Pinning @types/jasmine to 2.5.42

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.html

@icfantv please review.
App Engine has no notion of capacity at deploy time, so there's nothing to populate here.

fix(core) hide capacity in deploy execution details if unnecessary

---

app/scripts/modules/core/delivery/service/executions.transformer.service.js
app/scripts/modules/core/delivery/service/executions.transformer.service.spec.js

This makes buildInfoUrl being preferred over constructing one from the jenkins object.

prefer buildInfoUrl over jenkins details when showing link to ci build

---

app/scripts/modules/core/cluster/cluster.service.js
app/scripts/modules/core/serverGroup/serverGroup.dataSource.js
app/scripts/modules/core/serverGroup/serverGroup.transformer.js
app/scripts/modules/google/serverGroup/serverGroup.transformer.js
app/scripts/modules/google/serverGroup/serverGroup.transformer.spec.js

@jtk54 or @duftler please review.
This fixes the load balancer tags for HTTP(S) load balancers:
This is a lingering issue from the listener -> url map transformation we have to do in the UI.
@anotherchrisberry FYI - I made a slight change in the core server group transformer.

fix(gce): normalize server group load balancers

---

app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js

The issue is that a load balancer can't be updated. Another one will be updated or created.
There're two reasons:
1. `$scope.loadBalancer.account` will be set to the first found account among all accounts as https://github.com/spinnaker/deck/blob/7427282bfea29a779d71b2e609be9a9f2d962f7c/app/scripts/modules/kubernetes/loadBalancer/configure/wizard/upsert.controller.js#L84 shows
2. $scope.loadBalancer is actually `loadBalancer.description`. But the `description.account` in the API response is null. This is fixed in https://github.com/spinnaker/clouddriver/pull/1527

fix(kubernetes) update user selected load balancer

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.html

* modify the cluster column to not shove everything off the containing
viewport when the cluster name is super long.

fix(core/pipeline): handle long cluster names

---

app/scripts/modules/core/pipeline/config/stages/travis/travisExecutionDetails.html

The new Travis stage was missing tabs in the execution details:
After this fix:

fix(travis stage): Tabs should be displayed in execution details

---

app/scripts/modules/core/delivery/executions/executions.controller.js

This has always been something of an issue, but it's more apparent now, as we fade out inactive pipelines when another execution has been routed to.

fix(executions): auto-navigate away from missing execution

---

app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.html
app/scripts/modules/core/delivery/executionGroup/execution/execution.directive.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.js
app/scripts/modules/core/delivery/executionGroup/executionGroup.less
app/scripts/modules/core/delivery/executions/executions.less
app/scripts/modules/core/delivery/status/executionStatus.html
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.service.ts

* Don't show account targets in the header unless it's grouped by pipeline
* Do show account targets in pipeline name header when not grouped by pipeline
* Remove unused `showPipelineName` field

refactor(executions): better render accounts, headings in executions

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/blesk/blesk.less
app/scripts/modules/netflix/blesk/blesk.module.ts
app/scripts/modules/netflix/blesk/bleskOverrides.css

Turns out fixing the height of the content wasn't a great idea.
Also cleaning up look/feel for blesk notifications to make them look okay in Spinnaker.

fix(netflix) prevent blesk from pushing down other content

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/utils/stickyHeader/stickyHeader.directive.ts
app/scripts/modules/netflix/blesk/blesk.less
app/scripts/modules/netflix/blesk/blesk.module.ts
app/scripts/modules/netflix/fastProperties/dataNav/fpRollout.less

This is definitely the last set of bug fixes for the UI refresh.
* fixed an issue where the pipeline config screen was not scrollable
* removed the `position: relative` on the sticky headers container, since it doesn't seem to be doing anything except cutting off the tooltips on very long instance IDs in the clusters view

fix(ui): fix scroll on pipeline config

---

app/scripts/modules/core/delivery/details/executionDetails.less
app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/utils/stickyHeader/stickyHeader.directive.ts

If there's less than 800px for the execution details, fills the entire width of the details panel.
Also, better handle sticky headers on window resize or hiding of filters.

fix(pipelines) better handle execution details on small screen

---

app/scripts/modules/amazon/pipeline/stages/destroyAsg/awsDestroyAsgStage.js
app/scripts/modules/amazon/pipeline/stages/resizeAsg/awsResizeAsgStage.js
app/scripts/modules/amazon/pipeline/stages/scaleDownCluster/awsScaleDownClusterStage.js
app/scripts/modules/amazon/pipeline/stages/shrinkCluster/awsShrinkClusterStage.js
app/scripts/modules/azure/pipeline/stages/destroyAsg/azureDestroyAsgStage.js
app/scripts/modules/cloudfoundry/pipeline/stages/destroyAsg/cfDestroyAsgStage.js
app/scripts/modules/cloudfoundry/pipeline/stages/scaleDownCluster/cfScaleDownClusterStage.js
app/scripts/modules/cloudfoundry/pipeline/stages/shrinkCluster/cfShrinkClusterStage.js
app/scripts/modules/core/delivery/executionGroup/executionGroup.directive.html
app/scripts/modules/core/delivery/filter/executionFilter.service.js
app/scripts/modules/core/delivery/status/executionStatus.html
app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/google/pipeline/stages/destroyAsg/gceDestroyAsgStage.js
app/scripts/modules/google/pipeline/stages/resizeAsg/gceResizeAsgStage.js
app/scripts/modules/google/pipeline/stages/scaleDownCluster/gceScaleDownClusterStage.js
app/scripts/modules/google/pipeline/stages/shrinkCluster/gceShrinkClusterStage.js
app/scripts/modules/kubernetes/pipeline/stages/destroyAsg/kubernetesDestroyAsgStage.js
app/scripts/modules/kubernetes/pipeline/stages/shrinkCluster/shrinkClusterStage.js
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js
app/scripts/modules/openstack/pipeline/stages/destroyAsg/openstackDestroyAsgStage.js
app/scripts/modules/openstack/pipeline/stages/resizeAsg/openstackResizeAsgStage.js
app/scripts/modules/openstack/pipeline/stages/scaleDownCluster/openstackScaleDownClusterStage.js
app/scripts/modules/openstack/pipeline/stages/shrinkCluster/openstackShrinkClusterStage.js
app/scripts/modules/titus/pipeline/stages/destroyAsg/titusDestroyAsgStage.js
app/scripts/modules/titus/pipeline/stages/resizeAsg/titusResizeAsgStage.js
app/scripts/modules/titus/pipeline/stages/scaleDownCluster/titusScaleDownClusterStage.js
app/scripts/modules/titus/pipeline/stages/shrinkCluster/titusShrinkClusterStage.js

If a pipeline has never run, there are no executions from which to extract account info. We can still pull that data from the config.

feat(pipelines): show accounts from config if no executions found

---

app/scripts/modules/kubernetes/serverGroup/details/resize/resize.controller.js
app/scripts/modules/kubernetes/serverGroup/details/resize/resize.html

Sets min/max/desired to be equal in the resize description (without an autoscaler). This is what GCE does for a resize operation, and it prevents things like this:
Before:
After:

fix(kubernetes): resize modal bug and restyling

---

app/scripts/modules/core/pipeline/config/triggers/travis/selectorTemplate.html
app/scripts/modules/core/pipeline/config/triggers/travis/travisTrigger.module.ts
app/scripts/modules/core/pipeline/config/triggers/travis/travisTriggerOptions.component.spec.ts
app/scripts/modules/core/pipeline/config/triggers/travis/travisTriggerOptions.component.ts

Fixed by properly converting the 'travis-trigger-options' directive into a component in a more "typescripty" way and replacing `bindToController` with `bindings`.

fix(travis stage): Travis trigger component not working properly

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.less

Current:
This PR:
Still gonna run into problems when someone is targeting five accounts with long names, but we can deal with that when we need to...

fix(pipelines): fix alignment on multi-line account labels

---

app/scripts/modules/core/application/applications.html
app/scripts/modules/core/projects/projects.html
app/scripts/modules/core/task/tasks.html

Updating to the newest ui-bootstrap broke the pagination directive (it's now restricted to `A` instead of `E`).
cc @jrsquared

fix(pagination) fix pagination on /applications, /projects

---

app/scripts/modules/core/securityGroup/AllSecurityGroupsCtrl.js
app/scripts/modules/core/securityGroup/filter/SecurityGroupFilterCtrl.js

Long ago, it mattered that we refreshed security groups whenever we refreshed load balancers and server groups. We don't really need to do that now, as the security group loader considers the state of those other data sources.
cc @jrsquared

fix(security groups): prevent page flashing on security groups

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/azure/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.js
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

This commit adds Travis stages or triggers as valid predecessors to the bake stages.

fix(travis stage): Bake stages do not recognize Travis stage or trigger

---

app/scripts/modules/kubernetes/serverGroup/configure/wizard/replicas.html

Kubernetes Horizontal autoscaling's CPU utilization is calculated by `requested` CPU, and in some cases, it can be larger than 100%.
If you want to over provision your Node you would define small CPU request compared to your CPU limit. It can be useful if you have different small applications with temporary traffic.
From my cluster:
```
NAME                      REFERENCE                             TARGET    CURRENT   MINPODS   MAXPODS
alert-worker              Deployment/alert-worker               1050%       986%    2         10 
```
=>
```
request: 10m
limit: 150m
wanted target: 70%
target to set: 1050%
->
(150m * 0.7) / 10m = 10.5 => 1050%
```
In Kubernetes the `targetCPUUtilizationPercentage` has a type `int32` but I didn't find any validation for it.

fix(kubernetes): replicas targetCPUUtilizationPercentage can be larger than 100

---

app/scripts/modules/core/cluster/filter/multiselect.model.js
app/scripts/modules/core/instance/instances.directive.js

For whatever reason, clicking an active instance or server group in the clusters view clears the navigation filters. This prevents the attempted state navigation if the user is already there, preserving the filters.

fix(clusters): preserve filters when clicking active item

---

app/scripts/modules/kubernetes/securityGroup/details/details.controller.js

Deleting Security Groups in a namespace other than default would error
out becuase it wasn't passing namespace to the securityGroupWriter.

fix(kubernetes): Delete Security Group Namespace

---

app/scripts/modules/kubernetes/securityGroup/configure/wizard/upsert.controller.js

When changing namespace, the load balancer list wasn't being updated.
This is important because you might want to associate rules with load
balancers in the same namespace or associate rules with load balancers in other namespaces. It may be worth updating further in the
future to configure namespace for the SG as well as namespace for the
LB.
Fixes [#1535](https://github.com/spinnaker/spinnaker/issues/1535)

fix(kubernetes): update load balancer list when namespace changes

---

app/scripts/modules/core/delivery/executionGroup/executionGroup.less

right now, each tag takes up the entire width of the execution bar, which is not great

fix(pipelines): render account tag inline on time boundary view

---

app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/core/diffs/viewChangesLink.component.ts
app/scripts/modules/core/pipeline/config/stages/deploy/deployExecutionDetails.controller.js

* fix View Changes functionality when no metadata is present on ASGs.
* fix Pipeline execution view around changes when one or both of
commits/jarDiffs are missing.

fix(aws/netflix): fix diff view when no metadata

---

app/scripts/modules/core/securityGroup/securityGroupReader.service.ts

We don't currently load entity tags on the standalone security group, since we don't load them for the (non-existent) application.
This fixes that.

fix(securitygroups): render entity tags on standalone security groups

---

app/scripts/modules/core/cluster/filter/multiselect.model.js

Followup to a commit last week, preventing removal of filters when clicking an instance or server group - we didn't take into account the case where the "with details" box is checked. This fixes that scenario.

fix(instances): preserve filters when double-clicking

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/pipeline/config/pipelineConfigProvider.js
app/scripts/modules/core/pipeline/config/stages/stage.html
app/scripts/modules/core/pipeline/config/stages/unmatchedStageTypeStage/unmatchedStageTypeStage.controller.spec.ts
app/scripts/modules/core/pipeline/config/stages/unmatchedStageTypeStage/unmatchedStageTypeStage.controller.ts
app/scripts/modules/core/pipeline/config/stages/unmatchedStageTypeStage/unmatchedStageTypeStage.html
app/scripts/modules/core/pipeline/config/stages/unmatchedStageTypeStage/unmatchedStageTypeStage.ts
app/scripts/modules/core/utils/json/json.utility.service.ts

@anotherchrisberry or @icfantv or @jrsquared please review.
Renders and allows a user to edit stage JSON if there isn't a dedicated UI for the stage type.

feat(core): render pipeline stages without UIs

---

app/scripts/modules/core/diffs/viewChangesLink.component.ts
app/scripts/modules/core/entityTag/entitySource.component.ts

Currently, with entity tags enabled, if we find a provenance tag on a server group, we'll fetch the execution five times when the server group details is initially rendered, then three times whenever it's refreshed. This is because we don't cache the result of that fetch in either the `entityTagSource` or `viewChangesLink` components.
With this PR, we'll typically only fetch the execution twice: once when each component first renders. After that, the result is cached.
For `entityTagSource`, there's no concern: it's just used to generate a deep link, and that won't change, even if the execution is still running.
For `viewChangesLink`, we'll continue refetching (but only once per cycle) in the rare case the deploy stage is still running and hasn't added commits or jardiffs to its context.

perf(aws): do not overfetch execution for ASG source/changes

---

app/scripts/modules/amazon/serverGroup/details/scalingPolicy/scalingPolicySummary.component.html
app/scripts/modules/core/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/core/delivery/triggers/nextRun.component.js
app/scripts/modules/core/entityTag/dataSourceAlerts.component.ts
app/scripts/modules/core/entityTag/entitySource.component.ts
app/scripts/modules/core/entityTag/entityUiTags.component.ts
app/scripts/modules/core/help/helpField.component.ts
app/scripts/modules/core/pipeline/config/graph/pipelineGraph.component.html
app/scripts/modules/core/pipeline/config/pipelineConfigurer.html
app/scripts/modules/netflix/availability/availability.trend.html

As of ui-bootstrap 2.x, `popover-trigger` requires strings wrapped in quotes.

fix(popover): stringify popover triggers

---

app/scripts/modules/netflix/fastProperties/domain/propertyCommand.model.ts

Two issues:
1. `isEqual` does not work well once Angular comes into the picture, as it adds things like `$$hashKey` to the Angular-rendered object.
2. `env` is not set on the new `Scope`, (but is also not editable when selecting a property scope), so needs to be omitted when making the comparison.

fix(netflix): use angular.equals to compare fp scopes

---

app/scripts/modules/docker/image/dockerImageAndTagSelector.component.html
app/scripts/modules/docker/image/dockerImageAndTagSelector.component.ts

The help text indicates the field is optional, but for some reason it's marked as required in the HTML, and we have handlers that will set it to `null`, so maybe it's not required? Functionally, it appears to be optional.
Setting it to `null` is bad news, because either we don't send the `null` value to Front50, or Front50 strips out the `null` field, so it's never persisted. But it does change the structure of the pipeline whenever the trigger config loads, so the pipeline will always show the "Save Changes" button.

fix(docker): make tag optional, do not set to null if undefined

---

app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicy.html
app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.html
app/scripts/modules/google/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.ts
app/scripts/modules/google/serverGroup/configure/wizard/serverGroupWizard.html

- un-camelcases Autohealer (when the word is rendered in the UI).
- fixes bug where the "Autohealer" section was marked incomplete in the server group create dialogue.
@jtk54 or @duftler

fix(gce): autohealer config in server group dialogue

---

app/scripts/modules/core/presentation/navigation/pageNavigator.component.ts

Kind of a silly edge case, but: using `ng-if`, combined with a stateful service (page navigator) to register and reset pages means that, when moving from a stage back to the Configuration (i.e. `<triggers>`), the `<triggers>` content sets up its page navigator, then the `<pipeline-config-stage>` destroys its navigator and unregisters the scroll handler, which keeps the page navigator (since there's only ever one) from sticking.
The cleanest workaround is to just make the event namespace unique, so order is not important when binding/unbinding the navigators.
@jrsquared PTAL

fix(pipelines): prevent page navigator from unsticking in config

---

app/scripts/modules/core/pipeline/config/stages/stage.module.js

We currently only re-render the stage configuration if the index changes or the type changes. However, if you have two stages of the same type, and remove the second one, the UI won't update, because neither of those fields will change.
@jrsquared PTAL - this is what we were discussing earlier this morning.

fix(pipelines): force stage config rerender on refId change

---

app/scripts/modules/netflix/pagerDuty/pagerDuty.read.service.ts
app/scripts/modules/netflix/pagerDuty/pagerDutySelectField.component.ts

Now there's a v2 integration from PagerDuty, which is the default, and we are not going to deal with that right now, so this updates the help text on the field to explain to users that they should select the v1 integration.
A couple of other improvements:
1. The response to get the list of services from gate comes back in less than 100ms, so we don't need to cache it, since caching it means users need to refresh the entire page to get new services.
2. Auto-refreshing the list every ten seconds, so they don't need to close the modal to get the latest list of services if they just recently added one.

fix(netflix): clarify help text when setting up PagerDuty integration

---

app/scripts/modules/core/modal/modals.less

Not sure when this regression happened, but i just started noticing it a week or two ago:
Current:
PR:
Also making the text editable in the selections.

fix(core): fix CSS regressions on multiselect

---

app/scripts/modules/core/cluster/clusterPod.html
app/scripts/modules/core/delivery/executionGroup/executionGroup.component.html
app/scripts/modules/core/diffs/changes.html
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancer.html
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancerPod.html
app/scripts/modules/core/loadBalancer/loadBalancer/loadBalancerServerGroup.html
app/scripts/modules/core/modal/wizard/v2wizardPage.component.html
app/scripts/modules/core/presentation/navigation/pageNavigation.less
app/scripts/modules/core/presentation/navigation/pageSection.component.ts
app/scripts/modules/core/securityGroup/securityGroup.html
app/scripts/modules/core/securityGroup/securityGroupPod.html
app/scripts/modules/core/serverGroup/serverGroup.component.html
app/scripts/modules/core/utils/stickyHeader/stickyHeader.component.ts
app/scripts/modules/core/utils/utils.module.js
app/scripts/modules/netflix/ci/detail/detailTab/detailTabView.html

React world doesn't have an analog to attribute directives. Convert sticky-header to a component so we can start to use `sticky-header` in react components.
Eventually we will convert this to a React component, but this is a logical first step.

refactor(core): convert sticky-header to a component

---

app/scripts/modules/core/account/accountSelectField.directive.html
app/scripts/modules/core/account/accountSelectField.directive.js
app/scripts/modules/core/region/regionSelectField.directive.html
app/scripts/modules/core/region/regionSelectField.directive.spec.js

If the default value isn't found in the list of options, [angularjs sets it](http://stackoverflow.com/questions/12654631/why-does-angularjs-include-an-empty-option-in-select) to '?'. Since '?' _technically_ isn't an empty string, the field is incorrectly listed as valid.
I also added the 'Select...' placeholder to be displayed when the value is empty

fix(core): Fix default on account/region select field

---

app/scripts/modules/amazon/serverGroup/details/advancedSettings/editAsgAdvancedSettings.modal.html
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.aws.controller.js
app/scripts/modules/amazon/serverGroup/details/serverGroupDetails.html
app/scripts/modules/netflix/serverGroup/awsServerGroupDetails.html

The `enabledMetrics` field on an ASG is a list of objects, so we need to transform it to render properly in the UI.
Also fixing the option selector when editing an existing ASG.
Should fix https://github.com/spinnaker/spinnaker/issues/1575

fix(aws): render enabled ASG metrics in details panel

---

app/scripts/modules/core/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/delivery/service/execution.service.spec.js
app/scripts/modules/core/delivery/service/execution.service.ts

ExecutionEngine 'v2' is now default, so the force checkbox should be displayed by default.
This commit also change the cancel pipeline endpoint, the previous one is [deprecated](https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy#L93).

fix(force cancel pipeline): Display force checkbox by default

---

app/scripts/modules/core/delivery/filter/executionFilter.model.ts
app/scripts/modules/core/delivery/filter/executionFilter.service.ts

This is a short-term workaround to not using redux for our data stores.
I considered making this more like the `application.onRefresh` method, where you pass in a method and we handle the subscription internally, but, since we do the actual group updating outside the model, and, again, this is a short-term thing, let's just go with it, eh.

feat(pipelines): provide observable to surface execution group updates

---

app/scripts/modules/amazon/instance/awsInstanceType.service.js

Updating `r3 -> r4` family has been postponed into May. When r4 comes around, I'll replace the `SSD Storage` column with the default root EBS volume size, as no instance family will be using instance storage.
@spinnaker/netflix-reviewers PTAL

feat(aws): Updating instance types to default new families

---

app/scripts/modules/amazon/serverGroup/details/rollback/rollbackServerGroup.html

Pin `min` capacity to `desired`  capacity when rolling back

---

app/scripts/modules/core/config/settings.ts
app/scripts/modules/core/core.module.js
app/scripts/modules/core/delivery/executionGroup/execution/execution.less
app/scripts/modules/core/delivery/triggers/NextRunTag.tsx
app/scripts/modules/core/pipeline/config/stages/executionWindows/ExecutionWindowActions.tsx
app/scripts/modules/core/pipeline/config/stages/executionWindows/atlasGraph.component.ts
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowActions.component.ts
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/executionWindows/executionWindowsDetails.html
app/scripts/modules/core/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
app/scripts/modules/core/pipeline/config/stages/wait/SkipWait.tsx
app/scripts/modules/core/pipeline/config/stages/wait/skipWait.component.ts
app/scripts/modules/core/pipeline/config/stages/wait/waitExecutionDetails.controller.js
app/scripts/modules/core/pipeline/config/stages/wait/waitExecutionDetails.html
app/scripts/modules/core/utils/SystemTimezone.tsx
app/scripts/modules/core/utils/timeFormatters.ts

Nothing exciting here, just moving logic out of execution details and into React.
One thing that's not clear to me is when to put things on the `state` and when to make things private methods/fields on the component class. Would appreciate feedback on that...

refactor(pipelines): convert wait/execution window actions to React

---

app/scripts/modules/core/delivery/executionGroup/ExecutionGroup.tsx
app/scripts/modules/core/delivery/executionGroup/executionGroup.less
app/scripts/modules/core/domain/IPipeline.ts
app/scripts/modules/core/pipeline/config/services/pipelineConfig.service.ts

If there's a strategy in an application, we currently fail to render any executions because the `<NextRunTag>` looks at the `pipelineConfig`, which is null. Since we will never need that tag (or the `<TriggersTag>`) on a strategy, the easiest course of action is to simply not render them.
One thing I've noticed in this case is React does not do so great when it hits an exception. In an application where the last execution is a strategy, no execution groups render right now - you have the side filters and a blank middle section of the page.

fix(pipelines): avoid NPE rendering execution groups

---

app/scripts/modules/netflix/pipeline/stage/properties/create/property.component.html
app/scripts/modules/netflix/pipeline/stage/properties/create/property.component.js

The current code does this kinda wonky thing where it debounces the options selector, which occurs out of band of the Angular digest cycle, so the filtered list will only appear when the next digest cycle wraps up - which, in the case of the pipeline config screen, can be up to 30 seconds.
The slightly better way to handle this is to use the `refresh` attribute and set the list of properties on the component controller itself.
Even if there are thousands of properties for a given app, the performance probably isn't _that_ much different without the debouncing. This way, at least, the performance is good for apps that only have a few or a few hundred, and not inexplicably bad.

perf(netflix): improve fast property selector performance

---

app/scripts/modules/core/pipeline/config/stages/core/ExecutionBarLabel.tsx
app/scripts/modules/netflix/pipeline/stage/canary/CanaryExecutionLabel.tsx

Two small changes:
1. Use the custom label if supplied for the stage tooltip
2. Fix the canary score (netflix module only) in the canary label

fix(pipelines): show custom label as tooltip, fix canary score

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobExecutionDetails.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

Support resolving Run Job container tags from triggers. There are a
couple of things that can be improved here but this is basic
implementation. One thing to think about is what happens if there are 2
docker triggers and the pipeline is triggered by one that isn't used for
this job. What happens?
Changes include:
* Checkbox for selecting if you want to resolve from trigger
* If the box is checked, a list of Docker triggers is presented
* The Run Job Execution Details will not print the tag is it's from a
trigger
Fixes [#1566](https://github.com/spinnaker/spinnaker/issues/1566)

feat(kubernetes): Allow Run Job trigger tag

---

app/scripts/modules/netflix/ci/services/ciBuild.read.service.spec.ts
app/scripts/modules/netflix/ci/services/scm.read.service.ts
app/scripts/modules/netflix/ci/trigger/ci.trigger.handler.component.ts

* add test suite for scm reader service
* rename reader to be consistent with rest of deck.

chore(netflix/ci): add  scm reader test suite

---

app/scripts/modules/core/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/pipeline/config/services/pipelineConfig.service.ts

This whole controller is due for a rewrite, just not today.
We're currently persisting some values to local storage we absolutely shouldn't be, because the `viewState` object holds transient values, like the JSON of the pipeline config, the saving state, whether the pipeline config has history or not. We should only persist two values to local storage: the section, and the stage index.
The view can get into a state right now where, when doing something like editing the JSON of the pipeline, the save button goes into "saving..." mode, even though nothing is being saved.
Bumping the `version` field on the cache will clear out any existing cached values.

fix(pipelineconfig): only cache stage/section state

---

app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.ts

It's sometimes desirable to send no payload in a webhook stage. The current implementation does not allow this, however, and will refuse to update the `payload` field if left blank once something has been added.
Also, the use of `extend` means that properties cannot be removed from the payload field once they've been added, e.g. if I enter `{"a":1, "b":2}` in the textarea, then remove `"b":2`, the contents of the field still ends up as `{"a":1, "b":2}`. I can't think of a reason why we'd want to merge properties from the textarea into the `payload` field rather than replace it.
@amanya PTAL

fix(webhooks): allow empty payload in webhook stage

---

app/scripts/modules/titus/serverGroup/configure/serverGroupBasicSettingsDirective.html
app/scripts/modules/titus/serverGroup/configure/serverGroupBasicSettingsSelector.directive.js

We recently allowed a `~` character in the detail section of a server group name ( Netflix/frigga#20 )
I feel like there is a solid chance that there is somewhere else that cares about tilde but in doing some initial testing I didn't find it...

allow ~ in titus server group detail

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/feedback/Feedback.tsx

According to React Bootstrap docs, `<MenuItem>` is going to set an `href` on the anchor, even if you omit it, and it's going to navigate to it before calling the `onClick` or `onSelect` handlers. The solution, it seems, is to just not use `<MenuItem>` for non-links.
@jrsquared FYI - you probably never noticed it (I didn't) because, when testing, you were already at the root of the application, i.e. `http://localhost:9000/#`, so the navigation didn't do anything.

fix(netflix): do not navigate to root on jira click

---

app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js

The objective here is to be able to deploy baked docker containers to Kubernetes, so we don't have to rely on using the docker registry trigger, and we get to keep the traceability. 
I haven't synced with anyone on this approach, so I expect to have to alter worthing and/or some of the flow for this. So feel free to make suggestions for change. 
This PR depends on a change to orca: https://github.com/spinnaker/orca/pull/1299

feat(provider/kubernetes): Deploy baked docker images

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/core/pipeline/config/stages/webhook/modal/addCustomHeader.controller.modal.ts
app/scripts/modules/core/pipeline/config/stages/webhook/modal/addCustomHeader.html
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.html
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.module.ts
app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.ts

This will add support for customizing request headers that will be sent to the service called by the webhook stage.
Depends on https://github.com/spinnaker/orca/pull/1301
@anotherchrisberry @jervi PTAL

feat(webhooks): allow custom headers on webhook call

---

app/scripts/modules/core/entityTag/entityTags.read.service.spec.ts
app/scripts/modules/core/entityTag/entityTags.read.service.ts

We get error reports several times a week about entity tags failing to load. @jrsquared traced the cause to when a user closes their laptop in the middle of an application refresh cycle, then later reopens after their VPN connection has been broken.
The error reports are just noise at this point, so we should remove the exception handling.

refactor(entitytags): do not throw exception on entity tag load failure

---

app/scripts/modules/core/api/api.service.ts

Ran into an issue when saving pipelines where I would submit a request
to save and the response coming back had a Content-Type of text/plain
which would cause the request to "fail" regardless of if it actually
succeeded or not. Adds a check to allow zero length text plain headers
as well.
@danielpeach - I wasn't able to repro this locally. The only diff between my environment and my deployment is Auth is enabled. I pointed Front50 at the _same_ bucket and didn't get the `Content-Type: text/plain` response header. I'll keep trying though.
@anotherchrisberry - Daniel suggested that I tag you on this since this could affect local caches.

fix(deck): Add check for isZeroLengthText response

---

app/scripts/modules/core/pipeline/config/stages/webhook/webhookStage.ts

"statusUrlResolution" is not set to default in the "webhook" stage though it is enabled in the UI.
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely …

fix(webhook): Fix NPE as "statusUrlResolution" is not set by default

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js

We already have similar code in the server group modal, where we are using the same infinite scroll item limiting business.

fix(amazon): preserve existing security groups on ELB edit

---

app/scripts/modules/core/pipeline/config/triggers/cron/cronPicker.html
app/scripts/modules/core/pipeline/config/triggers/cron/cronTrigger.html

This was kind of a fun (?) one. If there are multiple cron triggers on the page with the same frequency options, only one is selectable, since the fields all have the same name.
Adding `name` to the `cronGen` component options makes it available in the template, and it's a UUID, so this fixes that problem...

fix(crontrigger): fix radio buttons when multiple cron triggers exist

---

app/scripts/modules/core/loadBalancer/filter/loadBalancer.filter.service.js
app/scripts/modules/core/serverGroup/serverGroup.dataSource.js
app/scripts/modules/core/utils/json/json.utility.service.ts

Did this ever work as expected? Maybe? Server groups probably worked until recently; load balancers, nope.
We use `stringVal` as a means to determine whether to replace elements and force a re-render via Angular's change detection. This works pretty well, unless we nest that value in itself on every refresh (load balancers), or we add entity tags, which are non-deterministically added to the server group, depending on whether the call to fetch cluster tags or the call to fetch server group tags comes back first (`stringify` serializes properties in the order in which they're added to an object).
So, we'll just alphabetize those strings when we generate them.

fix(clusters/loadBalancers): fix false positive change detections

---

app/scripts/modules/core/application/config/applicationConfig.view.html

Enabling Chaos Monkey creates an inconsistency in the actual order of items and their order on the navigation panel.

fix(config): update config so the navigation menu matches actual section order

---

app/scripts/modules/core/delivery/executionBuild/ExecutionBuildNumber.tsx

Previous code used a `ui-sref` in the template, which is relative to the execution state.

fix(executions): fix navigation to parent pipeline from standalone view

---

app/scripts/modules/amazon/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/pipeline/stages/bake/bakeStage.html
app/scripts/modules/azure/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/azure/pipeline/stages/bake/bakeStage.html
app/scripts/modules/core/pipeline/config/stages/bake/bakeStageChooseOs.component.html
app/scripts/modules/core/pipeline/config/stages/bake/bakeStageChooseOs.component.ts
app/scripts/modules/core/pipeline/config/stages/stage.module.js
app/scripts/modules/docker/pipeline/stages/bake/bakeStage.html
app/scripts/modules/docker/pipeline/stages/bake/dockerBakeStage.js
app/scripts/modules/google/pipeline/stages/bake/bakeStage.html
app/scripts/modules/google/pipeline/stages/bake/gceBakeStage.js
app/scripts/modules/openstack/pipeline/stages/bake/bakeStage.html
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

This consolidates some of the copy/pasted code around the choice of the base os in the bake stage.
Created a component and used a dropdown instead of radio buttons.
Dropdown looks better in my opinion and is more scalable in case of many possible base OS.
Screenshot of old version:
Screenshot of proposed version:
Another screenshot of new version:

refactor(bake/core): Replace bake stage choose base OS radio buttons for dropdown

---

app/scripts/modules/core/delivery/details/executionDetails.controller.js
app/scripts/modules/core/delivery/details/executionDetails.html
app/scripts/modules/core/delivery/executionGroup/ExecutionGroup.tsx

A couple of performance fixes:
* depend on `stringVal` of the execution to determine if it's changed - not the running time + id
* only set details/summary source URLs when the state changes

fix(pipelines): prevent re-render of running executions every second

---

app/scripts/modules/core/delivery/executionGroup/ExecutionGroups.tsx
app/scripts/modules/core/utils/stickyHeader/Sticky.tsx
app/scripts/modules/core/utils/stickyHeader/StickyContainer.tsx

Since the sticky component listened for the `<StickyContainer>` component to mount to get the subscription, if you set filters and then cleared them, the new `<Sticky>` components would not have listeners attached.

fix(core): Fix sticky-headers in react

---

app/scripts/modules/amazon/serverGroup/details/securityGroup/editSecurityGroups.modal.controller.js
app/scripts/modules/amazon/serverGroup/details/securityGroup/editSecurityGroups.modal.html

Surprise, `debounce` doesn't work with ui-select, so it ends up not pushing new changes to the model once a user starts typing to filter the list of security groups.
(We have very similar code in the create/clone modal, just didn't update it here)

fix(aws): remove debounce from ui-select, use inf-scroll

---

app/scripts/modules/titus/pipeline/stages/bake/titusBakeStage.js

- This ensures to url decode the parameters on the repo url

fix(titus): URL decode params to allow expressions in Bake package name

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/core/projects/project.less

This change allows independent column scrolling in the application views, and scrolling generally in the project dashboard view.
Apologies for the regression - we generally only use Chrome, but are happy to try to support other browsers as folks point things out!

fix(firefox): fix page scrolling in Firefox

---

app/scripts/modules/netflix/pipeline/stage/chap/chapExecutionDetails.controller.js
app/scripts/modules/netflix/pipeline/stage/chap/chapExecutionDetails.html

ChAP can have multiple canary reports.  This update renders a list of canary report links.  If there are more than one, the report key is shown in parentheses

fix(ChAP): Fix canary report link for ChAP

---

app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.js
app/scripts/modules/amazon/loadBalancer/configure/createLoadBalancer.controller.spec.js

Dreaming of a day when we replace the ui-select with a nice, performant component that handles large datasets.

fix(aws): prepend default security groups when creating ELBs

---

app/scripts/modules/core/cluster/allClusters.controller.js
app/scripts/modules/core/serverGroup/serverGroup.states.ts

@anotherchrisberry @jrsquared PTAL

fix(core/cluster): Use `redirectTo` hook to switch to pipelines when server groups are disabled

---

app/scripts/modules/core/navigation/state.provider.ts

This was wreaking havoc on inverse-boolean params.

fix(routing): do not add array field to params if not specified

---

app/scripts/modules/oracle/cache/cacheConfigurer.service.js
app/scripts/modules/oracle/image/image.reader.js
app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/oraclebmcs.settings.ts

This change adds some initial scaffolding for the Oracle BMCS provider. 
I chose the image and cache modules to merge first since they're fairly small.

feat(provider/oraclebmcs): Add initial scaffolding for Oracle BMCS

---

app/scripts/modules/core/delivery/filter/executionFilter.controller.js
app/scripts/modules/core/delivery/filter/filterNav.html

I honestly don't know how this has ever worked. We're using a different field for the `ng-model` and the `ng-repeat`.
The important (?) thing is this makes more sense and works, allowing predictable reordering of pipeline configs, including the last item in the list.

fix(pipelines): fix reordering of pipeline/strategy configs

---

app/scripts/modules/core/utils/timeFormatters.ts
app/scripts/modules/netflix/fastProperties/domain/property.domain.ts
app/scripts/modules/netflix/fastProperties/fastProperties.help.ts
app/scripts/modules/netflix/fastProperties/fastProperties.module.ts
app/scripts/modules/netflix/fastProperties/view/details/fastPropertyDetails.controller.ts
app/scripts/modules/netflix/fastProperties/view/details/fastPropertyDetails.html
app/scripts/modules/netflix/fastProperties/wizard/propertyDetails/propertyDetails.component.html
app/scripts/modules/netflix/netflix.module.ts
app/scripts/modules/netflix/pipeline/stage/properties/create/persistedPropertyList.component.html
app/scripts/modules/netflix/pipeline/stage/properties/create/persistedPropertyList.component.js
app/scripts/modules/netflix/pipeline/stage/properties/create/property.component.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

Wishing I'd put this into the 5k line PR yesterday to hide how ugly it is, but this allows users to enter a TTL when creating a fast property, and also lets them edit the scope once it's been selected without having to go into the JSON editor view.

feat(netflix): add TTL to properties, scope editor on stage

---

app/scripts/modules/netflix/fastProperties/fastProperties.less
app/scripts/modules/netflix/fastProperties/fastProperties.states.ts
app/scripts/modules/netflix/fastProperties/fastProperty.read.service.ts
app/scripts/modules/netflix/fastProperties/view/ApplicationProperties.tsx
app/scripts/modules/netflix/fastProperties/view/FastPropertiesList.tsx
app/scripts/modules/netflix/fastProperties/view/rollouts/FastPropertyRollouts.less
app/scripts/modules/netflix/fastProperties/view/rollouts/FastPropertyRollouts.tsx
app/scripts/modules/netflix/fastProperties/wizard/cloneFastPropertyToNewScopeWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/createFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/deleteFastPropertyWizard.controller.ts
app/scripts/modules/netflix/fastProperties/wizard/updateFastPropertyWizard.controller.ts

Removing the sticky headers approach for application fast properties/rollouts, favoring a tab-based view (no Jeremy this week so I'm going off the beaten path with the UX).
Also fixing routing when waiting for a pipeline to appear, ensuring we actually have the property context before doing the routing.
The controllers for create/delete/update/clone are incredibly similar and will be refactored at some point to a shared base class - but not tonight.

feat(netflix): move app fast properties to tabs

---

app/scripts/modules/core/core.module.js
app/scripts/modules/core/interceptor/debug.interceptor.ts
app/scripts/modules/core/interceptor/interceptor.module.ts
app/scripts/modules/core/navigation/state.provider.ts

@anotherchrisberry or @jrsquared please review.
Dumps a mutating request body to the console if `debug=true` is present as a query parameter (in the browser, not in the outgoing request).
I bet no one is going to discover this, so it would be nice in the future to have a better way to turn this mode on / consume the output.

feat(core): mutating request debug mode

---

app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScope.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeReadOnly.component.ts
app/scripts/modules/netflix/fastProperties/wizard/propertyScope/propertyScopeUpdatable.component.ts
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.module.js
app/scripts/modules/netflix/pipeline/stage/properties/index.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/bulkQuickPatchStage/bulkQuickPatchStage.module.js
app/scripts/modules/netflix/pipeline/stage/quickPatchAsg/quickPatchAsgStage.module.js

these don't need to be included, as they're not used in the modules themselves (or are included within the child modules themselves)

chore(netflix): remove unnecessary dependency injections

---

app/scripts/modules/core/core.module.js

Allow `ssh://` links, useful for one-click SSH access to servers from Spinnaker.

Allow `ssh:` links

---

app/scripts/app.ts
app/scripts/modules/core/core.module.js

react module is probably better in core, auth service doesn't need to be in app (it's loaded as part of auth module in core)

refactor(core): move react module to core

---

app/index.deck
app/scripts/modules/core/cluster/all.html
app/scripts/modules/core/cluster/allClusters.controller.js
app/scripts/modules/core/cluster/cluster.service.ts
app/scripts/modules/core/pageTitle/pageTitle.service.spec.js
app/scripts/modules/core/pageTitle/pageTitle.service.ts
app/scripts/modules/core/serverGroup/serverGroup.states.ts
app/scripts/modules/core/task/tasks.controller.js

Three tweaks here (in separate commits):
1. Deep links to tasks were broken after the ui-router upgrade, since the workaround that was in place is no longer needed.
2. Fixed rendering for on-demand clusters. Because the `resolve` in the clusters state was relying on the application to be ready, the transition we were firing off via the `applyParamsToUrl` was getting rejected and nothing was being shown on the page.
3. Tweaked the page title service. Since the `onStart` event is delayed a bit, for very large applications, the users sees the browser URL while the routing starts up, and doesn't see the spinner for a second or two, which gives the impression that something is broken or frozen.
@christopherthielen or @jrsquared PTAL

Filter fixes

---

gradle/buildViaTravis.sh
gradle/installViaTravis.sh

This PR modifies travis config to skip the gradle build
The change only takes effect when processing a travis pull request.  When a branch is merged into master, the normal gradle build is run to create artifacts.

chore(travis): Do not perform gradle build for travis pull requests

---

app/scripts/modules/core/navigation/state.provider.ts

Since we use commas as our separators in the query param, we have to actually encode/decode them by hand.

fix(executions): allow filtering on pipelines with commas in name

---

app/scripts/modules/amazon/serverGroup/configure/wizard/capacity/capacitySelector.directive.html
app/scripts/modules/netflix/pipeline/stage/canary/canaryStage.js

It never makes sense to use source capacity on canaries, since they will try to look up capacity on a cluster that should not exist.

fix(netflix): do not allow users to specify useSourceCapacity for canaries

---

app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearch.component.ts

We were incorrectly calculating stack values by checking clusters (multiple clusters can exist in a stack).

fix(netflix): dedupe stacks in fast prop scope picker

---

app/scripts/modules/core/help/helpContents.js
app/scripts/modules/google/applicationProviderFields/gceFields.html
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/serverGroup/configure/serverGroupCommandBuilder.service.js
halconfig/settings.js
settings.js

Closes https://github.com/spinnaker/spinnaker/issues/1638.
This is an application-level setting, not an account setting. The default for new applications can be set in `settings.js`.

feat(gce): makes `associate public ip` an application setting

---

app/scripts/modules/core/presentation/main.less
app/scripts/modules/netflix/fastProperties/scope/fastPropertyScopeSearchCategory.service.ts
app/scripts/modules/netflix/fastProperties/view/ApplicationProperties.tsx

* make sure animations are actually included _somewhere_ on the page
* fix fast property scope initialization
* remove tooltip on smaller screen - there's already tons of space in the header, no need to hide the label

fix(core): restore spinning animation

---

app/scripts/modules/core/config/settings.ts
app/scripts/modules/core/whatsNew/whatsNew.read.service.spec.ts
app/scripts/modules/core/whatsNew/whatsNew.read.service.ts

Removing the dependency on the netflix mode from the core module.
We'll update our internal settings files to match the new structure when we release this at Netflix.

chore(core): consolidate whats new settings to core

---

app/scripts/modules/core/pipeline/config/stages/deploy/deployStage.js

`deploy` stages are coming in as `createServerGroup` in v3 executions

fix(executions): add alias to deploy for v3 executions

---

app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.html
app/scripts/modules/core/src/domain/IStageOrTriggerTypeConfig.ts
app/scripts/modules/core/src/domain/ITriggerTypeConfig.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.spec.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts
app/scripts/modules/core/src/pipeline/config/stages/bake/bakeExecutionHandler.html
app/scripts/modules/core/src/pipeline/config/stages/bake/bakeStage.js
app/scripts/modules/core/src/pipeline/config/triggers/jenkins/jenkinsTriggerOptions.directive.html
app/scripts/modules/netflix/pipeline/stage/properties/create/property.component.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyExecutionHandler.html
app/scripts/modules/netflix/pipeline/stage/properties/create/propertyStage.js

Just templates, they're just templates.
But they can prevent form submission by marking fields as `required`.
Also preventing a manual execution with a Jenkins trigger if no build has been selected.
I believe this is the last bit of netflix-specific code in core...

refactor(core): make stage execution handling pluggable

---

app/scripts/modules/core/src/history/recentHistory.service.spec.ts
app/scripts/modules/core/src/history/recentHistory.service.ts

Fixes a minor regression with the ui-router 1 upgrade.
ui-router now includes all parameters, including absent (i.e. undefined) ones, in the state change event parameters. angular-cache will not store undefined keys, so when we get them out of the cache, they're just not there, and the `find` call from lodash doesn't match, since it does consider those `undefined` values.
The simple solution is to omit the undefined keys.

fix(history): ignore undefined params when replacing history entry

---

app/scripts/modules/core/src/presentation/main.less

Let's say this is because we think the animation is hokey and doesn't add anything to the user experience, not that I can't figure out why switching to the clusters view from tasks or pipelines causes the filters to start in a collapsed state, then expand.

feat(filters): remove sliding width animation on filter panels

---

app/scripts/modules/amazon/aws.module.js
app/scripts/modules/amazon/help/amazon.help.ts
app/scripts/modules/azure/azure.module.js
app/scripts/modules/azure/help/azure.help.ts
app/scripts/modules/cloudfoundry/serverGroup/configure/serverGroupArtifactSettingsDirective.html
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/google/gce.module.js
app/scripts/modules/google/help/gce.help.ts
app/scripts/modules/kubernetes/help/kubernetes.help.ts
app/scripts/modules/kubernetes/kubernetes.module.js
app/scripts/modules/netflix/help/netflixHelpContents.registry.ts
app/scripts/modules/openstack/help/openstack.help.ts
app/scripts/modules/openstack/openstack.module.js
app/scripts/modules/titus/help/titus.help.ts
app/scripts/modules/titus/titus.module.js

Should have done this a while ago. The main help file is unwieldy and contains help for disparate modules.
This splits it into a distinct file for each cloud provider.

refactor(help): split help into provider modules

---

app/scripts/modules/amazon/src/securityGroup/configure/ingressRuleGroupSelector.component.ts

Kind of important to initialize the component.

fix(aws): restore $onInit to ingress security group selector

---

app/scripts/modules/core/src/core.module.js
app/scripts/modules/core/src/healthCounts/HealthCounts.tsx
app/scripts/modules/core/src/modal/modals.less
app/scripts/modules/core/src/pipeline/config/templates/Variable.tsx
app/scripts/modules/core/src/pipeline/config/templates/VariableError.tsx
app/scripts/modules/core/src/pipeline/config/templates/VariableMetadataHelpField.tsx
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/tsconfig.json
app/scripts/modules/core/webpack.config.js

* exporting interfaces on React components
* tweaking select2 CSS loading to ensure order (also removes gradient from the selects to make them more consistent with the rest of the application)
* disabling sourcemap generation, since it fails on library builds and is going to take a lot of work to fix

refactor(core): flatten select2, misc lib build fixes

---

app/scripts/modules/core/src/utils/waypoints/waypoint.directive.js
app/scripts/modules/core/src/utils/waypoints/waypoint.service.ts

`waypointContainer` and `waypoint` directives both declare the same module, clobbering each other, so only one directive is actually available.
If you're wondering how this was working for the past two years, it's because the `waypointContainer` directive was loaded _after_ `waypoint`. A recent refactor (it doesn't matter which one, or who did it, or whether they tested this particular feature) switched that load order, so `waypointContainer` essentially disappeared.
All `waypoint` does is remove its jQuery data, which may not even be necessary, but let's leave it in place.

fix(core): assign unique namespaces to waypoint* directives

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

When I put this in at first, I didn't account for all scenarios. It
works for triggers that are always enabled. To support "one click
deployment" scenarios where you trigger a manual execution, then select
an image you wouldn't see the trigger show up in the list of available
triggers. By removing the check, you can select any trigger you define
and use that. If that trigger is used automatically or manually is
outside the scope of this feature.
ping @danielpeach

fix(kubernetes/runJob): Remove check for enabled on Run Job trigger option

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts

@anotherchrisberry it turns out this really is necessary.
@lwander fyi

fix(core): prevents incorrectly defaulting to AWS for stage configs

---

webpack.common.js

Not sure the backstory here, but it appears we are currently running es-lint twice. The HappyPack JS config already includes the `eslint-loader`, so with the `pre` rule we end up running it two times - but the first is never cached, so we're always re-running it.
Locally, I see a 15-20 second improvement in cold start (no cache), and 20-25 second improvement with a warmed cache.
I also played around with `cache-loader`, which seems even better after the initial run (~35 seconds faster); however, cold starts were ~20 seconds _slower_ than the current build, so I'm not as excited there. Still something to consider/play around with.

refactor(build): avoid linting twice

---

app/scripts/modules/core/src/delivery/delivery.states.ts

Fixes a regression from the ui-router upgrade which is preventing the removal of the `refId` param from deep links to a specific stage, which then prevents navigation to other stages, as it keeps seeing the `refId` parameter and replacing the `stage` param to point back to whatever it's resolved via the `refId` param.

fix(pipelines): remove refId param after resolving deep link

---

app/scripts/modules/core/src/application/service/application.read.service.ts

Nothing exciting, just creates the application with whatever name is actually stored in Front50, instead of whatever the user has typed into the URL. Prevents tasks from disappearing when users manually enter a URL such as `spinnaker/applications/DECK` (front50 will return an application named "deck").

fix(applications): use front50 application name instead of state param

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/oracle/securityGroup/configure/createSecurityGroup.controller.js
app/scripts/modules/oracle/securityGroup/configure/createSecurityGroup.html
app/scripts/modules/oracle/securityGroup/securityGroup.reader.js
app/scripts/modules/oracle/securityGroup/securityGroup.transformer.js

Adds security groups for Oracle Bare Metal Cloud provider.
We decided against allowing the creation of security groups through the UI due to some complexity in how they are implemented in Bare Metal.

feat(provider/oraclebmcs): Implement security groups for Oracle BMCS

---

app/scripts/modules/core/src/application/applicationModel.builder.ts

Current behavior is pretty bad, as the URL bounces back and forth between `/applications/{app}` and `/applications/{app}/clusters` indefinitely, and does not show the error message that the application can't be found.

fix(application): avoid URL flashing when application not found

---

app/scripts/modules/core/src/application/application.less

thanks for pointing this out @jrsquared

fix(application): avoid refresh icon wobble on narrow screens

---

app/scripts/modules/core/src/domain/IStage.ts
app/scripts/modules/core/src/domain/IStageTypeConfig.ts
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts

This PR adds support for webhook stages that are configured in the Orca and appears more or less as native stages in Deck.
Corresponds with https://github.com/spinnaker/orca/pull/1329 and https://github.com/spinnaker/gate/pull/389

feat(webhooks): Add preconfigurable webhook support

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/analytics/analytics.service.js
app/scripts/modules/core/webpack.config.js

* package collision on analytics (module and service were using the same package name and clobbering each other)
* moving `version.json` to an external so it can be built in the library consumer
* bumping core version

fix(core): unique package for analytics service; external version.json

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/delivery/details/singleExecutionDetails.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.spec.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.html

Someday, the pipeline configurer will go away (it's an artifact of the days when we displayed all application pipeline configs in the same view), but not today.

fix(pipelines): inject app, set on scope in pipeline configurer

---

app/scripts/modules/oracle/oraclebmcs.module.js
app/scripts/modules/oracle/pipeline/disableAsg/disableAsgStage.html
app/scripts/modules/oracle/pipeline/disableAsg/disableAsgStage.js
app/scripts/modules/oracle/pipeline/disableAsg/disableAsgStepLabel.html
app/scripts/modules/oracle/pipeline/stages/findAmi/findAmiExecutionDetails.html
app/scripts/modules/oracle/pipeline/stages/findAmi/findAmiStage.html
app/scripts/modules/oracle/pipeline/stages/findAmi/findAmiStage.js

Adds another pipeline stage for the Oracle BMCS cloud provider.

feat(provider/oraclebmcs): Implement findAmi pipeline stage

---

app/scripts/modules/core/src/entityTag/entityTags.read.service.spec.ts
app/scripts/modules/core/src/entityTag/entityTags.read.service.ts

The clouddriver endpoint defaults the `maxResults` parameter to `100` when retrieving entity tags. This is fine, except when we are passing a list of more than 100 entities, we'll only get the first 100 results.
Since we dedupe the list of tags before sending the request, we can't just count on the number of `entityId`s we send in - we need to actually declare how many we might get back.

fix(entitytags): include maxResults parameter when retrieving tags

---

app/scripts/modules/core/src/application/application.component.ts
app/scripts/modules/core/src/application/application.model.ts

If the app is not found, there will be no `dataLoader` from which to unsubscribe, so don't call `disableAutoRefresh` when moving to a different application.
In case someone calls `disableAutoRefresh` anyway (they never should, but who knows), we'll verify the `dataLoader` has been assigned before calling `unsubscribe` on it.

fix(core): avoid NPE when disabling autorefresh

---

app/scripts/modules/core/src/domain/IStageTypeConfig.ts
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts

Running into an issue with the `alias` being applied to the pipeline stage config: Orca will interpret that as the stage type to run, which causes problems, especially as the original intent of the field was to allow backwards compatibility when refactoring stages. None of this is documented - the stage config options are very cryptic and need extensive comments to explain them (I barely understand what they do).
Will submit a separate PR to add comments to the config interface once I figure out what the fields mean.

fix(pipelines): allow stage to declare executionAlias value

---

app/scripts/modules/core/src/application/application.component.ts
app/scripts/modules/core/src/application/application.less
app/scripts/modules/core/src/application/nav/applicationNav.component.less
app/scripts/modules/core/src/presentation/main.less

Currently, when an application's name is very long, the UI does terrible things:
Three options here:
1. Let the header overflow by removing the `height: 80px` style: <img width="1328" alt="screen shot 2017-05-26 at 11 21 01 am" src="https://cloud.githubusercontent.com/assets/73450/26507584/e60dd0e2-4205-11e7-9620-9f15ac679fd4.png">
2. Cut off the text after some number of characters to make it fit: <img width="1370" alt="screen shot 2017-05-26 at 11 22 59 am" src="https://cloud.githubusercontent.com/assets/73450/26507599/f845fd3e-4205-11e7-8d53-ff563f6869c3.png">
3. Shrink the header after a number of characters, and treat it the same way we treat narrower windows:
This PR implements (3). I think (2) is a bad option - you end up cutting an awful lot of the application name to make it fit …

fix(applications): shrink header for long application names

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/application/service/application.write.service.ts

`accounts` gets set by the directive that renders the attributes on the config screen, but it sets it as an array, which is no good, since we're no longer re-assembling that into a comma-delimited string.
Separate PR forthcoming in Gate to clean up account merging...

fix(core): remove application accounts before saving

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/serverGroup/serverGroup.dataSource.js

Having put in a nice fix yesterday to the entity tag reader to fetch the correct number of tags, I failed to account for an upstream optimization that reduced the number of tags the entity tag reader would consider, which is...not good.

fix(entityTags): do not pre-optimize tag retrieval in data source

---

app/scripts/modules/core/src/application/application.module.ts
app/scripts/modules/core/src/application/modal/editApplication.html
app/scripts/modules/core/src/application/modal/newapplication.html
app/scripts/modules/core/src/application/modal/upsertApplication.help.ts
app/scripts/modules/core/src/core.module.js
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/presentation/main.less

* adds some explanatory text to the cryptic "Instance Port" field.
* moves application modal help to its own file
* fixes the alignment of some checkboxes and their labels in the create/edit application modals

feat(core): include help on instance port, align checkboxes

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

When the pipeline has a docker registry trigger the value of c.imageDescription.imageId contains the (Tag resolved at runtime) from the trigger. This causes calls to the find image api to return [] and the calls are set up to run 10 times until a non empty result set is returned. These repeated calls to find image delay the dialog opening and the user is stuck watching a spinner for 10-20s. By switching to using c.imageDescription.repository, the find image calls return actual results and the dialog opens immediately.
https://spinnakerteam.slack.com/archives/C2W6RE0N4/p1495225548313863

fix(provider/kubernetes): fixes bug with edit server group dialog delays

---

app/scripts/modules/google/loadBalancer/configure/internal/listener.html

Editing ports in an ILB upsert is a no-op on the backend, so let's disallow this from the UI.

fix(provider/gce): Disallow editing ports for ILBs.

---

app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts

Removed this because I thought it was unnecessary, but apparently it is necessary?

fix(provider/amazon): fix load balancer vpc id

---

app/scripts/modules/core/src/deploymentStrategy/deploymentStrategySelector.component.ts

This isn't a problem for ad-hoc deploys (since they default to no strategy), but, when editing clusters in pipelines, if you have "red-black" or "custom" selected, the additional fields aren't displayed unless you switch to a different strategy, then back.

fix(core): initialize strategy selector

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/delivery/service/execution.service.ts
app/scripts/modules/core/src/delivery/service/executions.transformer.service.js

1. Omit a couple other fields when computing the `stringVal` for an execution: `requisiteIds`, `requisiteStageRefIds` - this is to deal with a weird bug in Orca where restarted stages can end up with 500k+ entries in that field
2. Dedupe the fields above, again just to get around the Orca bug
3. Correctly calculate whether stages have changed when synchronizing by looking at the stage itself, not the entire execution (which is always gonna be different, duh). This makes a (not really) surprisingly big difference.
4. When computing the `stringVal` for an execution, omit completed/not started stages. These should not ever change and thus should not factor into the `stringVal`, which is used to determine if the execution has changed.
There will probably be some bugs here, but the best way to …

fix(pipelines): correct diff on stages, smaller stringVal, dedupes

---

karma-shim.js

This only matters when you've run the `lib` builds for core, amazon, docker, etc, as they leave artifacts in the `/lib` directory, which karma doesn't like.
Opted for a `filter` call here as opposed to making the regex more convoluted.
Possibly better fix involves not outputting the spec files in `/lib`, who knows what that looks like...

fix(tests): exclude /lib/ from test context

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
app/scripts/modules/amazon/src/domain/index.ts
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/core/src/domain/ILoadBalancer.ts
app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts
app/scripts/modules/google/src/loadBalancer/loadBalancer.transformer.js

A first pass at separating out load balancer types. There is still some confusion around what gets transformed after the load balancers get read, and the different data structures when load balancers are retrieved as group vs a single load balancer, but this gets us a LOT closer to actual valid shapes.

refactor(provider/amazon): Separate load balancer types

---

app/scripts/modules/core/src/navigation/urlBuilder.service.ts

Ui-router returned null for the href for the state if region was missing, resulting in a Javascript crash (`Uncaught TypeError: Cannot read property 'includes' of null`).
This commit fixes this by mapping Kubernetes namespace to region.
@anotherchrisberry @jrsquared PTAL

fix(kubernetes): Search not working if result contained K8S load balancer

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/configure.less
app/scripts/modules/amazon/src/loadBalancer/configure/application/createApplicationLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/targetGroups.html
app/scripts/modules/amazon/src/loadBalancer/configure/choice/awsLoadBalancerChoice.modal.ts

We could definitely do a better job surfacing the errors, auto-updating the listeners to match updated names, and generating better names, but this forces the rule so I can move on to other, bigger ALB-related tasks. Will look at the other details later.

fix(provider/amazon): Require target groups to have unique names

---

app/scripts/modules/core/src/healthCounts/healthCounts.less

fixes a minor regression (only visible when a deploy stage is waiting for instances to come up) in the rendering of the health counts, where they are getting floated to the right, outside the parenthetical status indicator.

fix(pipelines): fix float on health counts

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/amazon/src/deploymentStrategy/rollingPush.strategy.ts

This is a very AWS-specific strategy (also, this is a regression)

fix(aws): restrict rolling push strategy to AWS

---

app/scripts/modules/core/src/entityTag/notifications/NotificationsPopover.tsx
app/scripts/modules/core/src/presentation/HoverablePopover.tsx

This adds `delayShow` and `delayHide` props and improves mouseenter/over and mouseleave handling.

feat(core/entityTag): Wait 100ms before showing entity tag popover

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/presentation/HoverablePopover.tsx

@christopherthielen sorry, I should have caught this in your PR earlier. We need to import directly from `rxjs` for library builds. I never figured out why, but something gets confused and breaks when we do deep imports like this, and it's not noticeable until you pull in core as a library.

fix(core): import from base rxjs

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/targetGroups/targetGroupSelector.component.html

fix(aws): provide explanatory text when no target groups present

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/listeners.html
app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts

* If there were no default security groups, would not render the security group names in the edit LB dialog
* Would not render health check timeout or health check interval in the target group edit details

fix(provider/amazon): Fix missing information for ALB target groups

---

app/scripts/modules/core/src/application/nav/applicationNav.component.less

Otherwise, the header is a couple pixels too tall and pulls the carat up, leaving a gap between it and the bottom of the header.

fix(core): reduce badge size in compact headers

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

Allow configuring container name in the RunJob stage. The default name
was the current date which makes it difficult to pin point containers for
logging purposes. Also, changes the default container name to `job`
since Clouddriver does that for containers without a name anyway.
Addresses [#1770](https://github.com/spinnaker/spinnaker/issues/1770)
@danielpeach PTAL!

feat(pipeline/RunJob): Allow container name conf

---

app/scripts/modules/amazon/src/certificates/amazon.certificate.read.service.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/createApplicationLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/listeners.html
app/scripts/modules/amazon/src/loadBalancer/configure/application/targetGroups.html
app/scripts/modules/amazon/src/loadBalancer/configure/classic/createClassicLoadBalancer.controller.spec.ts
app/scripts/modules/amazon/src/loadBalancer/configure/classic/createClassicLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/classic/listeners.html
app/scripts/modules/amazon/src/loadBalancer/configure/common/configure.less
app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.module.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/core/src/certificates/certificate.read.service.ts
app/scripts/modules/core/src/certificates/index.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/core/src/presentation/less/imports/colors.less

* Add a certificate service to cache the list of server certificates
* Convert load balancer (classic and application) certificate inputs to selects to use the new cache service
* A few minor CSS tweaks for the listeners in ALBs
* Fixes the bug where you couldn't actually put in a certificate for an HTTPS listener on an ALB
Relies on https://github.com/spinnaker/gate/pull/414 and https://github.com/spinnaker/clouddriver/pull/1702

feat(provider/amazon): Add certificate service and cleanup ALB listeners CRUD UI

---

app/scripts/modules/core/src/pipeline/config/services/pipelineConfig.service.ts

- pipeline deletes will fail if the name has leading whitespace
- Trimming the whitespace before submitting to the backend

fix(core): trim spaces from pipeline name before delete

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/serverGroup/details/details.html

Allows configurable Service Account Name for Server Groups and Run Job
configuration to enable applications access to the Kubernetes API if
need be. Default behavior is to assign the `default` Service Account if
left blank. I also added it to the Server Group details. Note, if the
service account is `default`, it will not show up as the API doesn't
return it with the ReplicaSet/Deployment.
@lwander FYI

feat(kubernetes): Configure Service Account Name

---

app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgmentExecutionDetails.html

A recent change to Orca allows stages to be considered successful if they time out, which was introduced specifically to allow manual judgment stages to act more optionally and not fail. This is something we're doing on some internal stuff at Netflix.
If the stage is complete, though, we want to hide the judgment options, which is what this change does.

fix(core): hide judgment inputs if manual judgment succeeded

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/createApplicationLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/targetGroups.html
app/scripts/modules/amazon/src/loadBalancer/configure/classic/createClassicLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/common/configure.less
app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts

Force target group names to start with load balancer name because reasons.
@anotherchrisberry or @christopherthielen PTAL

feat(provider/amazon): Enforce target group naming convention

---

app/scripts/modules/core/src/pipeline/config/stages/core/baseExecutionDetails.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/script/scriptExecutionDetails.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/script/scriptExecutionDetails.html
app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.module.js

We've gotten user complaints that troubleshooting a failed script execution is not obvious:
Users are not seeing the "Script Results" link above, or not understanding that they can see the output of the script by clicking on the link 
This PR makes the link more obvious:

fix(core): improve error message on script stage failure

---

app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/core/src/certificates/certificate.read.service.ts

The number of times that certificates are needed (only when creating or editing a load balancer) are too few to really justify a cache. Caching also provides a disconnect between time added to AWS and time they show up in the UI.

feat(provider/amazon): Load certificates on demand

---

app/scripts/modules/core/src/application/config/applicationCacheManagement.directive.html
app/scripts/modules/core/src/application/config/applicationCacheManagement.directive.js

Added these checks when adding certificate caching since it's provider specific. Even after ripping out certificate caching, figured these checks were still nice to have.

fix(provider/amazon): Check to make sure cache types exists before showing refresh

---

.gitignore
app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/loadBalancer/TargetGroup.tsx
app/scripts/modules/core/package.json
app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/instance/instances.component.ts
app/scripts/modules/core/src/loadBalancer/LoadBalancer.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancerServerGroup.tsx
app/scripts/modules/core/src/loadBalancer/loadBalancer.states.ts
app/scripts/modules/core/src/navigation/state.provider.ts
app/scripts/modules/core/src/navigation/stateHelper.provider.ts
app/scripts/modules/core/src/reactShims/index.ts
app/scripts/modules/core/src/reactShims/react.module.ts
app/scripts/modules/core/src/reactShims/react.uirouter.css
app/scripts/modules/core/src/reactShims/react.uirouter.tsx
app/scripts/modules/core/src/securityGroup/securityGroup.directive.js
app/scripts/modules/core/src/securityGroup/securityGroup.html
app/scripts/modules/core/src/utils/stickyHeader/stickyHeader.component.ts
package.json
yarn.lock

- Removes ` @uirouter/angularjs`
- Adds `@uirouter/react-hybrid` which depends on `@uirouter/react` and `@uirouter/angularjs`
- Switch to `@uirouter/react` components `UISref` and `UISrefActive` and remove `inheritedData()` workaround
- Routes to `LoadBalancers` react component
- Bumps `core` and `amazon` versions

feat(react): Route to react components; use react UISref components

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/loadBalancer/configure/application/createApplicationLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/targetGroups.html
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts

Also do not allow the user to enter a target group name that will be longer than 32 characters (AWS limit)
@christopherthielen PTAL
@cfieber FYI

fix(provider/amazon): Only enforce TG naming to be based on appname

---

app/scripts/modules/core/src/pipeline/config/templates/Variable.less
app/scripts/modules/core/src/pipeline/config/templates/Variable.tsx

Wrap variable names in pipeline template variable config modal (instead of hiding parts of them). I guess I could do something clever to break the variable names non-arbitrarily...but who knows what conventions people are using for variable names.

fix(pipeline_templates): wrap variable name

---

app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/amazon/src/securityGroup/securityGroup.reader.ts
app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts

Starting to add a few things to security groups and trying to reason about the current structure was... miserable. Rename some of the types and reuse others that already existed.

refactor(core): Refactor security group types to make sense

---

app/scripts/modules/core/src/delivery/service/executions.transformer.service.js
app/scripts/modules/core/src/pipeline/config/graph/pipeline.graph.component.ts

Getting some console errors for undefined nodes, protect against this case.

fix(core): Protect against undefined nodes in the pipeline graph

---

yarn.lock

Not sure how this happened, but yarn.lock and package.json are out of sync on `react-hybrid` (0.0.4 in package, 0.0.3 in yarn).
@christopherthielen PTAL

chore(core): update yarn lock file for react-router

---

app/scripts/modules/core/src/naming/naming.service.ts
app/scripts/modules/core/src/navigation/index.ts
app/scripts/modules/core/src/navigation/urlBuilder.registry.ts
app/scripts/modules/core/src/navigation/urlBuilder.service.ts
app/scripts/modules/core/src/search/externalSearch.registry.ts
app/scripts/modules/core/src/search/index.ts
app/scripts/modules/core/src/search/infrastructure/infrastructure.html
app/scripts/modules/core/src/search/infrastructure/infrastructureSearch.service.ts
app/scripts/modules/core/src/search/searchResult/searchResult.directive.html

Allows search integration without adding custom functionality (e.g. proxying) to Gate or any other service.
The expectation is that the searches will return in a reasonable amount of time, since all search results must be resolved before rendering. We may want to revisit that later, although I'm not crazy about it, as it would add some jank to the page.
Also added some one-time bindings to search results on the infrastructure page, and tweaked the search results to allow HTML.

feat(core): implement external search API in infrastructure search

---

app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.html
app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.ts

I'm seeing one strange thing, and I don't know if it's intentional. Any attempt to disable a k8s server group in stage like "destroy" or a pipeline fails because of the traffic guard, but a direct "disable" operation greets me with this dialog: 
and the disable succeeds if I enter "0". Is that right?
@tomaslin @duftler FYI

fix(traffic_guards): Allow accounts w/ namespaces to use traffic guards

---

app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.aws.controller.js

Adding a guard to verify `buildInfo` exists; replacing other guards with lodash `has` for brevity.
cc @icfantv

fix(aws): guard against missing buildInfo on server group details

---

app/scripts/modules/core/src/presentation/formsy/components/TextArea.tsx
package.json
yarn.lock

The type definitions are a bit shaky in 15.0.>35 (36,37,38 have come out in the past three days), so let's pin this to 35 for now.

chore(core): downgrade @types/react to 15.0.35

---

app/scripts/modules/core/.npmignore
app/scripts/modules/core/package.json
app/scripts/modules/core/src/delivery/executions/executions.html
app/scripts/modules/core/src/delivery/executions/executions.less
app/scripts/modules/core/src/insight/insightLayout.component.html
package.json
yarn.lock

v0.0.12 passes `secondary-panel` class through to the `ui-view`

fix(scroll): Update react-hybrid to 0.0.12 

---

app/scripts/modules/core/src/application/ApplicationComponent.tsx

We still want to set the state if the application is not found, as the `render` method depends on `state.compactHeader`.

fix(core): avoid NPE rendering header for missing apps

---

app/scripts/modules/core/src/account/accountTag.component.ts

If the account changes from a prod account to a non-prod account, the tag will not necessarily update its color.

fix(core): update account tag color on account change

---

app/scripts/modules/core/src/config/settings.ts

We are basically doing this already on provider settings, just not on the main settings.

fix(core): preserve reset methods on settings reset calls

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts

We need to update the stage on the controller when the state changes; otherwise, clicking on the execution graph between two stages will not update the execution details fully.

fix(core): update webhook stage scope on stage change

---

app/scripts/modules/core/src/delivery/executionGroup/executionGroup.less

Fixes a minor regression from the conversion of sticky headers to CSS-only, adding a little gap between the headers on the executions view when they are collapsed.
**Current**
**PR**

fix(core): add margin between collapsed execution group headers

---

app/scripts/modules/core/src/delivery/details/singleExecutionDetails.component.ts
app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts

A couple of small things I noticed investigating other issues:
* we should consider the `FAILED_CONTINUE` status when computing the `isFailed` property
* the single execution details loads the execution twice when it loads

fix(core): avoid double-load of execution, treat F_C as isFailed

---

app/scripts/modules/canary/canary/canaryStage.transformer.js
app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts

At some point, `deploy` became `createServerGroup`, resulting is us losing a fair amount of context (task status, exceptions).
This fixes that, and also treats `STOPPED` as a failed state, since it is a failed state.

fix(canary): show exception on STOPPED; extract deploy stages

---

app/scripts/modules/core/package.json
app/scripts/modules/core/webpack.config.js

fix(canary): show exception on STOPPED; extract deploy stages
fix(core): avoid double-load of execution, treat FAILED_CONTINUE as isFailed

chore(core): bump package to 0.0.45

---

app/scripts/modules/core/src/cluster/allClusters.controller.js
app/scripts/modules/core/src/serverGroup/serverGroup.component.ts
app/scripts/modules/core/src/utils/scrollTo/scrollTo.service.ts

Cluster and server group names can have invalid (at least according to jQuery) characters in their names, like `^`.
Like most util-like functions, there's no great place to put this dumb thing so I jammed it into the scrollToService, since that's what inevitably calls the things with the ids.

fix(core): provide valid ids for scrollTo clusters

---

app/scripts/modules/core/src/bootstrap/spinnaker.component.ts
app/scripts/modules/core/src/delivery/create/TemplateDescription.tsx
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/rollingredblack.strategy.ts
app/scripts/modules/core/src/instance/details/console/consoleOutputLink.directive.js
app/scripts/modules/core/src/navigation/urlBuilder.registry.ts
app/scripts/modules/core/src/pipeline/config/stages/script/scriptExecutionDetails.controller.ts
app/scripts/modules/core/src/pipeline/config/templates/Variable.spec.tsx
app/scripts/modules/core/src/search/externalSearch.registry.ts

* for files already in the core module, modify the imports to not import
from `@spinnaker/core`.  rather, favor importing from their `core/` or
relative path.

chore(imports): don't use alias for core imports

---

app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.html

Changes were made to the Jenkins task UI used by Deck to support
specific parameter types already provided by Igor. The default was left as
input:text to keep the functionality for unknown/unspecified parameter types.
Recommendations/changes welcome.
[https://github.com/spinnaker/spinnaker/issues/1872](Issue)

feat(CI/Jenkins): Add parameter type checking/mapped elements to Jenkins task UI.

---

app/scripts/modules/amazon/src/loadBalancer/configure/classic/advancedSettings.html
app/scripts/modules/core/src/help/help.contents.ts

* add an error check and message around ensuring the load balancer
health timeout is less than the health interval.
* updated help bubble text to include field value requirements for timeout and interval.
* fix broken help bubbles for classic ELB advanced settings.

fix(aws/loadbalancer): ensure timeout < interval

---

app/scripts/modules/core/src/presentation/details.less

At some point, the icon got shifted down by 10px. This aligns it with the text.

fix(core): fix alignment of copy-to-clipboard icon

---

app/scripts/modules/core/src/presentation/HoverablePopover.tsx

If a popover includes two input elements, navigating between them causing the popover to close, which is surprising.

fix(core): remove blur handler on HoverablePopover

---

app/scripts/modules/core/src/delivery/details/singleExecutionDetails.component.ts

maybe we shouldn't constantly add a load operation every time the execution is refreshed

fix(pipelines): do not exponentially load single execution details

---

app/scripts/modules/core/src/delivery/delivery.dataSource.js
app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/src/delivery/filter/executionFilter.service.spec.ts
app/scripts/modules/core/src/delivery/filter/executionFilter.service.ts
app/scripts/modules/core/src/delivery/service/execution.service.spec.js
app/scripts/modules/core/src/delivery/service/execution.service.ts

This addresses a source of confusion for users who see a discrepancy between the running executions badge counter and the badge counters on individual pipelines due to a couple of things:
1. There are two data sources in play: one to get the overall count (`runningExecutions`), another to get the executions for each pipeline (`executions`), and they are both loaded asynchronously, so they often won't reflect the same data.
2. The `executions` data source has a limit based on a UI control that determines how many pipelines it loads. If one pipeline has five active executions going, but the UI control is set to "2", the user will only see "2" in the badge on that pipeline and wonder where the other three running executions are.
With this change, the numbers should always make sense, except …

fix(pipelines): always show running executions and keep count in sync

---

halconfig/settings.js

This was inadvertently left out of #4015.

fix(dcos): Add DC/OS to the list of default providers

---

app/scripts/modules/core/src/utils/timeFormatters.spec.ts
app/scripts/modules/core/src/utils/timeFormatters.ts

When a task has been running for more than a month, the duration's number of days rolls over back to 1.  This switches to moment's `asDays()` instead of `days()`

fix(core/utils): Fix task running duration when longer than 31 days

---

app/scripts/modules/core/src/cluster/cluster.service.ts

Orca V3 uses the `createServerGroup` stage, not the `deploy` stage.
(We should probably move this code out of the cluster service itself and put it into the stage config at some point, but not today)

fix(core): add createServerGroup to list of candidate running stages

---

app/scripts/modules/core/src/canary/canaryScores.component.ts

There's a directive naming collision with our internal build, so renaming this for now to get a fix out.
cc @danielpeach

fix(core): rename canary score component

---

app/scripts/modules/core/package.json

fix(core/utils): Fix task running duration when longer than 31 days
fix(core): add createServerGroup to list of candidate running stages
fix(core): rename canary score component

chore(core): bump package to 0.0.53

---

app/scripts/modules/core/src/serverGroup/configure/common/deployInitializer.component.ts

When `viewState.disableNoTemplateSelection` is not set, `selectedTemplate` never gets set. If there is only one template, this control assumes that single template is already selected.
...
This took me way too long to figure out.

fix(core): Fix deploy template selection when one server group and no template selection is disabled

---

app/scripts/modules/kubernetes/help/kubernetes.help.ts
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js
app/scripts/modules/kubernetes/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.controller.js
app/scripts/modules/kubernetes/serverGroup/configure/wizard/advancedSettings.html

adds support for dns policy on server groups and run job stages.
https://kubernetes.io/docs/api-reference/v1.7/#pod-v1-core
Corresponding Clouddriver PR: spinnaker/clouddriver#1800

feat(provider/kubernetes): add dns policy

---

app/scripts/modules/core/src/cancelModal/cancel.html
app/scripts/modules/core/src/cancelModal/cancelModal.service.ts
app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/src/domain/IExecution.ts
app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/pipeline/config/services/piplineConfig.service.spec.ts
app/scripts/modules/core/src/pipeline/config/validation/pipelineConfig.validator.spec.ts

The executionEngine field is redundant as there's only one now and we will hopefully never create a v4.
Force cancel does nothing as of v3.

chore(deck): removed executionEngine flag and force cancel option

---

app/scripts/modules/core/package.json

* fix(core): Fix deploy template selection when one server group and no template selection is disabled
* style(core/styleguide) Cataloging Spinnaker styles in to a style guide
* refactor(core + canary): move shared canary components back to canary module
* fix(core): do not overwrite target percentages on rolling red/black
* chore(deck): removed executionEngine flag and force cancel option
* feat(pipeline_templates): adds link to template json

chore(core): bump package to 0.0.54

---

app/scripts/modules/core/src/styleguide/src/styles/postcss.config.js

The relative path wasn't working so great for the core library, in that it was preventing it from being built.
Seems like a great case for the old `path` hammer.

chore(styleguide): fix styleguide config paths

---

app/scripts/modules/core/src/application/config/links/applicationLinks.component.html
app/scripts/modules/core/src/instance/details/instanceLinks.component.js

Allows users to configure HTTPS-specific links to instances when required, e.g. `https://{{ipAddress}}:7002/something`, without having to specify `privateIpAddress` or `publicDnsName`.
Also adding a link to the guide on spinnaker.io to help folks with self-service on this feature.

feat(core): include address in context for instance links

---

.gitignore
app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx

Actually three things:
1. Allow "Stop" and "Continue" button labels to be customized
2. Allow execution account labels to be shown regardless of sort filter status
3. add the styleguide generated file to .gitignore

feat(core): allow customization of manual judgment action labels

---

app/scripts/modules/amazon/package.json

Not sure what's going on, but running `npm publish` did not run the `prepare` script - just pushed what was already there to npm.
What I'm saying is this is the same as version 0.0.27 except it actually contains the changes that are in the src directory of 27, just not in the build lib.js artifact.
Something strange is going on. Not sure if it's just me...

chore(amazon): bump package to 0.0.28

---

app/scripts/modules/amazon/src/aws.settings.ts
app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/src/pipeline/stages/bake/bakeStage.html

This is supported by the Netflix internal bakery only right now.

feat(amazon): make root volume size configurable on bake stage

---

app/scripts/modules/core/src/delivery/filter/executionFilter.controller.js

Console errors occasionally show up for this. We eventually will refactor, but for now: seatbelt.

fix(core/delivery): Seatbelt for undefined on execution filter destroy

---

app/scripts/modules/core/src/delivery/create/CreatePipelineModal.tsx

Seeing occasional errors in our logs, maybe we shouldn't?

fix(core): avoid accessing data source when not present or loaded

---

app/scripts/modules/core/src/forms/buttonBusyIndicator/buttonBusyIndicator.component.ts
app/scripts/modules/core/src/help/HelpField.tsx
app/scripts/modules/core/src/help/helpField.component.ts
app/scripts/modules/core/src/modal/buttons/SubmitButton.tsx
app/scripts/modules/core/src/modal/buttons/submitButton.component.ts
app/scripts/modules/core/src/presentation/main.less

These components no longer render properly under `.styleguide` due to this rule:
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/styleguide/src/styles/typography.css#L157-L159 

fix(styles): fix icons under styleguide class

---

app/scripts/modules/core/src/pipeline/config/stages/core/editStageJson.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/core/editStageJson.modal.html
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js

We frequently tell folks to edit the pipeline JSON to access features that aren't exposed via the UI. This is cumbersome on a sufficiently large pipeline.
This PR does not deal with locked pipelines - wanted to get opinions on if this a good idea or not. If we like it, I'll add read-only functionality for locked pipelines.
We also still need to come up with an approach to handle expressions in non-text fields, something that's long overdue.

feat(pipelines): allow JSON editing of individual stages

---

app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.controller.js

I'm scratching my head on this one. I think the intent was: if a user set up a fast property or wanted to override some other field for a single execution, they'd want to carry that update through to subsequent executions.
That might be true in some cases, but it's causing a lot of confusion for teams that sometimes don't want to set a property and are deleting the property for their execution, and then it's gone for the next execution.
This behavior was very surprising to me. I couldn't even understand what the user was complaining about until I removed a property, ran the pipeline, then re-ran it and saw that the property was gone.

fix(pipelines): do not save changes to pipeline config on execution run

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js

`target-groups` has been collapsed under `load-balancers`

fix(aws): fix markDirty call on target group removal in clone dialog

---

webpack.common.js

This might make sense to someone else.
This afternoon, we started noticing the cloud provider icons were not rendering when running the dev server. This might also be affecting OSS users (we have a custom build internally which consumes the modules).
I'm not sure why, but the first `file-loader` rule (#L66 in the current code) seemed to be catching and processing the SVG files, and outputting them as references to the files that were generated via #L75's rule, which resulted in invalid SVG files, and, thus, no images. Removing the `(.*)` from the regex fixed it.
I added naming patterns to the outputs to help trace this down and left it in because it's nice to know what the files are, e.g. `appengine.icon.d44e5.svg` instead of `4738441332bb5b89fbf1b32f390fd573.svg`.

fix(webpack): fix svg rendering in devServer mode

---

gradle/installViaTravis.sh
package.json

`yarn install` fails with yarn 1.0+ which enforces the `engines` fields
@icfantv @anotherchrisberry @jrsquared

fix(package): Widen package.json engines fields

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/core/src/search/widgets/search.component.ts

* basically all cloud providers have the current set of filter types so
there's no reason to tie it to the aws module.  also, because the
new page will ultimately be feature flagged due to the necessary
back-end clouddriver work (i.e., `KeyParser` implementation).

chore(search): move enabled filters

---

app/scripts/modules/core/src/pipeline/config/stages/optionalStage/optionalStage.directive.js

This should fix a bug when editing a pipeline that has no stages causing deck to crash.

fix(core): Seatbelt optionalStage directive to make sure stage exists

---

app/scripts/modules/core/src/cluster/rollups.less

Broke the background color for active server group. Fixed it to use a shade of blue from the style guide.

style(core/cluster): Fixed active state color for server group

---

app/scripts/modules/core/src/delivery/status/executionStatus.component.ts
app/scripts/modules/core/src/delivery/status/executionStatus.html

Fixes a somewhat recent regression where execution relative times stopped updating. Previously, they updated because we'd replace the entire execution and re-render it pretty frequently, but we're a little more selective with what we re-render now...

fix(pipelines): refresh relative start time on interval

---

app/scripts/modules/core/src/cluster/ClusterPod.tsx
app/scripts/modules/core/src/cluster/ClusterPodTitleWrapper.tsx
app/scripts/modules/core/src/cluster/DefaultClusterPodTitle.tsx
app/scripts/modules/core/src/cluster/index.ts
app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/entityTag/entityTags.module.ts
app/scripts/modules/core/src/entityTag/index.ts
app/scripts/modules/core/src/entityTag/notifications/EntityNotifications.tsx
app/scripts/modules/core/src/entityTag/notifications/entityNotifications.component.ts
app/scripts/modules/core/src/entityTag/notifications/index.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/core/src/widgets/index.ts

Allows customization of the cluster pod header.
@christopherthielen PTAL

refactor(cluster): allow cluster pod header to be customized

---

app/scripts/modules/core/src/pipeline/config/actions/pipelineConfigActions.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

A call that once took 100ms now takes up to a second or two sometimes (usually not, but sometimes it does), so it's confusing to users when they see "no version history".

fix(pipelines): show loading message while fetching version history

---

app/scripts/modules/core/src/application/applicationModel.builder.ts
app/scripts/modules/core/src/application/config/appConfig.dataSource.js
app/scripts/modules/core/src/application/service/application.read.service.ts
app/scripts/modules/core/src/application/service/applicationDataSource.registry.ts
app/scripts/modules/core/src/application/service/applicationDataSource.ts
app/scripts/modules/core/src/delivery/delivery.dataSource.js
app/scripts/modules/core/src/loadBalancer/loadBalancer.dataSource.ts
app/scripts/modules/core/src/securityGroup/securityGroup.dataSource.js
app/scripts/modules/core/src/serverGroup/serverGroup.dataSource.js
app/scripts/modules/core/src/task/task.dataSource.js

- Also deprecate and remove usage of `DataSourceConfig` because it doesn't do anything useful
@anotherchrisberry @icfantv @jrsquared ptal

feat(core/application): Add 'autoActivate' toggle for DataSources

---

app/scripts/modules/core/src/application/ApplicationPostSearchResultSearcher.ts
app/scripts/modules/core/src/cluster/ClusterPostSearchResultSearcher.ts

* add default method value for post search result searchers so that it
can intelligently process search result map lookups that don't exist.
this is currently an artifact of region searching such that too many
search results are found and they're culled in clouddriver so that only
instance results come back.  we need to change the way the results are
returned for the new search to perhaps limit the search results to, say,
_n per type rather than _n total_.  need to have a think about
this.

fix(search): add default method value

---

package.json
yarn.lock

In prep for switch from `@autoBindMethods` to `@BindAll`

chore(deps): Update lodash-decorators to 4.4.1

---

app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Before, the Subnet selector in the server group details always defaulted to the first subnet choice. Now the subnet is properly populated from the server group details.

fix(provider/openstack): Subnet Selector shows correct subnet

---

app/scripts/modules/amazon/src/loadBalancer/AmazonLoadBalancerClusterContainer.tsx
app/scripts/modules/amazon/src/loadBalancer/amazonLoadBalancerDataUtils.ts
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/core/src/loadBalancer/LoadBalancerPod.tsx

NLBs are live in AWS (and already cached in Clouddriver). This does not allow CRUD of NLBs, but it will allow you to see the existence of them in deck and select those already existing target groups in a deploy configuration.

feat(provider/amazon): Show NLBs in the Load Balancer screen and allow NLB target groups to be selected when deploying

---

app/scripts/modules/google/src/domain/backendService.ts
app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/loadBalancer/configure/common/commonCreateLoadBalancer.html
app/scripts/modules/google/src/loadBalancer/configure/common/commonEditLoadBalancer.html
app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.html
app/scripts/modules/google/src/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/google/src/loadBalancer/configure/ssl/portName.html
app/scripts/modules/google/src/loadBalancer/configure/tcp/gceCreateTcpLoadBalancer.controller.ts
app/scripts/modules/google/src/loadBalancer/configure/tcp/portName.html
app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.html
app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts

Added a new section to declare named ports in the affected LBs and a new section in the GCE server group wizard to add named ports and map them to an actual port number.

feat(provider/gce): Support named ports for global LBs.

---

app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.less

I broke this all the way back in https://github.com/spinnaker/deck/pull/4127

fix(projects): restore project header width to 100%

---

app/scripts/modules/core/src/config/versionCheck.service.ts

Using the much more efficient empty arrow function in lieu of the bulky `noop` that some people prefer

fix(versionCheck): swallow exception if version.json fetch fails

---

app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.ts

Sending int/float variables as strings cause validation errors on the server side.

fix(pipeline_template): Cast numeric variable types during plan

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

I will not explain why this fixes the pipeline config rendering when using the "Edit as JSON" feature, nor will I explain why it's currently broken. Also, I will not confirm this change doesn't have any surprising side effect on templated pipelines.

fix(pipelines): correctly rerender when editing JSON

---

app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts

If a moniker is available for the server group it is passed along to orca/clouddriver to process the task/job.

feat(moniker) - updating server group writer/operations to pass moniker params to gate/orca

---

app/scripts/modules/amazon/src/pipeline/stages/cloneServerGroup/awsCloneServerGroupStage.js
app/scripts/modules/core/src/application/listExtractor/listExtractor.service.spec.ts
app/scripts/modules/core/src/application/listExtractor/listExtractor.service.ts

This fix adds a filter to only retrieve the target cluster moniker.  Previously it returned all monikers and it just grabbed the first one.

fix(moniker) - adds filter to only retrieve target cluster for clone aws cluster stage

---

app/scripts/modules/core/src/cloudProvider/versionSelection/versionSelector.component.ts

TS complains (fairly) that this field shouldn't be private. It is used in the template, so just making it public here.

fix(core): remove access modifier from local variable in versionSelector

---

app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/kubernetes/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

All accounts should be reporting `providerVersion` now, since the account interface returns `v1` by default: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AccountCredentials.java#L72
Even if they don't, as long as the provider ignores the version no change in behavior should happen.

feat(core): Version account lookup

---

app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts

New PR because I'm always going to fail at rebasing against deck correctly.
From: https://cloud.google.com/compute/docs/disks/local-ssd#create_local_ssd
"Each local SSD is 375 GB in size, but you can attach up to eight local SSD devices for 3 TB of total local SSD storage space per instance"
4 was the old limit
Closes spinnaker/spinnaker#1945

fix(provider/gce) Update max disk number for local-ssd to 8 from 4

---

app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts

`credentials` is there for the upsert load balancer stage, but not when editing an existing load balancer.

fix(amazon): properly assign credentials when editing load balancers

---

app/scripts/modules/core/src/delivery/executions/executions.html

No need for `execution-filters` - it's being used for the side filters and this is confusing (and causing misalignment of the entries in the top header).

fix(executions): fix header alignment

---

app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/manifest/manifestWriter.module.ts
app/scripts/modules/core/src/manifest/manifestWriter.service.ts
app/scripts/modules/kubernetes/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/v2/manifest/manifestCommandBuilder.service.ts
app/scripts/modules/kubernetes/v2/manifest/wizard/basicSettings.component.ts
app/scripts/modules/kubernetes/v2/manifest/wizard/manifestEntry.component.ts
app/scripts/modules/kubernetes/v2/manifest/wizard/manifestEntry.less
app/scripts/modules/kubernetes/v2/manifest/wizard/manifestWizard.controller.ts
app/scripts/modules/kubernetes/v2/manifest/wizard/manifestWizard.html
app/scripts/modules/kubernetes/v2/serverGroup/serverGroupCommandBuilder.service.ts

Requires a change in orca for this to work - probably shouldn't be merged yet.

feat(provider/kubernetes): Create manifest

---

app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/appengineEditLoadBalancerStage.ts
app/scripts/modules/azure/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/canary/canary/canaryStage.js
app/scripts/modules/core/src/application/applications.component.ts
app/scripts/modules/core/src/application/config/applicationAttributes.directive.js
app/scripts/modules/core/src/application/config/applicationAttributes.directive.spec.js
app/scripts/modules/core/src/application/config/links/applicationLinks.component.js
app/scripts/modules/core/src/delivery/executionGroup/ExecutionGroup.tsx
app/scripts/modules/core/src/delivery/executions/executions.controller.js
app/scripts/modules/core/src/modal/dismiss.decorator.ts
app/scripts/modules/core/src/modal/modal.module.js
app/scripts/modules/core/src/notification/notificationList.directive.js
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/src/pipeline/config/preconditions/preconditionList.directive.js
app/scripts/modules/core/src/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.js
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgmentStage.js
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
app/scripts/modules/core/src/projects/project.controller.js
app/scripts/modules/core/src/projects/projects.controller.js
app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
app/scripts/modules/core/src/search/infrastructure/infrastructureV2.controller.ts
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

With the changes from [this PR](https://github.com/spinnaker/deck/commit/64d385fab6ec93f71208b5888bbcf3f8b52c537e), we need to provide a catch if we are doing anything with the `result` of a modal being opened.
The decorator is in place to catch dismiss calls from `ReactInjector`d modals, e.g. clicking "Create Load Balancer", then dismissing the modal. Not sure why that always triggers the exception, but it does.

fix(core/modal): avoid throwing errors on modal $dismiss

---

app/scripts/modules/core/src/api/network.interceptor.ts
app/scripts/modules/core/src/core.module.ts

We're seeing a lot of errors due to users closing their laptops, then reopening them, while Deck is making http calls. These surface with a status of `-1`.
I tested this locally by closing my laptop while a refresh was happening, then reopening it a few seconds later, then a few minutes later, and did not get the flurry of thrown errors in the console. Also tested by toggling the wifi on my laptop, with similar results.
I don't think this will clear up all the error emails we get (internally at Netflix), but I think it'll clear up quite a few, and I think it'll also make the UI more resilient to those common scenarios.

fix(core/http): retry http calls failing due to network issues

---

app/scripts/modules/core/src/api/network.interceptor.ts

The current implementation goes a little crazy for a number of reasons, mostly 
a) the `config` object returned in the response interceptor is a copy of the original one, so the `retryQueue` never gets cleaned up, but also because
b) we were never putting anything in the `retryQueue` because let's not worry about why that was the case
Instead, we'll retry based on the `url` of the request, and we'll only retry up to 4 times, meaning requests will stop retrying after 10 to 15 seconds.

fix(network): include backoff, max number of retries in network recovery

---

app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js

Adding a couple of checks to avoid some exceptions when 
a) the server group has been destroyed
b) the server group has no `buildInfo`

fix(pipelines): guard against missing info on deploy stage

---

app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js

Removes 'application accounts' handling for a simpler and straightforward approach. Fixes an issue where infrastructure needs to be present for regions/networks/subnets etc to be populated in the server group from the credentials.
Dan typed this change on my keyboard.

fix(provider/gce): Fix credential account handling in svg wizard.

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts

It's not _really_ required, but it's confusing that it'll default to a `POST` on the backend, so let's strongly suggest users enter something.

fix(pipelines): add validator to webhook stage "method" field

---

app/scripts/modules/core/src/domain/IArtifact.ts
app/scripts/modules/core/src/domain/IBuild.ts
app/scripts/modules/core/src/domain/IExpectedArtifact.ts
app/scripts/modules/core/src/domain/index.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.html
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.html
app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
app/scripts/modules/core/src/pipeline/config/validation/pipelineConfig.validator.ts

I know there has to be a better way to display this but, the idea is
1. A user describes a subset of the fields to match their artifact against
2. If no artifact matches, they can optionally use a prior execution's artifact
3. If that fails, or is not specified, they can fall back to a "default artifact"
4. If that fails, or is not specified, the pipeline fails to start. 
With the related orca, echo & kork changes I got this to work. 
Later at the top of each "expected artifact block" you will be able to pick a "type" that changes how the match & default artifacts are rendered. For example, if the type "gcs" is selected, the user will have to fill out the artifact's bucket & filepath instead of "type, name, location, version & reference".

feat(artifacts): Simplify expected artifacts

---

app/scripts/modules/core/src/help/help.contents.ts

@lwander 
`ol` will count for you and you won't get a bullet point and a number.

fix(artifact): s/ul/ol

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts

This feature adds monikers to the amazon deploy stage.  One line of note is regarding the stringify of the application object below.  This is because the model (IServerGroupCommand) expecting an Application object but at runtime a string is given (see screenshot below).  So to avoid a compilation error, we stringify.  Not sure if there is a better approach.

feat(moniker) - adding monikers to the deploy stage

---

app/scripts/modules/openstack/common/cacheBackedMultiSelect.template.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/interface.html
app/scripts/modules/openstack/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/openstack/network/networkSelectField.directive.js

fix(provider/openstack): Fixed network so it is filtered by account for load balancer creation.
fix(provider/openstack): Fixed network so it refreshes when a new account is selected.
fix(provider/openstack): Fixed network so it resets to default when a new account is selected and the selected network becomes invalid.
fix(provider/openstack): Fixed security groups so it clears and refreshes when a new account is selected.
fix(provider/openstack): Fixed security groups refresh button.
fix(provider/openstack): Removed security group refresh tooltip that wasn't showing any data.

OS load balancer network and sg bugfixes

---

app/scripts/modules/core/src/entityTag/entitySource.popover.html

As of spinnaker/orca#1705, `orca` is now adding previous server group
details to the `spinnaker:metadata` tag.
These details include:
- previous server group name
- image name
- image id

feat(entitytags): Show replaced server group details in popover

---

app/scripts/modules/azure/cache/cacheConfigurer.service.js

fix(azure): retain `this` binding in azure cache initializer

---

app/scripts/modules/core/src/task/tasks.html

We claim in the placeholder text of the `reason` field in the modals that HTML is okay, so maybe we should try rendering HTML...

fix(core): render reason as HTML in tasks view

---

app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.html

Rolling back to a previous image is available iff:
- a `spinnaker:metadata` entity tag exists with `previousServerGroup`
details
- there are no other server groups in the cluster/region

feat(provider/amazon): Rollback support for PREVIOUS_IMAGE strategy

---

app/scripts/modules/kubernetes/help/kubernetes.help.ts
app/scripts/modules/kubernetes/securityGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/createWizard.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/editWizard.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/tls.controller.js
app/scripts/modules/kubernetes/securityGroup/configure/wizard/tls.html
app/scripts/modules/kubernetes/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/securityGroup/details/details.controller.js
app/scripts/modules/kubernetes/securityGroup/details/details.html
app/scripts/modules/kubernetes/securityGroup/transformer.js

This enables the setting of annotations, labels and TLS secrets on k8s Security groups (aka ingress resources) from the UI.
It is one of 2 PR's that fix spinnaker/spinnaker#2000 (the other being spinnaker/clouddriver#2005)

feat(provider/kubernetes): Enable annotations, labels and secrets for security groups (aka ingress resources) (spinnaker/spinnaker#2000)

---

app/scripts/modules/core/src/deploymentStrategy/deploymentStrategy.module.ts
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/additionalFields.html
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/pipelineSelector.component.html
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/pipelineSelector.component.ts
app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/rollingredblack.strategy.ts

feat(rrb): Allow for specifying pipelines to run before disable

---

app/scripts/modules/core/src/pipeline/config/stages/executionWindows/executionWindowsDetails.html

If an execution window fails, the reason is not displayed to the user. This PR fixes that.

fix(core/pipeline): Show errors in time window stage execution details

---

app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx

If the `get` call fails, an exception will be thrown, but the execution will never try to refresh again, which can cause confusion.

fix(core): handle running execution fetch failure

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/utils/uibModalRejections.ts
app/scripts/modules/core/src/utils/utils.module.js

This still allows the `.result` to be chained off from the calling code, such as:
```
$uibmodal.open({ ... }).result.then(onConfirm, onCancel)
```

feat(core/modal): Silence all rejection warning in console when ui-bootstrap modals are closed/cancelled.

---

app/scripts/modules/core/src/delivery/details/executionDetails.less

Small CSS adjustment. There used to be a whitespace character between the glyph and the heading text in the Angular days.

fix(core/executions): tweak padding on status glyph

---

app/scripts/modules/core/src/delivery/service/executions.transformer.service.ts

fix(core): Stop grouping groups with only one stage

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/canary/canary/canaryStage.js
app/scripts/modules/core/package.json
app/scripts/modules/core/src/naming/naming.service.ts

The `moniker` objects for the `*-baseline` and `*-canary` clusters were not being updated properly after editing the canary cluster configuration.
@anotherchrisberry @jrsquared @asher @cfieber

fix(canary): Fix moniker for baseline/canary clusters

---

app/scripts/modules/core/src/projects/project.controller.js
app/scripts/modules/core/src/projects/project.less

We lost the refresh icon when we changed it from bootstrap to font awesome.
The initial application setting broke (I think) when we upgraded ui-router at some point (looks like we were relying on the stateChangeSuccess event previously).

fix(core/projects): restore refresh icon, set app name on init

---

app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentExecutionDetails.tsx

Fixes a regression from a couple of weeks ago, where a misleading exception on a manual judgment stage always appears when the user halts the stage.

fix(core): omit exception message on stopped manual judgment stages

---

app/scripts/modules/core/src/cluster/rollups.less

add support for `health-status-Failed`. previously, instances in a
`Failed` state were getting the `Up` styling which is misleading.
Fixes spinnaker/spinnaker#2059

fix(core): support failed health status style

---

app/scripts/modules/core/src/cluster/cluster.service.ts

After serverGroups are fetched from Clouddriver, `addNameParts()` runs:
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/cluster/cluster.service.ts#L40
The original behavior was to fetch server groups from Clouddriver. Then overwrite app/stack/detail by re-deriving them via the `NamingService` in Deck. The `NamingService` uses the Frigga conventions. In the case of the Kubernetes V2 provider, it was really messing things up. In particular the cluster view was never organized correctly. All server groups for all providers fetched from clouddriver should now have a moniker, I added a check just as an extra precaution.
I think that in the long run we will probably want to just rely on the moniker to determine app/stack/detail, but we can address that in another …

fix(moniker): Arrange cluster by moniker.cluster if available

---

app/scripts/modules/core/src/cloudProvider/versionedCloudProvider.service.spec.ts
app/scripts/modules/core/src/cloudProvider/versionedCloudProvider.service.ts
app/scripts/modules/core/src/instance/instance.states.ts

Allows the correct instance detail controller & template to be resolved from the instance state definition.
Basically reproduces the logic inside most of the instance details controllers for resolving an instance's account from instance id + cloud provider.
Shouldn't do anything different if your provider only has one version.

feat: resolve provider version in instance state

---

app/scripts/modules/core/src/cluster/filter/multiselect.model.js

When using multi-select on the cluster view page, monikers are not carried through with the server group information. This PR will fix it. I'm not exactly sure why only certain fields are mapped through from the server group model. It seems like IServerGroup should be used here, but I think that is a separate issue.

feat(moniker): Use server group moniker in multi-select
