app/scripts/modules/core/package.json

0.0.33:
* Update react-hybrid to 0.0.7
* UI for rolling red black strategy

chore(core): bump package version

---

app/scripts/modules/core/package.json

* add accountService, viewStateCache to ReactInjector
* add virtualized-select
* convert applicationComponent to React
* initialize variables on pipeline templates
* upgrade @types/react to 0.0.35
* app console feature

chore(core): bump version to 0.0.34

---

app/scripts/modules/amazon/package.json

chore(amazon): bump package to 0.0.18

---

app/scripts/modules/core/src/pipeline/config/templates/Variable.spec.tsx
app/scripts/modules/core/src/pipeline/config/templates/inputs/BooleanInput.tsx
app/scripts/modules/core/src/pipeline/config/templates/pipelineTemplate.module.ts
app/scripts/modules/core/src/pipeline/config/templates/pipelineTemplate.service.ts

@jrsquared or @anotherchrisberry

feat(pipeline_templates): adds boolean variable configuration type

---

app/scripts/modules/core/src/application/ApplicationComponent.tsx
app/scripts/modules/core/src/delivery/executionGroup/execution/Execution.tsx
app/scripts/modules/core/src/presentation/refresher/Refresher.tsx
app/scripts/modules/core/src/presentation/refresher/refresher.less

fix(core): Fix application refresher

---

app/scripts/modules/core/src/delivery/executions/executions.less

fix(core): fix scrolling regression on pipeline config

---

app/scripts/modules/core/package.json

feat(pipeline_templates): adds boolean variable configuration type
fix(core): Fix application refresher
feature(core): Add ability to override application icon
fix(core): Upgrade uirouter to fix initial page load
fix(core): fix scrolling on pipeline config view

chore(core): bump to 0.0.35

---

app/scripts/modules/core/package.json

* fix(core): avoid NPE rendering header for missing apps
* chore(core): convert notifierService to TS, export from core
* refactor(core): use common component for deploy initialization

chore(core): bump package to 0.0.37

---

app/scripts/modules/amazon/package.json

* allow default VPC specification when creating security groups

chore(amazon): bump package to 0.0.19

---

app/scripts/modules/core/package.json

* refactor: use pure CSS for sticky headers
* chore: upgrade to TS2.4
* fix: update account tag color on changes

chore(core): bump package to 0.0.38

---

app/scripts/modules/core/package.json

fix: preserve reset methods on settings reset calls

chore(core): bump version to 0.0.39

---

app/scripts/modules/google/src/gce.module.ts
app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/loadBalancer/configure/choice/loadBalancerTypeToWizardMap.constant.ts
app/scripts/modules/google/src/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/google/src/loadBalancer/configure/ssl/listener.html
app/scripts/modules/google/src/loadBalancer/configure/tcp/createLoadBalancerProperties.html
app/scripts/modules/google/src/loadBalancer/configure/tcp/gceCreateTcpLoadBalancer.controller.ts
app/scripts/modules/google/src/loadBalancer/configure/tcp/listener.html
app/scripts/modules/google/src/loadBalancer/details/loadBalancerDetail.controller.js
app/scripts/modules/google/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.directive.js
app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts

Mostly copy-paste from SSL Proxy code.

feat(provider/google): Support TCP Proxy Load Balancing

---

app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/core/src/confirmationModal/confirm.html
app/scripts/modules/core/src/confirmationModal/confirmationModal.controller.js
app/scripts/modules/core/src/securityGroup/securityGroupWriter.service.ts
app/scripts/modules/core/src/task/monitor/taskMonitor.builder.ts
app/scripts/modules/core/src/task/monitor/taskMonitor.html
app/scripts/modules/core/src/task/taskExecutor.ts

Depends on https://github.com/spinnaker/clouddriver/pull/1752

feat(provider/amazon): Add ability to delete dependent ingress rules when deleting security group

---

app/scripts/modules/core/package.json

fix(core): Fix refresher to show the actual current state

chore(core): bump package to 0.0.40

---

app/scripts/modules/amazon/package.json

feat(provider/amazon): Add ability to delete dependent ingress rules

chore(amazon): bump package to 0.0.20

---

app/scripts/modules/core/package.json

* fix(core): add margin between collapsed execution group headers 
* fix(core): update webhook stage scope on stage change

chore(core): bump package to 0.0.41

---

app/scripts/modules/core/package.json

fix(core): Fix activeState being null for application refresh

chore(core): bump package to 0.0.42

---

app/scripts/modules/amazon/package.json

* feat(provider/amazon): Support add/remove instance from target group 
* fix(provider/amazon): If ASG only has one target group, tag should say "target group"

chore(amazon): bump package to 0.0.21

---

app/scripts/modules/core/src/cluster/rollups.less

fix(core): Load balancers tag popup and runnings tasks popup show up under headers

---

app/scripts/modules/core/src/reactShims/react.uirouter.css

* fix the left side filter scrolling in firefox

fix(core/servergroup): fix filter scrolling on ffx

---

app/scripts/modules/core/package.json

* fix(core): fix filter scrolling on firefox
* fix(core): Load balancers tag popup and runnings tasks popup show up
* fix(core): Fix undefined error in ApplicationComponent

chore(core): bump package to 0.0.43

---

app/scripts/modules/amazon/package.json

* feat(amazon): implement target tracking policy support

chore(amazon): bump package to 0.0.22

---

app/scripts/modules/core/package.json

chore(core): add card-choices CSS classes

chore(core): bump package to 0.0.44

---

app/scripts/modules/amazon/package.json

* fix disableScaleIn flag on target tracking policy config

chore(amazon): bump package to 0.0.23

---

app/scripts/modules/amazon/package.json

fix build to omit react from library

chore(amazon): bump package to 0.0.24

---

app/scripts/modules/canary/canary/canaryStage.transformer.js

fix(canary): clean up formatting on exception message

---

app/scripts/modules/core/package.json

fix(core): provide valid ids for scrollTo clusters
fix(core): use flexbox for global header

chore(core): bump package to 0.0.46

---

app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
app/scripts/modules/core/src/search/infrastructure/infrastructure.html

* tagging widget commit erroneously removed the core infrastructure
search leaving no search feature present.  this re-adds it behind the
negation of the tagging widget feature flag.

chore(core/search): unbreak core inf searching

---

app/scripts/modules/core/src/loadBalancer/LoadBalancers.tsx

This fixes a react lifecycle error: `setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor).` by triggering global updates in componentDidMount instead of constructor.
In general, it seems like a good idea to move this sort of global data updates from the constructors and into `componentDidMount`
@anotherchrisberry @icfantv @jrsquared PTAL

fix(core/loadBalancers): Move initialization from constructor to componentDidMount

---

build.gradle

fix(apache2): lower bound apache2 version

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
app/scripts/modules/amazon/src/help/amazon.help.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/createApplicationLoadBalancer.controller.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/listeners.html
app/scripts/modules/amazon/src/loadBalancer/configure/common/configure.less
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/amazon/src/loadBalancer/targetGroup.less

Add the ability to add/remove custom rules to ALB listeners.

feat(provider/amazon): Add CRUD support for ALB listener rules

---

app/scripts/modules/kubernetes/serverGroup/configure/configuration.service.js

@lwander or @ethanfrogers please review.
Closes https://github.com/spinnaker/spinnaker/issues/1880.

fix(k8s): allow containers with similar image names to be selected

---

app/scripts/modules/docker/package.json

* feat(docker): allow expressions in dockerImageTagSelector

chore(docker): bump to 0.0.4

---

app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/amazon/src/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
yarn.lock

@spinnaker/netflix-reviewers PTAL

fix(aws): Change EBS optimized flag based on instance type

---

app/scripts/modules/google/src/instance/gceInstanceType.service.js
app/scripts/modules/google/src/serverGroup/configure/serverGroup.configure.gce.module.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.js
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html
app/scripts/modules/google/src/serverGroup/serverGroup.transformer.js

feat(gce): adds support for configuring multiple persistent disks

---

app/scripts/modules/amazon/src/loadBalancer/AmazonLoadBalancersTag.tsx
app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/loadBalancer/LoadBalancersTag.spec.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancersTag.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancersTagWrapper.tsx
app/scripts/modules/core/src/presentation/HoverablePopover.tsx

I started refactoring these to a single component, but dropped it because I ran out of time this week.

fix(core/loadBalancers): Fix z-index issues by converting load balancer list to a popover

---

app/scripts/modules/core/package.json

feat(CI/Jenkins): Add parameter type checking/mapped elements to Jenkins
feat(core): add new tagging widget
fix(core): fix alignment of copy-to-clipboard icon
fix(core/loadBalancers): Move initialization from constructor to componentDidMount
refactor(core): Reactify clusters view
fix(core/loadBalancers): Render LoadBalancerWrapper to switch components by provider
fix(core/loadBalancers): Fix z-index issues by converting load balancer tag to React

chore(core): bump package to 0.0.47

---

app/scripts/modules/amazon/package.json

feat(provider/amazon): Combine load balancers and target groups in the deploy dialog
fix(aws/loadbalancer): ensure timeout < interval
refactor(aws): convert sg details advanced settings view to React 
feat(provider/amazon): Add CRUD support for ALB listener rules
fix(aws): Change EBS optimized flag based on AWS defaults

chore(amazon): bump package to 0.0.25

---

app/scripts/modules/dcos/dcos.module.js
app/scripts/modules/dcos/loadBalancer/configure/configure.dcos.module.js
app/scripts/modules/dcos/loadBalancer/configure/wizard/basicSettings.html
app/scripts/modules/dcos/loadBalancer/configure/wizard/createWizard.html
app/scripts/modules/dcos/loadBalancer/configure/wizard/editWizard.html
app/scripts/modules/dcos/loadBalancer/configure/wizard/ports.controller.js
app/scripts/modules/dcos/loadBalancer/configure/wizard/ports.html
app/scripts/modules/dcos/loadBalancer/configure/wizard/resources.controller.js
app/scripts/modules/dcos/loadBalancer/configure/wizard/resources.html
app/scripts/modules/dcos/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/dcos/loadBalancer/details/details.controller.js
app/scripts/modules/dcos/loadBalancer/details/details.dcos.module.js
app/scripts/modules/dcos/loadBalancer/details/details.html
app/scripts/modules/dcos/loadBalancer/transformer.js

feat(provider/dcos): Add the DC/OS load balancer wizard

---

app/scripts/modules/core/src/loadBalancer/loadBalancerDataUtils.ts

@anotherchrisberry FYI @jrsquared

fix(core/loadBalancer): Filter nulls from loadbalancers list

---

app/scripts/modules/core/package.json

refactor(canary): convert canary scores component to React (#3999)

chore(core): bump package to 0.0.50

---

app/scripts/modules/openstack/pipeline/stages/bake/bakeStage.html
app/scripts/modules/openstack/pipeline/stages/bake/openstackBakeStage.js

@danielpeach this new one should be GTG

feat(openstack): Add advance options to openstack bake configuration

---

app/scripts/modules/core/package.json

* fix(pipelines): always show running executions and keep count in sync 
* fix(pipelines): do not exponentially load single execution details

chore(core): bump package to 0.0.51

---

app/scripts/modules/amazon/src/certificates/amazon.certificate.read.service.ts

Caching is turning out to be more trouble than it's worth - it typically takes less than a second to fetch and group the data.
@christopherthielen PTAL
@jrsquared FYI

fix(amazon): do not cache certificate data

---

app/scripts/modules/amazon/package.json

fix(amazon): do not cache certificate data

chore(amazon): bump package to 0.0.26

---

app/scripts/modules/core/src/canary/CanaryScores.tsx
app/scripts/modules/core/src/canary/canaryScores.component.ts

feat(canary): configurable help fields for canary scores component

---

app/scripts/modules/core/package.json

feat(canary): configurable help fields for canary scores component (#4007)
fix(pipeline_graph): sort graph nodes lexicographically by refId if refId is a string (#4012)

chore(core): bump package to 0.0.52

---

app/scripts/modules/core/src/delivery/create/ManagedTemplateSelector.tsx
app/scripts/modules/core/src/delivery/create/TemplateDescription.tsx
app/scripts/modules/kubernetes/help/kubernetes.help.ts
yarn.lock

Looks like this:
Also fixes linter issue.

feat(pipeline_templates): adds link to template json

---

package.json

Just throwing things at the wall to see if any of them stick

chore(core): update to latest yarn

---

app/scripts/modules/core/src/styleguide/src/styles/postcss.config.js

chore(core): fix build for styleguide

---

app/scripts/modules/core/src/widgets/accountRegionClusterSelector.component.js

fix(core): sort regions in account/region/cluster selector

---

app/scripts/modules/core/package.json

* fix(core): sort regions in account/region/cluster selector
* feat(core): include address in context for instance links
* feat(core): allow customization of manual judgment action labels

chore(core): bump version to 0.0.55

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/targetTracking/upsertTargetTracking.controller.ts

Depends on https://github.com/spinnaker/clouddriver/pull/1809

refactor(aws): consolidate scaling policy update operations

---

app/scripts/modules/amazon/package.json

* refactor(aws): consolidate scaling policy update operations

chore(amazon): bump package to 0.0.27

---

app/scripts/modules/core/package.json

* feat(core): replace marked with commonmark
* style(core): Add new spinner styles and a react component for spinner

chore(core): bump package to 0.0.56

---

app/scripts/modules/core/src/whatsNew/whatsNew.directive.modal.html

missed this in the commonmark conversion

fix(core): render whats new content as html

---

app/scripts/modules/core/package.json

fix(core): render whats new content as HTML

chore(core): bump package to 0.0.57

---

app/scripts/modules/amazon/package.json

* feat(amazon): make root volume size configurable on bake stage (netflix-only feature)
* feat(amazon): implement preferSourceCapacity flag in deploy config

chore(amazon): bump package to 0.0.29

---

app/scripts/modules/core/src/domain/ITrigger.ts
app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsub.trigger.ts
app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsubTrigger.html
app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js

Very basic UI for configuring pubsub triggers. Some improvements that will happen in the future:
* Suggest subscriptions configured in Echo (needs backend work first)
* Artifact filter support in the trigger configuration (needs a bunch of backend work first)

feat(gce/pubsub): Adds basic UI for configuring pubsub triggers.

---

app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx

I obviously tested this when I made the changes last week.

fix(core): fix rendering of manual judgment instructions

---

app/scripts/modules/amazon/src/help/amazon.help.ts
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/amazon/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
app/scripts/modules/amazon/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.js
app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.html

This is for https://github.com/spinnaker/spinnaker/issues/1076
Added spotPrice field to Advanced Settings in the Server Group wizard for AWS.
Related to https://github.com/spinnaker/orca/pull/1572 and https://github.com/spinnaker/clouddriver/pull/1833

feat(provider/aws): Added support for setting spot price

---

app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.ts
app/scripts/modules/core/src/chaosMonkey/chaosMonkeyConfig.component.ts
app/scripts/modules/core/src/chaosMonkey/chaosMonkeyExceptions.component.ts
app/scripts/modules/core/src/cluster/ClusterRuleMatcher.spec.ts
app/scripts/modules/core/src/cluster/ClusterRuleMatcher.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/core/src/widgets/cluster/clusterMatches.component.ts

Companion PR to https://github.com/spinnaker/orca/pull/1579
Consolidating the disparate cluster matching code, aligning it and including tests

feat(core): implement cluster matcher functionality

---

app/scripts/modules/ecs/ecs.module.js
app/scripts/modules/ecs/ecs.settings.ts
settings.js

feat(provider/ecs): Added default settings to the cloud provider registry
@anotherchrisberry @icfantv @jrsquared @christopherthielen

feat(provider/ecs): Added default settings to the cloud provider registry

---

app/scripts/modules/core/package.json

* fix(core/executions): Fix execution details reloading every refresh
* fix(core/delivery): Seatbelt for undefined on execution filter destroy
* fix(core): avoid accessing data source when not present or loaded 
* fix(core): fix rendering of manual judgment instructions
* refactor(core/delivery): Convert executions.transformer.service to TS
* feat(core): implement cluster matcher functionality
* refactor(core): De-angularify OrchestratedItemTransformer

chore(core): bump package to 0.0.59

---

app/scripts/modules/amazon/package.json

* feat(provider/aws): Added support for setting spot price
* feat(aws): add feature flag to disable spot price field

chore(amazon): bump package to 0.0.30

---

app/scripts/modules/core/package.json

* feat(pipelines): allow JSON editing of individual stages

chore(core): bump package to 0.0.61

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/webpack.config.js

fix(aws): fix markDirty call on target group removal in clone dialog

chore(aws): bump package to 0.0.32

---

app/scripts/modules/core/package.json

Attaching selectors to input types

chore(core): bump package to 0.0.64

---

app/scripts/modules/core/src/styleguide/public/styleguide.html
app/scripts/modules/core/src/styleguide/src/styles/spinners.css

Included how to use spinners in react and angular in the styleguide comments.

style(core/styleguide): Added snippets for react/angular consumption for spinners 

---

app/scripts/modules/core/package.json

style(infrastructure): Add new spinner to infrastructure search
style(spinner): Applying new spinner to global search
style(responsiveness): Main spinnaker nav header responsiveness

chore(core): bump package to 0.0.65

---

app/scripts/modules/core/src/search/widgets/search.component.ts

* adds quick and dirty support for searching by type.
We prefer small, well tested pull requests.

feat(search): add ability to search by type

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/overrideTimeout/overrideTimeout.directive.js

Updating deck to reflect new timeout behavior introduced in https://github.com/spinnaker/orca/pull/1605

fix(timeouts): updating help text to reflect new timeout behavior

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/LineChartHack.css
app/scripts/modules/core/src/pipeline/config/actions/history/showHistory.less

Not exciting, just fixing some issues that crept in with the style guide.

fix(style): fix small regressions on charts, history views

---

app/scripts/modules/core/src/delivery/create/CreatePipelineModal.tsx

* ensure the name input field has focus when the pipeline creation
dialog is opened.

fix(pipeline): auto focus input field

---

app/scripts/modules/core/src/domain/IExpectedArtifact.ts
app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/domain/ITrigger.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.html
app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/trigger.html
app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
app/scripts/modules/core/src/pipeline/config/validation/pipelineConfig.validator.ts
settings.js

Adds a section to pipeline config for declaring expected artifacts from trigger sources, and adds support in pub/sub triggers to select artifacts the trigger can produce.

feat(pipeline): Add pipeline config section for artifacts.

---

app/scripts/modules/core/src/pipeline/config/stages/optionalStage/optionalStage.directive.html

fix(pipelines): enlarge conditional expression input

---

halconfig/settings.js
yarn.lock

fix(halconfig): add missing comma in halconfig settings.js

---

yarn.lock

@duftler the auto-generated yarn.lock changes (https://github.com/spinnaker/deck/pull/4134) broke the build.

fix(build): revert yarn.lock changes

---

app/scripts/modules/core/package.json

* fix(core): Seatbelt optionalStage directive to make sure stage exists
* style(core): Found and replaced with closest colors for variables
* feat(pipeline): Add pipeline config section for artifacts
* fix(pipelines): fix back link when execution cannot be found
* fix(pipelines): enlarge conditional expression input
* fix(pipelines): refresh relative start time on interval
* refactor(cluster): allow cluster pod header to be customized
* fix(pipelines): show loading message while fetching version history

chore(core): bump package to 0.0.67

---

app/scripts/modules/core/package.json

* refactor(core/formsy): Refactor formsy, create react app-config saver (#4132)
* feat(core/application): Add 'autoActivate' toggle for DataSources (#4139)
* fix(search): add supplemental searching capability (#4133)

chore(core): bump package to 0.0.68

---

docker/spinnaker.conf.gen

apache spinnaker.conf add `ProxyPreserveHost On` to preserve host to gate

fix(docker) add ProxyPreserveHost On

---

app/scripts/modules/core/src/projects/ProjectSearchResultFormatter.ts
app/scripts/modules/core/src/search/searchResult/SearchResults.tsx

* update the project search result icon and remove unnecessary fixed
with font awesome class.

chore(search): update project icon

---

app/scripts/modules/core/src/bootstrap/angular.config.ts

Weird, I specifically remember removing that.
- other chris

chore(imports): remove unused import

---

app/scripts/modules/core/package.json
app/scripts/modules/core/webpack.config.js

* chore(search): update project icon
* fix(react): Do not suppress unhandled rejections in promises.
* Update Tooltip: Pipeline Config -> Property File
* chore(search): tweak CSS styles per feedback
* fix(travis) prefer complete buildInfoUrl over composing it.

chore(core): bump package to 0.0.70

---

app/scripts/modules/amazon/package.json

feat(provider/amazon): Show NLBs in the Load Balancer screen and allow NLB target groups to be selected when deploying

chore(amazon): bump package to 0.0.34

---

app/scripts/modules/kubernetes/pipeline/stages/runJob/runJobStage.js

surfacing the timeout option in the UI for run job
@lwander @anotherchrisberry PTAL

feat(kubernetes): surfacing timeout override for run job

---

app/scripts/modules/google/src/domain/backendService.ts
app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/loadBalancer/configure/common/commonCreateLoadBalancer.html
app/scripts/modules/google/src/loadBalancer/configure/common/commonEditLoadBalancer.html
app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.html
app/scripts/modules/google/src/loadBalancer/configure/ssl/backendService.html
app/scripts/modules/google/src/loadBalancer/configure/ssl/gceCreateSslLoadBalancer.controller.ts
app/scripts/modules/google/src/loadBalancer/configure/tcp/backendService.html
app/scripts/modules/google/src/loadBalancer/configure/tcp/gceCreateTcpLoadBalancer.controller.ts

feat(provider/gce): Support for connection draining in LBs.

---

app/scripts/modules/core/package.json

* fix(docs) Update Tooltip: Bake Configuration -> Base AMI
* fix(core): Fix undefined for getting length of commits
* chore(*): Re-enable source maps
* feat(core): Make HoverablePopover flip sides if there is not room
* feat(sourceMaps): Embed sources in sourcemaps for lib builds
* fix(projects): restore project header width to 100%
* fix(versionCheck): swallow exception if version.json fetch fails

chore(core): bump package to 0.0.71

---

settings-local.js
webpack.common.js

feat(core): adds settings-local.js

---

app/scripts/modules/amazon/src/instance/details/instanceDetails.html
app/scripts/modules/amazon/src/loadBalancer/configure/common/createLoadBalancerLocation.html
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/core/src/application/modal/newapplication.html
app/scripts/modules/core/src/bootstrap/spinnaker.component.ts
app/scripts/modules/core/src/delivery/executions/executions.html
app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.html
app/scripts/modules/core/src/notification/modal/editNotification.html
app/scripts/modules/core/src/pipeline/config/copyStage/copyStage.modal.html
app/scripts/modules/core/src/pipeline/config/pipelineConfig.html
app/scripts/modules/core/src/pipeline/config/preconditions/modal/editPrecondition.html
app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.html
app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.html
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/securityGroup/groupings.html
app/scripts/modules/core/src/serverGroup/details/scalingActivities/scalingActivities.html
app/scripts/modules/core/src/task/tasks.html
app/scripts/modules/oracle/instance/details/instanceDetails.html
app/scripts/modules/oracle/serverGroup/details/serverGroupDetails.html

Updated a bunch of spinners using "us-spinner" to use the new spinner ng component.

style(core/amazon/oracle): Updated spinners to use new designs

---

app/scripts/modules/core/src/search/infrastructure/infrastructureV2.controller.ts

* just set the title and don't try to get fancy with trying to figure
out a title based on the search filters.

fix(search): fix advanced search page title

---

app/scripts/modules/core/package.json

* fix(diff): Make sure jarDiffs has a default to prevent calling Object.keys
* feat(core): versioned cloud provider service
* feat(core/pipeline): Scroll grouped stages popover
* fix(pipeline_template): Cast numeric variable types during plan
* fix(stage): fix default timeout for deploy stage
* style(core/amazon/oracle): Updated spinners to use new designs 
* fix(pipelines): correctly re-render when editing JSON
* refactor(serverGroup): update server group writer to use moniker
* refactor(clusterMatch): tweak cluster match component args, export more components via library
* fix(search): fix advanced search page title

chore(core): bump package to 0.0.73

---

app/scripts/modules/amazon/package.json

* refactor(serverGroup): clone stage now uses moniker
* style(core/amazon/oracle): Updated spinners to use new designs

chore(amazon): bump package to 0.0.36

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

fix(pipelines): properly sync plan/pipeline/renderablePipeline

---

app/scripts/modules/openstack/subnet/subnetSelectField.directive.js

Cherry pick for release 1.4.2 from 
https://github.com/spinnaker/deck/commit/162909cbc8d993962829aa901746f1430b6a1258
@ajn0592 @edwinavalos FYI

Fix subnet selection box (#4124)

---

app/scripts/modules/core/package.json

fix(pipelines): properly sync plan/pipeline/renderablePipeline

chore(core): bump package to 0.0.74

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

fix(core/pipeline): Fix configure view state callback for MPT

---

app/scripts/modules/core/package.json

* fix(core/pipeline): Fix configure view state callback for MPT
* feat(pipeline): Change Artifact UI to use ExpectedArtifact model.
* feat(core): Versioned cloud provider deploy select
* style(all): Removed all less color variables and using CSS4 consolidated variables
* chore(search): update badge count label
* feat(core): Version account lookup
* refactor(core) naming service for sequence only uses moniker now
* fix(pipelines): show indicator when deleting pipeline config

chore(chore): bump package to 0.0.75

---

app/scripts/modules/amazon/package.json

* fix(provider/amazon) Enable & fix existing "Create LB" stage
* feat(provider/aws): Add help text to the LB internal checkbox
* fix(rollbacks): support for tolerating some instance failures

chore(amazon): bump package to 0.0.37

---

app/scripts/modules/core/src/naming/naming.service.spec.ts
app/scripts/modules/core/src/pipeline/config/actions/delete/deletePipelineModal.controller.spec.js

chore(tests): enable all tests

---

app/scripts/modules/amazon/package.json

* fix(amazon): properly assign credentials when editing load balancers

chore(amazon): bump package to 0.0.38

---

app/scripts/modules/core/package.json

* fix(executions): fix header alignment

chore(core): bump package to 0.0.77

---

app/scripts/modules/kubernetes/v2/manifest/manifestCommandBuilder.service.ts

Forgot I had this unstaged change before merging the manifest-deploy.
Sorry :x

fix(provider/kubernetes): Adds correct cloudprovider field

---

app/scripts/modules/core/package.json

* feat(script,jenkins): show contents of properties file
* feat(moniker): adds monikers to stages that includes cluster-selects

chore(core): bump package to 0.0.78

---

app/scripts/modules/amazon/package.json

* feat(moniker): adds monikers to stages that includes cluster-selects

chore(amazon): bump package to 0.0.39

---

app/scripts/modules/core/package.json

* fix(core/http): retry http calls failing due to network issues
* fix(core/modal): avoid throwing errors on modal $dismiss

chore(core): bump package to 0.0.79

---

app/scripts/modules/core/package.json

fix(network): include backoff, max number of retries in network recovery

chore(core): bump package to 0.0.80

---

app/scripts/modules/core/package.json

* fix(core): catch modal dismiss
* chore(core): Remove some old files and convert a test to ts
* feat(core): Version server group transformer delegate
* feat(pipelines): use textarea for expression entry

chore(core): bump package to 0.0.81

---

app/scripts/modules/amazon/package.json

* feat(amazon): clarify naming/description on create load balancer/security group

chore(amazon): bump package to 0.0.40

---

app/scripts/modules/core/package.json

* refactor(core): convert create pipeline to react
* fix(core): catch dismiss of confirmation/cancel modals

chore(core): bump package to 0.0.83

---

app/scripts/modules/kubernetes/v1/kubernetes.v1.module.js
app/scripts/modules/kubernetes/v2/kubernetes.v2.module.ts

fix(kubernetes): fix template loading

---

app/scripts/modules/kubernetes/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/v2/serverGroup/IKubernetesServerGroup.ts
app/scripts/modules/kubernetes/v2/serverGroup/details.controller.ts
app/scripts/modules/kubernetes/v2/serverGroup/details.html

spinnaker/spinnaker#1902
spinnaker/spinnaker#1995

feat(provider/kubernetes): V2 server group details

---

app/scripts/modules/core/package.json

* fix(core/datasource): Possibly unhandled rejection: undefined
* refactor(core): Convert ExecutionStatus to react
* refactor(core/search): Remove client-side fetch of server groups
* feat(search): add server groups to clusters

chore(core): bump package to 0.0.84

---

app/scripts/modules/amazon/package.json

* refactor(aws): make transformScalingPolicy method public

chore(amazon): bump package to 0.0.41

---

app/scripts/modules/core/src/delivery/status/ExecutionStatus.spec.tsx
app/scripts/modules/core/src/delivery/status/ExecutionStatus.tsx

@christopherthielen @anotherchrisberry

fix(core): Fix rendering executions that have JSON in the parameters

---

app/scripts/modules/core/package.json

* refactor(aws): make transformScalingPolicy method public
* refactor(core): Convert executions to react
* fix(pipelines): add validator to webhook stage "method" field
* fix(core): Fix rendering executions that have JSON in the parameters

chore(core): Bump module to 0.0.85

---

app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts

fix(appengine): allow non-default accounts in deploy dialogue

---

app/scripts/modules/core/src/diffs/viewChangesLink.component.ts
app/scripts/modules/core/src/entityTag/entitySource.component.ts

`finally` is different from `catch`

fix(core): catch exceptions on server group source when pipeline 404s

---

app/scripts/modules/amazon/src/loadBalancer/configure/common/createAmazonLoadBalancer.controller.ts
app/scripts/modules/core/src/domain/ILoadBalancer.ts
app/scripts/modules/core/src/loadBalancer/loadBalancer.write.service.ts

Adds monikers to load balancers, create/edit stages and tasks

feat(moniker) - adding monikers to load balancers

---

app/scripts/modules/core/package.json

* fix(core): Fix configure pipeline links when details is open
* fix(core): catch exceptions on server group source when pipeline 404s
* refactor(core): Convert executionDetailsSectionNav, executionStepDetails, etc.

chore(core): bump package to 0.0.86

---

app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/appengineEditLoadBalancerStage.ts
settings.js

chore(appengine): remove edit load balancer feature flag

---

app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/appengine/serverGroup/transformer.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/core/src/storage/index.ts
app/scripts/modules/core/src/storage/storageAccount.service.ts

Also select between git and GCS during a GAE deploy, and select a storage account accordingly.

feat(provider/gae): Specify artifact in GAE deploy from GCS.

---

app/scripts/modules/kubernetes/loadBalancer/configure/wizard/advancedSettings.html
app/scripts/modules/kubernetes/loadBalancer/details/details.html

fixes spinnaker/spinnaker#2035

feat(provider/kubernetes): Enable setting of labels on k8s Service objects #2035

---

app/scripts/modules/core/package.json

* chore(package): update uirouter libs to latest
* feat(entitytags): Show replaced server group details in popover
* fix(core): render reason as HTML in tasks view
* refactor(core/delivery): Convert ExecutionDetails to react

chore(core): bump package to 0.0.87

---

app/scripts/modules/core/package.json

* chore(core/amazon): make moniker changes library-friendly

chore(core): bump package to 0.0.88

---

app/scripts/modules/amazon/package.json

* feat(moniker) - adding monikers to load balancers
* feat(moniker) - adding monikers to the deploy stage
* feat(provider/amazon): Rollback support for PREVIOUS_IMAGE strategy

chore(amazon): bump package to 0.0.42

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/core/package.json
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.spec.ts

changing the declared interface of the command instead of trying to wedge the entire application into the command

fix(core/amazon): fix application name on server group command

---

app/scripts/modules/core/src/cluster/filter/clusterFilter.component.html
app/scripts/modules/core/src/cluster/filter/clusterFilter.component.ts
app/scripts/modules/core/src/cluster/filter/clusterFilter.model.ts
app/scripts/modules/core/src/cluster/filter/clusterFilter.service.ts
app/scripts/modules/core/src/domain/ISecurityGroup.ts
app/scripts/modules/core/src/filterModel/filter.model.service.js
app/scripts/modules/core/src/loadBalancer/filter/loadBalancer.filter.component.html
app/scripts/modules/core/src/loadBalancer/filter/loadBalancer.filter.component.ts
app/scripts/modules/core/src/loadBalancer/filter/loadBalancer.filter.service.ts
app/scripts/modules/core/src/loadBalancer/filter/loadBalancerFilter.model.ts
app/scripts/modules/core/src/securityGroup/filter/securityGroup.filter.component.html
app/scripts/modules/core/src/securityGroup/filter/securityGroup.filter.component.ts
app/scripts/modules/core/src/securityGroup/filter/securityGroup.filter.service.js
app/scripts/modules/core/src/securityGroup/filter/securityGroupFilter.model.ts
app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts

We've had requests for this periodically over the past couple of years.

feat(core): add detail filter to cluster/lb/sg views

---

app/scripts/modules/amazon/package.json

* feat(amazon): Add load balancer dns name to target group details
* fix(amazon/loadBalancer): Modify shouldComponentUpdate to allow for more specific updates
* fix(core/amazon): don't show copy capacity options for create/clone server group
* feat(rrb): Allow for specifying pipelines to run before disable

chore(amazon): bump package to 0.0.44

---

app/scripts/modules/core/package.json

* fix(core/loadBalancer): Modify shouldComponentUpdate to allow for more specific updates
* fix(core/loadBalancer): Actually check for all the changes to props
* refactor(core/delivery): Convert waitExecutionDetails to react
* fix(core): Navigate to the first stage if passed in stage does not exist
* feat(core): add detail filter to cluster/lb/sg views

chore(core): bump package to 0.0.90

---

app/scripts/modules/core/package.json

* refactor(*): Remove duplicate execution details templates
* fix(core/pipeline): Show errors in time window stage execution details

chore(core): Bump core to 0.0.91

---

app/scripts/modules/amazon/package.json

* refactor(*): Remove duplicate execution details templates

chore(amazon): bump to 0.0.45

---

webpack.common.js

`halconfig.js` needs to come after `vendor.js`
@lwander FYI

fix(core): Fix webpackJsonp not being defined for local dev

---

app/scripts/modules/core/package.json

* fix(core): handle spel expressions in map editors
* refactor(*): More execution details refactoring
* fix(core/executions): adjust padding on status glyph

chore(core): bump package to 0.0.93

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js

fix(amazon): do not set useSourceCapacity on clones

---

app/scripts/modules/amazon/package.json

* fix(amazon): do not set useSourceCapacity on clones

chore(amazon): bump package to 0.0.46

---

app/scripts/modules/core/src/delivery/service/executions.transformer.service.ts

fix(core): Fix groups from breaking executions view

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/scalingPolicySummary.component.less
app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/pipeline/config/preconditions/preconditionList.directive.less
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.html
app/scripts/modules/core/src/pipeline/config/templates/Variable.less
app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/search/searchResult/baseTable.less

`word-break: break-word` doesn't work in Firefox. This is probably better? It may cause other problems, which I am excited about.

fix(core): replace word-break CSS with overflow-wrap

---

app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/serverGroup/pod/runningTasksPopover.html
app/scripts/modules/core/src/serverGroup/pod/runningTasksTag.directive.js
app/scripts/modules/core/src/serverGroup/pod/runningTasksTag.html

fix(core/runningTasks): Use popover so z-index is above all other elements

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/scalingPolicySummary.component.less
app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/pipeline/config/preconditions/preconditionList.directive.less
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.html
app/scripts/modules/core/src/pipeline/config/templates/Variable.less
app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/search/searchResult/baseTable.less

Rolling back all but one of the changes in https://github.com/spinnaker/deck/commit/abfbb321fd7656168e9986fa02f903ab91c05779, which turn out to have been misguided.

fix(core): revert word-break/overflow-wrap swaps

---

app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts

I added help text because the labels were starting to look lonely.

feat(provider/kubernetes): surface stack & detail

---

app/scripts/modules/core/package.json

* refactor(core/pipeline): Convert a few execution source details to react
* fix(core/runningTasks): Use popover so z-index is above all other elements
* fix(core): revert word-break/overflow-wrap swaps

chore(core): bump package to 0.0.95

---

app/scripts/modules/amazon/package.json

* fix(amazon): Traffic should be enabled when choosing a non-custom strategy

chore(amazon): bump package to 0.0.48

---

app/scripts/modules/core/package.json

* refactor(core/pipeline): Convert *AsgExecutionDetails to react
* refactor(core/pipeline): Convert *ClusterExecutionDetails to react
* feat(pipeline_template): Better support for templated pipelines
* fix(core/projects): restore refresh icon, set app name on init
* refactor(core/pipeline): Refactor execution window and manual judgment
* fix(core): omit exception message on stopped manual judgment stages
* chore(style/header): tweak the pixels
* refactor(*/pipeline): Convert clone server group execution details to react

chore(core): bump package to 0.0.96

---

app/scripts/modules/amazon/package.json

* refactor(*/pipeline): Convert clone server group execution details to react

chore(amazon): bump package to 0.0.49

---

app/scripts/modules/core/package.json

* revert pipeline_template changes from #4288

chore(core): bump package to 0.0.97

---

app/scripts/modules/core/src/pipeline/config/stages/executionWindows/ExecutionWindowActions.tsx
app/scripts/modules/core/src/pipeline/config/stages/shrinkCluster/ShrinkClusterExecutionDetails.tsx

fix(core/pipeline): Fix a couple undefined errors in execution details

---

app/scripts/modules/core/src/manifest/manifestWriter.service.ts
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/IManifestCoordinates.ts
app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.html
app/scripts/modules/kubernetes/src/v2/serverGroup/details/IKubernetesServerGroup.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html

https://github.com/spinnaker/orca/pull/1774
https://github.com/spinnaker/clouddriver/pull/2082
spinnaker/spinnaker#1902

feat(provider/kubernetes): v2 manifest delete ctrl

---

package.json

chore(core): update node/npm/yarn versions

---

app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/IKubernetesLoadBalancer.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html

spinnaker/spinnaker#1902
spinnaker/spinnaker#1995

feat(provider/kubernetes): v2 lb details

---

app/scripts/modules/core/src/instance/instance.states.ts

chore(*): placate linter

---

app/scripts/modules/core/src/pipeline/config/actions/history/showHistory.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/src/pipeline/config/services/pipelineConfig.service.ts

Endpoint is already there, just never got wired into the UI

fix(core): enable history comparison for strategies

---

app/scripts/modules/amazon/src/pipeline/stages/resizeAsg/resizeAsgStepLabel.html
app/scripts/modules/core/src/delivery/details/StageFailureMessage.tsx

feat(core): Link to failing synthetic stage rather than "No reason provided."

---

app/scripts/modules/core/package.json

* fix(core/pipeline): Fix a couple undefined errors in execution details
* fix(core): support failed health status style
* chore(core): update node/npm/yarn versions
* feat(core): Versioned provider load balancer
* fix(moniker): Arrange cluster by moniker.cluster if available
* feat: resolve provider version in instance state
* fix(core): enable history comparison for strategies
* feat(moniker): Use server group moniker in multi-select
* feat(core): Link to failing synthetic stage rather than "No reason provided"

chore(core): bump package to 0.0.98

---

halconfig/settings.js

Add canary feature flag to enable halyard to manage canary feature for deployment
Update halconfig/settings.js with feature from settings.js for canary configuration.

chore(halconfig): Allow canary to be enabled

---

app/scripts/modules/core/package.json

* feat(core): resolve provider version for standalone instances
* fix(core): Link to child executions when no error messages available

chore(core): bump package to 0.0.99

---

app/scripts/modules/canary/acaTask/acaTaskStage.js

Not sure how that slipped past Travis...

fix(canary): fix syntax in acaTask stage

---

app/scripts/modules/ecs/ecs.help.ts

feat(provider/ecs): Added help texts for ECS module
@anotherchrisberry @icfantv @jrsquared @christopherthielen

feat(provider/ecs): Added help texts for ECS module

---

app/scripts/modules/core/src/delivery/details/StageFailureMessage.tsx

Deep linking with `stageId` is far more consistent
than attempting to calculate stage and step offsets.

fix(core): Favor using `stageId` when building links to failed stages

---

app/scripts/modules/core/src/pipeline/config/stages/disableCluster/DisableClusterExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/config/stages/scaleDownCluster/ScaleDownClusterExecutionDetails.tsx

Eventually this duplication should be pulled out, but for now...

fix(core): Fix a few more undefined errors from execution details conversions

---

app/scripts/modules/core/package.json

fix(core): re-enable filter on (none) for stack/detail

chore(core): bump package to 0.0.101

---

app/scripts/modules/kubernetes/src/securityGroup/configure/wizard/upsert.controller.js
app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.js

if you had multiple provider accounts confiured, editing security groups
didn't work as it wasn't setting things up properly.

fix(provider/kubernetes): fix security group edit

---

app/scripts/modules/kubernetes/src/v2/instance/details/IKubernetesInstance.ts
app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/instance/details/details.html
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts

feat(provider/kubernetes): v2 adds instance details

---

app/scripts/modules/core/src/deploymentStrategy/strategies/redblack/additionalFields.html

feat(core): Support delay before scale down when red/black'ing

---

app/scripts/modules/core/package.json

* feat(pipeline_template): Better support for templated pipelines with dynamic sources
* fix(*): Fix disable cluster execution details config
* feat(core): Support delay before scale down when red/black'ing

chore(core): bump package to 0.0.102

---

app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/domain/IServerGroupManager.ts
app/scripts/modules/core/src/serverGroupManager/serverGroupManager.module.ts
app/scripts/modules/core/src/serverGroupManager/serverGroupManager.service.ts

feat(core): server group manager module, service, and typings

---

webpack.common.js

feat(build): add env variable for setting.js location

---

app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/edit/editManifestWizard.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestWizard.html
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html

feat(provider/kubernetes): edit manifest in details view

---

app/scripts/modules/core/package.json

* feat(core): server group manager module, service, and typings
* feat(core): server group manager data source, states, and kubernetes details
* chore(core): update to latest webpack (3.8.1)
* chore(*): Updgrade lodash-decorators to get named functions for bindAll
* feat(core): allow pipeline parameters to be required
* feat(core): server group manager button on server group pod
* fix(core): hide jenkins failure message when controller not initialized

chore(core): bump package to 0.0.104

---

app/scripts/modules/amazon/package.json

* fix(aws): fall back to naming service on clone stage

chore(amazon): bump package to 0.0.50

---

app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.html
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.html
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.js

enhance run job stage by moving configuration into a modal and
reorganizing things into sections. this makes it less crowded as we
start introducing more options from the pod spec.

enhance(provider/kubernetes): runJob stage

---

app/scripts/modules/amazon/package.json

* feat(amazon): Allow for enabling of a partially disabled server group

chore(amazon): bump package to 0.0.51

---

app/scripts/modules/core/package.json

* refactor(core/search): Create consts for ISearchResultTypes and individual search components
* feat(core/search): Add health counts to server groups search results

chore(core): bump package to 0.0.105

---

app/scripts/modules/core/package.json

* fix(core/pipeline): Fix a couple undefined errors in execution details
* refactor(core/pagerduty): Convert bits to TS, support multiple applications, other stuff

chore(core): Bump to 0.0.106

---

app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerTag.tsx

feat(core): server group manager styles

---

app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts

chore(kubernetes): Placate linter

---

app/index.deck
app/scripts/modules/core/src/cloudProvider/versionedCloudProvider.service.spec.ts
app/scripts/modules/core/src/cloudProvider/versionedCloudProvider.service.ts
app/scripts/modules/core/src/domain/IDeckRootScope.ts
app/scripts/modules/core/src/loadBalancer/loadBalancer.states.ts
app/scripts/modules/core/src/serverGroup/serverGroup.states.ts
app/scripts/modules/core/src/serverGroupManager/serverGroupManager.states.ts

fix(core): fix race condition in versioned cloud provider

---

app/scripts/modules/core/src/notification/notificationList.directive.html
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/presentation/main.less

refactor(core/presentation): Refactor footer css to be reusable

---

app/scripts/modules/core/src/manifest/manifestWriter.service.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.html
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(provider/kubernetes): scale modal

---

app/scripts/modules/kubernetes/src/container/ports.component.html
app/scripts/modules/kubernetes/src/container/ports.component.js
app/scripts/modules/kubernetes/src/container/resources.component.html
app/scripts/modules/kubernetes/src/container/resources.component.js
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.html

add support for more of the Pod spec within the Run Job stage. also adds
a couple new components that could be dropped in to replace what is
currently in the container configurer.

feat(provider/kubernetes): runJob more fields

---

app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts

feat(provider/kubernetes): make it clear that stack/detail are optoinal

---

app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.js

fix lint issues from the last few round of runjob prs
ping @danielpeach

fix(provider/kubernetes): fix lint issues

---

package.json
yarn.lock

Extensively tested in one place in the UI

chore(core): update to jquery-ui 1.12

---

app/scripts/modules/core/src/delivery/details/ExecutionDetailsSectionNav.tsx

Had to switch to calling $state directly because the react --> angular --> react wasn't updating the UIRouterContext...

fix(core/delivery): Fix jumping to same type stage when clicking details sections

---

app/scripts/modules/core/package.json

* fix(moniker): sort server groups by sequence if possible
* fix(core): add space between icon and label on create pipeline button
* feat(core/search): tweak styles on v2 search
* fix(core/delivery): Fix jumping to same type stage when clicking details

chore(core): bump package to 0.0.108

---

app/scripts/modules/core/src/delivery/details/StageFailureMessage.tsx
app/scripts/modules/core/src/delivery/service/executions.transformer.service.ts
app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
app/scripts/modules/core/src/task/monitor/taskMonitorError.component.js
app/scripts/modules/core/src/task/tasks.html
app/scripts/modules/core/src/task/tasks.less

WIP - do not merge, depends on spinnaker/orca#1799

feat(locking): error message rendering for cluster locking failures

---

app/scripts/modules/core/src/domain/IManifest.ts
app/scripts/modules/core/src/domain/index.ts
app/scripts/modules/core/src/manifest/index.ts
app/scripts/modules/core/src/manifest/manifestReader.service.ts
app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(provider/kubernetes): surface manifest stability

---

app/scripts/modules/kubernetes/src/v2/manifest/status/status.component.ts

trailing whitespace lint error
@lwander FYI

chore(provider/kubernetes): Fix lint

---

app/scripts/modules/kubernetes/src/securityGroup/configure/wizard/upsert.controller.js

lint was complaining about an unused function which should have been
used.
@danielpeach or @anotherchrisberry

fix(provider/kubernetes): fix sg lint

---

app/scripts/modules/core/package.json

* fix(core): omit moniker when caching security groups

chore(core): bump package to 0.0.111

---

app/scripts/modules/core/src/delivery/executions/Executions.tsx

fix(core): add space on Start Manual Executions button

---

app/scripts/modules/core/src/manifest/manifestWriter.service.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/pause.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/pause.html
app/scripts/modules/kubernetes/src/v2/manifest/rollout/resume.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/resume.html
app/scripts/modules/kubernetes/src/v2/manifest/status/status.component.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(manifest): more status banners

---

app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts

closes https://github.com/spinnaker/spinnaker/issues/1967

feat(core): versioned security group create

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts

feat(artifact): docker artifact

---

app/scripts/modules/kubernetes/src/instance/details/details.controller.js
app/scripts/modules/kubernetes/src/instance/details/details.html

add access to pod logs in v1 provider
Clouddriver PR: https://github.com/spinnaker/clouddriver/pull/2162
@lwander @danielpeach PTAL.

feat(provider/kubernetes): v1 pod logs

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/instance/details/details.html
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/status/condition.component.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(provider/kubernetes): surface shared "conditions"

---

app/scripts/modules/kubernetes/src/v2/manifest/rollout/undo.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/undo.html
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(provider/kubernetes): v2 surface rollout revision details

---

app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.controller.js
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.html

when making the switch to multi-container jobs, i forgot to update the
execution details

fix(provider/kubernetes): fix runJob exec details

---

app/scripts/modules/core/src/authentication/authentication.interceptor.service.ts
app/scripts/modules/core/src/bootstrap/bootstrap.module.ts
app/scripts/modules/core/src/insight/insight.module.ts
app/scripts/modules/core/src/instance/instance.write.service.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/core/src/utils/timeFormatters.ts

Fixed some typings preventing building of the `@spinnaker/core` module.
```bash
cd app/scripts/modules/core
yarn lib
```

fix(core): typings

---

app/scripts/modules/core/package.json

* fix(core): add space on Start Manual Executions button
* feat(core): versioned security group create
* feat(artifact): docker artifact
* refactor(*): Convert find ami execution details to react
* refactor(core): Convert script stage execution details to react
* chore(*): Update typescript and tslint and fix lint errors
* fix(core): Fix details panel cutoff at smaller sizes
* fix(core): avoid NPE if security group cache does not exist
* refactor(core/pipeline): Consolidate everything from /delivery into /pipeline
* refactor(core/pipeline): Rename StageDetails to StepExecutionDetails
* refactor(core/pipeline): Rename ExecutionDetails to StageExecutionDetails
* fix(core): typings

chore(core): Bump to 0.0.112

---

app/scripts/modules/kubernetes/src/v2/serverGroup/serverGroupTransformer.service.ts

@jrsquared whoops, i missed one 😞

fix(kubernetes): fixed typing

---

app/scripts/modules/core/package.json

* fix(core/pipeline): Fix unhandled rejections with the pipeline graph
* feat(core): Add a pagerDuty read service, tag, and select field

chore(core): Bump to 0.0.113

---

app/scripts/modules/core/package.json

* perf(core/executions): consider pipeline filters when fetching executions
* feat(core): console output jump to end
* fix(core/executions): trigger filter collapse correctly

chore(core): bump package to 0.0.115

---

app/scripts/modules/amazon/package.json

* fix(provider/amazon): Tags not copied when cloning ASG

chore(amazon): bump package to 0.0.52

---

app/scripts/modules/kubernetes/package.json

chore(kubernetes): bump npm package version

---

app/scripts/modules/core/src/pipeline/config/stages/core/StepExecutionDetails.tsx

Hopefully this lowers the transition aborted errors...

fix(core/pipeline): De-duplicate state transitions for execution details

---

app/scripts/modules/core/package.json

* fix(core/pipeline): Pipeline graph overflow in firefox
* fix(*/loadBalancer): Fix server group show/hide control
* fix(*/loadBalancer): Fix a few undefined errors with load balancers
* fix(core/pipeline): Fix undefined edge case in ScriptExecutionDetails
* fix(core/pipeline): De-duplicate state transitions for execution details

chore(core): bump to 0.0.116

---

app/scripts/modules/amazon/package.json

* fix(*/loadBalancer): Fix server group show/hide control
* fix(*/loadBalancer): Fix a few undefined errors with load balancers
* fix(amazon/loadBalancer): Edit load balancers in the context of the application they were created in/with

chore(amazon): bump to 0.0.53

---

app/scripts/modules/core/package.json

* fix(core): reduce starting instance animations
* refactor(core/pipeline): Convert singleExecutionDetails to react

chore(core): bump package to 0.0.117

---

app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/instance/Instances.tsx

inline-block is not great for multiline chunks, derp

fix(core): use inline element for instance groups

---

app/scripts/modules/core/package.json

* fix(core): use inline element for instance groups

chore(core): bump package to 0.0.118

---

app/scripts/modules/core/src/pipeline/config/stages/group/groupStage.ts
app/scripts/modules/core/src/pipeline/service/executions.transformer.service.ts

fix(core): prevent adding group stages, handle rendering gracefully

---

app/scripts/modules/core/package.json

* fix(core): prevent adding group stages, handle rendering gracefully

chore(core): bump package to 0.0.119

---

app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/hiddenMetadataKeys.value.js
app/scripts/modules/google/src/serverGroup/configure/wizard/zones/regionalSelector.directive.html
app/scripts/modules/google/src/serverGroup/configure/wizard/zones/zoneSelector.directive.html

Depends on https://github.com/spinnaker/clouddriver/pull/2201.

feat(gce): UI for zone selection.

---

app/scripts/modules/amazon/package.json

* feat(amazon): Support passing a capacity constraint during resize

chore(amazon): bump package to 0.0.54

---

app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/core/src/artifact/artifact.module.ts
app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
app/scripts/modules/core/src/artifact/index.ts
app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

feat(provider/kubernetes): deploy manifest from artifact

---

app/scripts/modules/core/package.json

* refactor(core/pipeline): Cleanup time boundary sorting/comparison
* fix(core/task): Do not show tasks link if no application associated with task
* refactor(core/entityTags): retrieve tags by application
* fix(core/pipelines): rerender view when first stage is removed

chore(chore): bump package to 0.0.120

---

app/scripts/modules/core/src/styleguide/public/styleguide.html
app/scripts/modules/core/src/styleguide/src/public/styleguide.html
app/scripts/modules/core/src/styleguide/src/styleguide-template/template.ejs

Plus, with all the whitespace my IDE removed, this should significantly reduce the package size

fix(core/styleguide): remove black header from style guide template

---

app/scripts/modules/kubernetes/src/v2/manifest/edit/editManifestWizard.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts

Fixes this bug: https://github.com/spinnaker/spinnaker/issues/2108

fix(provider/kubernetes): Fixed incorrect duplication upon edit.

---

app/scripts/modules/core/package.json

* feat(core): Add aliases to application config
* fix(core/styleguide): remove black header from style guide template

chore(core): Bump to 0.0.121

---

app/scripts/modules/core/package.json

* fix(core/executions): do not auto-refresh manual judgment stages

chore(core): bump package to 0.0.122

---

app/scripts/modules/core/package.json

* feat(core/pipeline): Expose "Override stage timeout" UI for Pipeline

chore(core): Bump to 0.0.123

---

app/scripts/modules/core/src/pipeline/config/stages/core/executionSummary.html

This is an `@`, not a `=` binding

fix(core/analytics): send correct stage label

---

app/scripts/modules/docker/package.json

* fix(docker): disable manual execution until tag selected

chore(docker): bump package to 0.0.6

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.html
app/scripts/modules/kubernetes/src/v2/manifest/scale/scaleSettingsForm.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestLabelSelector.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestSelector.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/labelEditor/labelEditor.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/selector.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/resizeManifest/resizeManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/resizeManifest/resizeManifestConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/resizeManifest/resizeManifestStage.ts

Adds delete and resize manifest stages:

feat(provider/k8sv2): Delete/Resize manifest stage

---

app/scripts/modules/kubernetes/src/v2/manifest/selector/selector.component.ts

@danielpeach As per your request.

fix(provider/k8s-v2): Add field label to 'name'/'labels' toggle

---

app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.html
app/scripts/modules/kubernetes/src/v2/manifest/rollout/pause.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/pause.html
app/scripts/modules/kubernetes/src/v2/manifest/rollout/resume.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/resume.html
app/scripts/modules/kubernetes/src/v2/manifest/rollout/undo.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/undo.html
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scale.html

https://github.com/spinnaker/orca/pull/1852

fix(provider/k8s-v2): Use 'manifestName' in place of 'name' in adhoc operations

---

app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/gcs.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts

feat(artifacts): github artifact helper

---

app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/scale/scaleSettingsForm.component.js
app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestLabelSelector.js
app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestSelector.js
app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestStage.ts

https://github.com/spinnaker/spinnaker/issues/2179
https://github.com/spinnaker/clouddriver/pull/2237

feat(provider/kubernetes): dynamic rollback stage

---

app/scripts/modules/core/src/domain/IArtifact.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionConfig.html
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/pipeline.module.ts

feat(artifacts): find artifact from execution

---

app/scripts/modules/core/src/search/infrastructure/SearchResult.tsx

Sometimes these have HTML in them.

fix(core): allow HTML in search result display

---

app/scripts/modules/core/package.json

- feat(artifacts): find artifact from execution (#4593)
- feat(provider/aws): Pipeline support for rolling back a cluster (#4590)
- feat(core/pipelines): add jitter to exec windows (#4598)
- fix(core): allow HTML in search result display (#4600)

chore(core): bump to 0.0.125

---

app/scripts/modules/amazon/package.json

- feat(provider/aws): Pipeline support for rolling back a cluster (#4590)

chore(amazon): bump to 0.0.57

---

webpack.common.js

https://github.com/spinnaker/spinnaker/issues/2199

fix(build): fixes settings-local load for non-local builds

---

app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/artifact/artifact.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/showManifestYaml.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts

feat(kubernetes): deployed yaml in pipeline

---

app/scripts/modules/core/package.json

* feat(core): Set custom parameters using the UI
* fix(core): add cluster level tags to server groups
* fix(core): Fixes issue where jquery-ui was not correctly loaded by webpack
* fix(core/pipeline): Fix execution graph of groups when MPT partial contains a single stage
* fix(core/pipeline) Check to see if .stage.restrictedExecutionWindow exists
* fix(core/reactShims): Add catch block to reactShims state.go() calls
* fix(core): keep restrict execution checkbox checked if it's set
* fix(all): change deprecated babel preset es2015 to preset-env
* style(core): Pods CSS bug fix + addition of bold variants to type
* fix(all): update spinners
* fix(core/search): Fix redirect from 'home.infrastructure' to 'home.search'
* chore(package): upgrade uirouter/visualizer to 5.1.3
* fix(core): remove …

chore(core): bump package to 0.0.126

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

https://github.com/spinnaker/spinnaker/issues/2225

feat(provider/kubernetes): v2 rename required deployed artifacts

---

app/scripts/modules/core/package.json

* fix(core): allow side filters to be collapsed
* feat(core): enable highlighting of invalid pristine fields

chore(core): bump package to 0.0.127

---

app/scripts/modules/ecs/serverGroup/configure/wizard/verticalScaling/verticalScaling.component.html
app/scripts/modules/ecs/serverGroup/configure/wizard/verticalScaling/verticalScaling.component.js
app/scripts/modules/ecs/serverGroup/configure/wizard/verticalScaling/verticalScaling.html

feat(provider/ecs): Added vertical scaling section to deploy modal

feat(provider/ecs): Added vertical scaling section to deploy modal

---

app/scripts/modules/ecs/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
app/scripts/modules/ecs/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.js
app/scripts/modules/ecs/serverGroup/configure/wizard/advancedSettings/advancedSettings.html

feat(provider/ecs): Added advancedSettings section to deploy modal

feat(provider/ecs): Added advancedSettings section to deploy modal

---

app/scripts/modules/ecs/serverGroup/details/serverGroupDetails.ecs.controller.js
app/scripts/modules/ecs/serverGroup/details/serverGroupDetails.html
app/scripts/modules/ecs/serverGroup/details/serverGroupDetails.module.ts

feat(provider/ecs): Added Server group details view

feat(provider/ecs): Added Server group details view

---

app/scripts/modules/ecs/logo/ecs.logo.less

feat(provider/ecs): Updated the ECS logo less file

feat(provider/ecs): Updated the ECS logo less file

---

app/scripts/modules/ecs/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.html
app/scripts/modules/ecs/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.ts
app/scripts/modules/ecs/serverGroup/configure/wizard/loadBalancers/loadBalancers.html

feat(provider/ecs): Added LoadBalancers section to deploy modal

feat(provider/ecs): Added LoadBalancers section to deploy modal

---

app/scripts/modules/ecs/serverGroup/configure/wizard/templateSelection/templateSelection.html

feat(provider/ecs): Added template selection view

feat(provider/ecs): Added template selection view

---

app/scripts/modules/ecs/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/ecs/serverGroup/details/rollback/rollbackServerGroup.html

feat(provider/ecs): Added Rollback menu option

feat(provider/ecs): Added Rollback menu option

---

app/scripts/modules/ecs/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
app/scripts/modules/ecs/serverGroup/configure/wizard/location/basicSettings.html

feat(provider/ecs): Added Location section to deploy modal

feat(provider/ecs): Added Location section to deploy modal

---

app/scripts/modules/ecs/placementStrategy/IPlacementStrategy.ts
app/scripts/modules/ecs/placementStrategy/PlacementStrategy.ts
app/scripts/modules/ecs/placementStrategy/placementStrategy.service.ts

feat(provider/ecs): Added Placement strategy service

feat(provider/ecs): Added Placement strategy service

---

app/scripts/modules/ecs/serverGroup/details/resize/resizeCapacity.component.html
app/scripts/modules/ecs/serverGroup/details/resize/resizeCapacity.component.ts
app/scripts/modules/ecs/serverGroup/details/resize/resizeServerGroup.controller.js
app/scripts/modules/ecs/serverGroup/details/resize/resizeServerGroup.html

feat(provider/ecs): Added Resize server group menu option

feat(provider/ecs): Added Resize server group menu option

---

app/scripts/modules/ecs/ecsCluster/EcsCluster.ts
app/scripts/modules/ecs/ecsCluster/IEcsCluster.ts
app/scripts/modules/ecs/ecsCluster/ecsCluster.read.service.ts

feat(provider/ecs): Added an ECS Cluster reader

feat(provider/ecs): Added an ECS Cluster reader

---

app/scripts/modules/ecs/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/ecs/serverGroup/configure/serverGroupConfiguration.service.ts

feat(provider/ecs): Added the ServerGroup Configuration Service

feat(provider/ecs): Added the ServerGroup Configuration Service

---

app/scripts/modules/ecs/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
app/scripts/modules/ecs/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.js
app/scripts/modules/ecs/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.html

feat(provider/ecs): Added horizontal scaling section to deploy modal

feat(provider/ecs): Added horizontal scaling section to deploy modal

---

app/scripts/modules/ecs/metricAlarm/MetricAlarm.ts
app/scripts/modules/ecs/metricAlarm/metricAlarm.read.service.ts

feat(provider/ecs): Added MetricAlarms reader

feat(provider/ecs): Added MetricAlarms reader

---

app/scripts/modules/ecs/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js

feat(provider/ecs): Added CloneServerGroup.ecs.controller

feat(provider/ecs): Added CloneServerGroup.ecs.controller

---

app/scripts/modules/ecs/instance/details/instance.details.controller.js
app/scripts/modules/ecs/instance/details/instanceDetails.html

feat(provider/ecs): Added instance details view

feat(provider/ecs): Added instance details view

---

app/scripts/modules/ecs/pipeline/stages/disableAsg/disableAsgStage.html
app/scripts/modules/ecs/pipeline/stages/disableAsg/disableAsgStepLabel.html
app/scripts/modules/ecs/pipeline/stages/disableAsg/ecsDisableAsgStage.js

feat(provider/ecs): Added Disable ASG stage

feat(provider/ecs): Added Disable ASG stage

---

app/scripts/modules/ecs/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js
app/scripts/modules/ecs/serverGroup/configure/wizard/serverGroupWizard.html

feat(provider/ecs): Added ServerGroup Wizard

feat(provider/ecs): Added ServerGroup Wizard

---

app/scripts/modules/ecs/ecs.help.ts

feat(provider/ecs): Updated the ECS help file

feat(provider/ecs): Updated the ECS help file

---

app/scripts/modules/ecs/iamRoles/IRole.ts
app/scripts/modules/ecs/iamRoles/iamRole.read.service.ts

feat(provider/ecs): Added IAM role reader to ECS
@anotherchrisberry @jrsquared @christopherthielen

feat(provider/ecs): Added IAM role reader to ECS

---

app/scripts/modules/ecs/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/ecs/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js

Cleaning up linting, import issues

fix(ecs): clean up imports, method signature

---

app/scripts/modules/core/src/task/tasks.html

This has been broken for some time, probably?

fix(core): fix link to deployed server group in tasks view

---

app/scripts/modules/core/package.json

* feat(deck) - Add gitlab as a gitSource
* fix(core): handle execution window expressions gracefully
* fix(core/pipelines): do not show no pipelines message while initializing
* fix(core): fix link to deployed server group in tasks view
* perf(core): lazy load data for load balancers, security groups

chore(core): bump package to 0.0.128

---

app/scripts/modules/ecs/serverGroup/serverGroup.transformer.spec.ts
app/scripts/modules/ecs/serverGroup/serverGroup.transformer.ts

feat(provider/ecs): Added serverGroup Transformer stage

feat(provider/ecs): Added serverGroup Transformer

---

app/scripts/modules/ecs/ecs.module.js

feat(provider/ecs): Updated the ECS Module with all its content

feat(provider/ecs): Updated the ECS Module with all its content

---

app/scripts/modules/core/package.json

* fix(core): remove lazy datasource config on security groups, load balancers

chore(core): bump package to 0.0.129

---

app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/index.ts

feat(provider/kubernetes): export k8s server group interface

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
app/scripts/modules/kubernetes/package.json

chore(provider/kubernetes): bump kubernetes package version

---

app/scripts/modules/amazon/package.json

- feat(amazon/serverGroup): warn that scaling policies will not work when capacity is pinned

chore(amazon): bump package to 0.0.59

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts

fix(webhooks): default parameters to empty list

---

app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx

That div was an artifact of debugging...

refactor(core): remove redundant div from cluster pod wrapper

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/loadBalancer/details/LoadBalancerActions.tsx

* replace old spinners with new spinners
* fix(amazon/loadBalancer): Show region and account when deleting a load balancer
* refactor(amazon/loadBalancer): Make load balancer actions button a react dropdown

chore(amazon): bump package to 0.0.60

---

app/scripts/modules/core/package.json

* feat(webhooks): preconfigured webhook params
* fix(core): fix restore to this version behavior on pipeline config
* fix(core/vis): Fix visualizer toggle to clean up old copies of the visualizer
* fix(core/search): Fix instance searches
* fix(webhooks): default parameters to empty list
* fix(core/presentation): Add padding to filter sidebar as a scrolling affordance
* fix(core): surface app data status in views without active states
* refactor(core): misc spinner updates
* fix(core/search): Fix calling setState on unmounted RecentlyViewedItem
* refactor(core/search): Refactor Search V2
* refactor(core/search): Use router state to drive search results
* refactor(core/search): Reactify SearchV2
* perf(core/clusters): use ReactVirtualized to render clusters
* refactor(core): Remove unused …

chore(core): bump package to 0.0.130

---

app/scripts/modules/core/package.json

* fix(core): use small loader instead of nano on task monitor
* fix(core): reset cluster measure cache when groups update

chore(chore): bump package to 0.0.133

---

app/scripts/modules/amazon/package.json

* fix(amazon): show load balancer actions menu

chore(amazon): bump package to 0.0.61

---

app/scripts/modules/core/src/account/AccountTag.tsx

fix(core/account): Fix account tag color rendering during scroll/filter operation

---

package.json
yarn.lock

chore(kayenta): bump deck-kayenta version

---

app/scripts/modules/core/src/authentication/userMenu/userMenu.directive.spec.js
app/scripts/modules/core/src/forms/checklist/checklist.directive.spec.js
app/scripts/modules/core/src/forms/checkmap/checkmap.directive.spec.js
app/scripts/modules/core/src/forms/mapEditor/mapEditor.component.spec.js
app/scripts/modules/core/src/forms/numberList/numberList.component.spec.ts
app/scripts/modules/core/src/pipeline/config/stages/core/stageConfigField/stageConfigField.directive.spec.js
app/scripts/modules/core/src/pipeline/config/stages/overrideTimeout/overrideTimeout.directive.spec.js
app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.directive.spec.js
app/scripts/modules/core/src/whatsNew/whatsNew.directive.spec.js
app/scripts/modules/core/src/widgets/spelText/spelText.decorator.js
package.json
yarn.lock

There's a huge list of breaking changes! One of them was `.size()` is gone and replaced with `.length`.

chore(core): upgrade jQuery to 3.3.1

---

app/scripts/modules/core/src/styleguide/src/styles/buttons.css

Added disabled states for buttons. Added button groups.
Button groups offer a container where button can be arranged with default margins. The last button does not have any margins.

style(styleguide): Disabled state for buttons + button groups

---

app/scripts/modules/core/src/entityTag/entityTags.dataSource.ts

Sometimes these data sources are never ready

fix(core): handle load failures in entityTags datasource

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html

Fix the broken new spinner which was used instead of cog inside saving... button in pipelines.
Reverting back to cog. Will update it with newer spinner pattern from Jeremy when its available.

style(pipeline): Fix for the broken spinner

---

app/scripts/modules/core/src/styleguide/public/styleguide.html

fix(core): Add styleguide.html back since it breaks the docker build

---

app/scripts/modules/amazon/package.json

* fix(core/amazon): wrap spinner size in quotes

chore(amazon): bump package to 0.0.62

---

app/scripts/modules/core/package.json

* feat(core): Create a react modal wizard
* fix(core/account): Fix account tag color rendering during scroll/filter
* feat(styleguide): Added disabled states for button + a button group for buttons
* fix(core): handle load failures in entityTags datasource
* fix(core/amazon): wrap spinner size in quotes
* fix(core): reverting to cogs for the pipeline saving button

chore(core): bump package to 0.0.134

---

app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html

feat(provider/appengine): Container deploy w/ free url or artifact

---

app/scripts/modules/kubernetes/src/container/configurer.directive.html
app/scripts/modules/kubernetes/src/container/volumes.component.html
app/scripts/modules/kubernetes/src/container/volumes.component.js
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts

https://github.com/spinnaker/clouddriver/pull/2316
https://github.com/spinnaker/spinnaker/issues/2082

feat(provider/kubernetes): v1 subpath UI support

---

app/scripts/modules/amazon/package.json

* feat(amazon): Convert create load balancer modal to react

chore(amazon): Bump to 0.0.63

---

app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/trigger.html
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

Adding additional tool tips for kubernetes v2 provider.

docs(provider/kubernetes) - Adding additional tool tips for kubernetes v2 provider

---

app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx

fix(core): Improved pipeline template tooltip copy

---

app/scripts/modules/core/package.json

* feat(core): Indicate templated pipelines
* fix(core): Improved pipeline template tooltip copy
* feat(core/reactShims): Add angularJS template/controller adapter
* feat(core): Add support for react versions of stage details
* fix(core): append pipeline dropdown to body
* style(all): Added grids to the main container of the app
* refactor(core): convert instance list body to React

chore(core): bump package to 0.0.136

---

app/scripts/modules/core/package.json

fix(core/instance): Make navigating to instance details work agai

chore(chore): bump package to 0.0.137

---

app/scripts/modules/core/src/search/index.ts

To be able to use it from e.g. the customized deck

fix(core/search): Export the new GlobalSearch react component

---

app/scripts/modules/amazon/src/loadBalancer/TargetGroupDetails.tsx
app/scripts/modules/amazon/src/loadBalancer/targetGroup.states.ts
app/scripts/modules/core/src/application/ApplicationComponent.tsx
app/scripts/modules/core/src/application/ApplicationIcon.tsx
app/scripts/modules/core/src/application/config/ApplicationConfig.tsx
app/scripts/modules/core/src/application/config/appConfig.states.ts
app/scripts/modules/core/src/application/config/applicationConfig.view.html
app/scripts/modules/core/src/insight/insight.less
app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
app/scripts/modules/core/src/instance/instance.states.ts
app/scripts/modules/core/src/loadBalancer/LoadBalancerDetails.tsx
app/scripts/modules/core/src/loadBalancer/loadBalancer.states.ts
app/scripts/modules/core/src/securityGroup/SecurityGroupDetails.tsx
app/scripts/modules/core/src/securityGroup/securityGroup.states.ts
app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerDetails.tsx
app/scripts/modules/core/src/serverGroupManager/serverGroupManager.states.ts

- Application Config
- Application Icon
- Target Group Details
- Load Balancer Details
- Instance Details
- Security Group Details
- Server Group Manager Details

feat(details): Migrate the following to use the @Overridable() decorator

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html

This is dependent on spinnaker/orca#1924 so don't merge until that's in I guess.

feat(dryrun): added a checkbox to let users dry run pipelines

---

app/scripts/modules/core/package.json

* feat(core/search): Require 3 chars for global search, move to React
* fix(pipelines): Fix polling for manual execution
* fix(pipelines/help): Explain when concurrent pipelines get canceled
* feat(core): allow hidden (but enable-able) data sources
* fix(details): allow details dropdowns to wrap (at smaller widths)
* fix(core): allow multiselect toggling on instance checkbox click
* feat(core/overrideRegistry): Add react component decorators
* feat(details): Migrate some overrides to @Overridable() decorator
* fix(core): eagerly fetch more than one cluster grouping pod
* refactor(core): limit calls to /credentials
* feat(dryrun): added a checkbox to let users dry run pipelines

chore(core): bump package to 0.0.138

---

app/scripts/modules/kubernetes/src/v2/manifest/showManifestYaml.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/showManifestYaml.html

fix(provider/kubernetes): Remove a trailing 'for' from title in show manifest modal

---

app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.spec.js

feat(dryrun): made dry run a flag on the trigger rather than a different type

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.module.ts

Missing a BindAll, some imports got dropped

fix(amazon): restore server group actions

---

app/scripts/modules/amazon/package.json

* fix(amazon): restore server group actions

chore(amazon): bump package to 0.0.65

---

app/scripts/modules/amazon/package.json

refactor(amazon/loadBalancer): Pull out load balancer create type since it is generic

chore(amazon): bump package to 0.0.66

---

app/scripts/modules/core/package.json

feat(core/search): Consolidate search registries and v1/v2 data fetching (#4775)
fix(core): restore auto-scroll on deep linked server group render (#4776)
fix(core): Fix missing wizard section labels (#4778)
refactor(core/search): Clean up GlobalSearch, make state mgmt. way less flaky (#4760)
fix(core/loadBalancer): Fix create load balancer button for multiple providers.
fix(core): avoid flickering scrollbars in clusters view (#4774)
fix(rxjs): switch RxJS deep imports to `import { Foo } from 'rxjs'` (#4772)
fix(core): shrink tag marker to fit better in cluster header (#4773)
feat(core/application): reactify applications search (#4759)
fix(core/search): Remove angular2react bridging of native react component (#4763)
fix(core): handle challengeDestructiveActions being undefined in API …

chore(core): Bump module to 0.0.140

---

app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
app/scripts/modules/core/src/search/infrastructure/infrastructure.states.ts
app/scripts/modules/core/src/search/searchResult/SearchResultGrid.tsx
app/scripts/modules/core/src/search/searchResult/SearchResults.tsx

fix(core/search): Select first search tab with >0 results, if no tab is already selected.

---

Dockerfile

chore(docker): Upgrade base image (#2298)

---

app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestAnnotations.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestLabels.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestLabels.less
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html

feat(provider/kubernetes): useful UI metadata

---

app/scripts/modules/kubernetes/src/v2/manifest/manifestLabels.component.ts

chore(linter): missed " inplace of '

---

app/scripts/modules/core/src/presentation/main.less

Added a few overrides for react select to match spinnaker select design specs.

style(core): Styling react-select to match spinnaker select

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html

https://github.com/spinnaker/spinnaker/issues/2304
With multiple manifests it's helpful to delineate here

feat(provider/kubernetes): provide name of deployed manifest

---

.gitignore
app/scripts/modules/core/src/domain/IArtifact.ts
app/scripts/modules/core/src/domain/IExecutionTrigger.ts
app/scripts/modules/core/src/pipeline/status/ArtifactList.spec.tsx
app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
app/scripts/modules/core/src/pipeline/status/artifactList.less

https://github.com/spinnaker/spinnaker/issues/2299

feat(provider/kubernetes): List trigger artifacts in execution status

---

app/scripts/modules/core/src/serverGroup/serverGroup.transformer.js

@lwander FYI since your name is on this bit...

fix(core/serverGroup): Fallback to no providerVersion if user does not have account permission

---

app/scripts/modules/core/src/styleguide/src/styles/layers.css

Added comments to include variable names for each one of the layers to use without selectors.

style(core/styleguide): Displaying usage info for layers in styleguide

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.spec.ts

fixes release build
https://github.com/spinnaker/deck/pull/4832

fix(core): add authorized field to test accounts

---

app/scripts/modules/core/src/account/account.service.ts

fix(core/accounts): fix versioned account lookup (#4837)

---

app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelection.service.spec.ts
app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelection.service.ts
app/scripts/modules/core/src/domain/IStageTypeConfig.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.spec.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts

fixes https://github.com/spinnaker/spinnaker/issues/2277
- Hide excluded provider icons in stage selection dropdown
- Hide excluded providers from provider selection modal
Excluded provider appears as an Add Server Group option.
No Modal Appears

fix(core/stages): Hide excluded providers

---

app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html

fix(provider/appengine): server group wizard: gcs "storage account" -> "artifact account"

---

app/scripts/modules/core/package.json

* fix(core): add authorized field to test accounts
* fix(core/accounts): fix versioned account lookup
* fix(core): avoid scrollbars in cluster pod header
* feat(core/pipelines): allow triggering of execution via deep link
* fix(core/stages): Hide excluded providers
* refactor(core/filterModel): Refactor filter.model.service to Typescript
* refactor(core): convert security group filter service to TS
* fix(core): allow overflow on details panel for menus

chore(core): bump package to 0.0.149

---

app/scripts/modules/amazon/src/loadBalancer/configure/common/SecurityGroups.tsx

fix(amazon/loadBalancers): Remove clear all from security group select

---

app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts

Before / After
fixes https://github.com/spinnaker/spinnaker/issues/2346

fix(provider/kubernetes): hide stages in applications with only k8s v2 account

---

app/scripts/modules/core/src/domain/IStageTypeConfig.ts
app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
app/scripts/modules/core/src/pipeline/pipeline.module.ts
app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.js
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts

feat(artifacts): allow specific stages to 'produce' artifacts

---

app/scripts/modules/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx

fix(amazon): make security groups in server group details links

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/core/src/account/account.service.spec.ts
app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
app/scripts/modules/ecs/serverGroup/configure/serverGroupConfiguration.service.ts

fix(core/overrideRegistry): Handle Override component synchronously, when possible

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts

Particularly useful with https://github.com/spinnaker/clouddriver/pull/2380

feat(kubernetes): Surfacing timeout override for Deploy (Manifest)

---

app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/FindArtifactFromExecutionExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts

https://github.com/spinnaker/spinnaker/issues/2342

fix(artifacts): show artifact execution config

---

app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/FindArtifactFromExecutionExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts

fix(artifacts): show artifact execution config (#4870)

---

app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
app/scripts/modules/core/src/application/service/applicationDataSource.ts
app/scripts/modules/core/src/cluster/ClusterPod.tsx
app/scripts/modules/core/src/cluster/DefaultClusterPodTitle.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancer.tsx
app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
app/scripts/modules/core/src/serverGroup/details/ServerGroupDetails.tsx

after successfully editing an entity tag, the modal shows an error message. This is due to an incorrect this binding for the `onUpdate` callbacks.
I added arrow functions in the react code.  I also added `@BindAll` on the `ApplicationDataSource` class to catch the same scenario from angularjs code.  I tried fixing it the "right" way but got lost trying to make sense of angularjs "&" binding

fix(core/entityTag): Fix error message after successful entity tag updates

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts

1.6.x cherry-pick of https://github.com/spinnaker/deck/pull/4879

fix(provider/kubernetes): delete action broken for all but server groups

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts

fix(provider/kubernetes): add type to manifestController resolver funcs

---

app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
app/scripts/modules/core/src/presentation/ModalService.tsx

fix(core/presentation): Fix react modal wrapper

---

app/scripts/modules/core/package.json

* feat(core/angular): Improve error message when angular module dep is undefined
* fix(core/healthCounts): Propagate css class to health counts
* fix(core/overrideRegistry): Handle Override component synchronously
* fix(core/entityTag): Fix error message after successful entity tag upsert
* refactor(core/presentation): Change how ReactModal works
* fix(core/presentation): Fix react modal wrapper
* feat(core): update permissions help text to include warning about caching
* feat(core/executions): allow pipeline rerun with same parameters

chore(core): bump package to 0.0.151

---

app/scripts/modules/amazon/package.json

* feat(amazon/loadBalancer): Export react load balancer components
* fix(amazon): make security groups in server group details links

chore(amazon): bump package to 0.0.75

---

app/scripts/modules/core/package.json

* fix(core/overrideRegistry): Use account name (not id) when choosing override
* fix(core/pipeline): Fix pipeline config - add stage that uses BaseProvider
* fix(core/reactShims): Fix first render when receiving props before $state is set

chore(core): bump package to 0.0.152

---

app/scripts/modules/openstack/src/securityGroup/configure/wizard/upsert.controller.js

fix(openstack): add missing semicolon

---

app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/core/src/cache/cacheInitializer.service.spec.ts
app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js

This reverts commit 3d01879bcce983f1950175bb77baf254807d07c9.
The issue this patch fixed was not present in release-1.6.x so we're rolling it back.

Revert "fix(core/pipeline): Fix pipeline config - add stage that uses BaseProviderStageCtrl (#4885) (#4891)"

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts

feat(kubernetes): Surfacing timeout override for Deploy (Manifest) (#4871)

---

app/scripts/modules/core/src/application/config/dataSources/applicationDataSourceEditor.component.html
app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.html
app/scripts/modules/core/src/pipeline/config/actions/delete/deletePipelineModal.html
app/scripts/modules/core/src/pipeline/config/actions/rename/renamePipelineModal.html
app/scripts/modules/core/src/pipeline/config/triggers/jenkins/jenkinsTriggerOptions.directive.html
app/scripts/modules/core/src/pipeline/config/triggers/travis/travisTriggerOptions.component.html
app/scripts/modules/core/src/serverGroup/details/scalingActivities/scalingActivities.html
app/scripts/modules/docker/src/pipeline/trigger/dockerTriggerOptions.directive.html

* the nano spinner is a block-level element, so it looks off in buttons (we've already fixed this in a few places; this fixes the rest of them)
* the nano spinner is also a little too small in the other places in this PR

style(core): replace nano spinners on inline buttons

---

app/scripts/modules/core/package.json

* style(all): Updated references to styleguide package
* fix(core): allow grouping by time on cancelled executions
* style(core): replace nano spinners on inline buttons
* fix(core/pipelines): force data refresh on pipeline creation

chore(core): bump package to 0.0.153

---

app/scripts/modules/google/src/pipeline/stages/resizeAsg/gceResizeAsgStage.js

fix(provider/google): add resize stage timeout override

---

app/scripts/modules/core/src/overrideRegistry/Overridable.tsx

Should enable something like this:
```
@Overrides('other.component')
class Custom extends React.Component {
render() {
const { OriginalComponent, ...props } = this.props;
return (
<h3>Custom header</h3>
<OriginalComponent {...props}/>
)
}
}
```

feat(core/overrideRegistry): Pass the original component to the overriding component as a prop

---

app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts

Before:
After: no error & artifact removed.

fix(artifacts): removing artifact from 'produces artifacts' throws exception

---

app/scripts/modules/core/src/overrideRegistry/Overridable.tsx

not even @christopherthielen is above the law

style(core): wrap Overridable expressions in parens

---

app/scripts/modules/core/package.json

* refactor(core): Remove formsy; replace-ish with formik
* feat(core) add a help menu with links to docs and community
* feat(core/pipelines): allow user-friendly labels on pipeline parameters
* feat(core/cluster): Allow task matchers to be configured from deck-customized
* style(core): postioned the entity notifications to the right
* feat(core/overrideRegistry): Pass the original component to the override

chore(core): bump package to 0.0.155

---

app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsub.trigger.ts
app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsubTrigger.html

feat(pubsub): specify run-as-user for pubsub triggers

---

app/scripts/modules/core/package.json

feat(pubsub): specify run-as-user for pubsub triggers (#4918)

chore(core): bump package to 0.0.156

---

app/scripts/modules/amazon/src/loadBalancer/configure/common/SecurityGroups.tsx
app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
app/scripts/modules/core/src/modal/wizard/WizardPage.tsx
app/scripts/modules/core/src/modal/wizard/modalWizard.less

 feat(amazon/loadBalancers): Disable create button until security groups are loaded

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.spec.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts

fixes https://github.com/spinnaker/spinnaker/issues/2470

fix(provider/kubernetes): manifests array nests itself on save

---

app/scripts/modules/core/package.json

* feat(core/wizard): Support a waiting state for sections
* chore(core): add analytics to recently viewed items
* Making sure styleguide renders in deck
* fix(core/instance): Update InstanceDetails when props change
* fix(core/pipelines): force refresh pipeline configs after save completes

chore(core): Bump to 0.0.157

---

app/scripts/modules/amazon/package.json

* fix(amazon/loadBalancers): Stop showing stale data in load balancer edit dialog
* feat(amazon/loadBalancers): Disable create button until security groups are loaded
* feat(aws): allow setting the target type for target groups

chore(amazon): Bump to 0.0.76

---

app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestSelector.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/selector.component.ts

fixes https://github.com/spinnaker/spinnaker/issues/2459

fix(provider/kubernetes): Undo Rollout stage incorrectly fails validation when "kind" is present

---

app/scripts/modules/google/src/address/address.reader.ts
app/scripts/modules/google/src/backendService/backendService.reader.js
app/scripts/modules/google/src/certificate/certificate.reader.ts
app/scripts/modules/google/src/healthCheck/healthCheck.read.service.ts

fix(provider/gce): Fix call to list backends

---

app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/pipeline/config/parameters/parameter.html
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html

A boring implementation of https://github.com/spinnaker/deck/pull/4942 with no web workers or eval

feat(core): allow parameters to be hidden based on other params

---

app/scripts/modules/core/package.json

* feat(core): allow parameters to be hidden based on other params
* feat(core): allow custom warning when users skip an execution window

chore(core): bump package to 0.0.160

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx

fix(amazon/loadBalancer): Validate target group name when region/account changes

---

app/scripts/modules/amazon/package.json

* fix(amazon/loadBalancer): Validate target group name when region/account changes

chore(amazon): Bump to 0.0.79

---

app/scripts/modules/core/package.json

* chore(core/pagerDuty): Add status to IPagerDutyService

chore(core): Bump to 0.0.161

---

app/scripts/modules/core/src/application/search/Applications.tsx

Closes https://github.com/spinnaker/spinnaker/issues/2508

fix(core/application): fix scrolling of applications list

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

fix(core/application): fix scrolling of applications list
feat(core/serverGroup): Refactor to smaller components and make them Overridable (#4941)
feat(goats): goats

Bump core to 0.0.162 and amazon to 0.0.80

---

app/scripts/modules/core/src/naming/naming.service.spec.ts
app/scripts/modules/core/src/naming/naming.service.ts

feat(core): remove 'N/A' if no server group sequence exists

---

app/scripts/modules/core/src/presentation/forms/components/ExpressionInput.tsx
app/scripts/modules/core/src/presentation/forms/index.ts
app/scripts/modules/core/src/presentation/forms/spel2js.templateParser.ts

@christopherthielen I like this so much now I want to export it

feat(core): expose spel evaluator in spinnaker/core

---

app/scripts/modules/core/package.json

* fix(core/overrideRegistry): fix lint error
* fix(core/pipelines): fixed a spinner that was off
* feat(core): remove 'N/A' if no server group sequence exists
* feat(core): expose spel evaluator in spinnaker/core

chore(core): bump package to 0.0.164

---

app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/additionalFields.html
app/scripts/modules/core/src/help/help.contents.ts

feat(rollback): Support rollback on failure for Rolling Red/Black

---

app/scripts/modules/core/package.json

* fix(pipeline_templates): prevent [object Object] when object's default value is provided
* fix(core/entityTag): Fix background colors of notification categories
* feat(core/presentation): Add margin selector for flex-container-h layout
* fix(core/presentation): Increase specificity of flex-pull-right
* feat(core/serverGroup): Use flexbox instead of bootstrap grid to lay out running tasks
* feat(rollback): Support rollback on failure for Rolling Red/Black
* fix(core): omit colon if there is no server group sequence

chore(core): bump package to 0.0.165

---

app/scripts/modules/docker/src/pipeline/trigger/dockerTriggerOptions.directive.js

This is similar to the fix in https://github.com/spinnaker/echo/pull/219

fix(triggers): Pass image as an artifact when using Docker trigger

---

app/scripts/modules/core/src/pipeline/config/stages/core/executionSummary.html
app/scripts/modules/core/src/pipeline/details/stageSummary.component.ts

Addresses the comment in https://github.com/spinnaker/spinnaker/issues/2005#issuecomment-372429960

feat(core): allow markdown in stage-level comments

---

app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.ts

feat(core/pipeline): Allow overriding of default timeout for "Script stage" from UI

---

app/scripts/modules/core/package.json

* feat(core/pipeline): Allow overriding of default timeout for "Script Stage"
* fix(core): avoid rendering wizard pages before they have registered

chore(core): bump package to 0.0.167

---

app/scripts/modules/core/src/entityTag/notifications/NotificationsPopover.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancersTag.spec.tsx
app/scripts/modules/core/src/presentation/HoverablePopover.tsx

feat(core/entityTag): Close entity tag popover when delete/edit is clicked
refactor(core/presentation): Refactor some JSX to standalone components

feat(core/presentation): Provide `hidePopover()` prop to popover contents component

---

app/scripts/modules/core/package.json

feat(core): adds ability to define a dockerInsight link (#4994)
feat(core/presentation): Provide `hidePopover()` prop to popover contents component (#4992)
feat(core/entityTag): Close entity tag popover when delete/edit is clicked
refactor(core/presentation): Refactor some JSX to standalone components

chore(core): bump package to 0.0.168

---

app/scripts/modules/core/src/pipeline/executionBuild/ExecutionBuildLink.tsx

This broke...some time ago? Fixing it with the new trigger structure.

fix(core): fix build link to parent pipeline

---

app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.html
app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js

Not very nice to overwrite people's expressions...

fix(core): allow expressions in pipeline stage application field

---

app/scripts/modules/core/src/pipeline/details/StageFailureMessage.tsx

- Displays a warning if stage didnt fail

feat(core): Support warning message type for stages

---

app/scripts/modules/core/package.json

* feat(core): omit unsupported cloud provider data from clusters
* fix(core): fix build link to parent pipeline
* fix(core/help): Allow target="_blank" in links in help popover
* fix(core): allow expressions in pipeline stage application field
* fix(core): ensure stage comments are in string format
* feat(core): Support warning message type for stages

chore(core): bump package to 0.0.169

---

app/scripts/modules/amazon/package.json

* refactor(amazon/core): move targetHealthyPercentage component to core
* feat(amazon/serverGroup): Change default capacity constraint to off

chore(amazon): bump package to 0.0.82

---

app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/replicas.html

Hello, I'm new to Spinnaker.
This PR will enable `use source capacity` for kubernetes in deploy stage which was implemented at  https://github.com/spinnaker/clouddriver/pull/1817
I tested this patch under GKE 1.9.3.

feat(kubernetes): Expose use source capacity for deploy (#2543)

---

app/scripts/modules/amazon/src/serverGroup/details/sections/ScheduledActionsDetailsSection.tsx

Fixes a regression from #4742. FYI @jrsquared

fix(amazon/serverGroups): Unable to open "Edit Scheduled Actions" modal

---

app/scripts/modules/core/package.json

refactor(core/task+amazon/common): Reactify UserVerification and AwsModalFooter #5015
fix(core): count down remaining time in wait stage details

chore(core): bump package to 0.0.170

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts

fix(amazon/serverGroup): Add spelLoadbalancers to IAmazonServerGroupCommand

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.less
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/defaultBase64.artifact.ts

fixes https://github.com/spinnaker/spinnaker/issues/2526
With invalid input:

feat(artifacts): Support embedded/base64 artifact type

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

* fix(core/pipeline): Fix closing of "new pipeline" modal using X or Cancel buttons
* fix(tooltip): updating conditional on expression tooltip
* feat(artifacts): Support embedded/base64 artifact type
* fix(bake): Fix JavaScript error on bake stage load
* chore(core): upgrade to font-awesome 5
* fix(core): do not render application list if all are filtered out
* fix(artifacts): remove unreachable error markup
* fix(amazon/loadBalancers): Disable editing target group names
* fix(amazon/loadBalancers): Don't allow to create if duplicate target group names

chore(core/amazon): bump core to 0.0.171, amazon to 0.0.84

---

app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
app/scripts/modules/core/src/pipeline/executions/execution/execution.less

also looks like the dimensions of the icon may have changed ever so slightly, hence the width increase.

fix(executions): fontawesome renamed repeat icon to redo

---

app/scripts/modules/core/package.json

* fix(executions): fontawesome renamed repeat icon to redo

chore(core): bump package to 0.0.172

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.html
app/scripts/modules/appengine/pipeline/stages/editLoadBalancer/loadBalancerChoice.modal.html
app/scripts/modules/canary/canary/actions/endCanary.modal.html
app/scripts/modules/canary/canary/actions/generateScore.modal.html
app/scripts/modules/core/src/application/config/dataSources/applicationDataSourceEditor.component.html
app/scripts/modules/core/src/application/config/footer/ConfigSectionFooter.tsx
app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.html
app/scripts/modules/core/src/application/config/links/editLinks.modal.html
app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelection.html
app/scripts/modules/core/src/modal/buttons/SubmitButton.tsx
app/scripts/modules/core/src/modal/buttons/submitButton.component.ts
app/scripts/modules/core/src/modal/modals.less
app/scripts/modules/core/src/notification/modal/editNotification.html
app/scripts/modules/core/src/notification/notificationList.directive.html
app/scripts/modules/core/src/pipeline/config/actions/delete/deletePipelineModal.html
app/scripts/modules/core/src/pipeline/config/actions/json/editPipelineJsonModal.html
app/scripts/modules/core/src/pipeline/config/actions/rename/renamePipelineModal.html
app/scripts/modules/core/src/pipeline/config/copyStage/copyStage.modal.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/pipeline/config/preconditions/modal/editPrecondition.html
app/scripts/modules/core/src/pipeline/config/stages/bake/modal/addExtendedAttribute.html
app/scripts/modules/core/src/pipeline/config/stages/core/ExecutionMarkerIcon.tsx
app/scripts/modules/core/src/pipeline/config/stages/core/editStageJson.modal.html
app/scripts/modules/core/src/pipeline/config/stages/travis/modal/addParameter.html
app/scripts/modules/core/src/pipeline/config/stages/webhook/modal/addCustomHeader.html
app/scripts/modules/core/src/serverGroup/configure/common/instanceArchetypeDirective.html
app/scripts/modules/core/src/serverGroup/configure/common/v2instanceArchetype.directive.html
app/scripts/modules/core/src/task/monitor/taskMonitorStatus.component.js

This is surely the rest of the icons.

fix(*): update icons to font-awesome 5 equivalents

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

* fix(*): update icons to font-awesome 5 equivalents
* style(core): override icon for sitemap
* fix(core/pipeline): Update cancel execution icon for FA-v5

chore(core/amazon): bump core to 0.0.173, amazon to 0.0.85

---

app/scripts/modules/titus/package.json
app/scripts/modules/titus/src/serverGroup/configure/serverGroupBasicSettingsDirective.html

fix(titus): handle strategy change

---

app/scripts/modules/core/src/entityTag/notifications/NotificationsPopover.tsx

Put the SFC as an instance variable on the class so it doesn't get re-created during each render.

fix(core/entityTag): Fix notifications popover re-mounting during each render.

---

app/scripts/modules/titus/src/loadBalancers/TitusLoadBalancersTag.tsx

fix(titus): restore load balancer tag icon

---

app/scripts/modules/titus/package.json

- feat(titus): Support specifying a percentage of instances to relaunch (#5054)
- fix(titus): restore load balancer tag icon (#5053)

chore(titus): bump package version to 0.0.4

---

app/scripts/modules/core/package.json

* fix(core/entityTag): Fix notifications popover re-mounting during each render
* fix(core): avoid excessive rerender on popovers with templates
* fix(core/securityGroups): ensure security groups view renders when ready
* fix(core): avoid overflow on Applications actions menu
* style(core): higher contrast background on active page in page navigator
* style(core): use different icon for application in search
* fix(core): do not throw exception on missing versioned provider

chore(core): bump package to 0.0.174

---

app/scripts/modules/core/src/application/ApplicationComponent.tsx
app/scripts/modules/core/src/application/nav/ApplicationRefresher.tsx
app/scripts/modules/core/src/application/nav/PagerDutyButton.tsx

Moving some things around in an effort to create a smaller PR for the navigation refactor...

refactor(core): move app refresher, pager duty buttons to components

---

app/scripts/modules/core/package.json

* feat(core): add categories for application data sources
* chore(package): minify package bundles in production mode only
* chore(package): use --mode=production in gradle build (used by jenkins)
* refactor(core): move app refresher, pager duty buttons to components
* chore(karma): do not use jenkins reporter
* feat(core): implement categorized navigation

chore(core): bump package to 0.0.175

---

app/scripts/modules/core/src/application/index.ts
app/scripts/modules/core/src/application/nav/CategoryDropdown.tsx
app/scripts/modules/core/src/application/nav/NavIcon.tsx
app/scripts/modules/core/src/application/nav/applicationNav.component.less
app/scripts/modules/core/src/application/nav/defaultCategories.ts
app/scripts/modules/core/src/loadBalancer/loadBalancer.dataSource.ts
app/scripts/modules/core/src/pipeline/pipeline.dataSource.js
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/securityGroup/securityGroup.dataSource.ts
app/scripts/modules/core/src/serverGroup/serverGroup.dataSource.ts
app/scripts/modules/core/src/task/task.dataSource.js

Minor style adjustments; also exporting the default categories

style(core): tweak navigation icon sizes/placement

---

app/scripts/modules/core/package.json

* style(core): tweak navigation icon sizes/placement

chore(core): bump package to 0.0.176

---

app/scripts/modules/core/src/application/nav/ThirdLevelNavigation.tsx

Definitely the last style tweak with the new navigation

style(core): add running-count style to third-level nav badge

---

app/scripts/modules/core/package.json

fix badge icon in third-level nav

chore(core): bump package to 0.0.177

---

app/scripts/modules/core/src/application/nav/CategoryDropdown.tsx
app/scripts/modules/core/src/application/nav/applicationNav.component.less

The easiest way to deal with the react bootstrap dropdown is to set it to disabled and beat the CSS into submission.

feat(core): navigate to first item in nav dropdown by default on click

---

app/scripts/modules/core/package.json

* feat(core): navigate to first item in nav dropdown by default on click

chore(core): bump package to 0.0.178

---

halconfig/settings.js

(fixes spinnaker/spinnaker#2579)

Add the ability to enable infrastructureStages

---

app/scripts/modules/core/src/pipeline/config/stages/wait/waitStage.ts

fix(core): set initial state of skipWaitCustomText on wait stage

---

app/scripts/modules/core/package.json

fix(core): set initial state of skipWaitCustomText on wait stage

chore(core): bump package to 0.0.180

---

package.json
yarn.lock

chore(kayenta): bump kayenta to 0.0.35

---

app/scripts/modules/kubernetes/package.json

chore(kubernetes): bump package to 0.0.6

---

app/scripts/modules/core/src/account/account.service.ts
app/scripts/modules/core/src/cloudProvider/cloudProvider.module.ts
app/scripts/modules/core/src/cloudProvider/cloudProvider.registry.spec.ts
app/scripts/modules/core/src/cloudProvider/cloudProvider.registry.ts
app/scripts/modules/core/src/cloudProvider/index.ts
app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelection.service.spec.ts
app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelection.service.ts
app/scripts/modules/core/src/cloudProvider/providerService.delegate.ts
app/scripts/modules/core/src/cloudProvider/skin.service.spec.ts
app/scripts/modules/core/src/cloudProvider/skin.service.ts
app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelection.service.ts
app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelector.component.ts
app/scripts/modules/core/src/cloudProvider/skinSelection/skinSelector.html
app/scripts/modules/core/src/cluster/allClusters.controller.js
app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
app/scripts/modules/core/src/instance/instance.states.ts
app/scripts/modules/core/src/loadBalancer/CreateLoadBalancerButton.tsx
app/scripts/modules/core/src/loadBalancer/loadBalancer.states.ts
app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
app/scripts/modules/core/src/securityGroup/securityGroup.states.ts
app/scripts/modules/core/src/serverGroup/details/ServerGroupDetailsWrapper.tsx
app/scripts/modules/core/src/serverGroup/serverGroup.transformer.js
app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts

Decouples a UI implementation (a "skin") from the provider version returned by an account.

feat(core): move from provider version UI implementation to skins

---

app/scripts/modules/core/package.json

chore(core): bump package to 0.0.181

---

app/scripts/modules/core/src/loadBalancer/loadBalancer.transformer.js
app/scripts/modules/core/src/securityGroup/securityGroupTransformer.service.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/transformer.ts
app/scripts/modules/kubernetes/src/v2/securityGroup/transformer.ts

The v2 provider was implicitly using the v1 provider's transformers, which was leading to some odd behavior.

feat(kubernetes): use v2 load balancer and security group transformers

---

app/scripts/modules/core/package.json

* fix(core/search): dont throw when SETTINGS.defaultProviders is null-ish
* style(core): Updating to use auto-generated files from icomoon.app
* style(core/navigation): remove dead zones from nav dropdown
* refactor(core): allow dataSources to specify a required dataSource

chore(core): bump package to 0.0.183

---

app/scripts/modules/amazon/package.json

* feat(aws): Support rollback of a disabled server group
* style(*): Updating to use auto-generated files from icomoon.app

chore(amazon): bump package to 0.0.87

---

app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicy.html
app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.html
app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/details/autoHealingPolicy/modal/upsertAutoHealingPolicy.modal.controller.ts
app/scripts/modules/google/src/serverGroup/details/autoHealingPolicy/modal/upsertAutoHealingPolicy.modal.html

Depends on https://github.com/spinnaker/clouddriver/pull/2476. No major UI changes, just data.

feat(provider/gce): Support nested health checks in autoHealingPolicy.

---

app/scripts/modules/core/src/domain/IManifest.ts
app/scripts/modules/kubernetes/src/v2/manifest/showManifestDetails.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html

https://github.com/spinnaker/spinnaker/issues/2587

feat(provider/kubernetes): pipeline manifest events

---

app/scripts/modules/amazon/package.json
app/scripts/modules/titus/package.json

* feat(aws/titus): offer rollback when user enables an older server group

chore(amazon/titus): bump packages to 0.0.88, 0.0.6

---

app/scripts/modules/titus/src/instance/details/instanceDetails.html
app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html

Not sure how I missed these in a prior refactor...

fix(titus): keep instance/job title on same line as icon

---

app/scripts/modules/core/package.json

* fix(core): toggle disabled to false if needed on application refresh
* fix(core): remove :focus styling on nav dropdowns

chore(core): bump package to 0.0.185

---

settings.js

chore(canary-v2): Add placeholder config for kayenta.

---

app/scripts/modules/titus/package.json

* fix(titus): keep instance/job title on same line as icon
* fix(titus): fix alignment of migration config fields

chore(titus): bump package to 0.0.7

---

app/scripts/modules/core/src/cache/deckCache.service.ts

This code never worked, but it should work now.

fix(core): do not cache non-json responses in local storage

---

webpack.config.js

fix(build): turn off minification for deck-kayenta

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts

* fix(core): do not cache non-json responses in local storage
* fix(core): make nav category headings clickable in Firefox

chore(core): bump package to 0.0.186

---

app/scripts/modules/titus/package.json

* fix(titus/deploy): Show loading spinner for target groups in deploy config
* fix(titus/loadBalancer): Fix load balancer icon

chore(titus): bump package to 0.0.8

---

app/scripts/modules/core/package.json

chore(core): bump package to 0.0.187

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
app/scripts/modules/core/src/pipeline/pipeline.module.ts

feat(bake/manifest): bake manifest stage config

---

app/scripts/modules/core/src/modal/wizard/WizardPage.tsx
app/scripts/modules/core/src/modal/wizard/modalWizard.less

fix(core/wizard): Fix header icons at smaller widths

---

app/scripts/modules/core/package.json

* fix(core/wizard): Fix header icons at smaller widths
* fix(core/nav): use 'undefined' instead of 'null' for empty select value
* refactor(core): lazy load execution details
* style(core): prettier things

chore(core): bump package to 0.0.188

---

app/scripts/modules/core/package.json

* fix(core): fix manual judgment render, active execution refresh

chore(core): bump package to 0.0.189

---

app/index.deck

It seems trivial, but I don't want our Spinnaker install to display gender specific welcome messages. It is just a movie quote but without that context it can come across weird.

remove a welcome message

---

app/scripts/modules/amazon/src/instance/details/instance.details.controller.js

This is the same as https://github.com/spinnaker/deck/pull/5156, just for `release-1.6.x` branch.

fix(amazon): ask if reboot should consider amazon health only

---

app/scripts/modules/amazon/package.json
app/scripts/modules/titus/package.json

* refactor(*): De-angularize caches
* fix(amazon): ask if reboot should consider amazon health only

chore(amazon/titus): bump packages to 90, 10

---

app/scripts/modules/core/package.json

* fix(core/canary): do not transform lazy canaries, smarter(?) stage synchronization/hydration

chore(core): bump package to 0.0.192

---

app/scripts/modules/kubernetes/src/serverGroup/details/resize/resize.html

same as https://github.com/spinnaker/deck/pull/5159, but for `release-1.6.x` branch.

fix(kubernetes) remove upper limit for CPU Target on resize

---

app/scripts/modules/core/package.json

* fix(core): fix awaiting judgment overflow, prevent flicker on active stages

chore(core): bump package to 0.0.193

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html

https://github.com/spinnaker/rosco/pull/247

feat(bake/manifest): support overrides

---

app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.html

fix(core/jenkins): show long choice params on multiple lines in dropdown

---

app/scripts/modules/core/package.json

* feat(bake/manifest): support overrides
* feat(redblack): UI option for 'Rollback on Failure'
* fix(core/execution) fix wrong parameter passed to getExectionsForConfigIds
* fix(core/jenkins): show long choice params on multiple lines in dropdown
* feat(core): show execution timestamp on hover

chore(core): bump package to 0.0.194

---

app/scripts/modules/core/src/pipeline/service/execution.service.ts

fix(core): remove artificial dehydration code from execution service

---

app/scripts/modules/core/package.json

* fix(core): remove artificial dehydration code from execution service

chore(core): bump package to 0.0.197

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/help/index.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/core/src/task/verification/UserVerification.tsx

fix(core): fix HelpField export

---

app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts

fix(provider/kubernetes): hide bake manifest stage from k8s v1 provider

---

app/scripts/modules/kubernetes/src/common/tolerations/TolerationsComponent.tsx

fix the case there tolerations is undefined or null

fix(provider/kubernetes): fix empty tolerations

---

halconfig/settings.js

cherry pick of https://github.com/spinnaker/deck/pull/5190

fix(provider/ecs): enable ecs provider within deck. (#5190)

---

app/scripts/modules/kubernetes/src/container/environmentFrom.component.html
app/scripts/modules/kubernetes/src/container/environmentFrom.component.ts
app/scripts/modules/kubernetes/src/container/environmentVariables.component.html
app/scripts/modules/kubernetes/src/container/environmentVariables.component.js

exposed the optional field for ConfigMap/Secret environment variables.
fixes spinnaker/spinnaker#2589

feat(provider/kubernetes): expose optional envvar

---

app/scripts/modules/core/src/cluster/filter/clusterFilter.component.ts

This is a dirty hack.  
I will circle back around later and update the `filterModel` stuff to use router params.  I'll remove the manual params management code.

fix(core/cluster): fix infinite loop toggling listInstances true/false

---

app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

Almost address: https://github.com/spinnaker/spinnaker/issues/2636 use of "--values". Stopping short to keep the change small.

feat(bake/manifest): helm values artifacts

---

app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts

It's never really made sense to store the `Show [x] executions per pipeline` value globally, as the number of pipelines and executions - and the cost of fetching and rendering the executions - can vary significantly between applications. If a user is in an application with just one pipeline and sets that number to 50, then navigates to a much larger application, the page might never load.
This PR changes the behavior to cache the execution grouping values per application, and prevents caching the grouping when a subset of pipelines is rendered.

fix(core/executions): store execution count filter per application

---

app/scripts/modules/appengine/package.json

chore(appengine): bump package version to 0.0.2

---

webpack.config.js

Revert "fix(build): re-minify build"

---

app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts

https://github.com/spinnaker/clouddriver/pull/2574

feat(provider/kubernetes): cluster/app/detail no longer configurable in the UI

---

app/scripts/modules/kubernetes/package.json

chore(kubernetes): bump package to 0.0.11

---

app/scripts/modules/core/package.json

* fix(core): fix task matcher region check for rollbackServerGroup

chore(core): bump package to 0.0.205

---

app/scripts/modules/kubernetes/src/v2/manifest/showManifestDetails.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployStatusManifestSummary.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/manifestStatus.component.ts

fixes https://github.com/spinnaker/spinnaker/issues/2729

feat(provider/kubernetes): add manifest status in execution summary

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/manifestStatus.component.ts

fixes https://github.com/spinnaker/spinnaker/issues/2744

fix(provider/kubernetes): manifest status fails to show unstable entries

---

app/scripts/modules/core/src/help/help.contents.ts

Adding guidance around `latest` tag and tag updates.

docs(tootltip): update docker trigger tooltip

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployStatusManifestSummary.ts

in anticipation of https://github.com/spinnaker/deck/pull/5260

fix(provider/kubernetes): update manifest status class for babel change

---

app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx

fix(core): trim pipeline name when checking for duplicates

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

* perf(*): transpile to latest two modern browsers only
* fix(core): trim pipeline name when checking for duplicates
* docs(tootltip): update docker trigger tooltip
* fix(core): remove tooltip if needed when unmounting instances

chore(core/amazon): bump packages

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/google/src/pipeline/stages/bake/bakeStage.html
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js

feat(artifacts): Allow artifacts to be selected in bake config

---

app/scripts/modules/titus/package.json

* fix(provider/titus): removes allocateIp and ports since these are no longer used

chore(titus): bump package to 0.0.18

---

app/scripts/modules/titus/src/pipeline/stages/runJob/runJobExecutionDetails.html

fixes issue where we would show an empty link to execution logs

fix(provider/titus): fix premature display of titus logs

---

app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/checkPreconditionsStage.ts
app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.ts

This causes an error and prevents the stage config from rendering.

fix(core): do not use arrow functions for inline ng controllers

---

app/scripts/modules/titus/package.json
app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx

* refactor(titus): convert run job details to React

chore(titus): bump package to 0.0.21

---

app/scripts/modules/core/src/instance/instanceType.service.ts
app/scripts/modules/google/src/instance/gceInstanceType.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts

fix(provider/gce): Warn user if using default instanceType storage.

---

app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts

Fix whitespace, broke the previous build from linter errors. FYI @danielpeach @anotherchrisberry.

fix(provider/gce): Fix whitespace.

---

app/scripts/modules/core/package.json

* fix(core/pipelines): display comments on stage details

chore(core): bump package to 0.0.209

---

app/scripts/modules/core/package.json

* fix(core/executions): do not restore filter states when pipeline filters applied
* fix(core/executions): synchronize stage summaries more aggressively

chore(core): bump package to 0.0.210

---

app/scripts/modules/core/package.json

* fix(core/executions): ensure group count is set; sync before setting hydrated flag

chore(core): bump package to 0.0.211

---

app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx

fix(titus): fix links to job execution details

---

app/scripts/modules/titus/package.json

* fix(titus): fix links to job execution details
* refactor(core): rename Security Groups to Firewalls

chore(titus): bump package to 0.0.22

---

app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.ts

fix(core/pipelines): fix this binding on pipeline template controller

---

app/scripts/modules/core/package.json

* fix(core/executions): do not overwrite hydrated executions
* fix(core/pipelines): fix this binding on pipeline template controller
* refactor(core): handle TS issue with interface extension
* fix(core): fix path to entity source pipeline

chore(core): bump package to 0.0.213

---

app/scripts/modules/core/src/cluster/onDemand/onDemandClusterPicker.component.ts

feat(titus): make on demand cluster ui more obvious

---

app/scripts/modules/core/src/entityTag/notifications/EntityNotifications.tsx
app/scripts/modules/core/src/entityTag/notifications/EphemeralPopover.tsx
app/scripts/modules/core/src/entityTag/notifications/notifications.less

feat(ttl): Clearly identify ephemeral server groups

---

app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTriggerTemplate.tsx
app/scripts/modules/core/src/pipeline/config/triggers/travis/TravisTriggerTemplate.tsx
app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx

Fix the rest of the triggers if there are multiple of the same type.

fix(core): Fix the triggers to reload when multiple triggers of same type

---

app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js

Prettier did some extra things so ignore those.

fix(core): Cleanup manual trigger template state when switching pipelines

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/artifactTab.ts

Previously the "consumed artifacts" listed in the execution artifacts tab were limited to just those from the execution's trigger.  This PR includes the artifacts generated by other stages in that list as well.
In the image below a GCS artifact was utilized by a bake stage to produce a base64 artifact which was then passed to the deployManifest stage.

feat(artifacts): include stage.outputs artifacts in execution artifacts tab

---

app/scripts/modules/core/src/artifact/artifactSelector.less
app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
app/scripts/modules/google/src/pipeline/stages/bake/bakeStage.html
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

feat(artifacts): type icons in artifact selectors

---

app/scripts/modules/azure/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/ecs/serverGroup/details/serverGroupDetails.ecs.controller.js
app/scripts/modules/openstack/src/instance/details/instance.details.controller.js
app/scripts/modules/openstack/src/loadBalancer/configure/wizard/upsert.controller.js
app/scripts/modules/oracle/securityGroup/configure/createSecurityGroup.controller.js

Mostly the `root/app` entries from the FirewallLabels works, but also a RecentHistoryService line I missed.

fix(*): fix imports from core module

---

app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx

Also fixing an NPE when a job hasn't run yet on Titus

 fix(core): force Registry config block to run earlier

---

app/scripts/modules/amazon/src/securityGroup/configure/CreateSecurityGroupCtrl.js
app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroup.html

need to use an arrow function here, and also need to close the interpolation statement in the HTML template...

fix(amazon): unbreak firewall creation button

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

* amazon: 0.0.97
* core: 0.0.225
* titus: 0.0.28

chore(*): bump core/amazon/titus packages

---

app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/defaultBase64.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/defaultDocker.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/defaultGcs.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/gcs.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/defaultGithub.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/defaultGitlab.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/gitlab.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/defaultS3.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/s3.artifact.ts

Before:
After:
fixes https://github.com/spinnaker/spinnaker/issues/2668

feat(artifacts): Show artifact icon in artifact.component

---

settings.js

chore(build): Add ARTIFACTS_ENABLED env variable.

---

app/scripts/modules/core/src/pipeline/details/StageFailureMessage.tsx

fix(core): Show stage failure message when necessary

---

app/scripts/modules/oracle/instance/details/instance.details.controller.js

fix(oracle): fix InstanceReader import

---

app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.less

fixes https://github.com/spinnaker/spinnaker/issues/2797
Before:
After:

fix(provider/kubernetes): manifest textarea clipped

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/core/package.json
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
app/scripts/modules/titus/package.json

also a minor importing oops fixed

chore(*): package bumps: core to 230, amazon to 100, titus to 31

---

app/scripts/modules/core/src/pipeline/config/validation/PipelineConfigValidator.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestStage.ts

fixes https://github.com/spinnaker/spinnaker/issues/2568

fix(provider/kubernetes): config relying on name instead of labels incorrectly validates kind

---

app/scripts/modules/core/src/domain/IOrchestratedItem.ts
app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts

feat(core): Support buffered executions and sort appropriately

---

app/scripts/modules/core/src/pipeline/config/triggers/trigger.html

Renamed as-per @duftler's suggestion during @ezimanyi's demo

fix(artifacts): "expected artifacts" < "artifact constraints"

---

app/scripts/modules/amazon/package.json

* fix(amazon): filter app load balancer options by account/region in cluster config

chore(amazon): bump package to 0.0.101

---

app/scripts/modules/core/package.json

@christopherthielen @jrsquared PTAL

chore(core): bump package to 0.0.232

---

app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx

fix(core): fix check on showAllInstances for cluster height calculations

---

app/scripts/modules/core/src/artifact/ArtifactIconService.ts
app/scripts/modules/core/src/artifact/icons/bitbucket-file-artifact.svg
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/bitbucket.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/defaultBitbucket.artifact.ts

feat(artifacts/bitbucket): added bitbucket artifact

---

app/scripts/modules/core/package.json

* fix(core): fix check on showAllInstances for cluster height calculations
* feat(artifacts/bitbucket): added bitbucket artifact

chore(core): bump package to 0.0.234

---

app/scripts/modules/core/src/presentation/ReactModal.tsx
app/scripts/modules/core/src/presentation/forms/components/ExpressionInput.tsx

- Call onChange callback in ExpressionInput

refactor(core/presentation): Add third 'modalProps' prop to ReactModal.show()

---

app/scripts/modules/core/package.json

refactor(core/presentation): Add third 'modalProps' prop to ReactModal.show() (#5418)

chore(core): Bump to 0.0.235

---

app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/volumes.controller.js
app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/volumes.html

Add support for NFS volume sources. spinnaker/clouddriver#2685 added the support in clouddriver.
(Note: Simular to #3898; partially addresses spinnaker/spinnaker#1826)

feat(provider/kubernetes): Support NFS Volumes

---

app/scripts/modules/core/src/manifest/ManifestWriter.ts
app/scripts/modules/core/src/pipeline/index.ts
app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/patch/patchOptionsForm.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchOptionsForm.component.ts

spinnaker/spinnaker#2786
@lwander @danielpeach 
WIP: Couple of small things still remaining:
~~- [ ]Show produced artifacts~~ (discussed w/ @lwander . patch does not technically create anything, it just updates in place, so we decided to not show this.)

Add a new patch manifest stage for kubernetes V2 provider

---

app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html

fix(appengine): auto pick a source type

---

app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingProcessesDetailsSection.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/ScheduledActionsDetailsSection.tsx
app/scripts/modules/core/src/cache/collapsibleSectionStateCache.ts
app/scripts/modules/core/src/cluster/filter/FilterSection.tsx
app/scripts/modules/core/src/cluster/filter/collapsibleFilterSection.directive.js
app/scripts/modules/core/src/cluster/filter/collapsibleFilterSection.html
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/executions/executionGroup/executionGroup.less
app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
app/scripts/modules/core/src/presentation/collapsibleSection/collapsibleSection.directive.html
app/scripts/modules/core/src/presentation/collapsibleSection/collapsibleSection.directive.js
app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/serverGroup/details/RunningTasks.tsx

- Pass in four classNames
- Do not render `<h4>` markup when render prop is provided
- Tweak chevron size (use px)
- Animate chevron rotation

feat(core/presentation): Make CollapsibleSection less style opinionated

---

app/scripts/modules/core/src/cluster/task.matcher.ts

A task matcher was not found when the stage type was 'resizeServerGroup'
- Removed `good grief`

fix(core/cluster): force stages to lowercase for taskmatcher lookup

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsubTrigger.html

fix(pubsub): constraint alignment & help text

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
app/scripts/modules/amazon/src/loadBalancer/OidcConfigReader.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/ConfigureOidcConfigModal.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
package.json
yarn.lock

This still has some tweaks needed, but getting it out a little early for early feedback.
Action section of a listener in the load balancer config:

feat(amazon/loadBalancers): Support authenticate-oidc actions

---

app/scripts/modules/core/src/domain/ISecurityGroup.ts
app/scripts/modules/core/src/securityGroup/securityGroup.html
app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts

fix(core/securityGroup): Fix links to titus server groups (in sidebar) from firewalls screen

---

app/scripts/modules/core/src/presentation/forms/fields/ExpressionField.tsx
app/scripts/modules/core/src/presentation/forms/fields/ExpressionRegexField.tsx
app/scripts/modules/core/src/presentation/forms/fields/TextField.tsx

fix(core/presentation): fix broken travis

---

app/scripts/modules/core/src/application/config/deleteApplicationSection.directive.js

fix(core/application): Fix delete application modal hanging

---

app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.html
app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.js
app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html

Still needs a bit of work in Orca. Depends on https://github.com/spinnaker/clouddriver/pull/2712.

feat(provider/gce): Adds mode to autoscaling detail and upsert.

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/help/HelpMenu.tsx
halconfig/settings.js
settings.js

feat(core): configurable feedback link

---

app/scripts/modules/core/package.json

chore(core): bump package to 0.0.241

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestStage.ts

fixes https://github.com/spinnaker/spinnaker/issues/2740

feat(kubernetes): add account tag to pipeline headers

---

app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/core/src/loadBalancer/LoadBalancerServerGroup.tsx

fix(titus): Fix links to titus servergroups from amazon load balancer

---

webpack.config.js

Closes https://github.com/spinnaker/spinnaker/issues/2942

feat(build): add cache bust for builds

---

app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts

- pipeline names should not have trailing spaces

fix(core): Should trim pipeline name on save

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/notification/modal/editNotification.controller.modal.js
app/scripts/modules/core/src/notification/notificationList.directive.js
app/scripts/modules/core/src/notification/notifications.module.js
app/scripts/modules/core/src/notification/types/googlechat/additionalFields.html
app/scripts/modules/core/src/notification/types/googlechat/googlechat.notification.type.module.js

Add a new notification type Google Chat.
This is part of the issue spinnaker/spinnaker#2936

feat(notification): Add support for Google Chat.

---

app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html

Issue: https://github.com/spinnaker/spinnaker/issues/2710

feat(kubernetes): add more info about k8s-v2 loadbalancer

---

webpack.config.js

cherry pick of https://github.com/spinnaker/deck/pull/5482

fix(build): add cachebust query param to scripts in index.html (#5482)

---

app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.controller.ts
app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.html

fix(amazon/loadBalancer): Fix DNS link in target group to match load balancer

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/failOnFailedExpressions/failOnFailedExpressions.directive.html
app/scripts/modules/core/src/pipeline/config/stages/failOnFailedExpressions/failOnFailedExpressions.directive.js
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js

- adds a UI control to set `failOnFailedExpressions=true`

feat(core): Adding option to fail pipeline on failed expressions

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
halconfig/settings.js
settings.js

prefer to have this customizable so we can see further back

feat(core): customizing maximum number of pipelines displayed

---

app/scripts/modules/core/src/pipeline/config/triggers/webhook/webhook.trigger.ts
app/scripts/modules/core/src/pipeline/config/triggers/webhook/webhookTrigger.html

adds runAsUser to the webhook trigger.
@lwander @danielpeach PTAL. I'll submit a patch for 1.8 once merged. cc @kevinawoo 
fixes spinnaker/spinnaker#2588

fix(trigger/webhook): add runAsUser to webhook

---

app/scripts/modules/core/src/pipeline/config/triggers/webhook/webhook.trigger.ts

fix(trigger/webhook): fix linting issue

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/triggers/jenkins/jenkinsTrigger.html
app/scripts/modules/core/src/pipeline/config/triggers/travis/travisTrigger.html

fix(core): properties message for jenkins stage is wrong

---

app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx

fix(core/cluster): Do not scroll to bottom of clusters view when no cluster is selected

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

cherry pick of https://github.com/spinnaker/deck/pull/5450

fix(pipeline): Correctly handle saving pipeline templates (#5450)

---

app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js
app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js

Docker artifacts configured in a stage now appear in the 'Containers' and 'Init Containers' field when deploying using the Kubernetes V1 provider.

feat(kubernetes): Allow deploying containers specified as artifacts

---

app/scripts/modules/core/src/pipeline/config/stages/stage.html

Definitely a less-than-stellar fix, but it works, and this template will go away soon...

fix(core): Fix stage execution windows from undefined error

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/config/triggers/pipelineRoles.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/runAsUserSelector.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
settings.js

Deck part of https://github.com/spinnaker/spinnaker/issues/3037
Here is what this looks like:

feat(authz/config): Add a pipeline roles section to pipeline config.

---

app/scripts/modules/core/package.json

chore(core): bump core package to 0.0.248

---

app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.controller.js

Noticed a minor lint issue in my Travis run for a previous PR.

style(kubernetes): Removing unused variable

---

app/scripts/modules/kubernetes/package.json
app/scripts/modules/kubernetes/src/serverGroup/artifactExtractor.ts

fix(kubernetes): fixes package build

---

app/scripts/modules/core/package.json

@jrsquared @anotherchrisberry PTAL

chore(core): bump core package to 0.0.249

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts

fixes https://github.com/spinnaker/spinnaker/issues/3119

feat(artifacts): alphabetically sort artifact types by label

---

app/scripts/modules/core/src/instance/Instances.tsx
app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
package.json
yarn.lock

Cherry pick of https://github.com/spinnaker/deck/pull/5572 into release-1.9.x branch fixes https://github.com/spinnaker/spinnaker/issues/3140

fix(core/overrideRegistry): Fix @Overridable + Stateless Functional Component

---

app/scripts/modules/core/src/search/global/GlobalSearch.tsx
app/scripts/modules/core/src/search/global/GlobalSearchResults.tsx
app/scripts/modules/core/src/search/global/globalSearch.less
package.json
yarn.lock

feat(core/search): Add "show all" links to each category

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.ts
halconfig/settings.js
settings.js

cherry-pick of https://github.com/spinnaker/deck/pull/5586
* feat(wercker): feature toggle for wercker stages
This makes it possible to set feature.wercker to false. We do not want
to expose stages that cannot be used by our users.
* address comments

fix(wercker): feature toggle for wercker stages (#5586)

---

app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js

Cherry-pick of https://github.com/spinnaker/deck/pull/5580 requested by @jervi

fix(amazon/deploy): Edit deployment cluster button did not work (#5580)

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/edit/editManifestWizard.controller.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestWizard.controller.ts
app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts

https://github.com/spinnaker/spinnaker/issues/3159

fix(kubernetes): pick correct account when opening edit manifest wizard

---

app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts

sorry about the monster diff for a two-line change

fix(kubernetes): correct lint error

---

halconfig/settings.js

chore(halconfig): allow enabling travis & wercker in halconfig (#5609)

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.html
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html
app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.html
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

Closes https://github.com/spinnaker/spinnaker/issues/3155

feat(kubernetes): use native language on action buttons

---

app/scripts/modules/canary/canary/canaryStage.js

Noticed this while I was fixing related stuff. Looks like the react deploy dialog wasn't hooked up to editing and the resultant command from adding a cluster pair wasn't getting handled.i
I don't even know if anybody uses this, but hey, it's fixed!

fix(canary): Make deploy dialog command handling and cluster edits work

---

app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts

In the released locking implementation the exception details
changed from three attributes in the exception detail to an
object that contained those attributes.

fix(locking): updated LockFailureException details

---

app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

Cherry-pick of https://github.com/spinnaker/deck/pull/5627 into 1.9
FYI @stewchen

fix(appengine): add server group button broken

---

app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

feat(appengine): filter container image artifacts to just docker images

---

app/scripts/modules/core/src/pipeline/config/triggers/webhook/webhookTrigger.html

when i submitted the first patch for this i accidentally referenced the
components controller incorrectly.
@danielpeach @sbwsg PTAL!

fix(trigger/webhook): fix runas user

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestEvents.tsx

fix(provider/kubernetes): fix missing event message check

---

app/scripts/modules/kubernetes/src/v2/manifest/edit/editManifestWizard.controller.ts

This mimics the behavior or `kubectl edit`.
Part of a fix for https://github.com/spinnaker/spinnaker/issues/3165

fix(provider/kubernetes): edit last applied config

---

app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
app/scripts/modules/core/src/domain/IExpectedArtifact.ts
app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js

First step towards https://github.com/spinnaker/spinnaker/issues/2921 is to get expected artifact creation in to a central place for components to access.

feat(artifacts): move artifact creation into central service

---

app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerHeading.tsx

fix(kubernetes): fix scrolling behavior for deployments in cluster view

---

app/scripts/modules/ecs/src/instance/details/instanceDetails.html

feat(provider/ecs): Added support for ENIs in the instance details view

feat(provider/ecs): Added support for ENIs in the instance details view

---

app/scripts/modules/ecs/src/placementStrategy/placementStrategy.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html

fix(ecs/deploy): Clarified binpack strategy as being memory binpack

fix(ecs/deploy): Clarified binpack strategy as being memory binpack

---

app/scripts/modules/core/src/application/config/applicationConfig.view.html
app/scripts/modules/core/src/application/config/links/applicationLinks.component.html
app/scripts/modules/core/src/application/config/links/applicationLinks.component.js
app/scripts/modules/core/src/application/config/links/applicationLinks.component.less
app/scripts/modules/core/src/instance/details/instanceLinks.component.js
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/titus/src/instance/details/instance.details.controller.js

Show a cloud provider dropdown if the application has multiple cloud providers
If an application only has a single cloud provider, do not show the cloud provider selector

 feat(core): Support different instance link sections by cloud provider

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.html
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/ManifestQos.tsx
app/scripts/modules/kubernetes/src/v2/manifest/ManifestResources.tsx
app/scripts/modules/kubernetes/src/v2/manifest/manifestQos.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestResources.component.ts

https://github.com/spinnaker/spinnaker/issues/3230

feat(provider/kubernetes): container metrics & QOS tier

---

app/scripts/modules/core/src/pipeline/config/stages/StageName.tsx

Cherry pick of @ezimanyi's fix into 1.9 https://github.com/spinnaker/deck/pull/5656

fix(artifacts): Fix artifact in execution history (#5656)

---

app/scripts/modules/kubernetes/src/v2/instance/details/details.html

feat(provider/kubernetes): move logs up to top section

---

app/scripts/modules/core/src/pipeline/config/stages/applySourceServerGroupCapacity/ApplySourceServerGroupCapacityDetails.tsx

fix(core/pipeline): Add error message to ApplySourceServerGroupCapacityDetails stage

---

app/scripts/modules/core/src/artifact/react/ArtifactIcon.tsx
app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
app/scripts/modules/core/src/pipeline/config/stages/core/stageConfigField/StageConfigField.tsx
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/singleFieldArtifactEditor.tsx

Continuing the series of patches for https://github.com/spinnaker/spinnaker/issues/2921

feat(artifacts): add icon helper and use stage config field where possible

---

app/scripts/modules/core/src/artifact/react/ExpectedArtifactSourceSelector.tsx

Part of the editor functionality for https://github.com/spinnaker/spinnaker/issues/2921

feat(artifacts): add a select box for choosing an artifact source

---

app/scripts/modules/amazon/src/serverGroup/AvailabilityZoneSelector.tsx

fix(amazon): Fix availability zone selector showing correct state

---

app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/network/CreateNetworkLoadBalancer.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/AmazonCloneServerGroupModal.tsx
app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
app/scripts/modules/core/src/pagerDuty/PageModal.tsx
app/scripts/modules/core/src/presentation/ReactModal.tsx
app/scripts/modules/core/src/task/monitor/TaskMonitor.ts
app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/ConfigBinModal.tsx

Some other minor modal related bug fixes

refactor(core/task): Simplify task monitoring in React Modals

---

app/scripts/modules/amazon/src/serverGroup/AvailabilityZoneSelector.tsx
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupSecurityGroups.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx

A series of fixes related to AWS Clone stage.

fix(aws): Fix clone stage.

---

app/scripts/modules/core/src/pipeline/config/triggers/git/git.trigger.ts

Fixes https://github.com/spinnaker/spinnaker/issues/3166

fix(trigger): add labels for gitlab trigger fields

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx

Maybe I'll learn how checkboxes work.

fix(amazon/deploy): Fix instance monitoring and ebs optimized checkboxes

---

app/scripts/modules/core/src/artifact/NgManifestArtifactDelegate.ts
app/scripts/modules/core/src/artifact/index.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html

feat(kubernetes): add inline artifact editor to patch manifest stage

---

app/scripts/modules/core/src/api/ApiService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts

Fixes https://github.com/spinnaker/spinnaker/issues/3277

feat(api): reject invalid content API responses with message

---

app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html
app/scripts/modules/appengine/src/serverGroup/configure/wizard/cloneServerGroup.controller.ts
app/scripts/modules/core/src/artifact/ExpectedArtifactSelectorViewControllerAngularDelegate.ts
app/scripts/modules/core/src/artifact/NgAppEngineDeployArtifactDelegate.ts
app/scripts/modules/core/src/artifact/NgManifestArtifactDelegate.ts
app/scripts/modules/core/src/artifact/index.ts
app/scripts/modules/core/src/artifact/react/ExpectedArtifactEditor.tsx
app/scripts/modules/core/src/domain/IArtifactEditorProps.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx

feat(artifacts): add inline artifact editor for appengine artifacts

---

app/scripts/modules/ecs/src/ecs.help.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html

* Clouddriver pull request has been merged:
* https://github.com/spinnaker/clouddriver/commit/3910a332e2d410ea977bbbc4e8bf8f039bee97cb

feat(provider/ecs): Added support for environment variables

---

app/scripts/modules/core/src/artifact/ExpectedArtifactSelectorViewController.ts
app/scripts/modules/core/src/artifact/ExpectedArtifactSelectorViewControllerAngularDelegate.ts
app/scripts/modules/core/src/artifact/NgAppEngineDeployArtifactDelegate.ts
app/scripts/modules/core/src/artifact/NgBakeManifestArtifactDelegate.ts
app/scripts/modules/core/src/artifact/NgGCEImageArtifactDelegate.ts
app/scripts/modules/core/src/artifact/NgManifestArtifactDelegate.ts
app/scripts/modules/core/src/artifact/index.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts

feat(kubernetes): bake manifest artifacts inline editor

---

app/scripts/modules/core/src/instance/instance.states.ts

fix(amazon/instance): Fix standalone instance view

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts

Closes https://github.com/spinnaker/spinnaker/issues/2711

feat(artifacts): default artifact type auto selected from match artifact

---

app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
app/scripts/modules/core/src/pipeline/config/services/PiplineConfigService.spec.ts

fix(kayenta): fix editing canary + baseline server groups

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/core/src/artifact/imageSourceSelector.component.ts
app/scripts/modules/core/src/serverGroup/configure/common/DeployInitializer.tsx
app/scripts/modules/core/src/serverGroup/configure/common/deployInitializer.component.ts
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html
app/scripts/modules/kubernetes/src/v2/serverGroup/serverGroupTransformer.service.ts

Related to https://github.com/spinnaker/deck-kayenta/pull/341

feat(kayenta): show image sources

---

package.json
yarn.lock

chore(prettier): Just Update Prettier™

---

app/scripts/modules/core/src/serverGroup/configure/common/v2instanceArchetypeSelector.component.ts

Cherry pick of https://github.com/spinnaker/deck/pull/5730 into 1.9.x.

fix(core/serverGroup): Guard for existence of callbacks (#5730)

---

app/scripts/modules/core/src/serverGroup/configure/common/v2InstanceTypeSelector.component.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html

This fix also needs cherry picked into 1.9.x.

fix(provider/google): Deploy custom archetype fixes.

---

app/scripts/modules/kubernetes/src/v2/manifest/wizard/BasicSettings.tsx
app/scripts/modules/kubernetes/src/v2/manifest/wizard/ManifestEntry.tsx

fix(kubernetes): fix after formik modal wizard refactor

---

app/scripts/modules/core/package.json
app/scripts/modules/core/src/artifact/react/ArtifactIconList.tsx
app/scripts/modules/core/src/help/HelpMenu.tsx
app/scripts/modules/core/src/pagerDuty/PageButton.tsx
app/scripts/modules/core/src/pagerDuty/PageModal.tsx
app/scripts/modules/core/src/pagerDuty/pager.states.ts
app/scripts/modules/core/src/pipeline/config/stages/StageName.tsx
app/scripts/modules/core/src/pubsub/PubsubSubscriptionReader.ts

switch from `@spinnaker/core` imports to `core/packagename`
Also bump package to 269

Fix imports

---

app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

Deploy stage does not require these because of triggers.

fix(titus/deploy): Disable image selection for titus deploy stage

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/common/SecurityGroups.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupCapacity.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettings.tsx
app/scripts/modules/cloudfoundry/src/common/wizard/sections/cfDisclaimer.cf.tsx
app/scripts/modules/cloudfoundry/src/loadBalancer/configure/loadBalancerDetails.tsx
app/scripts/modules/cloudfoundry/src/loadBalancer/configure/noLoadBalancer.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings.cf.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/basicSettings.cf.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings.cf.tsx
app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
app/scripts/modules/core/src/modal/wizard/WizardPage.tsx
app/scripts/modules/kubernetes/src/v2/manifest/wizard/BasicSettings.tsx
app/scripts/modules/kubernetes/src/v2/manifest/wizard/ManifestEntry.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx

refactor(core/modal): Improve wizardPage types so no type param is necessary

---

app/scripts/modules/kubernetes/src/v2/manifest/wizard/ManifestEntry.tsx
app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.component.ts
app/scripts/modules/kubernetes/src/v2/manifest/yaml/YamlEditor.tsx

fix(kubernetes): copy into pipeline stage

---

app/scripts/modules/kubernetes/package.json

chore(provider/kubernetes): bump k8s package version

---

package.json
yarn.lock

chore(kayenta): bump package to 0.0.60

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html

Cherry pick of https://github.com/spinnaker/deck/pull/5838 into 1.10.

fix(kubernetes): fix saving of kubernetes yaml patches (#5838)

---

app/scripts/modules/oracle/src/pipeline/stages/bake/bakeStage.html
app/scripts/modules/oracle/src/pipeline/stages/bake/ociBakeStage.js

Cherry-pick the fix (https://github.com/spinnaker/deck/pull/5843) into Spinnaker 1.10 release

fix(bakery/oracle): use read-only text field for bake region

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

fix(kubernetes): hide copy manifest button if source type is artifact

---

gradle/buildModules.sh

Fixes travis builds on this branch.

fix(buildModules): switch to nvm install [version]

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceStage.ts

feat(artifacts): Add execution artifacts tab to findArtifactsFromResourceStage

---

app/scripts/modules/kubernetes/src/v2/manifest/traffic/ManifestTrafficService.spec.ts
app/scripts/modules/kubernetes/src/v2/manifest/traffic/ManifestTrafficService.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html

https://github.com/spinnaker/spinnaker/issues/3470
Can add a dropdown to pick a specific set of load balancers if people ask for it.

feat(kubernetes): ad-hoc enable/disable server groups

---

app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/StringsAsOptions.tsx
app/scripts/modules/core/src/presentation/forms/inputs/index.ts
package.json
yarn.lock

TL;DR;
```ts
<Formik
initialValues={{ application: '' }}
render={formik => (
<FormikFormField
name="application"
label="Choose Application"
input={props => (
<StringsToOptions strings={applications}>
{options => <ReactSelectInput {...props} options={options} />}
</StringsToOptions> 
)}
/>
)};
/>
```

feat(core/presentation): Add ReactSelectInput component

---

app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx

feat(core/presentation): add onBlur to react-select-input

---

app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.js
app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyService/cloudfoundryDestroyServiceStage.js

Co-Authored-By: Joris Melchior <joris.melchior@gmail.com>
Co-Authored-By: Stu Pollock <spollock@pivotal.io>

fix(provider/cf): ensure regions are initialized before rendering

---

app/scripts/modules/core/src/pipeline/config/stages/stage.module.js

`_.defaultsDeep` is safer. Thanks @christopherthielen.

feat(stages/evaluatevariables): Using lodash.defaultsDeep instead

---

app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.controller.ts
app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html
halconfig/settings.js
settings.js

TODO(sbws): remove flag from halyard

feat(appengine): Unflag appengine container deployments

---

app/scripts/modules/google/package.json

chore(google): bump google module to 0.0.4

---

app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

Cherry-pick of https://github.com/spinnaker/deck/pull/5908

fix(appengine): selectedProvider received as null

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html

cherry-pick of https://github.com/spinnaker/deck/pull/5915

fix(artifacts): hide artifact editor when source of manifest is text

---

app/scripts/modules/core/src/presentation/forms/Validation.ts
app/scripts/modules/core/src/presentation/forms/fields/FormField.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx

- Support multiple validators and `required` flag in `FormField` and `FormikFormField`

feat(core/presentation): Introduce Validation class for reusable validation fns.

---

app/scripts/modules/core/package.json

57b1e4904c04d04cb485d2850fd0675d41c4f60c  chore(core/presentation): Update formik from 0.11.11 to 1.3.1 (#5917)
c0842ad00bb6afb6b63e943fa5d9c78fe9ec1b3f fix(provider/cf): fetch services on a per-region basis
f22fecd5e774ddf42e5c308df26cfee431597c86 feat(core/presentation): Introduce Validation class for reusable validation fns. (#5913)
9eacd0c813bee30086daf8d36a60af4e950cb70d chore(core/pipeline): Cleaning up imports (#5914)
b08bab2d4198deb0ba3b84c7ba7ae887e6c7b492 refactor(core/projects): Simplify TrashButton click handler
1abc6ba441641fd1e9c13f346bf3a7a4eeb6af32 refactor(core): Remove invalid <g> from HoverablePopover (#5904)
8523bbd7eb620cb4ec43754e02508fecb086b64e test(core/cluster): fix lint error unused variable (#5910)
cc68c9c468520b14e65eef8b6f5b6261ef5bae72 feat(core): Support a …

chore(core): Bump version to 0.0.281

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
app/scripts/modules/core/src/pipeline/config/triggers/pipelineRoles.component.ts
app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
settings.js

Adds support to the UI to toggle on/off respectQuietPeriod.
@skandragon FYI
Only enabled with `SETTINGS.feature.quietPeriod: true`

feat(core/triggers): Add UI to toggle on/off respectQuietPeriod

---

app/scripts/modules/oracle/src/helpContents/oracleHelpContents.ts
app/scripts/modules/oracle/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/oracle/src/serverGroup/configure/wizard/cloneServerGroup.controller.js
app/scripts/modules/oracle/src/serverGroup/configure/wizard/network/networkSettings.html
app/scripts/modules/oracle/src/serverGroup/configure/wizard/serverGroupWizard.html
app/scripts/modules/oracle/src/serverGroup/details/serverGroupDetails.html

Add support for authorized SSH key when creating instances on Oracle cloud.
Related clouddriver PR is https://github.com/spinnaker/clouddriver/pull/3091.

fix(provider/oracle): add ssh key

---

app/scripts/modules/core/package.json

e1b94b0a9368978414910c1eb39457ca9e570352 feat(webhook): add PATCH to list of options for webhook (#5912)
0d938b1d7857843ddbe13b1aff933c31b40b0fcc feat(core/triggers): Add UI to toggle on/off respectQuietPeriod (#5921)
5afff2cf35af7fb388513bc2685614b1a63a6471 fix(core/presentation): use Option<string> in StringToOptions
7b1fa9799a229faf13becbf824f5a17a6e052cca fix(core/help): Export HelpField and HelpMenu

chore(core): Bump version to 0.0.282

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts

Fixes https://github.com/spinnaker/spinnaker/issues/3549

fix(artifacts): bake manifest artifact scope used before defined

---

app/scripts/modules/core/src/pipeline/config/triggers/triggers.html

fix(core/pipeline): Make quiet period message more specific

---

app/scripts/modules/kubernetes/src/serverGroup/configure/CommandBuilder.js

cherry pick of https://github.com/spinnaker/deck/pull/5975

fix(kubernetes): defaults can be passed in as null (#5975)

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBAdvancedSettings.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/classic/AdvancedSettings.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/classic/HealthCheck.tsx
app/scripts/modules/core/src/presentation/forms/Validation.ts
app/scripts/modules/core/src/presentation/forms/fields/FormField.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
app/scripts/modules/core/src/presentation/forms/inputs/CheckboxInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/NumberInput.tsx
app/scripts/modules/core/src/presentation/forms/interface.ts

- Add internal Validators in NumberInput for min/max
- Use internal validators for NumberInputs

feat(core/presentation): Support internal Validator(s) in Inputs

---

app/scripts/modules/core/src/presentation/forms/FormField.tsx
app/scripts/modules/core/src/presentation/forms/FormikFormField.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionField.tsx
app/scripts/modules/core/src/presentation/forms/fields/index.ts
app/scripts/modules/core/src/presentation/forms/index.ts
app/scripts/modules/core/src/presentation/forms/inputs/expression/ExpressionError.tsx
app/scripts/modules/core/src/presentation/forms/inputs/expression/ExpressionInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/expression/evaluateExpression.ts
app/scripts/modules/core/src/presentation/forms/inputs/expression/index.ts
app/scripts/modules/core/src/presentation/forms/interface.ts

- Extract evaluateExpression to a separate file
- Move FormField and FormikFormField to parent directory

refactor(core/presentation): Move some code around

---

app/scripts/modules/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx

same as https://github.com/spinnaker/deck/pull/6003

fix(aws/serverGroups): always show AWS sever group settings

---

app/scripts/modules/kubernetes/src/v2/manifest/selector/ManifestSelector.tsx

Cherry-pick fix for #3513 into 1.10.x for 1.10.4 release.

fix(kubernetes): Allow resource name to be added as expression #3513

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

Sorry for the bonus versions, I got excited.

Package bump

---

app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestSelector.ts
app/scripts/modules/kubernetes/src/v2/manifest/selector/selector.component.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceConfig.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestConfig.controller.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestConfig.html

https://github.com/spinnaker/orca/pull/2511
I skipped the "delete" stage since it looks fairly involved and Dan left a TODO to address label selectors in the manifest selector: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/kubernetes/src/v2/manifest/selector/IManifestSelector.ts#L20
Could you look into that one @danielpeach?

feat(provider/kubernetes): dynamic lookups in scale/find

---

app/scripts/modules/core/package.json

c8cebde7c3612db006d5d95654b4f080dbb12e8f fix(core/pipeline): Only show quiet period tag if respect flag is true (#6038)

chore(core): Bump version to 0.0.293

---

app/scripts/modules/core/src/reactShims/ngReact.ts
app/scripts/modules/core/src/widgets/AccountRegionClusterSelector.tsx
app/scripts/modules/core/src/widgets/accountRegionClusterSelectorWrapper.component.ts
app/scripts/modules/core/src/widgets/widgets.module.ts

This is to prepare for converting the Cloud Foundry pipeline stages from Angular to React.

refactor(core): Reactify AccountRegionClusterSelector

---

app/scripts/modules/oracle/src/domain/IOracleLoadBalancer.ts
app/scripts/modules/oracle/src/loadBalancer/configure/backendSets.html
app/scripts/modules/oracle/src/loadBalancer/configure/certificates.html
app/scripts/modules/oracle/src/loadBalancer/configure/createLoadBalancer.controller.spec.ts
app/scripts/modules/oracle/src/loadBalancer/configure/createLoadBalancer.controller.ts
app/scripts/modules/oracle/src/loadBalancer/configure/editLoadBalancer.html
app/scripts/modules/oracle/src/loadBalancer/details/loadBalancerDetail.controller.ts
app/scripts/modules/oracle/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/oracle/src/serverGroup/configure/serverGroupConfiguration.service.js

fix(provider/oracle): fix update/edit LoadBalancer

---

app/scripts/modules/core/src/application/nav/ApplicationRefresher.tsx

fix(core/application): Move observable subscription to componentDidMount()

---

package.json
yarn.lock

removes extraneous `<div class="UIView">` tags

chore(*): Update uirouter/react-hybrid to 0.3.9

---

app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx

This fixes a bug where desired is controlled by scaling policies and is disabled in the UI.
The ui now updates desired if min is increased above current desired, or max is decreased below desired.  However, if the user moves the value back down the desired wasn't adjusted back down.
This fixes the behavior by always trying to adjust towards the current desired value but respecting the new min/max.

fix(amazon/serverGroup): Track min/max values to desired better

---

app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx

In a previous PR we change deck to only submit the changed min/max/desired values to the back end.
This addresses feedback from @dreynaud about surfacing the details about which fields have actually changed.  The user may assume they're submitting all three values when they're only changing one value.
This also fixes duplicate validation messages appearing.

 fix(amazon/serverGroup): Show the list of changed values (min/max/desired)

---

app/scripts/modules/core/src/serverGroup/details/RunningTasks.tsx

fix(core/serverGroup): Fix occasional NPE when serverGroup.runningTasks is null

---

app/scripts/modules/core/src/application/nav/CategoryDropdown.tsx
app/scripts/modules/core/src/domain/IExecution.ts
app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/domain/IServerGroupManager.ts
app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
app/scripts/modules/core/src/entityTag/clusterTargetBuilder.ts
app/scripts/modules/core/src/entityTag/entityRef.builder.ts
app/scripts/modules/core/src/entityTag/entityTags.dataSource.ts
app/scripts/modules/core/src/entityTag/notifications/GroupedNotificationList.tsx
app/scripts/modules/core/src/entityTag/notifications/NotificationList.tsx
app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
app/scripts/modules/core/src/pipeline/pipeline.dataSource.js
app/scripts/modules/core/src/serverGroupManager/ServerGroupManager.tsx
app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerHeading.tsx
app/scripts/modules/core/src/serverGroupManager/serverGroupManager.dataSource.ts
app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html
app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.html
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

feat(entityTags):kubernetes support

---

app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings.cf.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/basicSettings.cf.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings.cf.tsx

refactor(provider/cf): make better use of formik library capabilities

---

app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings.cf.tsx

fix(provider/cf): add missing trigger to deploys

---

app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/cloudFoundryInfoDetailsSection.tsx

Display the tags for services in server group details
spinnaker/spinnaker#3638

feat(provider/cf): display service tags for SG

---

app/scripts/modules/amazon/package.json

40c3efeb6e2d62604c0c69f934a7009e08fdcffc fix(aws): update load balancer zones when region changes (#6074)

chore(amazon): Bump version to 0.0.141

---

app/scripts/modules/core/src/pipeline/config/triggers/RunAsUser.tsx
app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerConfig.tsx

Before:
After:
Fixes https://github.com/spinnaker/spinnaker/issues/3607

fix(docker): RunAsUser select box appears doubled

---

app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupConfigurationModel.cf.ts
app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings.cf.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/cloudFoundryInfoDetailsSection.tsx

feat(provider/cf): display cf health check details for app

---

app/scripts/modules/docker/package.json

a298b9a15c6b33438c4c183067b93e7c9313bb2d feat(docker): Add digest support to manual docker trigger (#6085)
ce9f2cb970840d24345e6f697b64b3106a289d55 fix(docker): RunAsUser select box appears doubled (#6082)

chore(docker): Bump version to 0.0.23
