spinnaker/deck

- app/scripts/modules/canary/acaTask/acaTaskStage.js
*Title*
Picking Accounts from all Providers during ACA Task Creation
*Description*
This patch allows accounts of all configured providers to be listed during creation of an ACA task. Currently, only AWS accounts are listed in the drop down.
This essentially fixes the issue filed at [#2083](https://github.com/spinnaker/spinnaker/issues/2083)
*Environment*
I am running Spinnaker on AWS to deploy into AWS and Kubernetes.
*Cloud Provider*
AWS and Kubernetes
*Fix Area*
Pipeline Templates, Canary
*Testing*
I have tested these changes and ensured successful ACA task runs having set AWS & Kubernetes as cloud providers.
> fix(aca): listing accounts from all configured providers

- app/scripts/modules/core/src/delivery/details/StageFailureMessage.tsx
- app/scripts/modules/core/src/event/EventBus.spec.ts
- app/scripts/modules/core/src/event/EventBus.ts
- app/scripts/modules/core/src/index.ts
We are going to use this internally to track when users see what was formerly a low-value error message ("No reason provided") and figure out what actual error message could be surfaced.
> feat(core): provide simple general purpose event bus

- app/scripts/modules/core/package.json
- app/scripts/modules/core/src/event/EventBus.spec.ts
* fix(canary): fix syntax in acaTask stage
* fix(core): Link to failed stage had incorrect name
* fix(core): Favor using `stageId` when building links to failed stages
* fix(core): Fix a few more undefined errors from execution details controller
* feat(core): provide simple general purpose event bus
> chore(core): bump package to 0.0.100

- app/scripts/modules/core/src/filterModel/filter.model.service.js
Fixing a regression from https://github.com/spinnaker/deck/pull/4369
Previously, `stack` and `detail` would be set to empty strings if they were not present. Since they're `null` in the case of monikers, the `(none)` filters won't work.
cc @andrewbackes
> fix(core): re-enable filter on (none) for stack/detail

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.html
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.js
- app/scripts/modules/kubernetes/src/presentation/imageId.filter.ts
add support for using images found from context in the runJob stage. i
refactored the `Resolve from Trigger` checkbox, and included Context and
Trigger images in the same dropdown to bring it more in line with the
Server Group configuration.
spinnaker/spinnaker#1960
@danielpeach can I get some early feedback on this? I had to copy a bunch of code over from the Server Group module. I feel like there may be a better way to handle that, I just don't know what it is.
> feat(provider/kubernetes): runJob context images

- app/scripts/modules/kubernetes/src/serverGroup/paramsMixin.js
when destroying multiple servergroups, the namespace key wasn't being
populated properly. `serverGroup.region` is the correct key to use for
namespace.
ping @danielpeach or @lwander 
Fixes spinnaker/spinnaker#2027
> fix(provider/kubernetes): fix destroy multiple

- app/scripts/modules/core/src/domain/index.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.dataSource.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.module.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.service.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.states.ts
- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html
`#/applications/{app}/clusters/serverGroupManagerDetails/{provider}/{account}/{region}/{serverGroupManagerName}` now opens the server group manager details panel.
> Server Group Manager data source, states, and kubernetes details

- app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.controller.js
- app/scripts/modules/core/src/delivery/manualExecution/manualPipelineExecution.html
- app/scripts/modules/core/src/pipeline/config/parameters/parameter.html
Companion PR for https://github.com/spinnaker/gate/pull/479
Also fixing alignment of the options checkbox on the parameter config, and removing the help fields, since there's no help content associated with them.
Also only showing a single running execution in the warning that there are currently running executions. If there are multiple, it's hard to read and navigate the modal.
> feat(core): allow pipeline parameters to be required

- app/scripts/modules/kubernetes/src/container/environmentVariables.component.js
fixes a problem where deleting an environment variable would cause other
environemnt variable types to get messed up.
Fixes spinnaker/spinnaker#1866
ping @danielpeach
> fix(provider/kubernetes): fix envvar deletion

- app/scripts/modules/core/src/domain/IServerGroupManager.ts
- app/scripts/modules/core/src/index.ts
- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
- app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerTag.tsx
- app/scripts/modules/core/src/serverGroupManager/index.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.states.ts
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
Not worrying about styling yet because we haven't decided on an icon and this will only be visible to V2 Kubernetes users.
> feat(core): server group manager button on server group pod

- app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsExecutionDetails.html
The Jenkins stage error message is constructed after the initial template rendering, so there's a single render call that triggers the `no-reason` warning, but it's not valid and just adding noise.
> fix(core): hide jenkins failure message when controller not initialized

- app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.aws.controller.js
- app/scripts/modules/amazon/src/serverGroup/details/serverGroupDetails.html
A server group may have disabled instances (out of service) but NOT
itself be disabled.
> feat(amazon): Allow for enabling of a partially disabled server group

- app/scripts/modules/core/src/search/searchResult/Renderers.tsx
- app/scripts/modules/core/src/search/searchResult/SearchResultGrid.tsx
- app/scripts/modules/core/src/search/searchResult/searchResultsType.registry.ts
- app/scripts/modules/core/src/serverGroup/serverGroup.less
- app/scripts/modules/core/src/serverGroup/serverGroupSearchResultType.tsx
This PR fetches server group health counts when the server groups tab is selected.  The server groups are fetched in batches (of 25).  While fetching, a `<Spinner size="small" />` is shown in the Health column for each server group.
> feat(core/search): Add health counts to server groups search results

- app/scripts/modules/openstack/src/serverGroup/configure/wizard/access/AccessSettings.controller.js
Fixes bug in server group creation where selecting an account with multiple OpenStack accounts did not load Security Groups associated with that specific account.
> fix(provider/openstack): Update securityGroups after account change

- webpack.common.js
@anotherchrisberry let me know if I'm doing this wrong, but it seems like adding API_HOST there forces the default settings.js to use netflix's internal API_HOST as opposed to localhost:8084
> fix(webpack): remove API_HOST

- app/scripts/modules/core/package.json
* error message rendering for cluster locking failures
* fix(webpack): remove API_HOST
* feat(pagerduty): Support details field as a Map
> chore(core): Bump to 0.0.110

- app/scripts/modules/amazon/src/loadBalancer/configure/classic/createClassicLoadBalancer.controller.spec.ts
- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.spec.ts
- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
The moniker roughly triples the size of the cached security group in local storage.
In most installations, this is probably not a big deal, but Netflix has a large footprint in the cloud, and we're seeing security groups taking > 3 MB of local storage space, resulting in frequent cache quota overflows, which results in local storage clearing, which is...not great.
As far as I can tell, nothing is reading the moniker data for security groups from this data source, so this should not be a problem.
We need to reconsider our strategy for storing security groups in local storage, but in the interim, this is needed.
FYI @lwander @andrewbackes
> fix(core): omit moniker when caching security groups

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.html
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.html
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobStage.js
adds support for running jobs with multiple containers. will convert
existing `container` usage to `containers`
@danielpeach PTAL. for real this time. this is the final round of run job work.
> feat(provider/kubernetes): runJob multi container

- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
Not super sure why there wouldn't be anything under that key.
> fix(core): avoid NPE if security group cache does not exist

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.controller.js
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.html
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobLogs.html
add support for displaying logs for runJob
Clouddriver PR: https://github.com/spinnaker/clouddriver/pull/2164
@danielpeach @lwander PTAL! 
spinnaker/spinnaker#1832
> feat(provider/kubernetes): runJob logs

- app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.controller.js
- app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.html
- app/scripts/modules/core/src/instance/details/console/consoleOutputLink.directive.js
constrain modal height and add shortcut to end of the output by jumping
`pre` content to end.
@anotherchrisberry PTAL. I pulled the `800px` from the changes modal so it's not _totally_ arbitrary.
> feat(core): console output jump to end

- app/scripts/modules/core/src/insight/insightFilterState.model.ts
- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Supersedes https://github.com/spinnaker/deck/pull/4512
The react component is not aware of the Angular service value changing, so moving the `expanded` value into the component state (while still persisting the value in local storage).
Also removing a bunch of cruft in the Angular service, since it's a simple toggle now - it used to expand with some animation, but that was really janky.
The side filters on the executions view have not been toggle-able for about six weeks now, so I'm guessing most people don't use them.
> fix(core/executions): trigger filter collapse correctly

- app/scripts/modules/amazon/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
- app/scripts/modules/amazon/src/pipeline/stages/bake/bakeExecutionDetails.html
Not a lot going on here, just omitting the `<stage-failure-message>` tag if there's no message and directing the user more explicitly to the bakery logs.
> fix(amazon): provide better error message when bake stage fails

- app/scripts/modules/core/src/cluster/rollups.less
- app/scripts/modules/core/src/instance/Instances.tsx
- app/scripts/modules/core/src/presentation/main.less
We ran into an unusual application whose steady state is all instances being in a "starting" state. 
This would be fine if the application didn't have thousands of instances, but it does. So, right now, the browser is forced to animate thousands of nodes on the page in a constant cycle.
This PR addresses this by grouping the instances into a separate div and animating that div.
> fix(core): reduce starting instance animations

- app/scripts/modules/kubernetes/src/v2/manifest/edit/editManifestWizard.controller.ts
- app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestWizard.controller.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestWizard.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
- app/scripts/modules/kubernetes/src/v2/serverGroup/serverGroupCommandBuilder.service.ts
This way backingData & manifestText aren't stored in the pipeline definition. 
FYI @andrewbackes this might break any pipelines you've already created with this stage
> fix(provider/kubernetes): v2 move backing data out of stage

- app/scripts/modules/core/src/domain/ITrigger.ts
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsubTrigger.html
> feat(pubsub): support constraints

- app/scripts/modules/amazon/src/help/amazon.help.ts
- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeServerGroup.controller.js
- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeServerGroup.html
`clouddriver` can enforce that capacity of the server group being
resized has not changed in the background.
This addresses situations where autoscaling has occurred in the
background and subsequently been "undone" by a concurrent resize operation.
> feat(amazon): Support passing a capacity constraint during resize

- app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.controller.ts
- app/scripts/modules/kubernetes/src/v2/manifest/delete/delete.html
- app/scripts/modules/kubernetes/src/v2/manifest/delete/deleteOptionsForm.component.ts
Moving this form into it's own component will allow it to be re-used in the 'Delete Manifest' pipeline stage.
> fix(provider/k8sv2): Move delete manifest form into component

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
We typically change the `stageIndex` value, which triggers a re-render on the stage details when editing a pipeline and deleting a stage. 
If you delete the first stage, however, the details stick around, because we don't update the index. This just calls a broadcast so we do update the details.
> fix(core/pipelines): rerender view when first stage is removed

- app/scripts/modules/amazon/package.json
* fix(amazon): omit spinnaker metadata tags when cloning server groups
> chore(amazon): bump package to 0.0.55

- app/scripts/modules/kubernetes/src/kubernetes.settings.ts
- app/scripts/modules/kubernetes/src/proxy/ui.service.js
- settings.js
Not all Kubernetes systems have the same apiPrefix, so let it be configurable
like the instanceLinkTemplate.  Defaults to existing hard-coded apiPrefix value for backwards compatibility.
> feat(provider/kubernetes): Configurable apiPrefix for K8s

- app/scripts/modules/kubernetes/src/container/configurer.directive.html
- app/scripts/modules/kubernetes/src/container/configurer.directive.js
- app/scripts/modules/kubernetes/src/container/environmentFrom.component.html
- app/scripts/modules/kubernetes/src/container/environmentFrom.component.ts
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.html
- app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js
add support for envFrom pod option. this option allows users to specify
a config map of secret to use for environment variables.
@danielpeach PTAL!
spinnaker/spinnaker#2120
> feat(provider/kubernetes): support envFrom

- app/scripts/modules/core/src/application/nav/applicationNav.component.less
- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
If a pipeline is just waiting for a manual judgment to be made, there's no sense refreshing it every second.
Also making some clearly unrelated changes that can't be justified in the same PR
> fix(core/executions): do not auto-refresh manual judgment stages

- app/scripts/modules/kubernetes/src/container/environmentFrom.component.ts
the previous commit didn't handle the case for existing containers. new
containers worked fine becuase they got a new envFrom key when created.
ping @danielpeach
> fix(provider/kubernetes): fix existing envfrom

- webpack.common.js
Related to this: https://github.com/spinnaker/deck/pull/4469 having these env vars breaks the default settings.js since it always prefers to read from the user's environment than what's set in settings.js
@jtk54 FYI
> fix(build): remove default env vars

- app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js
The UI for overriding stage timeouts was not enabled for the Pipeline Stage.  Some pipelines may take longer than 12 hrs to run, so users should be allowed to choose the timeout.
> feat(core/pipeline): Expose "Override stage timeout" UI for Pipeline Stage

- app/scripts/modules/docker/src/pipeline/trigger/dockerTriggerOptions.directive.html
- webpack.common.js
We've had a few users click the "Run" button before the tags have loaded, which starts the pipeline without any tag.
> fix(docker): disable manual execution until tag selected

- app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js
- app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/basicSettings.html
fix an issue where i was calling forEach on an undefined property. if
the property doesn't exist, it will just pass an empty set. also,
iniContainers are not required.
ping @danielpeach 
fyi @andrewbackes @kevinawoo
> fix(provider/kubernetes): initContianers exiting

- app/scripts/modules/appengine/appengine.settings.ts
- app/scripts/modules/appengine/helpContents/appengineHelpContents.ts
- app/scripts/modules/appengine/serverGroup/configure/serverGroupCommandBuilder.service.ts
- app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
- app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.html
- app/scripts/modules/appengine/serverGroup/configure/wizard/configFiles.component.ts
- app/scripts/modules/appengine/serverGroup/transformer.ts
- settings.js
Currently feature flagged behind `providers.appengine.defaults.containerImageUrlDeployments`
> feat(provider/appengine): Enable flex deployments from image url

- app/scripts/modules/openstack/src/region/regionSelectField.directive.js
- app/scripts/modules/openstack/src/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
- app/scripts/modules/openstack/src/serverGroup/configure/wizard/location/basicSettings.html
Before, the Region selector in the server group details always defaulted to the first region choice. Now the region is properly populated from the server group details.
> fix(provider/openstack): Region Selector shows correct region

- app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.gce.controller.js
- app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.less
Prior to this change the menus for Cores and Memory (Gb) would appear underneath the wizard's sticky headers, blocking options somewhat.
Before:
After:
> style(provider/google): Fix react-style dropdown z-index in Instance Type Configurer

- app/scripts/modules/core/src/pipeline/config/stages/travis/modal/addParameter.controller.modal.ts
- app/scripts/modules/core/src/pipeline/config/stages/travis/modal/addParameter.html
- app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.html
- app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.module.ts
- app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.ts
Also, we remove the visualization of parameters already defined in the `.travis.yml` because they are always taken into account, if some user-defined parameter overrides some parameter the former will be used.
This is how it looks:
> feat(travis): set custom parameters using the UI

- app/scripts/modules/core/src/entityTag/entityTags.read.service.ts
I broke this when refactoring how we retrieve entity tags for server groups, so we currently are not showing cluster-level alerts/notices. This fixes that for @ajordens
> fix(core): add cluster level tags to server groups

- webpack.common.js
In the Pipelines view (`#/applications/{appname}/executions/configure/{guid}`) there is a JavaScript error related to [angular-ui/ui-sortable](https://github.com/angular-ui/ui-sortable/issues/518) on page load:
```
angular.js:14525 TypeError: element.sortable is not a function
at init (sortable.js:531)
at initIfEnabled (sortable.js:539)
at Object.link (sortable.js:550)
at angular.js:1346
at angular.js:10420
at At (angular.js:10426)
at f (angular.js:9815)
at a (angular.js:9055)
at f (angular.js:9809)
at angular.js:10154 "<div ng-model="pipeline.parameterConfig" ui-sortable="parametersCtrl.sortOptions" class="ng-pristine ng-untouched ng-valid ng-isolate-scope">"
```
Which breaks drag/drop of Parameters, etc.
As per https://github.com/angular-ui/ui-sortable/issues/518 adding the following to …
> fix(webpack): Fixes issue where jquery-ui was not correctly loaded by webpack

- app/scripts/modules/core/src/pipeline/service/executions.transformer.service.ts
Previously this caused a stack overflow because the refId and requisiteStageRefIds didn't match up.
> fix(core/pipeline): Fix execution graph of groups when MPT partial contains only one stage

- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/executionWindows.controller.js
In the Pipeline configuration screen (`#/applications/{app name}/executions/configure/{guid}`) when clicking on "Manual Judgement" in the Deploy panel the following `TypeError` is triggered:
```
TypeError: Cannot convert undefined or null to object
at toggleWindowJitter (executionWindows.controller.js:124)
at Scope.$digest (angular.js:17999)
at Scope.$apply (angular.js:18269)
at done (angular.js:12387)
at completeRequest (angular.js:12613)
at XMLHttpRequest.requestLoaded (angular.js:12541) undefined
```
This PR adds a small check to make sure `$scope.stage.restrictedExecutionWindow` exists before trying to `delete` its properties.
> fix(core/pipeline) Check to see if restrictedExecutionWindow exists

- app/scripts/modules/core/src/reactShims/react.injector.ts
Hoping this will silence some of those `state.go()` "transition aborted" messages.
> fix(core/reactShims): Add catch block to reactShims state.go() calls

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js
when populating the list of triggering images, if you had a trigger of
any other type (ex `cron`), the container list bomb. this only allows
triggers of type `docker` to be considered.
> fix(provider/kubernetes): fix runjob trigger image

- app/scripts/modules/amazon/src/pipeline/stages/cloneServerGroup/awsCloneServerGroupStage.js
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
This only affects new clone / deploy stages and is targeted at
better supporting instance types that are not yet natively supported
by `clouddriver`.
An edge case exists when a server group is created with the
default block device mappings for "unknown" instance types.
Subsequent clones of this server group will carry forward this
set of block device mappings even after support for the new instance
type has been added to `clouddriver`.
> fix(amazon): Default `copySourceCustomBlockDeviceMappings` to false

- app/scripts/modules/core/src/help/help.contents.ts
Make more explicit distinction between Pub/Sub Payload Constraints vs. Expected Artifacts.  Payload constraints run before a payload body is processed with a jinja template while artifact fields are checked after the jinja transformation takes place.
> feat(provider/google): Clarify help messages for pubsub fields.

- app/scripts/modules/core/src/pipeline/create/CreatePipelineButton.tsx
- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
Making it much more explicit you need to create a new pipeline config to do anything useful with the executions view.
Current:
PR:
Closes https://github.com/spinnaker/spinnaker/issues/2223
> fix(core): remove "0" from filter list when no pipelines present

- app/scripts/modules/amazon/package.json
* fix(amazon): Default `copySourceCustomBlockDeviceMappings` to false
* fix(amazon): fresh new spinners
> chore(amazon): bump package to 0.0.58

- app/scripts/modules/core/src/insight/insightFilter.component.html
- app/scripts/modules/core/src/presentation/main.less
This has probably been broken for a really long time but nobody uses it?
> fix(core): allow side filters to be collapsed

- app/scripts/app.ts
- package.json
- yarn.lock
Requires us to temporarily downgrade react, prop-types, and react-dom in deck's package.json.  With higher versions of those packages yarn considers them in conflict with kayenta and doesn't hoist them to the root node_modules directory.  Webpack is then unable to find them during build.
> feat(core): import kayenta

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/serverGroupWizard.html
- app/scripts/modules/core/src/presentation/main.less
Ran into a confusing case where there were invalid fields in a cluster config, but no fields were highlighted because the user was editing the cluster and hadn't touched the fields, which is a little confusing.
> feat(core): enable highlighting of invalid pristine fields

- app/scripts/modules/core/src/application/modal/createApplication.modal.controller.js
- app/scripts/modules/core/src/application/modal/editApplication.controller.modal.js
- app/scripts/modules/core/src/application/modal/editApplication.html
- app/scripts/modules/core/src/application/modal/newapplication.html
- app/scripts/modules/core/src/pipeline/config/triggers/git/git.trigger.ts
Gitlab scm support was added to igor in spinnaker/spinnaker#2047 .This extends that addition to deck.
This also allows the gitSources to be overridden in configuration via settings.js/settings-local.js.
> feat(gitlab) - Add gitlab as a gitSource and allow gitSources to be configured via settings.js

- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/executionWindows.html
The recent change was meant to handle a case where this flag was set with a parameter, but unfortunately prevented the checkbox from functioning as a toggle in any other case.
This exposes the parameterized version if applicable. Not providing an easy way to set the parameter (users will still need to edit the JSON directly), but it at least exposes the parameterized field.
cc @archana-s
> fix(core): handle execution window expressions gracefully

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Also moving some logic into the `componentWillMount` method to get rid of a React warning about calling `setState` in a constructor.
> fix(core/pipelines): do not show no pipelines message while initializing

- app/scripts/modules/core/src/application/application.model.spec.ts
- app/scripts/modules/core/src/application/service/application.read.service.spec.ts
- app/scripts/modules/core/src/loadBalancer/LoadBalancers.tsx
- app/scripts/modules/core/src/loadBalancer/loadBalancer.dataSource.ts
- app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
- app/scripts/modules/core/src/securityGroup/securityGroup.dataSource.ts
People don't frequently visit these pages, so most of the background fetching is a waste of time/resources.
I considered doing the same thing to the clusters tab, but that felt sluggish, as that and the pipelines tab are the two most frequently visited tabs.
> perf(core): lazy load data for load balancers, security groups

- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeCapacity.component.html
- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeCapacity.component.ts
- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeServerGroup.html
For the majority of use cases, pinning capacity at a fixed size while a scaling policy is in effect is not a desirable state, and will lead to the appearance of the scaling policy 'not working'. This adds a yellow warning section below the capacity resize inputs when the chosen capacity range would result in scaling policies becoming ineffective.
> feat(amazon/serverGroup): warn that scaling policies will not work when capacity is pinned

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.html
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
adds support for preconfigured webhook parameters. these parameters can
be set in orca's config and are then exposed to users. instead of
expecting users to fillout an entire payload, these parameters can be
used to expose the important parts and abstract the other configuration
away.
related orca pr: spinnaker/orca#1887
@anotherchrisberry @ajordens PTAL
> feat(webhooks): preconfigured webhook params

- app/scripts/modules/core/src/presentation/main.less
Currently when you scroll to the bottom of the filter sidebar it's not entirely obvious you've reached the end. This adds a little bit of padding to the bottom of the inner content element as an affordance.
cc @archana-s
> fix(core/presentation): Add padding to filter sidebar as a scrolling affordance

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
Artifacts are "bound", not "deployed"
> fix(provider/kubernetes): Fix label wording

- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
> fix(amazon/loadBalancer): Show region and account when deleting a load balancer

- app/scripts/modules/core/src/task/monitor/taskMonitorStatus.component.js
This loader sits on its own line, so should be three bars, not one
> fix(core): use small loader instead of nano on task monitor

- app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx
We consider when the side filters change, but not when the actual data changes. If a server group appears or disappears, we need to invalidate the cache so heights are recalculated.
> fix(core): reset cluster measure cache when groups update

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
Manifests can be provider through artifacts so this field is now optional.
> fix(provider/kubernetes) - manifests can be provided now through artifacts

- app/scripts/modules/openstack/src/serverGroup/configure/wizard/location/ServerGroupBasicSettings.controller.js
Previously, when changing the region when creating a new openstack server group the subnet list did not update. This is because there wasn't a watch on the region changing. This has now been fixed.
> fix(provider/openstack): Subnet list now updates on region change

- app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.html
- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/atlasGraph.component.ts
The size and message attributes need to be wrapped in single quotes when used in as an Angular component.
Also changing these two to size medium, which includes the the "loading..." message and centers the loading bar.
@archana-s what do you think about center-aligning the small loader?
> fix(core/amazon): wrap spinner size in quotes

- app/scripts/modules/core/src/forms/mapEditor/mapEditor.component.html
- app/scripts/modules/core/src/forms/mapEditor/mapEditor.component.js
- app/scripts/modules/core/src/forms/mapEditor/mapEditor.component.spec.js
> feat(core): map editor hidden keys

- app/scripts/modules/google/src/address/address.reader.ts
- app/scripts/modules/google/src/backendService/backendService.reader.js
- app/scripts/modules/google/src/certificate/certificate.reader.ts
- app/scripts/modules/google/src/healthCheck/healthCheck.read.service.ts
We previously used /search to query the infrastructure caches and
suggest several types of components in the UI. There was a recently
added constraint that requires /search queries to provide a string
`>=` length 3, which broke our cache queries. This change is a temporary
fix/workaround to fix the contract breakage.
> fix(provider/gce): Fix search endpoint calls.

- app/scripts/modules/core/src/domain/IExecution.ts
- app/scripts/modules/core/src/domain/IPipeline.ts
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/executions/executions.less
- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Add a small table icon to the group header / execution title of pipelines that are based on templates.
Open to suggestions on better icon choice.
Includes a tooltip on hover:
> feat(core): Indicate templated pipelines

- app/scripts/modules/core/src/instance/InstanceListBody.tsx
Re-add the `data-instance-id` attr that was lost in #4733 so that clicking on instances in the details view works.
Separately, we should go back and set this up as an onClick handler on each row now that React is handling the event delegation (once we confirm there's no negative perf impact).
> fix(core/instance): Make navigating to instance details work again post-React-rewrite

- app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.less
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
A small change to add an indicator when entered manifest YAML isn't valid.
> fix(provider/kubernetes): add error message when manifest yaml isn't valid

- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Refresh pipeline executions when a manual execution fails, so the
failure is surfaced in the UI. Update polling for executions to look
for the specific execution, rather than looking for all running executions
and filtering in JavaScript.  This fixes a bug leading to infinite
polling if the execution ended up in a non-running status before the
first poll.
> fix(pipelines): Fix polling for manual execution

- app/scripts/modules/core/src/help/help.contents.ts
Screenshot of the new message:
> fix(pipelines/help): explains when concurrent pipelines get canceled

- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Small fix to replace explicit use of $q.defer with directly
returning a promise.
> style(pipelines): Remove explicit use of $q.defer

- app/scripts/modules/core/src/instance/InstanceListBody.tsx
The checkbox click handler is fighting with body click handler (and apparently the `event.stopPropagation()` call isn't stopping propagation, go figure)
> fix(core): allow multiselect toggling on instance checkbox click

- app/scripts/modules/core/src/cloudProvider/versionedCloudProvider.service.ts
- app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
- app/scripts/modules/core/src/overrideRegistry/Overrides.tsx
- app/scripts/modules/core/src/overrideRegistry/index.ts
- app/scripts/modules/core/src/overrideRegistry/override.registry.ts
- app/scripts/modules/core/src/reactShims/AngularJSAdapter.tsx
feat(core/reactShims): Add templateUrl support to AngularJSAdapter react component
Migrate ServerGroupDetails and ApplicationIcon to use @Overridable() decorator.
> feat(core/overrideRegistry): Add react component decorators to enable UI overrides

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
When cloning an existing ASG, the expectation is the user should not have to go to the Advanced Settings section and change anything. Right now, if the user has custom EBS mappings, those will _not_ be copied over when cloning unless the user goes and selects the correct option, which is a big surprise.
> fix(amazon): copy EBS volumes when explicitly cloning an ASG

- app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx
I had optimized this for the wrong scenario (absolute worst case), which negatively affects 99.9% of the actual real world scenarios.
> fix(core): eagerly fetch more than one cluster grouping pod

- app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.spec.js
- app/scripts/modules/core/src/account/account.service.spec.ts
- app/scripts/modules/core/src/account/account.service.ts
- app/scripts/modules/core/src/chaosMonkey/chaosMonkeyExceptions.component.spec.ts
- package.json
- yarn.lock
Companion PR to spinnaker/gate#502 and spinnaker/clouddriver#2326
We have all the details in the list of credentials now, so we can stop calling it separately in the UI, and just maintain a local cache.
> refactor(core): limit calls to /credentials

- app/scripts/modules/core/src/presentation/details.less
We have some details panels with buttons and dropdowns.
The dropdowns have `btn-sm` in them, so...
> fix(core): consistent button sizing in details panels

- app/scripts/modules/core/src/cluster/rollups.less
My OCD was hurting
Before:
After:
> fix(core/cluster): Vertically align icons and make them the same size

- app/scripts/modules/core/src/account/AccountTag.tsx
If a provider returns a response without a challengeDestructiveActions field then that value is cached as `undefined`.  The `typeof` check on line 44 will then assume that the cache is holding a Promise (since the value isn't a bool) and attempt to call `.then` on undefined.
Before (appengine provider):
After: no error.
> fix(core): handle challengeDestructiveActions being undefined in API response

- app/scripts/modules/appengine/serverGroup/configure/wizard/basicSettings.controller.ts
I don't understand why this and https://github.com/spinnaker/deck/pull/4766 are suddenly needed in the appengine provider.  It feels like some API response changed format dramatically but I've tried bisecting back a bit in the commit histories of deck/gate/orca/clouddriver but can't find where this issue was introduced.  Nonetheless, this PR works around the issue of account git credentials being undefined in appengine.
Console error when adding server group:
Missing account dropdown in basicSettings screen:
Error removed and account dropdown appears correctly.
> fix(provider/appengine): dont throw error when git credentials are missing

- app/scripts/modules/core/src/entityTag/notifications/notifications.less
People with scroll bars always enabled see this on clusters with alerts:
I fought this for a while and this seemed like the least harmful fix.
> fix(core): shrink tag marker to fit better in cluster header

- app/scripts/modules/core/src/cluster/allClusters.html
Only noticeable when users have their scrollbars set to always show and they toggle some filters in the clusters view, going from a view where the cluster groupings are too tall to where they are not.
See https://github.com/bvaughn/react-virtualized/issues/773
> fix(core): avoid flickering scrollbars in clusters view

- app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.spec.ts
- app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
- app/scripts/modules/core/src/pagerDuty/pagerDutySelectField.component.ts
- app/scripts/modules/core/src/serverGroupManager/serverGroupManager.service.ts
A few imports referencing `@spinnaker/core` made their way into the core package itself. This doesn't cause problems in the majority of cases (which _I think_ is due to having an alias setup in the webpack config). When using `npm link`/`yarn link` to work on projects that import `@spinnaker/core`, though, webpack fails to resolve any imports for `@spinnaker/core` that live inside the core package. In general we should be importing things internal to core using the `core/*` alias or relative imports anyway, so this does a simple swap on the import references.
cc @jrsquared @danielpeach since both of you touched these.
> fix(core): Don't use '@spinnaker/core' imports inside core package

- app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionConfig.html
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/defaultDocker.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/defaultGcs.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/defaultGithub.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts
Now the "default" set of artifacts will actually be useful. For example, entering a docker image will allow the correct image & version to bind in a downstream stage - previously the image reference would be missing and binding would fail.
> feat(artifacts): better default artifact behavior

- app/scripts/modules/core/src/account/account.service.ts
- app/scripts/modules/core/src/cache/cacheInitializer.service.spec.ts
- app/scripts/modules/core/src/chaosMonkey/chaosMonkeyExceptions.component.spec.ts
- Add `getAllAccounts` to return `IAccountDetails` metadata for all accounts
- Passthrough other APIs such as `getAccountDetails` through getAllAccounts
- `getAccounts` continues to return only accounts the user is authorized for
> fix(core/*): Fix viewing of account badges, and servergroup/instance/foo details for accounts you don't have access to

- app/scripts/modules/core/src/account/account.service.ts
- app/scripts/modules/core/src/domain/IStageTypeConfig.ts
- app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.spec.ts
- app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
~Providers are passed around as strings when assessing whether stages support them or not.  Both the kubernetes v1 and the kubernetes v2 provider share a provider string of `kubernetes`.  Therefore the stage filtering assumes that any stage supported by v1 is also supported by v2 but this is not the case.~
~This workaround allows a field to be added to a stage that lists specific provider versions that it doesn't support.  After the initial set of stages is filtered via provider strings, a second round of filtering is performed to remove any stage where the set of accounts for this application are entirely excluded by the stage's type.~
~This solution doesn't feel quite right but I can't see a way past this problem without a large refactor such that everywhere we pass a provider string we …
> fix(provider/kubernetes): exclude stages when k8s v2 is the only provider

- app/scripts/modules/amazon/src/cache/cacheConfigurer.service.js
- app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
- app/scripts/modules/amazon/src/instance/awsInstanceType.service.spec.js
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.html
- app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts
I ran through this a bunch of times today, and I honestly don't think we get anything by keeping these items in local storage, aside from annoying users when the cache gets wiped out because we run out of space.
The endpoints in question load in around 2s for us (and I suspect we have more load balancers in AWS than most Spinnaker users), and they take up quite a bit of local storage space.
I don't think we can get rid of security groups yet, but maybe we can figure that out some day.
@jrsquared or @christopherthielen feel free to merge next week, or leave it for the following week.
> refactor(amazon): remove local storage caches: instance types, load balancers

- app/scripts/modules/core/src/cluster/DefaultClusterPodTitle.tsx
- app/scripts/modules/core/src/cluster/rollups.less
- app/scripts/modules/core/src/entityTag/notifications/notifications.less
- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
I was pretty sure I had fixed this a couple of weeks ago by shrinking the font size of the `tag-marker` class but I hadn't, so now I'm converting a bunch of the header contents to flexbox using the style guide.
> fix(core): avoid scrollbars in cluster pod header

- app/scripts/modules/kubernetes/src/instance/details/details.controller.js
deregister and register from/to LB actions werent working due to a
missing namespace.
fixes spinnaker/spinnaker#2340
@lwander @danielpeach i'll cherry pick this over into the 1.6.x branch once merged.
> fix(provider/kubernetes): fix instance dereg lb

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/pipeline.states.ts
We've had a few folks ask for this functionality in the past - provide a way to invoke the manual execution modal from a deep link.
> feat(core/pipelines): allow triggering of execution via deep link

- app/scripts/modules/core/src/loadBalancer/LoadBalancerPod.tsx
- app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.directive.html
- app/scripts/modules/core/src/securityGroup/securityGroupPod.html
Missed these yesterday when scanning the codebase as part of https://github.com/spinnaker/deck/pull/4836
> fix(core): restore pod header widths to fill container

- app/scripts/modules/core/src/insight/insight.less
- app/scripts/modules/core/src/presentation/main.less
- app/scripts/modules/core/src/styleguide/public/styleguide.html
It's CSS so it'll probably screw something else up but we can deal with that when we find it.
(This probably only affects Netflix, unless someone else has customized the header for the AWS server group panel and added another menu)
Before:
After:
> fix(core): allow overflow on details panel for menus

- app/scripts/modules/canary/canary/canaryStage.transformer.js
The other option is to do
```
monitorStage = { context: {} };
```
and let the rest of the code run using the mock stage
> fix(core/canary): don't die if the `monitorCanary` synthetic stage is missing

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsub.trigger.ts
- settings.js
This should pull from settings.js if configured, and if not fall back to the old behavior. Is there anything else I need to do to pull the list of pubsub providers from deck settings?
> feat(pubsub): pubsub providers list pulled from settings

- app/scripts/modules/core/package.json
* fix(core/canary): don't die if the `monitorCanary` synthetic stage is not present
* feat(pubsub): pubsub providers list pulled from settings
> chore(core): bump package to 0.0.150

- app/scripts/modules/core/src/pipeline/config/pipelineConfigProvider.ts
- app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts
Stages available in an application configured only with a V1 Provider, Before & After:
> fix(provider/kubernetes): exclude manifest stages from v1

- app/scripts/modules/core/src/index.ts
- app/scripts/modules/core/src/utils/failedToInstantiateModule.ts
- app/scripts/modules/core/src/utils/index.ts
- app/scripts/modules/core/src/utils/q.d.ts
Also add typescript overload to $q for normalizing a real promise into a fake angularjs promise.
fixes typings of :
`const stringPromise = $q.when(Promise.resolve('foo'))`
before, stringPromise was an `IPromise<Promise<string>>`
now, it will be an `IPromise<string>`
> feat(core/angular): Improve error message when angular module dep is undefined

- app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
- app/scripts/modules/core/src/presentation/ModalService.tsx
- Render the Modal component automatically
- Pass a Component class, instead of a bunch of JSX.Element
- Provide closeModel/dismissModal callbacks to the contents component
> refactor(core/presentation): Change how ReactModal works

- app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
`manifestController` is now a required, injected dependency of `kubernetesV2ManifestDeleteCtrl` but this isn't caught by type-checking because uibModal resolves the deps at runtime.  No-op needs to be provided for all users of that controller: loadBalancer details, instance details, security group details, and server group manager details.
Before fix, delete modal doesn't appear and error appears in console:
After fix, delete modal correctly appears:
> fix(provider/kubernetes): delete action broken for all but server groups

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
- app/scripts/modules/core/src/pipeline/config/triggers/jenkins/jenkinsTriggerOptions.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/jenkins/jenkinsTriggerOptions.directive.spec.js
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTrigger.module.js
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.spec.js
- app/scripts/modules/core/src/pipeline/config/triggers/travis/travisTriggerOptions.component.spec.ts
- app/scripts/modules/core/src/pipeline/config/triggers/travis/travisTriggerOptions.component.ts
- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/execution.less
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.spec.js
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/docker/src/pipeline/trigger/dockerTriggerOptions.directive.js
Adds an icon next to completed executions, allowing users to trigger a re-run of the pipeline with the same parameters (and build, for Jenkins).
> feat(core/executions): allow pipeline rerun with same parameters

- app/scripts/modules/core/src/account/account.service.ts
- app/scripts/modules/core/src/cache/cacheInitializer.service.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js
@jrsquared @ethanfrogers @lwander 
This (hopefully) fixes an issue when adding a stage to a pipeline.  It seems there was some `$q` trickery going previously, which was lost when wrapping a native promise as a `$q` promise `$q.when(observable$.toPromise())`.  I suspect this was due to the `$q` promise participating in the existing AngularJS digest cycle, while the wrapped promise was executing after an event loop tick.
This switches the `BaseProviderStageCtrl` to use an observable API which executes synchronously, when possible.
> fix(core/pipeline): Fix pipeline config - add stage that uses BaseProviderStageCtrl

- app/scripts/modules/core/src/domain/IExecution.ts
- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Ran into this today, looking at executions that were cancelled due to concurrent execution configuration.
> fix(core): allow grouping by time on cancelled executions

- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
There's a potential race condition when saving a pipeline: if the data source is already loading when the pipeline save starts, the save success handler could try to refresh without doing anything. Then the user gets an error message that is slightly confusing, and most users will just try to re-save the pipeline, which won't work because it's already saved successfully.
This just forces a refresh of the configs to avoid that situation.
> fix(core/pipelines): force data refresh on pipeline creation

- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
- app/scripts/modules/core/src/help/HelpMenu.less
- app/scripts/modules/core/src/help/HelpMenu.tsx
This PR adds a help menu in the app's header, to the right of the Search and, if present, the What's New button:
These screenshots show help without the optional Auth menu and What's New button:
> feat(core) add a help menu with links to docs and community

- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/parameters/parameter.html
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html
Parameters can be pretty unfriendly to end users, since we just display the name. This allows people to optionally include a label on the parameters.
> feat(core/pipelines): allow user-friendly labels on pipeline parameters

- app/scripts/modules/core/src/cluster/cluster.service.ts
- app/scripts/modules/core/src/cluster/task.matcher.ts
If a custom stage is created, this allows the stage name and matcher to be registered with a global TaskMatcher service
> feat(core/cluster): Allow task matchers to be configured from deck-customized

- app/scripts/modules/core/src/search/global/GlobalSearch.tsx
- app/scripts/modules/core/src/search/global/GlobalSearchRecentItems.tsx
- app/scripts/modules/core/src/search/infrastructure/ProjectSummaryPod.tsx
- app/scripts/modules/core/src/search/infrastructure/RecentlyViewedItems.tsx
- app/scripts/modules/core/src/search/infrastructure/SearchResultPod.tsx
- app/scripts/modules/core/src/search/infrastructure/SearchResultPodItem.tsx
- app/scripts/modules/core/src/search/infrastructure/SearchResultPods.tsx
I thought we were capturing analytics on recent items clicks, but we are not.
Adding this to check our assumptions on whether there is value showing recent items that are _not_ applications...
> chore(core): add analytics to recently viewed items

- app/scripts/modules/core/src/domain/IExecutionTrigger.ts
- app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
Adds an asterisk to indicate default artifacts used in an execution, and includes the phrase "Default Artifact" in the artifact's tooltip.
---
fixes https://github.com/spinnaker/spinnaker/issues/2329
> feat(provider/kubernetes): delineate default artifacts in executions

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
Avoids a race condition that can happen if the save completes while the pipeline configs are refreshing, and the user immediately goes back to the executions view to run the pipeline.
> fix(core/pipelines): force refresh pipeline configs after save completes

- app/scripts/modules/core/src/notification/modal/editNotification.controller.modal.js
- app/scripts/modules/core/src/notification/modal/editNotification.less
- app/scripts/modules/core/src/notification/types/slack/additionalFields.html
We wanted to add a little `#` channel indicator in the common Slack notification input we use across the UI. I've intentionally done it in a less-than-reusable way since I'd like to get inputs with before/after annotations into the style guide shortly and didn't want to duplicate work.
> feat(core/notification): Add a quick one-off slack channel affordance

- yarn.lock
People (myself included) have been getting errors installing `fsevents`. Turns out the version of `fsevents` that's resolved for `fsevents@^1.0.0` in the lockfile is `v1.1.1`, which is exactly one patch version before the package started including binaries for node 8.
Since the packages depending on `fsevents` don't need to be updated, I just went in and manually resolved `fsevents@^1.0.0` to `v1.1.3`, given that we're already using that version for some other packages without issue.
Seems to work great upon basic testing.
> fix(package): Manually bump lockfile entry for fsevents@^1.0.0

- app/scripts/modules/kubernetes/src/validation/applicationName.validator.js
Dashes in application names are allowed for applications created by the Kubernetes v2 provider using moniker annotations.
Users should be allowed to create applications containing dashes when using the Kubernetes provider, but be warned that such names should only be used for v2.
In particular, this is important in order to be able to create the application in deck and then provision templated pipelines using roer.
> fix(provider/kubernetes): Show warnings for dashes in app names

- app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts
The "You don't have any expected artifacts" message currently shows
when there are in fact artifacts.
> fix(artifacts): Fix no expected artifacts message

- app/scripts/modules/core/src/search/infrastructure/RecentlyViewedItems.tsx
- app/scripts/modules/core/src/search/infrastructure/search.infrastructure.module.js
- app/scripts/modules/core/src/search/infrastructure/searchResultPods.component.ts
Also removing the `searchResultPods` angular component - I cannot find any matches for `search-result-pods` in the codebase.
Tested this with both v1 and v2 search versions.
> fix(core): correct category on recently viewed analytics events

- app/scripts/modules/google/src/address/address.reader.ts
- app/scripts/modules/google/src/backendService/backendService.reader.js
- app/scripts/modules/google/src/certificate/certificate.reader.ts
- app/scripts/modules/google/src/healthCheck/healthCheck.read.service.ts
The call to get current backends is returning no results
as the query string needs to be at least 3 characters. Use the
allowShortQuery parameter to override this behavior.
> fix(provider/gce): Fix call to list backends

- app/scripts/modules/core/src/search/infrastructure/SearchResultPods.tsx
- app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
- app/scripts/modules/core/src/search/searchResult/SearchResultGrid.tsx
Couple of things:
1) I got rid of the "Please enter a search query to get started" text, because it was kind of useless and mostly just added visual noise.
2) Now when there's no recent history, we won't show the awkwardly orphaned "Recently Viewed" header above... nothing at all.
> fix(core/search): Get rid of useless prompt, hide 'Recently Viewed' header if no history

- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/manifest/showManifestDetails.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/showManifestYaml.component.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html
- app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.controller.ts
This is a first pass at https://github.com/spinnaker/spinnaker/issues/2327
Deployments and ReplicaSets now get linked from deploy pipelines to their respective details panels in the clusters view.
From here:
To here:
> feat(provider/kubernetes): link to resources next to YAML in deploy pipeline

- app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js
Seems this was always possibly broken, but some change in my chrome
caused this to happen very frequently. What was happening was a call to
lookup an account in the accountMap was being scheduled while it wasn't
set, causing the namespace validation to fail.
> fix(provider/kubernetes): v1 namespace lookup

- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/ExecutionWindowActions.tsx
- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/executionWindows.controller.js
- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/executionWindows.html
- app/scripts/modules/core/src/pipeline/config/stages/templates/index.ts
We have some users who want to make it much more explicit what will happen when an execution window is skipped, e.g. **This will cause the deployment to proceed outside normal business hours. Are you sure you want to do this?**
Seems like a reasonable ask.
> feat(core): allow custom warning when users skip an execution window

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/templateSelection/templateSelection.html
- app/scripts/modules/azure/serverGroup/configure/wizard/templateSelection.html
- app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/templateSelection.html
- app/scripts/modules/core/src/serverGroup/configure/common/deployInitializer.component.html
- app/scripts/modules/core/src/serverGroup/configure/common/deployInitializer.component.ts
- app/scripts/modules/dcos/serverGroup/configure/wizard/templateSelection.html
- app/scripts/modules/ecs/serverGroup/configure/wizard/templateSelection/templateSelection.html
- app/scripts/modules/google/src/serverGroup/configure/wizard/templateSelection/templateSelection.html
- app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/templateSelection.html
- app/scripts/modules/openstack/src/serverGroup/configure/wizard/templateSelection.html
- app/scripts/modules/oracle/serverGroup/configure/wizard/templateSelection/templateSelection.html
The template selection modal that appears when adding a new server
group in a 'Deploy' stage should dismiss when clicking the 'x'.
> fix(core): Fix dismissal of new server group template modal

- app/scripts/modules/kubernetes/src/v2/manifest/showManifestDetails.component.ts
Not a big deal, but prevents the `@spinnaker/kubernetes` NPM package from being built.
> fix(kubernetes): fix import

- app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
Static methods were missing from Overridable components
> fix(core/overrideRegistry): Copy static class properties to Overridable component

- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/executionGroup.less
Spinner that shows up next to "Start manual execution" link button in the executions page was off. Fixed it.
> style(core): Fixed a bad spinner

- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.html
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTriggerOptions.directive.spec.js
When selecting an execution for a pipeline triggered pipeline, it's hard to differentiate between the executions, as they are only displayed as a date/time and the execution status.
This PR adds some more information, if present. It works as long as the `scm` property of the trigger is set.
I'll probably do the same for the build triggers later.
> feat(core/triggers): More relevant info when selecting execution

- app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/presentation/Popover.tsx
- app/scripts/modules/core/src/presentation/Tooltip.tsx
Markdown is pretty great. This will let folks use it in their pipeline descriptions, and let engineers use it instead of vanilla HTML when creating help fields and other tooltips.
> feat(core): support markdown in tooltips and popovers

- app/scripts/modules/core/src/artifact/artifact.module.ts
- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/artifact/imageSourceSelector.component.ts
- app/scripts/modules/core/src/artifact/index.ts
- app/scripts/modules/core/src/cluster/cluster.service.ts
- app/scripts/modules/core/src/domain/ICluster.ts
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
- app/scripts/modules/core/src/serverGroup/configure/common/deployInitializer.component.ts
- app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
- app/scripts/modules/google/src/help/gce.help.ts
- app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
- app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
The deploy stage for the GCE provider now gives the option of deploying a specified upstream artifact rather than deploying the result of the most recent Bake or Find Artifact stage.
> feat(artifacts): Enable GCE deploy stage to deploy an artifact

- app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
Not sure if this broke with the React 16 upgrade or ??? but the `this.pages` array is only populated by the `onMount` call, so it is empty the first time through, and a bunch of NPEs get thrown and the modal doesn't open and people can't edit the load balancers.
> fix(core): avoid rendering wizard pages before they have registered

- app/scripts/modules/core/src/cluster/cluster.service.ts
- app/scripts/modules/core/src/serverGroup/serverGroup.transformer.js
If a server group is part of a cloud provider that is not configured, no cluster data ends up being loaded for any application that includes server groups in that provider, which seems wrong (it implies there are no server groups at all). It's probably better to just strip out the unsupported server groups.
We see this frequently during local development on the OSS codebase for applications that have a mix of AWS and Titus.
> feat(core): omit unsupported cloud provider data from clusters

- app/scripts/modules/core/src/help/HelpField.tsx
Allow links such as `<a target="_blank" href="http://blah.com">Blah</a>` to open in a new window
> fix(core/help): Allow target="_blank" in links in help popover

- app/scripts/modules/amazon/src/serverGroup/details/resize/resizeServerGroup.controller.js
Since adding a capacity constraint option for server group resizes, we've realized that for the majority of ad-hoc resizes capacity constraints are not a helpful protection. In the worst case, this can lead to urgent resizes being delayed due to the initial attempt failing and the user needing to go back and retry with capacity constraints turned off.
For now, the fastest path to fixing this problem is to change the default state so that capacity constraints are opt-in. Going forward, there may be more we can do to simplify along the lines of better messaging and/or allowing users to choose a single capacity setting they'd like to affect (i.e. only modify `desired` while leaving other processes free to modify `min`/`max`).
cc @emjburns
> feat(amazon/serverGroup): Change default capacity constraint to off

- app/scripts/modules/core/src/pipeline/details/stageSummary.component.ts
I don't know who would ever set the comment to a number via SpEL, but if they did, it would cause a lot of exceptions to be thrown.
> fix(core): ensure stage comments are in string format

- app/scripts/modules/core/src/pipeline/config/stages/wait/SkipWait.tsx
I'm not sure what is causing this, but the popover label for the wait stage (when it is running) re-mounts at least once a second, so the `OrchestratedItemRunningTime` object never gets a chance to set the remaining time field, so it's never rendered.
The frequent remounting is an interesting and potentially bigger problem, but I'm not sure why that is happening.
> fix(core): render remaining wait on wait stage popover

- app/scripts/modules/core/src/pipeline/config/stages/wait/SkipWait.tsx
- app/scripts/modules/core/src/pipeline/config/stages/wait/WaitExecutionDetails.tsx
Basically restoring all the code I deleted yesterday when I was sure it wasn't needed. Turns out it is needed, as we don't re-mount the stage details, just re-render (I forgot how React works).
Since the popover re-mounts all the time, we still need to render it immediately, so I've just added an `autoRefresh` prop to the component.
> fix(core): count down remaining time in wait stage details

- app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
> fix(amazon/loadBalancers): Show target group sticky status appropriately

- app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
Updating a listener to switch from `HTTPS` to `HTTP` would cause the AWS API to fail because the  `certificates` and `sslPolicy` fields are still provided.
> fix(amazon/loadBalancers): Remove cert and ssl policies when submitting http listener

- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.controller.js
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.html
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobLogs.html
Run Jobs that generate a large amount of log output can dramatically slow down loading of the pipeline executions screen in deck.
This PR sends an `expand` query param when fetching executions history and, by default, sets it not to fetch logs.  Fetching console output is now done when the user clicks on the `Console Output` link in the RubJob stage details.
see related PRs for gate https://github.com/spinnaker/gate/pull/515 and orca https://github.com/spinnaker/orca/pull/2061
Here's what a loading runJob log looks like:
> feat(provider/kubernetes): trim runJob logs from executions until explicitly requested

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.html
- app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
If someone has added a SpEL based load balancer or target group to a deploy config, then goes to edit that deploy config in the UI, it will remove them because they don't string match existing ones.
This basically trusts load balancers or target groups that have a `${` in them as being 'valid' so it will not remove them.
> fix(amazon/deploy): Do not destroy SpEL based load balancers in deploy config

- start.sh
previously, start.sh depended on a variable set by `npm run` to determine the desired node version.  Now, it reads it directly from `package.json`.  This allows somebody to run `./start.sh` directly instead of requiring `npm run start`.
Also improved nvm messages printed to console.
> feat(start.sh): improve nvm handling in start.sh

- app/scripts/modules/amazon/package.json
fix(amazon/serverGroups): Unable to open "Edit Scheduled Actions" modal 
fix(amazon/securityGroup): ingress selector would try to eagerly load vpcs so set empty default 
fix(amazon/deploy): Do not destroy SpEL based load balancers in deploy config 
refactor(core/task+amazon/common): Reactify UserVerification and AwsModalFooter 
fix(amazon/loadBalancers): Remove cert and ssl policies when submitting http listener 
fix(amazon/loadBalancers): Show target group sticky status appropriately
> chore(amazon): bump package to 0.0.83

- app/scripts/modules/core/src/help/help.contents.ts
Trying to make the behavior of conditional on expression more obvious. Users have been confused because this option simply removes the stage from the stage graph instead of stopping the whole branch of the pipeline.
> fix(tooltip): updating conditional on expression tooltip

- app/scripts/modules/core/src/pipeline/config/stages/wait/SkipWait.tsx
- app/scripts/modules/core/src/pipeline/config/stages/wait/WaitExecutionDetails.tsx
- app/scripts/modules/core/src/presentation/HoverablePopover.tsx
The arrow function causes a lot of unneeded re-renders when a template is passed in instead of a Component.
The rest of the PR just reverts changes made to the wait stage components to work around the underlying issue...
> fix(core): avoid excessive rerender on popovers with templates

- app/scripts/app.ts
Deck depends on Angular elements being jQuery objects, unfortunately.
> fix(core): load jQuery before Angular

- app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
There's a race condition where the security groups view sometimes does not render when switching between tabs - it gets stuck in the "loading" state.
I won't pretend to understand why this fixes the problem. It, uh, just does.
> fix(core/securityGroups): ensure security groups view renders when ready

- app/scripts/modules/core/src/application/application.module.ts
- app/scripts/modules/core/src/application/nav/applicationNav.component.ts
- app/scripts/modules/core/src/application/nav/applicationNavSecondary.component.ts
- app/scripts/modules/core/src/application/nav/defaultCategories.ts
- app/scripts/modules/core/src/application/nav/navigationCategory.registry.ts
- app/scripts/modules/core/src/application/service/applicationDataSource.registry.ts
- app/scripts/modules/core/src/application/service/applicationDataSource.ts
- app/scripts/modules/core/src/loadBalancer/loadBalancer.dataSource.ts
- app/scripts/modules/core/src/pipeline/pipeline.dataSource.js
- app/scripts/modules/core/src/reactShims/react.injector.ts
- app/scripts/modules/core/src/securityGroup/securityGroup.dataSource.ts
- app/scripts/modules/core/src/serverGroup/serverGroup.dataSource.ts
- app/scripts/modules/core/src/task/task.dataSource.js
Prep work for navigation refactor - does not affect existing navigation functionality...
* introducing a navigation category registry with two categories out of the box: delivery and infrastructure
* Making the refresh and refresh failure streams on application data sources public so we can do a little more rxjs and a little less Promise
* category ordering can be customized via the registry
> feat(core): add categories for application data sources

- app/scripts/modules/core/.npmignore
Yalc ignores a certain set of files like LICENSE or HISTORY (I'm not sure why) and this PR explicitly unignores them.
See: https://github.com/whitecolor/yalc/issues/8
> fix(core-package): Add explicit do-not-ignores to .npmignore so yalc doesn't exclude them

- app/scripts/modules/core/src/pipeline/config/stages/wait/SkipWait.tsx
- app/scripts/modules/core/src/pipeline/config/stages/wait/waitStage.html
- app/scripts/modules/core/src/pipeline/config/stages/wait/waitStage.ts
We did something similar for execution window skipping; this applies the same pattern to wait stages.
> feat(core): allow custom warning when users skip wait stage

- app/scripts/modules/amazon/src/serverGroup/details/sections/LaunchConfigDetailsSection.tsx
The instance count check appears to have been from the section before the launch config (Health), copied over by mistake when converting the component to React.
> fix(amazon): show launch configuration for empty server groups

- app/scripts/modules/core/src/application/nav/CategoryDropdown.tsx
- app/scripts/modules/core/src/application/nav/DataSourceEntry.tsx
- app/scripts/modules/core/src/application/nav/ThirdLevelNavigation.tsx
- app/scripts/modules/core/src/application/nav/applicationNav.component.less
* Fixing the CSS in the menu items (bootstrap has a pretty specific CSS selector setting the display to `block`, overriding the `flex` we are trying to get via `horizontal`)
* forcing the menus to close when the active category is set to this menu, getting rid of the disabled approach to close the menu because, when mousing between an active (i.e. disabled) menu and another one, the mouseEnter event does not fire on the adjacent one, so its menu does not display. I don't know why, I just spent three hours trying to figure it out and this is where we are and, well, this makes as much sense as the original approach.
* pushing the logic for the single-source (i.e. dropdown menu items, third-level navigation entries) data synchronization to its own component, since they are not synchronizing …
> fix(core): fix submenu alignment, sync running badges

- app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
- app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
- app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.html
A disabled server group can be rolled back iff at least one enabled
server group exists in the same cluster.
The largest enabled server group in the cluster will will be selected as
the rollback source.
depends on spinnaker/clouddriver#2455
> feat(aws): Support rollback of a disabled server group

- app/scripts/modules/kubernetes/src/v2/instance/details/details.html
- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html
- app/scripts/modules/kubernetes/src/v2/manifest/manifestEvents.component.ts
- app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html
https://github.com/spinnaker/clouddriver/pull/2464
https://github.com/spinnaker/spinnaker/issues/2587
This doesn't show details for executing pipelines yet -- that'll come in a later PR
> feat(provider/kubernetes): events in manifest details

- app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.service.ts
When deck's settings have been overridden such that `SETTINGS.defaultProviders` is null or undefined, bad things happen:
fixes https://github.com/spinnaker/spinnaker/issues/2561
> fix(core/search): dont throw when SETTINGS.defaultProviders is null-ish

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
as mentioned in spinnaker/spinnaker#2330, webhook stages now support
artifact production.
depends on spinnaker/orca#2906
@lwander PTAL
> feat(webhooks): support artifact production

- app/scripts/modules/titus/src/migration/titusMigrationConfig.component.less
On certain screen resolutions, the "Wait [x] seconds between updates" line will appear to the right of the line above it when toggling the batch size dropdown. Also, the batch size dropdown causes grief when it's open because it tries to render as a block level element, so we should force it to display inline.
> fix(titus): fix alignment of migration config fields

- app/scripts/modules/core/src/application/service/application.read.service.ts
Properly handle the case where a user enables a previously disabled data source that is opt-in.
Right now, the data will be saved, but when the application resets its data sources (because the user changed the data sources from the config tab), it will not enable the data source, so the checkbox on the config tab will remain unchecked, and the tab will not appear in the navigation until the user refreshes the page or navigates to a different app and then back to this one.
> fix(core): toggle disabled to false if needed on application refresh

- app/scripts/modules/core/src/application/nav/applicationNav.component.less
If you use the browser navigation to move between pages, the top level nav items tend to retain focus, which makes it look like they are selected. Also, the caret was only showing on the dropdowns when they were in a :hover or :focus state due to a previous refactor (CSS is hard for some people).
> fix(core): remove :focus styling on nav dropdowns

- app/scripts/modules/core/src/artifact/ArtifactReferenceService.spec.ts
- app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts
- app/scripts/modules/core/src/artifact/index.ts
- app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts
- app/scripts/modules/core/src/pipeline/config/stages/stage.html
- app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
- app/scripts/modules/google/src/pipeline/stages/cloneServerGroup/gceCloneServerGroupStage.js
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
This PR adds a small service that allows stages to register walker functions that know how to traverse that stage looking for artifact references.
The k8s deploy manifest stage and GCE clone stage both use this new service to register walker functions for themselves.  The trigger directive's `removeExpectedArtifact` method then utilizes these walkers to visit and remove stale artifact references from those stages when an expected artifact is deleted from a pipeline.
This approach is general, feels a bit convoluted, but works.  Very open to better approaches here.
Fixes https://github.com/spinnaker/spinnaker/issues/2562
Clicking the trash can icon to delete an expected artifact:
Resulted in this side effect on deploy manifest stages:
Deleting an expected artifact now manifests as this:
> fix(artifacts): deleting expected artifact removes stale artifact references from stage

- app/scripts/modules/core/src/application/nav/CategoryDropdown.tsx
- app/scripts/modules/core/src/application/nav/MenuTitle.tsx
Turns out we are doing some wonky things like nested anchor tags in buttons via the React Bootstrap `Dropdown.Toggle` component, and Firefox won't let you have an anchor in a button (it looks like an anchor but will not be clickable).
This may or may not be less hacky than the code it is replacing. It is at least "more valid HTML".
> fix(core): make nav category headings clickable in Firefox

- .eslintrc
Prettier is adding trailing commas to multi line functions declarations, i.e:
```js
function(
foo,
bar,
) {
// function body
}
``` 
eslint is puking on the `bar,` trailing comma.  Updating the eslint parser to support ES2017 features fixes the parse errors.
> fix(eslint): enable es2017 parsing to allow trailing commas in function declaration arguments

- app/scripts/modules/core/src/application/nav/TinyHeader.tsx
Fixes:
```
warning.js:33 Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
in select (created by TinyHeader)
in div (created by TinyHeader)
in TinyHeader (created by ApplicationHeader)
in div (created by ApplicationHeader)
in div (created by ApplicationHeader)
in div (created by ApplicationHeader)
in ApplicationHeader (created by ApplicationComponent)
in div (created by ApplicationComponent)
in ApplicationComponent (created by BindResolvesToProps)
in BindResolvesToProps (created by UIView)
in UIView (created by ReactUIView)
in UIRouterContextComponent (created by ReactUIView)
in ReactUIView
```
> fix(core/nav): use 'undefined' instead of 'null' for empty select value

- app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.service.ts
fixes:
```
Uncaught TypeError: node.parentIds.push is not a function
at eval (pipelineGraph.service.ts:89)
at Array.forEach (<anonymous>)
at Function.generateConfigGraph (pipelineGraph.service.ts:68)
at ConstructorWrapper.createNodes (PipelineGraph.tsx:133)
at ConstructorWrapper.applyPhasesAndLink (PipelineGraph.tsx:145)
at ConstructorWrapper.updateGraph (PipelineGraph.tsx:418)
at ConstructorWrapper.componentDidMount (PipelineGraph.tsx:468)
at commitLifeCycles (react-dom.development.js:8770)
at commitAllLifeCycles (react-dom.development.js:9946)
at HTMLUnknownElement.callCallback (react-dom.development.js:542)
```
> fix(core/pipeline): Fix rendering of pipeline graphs after tslint --fix

- app/scripts/modules/canary/acaTask/acaTaskStage.transformer.js
- app/scripts/modules/core/src/domain/IExecution.ts
- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/config/stages/core/ExecutionBarLabel.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The amount of data we return from the `application/{app}/pipelines` call is often very heavy and rarely needs to be. We don't need `context`, or `outputs`, or `tasks` on stages unless we hover over certain stage types or we expand the execution to look at the graph or stage details.
There will be a subsequent PR to Orca to remove those fields when `expand=false` is sent. For now, we are simulating that by removing them after the response comes back. The idea is to run this for a day or two in production, find out if we missed anything, then actually remove the fields from the Orca payload once we're satisfied we are handling everything in Deck correctly.
There are two cases I'm assuming we need the full stage context to render tooltips for the pipeline stages in the execution bar: if …
> refactor(core): lazy load execution details

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The first commit fixes a dumb thing I did copy/pasting something, and I don't want to talk about it.
The second commit fixes a few things I noticed:
* Orca doesn't always return the execution JSON in exactly the same order, so our `stringVal` check often unnecessarily replaces the execution or stages within the execution
* the active refresher code in the Execution component does not consider the case where an execution gets replaced by the execution service and the props have changed
The `TODO` comment still stands - this is a mess, and I am guessing it doesn't need to be now, as most of the code on this page is not Angular. Once we get the performance changes in around lazy loading, I will tackle refactoring this.
> fix(core): fix manual judgment render, active execution refresh

- app/scripts/modules/kubernetes/src/serverGroup/details/resize/resize.html
Current utilization is based on requested CPU, so it can be larger than 100%
> feat(kubernetes) remove upper limit for CPU Target on resize

- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Huh, who would have guessed we are only looking at the pipeline config to get the target accounts (the tags on the beginning of the execution group header) if there are no executions.
Since the executions are not going to provide that data now (unless one happens to be running), we should really get that data from the configs.
We still want to keep to `accountExtractor` field on the stage configs (and all that associated data), as it's used in our internal fast property pipelines views, but long-term, we should move this data extraction to Orca.
> fix(core): extract target accounts from config

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/details/StageExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Pushing the execution hydrate call up to the Execution component itself instead of the graph component, and preventing the details from being shown at all until the execution is hydrated. It's a lot easier to reason about things in the graph and execution details if you always assume it's hydrated.
Also avoiding an unnecessary `setState` call on the `viewState` field, since it was getting called a lot and causes a lot of pain on the pipeline graph.
And...using `Object.assign` to hydrate the stages and stage summaries instead of a handful of explicit assignments.
> fix(core): fix execution rendering on lazy executions

- app/scripts/modules/canary/canary/canaryStage.transformer.js
- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Turns out it is better to only hydrate the parts that get hydrated.
Also, better to not try to transform a canary stage with no context.
Finally, better to leave stages alone on a synchronize if they are not and were not active, e.g. if they were in a FAILED_CONTINUE state.
> fix(core/canary): do not transform lazy canaries; smarter stage hydration

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
This fixes a `TypeError: (pipelineConfigIds || []).join is not a function` error I'm having when accessing configuration for any declarative pipeline.
Not sure if this is the way to solve it so PTAL
> fix(core/execution) fix type error when configuring declarative pipelines

- app/scripts/modules/core/.npmignore
See: https://github.com/whitecolor/yalc/pull/24
> chore(npmignore): remove yalc workaround for 'history' and 'changes'

- app/scripts/modules/google/src/loadBalancer/configure/http/transformer.service.js
- app/scripts/modules/openstack/src/serverGroup/configure/ServerGroupCommandBuilder.js
webpack adds an alias for `@spinnaker/core` so that each module can be build separately and imported
> chore(core) fixed imports

- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
The `title` attribute is nice, but discoverability is not there on it - you have to hover over the timestamp for a couple of seconds for it to appear. And you cannot copy it.
This is a small change to address those two issues.
> feat(core): show execution timestamp on hover

- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/ExecutionWindowActions.tsx
- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgment.service.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgment.service.ts
- app/scripts/modules/core/src/pipeline/config/stages/wait/SkipWait.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterService.ts
The actions that can be taken on manual judgment, wait, and execution window stages do not update the execution itself, instead relying on the data source refresh cycle to update the stages, which can take a little while. This changes that behavior to update the execution when the change has been detected.
Also, we potentially reset the `hydrated` flag when we synchronize the execution, which we shouldn't do if it was previously hydrated. This is a problem when the execution is hydrated and then completes, as we'll reset the flag.
This is frankly more fallout and confusion due to the way we are trying to optimize refreshes via in-place updates of the executions, rather than replacing them completely, and in theory this stuff goes away when we get the rest of the executions view …
> fix(core): fix refresh on execution patches; default option on judgment

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Instead of worrying about the execution refresh from the `Execution` component itself, let's just refresh the running executions every 5000ms when we're on the executions view and let them get merged in as they are, anyway.
It's not *as* immediate as the per-second refresh, but it's a lot less chatty on the network, it's sufficiently responsive (average latency of active execution data should be ~2.5s, assuming data changes every second for an execution, which...it doesn't), and it's a lot easier to reason about the code this way.
> refactor(core): use running executions to refresh in-place executions

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.html
add support for run job node selector. looks like clouddriver already
supports this so we just need to expose it via the UI
fixes spinnaker/spinnaker#2553
> feat(provider/kubernetes): run job node selector

- app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
We have some internal Apache rewrite rules that change the Spinnaker URL from, e.g. `http://spinnaker?i-123456789` to `http://spinnaker/#/search?key=i-123456789&route=true`. 
We use this to quickly navigate (fine, navigate with fewer clicks) to an instance in the UI. It was a sneaky feature in the V1 search that we didn't implement in the V2 search. This adds it for V2.
> fix(core): allow auto-navigation on single search result in V2

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/titus/package.json
*spinnaker/core*
* fix(core): allow auto-navigation on single search result in V2
* fix(core): ExecutionBuildTitle sometimes gets an undefined execution
* refactor(*): de-angularize help contents/registry
*amazon/titus/kubernetes*
* de-angularize help contents/registry
> chore(*): bump packages for de-angularized help contents

- app/scripts/modules/kubernetes/src/v2/instance/details/details.html
- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.html
- app/scripts/modules/kubernetes/src/v2/manifest/annotationCustomSections.component.ts
- app/scripts/modules/kubernetes/src/v2/securityGroup/details/details.html
- app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
- app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html
Annotations on k8s resources with a key matching `(section-title).details.(html)?.spinnaker.io/(key-name)` will be used to populate a section in the details panel for that resource.
Hyphens in the section title and key name are replaced with spaces.
The content of the annotation is interpolated using the resource (ala instance links) so that information can be dynamically set with `{{ }}` template literals.
Finally, prior to reaching the DOM, the content is pushed through DOMPurify.sanitize.
Fixes https://github.com/spinnaker/spinnaker/issues/2529 and, by extension, provides support for https://github.com/spinnaker/spinnaker/issues/2528
> feat(provider/kubernetes): Surface specially named annotations in details UI

- halconfig/settings.js
Adding ECS functionality into Deck. There will also be a halyard Pull request associated with this work.
> feat(deploy/ecs): add ecs support

- app/scripts/modules/core/src/serverGroup/details/ShowUserData.tsx
- app/scripts/modules/core/src/utils/unicodeBase64.ts
User Data always comes back Base64 encoded. If the encoded data is just text, it's straightforward to decode and show it in the UI rather than making people manually decode every time. If the data is in another format (like gzipped binary), it's far less straightforward and doing the right thing to decode is highly dependent on the individual use case.
Since textual User Data is the most common use case, this adds a checkbox to decode as text that defaults to checked, but allows for viewing the encoded source in case you want to process it yourself.
> fix(core/serverGroup): Default to decoding User Data as text

- app/scripts/modules/kubernetes/src/v2/manifest/showManifestDetails.component.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestExecutionDetails.html
Totally subjective, but though we could make some changes while testing the new force cache refresh:
Before:
After:
> chore(provider/kubernetes): tighten deploy manifest details view

- app/scripts/modules/core/src/search/global/GlobalSearch.tsx
- app/scripts/modules/core/src/search/infrastructure/infrastructureSearch.service.ts
- app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.service.ts
Code already exists to sort global search results based on the proximity of the query term to the display names of the search results, we just aren't triggering it without sending the query to it. This results in some queries not showing an exact match, which is annoying.
> fix(core): sort global search results by ranking

- app/scripts/modules/core/src/pipeline/service/executions.transformer.service.ts
Keep the `summary` object with the correct stage as the `summary` object is used later on used ( [in here](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/service/executions.transformer.service.ts#L465) ) and without this, the `summary` object changes are discarded since it's changed an object which is not in the array anymore.
> fix(core) Keep correct stage in summary object for future operations

- app/scripts/modules/core/src/pipeline/status/ArtifactList.spec.tsx
- app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
We've been running into an issue at Netflix where Igor is not configured to decorate artifacts, but Orca is [adding artifact data to manual executions](https://github.com/spinnaker/orca/commit/b1f1686672a5f65bf452779f6d2ee7b49cc51aca). This results in a bunch of artifacts on execution objects without a `type` or `name`, which the current `ArtifactList` just dumps on the screen:
In general, artifacts that don't have a `type` or `name` are relatively useless from Deck's perspective (hence the decoration that Igor does). This change just omits any undecorated artifacts.
> fix(core/pipeline): Only list decorated artifacts

- app/scripts/modules/core/src/application/modal/editApplication.html
- app/scripts/modules/core/src/application/modal/newapplication.html
Fixes the regex used to validate the Repo Name in app config; previous version would generate the following error:
```Pattern attribute value ^((?!\:\/\/).)*$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^((?!\:\/\/).)*$/: Invalid escape```
> fix(config) Remove invalid escape in regex

- docker/ports.conf.gen
Change 443 in ports.conf.gen to {%DECK_PORT%} to allow it to be changed by docker entrypoint script. 
Fixes spinnaker/spinnaker#2733
> fix(ssl/apache2): Fix for ports.conf.gen

- app/scripts/modules/core/src/instance/Instance.tsx
If a user is hovering over an instance chiclet when the instance is removed from the view, the tooltip will stick around. In the Angular world, the tooltip would be removed automatically because the Angular/jQuery lifecycles were somewhat coordinated, IIRC, but that's not the case with React + jQuery.
A different solution would be to apply the tooltips in a less 2007-era way, but we'd need to get a tooltip solution that does an append-to-body type thing, which wasn't well supported by React before 16.3, as far as I know, and...this is fine for now.
> fix(core): remove tooltip if needed when unmounting instances

- app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/basicSettings.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/manifestEntry.component.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
* Make artifact components more re-usable by being more consistent about which tags should be handled by the parent form and which should be embedded in the component.  In particular, push ` <div class="container-fluid form-horizontal">` to the top of each form rather than repeating in each component.
* Replace boiler-plate form layout code with `stage-config-field` directive
> refactor(google): Refactor config fields to use consistent directive

- app/scripts/modules/core/src/instance/instanceType.service.ts
- app/scripts/modules/google/src/gce.settings.ts
- app/scripts/modules/google/src/instance/gceInstanceType.service.js
- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
- settings.js
Also adds sane storage disk configurations for instanceTypes not statically defined in categories. Credit @danielpeach.
> feat(provider/gce): Surface all available GCE instanceTypes.

- app/scripts/modules/core/src/domain/IPubsubSubscription.ts
- app/scripts/modules/core/src/domain/index.ts
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsub.trigger.ts
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/pubsubTrigger.html
- app/scripts/modules/core/src/pubsub/pubsubSubscription.service.ts
- halconfig/settings.js
- settings.js
* Part of a bug fix to display only Pub/Sub subscription names of subscriptions associated with a given Pub/Sub system type (e.g., 'google').
* This fix also touches echo and gate.
* This PR also removes 'kafka' from list of Pub/Sub System Types in settings.js and pubsub.trigger.ts as it is not being used.
* We have opted out of adding a button to refresh the cached list of subscriptions because @danielpeach deemed it an unlikely use case.
> fix(pubsub): Filter displayed list of Pub/Sub Subscription Names by Pub/Sub System Type.

- app/scripts/modules/core/src/pipeline/service/execution.service.ts
We need this to fully hydrate the stage summaries; otherwise, stage comments do not appear in the pipeline details.
> fix(core/pipelines): display comments on stage details

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The first one makes sure we don't override the execution filter state on route changes if the filter state is not actually cached.
The second one makes sure we try to synchronize the execution details whenever the execution is hydrated.
> Execution fixes

- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/CloneServerGroup.aws.controller.spec.js
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.html
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/loadBalancers/loadBalancerSelector.component.ts
99% of the time people are using load balancers from their own app. Sometimes the entire load balancer list can take a long time to come back, and the experience isn't great when the list is huge, so default to only load balancers from the specific app, but provide a way to load all of them on demand.
> feat(amazon): Cluster dialog - only preload load balancers associated with app

- app/scripts/modules/core/src/pipeline/config/stages/core/ExecutionDetailsSection.tsx
This is very annoying and I have tried a bunch of different things to try to work around it.
This is repeatable, so may be something we need to figure out eventually if we continue to extend multiple interfaces that reside in different files, and then try to use those interfaces in other libraries.
For now, I'm putting a big fat comment in place.
> refactor(core): handle TS issue with interface extension

- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Prevents replacement of a hydrated execution's stages with ones that are not hydrated.
This is the last bug we'll encounter due to the hydration code.
cc @danielpeach
> fix(core/executions): do not overwrite hydrated executions

- halconfig/settings.js
- settings.js
adds gitlab as a default git source. spinnaker/deck#4657 added the ability to override
this via `settings-local.js`. it seems like the default should be all available git sources
with the ability to pare down as necessary.
@anotherchrisberry @danielpeach PTAL!
> fix(settings): add gitlab git source by default

- app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.less
The only non-prettier change is to the selector for `svg.pipeline-graph` (making it `svg.pipeline-graph:not(:root)`), which is getting overridden by another selector now.
> fix(core/pipelines): fix execution graph overflow in Firefox

- app/scripts/modules/core/src/pipeline/config/pipelineConfig.module.js
- app/scripts/modules/core/src/pipeline/config/validation/anyFieldRequired.validator.ts
- app/scripts/modules/core/src/pipeline/config/validation/baseRequiredField.validator.ts
- app/scripts/modules/core/src/pipeline/config/validation/requiredField.validator.ts
- app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
Allow packages to be specified as either a string or a list of artifacts on the bake stage.  To implement this, create a new field validator that checks if at least one of a list of fields is non-null.
>  feat(artifacts): Either string or artifact is sufficient for bake stage

- app/scripts/modules/core/src/application/application.state.provider.ts
- app/scripts/modules/core/src/application/service/application.read.service.spec.ts
- app/scripts/modules/core/src/application/service/application.read.service.ts
Significant improvement in load time for situations where you _do not_
need cluster, server group and load balancer names.
> perf(core): Support loading an application with `?expand=false`

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
Maybe your webhook is polling for results and takes longer than 1 hour to complete. Let's surface the timeout for this case so you can override it.
> feat(webhook): override webhook timeout

- app/scripts/modules/core/src/pipeline/status/ArtifactList.spec.tsx
- app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
- app/scripts/modules/core/src/pipeline/status/artifactList.less
> feat(artifacts): show artifact type as icon in execution summary

- app/scripts/modules/core/src/artifact/artifact.module.ts
- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/artifact/summarizeExpectedArtifact.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
- app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
- app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.spec.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
expected artifact selector continues to work in k8s deploy manifest stage:
expected artifact multi-selector continues to work in gce bake stage:
Both of those also use the artifact summarize filter that was moved to its own angular module file.
> chore(artifacts): de-angularize expected artifact service

- app/scripts/modules/core/src/artifact/ArtifactReferenceService.spec.ts
- app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts
- app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/producesArtifacts.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
- app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
- app/scripts/modules/google/src/pipeline/stages/cloneServerGroup/gceCloneServerGroupStage.js
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
Adds artifact reference removal to the bakeManifest stage for the `expectedArtifacts` and `inputArtifacts` fields.
In the below image an artifact has been removed from the Expected Artifacts section of the config screen & that removal continues to be correctly reflected in the GCE deploy stage:
And here an artifact has been removed from a config screen and is correctly reflected in the bake manifest stage:
> chore(artifacts): de-angularize artifact reference service

- app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.controller.ts
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
Following up on a `todo()` from a while ago.  Here's how the expected artifect selector looks in the appengine server group wizard:
and I tested a deployment using the container image from the selector:
> chore(provider/appengine): use expected-artifact-selector in place of copy-paste

- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
I accidentally broke this with my previous appengine change.
Broken:
Fixed:
> fix(artifacts): ensure fieldColumns is not undefined in expected artifact select

- app/scripts/modules/core/src/artifact/ArtifactIconService.ts
- app/scripts/modules/core/src/artifact/icons/gitlab-file-artifact.svg
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.module.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/defaultGitlab.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/gitlab.artifact.ts
adds support for gitlab artifacts. the url for gitlab artifacts isn't
ideal (url encoded files and project names) but it's true to the API.
there may be a better way to support this in the future.
> feat(artifacts): add gitlab artifacts

- app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
- app/scripts/modules/amazon/src/instance/details/instance.details.controller.spec.js
- app/scripts/modules/amazon/src/instance/details/instanceDetails.html
- app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.js
- app/scripts/modules/cloudfoundry/instance/details/instance.details.controller.spec.js
- app/scripts/modules/cloudfoundry/instance/details/instanceDetails.html
- app/scripts/modules/core/src/cloudProvider/skin.service.ts
- app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
- app/scripts/modules/core/src/instance/details/instanceLinks.component.js
- app/scripts/modules/ecs/instance/details/instance.details.controller.js
- app/scripts/modules/ecs/instance/details/instanceDetails.html
- app/scripts/modules/google/src/instance/details/instance.details.controller.js
- app/scripts/modules/google/src/instance/details/instance.details.controller.spec.js
- app/scripts/modules/google/src/instance/details/instanceDetails.html
- app/scripts/modules/kubernetes/src/instance/details/details.controller.js
- app/scripts/modules/kubernetes/src/instance/details/details.html
- app/scripts/modules/openstack/src/instance/details/instance.details.controller.js
- app/scripts/modules/openstack/src/instance/details/instanceDetails.html
- app/scripts/modules/titus/src/instance/details/instance.details.controller.js
- app/scripts/modules/titus/src/instance/details/instanceDetails.html
So folks can use things like `{{stack}}` and `{{environment}}` when building links.
To the best of my knowledge I covered all the cloud providers that currently implement custom instance links — there are a few like Azure that didn't seem to use them at all. I kind of went around the existing angular data flow a bit in hopes of making things more amenable to reactification later, but I'm not particularly tied to it.
> feat(*/instance): add moniker info + env to instance link templates

- app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.html
- app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.ts
- app/scripts/modules/core/src/presentation/main.less
Made script path and command required in script stage.
When setting up a pipeline, if there is a script stage, the user needs to type in both script path and command. Made these fields required and added validators so the stage shows red to indicate its not fully set up.
> fix(core): Validators for script stage

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html
If the "Start Manual Execution" button is clicked at the top level, i.e. not from a specific pipeline config, `stageComponents` won't be initialized yet and a bunch of NPEs will get thrown around.
Also fixing the trigger label when there is just one.
> fix(core): avoid NPE on manual execution modal open

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
Rapid url cycles were triggered by changing a pipeline filter when altering the URL and hitting enter.
I.e., change:
```
http://localhost:9000/#/applications/deck/executions?vis=true&pipeline=Deploy%20to%20Test
```
to 
```
http://localhost:9000/#/applications/deck/executions?vis=true&pipeline=Deploy%20to%20Main
```
> fix(core/executions): Fix browser hangs from rapid URL cycles

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
Before: exception thrown when deploying namespace manifest
After: no exception thrown when deploying namespace manifest
> fix(provider/kubernetes): manifest.metadata.namespace can be null-ish

- app/scripts/modules/kubernetes/src/v2/loadBalancer/details/details.controller.ts
fixes https://github.com/spinnaker/spinnaker/issues/2709
Multiple k8s Services can share a name and account ID if they're in different namespaces.  Adding namespace to the set of matched fields finds the precise Service that was clicked on by the user.
No visual change; clicking on a k8s LB entry now shows details for that LB every time.
> fix(provider/kubernetes): clicking load balancer doesnt always show correct details view

- app/scripts/modules/core/src/application/applicationModel.builder.ts
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.spec.tsx
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
For schibsted: support override of `CreatePipelineModal`
to override:
```js
@Overrides('core.pipeline.CreatePipelineModal')
export class MyCreatePipelineModal extends React.Component {
render() {
return <Modal
... ... ...
}
}
```
@jrsquared @amanya
> feat(core/pipeline): Make CreatePipelineModal overridable

- app/scripts/modules/core/src/artifact/react/ExecutionArtifactTab.tsx
> fix(provider/kubernetes): artifact tab columns compressed in small windows

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraphNode.tsx
- app/scripts/modules/core/src/pipeline/config/stages/group/GroupExecutionLabel.tsx
- app/scripts/modules/core/src/pipeline/config/stages/group/GroupExecutionPopover.tsx
Improve the handling of clicking and hovering on stages in the pipeline graph in Chrome 67 (`foreignObject` creates its own stacking context) by consolidating the click/mouseEnter/mouseLeave events on the parent `<g>` element.
Small tweaks to the grouped stage menu, forcing it to be a bit wider because react-bootstrap does not support composite placement (i.e. `bottom left`), and the menu now appears in the middle of the entire node + label, which can be a lot wider than needed because, well, laying out this graph is complicated.
Closes https://github.com/spinnaker/spinnaker/issues/2850
> fix(core): improve pipeline graph mouse event handling for Chrome 67

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
Before:
Namespace manifest deploy status 404'd, always rendered with fallback view:
After:
Namespace manifest deploy state requested successfully, rendered with status pills:
> fix(provider/kubernetes): namespace manifests should be fetched with location of "_"

- app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx
- app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
I no longer understand what the `keyMapper` is supposed to be doing in the React Virtualized List. The `List` element does not seem to take those keys into consideration when re-rendering its rows, so when the underlying data has changed (because the filters have changed, for example), it seems to leave the row heights alone for any rows currently rendered on the screen. As soon as the user scrolls the list at all, however, the correct heights are applied, so I'm really not sure what to think of it.
This workaround is simple: reset the measurer cache whenever the filters change. I don't care for it, but maybe it's fine.
@erikmunson PTAL when you have a chance. You can test out the existing behavior in our clusters view of Orca by toggling the test account filter on and off.
This other …
> fix(core): recompute cluster pod heights on filter changes

- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.controller.js
- app/scripts/modules/kubernetes/src/pipeline/stages/runJob/runJobExecutionDetails.html
To fix https://github.com/spinnaker/spinnaker/issues/2869
Checks to see if a RunJob pipeline stage has output logs in the HTML with Angular, rather than in the controller.
The HTML will poll for changes in the logs all the time, and will update without any refreshing, and displays at all times
> fix(deck): Change RunJob stage to check for logs in HTML

- app/scripts/modules/amazon/src/help/amazon.help.ts
Removing the type of load balancer from the help because it is confusing when it appears in ALBs in target groups.
> fix(amazon): update help text

- app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.html
- app/scripts/modules/core/src/pipeline/config/stages/script/scriptStage.ts
When no path is specified, the script stage finds the script command in the root of the git repository.  Path is only required if the script is found elsewhere.
> fix(core/pipeline): Make script stage "Path" field not required

- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
> fix(provider/kubernetes): re-enable script stage for k8s v2

- app/scripts/modules/core/src/artifact/ArtifactIconService.ts
- app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
i.e., if a configured artifact type doesn't have an icon, don't show a question mark.
> fix(artifacts): only show question mark icon for custom artifacts

- app/scripts/modules/core/src/pipeline/config/stages/bake/ManualExecutionBake.tsx
We were relying on `ng-model`'s deep property setting to add a `trigger` object if it didn't already exist. Since the manual execution controller is already setup to handle us doing it this way I'm not gonna go in and muck with it.
> fix(core/pipeline): Don't fail when checking Force Rebake without a trigger

- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
Use `namespace` parameter in pipeline instead `properties.namespace`
> fix(bake/manifest): fix passing namespace in helm bakery

- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/manifest/ManifestAnnotations.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/ManifestLabels.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/manifestAnnotations.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/manifestLabels.component.ts
- app/scripts/modules/kubernetes/src/v2/manifest/status/ManifestCondition.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/status/condition.component.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestDetailsLink.tsx
- app/scripts/modules/kubernetes/src/v2/resources/ResourceDetails.tsx
- app/scripts/modules/kubernetes/src/v2/resources/resources.state.ts
An "unmapped resource" is one that doesn't map cleanly to Spinnaker's notion of server groups / firewalls / load balancers.  A k8s ConfigMap is an example of this.
Fixes https://github.com/spinnaker/spinnaker/issues/2586
Fixes https://github.com/spinnaker/spinnaker/issues/2327
This PR adds a k8s-specific URL that matches the pattern `/applications/:appId/clusters/manifest/:provider/:accountId/:region/:kind%20:name`.  I haven't leveraged the Override registry here because I don't think any of the other providers have the same need as kubernetes re: unmappable resources.
ConfigMap example:
For comparison's sake, here's how a pod renders with the existing k8s instance details view vs. the generic resource details view:
> feat(provider/kubernetes): generic details view for unmapped resources

- app/scripts/modules/core/src/account/AccountService.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestDetailsLink.tsx
Use the kubernetes->spinnaker kind mappings from https://github.com/spinnaker/clouddriver/pull/2722 to route users to a resource's details view.
> feat(kubernetes): use kind mapping to determine details view

- app/scripts/modules/titus/src/migration/titusMigrationConfig.component.ts
As requested by the titus folks.
> fix(titus): Default to 1 percent for container migrations vs 1 instance

- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTrigger.html
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTrigger.module.js
Previously these pipelines inherited the authentication context of their
parent pipeline.
spinnaker/orca#2295 has altered this behavior.
> feat(pipeline): Support `runAsUser` for implicit pipeline triggers

- webpack.config.js
Reverts spinnaker/deck#5479
See https://github.com/spinnaker/spinnaker/issues/2942
This is more complicated than I thought. The problem is that it adds a hash to `settings.js` that Halyard can't know about beforehand. I can't see a way to prevent `settings.js` from receiving a hash.
Maybe someone with more Webpack knowledge (@christopherthielen ) can think of a solution?
> Revert "feat(build): add cache bust for builds"

- webpack.config.js
Injects the script tags with a query param to help browsers figure out if they can load the script from cache or not:
```
<script type="text/javascript" src="settings.js?60126dc51605e31ce42c"></script>
<script type="text/javascript" src="settings-local.js?60126dc51605e31ce42c"></script>
<script type="text/javascript" src="vendors~app.js?60126dc51605e31ce42c"></script>
<script type="text/javascript" src="app.js?60126dc51605e31ce42c"></script>
```
> feat(build): add cachebust query param to scripts in index.html

- app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx
- app/scripts/modules/core/src/cluster/allClusters.html
Cluster page scrolls even when the user clicks on a cluster.
We set up scroll to specific server group if it is deep linked. this is set as a state in react. However it is never reset. As a result, even when the user clicks on a different server group, we update the route, but the state still has the previous server group set to scroll. So the page always scrolls to the previous server group. 
The current fix sets the ref as a state. This is because componentDidMount is called before the list component is loaded. So we need the ref and need to check when the component is updating and set it once the very first time to scroll.
> fix(core): Fixed cluster scroll jump

- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/core/src/loadBalancer/loadBalancer.read.service.ts
Fixed an issue with out-of-order actions for a rule.
This also makes sure the `authenticate-oidc` action is first, fixing the broken authenticate action.
> fix(amazon/loadBalancer): Support order property in listener actions

- app/scripts/modules/core/package.json
This version includes minor fixes to get npm publish to not have warnings
> chore(core): bump to 0.0.244

- app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts
Looks like this was accidentally applied to both v1 and v2, rather than just v2.
> fix(provider/kubernetes): Remove patch manifest stage v1 provider

- app/scripts/modules/kubernetes/src/v2/instance/details/IKubernetesInstance.ts
- app/scripts/modules/kubernetes/src/v2/instance/details/details.controller.ts
- app/scripts/modules/kubernetes/src/v2/instance/details/details.html
Console Output API for k8s v2 relies on the humanReadableName (previously returned as ID for k8s instances) which was no longer being passed since https://github.com/spinnaker/deck/pull/5506
Before:
After:
> fix(kubernetes): console output broken for instances

- app/scripts/modules/core/package.json
Bumping core to 0.0.246.
Includes fix for scrolling to bottom in clusters page.
> chore(core): Bump core to 0.0.246

- .gitignore
- AUTHORS
- app/scripts/modules/core/src/ci/igor.service.ts
- app/scripts/modules/core/src/domain/ITrigger.ts
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/WerckerExecutionLabel.tsx
- app/scripts/modules/core/src/pipeline/config/stages/wercker/modal/addParameter.controller.modal.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/modal/addParameter.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.module.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.ts
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTriggerTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.html
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.module.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
- halconfig/settings.js
- settings.js
Add WerckerTrigger and WerckerStage
Related PRs
https://github.com/spinnaker/halyard/pull/960
https://github.com/spinnaker/igor/pull/297
> feat(wercker): add wercker trigger and stage

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/CloneServerGroup.aws.controller.js
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/location/basicSettings.html
- app/scripts/modules/azure/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
- app/scripts/modules/cloudfoundry/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/cloudfoundry/serverGroup/configure/wizard/CloneServerGroupCtrl.js
- app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
- app/scripts/modules/ecs/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/ecs/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js
- app/scripts/modules/ecs/serverGroup/configure/wizard/location/basicSettings.html
- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
- app/scripts/modules/openstack/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/openstack/src/serverGroup/configure/wizard/location/basicSettings.html
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupBasicSettingsDirective.html
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.js
- package.json
- yarn.lock
This is (hopefully) a no-op.
This sets the stage for supporting the clone server group modal in React. When Formik sets the initial form values, it clones all the properties. Since we attach the functions to the upsert command itself, the functions are now performing changes on the old command that the Formik form has no understanding of.
Eventually we will just take the functions off the command itself, but this is a slightly safer step one to keep a lot of the supporting code paths the same in all the providers.
> refactor(*): Add server group configuration command to all configured command functions

- .gitignore
- AUTHORS
- app/scripts/modules/core/src/ci/igor.service.ts
- app/scripts/modules/core/src/domain/ITrigger.ts
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/WerckerExecutionLabel.tsx
- app/scripts/modules/core/src/pipeline/config/stages/wercker/modal/addParameter.controller.modal.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/modal/addParameter.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.module.ts
- app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.ts
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.module.js
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTriggerTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.html
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/werckerTrigger.module.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
- halconfig/settings.js
- settings.js
This PR reintroduces @shihchang 's work to add Wercker support that I [reverted here](https://github.com/spinnaker/deck/pull/5534).
Merge this PR once these service changes are merged:
https://github.com/spinnaker/igor/pull/297
https://github.com/spinnaker/echo/pull/295
https://github.com/spinnaker/gate/pull/574
https://github.com/spinnaker/orca/pull/2313
@shihchang please confirm with a message here that the code in this PR is as you expect it to be.  Many thanks and apologies again for the merge confusion.
> feat(wercker): add wercker trigger and stage (#5519)

- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
If config is allowed to be null (and looks like it is), seems reasonable that if there is no type, then it's not from a templated pipeline so `fromTemplate` should be false.
> feat(core): Adding null check to protect against undefined config

- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
Previously the clone modal wouldn't pick up disks when copying a server group.  Or, more accurately, it would pick them up and then immediately overwrite them with the instance type's default.
After this change a custom disk size correctly shows up in the clone modal:
> fix(provider/google): cloning server group doesnt correctly copy disk info

- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
Cherry-pick of https://github.com/spinnaker/deck/pull/5553 into release-1.8 branch
Previously the clone modal wouldn't pick up disks when copying a server group.  Or, more accurately, it would pick them up and then immediately overwrite them with the instance type's default.
After this change a custom disk size correctly shows up in the clone modal:
> fix(provider/google): cloning server group doesnt correctly copy disk

- start.sh
It's explicitly started using `sh` in `package.json`, so it should not use bash (although it has `#!/bin/bash`).
The alternative is to change `package.json` to use `bash` instead, but since this script has no need for an advanced shell, just use POSIX shell features.
This makes `yarn run start` work on systems where `sh` is not bash, where it previously failed with the error message
> ./start.sh: 8: ./start.sh: [[: not found
> fix(core): Remove bashisms from start.sh

- app/scripts/modules/google/src/pipeline/stages/findImageFromTags/gceFindImageFromTagsStage.js
GCE images aren't associated with a region, so there is no field to enter one in the UI. We should remove the validation that warns that a region has not been selected.
> fix(google): Remove image region validation from find image stage

- app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.service.ts
- app/scripts/modules/core/src/search/search.service.ts
- app/scripts/modules/core/src/search/searchResult/searchResultType.ts
See https://github.com/spinnaker/gate/blob/f38b1525135070bef6ca525ea8e261f60c39ef97/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/SearchController.groovy#L42-L45
> fix(core/search): Fix faceted search without any `q` query param

- app/scripts/modules/core/src/search/searchResult/Renderers.tsx
So we can compose cells with children instead of just text.
Don't think this calls for an entirely separate component (i.e. `CellWithChildren` or `ContainerCell`), does it?
> refactor(search): Update BasicCell to allow children

- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
Nothing happened when pressing the edit icon, apart for the following console error being printed: "Error: One of component or template or templateUrl options is required".
You should of course just enter the correct configuration values immediately, but some people are not perfect and do mistakes. This commit will make those people happy, because the edit button once again works.
> fix(amazon/deploy): Edit deployment cluster button did not work

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupSecurityGroups.tsx
Some more fun fixes:
- The radio buttons to select whether to copy source capacity or use new capacity settings were not working for several reasons (both options were checking the same condition, no `value` was specified for either, and there was a missing arrow binding for the `onChange` callback).
- The header/nav label was hard coded to `Security Groups` rather than using `FirewallLabels`.
- When `disableImageSelection` was set, the wizard could never be submitted/completed because `amiName` wasn't present and we were validating for it's existence all the time.
- The `preferSourceCapacity` setting was missing an arrow binding, and also showed the select field as empty/not selected when it was set to the default, rather than showing the actual default.
- The loading spinner + text for …
> fix(amazon/deploy): Make source capacity work again, other misc. fixes

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
- fix loading spinner
- fix initial image list load (prefixed by app name)
- disable clearing of 'prefer source capacity' dropdown
> fix(amazon/serverGroup): Improve image dropdown UX

- app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts
Native JS promises aren't hooked into Angular's event cycle - i.e., Angular doesn't notice when these promises resolve, and doesn't know to update the view.
Closes https://github.com/spinnaker/spinnaker/issues/3164
> fix(kubernetes): manifest editor load time

- app/scripts/modules/kubernetes/src/v2/manifest/annotationCustomSections.component.ts
> fix(kubernetes): replace all hyphens in annotation driven titles

- app/scripts/modules/kubernetes/src/v2/manifest/scale/scaleSettingsForm.component.ts
Before:
After:
Closes https://github.com/spinnaker/spinnaker/issues/3169
> fix(kubernetes): duplicate 'replicas' label in scale manifest stage

- app/scripts/modules/core/src/account/AccountService.ts
- app/scripts/modules/core/src/artifact/ArtifactIconService.ts
- app/scripts/modules/core/src/artifact/ArtifactTypes.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
Hides the artifact account selector when the user only has one configured account for a given artifact's type.  Embedded artifacts provide the clearest example of this; the user is unable to configure their own embedded-account and so the account selector is never displayed for embedded/base64 artifacts. More generally if, for example, a user only has a single GCS artifact account configured then Deck will simply choose that account and won't provide a single-entry select box.
An artifact selected that only has one available account associated with its type:
An artifact selected that has two available accounts associated with its type:
> feat(provider/kubernetes): hide artifact account selector when only one suitable account is available

- halconfig/settings.js
Looks like there was an option to enable "travis" although the trigger is already enabled.
> chore(halconfig): allow enabling travis & wercker in halconfig

- app/scripts/modules/amazon/src/loadBalancer/TargetGroup.tsx
- app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.html
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/core/src/instance/Instances.tsx
- app/scripts/modules/core/src/loadBalancer/LoadBalancerClusterContainer.tsx
- app/scripts/modules/core/src/loadBalancer/LoadBalancerInstances.tsx
- app/scripts/modules/core/src/loadBalancer/LoadBalancerServerGroup.tsx
The fact that there can be Titus server groups/instances underneath AWS load balancers in the hierarchy breaks some of the assumptions we originally made when building the LB view for AWS. This led to an end state where we tried to represent Titus entities using our Amazon components, which made the instance details pane make no sense (even though it rendered without issue).
I chose to patch this up by hydrating the provider onto instances when we get the provider for each server group, and switching things that were pulling providers off of target groups to use the server group instead (in places where the logic is scoped to a given server group). A couple of things that came to mind:
- It feels like it'd be nice to tack the provider onto the server group when it comes back from …
> fix(loadBalancer): Use correct provider for titus server groups/instances

- app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
> provider(kubernetes): Hide min/max label in servergroup details when min is null-ish

- app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/defaultDocker.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
Before, all artifact kinds are available regardless of which artifact accounts have been configured:
After, only the artifact kinds matching the set of configured accounts are available. In the below screenshot I only have a GCS credential configured. Base64 and Custom artifacts are credential-less and Docker artifacts are publicly accessible from docker hub:
> feat(artifacts): filter set of available artifact kinds by configured artifact accounts

- app/scripts/modules/core/src/serverGroup/configure/common/DeployInitializer.tsx
Turns out that the canary stage has historically told the deploy/clone dialog to force folks to select a server group template when adding a new canary/baseline pair (`disableNoTemplateSelection`). That used to work in angular-land, but when the relevant code got ported to the `DeployInitializer` component it broke. The underlying reason is that angular does a bunch of magic null-soaking that meant our controller code would happily evaluate derefs of the `selectedTemplate` object without it even existing. React is not nearly as happy to do that.
We already have a nicely setup `noTemplate` object that allows us to not worry about nulls, we just needed to actually use it for the canary stage case where you're forced to pick.
> fix(core/serverGroup): Make forced deploy template selection actually work

- app/scripts/modules/core/src/artifact/ArtifactIconService.ts
- app/scripts/modules/core/src/artifact/ArtifactTypes.ts
- app/scripts/modules/core/src/artifact/expectedArtifactSelector.component.ts
- app/scripts/modules/core/src/artifact/index.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
Before, a user could select a docker image as manifest source:
After, the manifest dropdown is prevented from showing docker images or kubernetes resources as possible manifest sources:
Closes https://github.com/spinnaker/spinnaker/issues/3198
> feat(kubernetes): filter artifact types that dont make sense for a manifest

- app/scripts/modules/core/src/pipeline/config/templates/configurePipelineTemplateModal.controller.ts
When inheriting triggers, pipelines, or expected artifacts from a Managed Pipeline Template, the inherited attributes were not copied over from the plan to the pipeline config that gets rendered.
This change copies them selectively, based on the desired inheritance.
> fix(pipeline): Fixed missing inherited triggers/parameters/artifacts

- app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
It looks as though deployStage now expects `buildNewServerGroupCommandForPipeline` to return a promise, and the other providers are doing so, but that appengine was missed.
Needs to be cherry-picked into 1.9.
Before, when clicking Add Server Group, no modal appears and the following error is shown in console:
After, the exception doesn't appear and the server group modal is shown.
> fix(appengine): add server group button broken

- app/scripts/modules/core/src/domain/IExecutionTrigger.ts
- app/scripts/modules/core/src/pipeline/executionBuild/ExecutionBuildLink.tsx
Trigger object can contain (optionally) a `link` and/or `linkText`. If that exists, use that for display purposes
> refactor(trigger): pull link and or text from ITrigger

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
It seems this particular command builder was missed when adding `submitButtonLabel` to everything.
> fix(amazon/deploy): Use the right text for submit btn when cloning

- app/scripts/modules/core/src/cluster/ClusterPod.tsx
- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.spec.ts
- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
- app/scripts/modules/core/src/cluster/rollups.less
- app/scripts/modules/core/src/domain/IServerGroup.ts
- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
- app/scripts/modules/core/src/serverGroup/ServerGroupHeader.tsx
- app/scripts/modules/core/src/serverGroupManager/ServerGroupManager.tsx
- app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerHeading.tsx
- app/scripts/modules/kubernetes/src/v2/serverGroup/serverGroupTransformer.service.ts
Clicking the top of the grouping opens the deployment details on the left side.
When selected, looks like this:
> feat(kubernetes): new deployment representation in cluster view

- app/scripts/modules/core/src/domain/IArtifactEditorProps.ts
- app/scripts/modules/core/src/domain/IArtifactKindConfig.ts
- app/scripts/modules/core/src/domain/index.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/Base64ArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/BitbucketArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/bitbucket.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/DockerArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/GcsArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/gcs.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/GithubArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/GitlabArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/gitlab.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/S3ArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/s3.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/singleFieldArtifactEditor.tsx
Part 2 of many towards https://github.com/spinnaker/spinnaker/issues/2921
This adds react components for editing each artifact type. Improved type safety over html template strings and they're a bit more fungible for use in different places.
These aren't used yet. I'm breaking up a larger set of diffs into individual PRs. The next in this series adds a manifest artifact editor that makes use of these.
> feat(artifacts): add react implementations of artifact editors

- app/scripts/modules/core/src/pipeline/config/stages/StageName.tsx
The artifact tab in the execution history is broken due to a duplicate angular module name.
> fix(artifacts): Fix artifact tab in execution history

- app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
revises some modal text to imply that another dialog box follows it.
> fix(ux): minor text revisions for server group enable modal

- app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
Now that m5 instances are battle tested, this changes our recommended family for normal/average uses from m4 -> m5. I also tweaked the language in the description, because it was phrased kind of strangely.
> feat(amazon/instance): Switch General Purpose instance from m4 -> m5

- app/scripts/modules/ecs/src/ecs.help.ts
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/networking/networkingSelector.component.html
Configuration for public IP address option ("Associate Public IP Address") when using VPC mode in ECS server groups
Clouddriver-side change is here: https://github.com/spinnaker/clouddriver/pull/2908
> feat(provider/ecs): Add option to associate public IP address

- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.html
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.less
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.module.js
minor change to the "deploy stage" table to allow word breaking, so the action icons don't get pushed out of view when the table's cell content is too long.
> fix(ux): deploy stage table layout

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
When a pipeline is configured with a parameter that can be selected from an options list, yet the default value is not part of that options list, it looks as if nothing is selected by default.
In actuality, the default option is still selected (just not shown in the UI) and running the pipeline will result in running with the default value, even though that was not present to the user.
Additionally, if the user selects from one of the options, there is no way to select the pipeline's configured default.
This PR forces the default value to be part of the options list if it is absent.
> fix(pipeline): fix invisible parameter when default is not in options

- halconfig/settings.js
Current halconfig/settings.js has fixed values for aws settings.
It should pick up settings configured by halyard.
This works with https://github.com/spinnaker/halyard/pull/1024 .
Ref: https://github.com/spinnaker/spinnaker/issues/3271
> feat(halconfig): Have AWS settings configured by halyard to be picked up in settings.js

- app/scripts/modules/core/src/projects/projects.states.ts
The projects states are under `home.project.**`, but were also duplicated underneath `home.projects.project.**`.
The second set of states are not used, AFAICT
This is a baby step.  More steps to come, I hope.
> fix(core/projects): remove duplicative home.projects.project.** substates

- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/domain/IArtifactSource.ts
- app/scripts/modules/core/src/domain/index.ts
Add type hints and helper methods for working with the possible sources of expected artifacts. At the moment the only sources are `IStage` and `IPipeline`.
This is a continuation of the work for https://github.com/spinnaker/spinnaker/issues/2921
> feat(artifacts): provide helpers for working with sources of artifacts

- app/scripts/modules/core/src/artifact/react/ArtifactAccountSelector.tsx
Used when editing inline artifacts (https://github.com/spinnaker/spinnaker/issues/2921)
> feat(artifacts): add select box for artifact accounts

- app/scripts/modules/core/src/artifact/react/ExpectedArtifactKindSelector.tsx
Introduces a select box to support `IArtifactKindConfig` objects. Used when creating new artifacts for https://github.com/spinnaker/spinnaker/issues/2921
> feat(artifacts): add an artifact kind select box

- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
Fixed passing the cloud provider correctly to server groups so their details can render from the load balancer page.
https://github.com/spinnaker/deck/commit/060ad9cc0eed5cf389d2923436f02911a2a25b6a#diff-0051f567bb321bdd6ec4d5e2652f82f1 This introduced a bug where the details of the server groups could not be accessed because they are missing the provider value during state transition. 
This is fixed by passing the cloud provider to the server groups. This will still keep the instance provider intact as it is hydrated with the provider information.
> fix(core): Server group details could not be opened

- app/scripts/modules/core/src/artifact/artifact.module.ts
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactEditor.tsx
This is the inline editor component for https://github.com/spinnaker/spinnaker/issues/2921
A GIF of using the editor in the deploy manifest stage:
> feat(artifacts): add inline artifact editor

- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
Given a pipeline execution with a `Bake` and `Deploy` stage (which has `Changes` to show):
1. Click the `Deploy` stage to show its details, see that the `Changes` section appears
2. Click the `Bake` stage to show its details
3. Click back to the `Deploy` stage to show it's details, the `Changes` section is now missing
The evaluation of whether or not to to display the "changes" tab is happening too early. Works fine if the `Deploy` is the first stage to be detailed, but if we're transitioning from another stage, the evaluation of what sections to display (which I've now refactored into `evaluateSections`) is evaluating while scope still contains the old stage and doesn't get to run after the scope is updated with the new stage.
Adding another evaluation within `initialized` lets it …
> fix(pipeline/deploy): Fixed missing tab by reevaluating scope later

- app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js
The logic for matching containers to upstream images matches only on the container description, and doesn't take into account whether the source of the image (artifact, trigger, etc.).  The matching logic should be updated to account for image source.
> fix(kubernetes): Fix container selection with multiple triggers

- app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js
The logic for matching containers to upstream images matches only on the container description, and doesn't take into account whether the source of the image (artifact, trigger, etc.).  The matching logic
should be updated to account for image source.
> fix(kubernetes): Fix container selection with multiple triggers (#5705)

- app/scripts/modules/core/src/artifact/ExpectedArtifactSelectorViewController.ts
- app/scripts/modules/core/src/artifact/index.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestArtifactDelegate.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
This PR enables a user to define an expected artifact while in-situ on the Deploy Manifest stage configuration screen. This pulls together the previous merges for https://github.com/spinnaker/spinnaker/issues/2921
I'm not particularly happy with the amount of code that's needed for a stage to utilize the inline editor. At the moment adding support to a new stage will involve writing a delegate class that meets the `IExpectedArtifactSelectorViewControllerDelegate` interface. In this PR it's an extra 100 lines of code that's specific to the deploy manifest stage. I'm still looking for ways to reduce this burden but there's no reason to hold back the functionality while I think about that. Suggestions welcome here.
> feat(kubernetes): use inline artifact editor for deploy manifest artifact

- app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js
When generating an image name from the registry, we were only replacing the first period, which breaks for registries that have more than one period.
> fix(kubernetes): Replace all periods in image name

- app/scripts/modules/kubernetes/src/serverGroup/configure/configuration.service.js
When generating an image name from the registry, we were only replacing the first period, which breaks for registries that have more than one period.
> fix(kubernetes): Replace all periods in image name (#5711)

- app/scripts/modules/core/src/application/service/applicationDataSource.ts
- app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
- app/scripts/modules/core/src/task/task.dataSource.spec.ts
I verified that no current afterLoad() implementation mutates the current data source's `data[]`, therefore calling dataUpdated() should be unnecessary.
> refactor(core/entityTag): Remove dataUpdated() call from DataSource onLoad

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html
Before:
An errant "Expected Artifacts" label would appear beneath the YAML editor.
After:
The label no longer appears.
> fix(kubernetes): hide expected artifact label when manifest source is text

- app/scripts/modules/openstack/src/loadBalancer/configure/wizard/upsert.controller.js
- app/scripts/modules/openstack/src/loadBalancer/configure/wizard/upsert.controller.spec.js
These tests were passing the test data to the service and the service was mutating the data.
Because of this, the expect calls were always true (the test wouldn't fail no matter what data you tested against)
> test(openstack): Fix some openstack load balancer update tests

- app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
- app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
Matching was switched to use `vpcName` instead of `vpcId` so that we can perform cross account matching (names will be the same whereas ids would differ).
Looks like `vpcName` was missing from the securityGroup in the **standalone** security groups view. This caused the match logic to set the `vpcId` to null, which is then later used to filter the list of security groups to populate into the dropdown (we default to only showing security groups in the matching vpc, with the option to select from other accounts).
Since nothing would match against null, we ended up filtering out all groups so there would be nothing to select from. This fix allows the matching and subsequent filtering to work properly again.
> Security groups standalone missing vpcName

- app/scripts/modules/core/src/application/application.model.spec.ts
- app/scripts/modules/core/src/application/application.model.ts
- app/scripts/modules/core/src/application/applicationModel.builder.ts
- app/scripts/modules/core/src/application/nav/ApplicationRefresher.tsx
- app/scripts/modules/core/src/application/service/ApplicationReader.ts
- app/scripts/modules/core/src/application/service/applicationDataSource.ts
- app/scripts/modules/core/src/pipeline/config/actions/delete/deletePipelineModal.controller.spec.js
- app/scripts/modules/core/src/pipeline/config/actions/rename/renamePipelineModal.controller.spec.js
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.spec.tsx
- app/scripts/modules/core/src/task/task.dataSource.spec.ts
- app/scripts/modules/core/src/utils/index.ts
- app/scripts/modules/core/src/utils/q.ts
- karma.conf.js
- Add two streams: one for raw `data$` and one for fetch `status$`
- Refactor onRefresh and onNextRefresh to use the streams
- use `nginject`
In some future refactor, I intend to replace the promise based refresh() method and nuke the mutable status flags (`loading`/`loaded`/etc).
- Removed addDataSources (moved to Application constructor)
- Derive application fetch `status$` stream from individual DataSource `status$` streams
- Require Data Source configs earlier (as a constructor parameter) for more predicable lifecycle
- Utilize new streams api
> refactor(core/application): Begin migration of Application Data Sources to Rx streams

- .travis.yml
This will build all the modules in parallel like:
<kbd>![](https://cl.ly/401b67525f40/Screen%20Recording%202018-09-18%20at%2001.54.gif)</kbd>
which will help reduce the time that travis takes to test.
- prior to #5750 being merged it took ~8 mins
- after #5750  was merged in, it took: ~11 mins
- with this PR, it now takes: ~6 mins. 😱 🎉 
> note: travis is usually limited to building 5 parallel jobs at a time, so we'll use that to our advantage and stack in the module builds.
> note: the build of "core" module is duplicated because each cloud provider's module requires the core module to be built.
> chore(travis): parallelize module build tests

- app/scripts/modules/core/src/application/application.model.ts
For some reason importing ICluster fro core/domain broke our downstream deck project
> fix(core/application): Use relative import of ICluster

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
No real change in the UI so no screenshots included but my previous PR to automatically choose a default artifact's kind from a match artifact completely broke default artifact behaviour.  This PR looks for a default artifact equivalent to the existing match artifact and uses that if available.  Previously I just copied the match artifact's type and kind, which meant that any logic specific to the default artifact type was completely skipped, effectively breaking default artifacts.
> fix(artifacts): use default artifact kind before match artifact kind

- app/scripts/modules/core/src/projects/dashboard/dashboard.controller.js
Increase scheduled re-fetch on clusters and executions in projects from 30s to 3min. 
There are some heavy projects set up at Netflix with multiple pipelines and clusters. This occasionally bombards clouddriver with requests especially if the tab is left open since it repeats the calls every 30s. In order to reduce these incidents, we decided to increase the interval for refetch from 30s to 3min.
> fix(core): Projects calls interval increased to 3min from 30s

- app/scripts/modules/core/src/artifact/NgAppEngineDeployArtifactDelegate.ts
- app/scripts/modules/core/src/artifact/NgBakeManifestArtifactDelegate.ts
- app/scripts/modules/core/src/artifact/NgGCEImageArtifactDelegate.ts
- app/scripts/modules/core/src/artifact/NgManifestArtifactDelegate.ts
- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
Notice that the newly-created expected artifact did not end up being selected in the select box. It likewise never ends up in the pipeline JSON. Very confusing. The manifest's artifact ID in the JSON *is* correctly set, however. Re-attempting the creation of the artifact always succeeds, so first creation is broken but second creation is fine.
Now the newly-created expected artifact does end up in the select box.
What's happening in the Before image is that the Pipeline which receives the new expected artifact is a stale reference that the view is no longer rendering. `$scope.$parent` is replaced at some point during the deploy stage's lifecycle, at which point the reference `$scope.$parent.pipeline` is also replaced, but I cannot find exactly when it is changing.
The workaround here is …
> fix(artifacts): Creating new expected artifact doesn't save first time

- app/scripts/modules/core/src/serverGroup/configure/common/v2InstanceTypeSelector.component.ts
- app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
* fix(provider/google): Updated command reference in archetype selector.
* fix(provider/google): Tolerate async backingData loading.
Cherry pick of https://github.com/spinnaker/deck/pull/5771.
> fix(provider/google): Deploy custom archetype fixes. (#5771)

- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/manifest/ManifestImageDetails.spec.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/ManifestImageDetails.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/manifestImageDetails.component.ts
- app/scripts/modules/kubernetes/src/v2/serverGroup/details/details.html
Closes https://github.com/spinnaker/spinnaker/issues/3263
Tooltip shows which container or init container the image is running on:
@Rigdon is this what you're looking for?
> feat(kubernetes): show images in server group details

- app/scripts/modules/core/src/account/AccountTag.tsx
- app/scripts/modules/core/src/account/accountTag.less
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
Having too many accounts utilized in a pipeline results in a messy execution group header:
This PR hides account tags if there are more than 2 and provides an on-hover handler to show those that are hidden:
It's not the prettiest thing in the world. Any objections to merging? Open to suggestions on the animation or layout.
Closes https://github.com/spinnaker/spinnaker/issues/3200
> feat(core): collapse execution group account tags if there are more than 2

- app/scripts/modules/cloudfoundry/src/cf.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/config/validation/validServiceParameterJson.validator.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteService/cloudfoundryDeleteServiceStage.js
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteService/deleteServiceStage.html
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteService/deleteServiceStepLabel.html
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.js
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.less
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/deployServiceStage.html
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/deployServiceStepLabel.html
- app/scripts/modules/core/src/domain/IService.ts
- app/scripts/modules/core/src/domain/index.ts
- app/scripts/modules/core/src/index.ts
- app/scripts/modules/core/src/pipeline/config/stages/deleteService/DeleteServiceExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/deleteService/deleteServiceStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/deployService/DeployServiceExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/deployService/deployServiceStage.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
- app/scripts/modules/core/src/services/ServicesReader.ts
- app/scripts/modules/core/src/services/index.ts
This contains the necessary pipeline stages to support deploy and delete Open Service Broker services. Aside from Cloud Foundry, Kubernetes also provides a service catalog that presents an aggregate view of Open Service Broker services and allows for deploying, deleting, and binding those services.
More detail on our reasoning around OSB service provisioning [here](https://docs.google.com/document/d/1cEkB2SdgrUNg1biNjHPd5H0WNv9IJSt1IDfSu4mKfc0/edit?usp=sharing)
> feat(provider/cf): add deploy and delete service pipeline stages

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/core/src/utils/retryablePromise.ts
The current logic for cancelling polling for an execucution is broken; in particular, if the API call to get an execution returns an error the polling will continue even after navigating away and unmounting the component.
> fix(core): Fix polling cancellation on manual trigger

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- settings.js
feat(core): Call new manual execution endpoint in Executions.tsx
Update Executions.tsx to call the new manual execution endpoint.
This change also does the following:
* Handles cancelling polling when Executions.tsx unmounts, which was not handled before
* Refactors some of the common manual triggering logic out of the react components and into a service
feat(core): Add triggerViaEcho to settings.js
> Call new manual execution endpoint in Executions.tsx

- app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
- app/scripts/modules/core/src/presentation/forms/fields/TextField.tsx
- app/scripts/modules/core/src/presentation/forms/fields/formikField.tsx
- app/scripts/modules/core/src/presentation/forms/interface.ts
- app/scripts/modules/core/src/presentation/forms/layouts/BasicLayout.tsx
(…and some other things)
WizardModal: support formClassName prop
TextField: Only show validation errors when field is touched
BasicLayout: Support input field with no label
formikField/TextField: support touched prop and set touched from onBlur
> feat(core/presentation): Support validation when fields are touched

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/openstack/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/titus/package.json
As far as I can tell we don't rely on the behavior of `prepare` (which also gets triggered on `install` in addition to `publish`). This just updates us to a more use-case appropriate `prepublishOnly` script across all packages.
An added side-benefit of this is a more convenient experience for those of us that use [`yalc`](https://github.com/whitecolor/yalc).
> chore(package): prepare -> prepublishOnly for everything

- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
#5818 added a check for a parameterized `imageId`, but in many cases that field can be undefined.
> fix(titus/deploy): fix parameterized imageId fix

- app/scripts/modules/core/src/instance/InstanceReader.ts
- app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.controller.js
- app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.html
- app/scripts/modules/core/src/instance/details/console/consoleOutput.modal.less
- app/scripts/modules/core/src/instance/details/console/consoleOutputLink.directive.js
- app/scripts/modules/kubernetes/src/instance/details/details.html
- app/scripts/modules/kubernetes/src/v2/instance/details/details.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/JobManifestPodLogs.tsx
Closes [issue #3360](https://github.com/spinnaker/spinnaker/issues/3360)
Updates kubernetes instance logs and job logs to be divided into tabs by container. Adds refresh functionality to instance logs:
cc @danielpeach @lwander
> feat(provider/kubernetes): split kubernetes pod logs by container #3360

- app/scripts/modules/oracle/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/oracle/src/pipeline/stages/bake/ociBakeStage.js
Use read-only text field for region instead of select field in Oracle Bake Configuration.  Note that in oracle provider, there is only one region per account.
> fix(bakery/oracle): use read-only text field for bake region

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html
I created a new issue separate from the Kubernetes JSON patch issue since I think this is an unrelated problem. We need to save the `patchBody` on the stage as a plain object so it can be serialized to JSON, but currently we are saving the raw YAML string, which causes CloudDriver to throw an error when the pipeline is run.
> fix(kubernetes): fix saving of kubernetes yaml patches #3433

- app/scripts/modules/core/src/pipeline/config/stages/core/executionSummary.html
- app/scripts/modules/core/src/pipeline/details/stageSummary.component.ts
Corresponds to https://github.com/spinnaker/orca/pull/2445
Deploy stages can't be skipped - just using deploy as an example.
Button:
Modal:
After skipping a stage:
> feat(core): skip stage button

- app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
- app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.html
- app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
- app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.html
We support this for a normal red/black and have been asked to also allow it during a rollback.
related to spinnaker/orca#2456
> feat(rollback): Support wait before disable during an orchestrated rollback

- app/scripts/modules/core/src/account/AccountSelectField.tsx
Dropdowns were empty since `componentWillReceiveProps` is not called on mount and `props.account` never change after that so `groupAccounts` never has a chance to map them into `state`.
> fix(core/account): Fixed AccountSelectField missing state initialization

- app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js
Cloning a security group gets the entire source security group object, then updates it with any modifications made in dialog. Unfortunately, "account" exists as multiple attributes:
- `account`
- `accountId`
- `accountName`
- `credentials`
and the `<account-select-field>` can only update a single attribute. To address this, we can copy the updated account to the rest of the fields.
> fix(amazon): Fixed cloning security group across accounts

- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.html
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.ts
This PR just moves a string template into an HTML file. Upcoming PR makes modifications to the template but I didn't want to mix logic change with this diff noise.
> feat(appengine): move config template into html file

- app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
The errors object in Formik 1.x mirrors the shape of the form data.  This means idiomatic formik will set things like `errors.object.array[0] = 'This is the error message'`.
If wizard page 1 adds `errors.object.array[0] = 'error message'` and page 2 adds `errors.object.textfield = 'a different error'`, using a simple `Object.assign` will clobber `errors.object` and lose the errors from page 1.
Additionally, now that errors objects are deep objects, you cannot do `Object.keys(errors).map(key => errors[key])` to get a list of error messages.  Thus, the `flattenErrors` method which flattens errors to an object, i.e. from:
```js
errors = {
object: {
array: [
'error message'
],
textfield: 'a different error',
}
};
```
to:
```js
{
'errors.object.array[0]': 'error message', …
```
> fix(core/modal): Deep merge `errors` object

- app/scripts/modules/core/src/artifact/expectedArtifact.service.spec.ts
- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
Fixes https://github.com/spinnaker/spinnaker/issues/3491
This PR makes Deck a bit more resilient when an artifact doesn't include a kind string.
Previously, if an artifact did not have a kind:
Now when kind is missing rely on the type, or failing that, assume kind is "custom":
The kind select remains outlined in red since I didn't want a UI component to silently modify the artifact's data, but at least the user is still able to modify the content of the artifact.
> feat(artifacts): infer kind from type if kind is not available

- app/scripts/modules/core/package.json
278 didn't contain the latest PR
> Chore(core): bump to 0.0.279

- app/scripts/modules/core/src/projects/configure/FormikApplicationsPicker.tsx
This encapsulates "pick one or more applications" into a component using formik.  At some point, we should replace this with a ReactSelect multi select (pills).
TL;DR;
```ts
<Formik initialValues={{ config: { applications: [] } }} render={formik => (
<FormikApplicationsPicker applications={allApplications} name="config.applications" />
)} />
```
> feat(core/projects): Add a FormikApplicationsPicker react component

- app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.html
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.ts
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/serverGroupWizard.less
- app/scripts/modules/appengine/src/serverGroup/transformer.ts
- app/scripts/modules/core/src/artifact/IArtifactAccountPair.ts
- app/scripts/modules/core/src/artifact/NgAppengineConfigArtifactDelegate.ts
- app/scripts/modules/core/src/artifact/index.ts
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactEditor.tsx
- app/scripts/modules/core/src/domain/IArtifactEditorProps.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/core/stageConfigField/StageConfigField.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/singleFieldArtifactEditor.tsx
This PR adds an artifact editor to the appengine server group wizard. A user can supply app.yaml or [any of the other appengine config files](https://cloud.google.com/appengine/docs/standard/python/configuration-files) via an artifact from trigger or stage.
> feat(provider/appengine): enable artifacts as config files

- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
Per [this issue](https://github.com/spinnaker/spinnaker/issues/3514), refreshing Docker images was failing with the following error due to unbound method:
> fix(docker): fix binding of `handleRefreshImages` method #3514

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
When manually executing templated pipelines, the "Force Rebake" checkbox is missing, even though the pipeline contains a bake stage. Templated pipelines do not contain any stages before runtime, so the bake stage is never asked to inject its custom logic into the manual execution modal.
This is a simple 90/10-solution that just ~~iterates through previous executions, finds the previous execution that actually ran, and naïvely copies the~~ plans a new execution and adds the stages to the pipeline, so that the bake stage magic is executed.
It might result in false positives or negatives if you are changing the pipeline template, but as the main structure of a pipeline rarely changes and the fact that there are no bad consequences of displaying a "Force Rebake" checkbox when there is no bake …
> feat(pipeline_templates): Display "Force Rebake" checkbox for MPT

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.less
Support a date picker for trigger parameters.
If the parameter has `"constraint": "date"` in the parameter config in the pipeline JSON, then when manually triggering the pipeline, the input for the parameter will only accept a valid date string and will have a date picker.
Currently no UI to actually pick the constraint type, JSON only feature right now.
@asher FYI
> feat(core): Support a date constraint on trigger parameters

- app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts
> fix(appengine): selectedProvider received as null when Create Server Group btn clicked

- app/scripts/modules/amazon/package.json
aa204d4e35a2073c4301f5510ee956801b03dbf3 fix(amazon/deploy): Fix clearing invalid security groups (#5948)
> chore(amazon): Bump version to 0.0.132

- package.json
- yarn.lock
Cherry-pick of https://github.com/spinnaker/deck/pull/5949 into 1.10 branch.
Fixes https://github.com/spinnaker/spinnaker/issues/3190
> chore(dependencies): bump deck-kayenta to 0.0.63

- app/scripts/modules/core/src/serverGroupManager/ServerGroupManager.tsx
- app/scripts/modules/core/src/serverGroupManager/ServerGroupManagerHeading.tsx
Fixes https://github.com/spinnaker/spinnaker/issues/3516
Before:
After:
Open to suggestions of a better way to indicate clickability. The duplication definitely isn't ideal.
> feat(kubernetes): include server group manager name in clickable clusters box

- app/scripts/modules/kubernetes/src/serverGroup/configure/CommandBuilder.js
I think this fixes https://github.com/spinnaker/spinnaker/issues/3544 and https://github.com/spinnaker/spinnaker/issues/3559
> fix(kubernetes): defaults can be passed in as null

- app/scripts/modules/core/src/artifact/ArtifactTypes.ts
- app/scripts/modules/core/src/artifact/react/ArtifactIconList.tsx
Fixes https://github.com/spinnaker/spinnaker/issues/3567
K8s kind now appears in list alongside artifact name:
> fix(kubernetes): add k8s kind in artifact icon list

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
Allow preconfigured webhooks to produce artifacts in deck. Previously preconfigured webhooks were not able to configure expected artifacts from deck. It appears this will enable that. I am not sure but I think this will work with orca as-is.
Everything else seems to be there for this to work?
> feat(artifacts): Allow preconfigured webhooks to produce artifacts

- package.json
- yarn.lock
Related: https://github.com/ui-router/react-hybrid/pull/138
This PR adds support for rendering UIView content using React Portals. This allows the child views to use the react context from the parent uiview. This should make global context APIs  like Redux easier to use.
> chore(*): Update uirouter/react-hybrid+react+angularjs to latest versions

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings.cf.tsx
allow only alphanumeric and '_' for env variable keys
> fix(provider/cf): allow only alphanumeric and '_' for env variable keys

- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
- app/scripts/modules/docker/src/image/DockerImageUtils.ts
- app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerConfig.tsx
- app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx
- app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
Be smarter about when we update docker image selector backing data, and consolidate the imageId generation into the control itself.
> refactor(docker): Consolidate and clean up image selector functions

- app/scripts/modules/core/src/pipeline/config/stages/StageConfigWrapper.tsx
- app/scripts/modules/core/src/pipeline/config/stages/core/IStageConfigProps.ts
- app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
When stage fields are updated, instead of mutating props directly and force updating, `StageConfig` components should actually invoke a callback with the changes.
Before:
```
this.props.stage.variables = variables;
this.props.stageFieldUpdated();
this.forceUpdate();
```
After
```
this.props.updateStageField({variables});
```
`StageConfigWrapper` exists purely to perform the `this.forceUpdate()` because we wouldn't want all the `StageConfig` components to have to make that call (or even be aware of it). The reason the force update is needed is because `$scope.stage` is updated above the render root. Once that can be encapsulated in the state of some parent component (when we migrate it from angular to react), the force update and the wrapper component should no longer be needed.
> refactor(stages): Adding StageConfigWrapper for cleaner StageConfigs

- app/scripts/modules/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx
I think this was disabled by accident. I don't see anything in the advanced settings to force it to be only enabled when `buildInfo` and `jenkins` properties exist
> fix(aws/serverGroups): always show AWS sever group settings

- yarn.lock
It looks like the yarn lockfile wasn't properly updated after upgrading uirouter to 5.0.21; commit the update that is generated by running yarn on the current package.json.
> fix(build): Fix yarn lockfile

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/pipeline/stages/runJob/TitusSecurityGroupPicker.tsx
Two tests for serverGroupConfiguration service started failing because the expected sort order was different (perhaps due to a chrome update to `sort()` api?).  I found the original PR that introduced this sorting #2937 and it seems to introduced due to a requirement of ui-select.  React-select doesn't have the same data requirements, so sorting in this way is no longer necessary.
> fix(amazon+titus/serverGroup): Revert custom sort logic no longer needed with react-select

- yarn.lock
I do not know "why", but we are seeing inconsistent behavior using the `copy-to-clipboard` functionality. It seems to fail when you copy something from somewhere else on a different web page, then try to use it. For whatever reason, I do not see it in the newer minor version of clipboard.js.
> chore(core): upgrade clipboard.js to 1.7.1

- app/scripts/modules/core/src/presentation/forms/FormikForm.tsx
Switch from a weird kludge using `<Field/>` to the supported formik `connect()` API
> fix(core/presentation): Use official formik `connect()` api to create `FormikForm` render-prop component.

- app/scripts/modules/core/src/pipeline/config/triggers/cron/cronPicker.html
A user entered "40" into the CRON trigger selector, assuming it would then trigger the pipeline every 40 minutes, which is...not something you can do with a single CRON trigger. It has to be something that 60 is a multiple of, so we should restrict the expression generator to those values.
> fix(core): restrict CRON trigger minutes options

- package.json
- yarn.lock
I fixed a bug with the new React Portal based ui-router react-hybrid code in `@uirouter/react-hybrid` `0.3.8`.  All React UIViews should once again have access to the same React context tree making features which use context (like Redux `connect()`) work much easier.
> chore(*): Update uirouter/react-hybrid to 0.3.8

- app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx
- app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts
Clouddriver has, for a long time, supported the notion of partial capacity updates, i.e. only changing the min, max, or desired value. We had not implemented anything in the UI, but ran into a minor incident due to (roughly) the following scenario:
1. An ASG has scaling policies, with min/desired/max set to 50/100/200.
2. A user goes to resize the ASG, setting the max to 300.
3. An alarm fires before the user submits the resize (but after the user opens the modal), setting the desired to 120.
4. The user submits the resize operation, sending 50/100/300.
5. AWS terminates the 20 new instances which were spun up to handle the alarm that fired.
6. Another alarm fires eventually, starting the process of spinning those new instances up.
> fix(aws): only send user-changed capacity fields on resize

- app/scripts/modules/kubernetes/src/container/securityContext/securityContextSelector.component.ts
This addresses issue: #2993. The problem is that deck pushes `FileSystem` and cloud driver expects `Filesystem`. This causes the pod yamls to not be updated and thus the deployed state to not reflect state as displayed in deck.
> fix(provider/kubernetes): Change FileSystem to Filesystem

- app/scripts/modules/core/src/widgets/spelText/spelAutocomplete.service.js
Turns out sometimes the values on spel autocomplete options can be _really_ long. I explicitly didn't want to invest any time into touching the old CSS that currently styles these dropdowns as it's done via `jquery-textcomplete` and I anticipate its days are numbered. So instead I changed the template string and added a `title` tooltip 🤷‍♂️ .
Because this is set at 90 characters I suspect folks will rarely ever run into it, but at least things won't look broken when there's a 500+ character value.
> fix(core/spel): Truncate spel autocomplete values to 90 chars

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings.cf.tsx
moved the `trigger` option to be second on the list of radio button options.
spinnaker/spinnaker#3617
> refactor(provider/cf): reorder artifact types

- app/scripts/modules/core/src/utils/workerPool.spec.ts
- app/scripts/modules/core/src/utils/workerPool.ts
@anotherchrisberry I generalized your worker pool code into a util class.  We can integrate this into the FP code some other day.
TLDR: 
```
const pool = new WorkerPool(2); // limit to 2 concurrent workers
pool.task(() => api.doStuff(1)).then(handleSuccess, handleFailure);
pool.task(() => api.doStuff(2)).then(handleSuccess, handleFailure);
pool.task(() => api.doStuff(3)).then(handleSuccess, handleFailure);
pool.task(() => api.doStuff(4)).then(handleSuccess, handleFailure);
```
And streaming via Rx https://stackblitz.com/edit/rxjs-workerpool?file=index.ts :
```ts
import { of } from 'rxjs'; 
import { map, mergeMap, combineLatest } from 'rxjs/operators';
import { WorkerPool } from './workerPool';
const delay = (millis = 0) => new Promise<void>(resolve => setTimeout(resolve, millis));
const …
```
> feat(core/utils): Add WorkerPool class to limit concurrency of promise based tasks

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupConfigurationModel.cf.ts
populate the red/black additional fields with the previously saved values from the pipeline stages.
> fix(provider/cf): populate red/black strategy additional fields

- yarn.lock
Older versions of upath declare a depdendency on node < 10, so this is needed for compatibility with node 10.
> chore(*): Upgrade upath to 1.1.0

- app/scripts/modules/core/src/application/service/ApplicationReader.ts
- app/scripts/modules/core/src/cluster/clusterSearchResultType.tsx
We are never calling `listApplications` with the `populateMap` parameter, so...let's just remove it. It's there to populate an email field in cluster search results, but there was a regression at some point in the past year that stopped it from being populated and nobody noticed.
> refactor(core): remove unused applicationMap code from ApplicationReader

- halconfig/settings.js
The last change to default to using the new manual trigger endpoint
only affected users running a localgit setup; to default to enabled
for halyard users, we need to change this file.
To turn off the settings, users can add the following to
settings-local.js:
window.spinnakerSettings.feature.triggerViaEcho = false;
> fix(core): Actually default to using new manual trigger endpoint

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
Before: Artifact account select incorrectly appears when manifest source is set to 'text'
After: Artifact account select does not appear unless manifest source is set to 'artifact'
> fix(artifact): hide artifact account selector when deploying manifest from inline text

- app/scripts/modules/core/src/entityTag/EntityTagsReader.ts
- app/scripts/modules/core/src/entityTag/clusterTargetBuilder.ts
Relates to #5498
A pipeline can be be renamed.  Seems like we should use the `pipeline.id` as the entity tag's `entityId` value instead of the `name`.
@nvndnl  PTAL
> fix(core/entityTag): Use pipeline.id for pipeline entity tag's `entityId` value

- app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
- app/scripts/modules/core/src/pipeline/config/stages/stage.html
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
The sort and filtering on the stage type picker is really bad, and it's getting worse as new stages are added:
**Bad matches**
Stages are matched based on any field in the stage config; apparently, some of these have a "wa" in them somewhere.
**Bad order**
The matches remain in alphabetical order, even if you type the name of a stage that exists.
**PR**
Instead, sort by label first, then description, and sort based on proximity of search text within those fields. Also, highlight it, so people can see quickly why it's matched:
Sorry for the Angular. I told myself I'd never touch anything Angular and not rewrite it to React, but this is a big one to bite off.
> fix(core): sort stage matches by label, then description

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestDetailsLink.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestStatus.tsx
Fixes https://github.com/spinnaker/spinnaker/issues/3443
Before, clicking a Details link in an execution showed the clusters screen with all clusters shown.
After, clicking a Details link in an execution shows the clusters screen filtered to the namespace that the resource you clicked on belongs.
> fix(kubernetes): clicking execution details link filters clusters screen

- app/scripts/modules/cloudfoundry/src/help/cloudfoundry.help.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CloudfoundryDeployServiceStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyService/CloudfoundryDestroyServiceStageConfig.tsx
add an option to override the time out setting when deploying or destroying services in pipeline stages.
spinnaker/spinnaker#3637
> feat(provider/cf): option to define timeouts for service creation/destroy

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestDetailsLink.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestStatus.tsx
Commits:
fix(kubernetes): fix manifest update race condition (#6101)
fix(kubernetes): namespace details links in executions dont work (#6114)
fix(kubernetes): clicking execution details link filters clusters screen (#6120)
> fix(kubernetes): cherry-pick execution and link fixes from master into 1.11

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
I don't want to brag, but I am very good at design.
**Current:**
**PR:**
> style(amazon): fix load balancer label alignment in server groups modal

- app/scripts/modules/cloudfoundry/src/pipeline/stages/resizeAsg/CloudfoundryResizeAsgStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/resizeAsg/cloudfoundryResizeAsgStage.module.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/details/resize/resizeCapacity.html
- app/scripts/modules/cloudfoundry/src/serverGroup/details/resize/resizeServerGroup.controller.ts
Now CF uses the Capacity struct in clouddriver to handle the case of
scaling-down ASGs to 0 instances, so CF's implementation in deck
must also use it.
spinnaker/spinnaker#3670
> fix(provider/cf): Rectify scaling ASGs

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/amazon/src/serverGroup/AvailabilityZoneSelector.tsx
- app/scripts/modules/amazon/src/subnet/subnetSelectField.component.ts
This should fix https://github.com/spinnaker/spinnaker/issues/3242 and is similar to #6108 with added fix to `AvailabilityZoneSelector` similar to #6074
> fix(amazon/loadBalancer) Fix load balancer VPC selection

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/amazon/src/serverGroup/AvailabilityZoneSelector.tsx
- app/scripts/modules/amazon/src/subnet/subnetSelectField.component.ts
This should fix spinnaker/spinnaker#3242 and is similar to #6108 with added fix to AvailabilityZoneSelector similar to #6074.
Fix to release-1.10.x, similar to #6115
> fix(amazon/loadBalancer): Fix load balancer VPC selection

- app/scripts/modules/core/src/application/service/ApplicationReader.ts
Turns out that historically we've updated the `disabled` flags on child data sources when their parent is disabled, but _not_ when they're enabled. The only reason it got noticed was because there's some child sources that populate nav items which were not updating without a refresh, but it's nice to do the right thing I suppose.
> fix(core/dataSources): make child sources always honor their parents' disabled state

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/AmazonCloneServerGroupModal.tsx
These methods are referenced in a way that `this` gets bound differently, resulting in a "Unknown Error" + "Operation Succeeded" message combo that is a little confusing for users.
> fix(amazon): use arrow functions in server group modal

- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
There is no reason to cache this call! We try to get the data out of local storage, but if it is not there (because the cache has expired or, more likely, been invalidated because it was missing something), we need to get new data from the server. If we always returned the first API call we made from the server, we're never going to get new data.
This is why, when you create a new server group, all security groups disappear from the page. The data source gets into a state where it keeps trying to reload the data, because it does not trust what it's getting back, but it just reloads the data from the HTTP cache.
Some work needs to be done still on the security group caching - it would be nice to remove the need for caching in local storage altogether - but this is a quick easy fix for a …
> fix(core): do not cache getAllSecurityGroups API call

- app/scripts/modules/amazon/tsconfig.json
- app/scripts/modules/appengine/tsconfig.json
- app/scripts/modules/cloudfoundry/tsconfig.json
- app/scripts/modules/docker/tsconfig.json
- app/scripts/modules/ecs/tsconfig.json
- app/scripts/modules/google/tsconfig.json
- app/scripts/modules/kubernetes/tsconfig.json
- app/scripts/modules/openstack/tsconfig.json
- app/scripts/modules/oracle/tsconfig.json
- app/scripts/modules/titus/tsconfig.json
I made some changes in core and tried building all the downstream modules using `gradle/buildModules.sh`.  Typescript complains that it doesn't understand the props being passed to the component from `core` when running `npm run lib` from `amazon` module (for example).
```
src/loadBalancer/configure/common/LoadBalancerLocation.tsx:346:19 - error TS2339: Property 'value' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AccountSelectInput> & Readonly<{ children?: ReactNode; }> & Readonly<IAccountSelectInputProps>'.
346                   value={values.credentials}
~~~~~~~~~~~~~~~~~~~~~~~~~~
src/loadBalancer/configure/common/LoadBalancerLocation.tsx:347:29 - error TS7006: Parameter 'evt' implicitly has an 'any' type.
347                   onChange={evt => …
```
> Add core alias tsconfig

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupCapacity.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupInstanceType.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupSecurityGroups.tsx
- app/scripts/modules/core/src/serverGroup/configure/common/instanceArchetypeDirective.html
- app/scripts/modules/core/src/serverGroup/configure/common/v2instanceArchetype.directive.html
Fixes an obscure and kind of dumb Chrome-specific bug where, if a user enters a very long value in the `Image` field search box, the modal gets stuck over to the right. This happens because there are several component in the modal that are wider than the modal, but the `steps` div has `overflow-x: hidden`. When the super long entry goes into the search field, Chrome scrolls the content over to follow the cursor, but then leaves it pulled to the right:
The trick is to make sure nothing actually blows over the width of the steps section by adding `container-fluid form-horizontal` classes to force the `form-group` divs to...look, there is a lot of Bootstrap and a lot of CSS happening in these modals. I barely understand why this fixes it.
Firefox and Safari handle this scenario correctly, …
> fix(core/amazon): avoid overflow on server group modal components

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/core/src/pipeline/config/stages/core/IStageConfigProps.ts
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.module.ts
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
Mostly driven by server data. Titus execution logs will need to be placed at `stage.context.execution.logs` for the Execution Details to properly link out to it though.
> feat(runJob): Adding support for preconfigured run job stages

- app/scripts/modules/core/src/cluster/cluster.service.ts
- app/scripts/modules/core/src/config/settings.ts
- halconfig/settings.js
- settings.js
For https://github.com/spinnaker/spinnaker/issues/3699
The config alphabetization is a periodic refactor we (maybe just I) seem to do. I don't know if it's worth the hassle but I'm doing it anyway. Also clearing out some unused config flags/features: `vpcMigrator`, `netflixMode`, `fastProperty`, `clusterDiff`.
> refactor(core): alphabetize config, make onDemandClusterThreshold configurable

- app/scripts/modules/amazon/src/loadBalancer/TargetGroup.tsx
- app/scripts/modules/amazon/src/loadBalancer/targetGroup.less
- app/scripts/modules/core/src/cluster/rollups.less
- app/scripts/modules/core/src/loadBalancer/LoadBalancerServerGroup.tsx
- app/scripts/modules/core/src/loadBalancer/loadBalancerPod.less
We have an extremely minimal affordance to indicate a user can click on a server group, load balancer, or security group - just a color change of the border from gray to blue:
_Server group (first one hovered)_
_Load balancer_
_Target group within a load balancer_
This is not the ultimate solution to discoverability that these things are clickable, but it's surely better than what we currently have?
_Server group_
_Load balancer_
_Target group_
> feat(core): increase visibility of hover on clickable pods

- app/scripts/modules/core/src/presentation/WatchValue.tsx
- `isEqual` is optional and ought to be typed as such
- Previously `render` would spit out `undefined`, which React finds displeasing
> fix(core/presentation): Give WatchValue better typing, tolerate no children

- app/index.deck
- app/scripts/modules/core/src/analytics/analytics.service.js
Not that this is the biggest contributor to slow load times for Deck, but...might as well not load the Google Analytics script if it's not going to be used?
> fix(core): do not load GA script if not configured

- app/scripts/modules/docker/package.json
adc4be1196681daef5433b5b2d7a1c0c6d784c26 fix(docker): Make sure to preselect define type for image selector (#6188)
> chore(docker): Bump version to 0.0.27

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
I kind of can't believe this hasn't come up before, but the instance type options are just in some random order.
> fix(aws): sort instance type options in server group modal

- app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
Turns out we have this great new instance type showing up, `p3dn`.
> fix(aws): really properly sort instance types

- app/scripts/modules/amazon/package.json
2c15170f9cc61638a38b34cf180b17543ffcfd0d fix(aws): really properly sort instance types (#6191)
75d7e334a08a232a57567ce54bcf01ff7a66a2b1 fix(aws): sort instance type options in server group modal (#6190)
> chore(amazon): Bump version to 0.0.146

- .gitignore
- package.json
- test/functional/tests/core/home.spec.ts
- test/functional/tests/core/pages/HomePage.ts
- test/functional/tests/core/pages/InfrastructurePage.ts
- test/functional/tests/core/pages/Page.ts
- test/functional/tests/google/clone.spec.ts
- test/functional/tests/google/pages/CloneModalPage.ts
- wdio.conf.js
- yarn.lock
This is the first in a series of commits adding functional testing in Deck. The complete feature is a lot of code so I'm breaking it up to make review a little easier. In this PR I'm adding webdriver.io (a node.js selenium wrapper + test runner) and some tests.
This commit adds two simple tests: a smoke test that opens the home page and a test that checks for expected values in a GCE clone modal.
These tests will only reproducibly pass if the developer sets up a Spinnaker deployment and GCE infrastructure matching those used when the test was written. A follow-up PR will add fixtures to remove this limitation.
Screencap of a successful test run:
And output at the terminal looks like this:
```bash
sbws@sbws-macbookpro:~/dev/spinnaker/deck
(introduce-functional-tests) λ yarn functional
yarn …
```
> feat(tests): add some functional tests to Deck

- test/functional/README.md
- test/functional/tools/FixtureService.ts
- test/functional/tools/GCSFixtureDownloader.ts
This adds a download utility that will download existing network fixtures to disk for any `.spec.ts` file that doesn't have a corresponding `.mountebank_fixture.json` file.  Support for GCS buckets is introduced here but adding support for other providers should be easy enough (for example if we decided in future to put network fixtures in git instead).
In a follow up commit I will add a publicly accessible bucket to serve up the fixtures and also introduce a script to automate all of this ceremony.
> feat(tests): Add downloader to fetch pre-recorded network fixtures

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
We should only be setting the `amiName` field if we're cloning a cluster, not if we're configuring it for a pipeline.
Fixes a minor regression from a couple of weeks ago.
> fix(aws): do not hardcode amiName when adding pipeline cluster

- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.spec.ts
- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
- app/scripts/modules/core/src/cluster/filter/mockApplicationData.js
- app/scripts/modules/core/src/domain/IServerGroup.ts
- app/scripts/modules/core/src/help/help.contents.ts
Adding label search functionality as a separate PR from label filter functionality as the latter is a bit messier (#3238)
> feat(core): add ability to search clusters by labels

- app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
Part of a [set of changes](https://docs.google.com/document/d/10y1KIBoSWlerFxkkW8nJLZ_zspz7ToCRifnWoFHyp8k/edit?usp=sharing) to expected artifacts.
> refactor(triggers): move expected artifact definition before triggers

- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentExecutionDetails.tsx
If a manual judgement is clicked and the user clicks to another Manual Judgement stage before the request completes, the new stage will show the `Continue` (or `Stop`) button as still pending, and it will remain pending even after the request completes.
This is because the `ManualJudgementApproval` component's `submitting` state remains true when switching to another `Manual Judgement` stage.
A simple `key={stage.refId}` fixes this as it tells React that the component instance shouldn't be shared between the two stages.
> fix(judgement): Adding stage refId as component key to bust residual state

- app/scripts/modules/appengine/src/serverGroup/configure/wizard/basicSettings.html
Before:
After:
Also fixes a bug where artifact account dropdown incorrectly appears when "GCS" and "via text input" radio buttons are selected.
> fix(appengine): move artifact account dropdown below radio buttons

- app/scripts/modules/core/src/filterModel/FilterModelService.ts
Clusters page filtered the page based on previously stored server group. 
As a result, if the user clicks on a different server group from the executions view, they would still land in the saved filter state. Clusters' saved state records the params applied for an application and whenever the user revisits the clusters page, it applies these params from saved state. This works well until we change the serverGroup for the same application. Since we didn't check against server group value changes in the new params vs saved state, we were always reverting back to the saved state. 
Fixed this behavior for serverGroup names. There are other filters like region/acct but I don't believe we deep link to just those filters.
> fix(core): Prevent cluster saved state filter overrides

- app/scripts/modules/amazon/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/azure/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/core/src/pipeline/config/stages/bake/modal/addExtendedAttribute.html
- app/scripts/modules/google/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/openstack/src/pipeline/stages/bake/bakeStage.html
Many optional paramters are defaulted by various config files during bake stages; it is useful to be able to explicitly clear these values using extended attributes. In order to allow this, allow the value of an extended attribute to be empty.
> fix(bake): Allow null extended attributes in bake stages

- app/scripts/modules/assert_clean_master.sh
- app/scripts/modules/build_order.sh
- app/scripts/modules/publish.sh
- app/scripts/modules/show_dirty_modules.sh
- app/scripts/modules/show_unpublished_commits.sh
This PR improves the safety of the deck publish script: `/deck/app/scripts/modules/publish.sh`.
Improvements:
- Asserts that you are on master, do not have a dirty working copy, and are not ahead or behind of upstream
- Updated dependencies (`yarn`) before building packages
- Builds all dependent packages, i.e., before publishing `titus`, it will build `docker`, `amazon`, and `core`
- Automatically builds dependent packages (and/or multiple published packages) in the correct order
- Provides a PR title that includes the packages being published and their new versions
- Automatically opens a browser to the "create pull request" screen
- Allows the scripts to be invoked using an absolute path `./app/scripts/module/publish.sh core`
- Supports "dry run" mode by answering "no" to the "publish …
> chore(scripts): Improve publish safety, add assert_clean_master.sh and build_order.sh

- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
Resolves https://github.com/spinnaker/spinnaker/issues/3371
Before, the continue button appears on the left.
After, it's on the right.
> feat(stage): manual judgement continue button moved to right

- app/scripts/modules/amazon/src/loadBalancer/configure/common/SecurityGroups.tsx
this logic was accidentally reversed during a prior refactor
> fix(amazon/loadBalancer): Restore the "security group removed" warning when switching regions

- app/scripts/modules/amazon/src/serverGroup/configure/AmazonImageSelectInput.tsx
After watching @ajordens try to use this menu, it seems like we should make two changes:
1. make the sorting options sticky so they don't disappear when the user scrolls through the menu
2. sort the menu options by timestamp by default
> feat(aws): make image sort options sticky; sort by TS by default

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
These durations are so nice, we should just show them by default.
We already have a GA event on the toggle of the show stage durations checkbox, so we'll track the usage of the feature at Netflix over the next month or two. If nobody seems to be turning off the durations, we'll remove the checkbox and behavior altogether unless there are objections.
> feat(core): show pipeline stage durations by default

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
If you click the "Save" button on a pipeline, then make changes to the config while the pipeline is still saving, those changes will not be tracked in the current state of the pipeline config, so you won't see the Save button again unless you make an additional change - and the revert button will do the wrong thing.
This is a very old bug. I considered converting the Angular here to React, but...it's 500+ lines of Angular.
> fix(core): avoid in sync race condition when saving pipelines

- app/scripts/modules/amazon/src/loadBalancer/details/LoadBalancerActions.tsx
FYI `uib-tooltip` does not do what you want it to do on React components.
> fix(aws): provide help explanation when load balancer delete is disabled

- app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.html
In an IP range rule, you can specify the protocol as `-1` and AWS will treat it as a wildcard, allowing traffic from all ports and all ranges. 
This is not super clear in the UI:
This is more clear:
> fix(aws): clarify all ports/protocols on IP range ingress

- app/scripts/modules/core/src/pipeline/triggers/NextRunTag.tsx
The CRON next run calculator works on UTC time. Since the Echo scheduler works in whatever timezone is configured, we were doing some really bad things to calculate the next run if there was an hourly restriction. The bad things worked most of the time, but that is arguably worse, since it would sometimes give the wrong calculation.
Turns out, the `next` method can take another parameter, which is the start date. So...we can just pass that in, offset back in time to UTC. This is a good thing, and gives us the correct calculation.
It would be nice to get that value from the backend, but, for now, this is at least better.
> fix(core): fix next CRON trigger calculation offset

- app/scripts/modules/amazon/src/logo/aws.logo.less
- app/scripts/modules/appengine/src/logo/appengine.logo.less
- app/scripts/modules/cloudfoundry/src/logo/cf.logo.less
- app/scripts/modules/core/src/cloudProvider/cloudProviderLogo.less
- app/scripts/modules/dcos/logo/dcos.logo.less
- app/scripts/modules/ecs/src/logo/ecs.logo.less
- app/scripts/modules/google/src/logo/gce.logo.less
- app/scripts/modules/kubernetes/src/logo/kubernetes.logo.less
- app/scripts/modules/openstack/src/logo/openstack.logo.less
- app/scripts/modules/titus/src/logo/titus.logo.less
`mask-*` was not implemented by several of the major browsers a few years ago when the cloud provider logo work was first done. 
This meant we worked around it with some really clunky `filter` code to get the green color, which wasn't exactly the same as the other green color.
`mask-*` is now implemented in Safari, Edge, and Firefox, so...let's use it and get rid of the gross `filter` bits?
> refactor(*): use mask-image CSS for cloud provider logos

- app/scripts/modules/core/src/help/HelpField.tsx
I noticed HelpField was being unnecessarily re-rendered a lot which was showing up during a perf profiler session.  Since it's a leaf node it should be safe to switch to PureComponent.
> refactor(core/help): Switch HelpField to PureComponent

- app/scripts/modules/core/src/navigation/urlParser.ts
- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
We have some users taking advantage of the deep linking ability to start a manual execution. They would like the ability to specify values for the parameters in the query string, e.g.
```
executions?startManualExecution=myPipeline&pipelineParam1=foo
```
I was going to rewrite this component in React, but...there's a lot going on in this component, so will for sure do it later.
> feat(core): allow setting params via query string on manual execution

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraphNode.tsx
The transform applied to the foreignObject doesn't seem to translate the hit target. Wrapping the foreignObject in a group seems to do the job.
Before, an area of the label is not clickable:
After, the entire label is clickable as expected:
Fixes https://github.com/spinnaker/spinnaker/issues/3828#event-2060240398
> fix(pipelines): hit target for labels is off by 8px

- app/scripts/modules/kubernetes/src/v2/manifest/editor/editor.less
Closes https://github.com/spinnaker/spinnaker/issues/3807
> fix(kubernetes): specify monospace fonts to prevent cursor misalignment in ace editor

- app/scripts/modules/core/src/pipeline/service/execution.service.ts
There are multiple ways an execution is hydrated (not just via the `hydrate` method). When we call the `hydrate` method, we should short-circuit out if it's already hydrated, rather than reload the execution.
This cuts down on the long loading indicators on execution stage tooltips.
> fix(core): do not overhydrate executions

- app/scripts/modules/core/src/presentation/forms/inputs/JsonEditor.tsx
Without this, `cmd+f` doesn't do anything.
With this, you get a pretty nice search box within the editor.
> feat(core): allow searching in pipeline JSON

- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.spec.ts
- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
When it's brand new, there are `isNew` flags on the pipeline and its stages. These get removed by the `savePipeline` method, which is a surprise!
It's better to make a deep copy of the config in the save method, and remove the fields from there.
Also toggling the `hasHistory` flag after a successful save.
> fix(core): do not flag pipelines dirty on initial save

- app/scripts/modules/core/src/presentation/forms/forms.less
- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
Currently, if an imageId is present in the config on load of this control, and the image cannot be found in the registry, it will clear it and set imageId to nothing.
This is bad.
After this fix, when an image cannot be found, it will switch to manual entry with a warning.
>  fix(docker): Do not clear an existing imageId even if fields cannot be found in registry

- app/scripts/modules/core/src/cluster/allClusters.controller.js
- app/scripts/modules/core/src/cluster/allClusters.html
- app/scripts/modules/core/src/instance/InstanceList.tsx
- app/scripts/modules/core/src/instance/InstanceListBody.tsx
- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
Instance sorting has been broken for...a while? Also, toggling the checkboxes on the clusters header do not cause the URL to change.
It would be nice to get away from the whole `sortFilter` thing, and use `$state` as the data source for these things. We'll get there eventually.
> fix(core): fix instance details sorting

- app/scripts/modules/core/src/pipeline/config/stages/wait/WaitStageConfig.tsx
- app/scripts/modules/core/src/widgets/spelText/SpelNumberInput.tsx
This is a hot feature that a lot of people have been asking for this year, the ability to have a zero second wait stage.
Also adding min/max to the `<NumberSpelInput>`, another hot feature our end users have been asking for.
> feat(core): allow min/max on NumberSpelInput, zero wait on Wait Stage

- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
If a user adds a new stage, then scrolls through the different stage types, selecting one, then another, then another, old fields from each stage config rendering will accumulate in the stage JSON. It's easy enough to clear those fields out, so we should do that.
> fix(core): clear stage-specific fields when changing stage types

- app/scripts/modules/core/src/artifact/expectedArtifact.service.spec.ts
- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
These commits consolidate all access to `artifact.kind` into the `getKindConfig` function.  This will make it easier to change the logic for inferring kind to no longer depend on `kind` being set.
>  refactor(artifacts): Remove explicit references to kind from artifacts

- app/scripts/modules/core/src/presentation/main.less
detail view will be reconsidered soon as part of larger infrastructure view redesigns. For now, this just lets the dropdowns not get cropped.
> fix(core/presentation): make detail dropdowns not visually crop

- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactEditor.tsx
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactSelector.spec.tsx
- app/scripts/modules/core/src/artifact/react/ExpectedArtifactSelector.tsx
- app/scripts/modules/core/src/artifact/summarizeExpectedArtifact.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/artifact.component.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
Replace all places where we write the kind field of artifacts with writing the customKind field. Delete artifact.kind any time we're updating customKind, as we want customKind alone to control whether to show the custom editing form once the artifact has this field.
> refactor(artifacts): Deprecate kind field

- app/scripts/modules/core/src/task/tasks.controller.js
Sometimes a clone results in an empty variable for 'deploy.server.groups', so we create a bad link. We can look in this other random variable as a fallback to get the region.
If you want to see a lot of lodash, look at this controller.
> fix(core): get region for deployed link from multiple sources

- app/scripts/modules/core/src/pipeline/config/validation/upstreamVersionProvided.validator.ts
Created a new validator to check upstream for stages/triggers that provide version information for bakes (https://github.com/spinnaker/deck/pull/6328), but forgot to pass through the flag that also checks stages/triggers of parent pipeline triggers. Whoops!
> fix(validation): Validator should pass checkParentTriggers through

- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
When testing this fix, my stack was also named 'clone' so I somehow confused this with the correct check on viewState mode. :see_no_evil: 
Will patch into 1.10 and 1.11 as well.
> fix(google): fix autohealing clone logic

- app/scripts/modules/core/src/deploymentStrategy/strategies/rollingredblack/AdditionalFields.tsx
fixes error when selecting rolling red/black without selecting a previous strategy
@ajordens 
```
console.js:35 TypeError: Cannot read property 'onFailure' of undefined
at exports.AdditionalFields.render (AdditionalFields.tsx:54)
at li (react-dom.production.min.js:163)
at si (react-dom.production.min.js:162)
at pi (react-dom.production.min.js:171)
at Ui (react-dom.production.min.js:202)
at qi (react-dom.production.min.js:203)
at Pa (react-dom.production.min.js:218)
at Ea (react-dom.production.min.js:217)
at La (react-dom.production.min.js:232)
at An (react-dom.production.min.js:85)
at HTMLDocument.o (raven.js:377)
```
> fix(core/deploymentStrategy): Fix rolling red/black NPE

- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
`alias` gets removed right after it's added. That's not very useful.
Moving it into `selectStage()` where it _feels_ like it belongs more and hopefully the stage police will let it stay.
> fix(stage): Fixing addAliasToConfig

- app/scripts/modules/core/src/subnet/subnet.read.service.ts
If there is no purpose field, we cannot render these subnets, which means we cannot render the VPC subnet select field, which means we cannot clone a server group in an account/region with any subnets without a purpose.
> fix(aws): filter out subnets with no purpose

- app/scripts/modules/amazon/src/loadBalancer/configure/network/NLBListeners.tsx
We don't actually do anything with the certificates, so maybe we shouldn't load them.
> refactor(aws): remove certificate loading from NLB modal

- app/scripts/modules/google/src/domain/autoHealingPolicy.ts
- app/scripts/modules/google/src/domain/healthCheck.ts
- app/scripts/modules/google/src/healthCheck/healthCheckUtils.spec.ts
- app/scripts/modules/google/src/healthCheck/healthCheckUtils.ts
- app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.html
- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
- app/scripts/modules/google/src/serverGroup/details/autoHealingPolicy/modal/upsertAutoHealingPolicy.modal.controller.ts
Previously, we specified autohealing health checks by name, which is not guaranteed to be a unique key because it is possible to have up to three health checks with the same name (one of each kind: `healthCheck`, `httpHealthCheck`, and `httpsHealthCheck`). This can lead to [this Angular error](https://code.angularjs.org/1.6.4/docs/error/ngRepeat/dupes?p0=healthCheck%20in%20$select.items&p1=string:routing-test-hc&p2=routing-test-hc), which prevents the autohealing health check dropdown from working.
This changes the display logic to key on the health check URL, which can be parsed to infer its name and kind. Additionally, health checks will now be displayed alphabetically, and duplicated names will now be displayed along with their kinds. Corresponding Clouddriver PR: …
> fix(google): differentiate among autohealing health check kinds

- test/functional/tests/core/applications_create_required_config_prevents_creation.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_create_takes_user_to_infra_page.spec.ts.mountebank_fixture.json
The built version of Deck from a fresh `git clone` requires that the `/auth/user` endpoint is stubbed. If it isn't then Deck won't get past the initial loading screen and tests will fail. This endpoint isn't hit when recording network fixtures locally with a development version of Deck.
> fix(tests): network fixtures need to handle deck requesting /auth/user

- app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx
If you resize your window width, you can end up with some rows and parts of your clusters cut off. This prevents that.
> fix(core): clear cluster height cache when resizing window

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx
- app/scripts/modules/core/src/presentation/main.less
Makes the `input-sm` class behave more nicely with react-select
**Current:**
**PR:**
> fix(amazon): better style of react-select for certificates

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
Fixing `isInternal` derived by the subnet purpose.
Also it looks like the checkbox input wasn't wired up to the `Formik`. I wonder how many people actually checked the unchecked checkbox!
> fix(amazon): Fixing load balancers isInternal flag

- test/functional/fixtures/anonymous_auth_response.mountebank_fixture.json
- test/functional/tests/appengine/pipelines_list.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_create_required_config_prevents_creation.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_create_takes_user_to_infra_page.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_list.spec.ts.mountebank_fixture.json
- test/functional/tests/core/home.spec.ts.mountebank_fixture.json
- test/functional/tests/google/clone.spec.ts.mountebank_fixture.json
- test/functional/tools/FixtureService.ts
- test/functional/tools/MountebankService.ts
- wdio.conf.js
Extract /auth/user stubbed response from all tests and put in a shared fixture file. This works around an issue where Deck in "dev mode" won't make this request and so recorded fixtures will be missing this stubbed response.  When the fixtures then get replayed with Deck in "production mode", the requests to /auth/user will 404 (since no response was recorded) and Deck will just hang on its loading screen. The test will fail for seemingly no good reason.
> fix(tests): add anonymous /auth/user stub for all tests

- tslint.json
I hate this rule.
We're likely going to want to change our linting over to `eslint` soon anyway.  TypeScript project is going to embrace eslint as the standard linter.
> - Semantic rules in ESLint
> - - Parity with TSLint
> - - Speed & scalability
> - Editor integration for ESLint
> In a survey we ran in VS Code a few months back, the most frequent theme we heard from users was that the linting experience left much to be desired. Since part of our team is dedicated to editing experiences in JavaScript, our editor team set out to add support for both TSLint and ESLint. However, we noticed that there were a few architectural issues with the way TSLint rules operate that impacted performance. Fixing TSLint to operate more efficiently would require a different API which would break existing …
> chore(tslint): Turn off picky member-ordering rule

- app/scripts/modules/core/src/forms/mapEditor/MapEditor.tsx
I found this import from `'util'` but it should be from `'lodash'`.  This is the only place `util` was being used.
> refactor(core/forms): Save 19kb in deck bundle by not using 'util' package

- app/scripts/modules/core/package.json
5be1a825f85d30359596e4e38bbf41bf145f7833 fix(core): fix filtering on no details in clusters view (#6423)
abe1eea2164a5dbae04f3755273e35a46bdb185f Revert "chore(uiSelect): Remove decorators for uiSelectMultiple which we no longer use, AFAICT"
> chore(core): Bump version to 0.0.317

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/common/AmazonCertificateSelectField.tsx
- app/scripts/modules/core/src/presentation/main.less
Not a huge change, but better - certificate names are usually pretty long.
For ALBs, it's all basically CSS
**Classic Load Balancer**
_current_
_PR_
**Application Load Balancer**
_current_
_PR_
> refactor(aws): move certificate config to second line on elb/alb

- app/scripts/modules/core/src/instance/details/InstanceDetails.tsx
- app/scripts/modules/core/src/instance/details/InstanceDetailsPane.tsx
- app/scripts/modules/core/src/instance/details/index.ts
- app/scripts/modules/core/src/instance/index.ts
- Extracted `InstanceDetailsPane` component
- Export react components from index
- Sort some things
Fixes this issue:
Before:
After:
> fix(core/instance): Show instance id not found message in details panel

- test/functional/README.md
- test/functional/run.js
- test/functional/tools/TestRunner.ts
Deck's nightly functional tests are currently failing.  I added a new feature flag to the test runner that lets a developer serve a single fixture file so they can click around Deck and confirm whether the fixture returns expected data.  At the same time as adding the feature I also updated the signature of the `createImposterFromFixtureFile` method to expect an auth fixture to be passed as well so that responses from the `/auth/user` endpoint can be mocked with data independent of a test fixture.  I forgot to update the new feature flag's usage of the `createImposterFromFixtureFile` method to match the updated function signature.
> fix(tests): give anonymous auth fixture to mountebank

- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
- app/scripts/modules/core/src/presentation/main.less
Making these CSS rules a little more specific than the defaults. Right now, the library build is bundling the CSS in a different order than specified, so these CSS rules are not being applied in custom builds utilizing the libraries.
> fix(core): make react-select CSS resets more specific

- app/scripts/modules/azure/serverGroup/configure/serverGroupCommandBuilder.service.js
Root cause: In **serverGroupCommandBuilder.service**, the `defaultCredentials` and `defaultRegion` are not set to correct value. So that the "credential" property passed to **accountSelectField.directive.js** is a Map instead of a string. And calling `includes` function on the Map cause the error which prevent the account list show
> fix(provider/azure): Fix the account list can't show when "Create Server Group" in cluster page 

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.html
Webhooks that are monitored persist results under the `webhook.monitor` node in the context
unlike the unmonitored webhook (which stores it under `webhook`).
Make sure to look at both nodes to find the HTTP status code as well as the response body
Additionally:
* Pretty format the JSON for payload and response in the UI
* Add ability to copy payload and response to clipboard
> fix(webhooks): Ensure body and status code are shown for webhooks with monitoring

- app/scripts/modules/core/src/application/application.model.ts
If data sources are not active, they should be considered "fetched" for the purposes of calculating the `lastRefresh` date on the application
> fix(core): consider NOT_INITIALIZED as fetched when setting app status

- app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
It's kind of nuts that, when you are editing a pipeline config, you're editing the actual data source data and not a copy.
This manifests when changing a pipeline config, navigating away (confirming you're leaving unsaved changes), then navigating back. If, for example, you removed a stage, that stage can still be missing when you navigate back if the pipeline configs have not refreshed yet.
> fix(core): do not edit live copy of pipeline configs

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
This fixes the bug where clicking the stage of another execution does not open that execution's details and display the details of the clicked stage.
Based on the following usage, it seems like `viewState.executionId` is meant to track against the global router state (which execution, if any, is expanded):
https://github.com/spinnaker/deck/blob/d09a9103b3ae434a25f88b4ff78cf8bb02e987f9/app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx#L89
If the `viewState` is initialized to the component's execution ID and not `$stateParams.executionId`, the following condition fails:
https://github.com/spinnaker/deck/blob/d09a9103b3ae434a25f88b4ff78cf8bb02e987f9/app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx#L90-L95
and prevents `showingDetails` from being …
> fix(executions): Fixed stage does not open when clicked

- app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
instead of from `core` so downstream projects don't need a `core` alias in tsconfig
This fixes a problem in our custom build where `IWizardModalProps` extends `IModalComponentProps` but `IModalComponentProps` could not be found.  This was because in the downstream project, TypeScript tries to resolve the `extends IModalComponentProps` clause through the `import { IModalComponentProps from 'core/presentation'`.  However, the downstream project's tsconfig.json isn't configured with a `"paths": { "core": "......" }`.  Typescript can't find the interface and gives up.  There is no error because we tell typescript not to check libraries via `skipLibCheck: true`
> fix(core/modal): Import IModalComponentProps relatively 

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
cd32f9d70513df5e6286c72be6904a20ca98ec3a fix(stages): Fixed stage/details out-of-sync due to state bug (#6480)
426441852c31c3fd56123dd90d2700bc4fee8c5c feat(artifacts): Human readable expected artifact display names (#6344)
20cf9b7686511d16b781099a9602b7c21a5e85ce fix(core/modal): Import IModalComponentProps relatively instead of from 'core' so downstream projects don't need a 'core' alias in tsconfig
b92c8aaee203cacbab25312a0b345cfaa5c90a2e Merge branch 'master' into 3798-route-mapping
04bc98b74688c102b7ab888b42a80e509b1048b8 feat(cf): Add Map/Unmap SGs and LBs
01dafc7ed9e498d3891f40e06145667dbc9b4033 feat(amazon/loadBalancer): Rudimentary support for redirect actions (#6470)
0451046c241b450ae4b05df0b67b61758c16acce chore(package): Add .npmignore to all packages …
> Bump package core to 0.0.324 and amazon to 0.0.163 and titus to 0.0.70

- app/scripts/modules/core/src/application/config/applicationConfig.controller.js
- app/scripts/modules/core/src/application/config/applicationConfig.view.html
- app/scripts/modules/core/src/application/config/customBanner/CustomBannerConfig.spec.tsx
- app/scripts/modules/core/src/application/config/customBanner/CustomBannerConfig.tsx
- app/scripts/modules/core/src/application/config/customBanner/customBannerColors.ts
- app/scripts/modules/core/src/application/config/customBanner/customBannerConfig.component.ts
- app/scripts/modules/core/src/application/config/customBanner/customBannerConfig.less
- app/scripts/modules/core/src/bootstrap/bootstrap.module.ts
- app/scripts/modules/core/src/bootstrap/customBanner.html
- app/scripts/modules/core/src/bootstrap/spinnaker.component.ts
- app/scripts/modules/core/src/core.module.ts
- app/scripts/modules/core/src/header/customBanner/CustomBanner.less
- app/scripts/modules/core/src/header/customBanner/CustomBanner.spec.tsx
- app/scripts/modules/core/src/header/customBanner/CustomBanner.tsx
- app/scripts/modules/core/src/header/customBanner/customBanner.component.ts
Let me know if you all have any thoughts on making the custom banners more or less configurable -- the specific use case this was requested for was putting up production freeze or maintenance alerts on specific applications.
> feat(core): add application-specific custom banners

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupZones.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx
Formik does not seem to recognize a nested field value mutation as a mutation, so it won't set the `dirty` flag to true, which prevents form submission if only these values are changed.
There might be another one or two lurking in that modal but these are the obvious ones.
> fix(amazon): do not mutate nested objects on clone server group command

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/utils/timeFormatters.spec.ts
- app/scripts/modules/core/src/utils/timeFormatters.ts
[This](https://github.com/spinnaker/deck/pull/6362) PR added the `displayTimestampsInUserLocalTime` feature flag to `SETTINGS.feature` in `settings.js` and `halconfig/settings.js` but tried to read it off of `SETTINGS` directly. This change makes sure that it is read off of `SETTINGS.feature` everywhere.
> fix(core): read displayTimestampsInUserLocalTime off SETTINGS.feature

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
bc9a14ba64b0f5812f17d09114ddb22aa3f26633 refactor(core): modularize execution status display on executions (#6489)
c1bcada8b78f889b608a9b5a86a3e6d7ffa9dd36 refactor(core/insight): refactor modules to avoid circular dependency
0ea42c2483c6e21b29a17a6ba368c32789d4f99e chore(visualizer): Switch from deprecated System.import() to dynamic import()
5c49dd2ab3c4226295a7e8041c25dabdbeee6a2c chore(typescript): Switch module from 'commonjs' to 'esnext' to emit raw dynamic 'import()'
cf861ba17b06f405e9250d8db4b7b157ca5dcf95 fix(core): read displayTimestampsInUserLocalTime off SETTINGS.feature
c6a3528edf48b9f05a4532be7f109ed5e24d5e0a feat(core): add application-specific custom banners
bc9a14ba64b0f5812f17d09114ddb22aa3f26633 refactor(core): modularize execution status display on executions (#6489) …
> Bump package core to 0.0.325 and docker to 0.0.32 and amazon to 0.0.165 and titus to 0.0.71

- test/functional/run.js
The functional test runner code is executed by node.js. Since `import` statements aren't yet supported in node we need to tell the typescript compiler to convert them to `require()` calls instead.
Prior to this change the functional tests fail with the following error:
```javascript
(function (exports, require, module, __filename, __dirname) { import * as process from 'process';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Module.m._compile (/Users/sbws/dev/spinnaker/deck/node_modules/ts-node/src/index.ts:439:23)
at Module._extensions..js (module.js:664:10)
at Object.require.extensions.(anonymous function) [as .ts] (/Users/sbws/dev/spinnaker/deck/node_modules/ts-node/src/index.ts …
```
> fix(tests): functional test runner needs imports converted to requires

- app/scripts/modules/core/src/widgets/accountRegionClusterSelector.component.html
- app/scripts/modules/core/src/widgets/accountRegionClusterSelector.component.js
The upcoming CloudFormation stage needs to select the account and region
where the CloudFormation template is deployed, but not the clusters.
This patch makes the cluster selection optional, defaulting to true
(show the cluster selection) which is the current behaviour.
> refactor(amazon): make cluster selection optional

- app/scripts/modules/core/src/presentation/forms/forms.less
Used CSS variables for colors in forms.
New set of styles for forms included hexcode and rgb color units. In order to ensure consistency, I moved them to the closest match in our styleguide.
> fix(style): Fix all lint errors for colors in forms

- package.json
- yarn.lock
Bootstrap 3.3.7 was found to have three XSS vulnerabilities. 
Bootstrap released a patch 3.4.0 which fixes these issues and does not include any new features or updates to existing ones which will break our styles. I ran a quick test on all our pages and found them to look exactly the same.
Reference:  https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/ 
If you are still worried: https://github.com/twbs/bootstrap/pull/27288
> fix(style): Upgrade bootstrap to avoid XSS vulnerabilities

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
a35088ab28cc3b25c9e6731f6fb70bf7d0e14ef0 chore(webpack): Switch to TerserPlugin.  Split bundles into ~5mb chunks
fe642b77e3d3acf9b19cc60a2b9f0b0e7ef1114b fix(style): Fix all lint errors for colors in forms (#6500)
8cf90fcc4d5d23a55372b93a5a8bc2db6bd8b838 refactor(amazon): make cluster selection optional (#6502)
a35088ab28cc3b25c9e6731f6fb70bf7d0e14ef0 chore(webpack): Switch to TerserPlugin.  Split bundles into ~5mb chunks
a35088ab28cc3b25c9e6731f6fb70bf7d0e14ef0 chore(webpack): Switch to TerserPlugin.  Split bundles into ~5mb chunks
226c2d224fd94d7408a3bde6b04fe659b2b25ef4 fix(titus): do not call setState on wizard validation (#6506)
a35088ab28cc3b25c9e6731f6fb70bf7d0e14ef0 chore(webpack): Switch to TerserPlugin.  Split bundles into ~5mb chunks
> Bump package core to 0.0.328 and docker to 0.0.33 and amazon to 0.0.167 and titus to 0.0.73

- app/scripts/modules/core/src/application/service/ApplicationReader.ts
- app/scripts/modules/core/src/header/customBanner/CustomBanner.tsx
Calling `.getApplication` spawns an entire application object, complete with refreshing data sources and all kinds of other things that may not be expected.
@maggieneterval I added this method for something completely unrelated (on our internal build) and saw this was a good place to use it in OSS. It prevents a double loading of server groups and other always-active data sources when switching applications.
> feat(core): add getApplicationAttributes method

- app/scripts/modules/core/src/header/customBanner/CustomBanner.spec.tsx
Travis builds are failing because this test has been failing since [this PR](https://github.com/spinnaker/deck/pull/6512/files) updated the banner component to use `getApplicationAttributes` rather than `getApplication`
> chore(core): update banner spec

- app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
- app/scripts/modules/core/src/account/accountTag.less
Regions in bake stage are sorted. Lint warnings fixed. 
Regions in bake stage configuration while setting up a pipeline is not sorted. Find Image stage however has it sorted. Sorted the list of regions. 
There was an additional lint warning for a color which is also fixed.
> fix(amazon/core): Sorting order of regions in bake stage + lint fix

- app/scripts/modules/core/src/deploymentStrategy/strategies/redblack/redblack.strategy.ts
maxRemainingAsgs use default placeholder value of 2 even if it is manually removed.
Scenario: A user configures a deploy stage with redblack and creates a cluster. This has a default maxRemainingAsg value of 2 by default. Now the user removes the maxRemainingAsgs from the pipeline JSON and saves the config. When the user gets to the cluster configuration in the UI, the maxRemainingAsg is set to 2 even though the value has been removed. This is incorrect because now the number of remaining ASGs is infinite and not 2 because it is not set. 
In this solution, I read if the strategy has already been set to determine if its a first time cluster config or existing cluster config. Based on that, it chooses whether to show the default values or not. This solution is easier than passing down if …
> fix(core): Max remaining ASG should honor value being removed

- app/scripts/modules/core/src/config/settings.ts
- halconfig/settings.js
- settings.js
https://github.com/spinnaker/spinnaker/issues/3894
This renames the feature flag to make it clear it only affects the UI. It is tied to the renamed flag in halyard, https://github.com/spinnaker/halyard/pull/1213/files
> feat(core): rename feature flag for managed pipeline templates v2 ui

- app/scripts/modules/core/src/presentation/forms/validation/validation.spec.ts
- app/scripts/modules/core/src/presentation/forms/validation/validation.ts
- app/scripts/modules/core/src/presentation/forms/validation/validators.ts
First class support for `required` turns a bunch of `.validate([isRequired()])` into `.required()` which is more readable and natural.
First class support for `optional`:
```js
b.field('foo', 'Foo').optional([
minValue(1003),
maxValue(1005)
])
```
is probably be more ergonomic than any other way we try to do it through composition, like
```js
b.field('foo', 'Foo').validate([
optional(minValue(1003)),
optional(maxValue(1005))
])
```
or
```js
b.field('foo', 'Foo').validate([
minValue(1003),
maxValue(1005)
].map(optional))
```
> Moved from validate to required/optional

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CloudfoundryDeployServiceStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateServiceInstanceDirectInput.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateUserProvidedInput.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/interfaces.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyAsg/CloudfoundryDestroyAsgStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyService/CloudfoundryDestroyServiceStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyService/cloudfoundryDestroyServiceStage.module.ts
renaming `serviceName` to `serviceInstanceName` so it is clear that `serviceInstanceName` represents the new service instance and not the name of the Service
> chore(cf): rename serviceName to serviceInstanceName

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraphNode.tsx
- app/scripts/modules/core/src/pipeline/config/stages/group/GroupExecutionPopover.tsx
- app/scripts/modules/core/src/presentation/HoverablePopover.tsx
The <g> tag is necessary within the execution graph (it's used by grouped stages, which happens via pipeline templates), but React barks about it outside <svg> tags.
cc @jkschneider @jrsquared @christopherthielen
> fix(core): only use <g> for popovers in within SVGs

- app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.ts
Most people add new traffic guards with the intention of them guarding traffic.
> fix(core): enable new traffic guards by default

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx
- app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/resize/CloudFoundryResizeServerGroupModal.tsx
- app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts
- app/scripts/modules/core/src/widgets/index.ts
- app/scripts/modules/core/src/widgets/spelText/SpelNumberInput.tsx
Support SPEL input and display for simple capacity in cluster configuration.
Some of the netflix users are setting an expression for capacity. Today, if someone sets the capacity as an expression and tried to edit something else in the cluster configuration, we ask them to enter a number for the capacity and override their expression. This change fixes that by supporting toggle between spel and number input.
> fix(amazon/cloudfoundry/core): SPEL support for capacity in cluster configuration

- cloudbuild-tagged.yaml
- cloudbuild.yaml
The 'java' docker repo has been deprecated and not maintained since the end of 2016 in favor of the 'openjdk' repo.
The old ones were using openjdk as well, so that's not a change, just the repo.  This also makes the base debian image more modern (stretch instead of jesse).
The particular issue this fixes is that deck wasn't building on debian stretch after node was upgraded.
> chore(build): Use newer base image for deck build

- app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.html
Currently it sets subnet as null as default value in drop down list after select same loadbalancer.
So update the logic to not change subnet after select same loadbalancer.
> fix(provider/azure): subnet is null after select same loadbalancer

- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
27d8a12c6e133ba0a25d874535f3c77da431113e chore(eslint): Fix lint errors
a8c174925f64045f70c11b2bfc11fe1fdd558660 chore(package): Just Update Prettier™
9eccc0f19d3f5aa5a55354d0c9344bb79a9c77bc refactor(artifacts): Generalize artifact delegate for reuse (#6495)
6c54b61d443907c396055d0f8e1bd2df9ab58405 fix(kubernetes): do not override `location` and `replicas` in new Scale Manifest stage
a35088ab28cc3b25c9e6731f6fb70bf7d0e14ef0 chore(webpack): Switch to TerserPlugin.  Split bundles into ~5mb chunks
54157f2e6787e6a12fa0e67ccbc138a903f72a40 fix(kubernetes/serverGroup): Remove module.exports assignment in typescript file
5c49dd2ab3c4226295a7e8041c25dabdbeee6a2c chore(typescript): Switch module from 'commonjs' to 'esnext' to emit raw dynamic 'import()'
0451046c241b450ae4b05df0b67b61758c16acce …
> Bump package kubernetes to 0.0.21 and google to 0.0.5

- halconfig/settings.js
- settings.js
If an application does not include a `cloudProviders` string in its JSON then certain UI features will fall back to the set of `defaultProviders` defined in the settings object when determining whether that application includes specific providers. If `"appengine"` is missing from the list of default providers then older appengine applications that don't include the `cloudProviders` field can end up showing AWS modals by mistake.
> fix(appengine): older apps that dont have cloudProviders field dont select correct serverGroup modal

- app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/triggers.html
https://github.com/spinnaker/spinnaker/issues/3970
The feature flag check now occurs in the `triggers.directive` giving each `<page-section>` a chance to init and register its page in the correct order with the `PageNavigationState`. `PageNavigationState` can then be used to render navigation items as long as they are `visible`.
This includes `prettier` changes that I can split into a separate commit if helpful.
> fix(core): Match order of pipeline config nav items to page sections

- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.html
- app/scripts/modules/core/src/pipeline/config/stages/stage.html
- app/scripts/modules/core/src/presentation/navigation/pageNavigator.component.ts
The stage config view could use more love than this, but, for now, let's remove the navigation bits on the left side. Most people don't notice they are even there, and I suspect nobody finds them actually useful?
With the side nav removed, we end up with a lot more space for clusters in the deploy stage, and expressions on conditional stages:
> refactor(core): remove navigation from stage config details

- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
a user requested that we display the `ExecutionStatus` parameter value as an unescaped JSON if the input was an unescaped JSON. Having an escaped JSON is causing issues with another tool from the user that parses parameters from the `ExecutionStatus`
spinnaker/spinnaker#3976
> feat(core): display unescaped JSON if pipeline parameter input was JSON

- app/scripts/modules/core/src/core.module.ts
in the module `source-sans-pro@2.0.10` `packageJson.main` is specified to be `source-sans-pro.css`, however this is dropped in following versions. Here's a screenshot of available versions:
To address this, let's directly reference the file which should help prevent build issues when upgrading and also with importing `@spinnaker/core` as a module in deck extensions since the current package.json specifies `"source-sans-pro": "^2.0.10",` which allows using the `2.45.0 (latest)` version.
> fix(core/css): be explicit on which file we're importing

- Dockerfile
I was having some trouble getting deck to build inside a container with 4gb memory (side note: it takes 4gb of memory to build deck 😱).  
`gradle` launches `webpack` and then two VMs are running at the same time (the Java VM for gradle and v8 for webpack).  This used enough extra memory that the webpack build consistently failed.  
AFACT, gradle isn't necessary to build the deck image.  It was used to install node and yarn, then kick off the webpack build.  However, the `node:10` base image comes with node and npm preinstalled.   I believe installing `yarn` and invoking the webpack build via `yarn build` should produce the same results.
> chore(Dockerfile): Use node:10 base image, do not use gradle to build

- app/scripts/modules/core/src/account/AccountSelectInput.tsx
- app/scripts/modules/core/src/account/accountSelectField.component.ts
The find image stage in AWS is blowing up with a digest-in-progress error when the stage is first selected. This is happening because...React->Angular->React->Angular, I guess, and the easiest solution is to call the change handler in a `$timeout` block instead of an `$apply`.
Separate PR coming to address some other issues I found along the way.
> fix(core): use $timeout to handle change event in accountSelectField

- app/scripts/modules/amazon/src/pipeline/stages/findAmi/awsFindAmiStage.js
- app/scripts/modules/amazon/src/securityGroup/configure/ingressRuleGroupSelector.component.ts
- app/scripts/modules/core/src/application/application.model.ts
When creating a Find Image stage, we throw away the account default because we don't set the accounts in the view on first render (they're set via the `listAccounts` callback). Easy fix is to just hide the picker until the accounts are there (which is the next cycle, basically immediately).
Also fixing a broken subscription thing that causes problems editing ingress rules for AWS.
> fix(*): fix account selection in findAmi, AWS ingress rule picker

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
b18a815fbc215290070e07a1152d4d916d325d6c fix(aws): fix security group rule updates (#6564)
1b424135d2d3515e052f011110223832601e6b1b fix(core): use $timeout to handle change event in accountSelectField (#6563)
8199164e647979bcd0a036657dc93df211103ffd fix(core/css): be explicit on which file we're importing (#6554)
c4287c657b0e037ccca71d8139c3e3c08ab8a705 feat(core): display unescaped JSON if pipeline parameter input was JSON (#6556)
6fd4bf3ea3b5d2805cf8da6143f68c6057116b53 fix(core): make one request per pipeline/strategy re-indexing event (#6519)
592073fa8724525eaf50419c1ae28f4fd3fb0dd3 fix(eslint): Fix eslint warnings for @typescript-eslint/camelcase
c17c742a15a47b49f94b7fb24fcff717bcc0a088 fix(eslint): Fix eslint warnings for @typescript-eslint/no-empty …
> Bump package core to 0.0.332 and amazon to 0.0.172

- app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
The usual periodic upgrade to cheaper, faster stuff. No machine stats changed.
I also added `r4` as vpc-only and HVM-only, seems it was missed.
> chore(amazon/instance): Promote the recommended high-memory family to r5

- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
The code as-is breaks whenever a parameter looks JSON-y, e.g. `"[1, 2]"` or `"{key: 3}"`, and the hoops we're jumping through to unescape in the case a user has sent escaped JSON in as a parameter are not worth working around.
> fix(core): do not try to parse/unescape execution status parameters

- app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.spec.tsx
- app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx
We don't really need to do all the measuring of the text to compute the width/position of the clipboard tooltip.
Right now, if you scroll down the executions view a bit, then click a Copy to Clipboard button, the screen goes blank and you have to refresh it, which is not the best experience.
> fix(core): do not blow away the screen when copying to clipboard

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
a3c08ee598345a143c7af4cce54ecde146878769 fix(core): do not blow away the screen when copying to clipboard (#6571)
3664ce2a4b571fcda570d454f1c124191f98aaec fix(core/amazon): Loadbalancer tags should have spinner to avoid panic (#6562)
d11da07addfe99eb07f7ddaf88019dc8a3abc34e fix(core): do not try to parse/unescape execution status parameters (#6570)
8ee56878f1acbb6752dc75f5812e4d8fab5fd9f6 chore(eslint): disable eslint namespace rule for Gremlin component
3664ce2a4b571fcda570d454f1c124191f98aaec fix(core/amazon): Loadbalancer tags should have spinner to avoid panic (#6562)
ce4a4ba9f4874d4833eb7381bb01f0b43be749e5 chore(amazon/instance): Promote the recommended high-memory family to r5 (#6566)
> Bump package core to 0.0.333 and amazon to 0.0.173

- app/scripts/modules/core/package.json
(no actual changes, working through an odd build issue)
> chore(core): Bump version to 0.0.334

- app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx
`displayText` is optional and defaults to `false`, let's make the interface reflect reality.
> fix(core/clipboard): correctly type CopyToClipboard's displayText prop

- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancerSourceData.ts
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
Minor inconsistency between the commands Clouddriver wants and the models AWS returns.
@jrsquared if people are not scripting against this part of the API, it would be good to convert Clouddriver to just use `redirectConfig` instead of `redirectActionConfig` and then undo most of these changes, unless there's a reason to have both, in which case, I am so proud of my code.
> fix(aws): set redirectActionConfig on ALB rules

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
4d816b54a0dade16becd5c0fa8aa0a4abd9782ee fix(core/clipboard): correctly type CopyToClipboard's displayText prop (#6580)
ad7c582006a70648b20a1c7b6bb466fa62fb8b6c fix(aws): set redirectActionConfig on ALB rules (#6579)
> Bump package core to 0.0.336 and amazon to 0.0.174

- app/scripts/modules/kubernetes/src/serverGroup/details/details.html
- app/scripts/modules/kubernetes/src/serverGroup/details/resize/resize.html
`serverGroup.autoscaler` comes as `undefined` in angular scope when there's no autoscaler attached to a server group, thus wrong modals were shown to users.
@christopherthielen @maggieneterval - feel free to test it with Kubernetes V2. I've tested it with Kubernetes V1 and now everyone is happy that the Resize feature can be used again.
> fix(kubernetes): properly detect if autoscaler is attached to server groups

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
d8538271bd69a429902e5e2aa33cfa01ca435cb0 fix(core): Child pipeline should route back correctly (#6586)
bc9a30bbe31b4473a758bda96460ceab0416d1e5 fix(core): allow selecting accounts via simple select field in AccountSelectInput (#6592)
4b91b36c6dc52af529efd89461ce0a44d6432ef5 refactor(core): move Ace Editor CSS to core module (#6588)
cc52bee0b9956693f948806322658f225efa5546 chore(angularjs): Remove all 'ngInject'; in favor of explicit DI annotation
b6bab1e16bb46697fec347cd30934f00fb2e9807 chore(prettier): Just Use Prettier™
f3fd790e20a4c3056edcb2c41282517e1cf35004 chore(angularjs): Explicitly annotate all AngularJS injection points
78d0b689efd4de00ab203d55df632dd5ece89133 fix(securityGroups): User `securityGroupName` for upsertSecurityGroupTask (#6569) …
> Bump package core to 0.0.337 and docker to 0.0.34 and amazon to 0.0.175 and titus to 0.0.75

- app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
Per feedback review within gate, change the Gate gremlin endpoint prefix from "gremlin" to "integrations/gremlin"
See https://github.com/spinnaker/gate/pull/725#discussion_r258652639
> feat(gremlin): update to Gremlin Gate endpoint prefix

- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
- app/scripts/modules/amazon/src/serverGroup/details/rollback/rollbackServerGroup.html
- app/scripts/modules/dcos/loadBalancer/configure/wizard/ports.html
- app/scripts/modules/dcos/loadBalancer/configure/wizard/resources.html
- app/scripts/modules/dcos/loadBalancer/details/details.html
- app/scripts/modules/ecs/src/instance/details/instanceDetails.html
- app/scripts/modules/ecs/src/serverGroup/events/events.html
- app/scripts/modules/google/src/loadBalancer/configure/common/commonCreateLoadBalancer.html
- app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendService.component.html
- app/scripts/modules/google/src/loadBalancer/configure/http/backendService/backendServices.html
- app/scripts/modules/google/src/loadBalancer/configure/http/healthCheck/healthChecks.html
- app/scripts/modules/kubernetes/src/loadBalancer/configure/wizard/advancedSettings.html
- app/scripts/modules/kubernetes/src/loadBalancer/configure/wizard/ports.html
- app/scripts/modules/kubernetes/src/serverGroup/configure/wizard/replicas.html
- app/scripts/modules/openstack/src/loadBalancer/configure/wizard/healthCheck.html
- app/scripts/modules/openstack/src/loadBalancer/configure/wizard/listeners.html
- app/scripts/modules/openstack/src/serverGroup/configure/wizard/access/accessSettings.html
- app/scripts/modules/openstack/src/serverGroup/details/serverGroupDetails.html
- app/scripts/modules/titus/src/instance/details/instanceDetails.html
- app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.html
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
Found and fixed some more invalid HTML
see #6597
> fix(html): Fix various invalid HTML

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
7d5fc346bca54c5d53f9eb46d823cd993c102058 chore(prettier): Just Use Prettier™ (#6600)
64fb4892ee3e7114eccb8f6acc9d84ae652f1af3 fix(html): Fix various invalid HTML (#6597)
39f6858797af81265a6de1aa0735c33b9c35bd30 fix(core/diffs): Fix misnamed tempate field
5cf6c79da63404bb7238291d38bb7f5cfd10c26b chore(prettier): Just Use Prettier™
3ffa4fb7498df815014d61071e8588f0b34bf8b9 chore(angularjs): Do not use .component('foo', new Foo())
14bf52b2da88555cbab3bca7ae33062cf32d7625 feat(gremlin): Per feedback review within gate, change the Gate gremlin endpoint prefix from "gremlin" to "integrations/gremlin" (#6591)
7d5fc346bca54c5d53f9eb46d823cd993c102058 chore(prettier): Just Use Prettier™ (#6600)
64fb4892ee3e7114eccb8f6acc9d84ae652f1af3 fix(html): Fix various invalid HTML (#6597) …
> Bump package core to 0.0.338 and docker to 0.0.35 and amazon to 0.0.176 and titus to 0.0.76

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
- app/scripts/modules/core/src/pipeline/filter/executionFilters.less
When re-ordering pipelines in the filter sidebar, it can get kinda wonky if you accidentally make the browser think you're selecting text. If you manage to click + drag just right, sometimes it even thinks you're trying to drag a multi-line text selection for copy-pasting.
This switches off text selection when entering re-ordering mode for strategies and normal pipelines. Outside re-ordering mode you can still select the pipeline names to copy-paste, if that's something you're into.
> fix(core/executions): Disable text selection when re-ordering pipelines

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
**Core:**
3e75815 refactor(core): migrate momentjs functionality to luxon + date-fns (#6604)
754c540 Merge branch 'master' into lb-is-loading
70fb404 fix(core/executions): Disable text selection when re-ordering pipelines (#6603)
a35b4cb Merge branch 'master' into lb-is-loading
1d320d6 Merge branch 'master' into lb-is-loading
c026514 Merge branch 'master' into lb-is-loading
cf528dc fix(core): loading spinner for LBs not dismissed
**Amazon:**
510557f fix(amazon/serverGroup): Do not apply default AZs unless the user wants to usePreferredZones (#6609)
**Titus:**
5e77299 fix(titus): Help users with iam profile setting (#6552)
> Bump package core to 0.0.339 and amazon to 0.0.177 and titus to 0.0.77

- app/scripts/modules/core/src/utils/timeFormatters.ts
It seems these were the last vestige of our internal-only Fast Properties feature living in `core`. This just yanks them out (they've been moved to our internal codebase).
> chore(core): yank out fastProperties formatters

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/serverGroup/AvailabilityZoneSelector.tsx
- app/scripts/modules/amazon/src/subnet/SubnetSelectInput.tsx
- When a new ALB was created, AZ autobalance mode was not saving the default AZs into the form state.
- When no default subnet is configured, the first subnet was selected in the UI, but not in the form state. 
- the isInternal checkbox was read-only
> fix(amazon/loadBalancer): Fix AZ autobalance, subnet AZ default value, and isInternal checkbox

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
69a2d56c5d026679530b3cb59d51ae0ca5edd606 fix(artifacts): lookup of artifact id with incorrect string (#6622)
10153213b2bdabbf5fb166863c6bb28eb5b398a6 fix(projects): config state was stale after update (#6464)
c0f6b24ec35e5e9eb438791a2eaf0b540af2830e chore(angularjs): Move $inject annotation above hoisted functions (#6621)
a6a6b7394a4d09ee646a452a804d23bdf7134616 fix(gremlin): Check for fetched data from API (#6553)
d828a53e55919c16a8cea82af404c05bad081066 chore(angularjs): Explicitly annotate directive controllers
ea0808f57121e108072a664bed445b186820d03e fix(amazon/loadBalancer): Fix AZ autobalance, subnet AZ default value, and isInternal checkbox (#6623)
> Bump package core to 0.0.341 and amazon to 0.0.178

- app/scripts/modules/kubernetes/src/v2/manifest/scale/scaleSettingsForm.component.ts
Currently the deck UI forces numeric input for replicas in the `Scale (Manifest)` stage. This prohibits configuring the stage to accept SpEL. Changed the input type to text, built and tested in our production cluster.
> fix(kubernetes): allow text input for replicas in `Scale (Manifest)` stage

- app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.html
- app/scripts/modules/core/src/application/config/footer/configSectionFooter.component.ts
- app/scripts/modules/core/src/chaosMonkey/chaosMonkeyConfig.component.html
If a user types an invalid value into a numeric field, the field will be marked invalid (and have a red outline) but can still be saved. This just prevents that.
> fix(chaos): do not let user save invalid chaos monkey config

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/DeleteManifestStageConfig.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.html
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestStage.ts
Follow-up to https://github.com/spinnaker/deck/pull/6628
Closes https://github.com/spinnaker/spinnaker/issues/3829
- Adds UI support for dynamic target selection in Patch Manifest stage
- In separate commit, fixes defaults for Delete Manifest stage
Corresponding Orca PR: https://github.com/spinnaker/orca/pull/2688
>  feat(kubernetes): add dynamic target selection to patch manifest stage

- app/scripts/modules/kubernetes/src/v2/manifest/selector/ManifestSelector.tsx
Found a random issue with the Manifest Selector where the manifestName could end up being set to `" "` in Label mode, which breaks the Delete Manifest validation because `" "` is not null or empty string.
> fix(kubernetes): only set manifestName in static mode manifest selector

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/presentation/main.less
We use the Execution component in our internal build to roll out property changes. When those executions are cancelled, we have custom code in Orca that will revert any changes that the execution has made so far.
This rollback behavior is not obvious to users - it's inconsistent with how pipelines in Spinnaker work on other changes. We don't want to _not_ perform the rollback, but we do want to let users know that it will happen if they cancel the execution, so we want to customize the tooltip on the cancel button, and add some body text to the confirmation modal when they choose to cancel.
> feature(core): allow custom tooltip, modal body on Cancel Execution

- app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
Background:
Currently orca doesn't process job according by new strategy after choosed new strategy like highlander for azure. The root cause is that deck doesn't memory the new strategy and pass to orca.
Fix:
So update the deck code to memory new strategy and then the memoried new strategy would be passed to orca.
> fix(provider/azure): Enable strategy for azure

- app/scripts/modules/core/src/domain/IExecution.ts
- app/scripts/modules/core/src/domain/IPipeline.ts
- app/scripts/modules/core/src/pipeline/config/CreatePipeline.tsx
- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/details/singleExecutionDetails.less
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/index.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
https://github.com/spinnaker/spinnaker/issues/4056
Removes configure as an option for pipelines from mptv2 templates:
Removes mptv2 pipelines from the Configure menu in the "Pipelines" view:
Removes the configure button from the single execution view if a execution has a mptv2 pipeline config:
Redirects to "Pipelines" view if user navigates to mptv2 pipeline config directly.
> fix(core): Remove configure button and setup redirect for mptv2 pipeline

- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.html
- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
See https://github.com/spinnaker/spinnaker/issues/3879 for full context on this patch but here's a quick summary:
Since the Titus Run Job stage is written in React its provider config
includes a `component` field. `stage.module.js` responds to a component
field by rendering it straight into the DOM.
When multiple providers are available for a given stage the
`baseProviderStage`, an angular component, is meant to be shown to
the user for them to pick which provider to use.
Unfortunately `stage.module.js`'s rendering of a React component short
circuits the rendering of the `baseProviderStage`. The user never gets presented
with the option to choose a different provider.
Resolving this first problem requires nulling out the `component` field
when baseProviderStage needs to be shown.
The …
> fix(core): titus run jobs override all other providers

- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.html
- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
Cherry-pick of https://github.com/spinnaker/deck/pull/6647
Since the Titus Run Job stage is written in React its provider config
includes a component field. stage.module.js responds to a component
field by rendering it into the DOM.
When multiple providers are available for a given stage (for example
with the Run Job stage) the baseProviderStage, an angular component, is
meant to be shown to the user for them to pick one.
Unfortunately the rendering of a React component from a provider config
short circuits the rendering of the baseProviderStage.
Resolving this first problem requires nulling out the `component` field
when baseProviderStage needs to be shown.
The follow-on issue is that baseProviderStage did not previously know
how to render react components. This meant that the user could …
> fix(core): titus run jobs override all other providers (#6647)

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/HttpArtifactEditor.tsx
Clouddriver uses the reference field to download the artifact
> fix(artifacts): save HTTP URL as artifact reference

- app/scripts/modules/core/src/cancelModal/CancelModal.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Markdown makes it safer and easier to format body in the modal (which currently html escapes)
Fixes this:
> fix(core/pipeline): make cancelmodal take markdown for body

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
- app/scripts/modules/core/src/pipeline/status/Artifact.spec.tsx
- app/scripts/modules/core/src/pipeline/status/Artifact.tsx
- app/scripts/modules/core/src/pipeline/status/ArtifactList.spec.tsx
- app/scripts/modules/core/src/pipeline/status/ArtifactList.tsx
- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
- app/scripts/modules/core/src/pipeline/status/ResolvedArtifactList.spec.tsx
- app/scripts/modules/core/src/pipeline/status/ResolvedArtifactList.tsx
- app/scripts/modules/core/src/pipeline/status/artifact.less
- app/scripts/modules/core/src/pipeline/status/artifactList.component.ts
- app/scripts/modules/core/src/pipeline/status/artifactList.less
Closes spinnaker/spinnaker#3748
* refactor(artifacts): Rename `ArtifactList` to `ResolvedArtifactList`
This component is specific to a list of resolved artifacts, and requires the pipeline's expected artifacts as input. Rename it to free up ArtifactList for a more generic list of artifacts.
* refactor(artifacts): Create a react component for an artifact list
The logic for rendering a single artifact is currently embedded in `ResolveArtifactList`; pull this into its own component so it can be reused and create a new `ArtifactList` component that generically displays a list of artifacts, without expected artifact logic.
* feat(artifacts): Re-use artifacts when re-running a pipeline
The manual execution widget does not currently support injecting artifacts into a pipeline. This means that …
> feat(artifacts): Re-use artifacts when re-running a pipeline

- app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsExecutionDetails.controller.js
- app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsExecutionDetails.html
The Jenkins stage is now able to produce artifacts, so show them in the execution details.
Back-end changes are in spinnaker/orca#2723 though this can still be merged first; it will just show an empty artifact tab in the Jenkins execution history until people can actually use artifacts.
> feat(jenkins): Add artifact status tab to Jenkins execution details

- app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.html
- app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.js
Parameters not accepted by a jenkins job are highlighted in a jenkins stage.
The stage config can end up having parameters that are no longer needed/accepted by the jenkins job. This is similar to https://github.com/spinnaker/deck/pull/6668.
> feat(core): Warning message about invalid job params

- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
This fixes the ECS server group modal.  Currently it won't load because the $inject list and the constructor list don't match up, leading to the wrong types being injected.
> fix(ecs): Remove unused cacheInitializer injection

- app/scripts/modules/amazon/package.json
955eac52f91b5bbcac41a0f790f0f94a9dc4cf11 fix(aws): do not aggressively and endlessly fetch vpcs (#6682)
> chore(amazon): Bump version to 0.0.180

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- halconfig/settings.js
- settings.js
* refactor(core): Remove triggerViaEcho feature flag
This flag was introduced in 1.11 and was enabled by default in 1.12; there have been no reports of any issues, so remove the flag.
* refactor(core): Remove unused functions
Also convert the test of waitUntilNewTriggeredPipelineAppears into a test of waitUntilPipelineAppearsForEventId, as it looks like I didn't add a test to that function when I wrote it.
* refactor(core): Rename echo-specific triggering functions
Now that the triggerViaEcho feature flag has been removed, rename the functions that were specific to the echo workflow to have more generic names.
>  refactor(core): Remove triggerViaEcho feature flag

- app/scripts/modules/core/src/cluster/cluster.service.ts
- app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
Makes Deck use moniker for GCE server groups. Depends on https://github.com/spinnaker/clouddriver/pull/3258
> feat(provider/gce): Moniker support for GCE server groups

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateServiceInstanceDirectInput.tsx
'Service' and 'Service Plan' were not populated when loading the configuration of a populated Deploy Service pipeline stage
spinnaker/spinnaker#4115
> fix(cf): populate saved pipeline stage data

- test/functional/tests/core/pages/ApplicationsListPage.ts
Nightly builds fail sometimes because this locator is used immediately after the browser is opened by the test runner and sometimes the app list hasn't loaded in yet.
> fix(tests): looking for app links sometimes fails because page isnt ready

- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
When searching for a manually started pipeline by eventId, we should also pass in the pipeline name to reduce the amount of data returned from the persistence store.
> fix(triggers): Add pipeline name to search request

- app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
Currently React trigger components don't receive prop updates when `ITriggerConfigProps#fieldUpdated` is called.
> fix(trigger): Fix react trigger components don't receive prop updates

- app/scripts/modules/core/src/widgets/spelText/SpelText.tsx
Fixes SpEL inputs for artifact selectors in React-based components.
> fix(artifacts): Fix SpEL text input used in React components

- app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.spec.ts
- app/scripts/modules/core/src/task/task.write.service.spec.ts
- app/scripts/modules/core/src/task/task.write.service.ts
- app/scripts/modules/core/src/task/tasks.controller.js
These endpoints were [just recently deprecated](https://github.com/spinnaker/gate/commit/4c06144025c0a0b264f88002e1ebeab302e88518), so we should start using the new, application-agnostic endpoints for these operations.
> refactor(core): use non-deprecated tasks endpoint for app tasks

- app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx
RunJob stage in execution now surfaces resources and env vars.
RunJob stage allows a user to configure resources and env vars. However during an execution, these are not provided for context, especially if it fails because of this config.
> feat(titus): Surface env and resources for runjob stage

- app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
We send `onTaskComplete` to the task monitor as a plain old function, so when the task completes, `this` is not what we want `this` to be.
> fix(titus): use arrow function to avoid bad this binding in callback

- app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
Turns out target groups are just target groups, and not specific to an NLB or ALB, so the names need to be unique across the two.
> fix(amazon): consider all target group names when creating new ones

- app/scripts/modules/core/src/domain/IPipelineTemplateV2.ts
- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.spec.tsx
- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
- app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateReader.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.less
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.states.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
Fixes https://github.com/spinnaker/spinnaker/issues/3888
Note: There are two duplicate-looking templates in this screenshot. This is working correctly and is just a side effect of spin's current implementation of template versioning.
- Adds template list screen that allows user to View the JSON of all of their saved templates
- Adds `#/pipeline-templates` route to get to the list screen (behind feature flag)
- Adds button in top nav to get to the list screen (behind feature flag)
I'm not opinionated about the location of the entrypoint (nav button at top of Deck) or the chosen URL (`#/pipeline-templates`). Happy to change these if anyone has suggestions for better placement or naming.
> feat(mptv2): add list screen for pipeline templates

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
This is consistent with the Deploy operation and the Clone server group action which both start on creation by default.
> fix(provider/cf): Default clone stage to start on creation

- app/scripts/modules/cloudfoundry/src/cf.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/rollbackCluster/CloudfoundryRollbackClusterStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/rollbackCluster/cloudfoundryRollbackClusterStage.html
- app/scripts/modules/cloudfoundry/src/pipeline/stages/rollbackCluster/cloudfoundryRollbackClusterStage.module.ts
- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/AccountRegionClusterSelector.spec.tsx
- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/AccountRegionClusterSelector.tsx
Cloud Foundry's Reactified implementation of AccountRegionClusterSelector did not account for moniker selection.  The moniker field is required by Orca to properly perform the rollback.
spinnaker/spinnaker#4180
> fix(cf): Repair Rollback Cluster pipeline stage

- app/scripts/modules/core/src/application/config/customBanner/CustomBannerConfig.tsx
- app/scripts/modules/core/src/application/config/customBanner/customBannerConfig.less
- app/scripts/modules/core/src/header/customBanner/CustomBanner.tsx
- Based on the UI for Entity Tag editing, adds support for writing custom application banners in Markdown, allowing for formatted text and links.
- Example: ![appbannermarkdown](https://user-images.githubusercontent.com/15936279/54939498-22dc4a00-4eff-11e9-8b7e-5de46ae4fdc6.png)
> feat(core): add markdown functionality to custom app banners

- settings.js
`webhook` was missing from `triggerTypes` in `settings.js` (patched file) whereas [it was available in `halconfig/settings.js`](https://github.com/spinnaker/deck/blob/efcec9696f70153ea09c4b0763ee15466a40c563/halconfig/settings.js#L239). this brings parity (for `triggerTypes`) between these two configuration files.
for deployments without `halyard`, without this in `triggerTypes`, one cannot define `webhook` triggers in deck UI. even the ones which are already defined wouldn't be rendered properly.
> fix(trigger): add webhook to triggerTypes

- app/scripts/modules/core/src/projects/service/ProjectWriter.ts
When orca is backed by SQL (not redis) there is a NOT NULL constraint on the `task.application` column.  We need to submit the task against some application. I've arbitrarily chosen 'spinnaker'.
> fix(core/projects): Submit task against the 'spinnaker' application

- app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
- app/scripts/modules/titus/src/index.ts
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/ConfigBinLink.tsx
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/ConfigBinModal.tsx
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/CustomMetric.tsx
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/configBin.reader.ts
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/configBinLink.component.ts
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/metricOptions.ts
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
We're going to start using ConfigBin (an internal service at Netflix) to forward Atlas metrics to Cloudwatch for AWS clusters. Currently, we're only using it for Titus.
Some minor refactoring to remove state in a few places, and to simplify some of the code matching existing metrics with canned ones, those are the friends we made along the way.
> refactor(titus): generalize ConfigBin and export it

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
4bc6ecd3ee0a3938627cb8b6c8a9c3c68148b3f8 fix(core/projects): Submit task against the 'spinnaker' application (#6748)
1f58407a8f8d1c28bf14c0e372cd3b482f4bb526 feat(amazon): show certificate upload/expiration when selected for load balancers (#6731)
efcec9696f70153ea09c4b0763ee15466a40c563 feat(core): add markdown functionality to custom app banners (#6745)
9c14b02e3212bfce64d2e228273a5ae2a2907fb6 feat(mptv2): add a search input to the mptv2 list (#6742)
a84eda8efb966221756c4ccad7a5106722892c6b fix(concourse): Support manual trigger execution by build number (#6738)
5529d53d562e9a8a6884ef93f96296c3d703b998 fix(core): Grey out execution actions for mptv2 pipelines (#6734)
1c9e07543aaefd36d8e1a5ea9d51321c350b57a8 feat(ecs): docker image selection (#6687) …
> Bump package core to 0.0.346 and amazon to 0.0.182 and titus to 0.0.81

- app/scripts/modules/core/src/pagerDuty/PageModal.tsx
Could use a full refactor on the ApplicationModelBuilder to remove the angular, but...not right now.
> fix(core): send application when paging via PagerDuty

- app/scripts/modules/core/package.json
65fbb679c66251db38e3db0ed62ce7f0c559ef1f fix(core): send application when paging via PagerDuty (#6764)
> chore(core): Bump version to 0.0.347

- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
angular2react makes it an object ref, derpity derp
> fix(titus): send cloudProvider as a string to ConfigBinLink

- app/scripts/modules/core/package.json
ad8d504863f654a659dc7c82b97b1c1b7a61a7e0 feat(core): provide link when task/stage fails due to traffic guards (#6772)
d819cf3740f9341f66aee9c8cfa40eb01c404054 fix(core): make chaos monkey opt-in for new apps (#6766)
> chore(core): Bump version to 0.0.348

- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.less
- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
- app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateWriter.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.states.ts
Fixes https://github.com/spinnaker/spinnaker/issues/4190
Adds a button to save a template directly from the pipeline export modal. Clicking the button saves the template and redirects the user to the templates screen where they can see their new template.
> feat(templates): add Save button to export pipeline template json modal

- app/scripts/modules/core/src/pagerDuty/PageModal.tsx
- app/scripts/modules/core/src/pagerDuty/pagerDuty.write.service.ts
#6764 tried to make sure that `pageApplicationOwner` tasks always have an app attached to them (we now require them when using the SQL storage backend for Orca). Problem is, the actual task being passed to `TaskWriter` never got an application — just the `TaskMonitor` instance we were using to watch it. 
This does two things:
- Ensure that `PagerDutyWriter.sendPage` always has an app to tie to the task it submits
- Move the decision logic for which app to use out of `PagerDutyWriter` by asking for it explicitly in `sendPage`. We don't really have enough context inside that method to know which app out of the list of many, one, or none would be appropriate
> fix(core/pagerDuty): give appropriate app to PagerDutyWriter

- app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/alarmBasedSummary.component.html
- app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/alarmBasedSummary.component.js
- app/scripts/modules/titus/src/help/titus.help.ts
You can't edit a policy with no alarm, so we might as well let you delete it. There's a slightly bigger question around why policies get into this state, but that's beyond the scope of Deck. In short, it happens when there is an error in Clouddriver copying a scaling policy: we create the new policy first, then we create the alarms; if something fails when creating the alarms (e.g. the Clouddriver instance gets terminated), we can end up here. This happens rarely but is something we should address.
Also removing an unused help field entry that has moved to our internal build.
> fix(amazon): allow deletion of scaling policies without alarms

- app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/namespaces.ts
Added AWS/ApplicationELB namespace to the list of cloudwatch namespaces.
> fix(amazon): Added AWS/ApplicationELB namespace to cloudwatch namespaces

- app/scripts/modules/amazon/package.json
- app/scripts/modules/titus/package.json
607f386a3511da4bb568a672ea2447ca2038b622 fix(amazon): Added AWS/ApplicationELB namespace to cloudwatch namespaces (#6791)
e96e7a927c56540c998fd6d09134df8438978625 fix(amazon): allow deletion of scaling policies without alarms (#6779)
e96e7a927c56540c998fd6d09134df8438978625 fix(amazon): allow deletion of scaling policies without alarms (#6779)
> Bump package amazon to 0.0.183 and titus to 0.0.86

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
The clone dialog needs to have pipeline and stage state so that it can look up available expected artifacts at this point in the pipeline's execution.
cc / @ciberkleid
> fix(provider/cf): Make expected artifacts selectable as clone manifests

- app/scripts/modules/google/src/domain/autoHealingPolicy.ts
- app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.html
- app/scripts/modules/google/src/serverGroup/configure/wizard/autoHealingPolicy/autoHealingPolicySelector.component.ts
- app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
- app/scripts/modules/google/src/serverGroup/details/autoHealingPolicy/modal/upsertAutoHealingPolicy.modal.controller.ts
Closes https://github.com/spinnaker/spinnaker/issues/4221
We made the following fixes to Deck and Clouddriver to disambiguate health checks of the same name by also specifying the health check kind:
Deck: https://github.com/spinnaker/deck/pull/6382
Clouddriver: https://github.com/spinnaker/clouddriver/pull/3282
This fix worked by using the health check's URL as a unique ID, and extracting the health check's name and kind from the URL prior to submit. However, this only worked for ad-hoc create and clone operations, not the deploy stage, where the field is bound to the stage model. To resolve this, I added an onSelect handler to the health check dropdown that will update the health check's name and kind based on the selected health check URL. Confusingly, Deck receives a server group's …
> fix(google): fix autohealing health checks in deploy stages

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/zones/zoneSelector.directive.html
- app/scripts/modules/google/src/serverGroup/serverGroup.transformer.js
This reverts commit ad2e2227442aa2e7abf85bf1a82ef7a5f51b1445.
In hindsight, Deck was already doing the right thing here. The platform, GCP, chooses the zones if the user doesn't specify them.  In some quick testing through the GCP UI, MIGs in us-central1 always seem to get spread across zones -b, -c, and -f and never end up on -a.  So it was incorrect to show in Deck that they might be placed on -a.
Closes https://github.com/spinnaker/spinnaker/issues/4071
> fix(google): revert "select all zones by default when deploying a regional gce server group (#6751)"

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/zones/zoneSelector.directive.html
- app/scripts/modules/google/src/serverGroup/serverGroup.transformer.js
Release-1.12.x version of https://github.com/spinnaker/deck/pull/6808
This reverts commit 63248626d8e416830b043fdc8db08d93e74e4bac.
In hindsight, Deck was already doing the right thing here. The platform, GCP,
chooses the zones if the user doesn't specify them. In some quick testing
through the GCP UI, MIGs in us-central1 always seem to get spread across
zones -b, -c, and -f and never end up on -a. So it was incorrect to show in
Deck that they might be placed on -a.
> fix(google): revert "select all zones by default when deploying a regional gce server group (#6751) (#6755)"

- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
`viewTemplateId` should be `templateId` when it's a parameter passed to the pipeline-templates-detail route.
> fix(mptv2): clicking a view link on template list screen throws exception

- app/scripts/modules/azure/help/azure.help.ts
- app/scripts/modules/azure/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/azure/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.html
- app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
- app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
- app/scripts/modules/azure/utility.ts
Background:
Enable Azure Load Balancer which supports inbound NAT port-forwarding rules to connect to azure vm instances.
There is one another related PR (https://github.com/spinnaker/clouddriver/pull/3552) in clouddriver. Please also help to review.
>  fix(provider/azure): Enable Azure Load Balancer from Azure VM Scale Set

- app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobLogsModal.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/runJobStage.ts
UI support for the V2 Run Job stage
This is just the basics of the stage. I'll be adding support for artifacts in future revisions. I'm not sure what we want to put in the execution details besides account and namespace but we could add more later.
> feat(kuberntes): v2 runJob

- app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
- app/scripts/modules/azure/loadBalancer/loadBalancer.transformer.js
- app/scripts/modules/azure/securityGroup/configure/CreateSecurityGroupCtrl.js
Background:
Currenly, when there is only one region, creating load balancer wizard failed to load region.
>  fix(provider/azure): Region can't be selected while creating loadbalancer with only one region

- app/scripts/modules/core/src/artifact/react/StageArtifactSelector.tsx
- app/scripts/modules/core/src/widgets/spelText/SpelText.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/ManifestBindArtifactsSelector.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
In 1.13, the K8S deploy manifest stage displays the new artifacts UI when the feature flag is enabled. When loading a pipeline defined in this way, artifacts were incorrectly nested one layer too deep.
Also fixed Promise treatment of the React components related to this.
See https://github.com/spinnaker/orca/pull/2830 for more details on the JSON structure changes we introduced into 1.13.
> fix(k8s): Fix deploy manifest

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.controller.ts
So that users aren't confused about whether they should put raw manifest text in "Text" source or in "Artifact" source of type base64.
> feat(k8s): Exclude inline base 64 artifact editing in k8s manifest

- app/scripts/modules/core/src/pipeline/details/LogsModal.tsx
- app/scripts/modules/core/src/pipeline/details/StageExecutionLogs.tsx
- app/scripts/modules/core/src/pipeline/details/index.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
supports logs for preconfigured kubernetes jobs. titus jobs only link
out to extenal systems for their logs. for kubernetes, logs are stored
in the execution context and can be displayed directly.
> feat(preconfiguredJob): logs for k8s jobs

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/defaultHttp.artifact.ts
For the same reason as in a previous PR https://github.com/spinnaker/deck/pull/6679, 
we also need to set the reference field for default http artifacts.
PTAL @jkschneider @jervi
> fix(artifacts): HTTP default artifact needs reference field

- app/scripts/modules/core/src/pipeline/config/stages/waitForCondition/SkipConditionWait.tsx
Turns out this is a warning that gets printed in the middle of the build output until it hits master, and then we run in production mode and it blows up.
> fix(core/pipeline): un-shadow parameter

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifest.validator.ts
These lookups were previously throwing errors under some conditions
> fix(kubernetes): safer lookups for deploy stage validators

- app/scripts/modules/core/src/pipeline/status/executionStatus.less
If the div showing execution status is too long on the X axis, the scrollbar will appear. That scrollbar, in conjunction with the `overflow-y: hidden` results in the "detail" link being impossible to click on.
<kbd>![56130276-b9db7580-5f84-11e9-91d3-8066fe5806de](https://user-images.githubusercontent.com/1613036/56131798-c366dc80-5f88-11e9-8c82-1d445c4dd44c.png)</kbd>
> fix(pipeline/executionStatus): "details" link hidden by scrollbar.

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/help/HelpMenu.tsx
This enables Spinnaker administrators to add a custom help link. This link can provide organization specific examples / use cases for Spinnaker. 
<kbd> ![](https://cl.ly/22da8b256bbe/Image%202019-04-11%20at%207.32.21%20PM.png) </kbd>
> feat(documentation): Custom help link

- app/scripts/modules/titus/src/instance/details/instance.details.controller.js
Something changed somewhere in Orca or Clouddriver that is causing grief terminating Titus instances when we send `managedInstanceGroupName` instead of `serverGroupName`
> fix(titus): send serverGroupName when terminating instances

- app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/LoadBalancerTypes.ts
- app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/index.ts
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/core/src/domain/ISubnet.ts
- app/scripts/modules/core/src/loadBalancer/CreateLoadBalancerButton.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/NumberInput.tsx
Working on a custom, wizard-driven flow for creating ALBs. It's very much tailored to Netflix for now, but will revisit it once we're happy with the flow.
These are the pieces that seem necessary to allow overriding (and ejecting from the wizard back into the default modal).
> refactor(core/amazon): allow custom load balancer creation flow

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
f6c87a338abd78d11ca1e4099fe5a2229ed6dfcb refactor(core/amazon): allow custom load balancer creation flow (#6852)
6ddc47602b701fce5890fe266429ddff38e8b0c3 fix(titus): correctly set dirty field on command viewstate (#6795)
20d676662a7caca429d4ccd52ef712f7fec140b0 feat(help): Custom help link (#6842)
a9cfe570a2a00c460716ac7c38d1f4b8da3ac7d4 chore: upgrade to react 16.8 (#6846)
2e4135a71ac9bec264a989b51c06af10f8f3ed07 fix(pipeline/executionStatus): "details" link hidden by scrollbar. (#6850)
af8fa5fe9bffe740ba7c0745ae542405a299cc24 feat(preconfiguredJobs): support produce artifacts (#6845)
48ba3fcd1e23cd1c4beab18a9e19d44deb2059af fix(core/pipeline): un-shadow parameter (#6843)
ec125272d65eef0495a120873ae621a14eec70f1 feat(core/pipeline): add execution UI for waitForCondition stage (#6826) …
> Bump package core to 0.0.351 and docker to 0.0.36 and amazon to 0.0.185 and titus to 0.0.87

- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.ts
The 'Find Artifact From Execution' stage has always filtered out the current stage when populating the pipeline choice dropdown in the UI. This places an unnecessary restriction on using artifacts from the current pipeline. An example use case for this is to pull a baseline artifact from the previous execution of the pipeline for ACA. This change removes the filter, allowing the current pipeline to be selected in the UI.
> fix(stage): remove pipeline filter for findArtifactFromExecution

- app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
- app/scripts/modules/azure/securityGroup/configure/CreateSecurityGroupCtrl.js
- app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
- app/scripts/modules/core/src/loadBalancer/loadBalancer.write.service.ts
- app/scripts/modules/google/src/loadBalancer/configure/common/commonLoadBalancer.controller.ts
- app/scripts/modules/google/src/loadBalancer/configure/http/httpLoadBalancer.write.service.js
- app/scripts/modules/oracle/src/loadBalancer/configure/createLoadBalancer.controller.ts
`networks` and `loadBalancers` caches no longer exist
> refactor(*): remove cache-clearing calls that do not do anything

- app/scripts/modules/core/package.json
0a5fd58ed76c894f9a8b0ab7027bd07e0dfc43ce refactor(*): remove cache-clearing calls that do not do anything (#6861)
a084b74ccffb3781eb8b534e8e6799d841c3ea28 fix(core): do not assume READ and WRITE are set on app permissions attribute (#6862)
0333b67defc62ae77cf5e48096ce7ea4715c1a5b fix(stage): remove pipeline filter for findArtifactFromExecution (#6858)
> chore(core): Bump version to 0.0.352

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/execution.less
- app/scripts/modules/core/src/pipeline/status/ExecutionParameters.spec.tsx
- app/scripts/modules/core/src/pipeline/status/ExecutionParameters.tsx
- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
- app/scripts/modules/core/src/pipeline/status/ParametersAndArtifacts.tsx
Hides the parameters/artifacts section if no parameters or artifacts are present:
_Current_
_PR_
Also changing the label: if there are no artifacts, just show "parameters"; if there are no parameters, just show "artifacts":
_Current_
_PR_
> fix(core): conditionally show/label parameters section of execution bar

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
3764ce7eaa7d1c117daf0c09e3fa2d9d26d579cc fix(core): conditionally show/label parameters section of execution bar (#6865)
769ebf89c08948df63bf33de47c1b7883a0db5f9 feat(titus): Include links appropriately from property file contents (#6730)
> Bump package core to 0.0.353 and titus to 0.0.88

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifest.validator.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
- settings.js
- feat(kubernetes): validate text manifests when rollout strategies enabled
- Display warning when [strategy.spinnaker.io/max-version-history](https://www.spinnaker.io/reference/providers/kubernetes-v2/#strategy) conflicts with behavior of selected strategy
- Display warning when not (exactly) one ReplicaSet manifest is entered
- feat(kubernetes): remove rollout strategies feature flag
- Now that Orca and Clouddriver support Kubernetes rollout strategies, it is safe to remove this feature flag
>  feat(kubernetes): validate text manifests when rollout strategies enabled

- app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx
Blowing up right now because `{entry}` is not nice with React.
> fix(titus): correctly render JSON objects in run job details

- app/scripts/modules/titus/package.json
9a622f0edea428a5582aa17ba8b42be1a454d4c9 fix(titus): correctly render JSON objects in run job details (#6872)
> chore(titus): Bump version to 0.0.89

- app/scripts/modules/core/src/pipeline/config/stages/FormikStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/StageConfigWrapper.tsx
- app/scripts/modules/core/src/pipeline/config/stages/common/IStageConfigProps.ts
- app/scripts/modules/core/src/pipeline/index.ts
- app/scripts/modules/core/src/presentation/forms/layouts/ResponsiveFieldLayout.tsx
- app/scripts/modules/core/src/presentation/forms/layouts/index.ts
The goal is to ultimately make stage configs simpler, more composable and have less boilerplate, something like:
```
<FormikFormField name="x" label="X" input={props => <TextInput {...props} />} />  
<FormikFormField name="y" label="Y" input={props => <AccountSelectInput {...props} />} />  
<FormikFormField name="z" label="Z" input={props => <RegionSelectInput {...props} />} />  
```
This means:
- Using `<FormikFormFields>` so that 1) form state can be managed by Formik and 2) layout is handled by `FieldLayout`s
- `Formik` for stages should be wired up in a consistent way
- `FieldLayout` inherited via context so that it doesn't have to be explicitly wired up
`<FormikStageConfig>` handles the latter 2 so that those details don't need to be part of every single stage.
Instead stage configs …
> refactor(stages): FormikStageConfig to provide Formik for StageConfigs

- app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx
This pull request changes `initialize` function and added `componentWillUnmount` function to make sure the subscription unsubscribed properly.
I found an issue that `Manual Execution` modal sent duplicate HTTP request to "/images/tags" endpoint.
For example, if you click `Start Manual Execution` button, select a pipeline, 1 OPTION method and 1 GET method request, it's **fine**:
<kbd><img width="1151" alt="1" src="https://user-images.githubusercontent.com/20374/56544754-58cd2680-65b0-11e9-8343-6bed0a519c4c.png"></kbd>
<kbd><img width="1153" alt="2" src="https://user-images.githubusercontent.com/20374/56544762-5ff43480-65b0-11e9-87f3-ef6fe6ba956f.png"></kbd>
<kbd><img width="1150" alt="3" src="https://user-images.githubusercontent.com/20374/56544768-6387bb80-65b0-11e9-8b91-fcc9fd5860bc.png"> …
> fix(docker): Fix subscription leak in DockerTriggerTemplate

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestConfig.html
When the artifacts rewrite feature flag is enabled, we should hide the manifest artifact selector in text mode and only show the YAML editor.
Before:
After:
> fix(kubernetes): hide manifest artifact selector in text mode

- app/scripts/modules/core/src/domain/IStageOrTriggerTypeConfig.ts
- app/scripts/modules/core/src/pipeline/config/stages/FormikStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/validation/PipelineConfigValidator.ts
Wiring up the new Formik-style stages' `validate` functions to the pipeline validator.
The old `validators` will take precedence, but the expectation is to use either or and not both, so if a stage has a `validate` function, the old `validators` should be removed.
> refactor(stages): Wire up Pipeline validation to stage validateFn

- app/scripts/modules/core/src/authentication/AuthenticationInitializer.ts
If the network interceptor fails on a bunch of calls that are stacked up, the logged out modal will pop up for each one, which happens when there is a network connection issue (e.g. VPN reconnection) during an app refresh. I've seen the modal pop up 10 or 11 times, which renders the background black (and also results in 10 or 11 re-authentication attempts when navigating away from, then back to, the logged out page).
This...fixes that.
> fix(core): do not overdo showing the auth modal

- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/createPipelineFromTemplate/CreatePipelineFromTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/createPipelineFromTemplate/createPipelineFromTemplate.less
- app/scripts/modules/core/src/pipeline/config/templates/v2/createPipelineFromTemplate/index.ts
Before this fix, the application select box would get clipped at the bottom of the modal and not show "samplek8"
> fix(core): Show all app selections when creating a pipeline from mptv2

- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
Users have to edit the load balancer right now to see details on a redirect action, no good.
Before:
After:
> feat(aws): show ALB listener redirect info in details

- app/scripts/modules/core/src/pipeline/config/stages/overrideFailure/overrideFailure.component.js
If the user edits the `failPipeline`, `continuePipeline`, or `completeOtherBranchesThenFail` fields via the Edit Stage as JSON modal, the changes are not reflected in the view until switching to another stage.
The bug occurs because, when we edit the stage as JSON, we assign the updated stage fields to the existing stage object, instead of replacing it completely.
This is not a new bug! It's been there since this feature was added almost three years ago. It just wasn't noticed because the logic we're hiding in this component is kinda nuts so nobody tried to manually edit it. Until this morning.
> fix(core): update stage failure component when JSON changes

- app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
I tried three or four different libraries that are supposed to transform `.d.ts` file imports from path aliases to relative paths, but couldn't get any of them to work. Maybe because of our weird "node modules at the top, tsconfig and webpack config at the bottom" setup? I don't know, but I gave up and felt sad about it.
> fix(core): use relative imports for ReactSelectInput

- app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
Strategies exist in `app.strategyConfigs` so `this.pipelineConfig` will be undefined `PipelineTemplateV2Service.isV2PipelineConfig` isn't protected against that.
Typescript probably would've caught this!
> fix(core): Fixed exception while configuring strategies

- app/scripts/modules/core/src/presentation/forms/inputs/ChecklistInput.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/index.ts
Not sure if there is a better way to handle this.
I need a form input to handle toggling an array of strings, e.g. days of the week:
```
{
days: ['Monday', 'Wednesday', 'Friday']
}
```
Usage:
```html
<FormikFormField
name="days"
label="Days"
input={props => <ChecklistInput {...props} options={['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']} />}
/>
```
> feat(core): add ChecklistInput form component

- app/scripts/modules/core/src/presentation/forms/forms.less
* removed redundant property declarations
* allowing `groupHeader` to be used outside an `sp-formItem`
* italicizing help contents (inline help) for new forms
> feat(core): modify form CSS for help text, group headers

- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildStage.ts
Adds GCB stage execution details tab with current status and link to logs.
> feat(gcb): add gcb-specific execution details tab

- app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/PackageSection.tsx
This is similar to how it is represented in the AWS impl. We could probably standardize the attributes across providers. I’m using “ciBuild” rather than “buildinfo” because CF already has a “buildinfo” that refers to creating the droplet with a build pack. In the view I prefer to incorporate the link with the build number rather than show it explicitly. There is not a lot of horizontal real estate in the detail side panels.
> feat(cf): add build info to server group

- app/scripts/modules/kubernetes/src/v2/manifest/manifest.service.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/JobManifestPodLogs.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
instead of reading logs from execution context (which will be removed
soon), use the job log viewer modal to grab logs directly from the
infrastructure. large portions of code stolen directly from the
DeployStatus component.
> refactor(runJob/kubernetes): use joblogviewer

- app/scripts/modules/core/src/manifest/IManifestSubscription.ts
- app/scripts/modules/core/src/manifest/ManifestService.ts
- app/scripts/modules/core/src/manifest/index.ts
- app/scripts/modules/core/src/manifest/stage/JobManifestPodLogs.tsx
- app/scripts/modules/core/src/manifest/stage/JobStageExecutionLogs.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/details/StageExecutionLogs.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestEvents.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
refactor some of the manifest components into the core module and use
those instead of the kubernetes specific ones. doing this because
`StageExecutionLogs` in the `core` module needs to use
`JobManifestPodLogs`.
> refactor(runJob/kubernetes): refactor exec details

- app/scripts/modules/core/src/application/modal/PermissionsConfigurer.spec.tsx
- app/scripts/modules/core/src/application/modal/PermissionsConfigurer.tsx
Applications can now have a new permission type called execute along with read and write. The application creation via the UI ensures that execute always implies read access and write always includes execute (and read).
Part of spinnaker/spinnaker#3554
> feat(roles): Add execute permission type to create new application.

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
8a2667c4b82199a63445223e5fc4e946dda9ce11 feat(titus): job disruption budget UI (#6925)
fc6c84301ae02a7d6add6dbe31f9b1f33ebfc0a3 feat(roles): Add execute permission type to create new application. (#6901)
9e03e52fbaf480b5689e4e186b7f5928c976cf6f refactor(runJob/kubernetes): refactor exec details (#6924)
3b7e5560dda48ebea94ab8ab63be0a5bce3b2a24 feat(gcb): add gcb-specific execution details tab
8a2667c4b82199a63445223e5fc4e946dda9ce11 feat(titus): job disruption budget UI (#6925)
> Bump package core to 0.0.358 and titus to 0.0.91

- app/scripts/modules/core/src/api/ApiService.spec.ts
- app/scripts/modules/core/src/api/ApiService.ts
This only handles the case of a consumer of ApiService requesting with a leading
slash character. Full uri normalization may be a useful thing to add to handle
a request containing directory traversal characters but I don't suspect we have
any of those whereas the double-slash case is pretty easy to accidentally do
> fix(core/api): normalize API request urls

- app/scripts/modules/core/src/pipeline/config/triggers/cron/cronPicker.html
Update the link to the reference for CRON expressions (old one was no longer valid)
Also, added a stronger warning when invalid expressions are entered
> fix(CRON): update links for CRON expression reference

- app/scripts/modules/core/src/presentation/forms/forms.less
When flexbox calculates a `flex-basis`, it does not consider margins, so having two columns next to each other whose `flex-basis`es add up to 100 will cause an overflow of content if either has a `margin` on its side.
Fix is pretty easy - just use `padding`.
> fix(core): use padding instead of margin on form flex columns

- app/scripts/modules/core/src/manifest/stage/JobStageExecutionLogs.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
if `context.execution.logs` is present (pulled from manifest annotation
`jobs.spinnaker.io/logs`), render the content as a link, templated with
manifest data.
Depends on spinnaker/orca#2893.
> feat(runJob/kubernetes): render external link

- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.controller.ts
This fixes a bug in Bake Manifest stage configuration. If the input artifacts have more than one account, UI shows the user a dropdown for selecting the desired account. However this selection is lost every time the user navigates to another screen/stage and comes back to Bake Manifest stage configuration, falling back always to the first artifact account shown in the dropdown.
The bug is caused because `InputArtifact` objects are created before having the list of artifact accounts ready. This has the effect of clearing the selected account, and when the account list is initialized the selected account fallbacks to the first in the list.
> fix(bake/manifest): Preserve artifact account selection

- app/scripts/modules/core/src/artifact/expectedArtifact.service.ts
- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildValidators.ts
- Allows GCB stage config to accept build definition as an artifact when `ARTIFACTS_REWRITE_ENABLED=true`. Otherwise, only accepts build definition as text and hides artifact selector. Accepting pre-rewrite artifacts in a React component without introducing Angular dependencies is non-trivial and will be addressed in a separate PR.
- Modifies function returned by `ExpectedArtifactService.accumulateArtifacts` to accept nested fields (i.e. `keyA.keyB`) in order to display consumed artifacts nested in context
- Refactors GCB stage to more closely adhere to new `FormikStageConfig` pattern and cancelable promise convention
Artifact defined inline:
Artifact defined in pipeline config:
Consumed artifact (when artifact is defined in pipeline config):
> feat(gcb): accept gcb definition file as artifact

- app/scripts/modules/titus/src/domain/ITitusServerGroup.ts
- app/scripts/modules/titus/src/help/titus.help.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
- app/scripts/modules/titus/src/serverGroup/details/DisruptionBudgetSection.tsx
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
I'm not going to convert the entire Titus server group details panel to React, but I will at least make this component not-Angular...
> feat(titus): show disruption budget in job details panel

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
0c4c5b2f71dff58da43a2ef4e0aaa69f619521df feat(gcb): accept gcb definition file as artifact (#6935)
e80240058c369f45b561bcb28a512080830ce538 fix(bake/manifest): Preserve artifact account selection (#6937)
d122749348d196b8626225d8741e6cdcb6e714bd feat(runJob/kubernetes): render external link (#6930)
3647ca552cc9fcdcb524cc748a462ba57def8849 fix(core): use padding instead of margin on form flex columns (#6934)
01cf072a3bf50ccdfad60db774f324cced733293 fix(CRON): update links for CRON expression reference (#6933)
a369da2b20fb058fb37eaf9cb4c72c6044e33212 fix(core/api): normalize API request urls (#6927)
a6b80f88c68afe524647c1a87546ce857649b262 feat(titus): show disruption budget in job details panel (#6938)
9b53dea0c01e30f98c3881de973dd489710cb451 fix(titus): allow editing default policy options …
> Bump package core to 0.0.359 and titus to 0.0.92

- app/scripts/modules/core/src/artifact/ArtifactReferenceService.spec.ts
- app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
fix(artifacts): remove stage references to removed artifacts in artifacts rewrite mode
- Adds call to `ArtifactReferenceService.removeReferenceFromStages` to post-artifacts-rewrite logic for trigger/artifact deletion.
feat(artifacts): support nested artifact references in ArtifactReferenceService
- Allow `ArtifactReferenceService.removeArtifactFromFields` to specify nested references to artifacts (i.e. `keyA.keyB`) by replacing direct lookups with `_.get` and `_.set`. This cleanest way to do this was replacing the `delete` logic with a `._set` to null, so updated tests accordingly.
> fix(artifacts): remove stage references to removed artifacts in artifacts rewrite mode

- app/scripts/modules/titus/src/serverGroup/details/DisruptionBudgetSection.tsx
- package.json
- yarn.lock
Instead of, e.g. "02:24:48", show "2h 24m 48s".
I'm wary of bringing in yet another library, but this thing is trivially small (3.3kb, including its one dependency), so not that wary.
> feat(titus): show disruption duration in readable format

- app/scripts/modules/titus/package.json
607ba2123336b69ee18df59af9c2ebb83bb37268 feat(titus): show disruption duration in readable format (#6945)
> chore(titus): Bump version to 0.0.93

- app/scripts/modules/amazon/src/securityGroup/securityGroup.transformer.js
- app/scripts/modules/core/src/cache/infrastructureCacheConfig.ts
- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
We ran into Safari' local storage limit (5 MB) trying to put the security groups cache in there. The changes here reduce the size of what we're putting into local storage by doing a couple of things:
* adding an additional level of grouping to each region (vpcId), so we don't have to store its value repeatedly
* storing the objects as a two-string tuple ([name, id]) instead of an object, so we don't have to store `"name":` and `"id":` repeatedly
This reduces the stored value size by about half. Compression adds about 10-30ms; decompression adds 10-30ms, too. I played around with actual compression algorithms, and was seeing ~90% size reduction, but I was also seeing 250+ms on both compression and decompression, so that's a non-starter IMO.
This is probably the last band-aid we want to put …
> feat(core): compress AWS security groups before caching

- app/scripts/modules/titus/src/domain/IJobDisruptionBudget.ts
- app/scripts/modules/titus/src/domain/ITitusServerGroup.ts
- app/scripts/modules/titus/src/domain/index.ts
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/WindowPicker.tsx
- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/DisruptionBudgetSection.tsx
- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/EditDisruptionBudgetModal.tsx
- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
Not exciting, fortunately. Reusing the budget editor from the create/clone modal to allow editing of existing disruption budgets.
> feat(titus): allow editing of existing disruption budget

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
954506ac56629b416441455ad1bb91929df19860 feat(core): compress AWS security groups before caching (#6947)
67baf43add977faded5eabb1e01b454acbdd1bce refactor(core): convert providerSelection modal to React (#6936)
1ada02195c197978e714126bf867121971ec7ccb feat(kubernetes): expose rendered helm template in execution details (#6943)
edee9effaf06ea096e98b5b65eed0d945d2bb76c fix(artifacts): remove stage references to removed artifacts in artifacts rewrite mode (#6939)
954506ac56629b416441455ad1bb91929df19860 feat(core): compress AWS security groups before caching (#6947)
016be9e269700ec78d5f809c60c6d43665183254 feat(titus): allow editing of existing disruption budget (#6950)
67baf43add977faded5eabb1e01b454acbdd1bce refactor(core): convert providerSelection modal to React (#6936)
> Bump package core to 0.0.360 and amazon to 0.0.188 and titus to 0.0.94

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
61c4afa03fd275f094925c64853af2851d15c563 fix(core): use new ProviderSelectionService everywhere (#6953)
bbcbd7363b860f12f624a1a6b1f0b2c2d70f0050 fix(titus): import TitusReactInjector from subdirectory (#6952)
> Bump package core to 0.0.361 and titus to 0.0.95

- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionConfig.html
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/expectedArtifact.component.ts
Fixes spinnaker/spinnaker#4344.  (This will also require a small change to orca a the orca task does not support looking up a default artifact.)
Find artifact from execution doesn't use the full expected artifact component, which means users can't assign a name or use a default artifact. Upgrade it to the full expected artifact component so
it gets these features.
Also fix the field defaulting; currently the fields will reset if you navigate away and back to the stage before saving.
Also add the "Artifact Status" tab to this stage so it's easier to see the artifact that was bound.
> fix(artifacts): Allow defaulting in execution artifact

- app/scripts/modules/core/src/pipeline/status/ExecutionParameters.tsx
- app/scripts/modules/core/src/pipeline/status/executionParameters.less
In the new parameter UI for executions, we truncate parameter values over a certain size. Turns out that the toggle for showing/hiding the truncated value was setup to fire when clicking _any part of the value_, not just the 'View Full' link, and that makes it hard/impossible to select text out of a long value (like a JSON object) to copy-paste.
This changes to an always-visible 'Show more' / 'Show less' toggle, and removes click handling on the text itself. I had to do some weird layout hacking with `line-height` to get the link to work, which as far as I can tell is caused by the table layout these parameters are using (the clickable area seems to get truncated by the table row element somehow).
In my heart of hearts I'd like to move to using flex layouts here as I think that would fix …
> fix(core/executions): make text on truncated params selectable

- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/DisruptionBudgetSection.tsx
- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/EditDisruptionBudgetModal.tsx
We need to conditionally set the `containerHealthProviders` based on the `platformHealthOnly` flag on the application attributes.
> fix(titus): consider platformHealthOnly flag when setting budget health

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
6d151c042e125e0de9f87da8eb5f373e9e3eed89 feat(stages): Support SpEL autocompletion for Evaluate Variables stage editor (#6958)
b74c8555f625c68ea0be7194d2c404db18f3264f fix(core/presentation): Handle non-string inputs to Markdown component using .toString() (#6960)
c931524e74b424282651f972f0e8841c17a316d4 fix(core/executions): make text on truncated params selectable (#6959)
3d7c79475835252ca456f515458f46b9fa7228ba fix(artifacts): Allow defaulting in execution artifact (#6961)
60ced4ad2f84cff5536631c196d88ce4e03b2639 feat(stages): Add Concourse stage (#6957)
cdd46e00b217e2010aba1dbec9d956ed64cd9227 fix(titus): consider platformHealthOnly flag when setting budget health (#6963)
> Bump package core to 0.0.362 and titus to 0.0.96

- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
This enables manual execution for templated v2 pipelines. This was fixed when configuration was addressed in this commit, https://github.com/spinnaker/deck/commit/90fb96c4bfbbb07b23c8c3072229e58aa6f68868#diff-a04c4d36f5303c52f54f0283a5e17c51 , while this PR enables interacting with UI elements for starting manual executions.
https://github.com/spinnaker/spinnaker/issues/4390
> feat(core): Enable manual execution of mptv2 pipelines

- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
This is more general purpose build info than the Jenkins one. It is based on the Artifactory buildinfo and will already be a part of the server group.buildinfo.
ICloudFoundryBuildInfo should probably be moved to core since it is general purpose, though there is already an IBuildInfo there that looks different. Maybe IArtifactoryBuildInfo, though there is nothing that ties it Artifactory exclusively.
> fix(server group): show a CI build link in server group.buildinfo

- app/scripts/modules/core/src/pipeline/service/execution.service.ts
Some people (I won't mention who), don't like bracket so we need to encode them or Gate will blow up.
> fix(executions): URI Encode pipeline names

- app/scripts/modules/core/src/pipeline/config/templates/v2/configurePipelineTemplateModalV2.controller.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/configurePipelineTemplateModalV2.html
This is a small fix to add Expected Artifacts to the list of items that can be selectively inherited from a template.
> fix(core): Add expected artifacts to inheritable mptv2 collections

- app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
UI for v2 run job capture output. there are 2 options - logs and
artifact. setting to `logs` will set the `propertyFile` option to
trigger the runJob stage to read from the container logs. setting to
artifact will trigger the `ConsumeArtifactTask` to fetch and inject the
defined artifact.
> feat(runjob): capture output ui

- app/scripts/modules/core/src/serverGroup/ServerGroup.tsx
We need to make this links regional, e.g. `url: 'https://registry.{{region}}.netflix.net/',
> feat(core): allow dynamic resolution of docker insights URL

- app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
- app/scripts/modules/core/src/search/searchResult/SearchResults.tsx
1. We rarely set `isSearching`, but we should.
2. If the user does not click on one of the side tabs, and there are no matches for a search, they get stuck in the "fetching search results" screen forever.
> fix(core): show no results message on v2 search

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
8edcc221c45f4d3533ffe2056323688a4ae31e32 fix(core): show no results message on v2 search (#6982)
1bbd93664306eaea595a746ae664c64944559ed4 feat(core): allow dynamic resolution of docker insights URL (#6981)
84db0ef6c88ba6b234a4f06d7f2af91b2d84ee41 fix(cf): reorg build info details on server group detail and summary (#6983)
c48a0179a179524fe02cdda76fb0eedb3d25bfaa fix(core): Add expected artifacts to inheritable mptv2 collections (#6975)
a21e95e8da9f7d3ed8a83da708e353dee71cd8ef refactor(core): Reactified parameters for triggers (#6923)
e439d2c6bb703f6f5a6483be86fbaa4163445c64 feat(gcb): allow pre-artifacts-rewrite expected artifacts to be selected in gcb stage (#6948)
fc50576eb0ff54ed1dd0a1c8efbac08c074e42cc fix(executions): URI Encode pipeline names (#6971) …
> Bump package core to 0.0.363 and amazon to 0.0.189

- app/scripts/modules/core/package.json
f44e2e8f93c3a509765633c4ab1e79694d7c2177 fix(titus): Shimming the execution logs for preconfigured jobs (#6972)
> chore(core): Bump version to 0.0.364

- app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js
I mean...I guess it was being imported by something else at some point?
> fix(amazon): explicitly import d3 for scaling policy graphs

- app/scripts/modules/amazon/package.json
e06039b98d9e4ae96b2c8849daae17c077b16237 fix(amazon): explicitly import d3 for scaling policy graphs (#6989)
> chore(amazon): Bump version to 0.0.190

- app/scripts/modules/core/src/pipeline/config/triggers/artifactory/ArtifactoryTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTrigger.tsx
The deck build is currently failing as non-allowed imports are present; fix these to import submodules
> fix(*): Fix imports

- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
If a pipeline has never run, it won't show up in the executions view when doing a text search that includes its name.
> fix(core): include un-run pipelines when filtering by text

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
4c06d10d70bc53008aaeeee1ae7441c36bfcf485 feat(titus): Render run job output file as YAML (#6992)
b888ff581c718da3dda9d3274b20c706184f5aff fix(core): filter empty URL parts in ApiService, do not next scheduler on unsubscribe (#7000)
4c06d10d70bc53008aaeeee1ae7441c36bfcf485 feat(titus): Render run job output file as YAML (#6992)
> Bump package core to 0.0.366 and titus to 0.0.97

- app/scripts/modules/core/src/projects/configure/Applications.tsx
- app/scripts/modules/core/src/projects/configure/ConfigureProjectModal.tsx
- app/scripts/modules/core/src/projects/configure/Pipelines.tsx
The `validate` method gets called immediately, so all the pipeline configs on an existing project (when editing) appear with a red outline.
Minor refactor to prevent validation until the pipeline configs are all initialized.
I'm sure there's an RxJS way to do this, too.
> fix(core): do not validate pipeline configs before initialization

- app/scripts/modules/core/package.json
cfb2a51e906c1b2cf50280413fab4db06ba8ef05 fix(core): do not validate pipeline configs before initialization (#7003)
> chore(core): Bump version to 0.0.367

- app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTriggerTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/jenkins/JenkinsTriggerTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/travis/TravisTriggerTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTriggerTemplate.tsx
This was kind of lost in the refactor to favor composition over inheritance.
It's worth considering a refactor of this functionality when we convert the manualPipelineExecution modal itself to React; this is a tactical fix to allow existing code to continue functioning.
Also fixing the label on the pipeline stage.
> fix(core): provide formatLabel option for all trigger types

- app/scripts/modules/core/package.json
7639f803ab3d197d861aa4ac2c03062ea2b1f494 fix(core): provide formatLabel option for all trigger types (#7007)
> chore(core): bump package to 0.0.368

- app/scripts/modules/core/src/pipeline/config/parameters/Parameters.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/triggers.directive.js
Pipelines created before https://github.com/spinnaker/deck/pull/6923 was deployed will not have `parameterConfig` unless the user has added parameters.
We don't really need to add the empty `parameterConfig` array to the pipeline. Doing so changes the JSON, which makes the pipeline dirty, which shows a revert button, which throws an error when clicked.
There's already a guard in place on the `addParameter` which will initialize the field. That's all we really need AFAICT.
> fix(core): do not automatically inject parameterConfig on pipelines

- app/scripts/modules/core/src/pipeline/config/triggers/BaseTrigger.tsx
Regression introduced in #6970 while converting triggers to React
> fix(core): Hide "Run as user" when using managed service accounts

- app/scripts/modules/kubernetes/src/v2/manifest/wizard/BasicSettings.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
adds fields for namespaceOverride to allow users to define the namespace
their manifests are deployed into (particularly for manifests baked from
Helm charts).
> feat(provider/kubernetes): namespace deployManifest

- app/scripts/modules/core/src/pipeline/config/triggers/BaseTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/webhook/WebhookTrigger.tsx
few fixes for the new react-powered pipeline and webhook triggers:
- the status chcecklist for for pipeline triggers wasn't transforming the `Set`s coming from `Checklist` to arrays, which got masked by the fact that the `onUpdateTrigger` method is typed with `any`. End result was that once a status was changed the underlying JSON was malformed and made the trigger component un-renderable on the next navigation to the same view
- fixed up some minor things in `PipelineTrigger` like not triggering the `destroy$` subject on unmount and not using the pre-existing `status` list if one existed
- webhook triggers were un-renderable in all cases due to using a standard instance method instead of an arrow function
> fix(core/pipeline): fix type mismatch in pipeline trigger, broken webhook trigger

- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestDetailsTab.tsx
If the bake manifest stage doesn't output any artifacts, the stage fails to render due to an NPE. This is probably rare as you'd generally want at least one artifact, but still worth fixing.
> fix(kubernetes): Fix NPE in bake manifest details

- app/scripts/modules/core/src/application/config/applicationAttributes.directive.js
- app/scripts/modules/core/src/application/modal/PermissionsConfigurer.spec.tsx
- app/scripts/modules/core/src/application/modal/PermissionsConfigurer.tsx
PermissionsConfigurer always assumed apps had EXECUTE permissions set
which is not true for applications created before EXECUTE was a thing.
A more detailed description is here: https://github.com/spinnaker/deck/pull/7015#issue-279537064
Thanks @jervi !!
> fix(authz): Handle apps without execute permissions

- app/scripts/modules/core/src/pipeline/config/triggers/artifactory/ArtifactoryTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/git/GitTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/PubsubTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTrigger.tsx
make trigger code more consistent and fix some rendering issues
in relation to the refactor https://github.com/spinnaker/deck/pull/6970
> refactor(core): minor fixes to the refactored triggers

- app/scripts/modules/core/src/chaosMonkey/chaosMonkeyExceptions.component.html
For example, one may actually want to enable chaos monkey on all other clusters except for the stack-less cluster.
> fix(chaos): Stack and detail are actually not required

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
fix stage initialization by setting the stage's application config if it
doesn't exist. this field is required to be set for the stage to work.
initially i had assumed the that BasicSettings component would configure
it.
> fix(kubernetes): fix runjob stage init

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/HelmArtifactEditor.tsx
helm chart versions weren't being listed properly because the chart name
was being pulled from the previous value. so, the list of versions you
got back were for a previously selected chart name instead of the newly
selected chart name.
> fix(artifact/helm): fix version list

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
When we navigate from Executions to standalone, `sortFilter.groupBy` remains in state (which is fine), but that ended up causing `showExecutionName` to be `false`, which is not consistent from if standalone was the initial view.
Also consolidated the nearly identical blocks of rendering the header.
> fix(executions): Fixed missing account tags in standalone

- app/scripts/modules/core/src/serverGroup/ServerGroupHeader.tsx
In the (currently unlikely) event that images and build info are both available, the images should not be first.
> fix(cf): server group header build links should precede images

- app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
Pretty sure this code path is only exercised at Netflix, and we don't support s3-backed AMI baking any more.
> feat(amazon): remove s3 as store type option for baking

- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
We were losing manually defined imageId on refreshes because didn't properly handle the `defineManually` case.
Basically we only call `synchronizeChanges` with the parts (org, repo, tag/digest), but when we're defining the imageId manually, we end up generating an `undefined` imageId because tag was undefined.
**tl;dr**
For the defineManually case, we just needed to parse imageId into `IDockerImageParts` before passing it into `synchronizeChanges`
> fix(docker): Stop losing manually defined imageId

- app/scripts/modules/core/src/task/monitor/TaskMonitor.ts
- app/scripts/modules/core/src/task/monitor/taskMonitor.html
When the task monitor first pops down, we should steal the focus so that the submit button that's underneath it no longer has focus. People keep pressing enter twice and submitting multiple duplicate tasks.
> fix(core): blur active element when rendering task monitor

- app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
- app/scripts/modules/core/src/presentation/FormElements.tsx
I was tempted to change these from SpEL inputs to number inputs but assuming there is a reason they are SpEL-enabled?
Also always setting `invalid` class on the input if there's an error. Otherwise, we have to add some pretty hacky stuff to `className` on the input itself.
> fix(core/amazon): validate target group healthcheck fields

- app/scripts/modules/core/src/api/ApiService.spec.ts
- app/scripts/modules/core/src/api/ApiService.ts
We have some internal endpoints we are proxying that return `application/hal+json`, which means we can't use API right now without, uh, this change or some change like this. Also there is not enough regex in the codebase.
> feat(core): allow any json subtypes in API response

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
2268217b0f3cc8bf52be773a0d7e4ef3899bc621 feat(core): allow any json subtypes in API response (#7040)
b55e3b819c219ec75544c6753891b31ff92ee5d2 fix(core/amazon): validate target group healthcheck fields (#6962)
c9791e62d032ab06f5fe06ffc3f3c070a8e2fea9 fix(core): blur active element when rendering task monitor (#7034)
43fb8a0b6ed63f818ab0a65cf15b3590dd6b40f5 fix(core): unwrap font-awesome span from button label (#7032)
8982b34874cefc7e2862d05acb735e808b62703d fix(cf): server group header build links should precede images (#7027)
59b69b8968631712985b8d0c4285696adf416c9c fix(executions): Fixed missing account tags in standalone (#7036)
f3fd44cb512ce594733fba983ac0eb38db77b905 fix(artifact/helm): fix version list (#7030)
f1ca123fdbfe237fadb3f6054d2b6066f361b1e0 fix(chaos): Stack and detail are …
> Bump package core to 0.0.371 and docker to 0.0.40 and amazon to 0.0.191

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.module.ts
Implements: spinnaker/spinnaker#4361
Corresponding clouddriver patch: spinnaker/clouddriver#3686
> feat(cf): Accepting both JSON and YAML in the Deploy Service Configuration stage `parameters` field

- app/scripts/modules/core/package.json
a6838326fdb8d0879ac062cacd421801615b6760 fix(core): set runAsUser field correctly on triggers (#7048)
f0287a11ccf92ab902adb55de8664bcde43175bd fix(runJob/kubernetes): use explicit pod name (#7039)
fc1cd1be9a361aad29f55ec4b17943273bd862f9 fix(core): allow clearing of run as user field in triggers (#7045)
246637936d56234d84801a91733afb630c9cb0b4 refactor(core): reactify CRON trigger (#7020)
> chore(core): Bump version to 0.0.372

- app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
Since we check for errors via `Object.keys`, we end up with false positives on the validation of target groups.
> fix(amazon): do not set target group errors to falsy values

- app/scripts/modules/amazon/package.json
e259625d239ba3246de3a06273236d4768cbfc2a fix(amazon): do not set target group errors to falsy values (#7050)
> chore(amazon): Bump version to 0.0.192

- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
- app/scripts/modules/docker/src/image/DockerImageUtils.spec.ts
- app/scripts/modules/docker/src/image/DockerImageUtils.ts
- app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
Apparently we never parsed the following formats correctly:
- `a/b/c:t`
- `x:sha256:abc123`, we always parsed digest into `sha256` instead of `sha256:abc123` because we split on the `:` and only used the first part
Also fixed a bug in cloning a server group that was deployed by digest where we always dropped the digest when building the command because we only looked at `dockerImageVersion` and not `dockerImageDigest`.
> fix(docker): Fixed imageId parsing and digest support

- app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
The react Select component does not render a large number of jobs very well. In our environment it freezes the browser for ~30 seconds after every typed letter. VirtualizedSelect seems to handle this a lot better (instant response). For reference, our job list contains 43 791 elements.
PTAL @Jammy-Louie
> fix(core): Build triggers: Properly render large number of jobs

- app/scripts/modules/core/src/reactShims/react.injector.ts
- app/scripts/modules/core/src/serverGroup/serverGroup.transformer.js
Making `clusterService` available (we use it in our internal build) to React; also fixing import order for performance, and removing an unused method in an entirely unrelated service
> refactor(core): expose clusterService in react injector

- app/scripts/modules/core/src/presentation/forms/inputs/ChecklistInput.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/WindowPicker.tsx
make checklist component more flexible by allowing the user to be able to specify a list of strings or a list of objects, similar to react-select
> refactor(core): allow checklist component to accept objects as a prop

- app/scripts/modules/core/src/manifest/stage/JobStageExecutionLogs.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
* fix(runJob/kubernetes): fix log display
fix a case where the log link was being displayed before all the data
needed to render it was available. this caused some confusing cases where
the link would be rendered but users would be met with a Not Found error in
the popup. ultimately this was due to a missing namespace. resolved by
pulling the namespace off of the job status instead of depending on the
manifest subscription.
* fix(runJob/kubernetes): fetch manifest once
jobs collect owned pods when collecting job status so we are no longer
dependent on subscribing to manifest events to get the pod names created by
the job. instead, simply fetch the manifest once. this is more reliable
than subscribing to manifest updates.
> fix(runJob/kubernetes): reliably display logs

- app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/ServerGroupInformationSection.tsx
If a server group is created by a pipeline, sometimes it would be nice to know which one did it. If a server group was created by a pipeline, the timestamp will now become a link to it.
> feature(cf): server group details creation timestamp links to pipeline

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
89e4e78505ed8760214389eea683ad929c7a5a9f fix(runJob/kubernetes): reliably display logs (#7060)
50f23fcca731ebbc3bf9a25805223632ea8a3364 refactor(core): allow checklist component to accept objects as a prop (#7058)
0eaae9a8e938a5ec3387ca471051417eda25cb61 refactor(core): expose clusterService in react injector (#7043)
8dd1417ed18557e2b37fceb820b6255bab4e1d1e fix(core): Build triggers: Properly render large number of jobs (#7056)
497523348967d2d8c84dc6f6a1c57b7ae895e1be fix(artifacts/helm): support regex/spel in version (#7033)
59259a91cee44f88d2559b2728a889919a635853 fix(docker): Fixed imageId parsing and digest support (#7053)
50f23fcca731ebbc3bf9a25805223632ea8a3364 refactor(core): allow checklist component to accept objects as a prop (#7058)
59259a91cee44f88d2559b2728a889919a635853 …
> Bump package core to 0.0.373 and docker to 0.0.41 and titus to 0.0.98

- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The V2 manual trigger endpoint only returned an event id, so deck had to poll for the appearance of a new trigger by polling on the event id.
Now that the endpoint also returns the execution id, we can poll on the execution id which should be significantly less expensive (for both orca and the redis/sql back-end).
> fix(triggers): Poll on execution id instead of event id

- app/scripts/modules/kubernetes/package.json
89e4e78505ed8760214389eea683ad929c7a5a9f fix(runJob/kubernetes): reliably display logs (#7060)
f0287a11ccf92ab902adb55de8664bcde43175bd fix(runJob/kubernetes): use explicit pod name (#7039)
3fd183ef3aa86808cc9cdb3b6ef09821acc8ac35 fix(kubernetes): fix runjob stage init (#7029)
4f4c32be1fef051a2299ecd7a90e2a1107bdc5cb feat(provider/kubernetes): namespace deployManifest (#7016)
8e97d5925b1cc1781d1651ae0acdc681175c3edb refactor(kubernetes): namespace selector component (#7012)
53cb42296a5dbbff15a96232ea4010d72b81ace2 refactor(kubernetes): convert deploy manifest stage to react (#7002)
0194821ef32b3d93e5a1df55ac5cb74200a34160 feat(runjob): capture output ui (#6978)
> chore(kubernetes): Bump version to 0.0.23

- app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
Moving deck over to maps so we can get quickly get rid of the lists (because it's not possible to represent a map as a list).
API already supports the map based constraints:
- currently returns both
- for operations, the `constraints` map (if present) will take precedence over the old lists, so we're safe to send only maps
- pipelines cluster configs will be transformed from lists to maps upon editing the cluster
> refactor(titus): Moving constraints from lists to maps

- app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
Background:
Currenly, it failed to run pipeline at WaitForUpInstance task and threw exception "Cannot cast object 'false' with class 'java.lang.Boolean' to class 'java.lang.Integer'". After investigated, I found the root cause is that orca will convert the capacity object to Map<String,Integer> but the azure code in deck would pass the property "useSourceCapacity" which is boolean value type under capacity object so that it failed. After checked, the property "useSourceCapacity" shouldn't be setted up under capacity object like other providers. And this property is unused in azure clouddriver.
Fix:
So I submitted this PR to remove the property "useSourceCapacity" from capacity object and add to outer layer of capacity under stage data.
> fix(provider/azure): Fail to run pipeline at WaitForUpInstance task

- app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.tsx
- app/scripts/modules/core/src/presentation/main.less
This PR changes the following things in `RadioButtonInput`:
- adds support for `inline` radio buttons.
- adds `stringOptions` prop instead of overloading `options` which previously took either an array of `Option` objects _or_ an array of `string`s (I'm open to feedback on this API change)
- switches from a `Set` of options to an array, so ordering can be applied.
I'd primarily like feedback from @anotherchrisberry  but he's OOO so I'm tagging Erik and Alan.
---
This PR also reverts tweaks to global bootstrap CSS that adjust margins and padding.
before: 
after:
---
Finally, this adds support for wrapping of inline checkboxes and radio buttons using a margin hack.  This puts the margin between successive elements on the *right* of the element instead of the left.  This is to support …
> feat(core/presentation): Support inline radio buttons

- app/scripts/modules/core/src/presentation/main.less
- app/scripts/modules/core/src/validation/ValidationMessage.tsx
```        <ValidationMessage message="The quick brown fox jumps over lazy dog" type="success" />```
This status is unstyled
```        <ValidationMessage message="The quick brown fox jumps over lazy dog" type="message" />```
This icon comes from the forms mockups greg comstock designed.  Note that we intend to style the `message` status further in the future, according to mockups.
```        <ValidationMessage message="The quick brown fox jumps over lazy dog" type="error" />```
```        <ValidationMessage message="The quick brown fox jumps over lazy dog" type="error" showIcon={false}/>```
> feat(core/presentation): Add "success" type to ValidationMessage

- app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
This has only been working when the auto-navigable thing was the last search result to return, I think, because we'll change the URL to the tab with the search results first, which loses the `route=true` query param.
> fix(core): fix auto-navigation on route=true searches

- app/scripts/modules/core/src/domain/IPipeline.ts
- app/scripts/modules/core/src/domain/ITrigger.ts
- app/scripts/modules/core/src/notification/notificationList.directive.html
- app/scripts/modules/core/src/pipeline/config/parameters/Parameter.tsx
- app/scripts/modules/core/src/pipeline/config/parameters/Parameters.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
- app/scripts/modules/core/src/pipeline/config/pipelineConfig.less
- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/configurePipelineTemplateModalV2.controller.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/configurePipelineTemplateModalV2.html
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.html
MPTv1 saved inherited items (notifications, triggers, parameters) directly to the pipeline config which allowed them to be displayed while configuring in deck. MPTv2 pipelines saved in spin do not save them to the pipeline config and instead rely on them being inherited during the plan phase. This PR renders items inherited from the plan and marks them as read only since they cannot be edited or deleted directly through the pipeline config.
https://github.com/spinnaker/spinnaker/issues/4451
Inherited Trigger
Inherited Notification
Inherited Parameter
> fix(core): Display template inherited items (mptv2) as read only

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts
- app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
Addresses https://github.com/spinnaker/spinnaker/issues/4510
- [perf] Removes unnecessary client-side alphabetization of image names: Clouddriver already alphabetizes image results [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/controllers/GoogleNamedImageLookupController.java#L118).
- [perf] Removes client-side filtration of images by account; adds account as image request parameter.
- [ux enhancement] Filters options by search text in image select dropdowns rather than only highlighting the matching text without actually removing non-matching options.
- [perf] Since we have already fetched all available account images to populate the persistent disk configuration, do not re-fetch images for Basic …
> perf(google): avoid unnecessary fetching and filtering of gce images

- test/functional/tests/google/clone.spec.ts.mountebank_fixture.json
- test/functional/tests/google/create_server_group_accelerator_zones.spec.ts.mountebank_fixture.json
[This change](https://github.com/spinnaker/deck/pull/7115/files) added the account param to outgoing GCE /find/images requests, causing Deck's functional testing suite to fail.
> fix(tests): change query param for gce deck functional tests

- app/scripts/modules/core/src/serverGroup/ServerGroupHeader.tsx
Only show one link. Prefer artifact to build. Use the Jenkins or Maven artifact icon.
> fix(artifact): use artifact icons in server group link

- app/scripts/modules/core/src/pipeline/config/stages/executionWindows/ExecutionWindows.tsx
Fixes a minor regression when viewing an existing pipeline stage without configured execution windows: if we add this default, it will dirty the stage and the user will be prompted to save changes, even if they haven't touched anything.
Simple solution is to default to an empty window when a user adds one.
Also fixing a bug where the graph is not updated when a user edits the stage via the "Edit as JSON" button.
> fix(core): do not inject default execution window values on render

- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
Historically, we let folks to a text search on the name, id, trigger, and stage context of an execution. Later we stopped actually loading in full stage context data for un-expanded executions to improve some performance problems, but that had the side effect of making context search pretty weird and seemingly non-deterministic from a user point of view (due to not knowing whether a value would be available or left out of search).
Two changes:
- Stop giving people weird experiences trying to guess what's searchable and what's not by no longer searching in stage context. This leaves name, id, and all the trigger fields. There's some help text about what you can search for that has been updated too
- Fix an _awesome_ bug with `parentExecution` fields on triggers: we were trying to stringify …
> fix(core/pipeline): stop searching stage context, being greedy about parentExecutions

- app/scripts/modules/core/src/presentation/forms/inputs/ChecklistInput.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/utils.ts
Also: mark `stringOptions` as `readonly` to allow read only arrays of options to be provided.
> feat(core/presentation): Always call onBlur in Checklist to "mark as touched"

- app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts
Worth digging into the backend, but we ran into an internal error that resulted in `"errors": [null]`, so we should filter those out and surface the `"error"` field, if it's present.
> fix(core): filter falsy error messages from errors object on tasks

- app/scripts/modules/core/src/pipeline/config/stages/pipeline/PipelineParametersExecutionDetails.tsx
React gets a little whiny about repeating nodes without keys.
> fix(core): provide key for repeating param JSX elements

- app/scripts/modules/openstack/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/openstack/src/serverGroup/serverGroup.transformer.js
The openstack clouddriver in Deck does not properly set the ID of a strategy pipeline when used as a custom step in a deploy pipeline.
This makes Orca fail the lookup of the strategy pipeline when executing the deployment. The pull request is aimed at properly setting the required attributes.
> fix(provider/openstack): Properly set the attributes of a strtegy pipeline

- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/FindArtifactFromExecutionExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionConfig.html
- app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
Closes https://github.com/spinnaker/spinnaker/issues/4354
Orca PR: https://github.com/spinnaker/orca/pull/3006
- Enables the selection of multiple artifacts in the Find Artifact from Execution stage.
- Makes minor UI changes to Find Artifact execution details tab.
Before:
After:
> feat(artifacts): find multiple artifacts from single execution

- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts
Add additional parameters to the monitored webhook to allow:
* waiting some number of seconds before polling starts
* retrying on specific HTTP status codes
see https://github.com/spinnaker/spinnaker/issues/3450
orca counterpart (https://github.com/spinnaker/orca/pull/2984)
> fix(webhooks): addresses issue 3450 - introduce a delay before polling webhook

- app/scripts/modules/core/src/domain/IPipelineTemplateV2.ts
- app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateReader.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
https://github.com/spinnaker/spinnaker/issues/4561
When templates are saved, they create 3 versions in front50. The first version represents the template addressed by id, the second version is the template addressed by the "latest" tag, and the third version is the template addressed by its content (digest). 
Displaying three versions in the UI was causing confusion as to which version was which. This change displays solely the `latest` version. The `latest` version allows a pipeline to automatically receive updates when a new version is published. Pinning to a version can be done through Spin CLI.
> fix(core): Display latest template in pipeline template list

- app/scripts/modules/core/src/domain/IExecutionStage.ts
- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.service.ts
- app/scripts/modules/core/src/pipeline/service/ExecutionsTransformer.ts
We've had a few requests over the years from users who want more control in the rendering of the pipeline graph. We work very hard to minimize a) the overlapping lines and b) the length of the lines.
Sometimes users want to override this. This PR provide that ability by adding another field to the stage JSON.
Not sure about the field name (does `graphRowOverride` make any sense) or about how to document this. I feel like it should be documented beyond "in the code" and "tribal knowledge". Feelings?
> feat(core): allow users to override pipeline graph positions

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
d5425b45b9692ccc989cacbde469343fd9919227 refactor(core): virtualize execution rendering (#7140)
342087cf996b2bcadb991e7086552b29509e7e4b feat(core): allow users to override pipeline graph positions (#7141)
fb58d70ddf8f14f2b2ca128505e6b255557ee583 fix(core): do not send a cloud provider on v2 search calls (#7142)
5d6d9aad3ee09afd70614aa821e48927a6920e50 chore(core): clarify clone stage help text (#7131)
745f0a16ac689209ff44fe2bc6839317476034a6 fix(core): Display latest template in pipeline template list (#7145)
456172b52d41fb7e014a8ac7344d9476687bbe27 fix(webhooks): addresses issue 3450 - introduce a delay before polling webhook (#7144)
7238d1de6ebef092c1c25d1851d9524593c63f8b feat(core): Enable new artifacts workflow in bakeManifest (#7138)
45e5aa348ab7138b3b2a078c457c218bc129869c …
> Bump package core to 0.0.377 and docker to 0.0.42 and amazon to 0.0.194

- app/scripts/modules/core/src/projects/ProjectHeader.tsx
This fixes `Cannot transition to abstract state 'home.project.application'`.
> fix(projects): Fixed project dashboard to application link

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.service.ts
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionPermalink.tsx
- app/scripts/modules/core/src/reactShims/state.events.ts
It looks like the `$stateChangeSuccess` event fires before the browser's location has been updated, so we're always behind a cycle when rendering the permalinks for executions.
Moved into a separate component because `<Execution>` is already pretty pretty big.
EDIT: I added a second commit to cut down on the re-render calls. What we are doing currently is kind of nuts and unnecessary and results in ~8 calls to `render` for each displayed execution every time a user clicks on a stage to toggle details or switch to a different execution.
> fix(core): properly update execution permalink on location change

- app/scripts/modules/amazon/package.json
f790fdf69c86146d0eca0a3f1648654c5fe2dcb6 fix(amazon): attach instanceId as id field on standalone instance details (#7156)
b53ac89ddebe0a73ee23c6c3f45764bea33dd418 feat(cfn/changesets): Introduce support for CFN changesets (#7071)
> chore(amazon): Bump version to 0.0.196

- app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
- app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionModal.tsx
- app/scripts/modules/core/src/modal/modals.less
These cards are used in three places and it's pretty obvious in hindsight that the last person to tweak them only looked at one of those places. I, on the other hand, considered all three, and also am a very good developer.
> fix(core): fix alignment on cards in card choices

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
973bd5c0d643f9437c17a512e95fb88307cb5444 fix(core/pipeline): When a pipeline or jenkins parameter is no longer accepted by the job/pipeline, show the parameter value (in addition to the name) in the warning message. (#7149)
8d929f06670e27055f488c282c13aa929578eccc fix(core): fix alignment on cards in card choices (#7158)
8d929f06670e27055f488c282c13aa929578eccc fix(core): fix alignment on cards in card choices (#7158)
> Bump package core to 0.0.379 and amazon to 0.0.197

- app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
- app/scripts/modules/amazon/src/instance/details/instanceDetails.html
- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
- app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.controller.ts
- app/scripts/modules/amazon/src/loadBalancer/details/targetGroupDetails.html
- app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
- app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.html
- app/scripts/modules/core/src/index.ts
- app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.less
- app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
- app/scripts/modules/core/src/managed/index.ts
- app/scripts/modules/core/src/managed/managedResourceDetailsIndicator.component.ts
- app/scripts/modules/core/src/serverGroup/details/ServerGroupDetails.tsx
The first PR for bringing [keel](http://github.com/spinnaker/keel) into the UI — this is a quick (largely experimental) attempt at indicating resources are managed. Currently applies to clusters, load balancers/target groups, and security groups.
Right now this is implemented via entity tags, but may change in the future. I'm not particularly tied to any of the specifics (including new directory structures, etc.).
>  feat(core/amazon): add a visual indicator to infra managed by Keel

- app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
Adding a hook point to include extra help text for docker tag selector - at Netflix, we have some additional info regarding how long we cache images, and would like to let users know about that limit.
> feat(docker): allow extra inline help on tag selector

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
2fd1aa97195cc1bf8c26447a3d144e6d6192021f  feat(core/amazon): add a visual indicator to infra managed by Keel (#7161)
e08e36f58edc81ee3143a08a57834bfd6c420d6f feat(docker): allow extra inline help on tag selector (#7143)
2fd1aa97195cc1bf8c26447a3d144e6d6192021f  feat(core/amazon): add a visual indicator to infra managed by Keel (#7161)
422be22d3a6563eeab280afc0c4b9176fe6d9705 fix(titus): allow security group in cluster config by name (#7160)
cdd6f2379859d3c2b13bac59aa470c08b391a865 chore(package): Just Update Prettier™
> Bump package core to 0.0.380 and docker to 0.0.43 and amazon to 0.0.198 and titus to 0.0.100

- app/scripts/modules/titus/src/pipeline/stages/runJob/TitusSecurityGroupPicker.tsx
Looks like this was also 99% there but using the wrong variable made mapping IDs to names then back to IDs in the new account/region not work.
> fix(runjob): Fixing security group matching by name

- app/scripts/modules/ecs/src/ecs.help.ts
- app/scripts/modules/ecs/src/ecs.module.ts
- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/serverGroupWizard.html
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/taskDefinition.html
Add support for deploying an ECS Task Definition as an artifact.
* Implements https://github.com/spinnaker/spinnaker/issues/4070
* Fixes https://github.com/spinnaker/spinnaker/issues/3341
This feature allows Task Definition attributes, including multiple containers, to be defined in an artifact (JSON file) and used in conjunction with pipeline images and other server group settings to deploy to ECS.
> feat(esc): Add support for task definition artifacts

- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionPermalink.tsx
Kinda derped this one by not handling the initial case where the details render right away on a hydrated execution.
> fix(core): correctly build permalinks for executions

- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
Currently, creating an ECS server group within the `deploy` stage of a pipeline results in server group creation happening immediately, but then it FAILS to join the pipeline (it's visible in the 'Clusters' screen but not within the `deploy` stage originally being edited). 
This is b/c the view state "mode" is not set when building a server group for a pipeline, resulting in "create" behavior vs. "editPipeline" behavior. 
This change sets the mode to "editPipeline", which adds the server group to the deploy stage being edited and executes creation on pipeline deployment (same behavior as when adding a server group to the stage via JSON).
> fix(ecs): Set viewState.mode when creating server group for pipeline

- app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/taskDefinition.html
Disables artifact selection when creating an ECS server group outside of a pipeline (since pipeline "expected artifacts" are needed for them to work).
> fix(ecs): Disable artifact selection outside of pipelines

- app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTriggerTemplate.tsx
If for some reason the build you're after is not found or not in the list.
> feat(trigger): Allow entry of explicit build number

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
51b8d2dab596db97ea9e6110cb6e2317ad97bb43 feat(trigger): Allow entry of explicit build number (#7176)
9eb04b48eb5d667f963e3496a23bbb7626047c8e fix(pipeline): Fixed stage config for faileventual (#7174)
40eb9394247966f51b1975bbbb069ebda8593a82 feat(core/task): UserVerification: Accept an 'account' prop. (#7173)
97c4aed44ea05672dcbdc2316cc857fb1f96c0dc refactor(core/serverGroup): Extract MinMaxDesiredChanges component (#7171)
97c4aed44ea05672dcbdc2316cc857fb1f96c0dc refactor(core/serverGroup): Extract MinMaxDesiredChanges component (#7171)
> Bump package core to 0.0.382 and amazon to 0.0.199

- app/scripts/modules/core/src/pipeline/pipeline.states.ts
... instead of having an abstract state
> fix(core/pipeline): Change 'pipelines' state to redirect to the default child 'executions'

- app/scripts/modules/core/src/domain/IExecution.ts
- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
Users are sometimes confused why their executions are "stuck" in `NOT_STARTED` state and it's usually because there is a `RUNNING` execution and the pipeline is configured with concurrent executions disabled (the default).
This change just explains it better when `limitConcurrent` is `true`. As a bonus, clicking `RUNNING` also links to executions filtered to running executions of the pipeline in question (there should only be one):
> fix(executions): Clarify why executions are NOT_STARTED

- app/scripts/modules/core/package.json
ecb2dd17aea1958e78089ed58f18a19ed502998f feat(gce): Support new artifact model for deploy SG (#7178)
c93b4d0130011aa6be927c3ce9760faf1a9e5890 fix(executions): Clarify why executions are NOT_STARTED (#7183)
1f3882b87a76d0e8db57d4172f7a62b65ae76d17 fix(core/pipeline): Change 'pipelines' state to redirect to the default child 'executions' ... instead of having an abstract state
> chore(core): Bump version to 0.0.384

- app/scripts/modules/core/src/pipeline/config/stages/common/ExecutionBarLabel.tsx
- app/scripts/modules/core/src/pipeline/config/stages/concourse/concourseStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/applyEntityTagsStage.ts
- app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/evaluateVariablesStage.ts
- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/core/src/presentation/HoverablePopover.tsx
You know the annoying thing where you hover over a stage and you get a loading indicator in a tooltip, and then it just goes away, and you have to mouse out and then back over the stage to see the label? This fixes that.
> fix(core): fix flickering render of stage labels on hydration

- app/scripts/modules/core/src/pipeline/config/stages/overrideTimeout/OverrideTimeout.tsx
This is one of those cases where, when converting from Angular to React, we tried to follow the original Angular code a little too closely.
I split the single method (`setOverrideValues`) into separate methods: one to handle stage config changing (user selects a different stage or sets a timeout value), another to handle the user toggling the checkbox to override the default timeout.
I think it's a little cleaner and easier to read, and it works on existing stages with overrides.
> fix(core): fix overrideTimeout behavior on existing stages

- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The canary transformer causes grief, because it filters out deploy stages _when the execution is hydrated_.
> fix(core): consider stage count when hydrating executions

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/service/ExecutionsTransformer.ts
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
The `graphStatusHash` is pretty cheap to calculate (especially cheap compared to everything else we do in the transformer) and pretty important for knowing whether to update anything in the pipeline graph. So...let's make sure we set it.
The scroll tracking we're doing right now doesn't really work, it turns out, because `deltaX` only represents the difference in the X position between wheel events. It's usually a very small number, and can be negative. It had worked historically because, well, because the graph never updated and people didn't seem to notice.
> fix(core): correctly compute pipeline graph scroll position

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
5d2f3075ea15472e5bdc163515934ad35f753055 fix(core): correctly compute pipeline graph scroll position (#7198)
829da5a98886a6c5d2cb17cbddcca20c75b118c0 feat(amazon): allow custom help message on scaling policy selection modal (#7199)
7a218bc8d1e54037f9dfd5fd81b9d6d6af3b010f fix(amazon): Disallow enable instance in a disabled server group (#7197)
> Bump package core to 0.0.388 and amazon to 0.0.201

- app/scripts/modules/core/src/pipeline/index.ts
We use this thing internally. Well, we used to use `executionService.transformExecution` but I refactored that out, since it was just delegating to the same method in ExecutionsTransformer, so here we are.
> refactor(core): export ExecutionsTransformer in core module

- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
When a user tries to re-run an execution, `command.trigger` is set to the trigger of the execution being re-run, however since Angular's `select` is checking for referential equality, it doesn't match anything in the list of options (`pipeline.trigger`) so the user is left with an empty select.
This fix attempts to match the execution to a `pipeline.trigger`(already copied into `this.triggers`) then hydrates it with everything from the trigger of the execution (so that other things like buildNumber do not get reset).
> fix(executions): Correctly populate trigger when rerunning an execution

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
768c2109ab2d5ddb98a1d521fb74b5e508a3ee07 fix(executions): Correctly populate trigger when rerunning an execution (#7205)
f340b0268c1c85aae96c54acee77aa39ef9770d6 feat(google): support stateful MIG operations (#7196)
bf68118738ed4dcfd2f8c9e61f8247bcccba2918 refactor(amazon): allow custom CLB config when ejecting from a wizard (#7206)
a468de458f784bc3e23b340acf053871d2d35678 fix(spel): Fix exceptions when account is an expression (#7168)
> Bump package core to 0.0.390 and amazon to 0.0.202 and titus to 0.0.104
