- app/scripts/modules/core/src/utils/index.ts
> feat(core): export worker pool class

- app/scripts/modules/core/package.json
49fc1cc0af8e3a80bd7cd36632b35fd7c5779e30 feat(core): export worker pool class (#6093)
> chore(core): Bump version to 0.0.296

- app/scripts/modules/core/src/entityTag/notifications/EntityNotifications.tsx
- app/scripts/modules/core/src/entityTag/notifications/EphemeralPopover.tsx
- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
> fix(core/executions): Fix NPE in ExecutionGroup->Notifications when there is a Strategy visible

- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts
- app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.html
> feat(webhook): add artifact status tab to webhook stage execution details

- app/scripts/modules/core/src/task/tasks.html
We could do a lot more work to fix this, but this view is kinda trash already and let's not get carried away trying to make it less trash.
> fix(core): fix copy-to-clipboard on deep-linked tasks

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
Before: Sometimes a user would see parallel Kubernetes deployments merged into a single set of Deploy Statuses in a deployManifest execution. See the bug described in https://github.com/spinnaker/spinnaker/issues/3661
After: the bug is no longer reproducible.  Clicking on a deployment stage will only show the resources deployed as part of that stage.
> fix(kubernetes): fix manifest update race condition

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/ManifestDetailsLink.tsx
Before, clicking on a Namespace details link in an execution resulted in a broken-looking clusters screen:
After, clicking on a Namespace details link opens the unmapped kubernetes resource details view in the clusters screen:
> fix(kubernetes): namespace details links in executions dont work

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/amazon/src/subnet/subnetSelectField.component.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/react/DeployStatus.tsx
* Fix "component is changing an uncontrolled" on LB name
* Fix subnet without "purpose" showing blank in dropdown
* Fix cannot go back to EC2 classic
Should fix https://github.com/spinnaker/spinnaker/issues/3242
> fix(amazon/loadBalancer) Fixed load balancer with multiple accounts

- app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesExecutionDetails.tsx
By not replacing it with a dash.
> fix(stages/evaluateVariables): Make empty string less confusing

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/amazon/src/subnet/subnetSelectField.component.ts
This should fix spinnaker/spinnaker#3242 and is similar to #6108 with added fix to AvailabilityZoneSelector similar to #6074
Fix to release-1.11.x, similar to #6115
> fix(amazon/loadBalancer): Fix load balancer VPC selection

- app/scripts/modules/core/src/pipeline/config/triggers/cron/cronPicker.html
needs to be a number for the value to be properly set on load
> fix(core): correctly render value in CRON minutes select field

- app/scripts/modules/core/src/pipeline/config/stages/core/ExecutionStepDetails.tsx
In the "Task Details", when a task is running, the running step duration does not increment. This fixes it.
> fix(core): increment running task time in step details

- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.html
Something we'll implement in our custom build at Netflix...
> feat(core): allow custom stuck deploy instructions on deploy details

- app/scripts/modules/core/package.json
a06e1e83d9b3d5be3e8388eae283138046a913a1 fix(core/dataSources): make child sources always honor their parents' disabled state (#6134)
9c9a3cbbd17024fc176c7a98c9f6128b21988fce feat(core): allow custom stuck deploy instructions on deploy details (#6131)
e73b3d646a7a8b143b3d5ba1b76a2c2850630638 fix(core): increment running task time in step details (#6132)
adf29630a7776af9e0bede77abf8b2a9fc9fc1e2 fix(core): correctly render value in CRON minutes select field (#6133)
b8acb94463a8c81d20116ec76cf95188140d8acd feat(core): Support for setting application attributes from react (#6122)
> chore(core): Bump version to 0.0.298

- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
Very minor, but we should not render this component if artifacts are disabled.
> fix(core/artifacts): hide artifact list on trigger if artifacts disabled

- app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/cloudFoundryInfoDetailsSection.tsx
Add the option to provide the pcf metrics url for the server group
spinnaker/spinnaker#3664
> feat(provider/cf): add the metrics link to SG details

- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/ApplyEntityTagsExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/ApplyEntityTagsStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/TagEditor.less
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/TagEditor.tsx
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/applyEntityTagsStage.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
The stage already exists, just adding a simple UI for it. Could definitely use some love, but it's functional for now.
@gcomstock FYI
> feat(core/pipelines): Add an apply entity tags stage

- app/scripts/modules/core/package.json
e6cb682e8e6bf2df545373fcd74ba564a92ee5ce feat(core): Export FormikApplicationsPicker for reuse (#6156)
> chore(core): Bump version to 0.0.300

- app/scripts/modules/core/package.json
4082b9266e6d24bd3ab4450bbaf2cb373b7354a2 refactor(core): remove ON_DEMAND_THRESHOLD from cluster service, use settings
> chore(core): Bump version to 0.0.301

- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.ts
Handling of `defaultValue`s for parameters, and also adding the parameters and their values in execution details (if available).
> feat(runJob): Stage config defaults, execution details for preconfigured

- halconfig/settings.js
> chore(provider/cf): re-add cf to halconfig

- app/scripts/modules/core/src/application/config/appConfig.states.ts
- app/scripts/modules/core/src/application/config/applicationConfig.view.html
- app/scripts/modules/core/src/presentation/navigation/pageNavigator.component.spec.ts
- app/scripts/modules/core/src/presentation/navigation/pageNavigator.component.ts
Allows links to specific sections of the app config, e.g. http://spinlocal.mgmt.netflix.net:9000/#/applications/deck/config?section=traffic-guards
> feat(core): allow deep linking to app config sections

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
There's not much difference between strategies and regular pipelines. But there is one big difference! You can't reorder strategies.
We can fix that on the backend, but since we haven't done that yet, let's just split out the pipelines and strategies into their own sections in the filters. This will prevent some confusion and frustration when users try to reorder pipelines and the strategies just... don't move.
> feat(core): differentiate pipelines and strategies in filters

- app/scripts/modules/amazon/src/serverGroup/configure/AmazonImageSelectInput.tsx
It's confusing to find the most recent image when you are cloning an AWS server group.
We can provide the creation date and some sorting options in the dropdown menu to pick images:
_current_
_PR_
> feat(aws): allow sorting of image options in server group modal

- app/scripts/modules/docker/package.json
b8c37a30fabb3adc11c2c0267501d1ceb4c9ebdc feat(docker): Support inputting image id directly
55dcd61bc862b1c1a250a9402d9203bc81738a4f fix(docker): Allow image id to be an expression (#6181)
> chore(docker): Bump version to 0.0.26

- app/scripts/modules/core/package.json
18d9e696c6afe24c07ddef2555873188a7d1a4db fix(core): Allow auto removal of pipelines when applications are removed (#6185)
> chore(core): Bump version to 0.0.303

- app/index.deck
Looks like we missed a `)` in https://github.com/spinnaker/deck/pull/6177/commits
> fix(core): add missing parenthesis

- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
- app/scripts/modules/core/src/pipeline/config/services/PiplineConfigService.spec.ts
See https://github.com/spinnaker/spinnaker/issues/1999
> fix(core): encode pipeline names in API request paths

- app/scripts/modules/cloudfoundry/src/loadBalancer/loadBalancer.transformer.ts
> fix(provider/cf): show SG and Instance info with LoadBalancers

- app/scripts/modules/core/src/cluster/filter/ClusterFilterModel.ts
- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.spec.ts
- app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
- app/scripts/modules/core/src/cluster/filter/LabelFilter.less
- app/scripts/modules/core/src/cluster/filter/LabelFilter.spec.tsx
- app/scripts/modules/core/src/cluster/filter/LabelFilter.tsx
- app/scripts/modules/core/src/cluster/filter/clusterFilter.component.html
- app/scripts/modules/core/src/cluster/filter/clusterFilter.component.ts
- app/scripts/modules/core/src/cluster/filter/labelFilter.component.ts
- app/scripts/modules/core/src/cluster/filter/labelFilterUtils.spec.ts
- app/scripts/modules/core/src/cluster/filter/labelFilterUtils.ts
- app/scripts/modules/core/src/core.module.ts
- app/scripts/modules/core/src/filterModel/IFilterModel.ts
Closes https://github.com/spinnaker/spinnaker/issues/3238:
> feat(core): add label filter UI to clusters view

- app/scripts/modules/core/src/presentation/main.less
ui-view main container where our contents (other than the header) is placed is now positioned "relative".
This is important as we move towards using CSS grids for the page layout. Using position: relative makes it easy to add content thats not layering one another. A netflix specific example of this is our blesk notifications.
> style(core): Making the main ui-view container positive relative

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
> Bump package core to 0.0.305 and amazon to 0.0.148 and titus to 0.0.65

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …
> Bump package core to 0.0.306 and docker to 0.0.28

- app/scripts/modules/core/src/reactShims/react.injector.ts
> feat(core): add InstanceWriter to CoreReactInject

- app/scripts/modules/core/package.json
a69f817793d0da82a0440d781fb7eaf86d6a0434 feat(core): add InstanceWriter to CoreReactInject
a5a2c78a154ac60bb6c5f0d6325a79c2ade556a3 feat(artifacts): Add HTTP to artifact icon list and service (#6333)
0c7d2f0d15f06d9fb4b7d22190a5f6121f41f100 feat(core/serverGroup): Add digests to docker insight server group link (#6327)
> chore(core): Bump version to 0.0.307

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
are you not entertained @spinnakerbot
> Bump package core to 0.0.308 and amazon to 0.0.149

- app/scripts/modules/core/src/notification/notification.details.filter.js
- app/scripts/modules/core/src/notification/types/pubsub/additionalFields.html
tag: https://github.com/spinnaker/spinnaker/issues/2784
Nobody should be using this feature yet, so there should be no risk of breakages
> fix(pubsub): Change from topic to publisherName

- app/scripts/modules/titus/package.json
6a1bc8de468163c4a4cdbaf9fa25b9af26356e97 feat(titus/runJob): Add support for env attrs and container attrs (#6377)
a931df26ef2e371a0630e6c2cd2661f07d9d9629 feat(aws/titus): warn on scaling policy creation if min/max are identical (#6366)
> chore(titus): Bump version to 0.0.67

- app/scripts/modules/core/src/deploymentStrategy/strategies/PipelineSelector.tsx
If a pipeline cluster is using a custom strategy from another application, we overwrite that value when we initialize the cluster config modal. Let's not do that!
Also let's add some spinner while the applications are loading because it looks a little nicer.
> fix(core): do not overwrite strategy app in cluster config

- app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts
- yarn.lock
Helpful when debugging an issue to see what the original capacity was...
> feat(core): include original capacity in server group resize title

- app/scripts/modules/core/package.json
2d8d20e314291b18c9aa2bf3ea282ac399cf7263 feat(core): include original capacity in server group resize title (#6352)
94fa5cb482669f4cf9445ed733d37d204b8c1cc1 fix(core): do not overwrite strategy app in cluster config (#6384)
795f1081ee241f1912232fe5217d4fa16b9effa5 fix(aws): filter out subnets with no purpose (#6383)
d6548d5f6e88ba80595faf85ef076e1d24d45e2d fix(stage): Fixing addAliasToConfig (#6381)
286d4ba44ed9fd1afcae447995ba5194e0c62b6a feat(core): Show timestamp in user's (browser's) timezone (#6362)
> chore(core): Bump version to 0.0.312

- app/scripts/modules/amazon/package.json
6e2a209d302e5fc5604a185b929e068224f21e9f refactor(aws): remove certificate loading from NLB modal (#6379)
> chore(amazon/): Bump version to 0.0.153

- test/functional/run.js
- test/functional/tests/appengine/pipelines_list.spec.ts
- test/functional/tests/core/applications_create_required_config_prevents_creation.spec.ts
- test/functional/tests/core/applications_create_required_config_prevents_creation.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_create_takes_user_to_infra_page.spec.ts
- test/functional/tests/core/applications_create_takes_user_to_infra_page.spec.ts.mountebank_fixture.json
- test/functional/tests/core/applications_list.spec.ts
- test/functional/tests/core/locators/HeaderNavLocators.ts
- test/functional/tests/core/locators/NewApplicationModalLocators.ts
- test/functional/tests/core/pages/ApplicationConfigPage.ts
- test/functional/tests/core/pages/ApplicationsListPage.ts
- test/functional/tests/core/pages/InfrastructurePage.ts
- test/functional/tests/core/pages/Page.ts
- test/functional/tools/TestRunner.ts
Add two functional tests:
1. Creating a new Application is prevented if required fields (name, email) are not populated.
2. Creating a new Application takes the user to the Infrastructure page for that application on success.
> feat(tests): Add functional tests for creating applications

- app/scripts/modules/amazon/src/certificates/AmazonCertificateReader.ts
- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/common/AmazonCertificateSelectField.tsx
In case someone wants to override the certificate select field...
> refactor(aws): move certificate selector to separate component

- app/scripts/modules/amazon/src/certificates/AmazonCertificateReader.ts
- app/scripts/modules/amazon/src/certificates/index.ts
- app/scripts/modules/amazon/src/domain/IAmazonCertificate.ts
- app/scripts/modules/amazon/src/domain/index.ts
- app/scripts/modules/amazon/src/index.ts
- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/common/AmazonCertificateSelectField.tsx
In case someone wants to use these in a custom build for something
> refactor(aws): export IAmazonCertificate

- app/scripts/modules/amazon/package.json
e0d19840f68f14c5490059b0df4aef7e9cd20681 refactor(aws): export IAmazonCertificate (#6397)
> chore(amazon): Bump version to 0.0.155

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/common/AmazonCertificateSelectField.tsx
- app/scripts/modules/amazon/src/loadBalancer/index.ts
It was the name of the account all along.
> refactor(aws): export cert field; rename cert field prop field

- app/scripts/modules/amazon/package.json
04b3ea53424b3be06649e747b2844c961fcc58bd refactor(aws): export cert field; rename cert field prop field (#6399)
> chore(amazon/): Bump version to 0.0.156

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> Bump package core to 0.0.314 and amazon to 0.0.157

- app/scripts/modules/core/package.json
e276fd5dbded891d08279e7e391e547280b34094 fix(webhooks): Various webhook stage improvements (#6407)
> chore(core): Bump version to 0.0.315

- app/scripts/modules/core/package.json
06089c82d16dfa3ef18ea57c0a8b630077876b12 fix(core): Fix stack filter on none (#6421)
be2fc98cd2a217d90ffd4f47c9ddf60fba8c63fd chore(uiSelect): Remove decorators for uiSelectMultiple which we no longer use, AFAICT
6926c897f72bbb476b5c064e76fa76a0c8b56708 refactor(core/forms): Save 19kb in deck bundle by not using 'util' package
> chore(core): Bump version to 0.0.316

- app/scripts/modules/core/src/filterModel/FilterModelService.ts
A lot of people might ask when this problem first surfaced and is this the right fix and those are fair questions.
> fix(core): fix filtering on no details in clusters view

- app/scripts/modules/core/src/bootstrap/appInit.ts
- package.json
I don't think this package `spin.js` is used.  @spinnaker/netflix-deck-reviewers anyone have any insight?
I searched for `.spin(` and got 0 results.
> chore(package): remove unused (hopefully) spin.js package

- app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.html
Depends on https://github.com/spinnaker/orca/pull/2598
(We can adjust behavior of the checkbox based on what we decide to do with the Orca PR)
> feat(core): allow disabling traffic guards

- app/scripts/modules/core/src/presentation/main.less
As per conversation in #6407 (https://github.com/spinnaker/deck/pull/6407#discussion_r250314195)
updating break-word style to be more pleasing to the eye
> fix(core): better word break

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
> Bump package core to 0.0.319 and docker to 0.0.31 and amazon to 0.0.159 and titus to 0.0.68

- app/scripts/modules/amazon/package.json
968f1672b1de00bab3711347bcf11b66a32174d3 fix(amazon/loadBalancer): Fix display of rule condition in alb config (#6437)
> chore(amazon): Bump version to 0.0.160

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestConfig.controller.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchOptionsForm.component.ts
Resolves https://github.com/spinnaker/spinnaker/issues/3810
> fix(kubernetes): post strategic patch body as object

- app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.html
- app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js
This PR enables expressions for the pipeline field in the pipeline stage.  It does not support expressions in pipeline parameters.
> fix(core/pipeline): Support expressions for pipeline name in the pipeline stage

- app/scripts/modules/core/package.json
4abd7d3745c77f01b2b04799d563f4de49ac8376 fix(core): do not edit live copy of pipeline configs (#6454)
ba8ac10b8e1f06400110a274f7806d6fb925439d fix(core): consider NOT_INITIALIZED as fetched when setting app status
> chore(core): Bump version to 0.0.321

- app/scripts/modules/core/package.json
0daebded57408e0537a56a46ae1c9fbb7a2b4315 feat(core): better handle stage removal (#6461)
1246086496255ea7be933380d5b7a7cd857598e2 fix(validation): Small fixes for validation (#6458)
> chore(core): Bump version to 0.0.322

- app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
> fix(aws): do not filter out security group ip ranges using wildcards

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
> Bump package core to 0.0.323 and amazon to 0.0.162 and titus to 0.0.69

- app/scripts/modules/publish.sh
@anotherchrisberry fyi
Paste your clipboard into the pr message and then squash/merge
> Copy changelog for all published modules to the clipboard for use in a PR comment

- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/ConfigBinModal.tsx
Realistically, this code should be in our internal build, but it's here in OSS land so that is where fixes go.
> fix(titus): use variable for account on configbin scaling metrics

- app/scripts/modules/amazon/package.json
b680b1ec86e4e7933790f9ab473d19d463ea795b fix(amazon): do not mutate nested objects on clone server group command (#6484)
> chore(amazon): Bump version to 0.0.164

- app/scripts/modules/amazon/tsconfig.json
- app/scripts/modules/appengine/tsconfig.json
- app/scripts/modules/cloudfoundry/tsconfig.json
- app/scripts/modules/core/src/bootstrap/uiRouterVisualizer.toggle.ts
- app/scripts/modules/core/src/cluster/allClusters.controller.js
- app/scripts/modules/core/src/core.module.ts
- app/scripts/modules/core/src/insight/insight.module.ts
- app/scripts/modules/core/src/insight/insightFilter.component.ts
- app/scripts/modules/core/src/insight/insightmenu.directive.ts
- app/scripts/modules/core/src/projects/projects.controller.js
- app/scripts/modules/core/tsconfig.json
- app/scripts/modules/docker/tsconfig.json
- app/scripts/modules/ecs/tsconfig.json
- app/scripts/modules/google/tsconfig.json
- app/scripts/modules/kubernetes/src/serverGroup/artifactExtractor.ts
- app/scripts/modules/kubernetes/src/v1/kubernetes.v1.module.ts
- app/scripts/modules/kubernetes/tsconfig.json
- app/scripts/modules/openstack/tsconfig.json
- app/scripts/modules/oracle/tsconfig.json
- app/scripts/modules/titus/tsconfig.json
- jsconfig.json
- package.json
- tsconfig.json
- yarn.lock
This PR replaces #6445
I think I've successfully shaved this yak.  I tested the OSS deck build and the netflix build and both seem to work fine.  Would appreciate a once-over from you folks, and then some testing on our local workstations and staging before I push this all the way to prod.
> System import is deprecated dont use it why are you still using it please stop

- app/scripts/modules/core/package.json
> chore(core): Bump version to 0.0.326

- app/scripts/modules/titus/package.json
7848f7aa6e3a71335caebbd6aa7eece2746a1285 fix(titus): Make iamProfile a required field in run job stage (#6487)
> chore(titus): Bump version to 0.0.72

- app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
changes to the WizardPage means we call validate on load
> fix(titus): do not call setState on wizard validation

- app/scripts/app.ts
why did this fix it i dont know
> fix(bootstrap): make sure jquery loads before angular

- app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/network/CreateNetworkLoadBalancer.tsx
Causes looping, also isn't actually needed.
> fix(amazon): do not call setState inside validate

- app/scripts/modules/amazon/package.json
e8979d040bb14978dc91afd04245bed9ff2cda15 chore(amazon): fix lint (#6510)
65162b397be1883b1f0069fe98f407474b226002 fix(amazon): do not call setState inside validate (#6509)
> chore(amazon): Bump version to 0.0.168

- app/scripts/modules/core/package.json
f7dc012e61178d66f43b7ca0eb698d689dacbed9 feat(core): add getApplicationAttributes method (#6512)
> chore(core): Bump version to 0.0.329

- app/scripts/modules/amazon/package.json
92f18eca7361eb725aa2f3db92b8bbe376519884 fix(amazon/loadBalancer): Fix NLB health check port validator (#6514)
> chore(amazon): Bump version to 0.0.169

- app/scripts/modules/core/src/config/settings.ts
- halconfig/settings.js
- settings.js
https://github.com/spinnaker/spinnaker/issues/3894
Adds a feature flag for Managed Pipeline Templates v2. Halyard changes to follow in separate PR.
> feat(core): add feature flag for managed pipeline templates v2

- app/scripts/modules/canary/canary/canaryDeployment/canaryDeploymentExecutionDetails.controller.js
- app/scripts/modules/core/src/cluster/clusterSearchResultType.tsx
- app/scripts/modules/core/src/navigation/UrlBuilder.ts
- app/scripts/modules/core/src/navigation/UrlBuilderRegistry.ts
- app/scripts/modules/core/src/navigation/index.ts
- app/scripts/modules/core/src/pipeline/config/stages/cloneServerGroup/CloneServerGroupExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.spec.js
- app/scripts/modules/core/src/pipeline/service/execution.service.ts
- app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.controller.spec.js
- app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.directive.js
- app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.directive.spec.js
- app/scripts/modules/core/src/reactShims/react.injector.ts
- app/scripts/modules/core/src/registry/Registry.ts
- app/scripts/modules/core/src/search/infrastructure/SearchV2.tsx
- app/scripts/modules/core/src/search/infrastructure/infrastructureSearch.service.ts
- app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.component.ts
- app/scripts/modules/core/src/search/infrastructure/infrastructureSearchV2.service.ts
- app/scripts/modules/titus/src/pipeline/stages/cloneServerGroup/cloneServerGroupExecutionDetails.controller.js
Also de-angularizes InfrastructureSearchServiceV2
> refactor(core): de-angularize UrlBuilder

- yarn.lock
yarn.lock is not up to date with some of the recent version bumps; check it in to resolve this
> chore(core): Check in changes to yarn.lock

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
40bfc7922ab54bb43bcf34babc3a251362aef65b refactor(core): remove navigation from stage config details (#6528)
c23989b5c087ebd5d41256d5f0a1cbd04b2ad0ce feat(gremlin): Gremlin UI which takes API key input then fetches comm… (#6549)
ee7b9364da35ad1580a813b0e595ad47a4171d5b fix(aws): allow ingress creation from all accounts (#6543)
eb0374c47e5b0fef21507462c540bdd4db632201 refactor(core): de-angularize UrlBuilder (#6541)
b2912bffb6ff0608b296993bbaed7b45db0c144a fix(core): Match order of pipeline config nav items to page sections (#6546)
ee7b9364da35ad1580a813b0e595ad47a4171d5b fix(aws): allow ingress creation from all accounts (#6543)
eb0374c47e5b0fef21507462c540bdd4db632201 refactor(core): de-angularize UrlBuilder (#6541)
a8c174925f64045f70c11b2bfc11fe1fdd558660 chore(package): Just Update …
> Bump package core to 0.0.331 and amazon to 0.0.171 and titus to 0.0.74

- app/scripts/modules/cloudfoundry/src/cf.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/cloneServerGroup/CloudfoundryCloneServerGroupStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/cloneServerGroup/cloudfoundryCloneServerGroupStage.html
- app/scripts/modules/cloudfoundry/src/pipeline/stages/cloneServerGroup/cloudfoundryCloneServerGroupStage.module.ts
- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/FormikAccountRegionClusterSelector.tsx
- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/index.ts
- app/scripts/modules/cloudfoundry/src/presentation/widgets/index.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/index.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupConfigurationModel.cf.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/CreateServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings/ConstantArtifactSettings.cf.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/basicSettings/BasicSettings.cf.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/cloneSettings/CloneSettings.cf.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/index.ts
> feat(cf): add clone SG pipeline stage

- app/scripts/modules/amazon/src/loadBalancer/AmazonLoadBalancersTag.tsx
- app/scripts/modules/core/src/loadBalancer/LoadBalancersTag.tsx
Loadbalancer tags now have a loading spinner.
For applications with large number of clusters, the loadbalancers fetch takes a little while or times out some times. The lack of loaders during this scenario causes panic among engineers as to if they even have the loadbalancers attached or not. Added the spinner for both the default load balancer button and the amazon specific one.
> fix(core/amazon): Loadbalancer tags should have spinner to avoid panic

- app/scripts/modules/core/package.json
8430dfccc3b3e792da2f33bc5419c5f6116f14d1 refactor(core): move stages/core to stages/common (#6574)
> chore(core): Bump version to 0.0.335

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
> fix(cf): pipeline edit deploy server group

- app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js
- app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.html
- app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupIngress.html
- app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupProperties.html
- app/scripts/modules/amazon/src/securityGroup/configure/editSecurityGroup.html
Almost all the changes are prettier-based reformats. I will annotate actual code changes.
> fix(aws): prevent clone submit when ingress rule removal in not acked

- app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingPoliciesDetailsSection.tsx
- app/scripts/modules/amazon/src/serverGroup/index.ts
Need this for some Cloudwatch forwarding work we're doing internally.
> feat(aws): allow override of scaling policies section

- app/scripts/modules/azure/securityGroup/clone/cloneSecurityGroup.controller.js
- app/scripts/modules/azure/securityGroup/configure/CreateSecurityGroupCtrl.js
- app/scripts/modules/azure/securityGroup/configure/EditSecurityGroupCtrl.js
- app/scripts/modules/azure/securityGroup/securityGroup.write.service.js
- app/scripts/modules/core/src/securityGroup/SecurityGroupWriter.spec.ts
- app/scripts/modules/core/src/securityGroup/SecurityGroupWriter.ts
- app/scripts/modules/google/src/securityGroup/configure/ConfigSecurityGroupMixin.controller.js
- app/scripts/modules/google/src/securityGroup/configure/editSecurityGroup.controller.js
Add `securityGroupName` to the `upsertSecurityGroupTask` as per `orca` change
https://github.com/spinnaker/orca/pull/2668
> fix(securityGroups): User `securityGroupName` for upsertSecurityGroupTask

- app/scripts/modules/amazon/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/azure/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/core/src/notification/notificationList.directive.html
- app/scripts/modules/core/src/notification/types/bearychat/additionalFields.html
- app/scripts/modules/core/src/notification/types/email/additionalFields.html
- app/scripts/modules/core/src/notification/types/googlechat/additionalFields.html
- app/scripts/modules/core/src/notification/types/pubsub/additionalFields.html
- app/scripts/modules/core/src/pipeline/config/preconditions/types/clusterSize/additionalFields.html
- app/scripts/modules/core/src/pipeline/config/stages/bake/modal/addExtendedAttribute.html
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestConfig.html
- app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.html
- app/scripts/modules/core/src/pipeline/config/stages/travis/modal/addParameter.html
- app/scripts/modules/core/src/pipeline/config/stages/webhook/modal/addCustomHeader.html
- app/scripts/modules/core/src/pipeline/config/stages/wercker/modal/addParameter.html
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/pipelineTrigger.html
- app/scripts/modules/core/src/projects/dashboard/cluster/projectCluster.directive.html
- app/scripts/modules/core/src/serverGroup/details/scalingActivities/scalingActivities.html
- app/scripts/modules/core/src/task/tasks.html
- app/scripts/modules/docker/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/google/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/openstack/src/pipeline/stages/bake/bakeStage.html
Prettier now supports HTML.  It told me these things are invalid HTML.
> fix(html): Fix various invalid HTML

- app/scripts/modules/ecs/src/instance/details/instanceDetails.html
accidentally removed this chunk in this commit: 04bb4a01c2d988aab5b5b8ae6e3aadbc59214898
> fix(ecs/instance): restore accidentally deleted section in instance details

- app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx
IAM instance profile for existing run job stages will get a recommended value.
Recently, we made IAM instance profile mandatory for run job titus stages. There are some pipelines which have run job stages without IAM profile set. This led to some user errors. One of the users updated other settings, and our application set the default application specific IAM profile. This change was unintentional and led to errors since they relied on titus's default IAM profile. In order to avoid these errors, we show default iam profile as a placeholder for existing run job stages without iam profiles. For newer stages, we automatically set iam profile so users do not have to worry about it. 
Treatment for existing run job stages:
> fix(titus): Help users with iam profile setting

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
**Core:**
4f15b54 chore(core): yank out fastProperties formatters (#6619)
**Titus:**
67d6ecc feat(titus): Reordering properties file contents based on length (#6617)
> Bump package core to 0.0.340 and titus to 0.0.78

- app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.js
- app/scripts/modules/azure/serverGroup/configure/wizard/securityGroup/serverGroupSecurityGroupsSelector.directive.js
- app/scripts/modules/core/src/account/collapsibleAccountTag.directive.js
- app/scripts/modules/core/src/application/config/applicationAttributes.directive.js
- app/scripts/modules/core/src/application/config/applicationCacheManagement.directive.js
- app/scripts/modules/core/src/application/config/applicationNotifications.directive.js
- app/scripts/modules/core/src/application/config/deleteApplicationSection.directive.js
- app/scripts/modules/core/src/cloudProvider/providerSelection/providerSelector.directive.js
- app/scripts/modules/core/src/forms/autofocus/autofocus.directive.js
- app/scripts/modules/core/src/instance/details/console/consoleOutputLink.directive.js
- app/scripts/modules/core/src/modal/modalOverlay.directive.js
- app/scripts/modules/core/src/modal/wizard/v2modalWizard.component.ts
- app/scripts/modules/core/src/navigation/stateactive.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/cron/cron.validator.directive.js
- app/scripts/modules/core/src/presentation/sortToggle/sorttoggle.directive.js
- app/scripts/modules/core/src/securityGroup/securityGroup.directive.js
- app/scripts/modules/core/src/utils/infiniteScroll.directive.js
- app/scripts/modules/core/src/whatsNew/whatsNew.directive.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancers/elSevenOptions/elSevenOptionsGenerator.component.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/securityGroups/tagSelectorGenerator.component.js
- app/scripts/modules/kubernetes/src/v2/manifest/annotationCustomSections.component.ts
- app/scripts/modules/openstack/src/common/selectField.component.js
- app/scripts/modules/openstack/src/instance/osInstanceTypeSelectField.directive.js
One more round of angularjs strictdi changes
> chore(angularjs): Explicitly annotate directive controllers

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
Addresses https://github.com/spinnaker/spinnaker/issues/4005
> fix(google/auth): Only show authorized accounts during Server group creation

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
Cherry-pick of https://github.com/spinnaker/deck/pull/6625.
> fix(google): Only show authorized accounts during Server group creation.

- app/scripts/modules/oracle/src/pipeline/stages/bake/bakeStage.html
- app/scripts/modules/oracle/src/pipeline/stages/bake/ociBakeStage.js
back port the fix (https://github.com/spinnaker/deck/pull/6627) into Spinnaker 1.12 release so that additional packer variables can be passed in to Oracle bakery.
> fix(bake/oracle): Added extendedAttributes

- app/scripts/modules/core/package.json
6f4eb89b7653ce645f4eaefe97122fe879faa475 feature(core): allow custom tooltip, modal body on Cancel Execution (#6635)
042943e5b18a695a691dd7925f621a4b20dfa0c8 fix(chaos): do not let user save invalid chaos monkey config (#6629)
9ba734bc7bf745c8e874f83622b7da26f51187ab feat(core): Export Pipeline Template action with modal and command copy (#6595)
> chore(core): Bump version to 0.0.342

- app/scripts/modules/azure/instance/azureInstanceType.service.js
- app/scripts/modules/azure/instance/azureInstanceType.service.spec.js
- app/scripts/modules/azure/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/azure/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/azure/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
- app/scripts/modules/azure/serverGroup/configure/wizard/instanceType/instanceType.html
- app/scripts/modules/azure/serverGroup/configure/wizard/serverGroupWizard.html
- app/scripts/modules/azure/serverGroup/serverGroup.transformer.js
Add support for instance type in server group
> feat(provider/azure): Add support for instance type in server group

- app/scripts/modules/core/src/pipeline/config/stages/common/IStageConfigProps.ts
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
Will be needed in Deploy Pipeline and new CF deploy stages.
> feat(core): Add pipeline to IStageConfigProps

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
eacfe75944210fb41f1d857f2450fb9cc55f3a10 feat(core): Warning message about invalid job params (#6669)
a28f7aff2f8d614f3e7c236f383562bcf85ea9b1 fix(core): Surface invalid params for a pipeline stage (#6668)
e2b4d8e9371d5d2f1f9b60e2a592e10b47df73e2 refactor(*): remove unused local storage caches (#6665)
35e82ac05b29de5091bdcbc05d46ddaecad3131c feat(core): Add support for an Artifactory Trigger (#6664)
bc2bf43e2e07dbec2d9e1e457fd61435a1cef1c4 feat(jenkins): Add artifact status tab to Jenkins execution details (#6666)
e0bda863cf5bbd266e0cdbd941b9d02ade1db484 feat(artifacts): Re-use artifacts when re-running a pipeline (#6663)
29582dd47fc29b4048123be0484e13dc2f95ae4f feat(core): Filter v2 pipeline templates from create pipeline modal (#6660)
45678a1854b1f8d4066e3cc3565181ac3f272679 …
> Bump package core to 0.0.343 and amazon to 0.0.179 and titus to 0.0.79

- app/scripts/modules/core/package.json
7a49d8222e4b52dd067a82f40e29b5055167df59 fix(core): In baseProvider, fixed autoselection of React stage (#6673)
> chore(core): Bump version to 0.0.344

- app/scripts/modules/amazon/src/vpc/VpcReader.ts
This is probably better - just cache the initial fetch operation; otherwise, for large applications with lots of clusters, hoo boy.
> fix(aws): do not aggressively and endlessly fetch vpcs

- app/scripts/modules/core/src/pipeline/config/stages/baseProviderStage/baseProviderStage.js
Cherry-pick of https://github.com/spinnaker/deck/pull/6673
This is a considerably bigger diff because of an angular deps / formatting change that occurred in master.  Ignoring whitespace removes most of the churn.
> fix(core): In baseProvider, fixed autoselection of React stage (#6673)

- app/scripts/modules/core/src/pipeline/config/stages/producesArtifacts/ProducesArtifacts.tsx
- app/scripts/modules/core/src/pipeline/config/stages/stage.html
- app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.html
* Also exclude front50 from Stage produces artifacts creation.
>  fix(artifacts): Make artifacts and artifactsRewrite flags mutually exclusive

- app/scripts/modules/cloudfoundry/src/presentation/forms/inputs/FormikConfigField.tsx
- app/scripts/modules/cloudfoundry/src/presentation/forms/inputs/index.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/artifactSettings/ArtifactSettings.cf.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings/ConfigurationSettings.cf.tsx
- app/scripts/modules/core/src/artifact/react/StageArtifactSelector.tsx
> fix(cf): fix the alignment issue for artifacts in deploy SG

- app/scripts/modules/amazon/src/loadBalancer/configure/common/LoadBalancerLocation.tsx
- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/configurationSettings/ConfigurationSettings.cf.tsx
- app/scripts/modules/core/src/account/AccountSelectInput.spec.tsx
- app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/ApplyEntityTagsStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/entityTags/TagEditor.tsx
- app/scripts/modules/core/src/projects/configure/ProjectAttributes.tsx
- app/scripts/modules/core/src/region/RegionSelectField.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/selector/ManifestSelector.tsx
- app/scripts/modules/kubernetes/src/v2/manifest/wizard/BasicSettings.tsx
- app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
- package.json
- yarn.lock
update the version of formik to resolve performance issues 
https://github.com/jaredpalmer/formik/issues/342
> chore(core): upgrade the version to formik 1.4.1

- app/scripts/modules/cloudfoundry/src/pipeline/stages/resizeAsg/CloudfoundryResizeAsgStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/resize/CloudFoundryResizeServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/ServerGroupSizingSection.tsx
> fix(cf): provide meaningful labels in resize dialog

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CloudfoundryDeployServiceStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateServiceInstanceDirectInput.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateUserProvidedInput.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/ICloudFoundryServiceManifestSource.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.module.ts
- also repaired validators for required fields
- also converted CreateUserProvidedInput's handling of data to be consistent with CreateServiceInstanceDirectInput
spinnaker/spinnaker#4084
> feat(cf): Add Updatable Flag To Create Service

- app/scripts/modules/cloudfoundry/src/presentation/forms/serverGroup/Routes.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/mapLoadBalancers/CloudFoundryMapLoadBalancersModal.tsx
- spinnaker/spinnaker#4122
In the infrastructure view only allow for mapping of a single route
at a time for server groups.
> fix(cf): map single route at a time

- app/scripts/modules/core/src/pipeline/config/triggers/trigger.directive.js
- app/scripts/modules/core/src/pipeline/config/triggers/trigger.html
* Also fix removal of last use of artifact from a trigger constraint when there are other triggers with no artifacts.
> fix(artifacts): Fix trigger artifact feature conditionalization

- app/scripts/modules/cloudfoundry/src/pipeline/stages/shareService/cloudfoundryShareServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/unshareService/cloudfoundryUnshareServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/CloudfoundryShareServiceExecutionDetails.tsx
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/CloudfoundryUnshareServiceExecutionDetails.tsx
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/index.ts
Add shared to and unshare from regions to execution details
spinnaker/spinnaker#4135
> fix(cf): Share / unshare execution details

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
29b001b67abaaa0d401bf8e468bddb6d43502d91 fix({core,cloudfoundry}/deploy): better red/black, rolling red/black help text (#6699)
647e3312dafbad43d59f051ba93329c4e5647f3b perf(core): cache subnets in window session (#6717)
5b6f229dfab78b6d72a29e50e92a64bb4f0a6f41 refactor(core): use non-deprecated tasks endpoint for app tasks (#6721)
061a60c58c31dcf3b8c7bd475cb9dcaf88adb86c fix(triggers): Add timeout to polling on manual trigger (#6707)
40c5e091903ba90944cb488e035a3393df482189 fix(concourse): Fix concourse trigger config (#6715)
2ac15b2f7c3bdd2764c97383e671078b617d7afc fix(artifacts): Fix SpEL text input used in React components (#6712)
8c4104fa0804f149c31ec177f9e12616eeffc59f fix(trigger): Fix react trigger components don't receive prop updates (#6711) …
> Bump package core to 0.0.345 and amazon to 0.0.181 and titus to 0.0.80

- test/functional/tests/core/applications_create_takes_user_to_infra_page.spec.ts.mountebank_fixture.json
The endpoints we use to poll for task updates when a new application is being created recently changed. The app creation test fixture didn't include responses for these task endpoints and so the functional test failed.
> fix(tests): update app creation fixture after tasks endpoint changed

- app/scripts/modules/core/src/pipeline/config/actions/templateJson/ShowPipelineTemplateJsonModal.tsx
- app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx
https://github.com/spinnaker/spinnaker/issues/4156
> fix:(core): Replace copy icon with descriptive text in template modal

- test/functional/tests/core/manual_execution_smoke_test.spec.ts
- test/functional/tests/core/manual_execution_smoke_test.spec.ts.mountebank_fixture.json
- test/functional/tests/core/pages/ManualExecutionModalPage.ts
- test/functional/tests/core/pages/PipelinesListPage.ts
- test/functional/tools/MountebankService.ts
> feat(tests): Add functional test for manual execution link

- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
Filters on `name`, `description` and `owner` strings in the template metadata.
Fixes https://github.com/spinnaker/spinnaker/issues/3913
> feat(mptv2): add a search input to the mptv2 list

- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
Fixes spinnaker/spinnaker#4123
> fix(ecs): Fix name of health check grace period attribute

- app/scripts/modules/titus/src/index.ts
- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/index.ts
I need this, it's important to me.
> refactor(titus): export more config bin stuff

- app/scripts/modules/titus/package.json
fb6eeb4f2b4c10fc6aeabba25eaa4ffb21ceece0 refactor(titus): export more config bin stuff (#6759)
> chore(titus): Bump version to 0.0.82

- app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/configBin/ConfigBinModal.tsx
If I touch any of this code again, it's all moving to our internal build of Deck.
> style(titus): tweak styles for config bin modal

- app/scripts/modules/titus/package.json
5474d6278bb4762c73b138ff567ddbcb3df15ca5 style(titus): tweak styles for config bin modal (#6762)
> chore(titus): Bump version to 0.0.83

- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
> fix(titus): remove metricOptions field

- app/scripts/modules/titus/package.json
e6a305e7c922f481f9cd14ddce6c14b707659ed3 fix(titus): remove metricOptions field (#6768)
c64a876822532cd791d5672442df1fc419073a85 refactor(titus): remove config bin code (#6767)
> chore(titus): Bump version to 0.0.84

- app/scripts/modules/titus/package.json
4b8e48dd65dc60e0cfbd11a2ee7567b6d58302e6 fix(titus): send cloudProvider as a string to ConfigBinLink (#6770)
> chore(titus): Bump version to 0.0.85

- app/scripts/modules/core/src/chaosMonkey/chaosMonkeyNewApplicationConfig.component.ts
- app/scripts/modules/core/src/config/settings.ts
- halconfig/settings.js
- settings.js
Closes https://github.com/spinnaker/spinnaker/issues/4095
> fix(core): make chaos monkey opt-in for new apps

- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
> fix(lint): Fix lint in pipeline templates list

- app/scripts/modules/core/package.json
8b1e5bf48a9d07007408d3eed9e355f6180857fb fix(core/pagerDuty): give appropriate app to PagerDutyWriter (#6789)
8422d6a2312ff08577fdcdbc74c49e107b2b06b2 fix(pipeline): Fix target impedance validator for clone server group (#6785)
ce12338f0d90925321a71299099bad162480fce8 fix(artifacts): Persist default artifact account in ExpectedArtifactModal (#6783)
3519f6f9e7d479c19755e2e40f46f323b0a82cf3 fix(lint): Fix lint in pipeline templates list (#6782)
36b86da691b44174a69984b06036c40e4900ad49 feat(templates): add Save button to export pipeline json modal (#6761)
50b74f2d0db86b15b66fd7a9a4985d0efb8fdb4b feat(gcb): add Google Cloud Build stage (#6774)
> chore(core): Bump version to 0.0.349

- app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateWriter.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/DeletePipelineTemplateV2Modal.less
- app/scripts/modules/core/src/pipeline/config/templates/v2/DeletePipelineTemplateV2Modal.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.less
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
> feat(mptv2): Add delete button & confirm modal to pipeline template list

- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.controller.ts
- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
NLBs don't have security groups.
> fix(amazon): hide security groups on NLBs

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
72e164dfcf11afbac559195a8fa6a91dd77ad2b9 refactor(core): de-angularize ApplicationModelBuilder, fix project executions (#6802)
cc053391ad7d11725066f8b25dcbe1853e4120cd fix(triggers): Add lastSuccessfulBuild as a build option in Jenkins default artifact (#6797)
daf72c4c0076af68d4d85720b3efc99454ba2f8f feat(mptv2): Add delete button & confirm modal to pipeline templates list (#6792)
06a7556ca5c3e7d78a4fc629b90854fae391f193 fix(amazon): hide security groups on NLBs (#6803)
72e164dfcf11afbac559195a8fa6a91dd77ad2b9 refactor(core): de-angularize ApplicationModelBuilder, fix project executions (#6802)
> Bump package core to 0.0.350 and amazon to 0.0.184

- app/scripts/modules/core/src/serverGroup/configure/common/v2InstanceTypeSelector.component.ts
- app/scripts/modules/google/src/serverGroup/configure/wizard/loadBalancingPolicy/loadBalancingPolicySelector.component.ts
- fix(google): safe call of onTypeChanged in v2InstanceTypeSelector
- fix(google): safe lookup and set of namedPorts in loadBalancingPolicySelector
> fix(google): GCE create server group and load balancer fixes

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/HelmArtifactEditor.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/helm.artifact.ts
Fixes https://github.com/spinnaker/spinnaker/issues/4239
> fix(artifacts): default helm artifact editor is missing from pipeline registry

- app/scripts/modules/core/src/domain/IPipelineTemplateConfigV2.ts
- app/scripts/modules/core/src/domain/index.ts
- app/scripts/modules/core/src/pipeline/config/templates/PipelineTemplateReader.ts
- app/scripts/modules/core/src/pipeline/config/templates/v2/ApplicationSelector.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/CreatePipelineFromTemplate.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.less
- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
- app/scripts/modules/core/src/pipeline/config/templates/v2/pipelineTemplateV2.service.ts
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
- app/scripts/modules/core/src/pipeline/create/TemplateDescription.tsx
- app/scripts/modules/core/src/pipeline/create/index.ts
- app/scripts/modules/core/src/pipeline/index.ts
https://github.com/spinnaker/spinnaker/issues/3893
Adds support for creating a pipeline from a v2 template in the template list.
> feat(core): Create pipeline from v2 template list

- app/scripts/modules/cloudfoundry/src/cf.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceKey/CloudfoundryCreateServiceKeyExecutionDetails.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceKey/CloudfoundryCreateServiceKeyStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceKey/cloudfoundryCreateServiceKeyStage.module.ts
> feat(cf): Create Service Key pipeline stage

- .github/PULL_REQUEST_TEMPLATE.md
add some tips to improve pull requests
> chore(github): add some tips to improve pull requests

- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/CreateServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/wizard/sections/basicSettings/BasicSettings.cf.tsx
> feat(cf): add deployment strategy to clone SG

- app/scripts/modules/azure/serverGroup/details/rollback/rollbackServerGroup.controller.js
Background:
Simplify processed stages of rollback function.
> fix(provider/azure): Simplify processed stages of rollback function

- app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.ts
adds support for producing artifacts by preconfigured job stages
> feat(preconfiguredJobs): support produce artifacts

- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
Typescript sometimes lulls you into thinking you're doing something good but you're actually footgunning
> fix(titus): correctly set dirty field on command viewstate

- app/scripts/modules/azure/help/azure.help.ts
- app/scripts/modules/azure/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.html
- app/scripts/modules/azure/serverGroup/configure/wizard/zones/zoneSelector.directive.html
- app/scripts/modules/azure/serverGroup/configure/wizard/zones/zoneSelector.directive.js
Background:
Disabling Inbound NAT when Zones are enabled.
>  fix(provider/azure): Disabling Inbound NAT when Zones are enabled

- app/scripts/modules/amazon/package.json
384e780c7648667c91ab94337924ca86319ad8fd refactor(amazon): export load balancer choice modal, remove customization hook (#6859)
> chore(amazon): Bump version to 0.0.186

- app/scripts/modules/azure/loadBalancer/configure/createLoadBalancer.controller.js
- app/scripts/modules/azure/securityGroup/configure/CreateSecurityGroupCtrl.js
- app/scripts/modules/azure/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
> fix(azure): remove unused imports

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
// changelog would go here if the bad wifi I was using to publish hadn't gone out in the middle of it.
> Bump package

- app/scripts/modules/core/package.json
a5e205981c451a0bad5162477238a5380d4e0971 fix(core): make imports relative on AccountSelectInput, RegionSelectInput (#6877)
> chore(core): Bump version to 0.0.355

- app/scripts/modules/cloudfoundry/src/cf.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceKey/CloudfoundryDeleteServiceKeyStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceKey/cloudfoundryDeleteServiceKeyStage.module.ts
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/CloudfoundryServiceKeyExecutionDetails.tsx
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/index.ts
> feat(cf): Delete Service Key pipeline stage

- app/scripts/modules/cloudfoundry/src/deploymentStrategy/CloudFoundryDeploymentStrategySelector.tsx
- app/scripts/modules/cloudfoundry/src/deploymentStrategy/strategies/rollingredblack/AdditionalFields.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts
- app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupConfigurationModel.cf.ts
> feat(cf): Added support for rolling red black deployments

- app/scripts/modules/azure/serverGroup/details/rollback/RollbackServerGroupModal.tsx
@sbwsg , I've updated react code according by your feedback in PR( https://github.com/spinnaker/deck/pull/6896 ). Please help to review. Thanks.
> fix(provider/azure): improve react code for rollback function

- app/scripts/modules/ecs/src/ecs.help.ts
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
> feat(ecs): Configure tags

- app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.html
- app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html
Fixes https://github.com/spinnaker/spinnaker/issues/4350
> fix(core): filter pipeline param choices by search text

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
bd7bcceab36617c79bf0e3851ffd55c6adfcabf6 fix(core): use relative imports for ReactSelectInput (#6909)
e44f22ba6b39a975f0721106d0f2ffbf03e4091d fix(core): update stage failure component when JSON changes (#6889)
9454e34046282b3bd1471c00fc509d30c946bed9 fix(core): filter pipeline param choices by search text (#6903)
960048f772a3a14044b13429c4391486b58d18c2 fix(core): Restore config button on exec view and dropdown for mptv2 (#6894)
af5ba5ba15c4a750acaf3f8f02ee780d715a6a69 feat(cf): Create service key SpEL expression (#6828)
62c2b513c9a7cdfbaea5d23d7328153ad4084178 feat(cf): Reduce angular dependencies (#6893)
7fde1fad4f3e6663dc388fce45f380f9f0531a4f fix(core): Show all app selections when creating a pipeline from mptv2 (#6891)
90fb96c4bfbbb07b23c8c3072229e58aa6f68868 feat(core): UI for …
> Bump package core to 0.0.356 and docker to 0.0.38 and amazon to 0.0.187

- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/AccountRegionClusterSelector.spec.tsx
- app/scripts/modules/cloudfoundry/src/presentation/widgets/accountRegionClusterSelector/AccountRegionClusterSelector.tsx
> fix(cf): Allow deletion of non existing cluster

- app/scripts/modules/ecs/src/ecs.help.ts
- app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
> feat(ecs): Configuration for platform version & placement constraints

- app/scripts/modules/titus/package.json
d6d882cd6049ce97e661197acefdcdfd9fa13cbd refactor(titus): Allow customization of instance details (#6908)
> chore(titus): Bump version to 0.0.90

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/runJobStage.ts
enable run job manifest to produce artifacts
> feat(provider/kubernetes): run job manifest artifacts

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/HelmArtifactEditor.tsx
Now setting initial state.
https://github.com/spinnaker/spinnaker/issues/4349
> fix(helm): Fix Helm artifact editor (names state unset)

- app/scripts/modules/core/package.json
88c4cd299a2fd5ac8724fe43dcaa129a49aad6a0 feat(core): modify form CSS for help text, group headers (#6920)
81a7ce3de788fc5868aa006bd917b4848c77b8dd feat(core): add ChecklistInput form component (#6919)
89db6040ee9dc5adb90b9d358e2795bb7f984712 fix(core): Fixed exception while configuring strategies (#6918)
d9e7123e74a6d41a97c86619fba0563ca6989685 fix(helm): Fix Helm artifact editor (names state unset) (#6914)
> chore(core): Bump version to 0.0.357

- app/scripts/modules/core/src/presentation/forms/forms.less
- app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/PolicyOptions.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/RateOptions.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/WindowPicker.tsx
Job disruption budget config for Titus.
Technically open source but really for Netflix.
> feat(titus): job disruption budget UI

- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/RateOptions.tsx
> fix(titus): allow editing default policy options when toggling default

- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/DisruptionBudgetSection.tsx
> fix(titus): import TitusReactInjector from subdirectory

- app/scripts/modules/canary/canary/canaryStage.js
- app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionService.spec.ts
- app/scripts/modules/core/src/pipeline/config/stages/createLoadBalancer/createLoadBalancerStage.js
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
> fix(core): use new ProviderSelectionService everywhere

- app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseStageConfig.tsx
- app/scripts/modules/core/src/pipeline/config/stages/concourse/concourseStage.ts
- app/scripts/modules/core/src/pipeline/config/triggers/concourse/concourse.service.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
- app/scripts/modules/core/src/widgets/spelText/SpelAutocompleteService.ts
Explanation of the stage flow is available [here](https://docs.google.com/presentation/d/1bPDrPhiLnu7GX_hn5vClgLrArOijkvJibK1Kyrb5GIE/edit?usp=sharing).
> feat(stages): Add Concourse stage

- app/scripts/modules/kubernetes/package.json
1ada02195c197978e714126bf867121971ec7ccb feat(kubernetes): expose rendered helm template in execution details (#6943)
d122749348d196b8626225d8741e6cdcb6e714bd feat(runJob/kubernetes): render external link (#6930)
9e03e52fbaf480b5689e4e186b7f5928c976cf6f refactor(runJob/kubernetes): refactor exec details (#6924)
98ca0ff3b304fdd814fa85d9f407f8ebc7e81409 refactor(runJob/kubernetes): use joblogviewer (#6917)
6c5eed6f642b801fe3abfd8a2ad10627779e55f9 feat(provider/kubernetes): run job manifest artifacts (#6902)
cd8780cc39951f57daf7b37c0928195a775bf32c fix(kubernetes): fix discrepancy between orca deploy stage model and artifacts rewrite stage model
d44be0c068dd4bd53212b44f407f7c2be4d8c7ae fix(kubernetes): hide manifest artifact selector in text mode
bd94593d91f99259a0bff97776909d1572e0540f …
> chore(kubernetes): Bump version to 0.0.22

- app/scripts/modules/amazon/src/aws.module.ts
- app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/network/CreateNetworkLoadBalancer.tsx
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.module.ts
- app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
- app/scripts/modules/amazon/src/reactShims/aws.react.injector.ts
No need for this to be Angular
> refactor(amazon): de-angularize load balancer transformer

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/HelmArtifactEditor.tsx
issue: https://github.com/spinnaker/spinnaker/issues/4370
> fix(artifacts): Fix fetching helm artifact versions

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
0fc8946ac251424f25c83a26cd212a5de5117eb5 fix(core): request project pipeline configs just in time (#6980)
cfd7690aa49b61b0ff40b41af519cad0acda3b41 fix(core): include un-run pipelines when filtering by text (#6979)
10fbec5ef2622dce2e7522aff585db00c8afa732 fix(core): set graph label node height correctly (#6993)
0ed0ab63370ca15de33609d7ebdbf797b0d8829a fix(artifacts): Fix fetching helm artifact versions (#6995)
dfc84b1bcca8253e94f9eaa3bc46102ba3d4e538 refactor(core): add React Components for PageSection and PageNavigator (#6926)
ce8a1637505ddde40cacfea9ba8cc807c127bb8f fix(cf): add Artifactory link (#6994)
f7cb7ab8a4f27351af34a7a28e73e31567637b7e chore(core): remove hipchat notification module (#6884)
98c9327400b1144d5d2ab32ebedc7a8fa667a493 fix(*): Fix imports (#6991) …
> Bump package core to 0.0.365 and docker to 0.0.39

- app/scripts/modules/core/package.json
d805c185c3d299b14e9746ef522ea702a96cbedc fix(core): do not automatically inject parameterConfig on pipelines (#7009)
> chore(core): Bump version to 0.0.369

- app/scripts/modules/core/package.json
80af46840150dcbb0073b54edafb8562ade5261b fix(core/pipeline): fix type mismatch in pipeline trigger, broken webhook trigger (#7018)
53cb42296a5dbbff15a96232ea4010d72b81ace2 refactor(kubernetes): convert deploy manifest stage to react (#7002)
96ac95a3c0d269c9467397ad7331a01495e2e435 fix(artifacts): Artifacts are shown on pipeline execution when artifactsRewrite is enabled (#6973)
5b6ad2a3de2ccdd8df5b125c39b41851a21a42e3 fix(core): Hide "Run as user" when using managed service users (#7013)
> chore(core): Bump version to 0.0.370

- app/scripts/modules/core/src/pipeline/config/triggers/RunAsUser.tsx
> fix(core): allow clearing of run as user field in triggers

- app/scripts/modules/core/src/pipeline/config/triggers/BaseTrigger.tsx
wrong field; otherwise, pretty good stuff
> fix(core): set runAsUser field correctly on triggers

- package.json
- yarn.lock
No longer used now that @Jammy-Louie literally rebuilt the entire thing in React
> chore(core): remove angular-cron-gen from package.json

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CloudfoundryDeployServiceStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.module.ts
Expected artifacts weren't showing up in this selection:
> fix(cf): fix deploy service manifest artifact selection

- app/scripts/modules/amazon/src/pipeline/stages/cloneServerGroup/awsCloneServerGroupStage.js
- app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackStage.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/cloneServerGroup/cloudfoundryCloneServerGroupStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/createServiceKey/cloudfoundryCreateServiceKeyStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceKey/cloudfoundryDeleteServiceKeyStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/cloudfoundryDeployServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyAsg/cloudfoundryDestroyAsgStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/destroyService/cloudfoundryDestroyServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/disableAsg/cloudfoundryDisableAsgStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/enableAsg/cloudfoundryEnableAsgStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/mapLoadBalancers/cloudfoundryMapLoadBalancersStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/resizeAsg/cloudfoundryResizeAsgStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/rollbackCluster/cloudfoundryRollbackClusterStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/shareService/cloudfoundryShareServiceStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/unmapLoadBalancers/cloudfoundryUnmapLoadBalancersStage.module.ts
- app/scripts/modules/cloudfoundry/src/pipeline/stages/unshareService/cloudfoundryUnshareServiceStage.module.ts
- app/scripts/modules/core/src/domain/IStageTypeConfig.ts
- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
- app/scripts/modules/core/src/pipeline/service/ExecutionsTransformer.ts
- app/scripts/modules/ecs/src/pipeline/stages/cloneServerGroup/ecsCloneServerGroupStage.js
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deleteManifest/deleteManifestStage.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestStage.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/traffic/disableManifest.stage.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/traffic/enableManifest.stage.ts
- app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestStage.ts
- app/scripts/modules/titus/src/pipeline/stages/runJob/titusRunJobStage.ts
The accountExtractor signature was not really accurate - sometimes they return a single string, sometimes they return an array. It...should just return an array.
> refactor(*): make accountExtractor return an array of strings

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deployService/CreateUserProvidedInput.tsx
> fix(cf): Change CUPS label to Route Service URL

- app/scripts/modules/core/package.json
0686fd8a7450daa3ce02096c2cb0bda4fc799d06 fix(core): fix auto-navigation on route=true searches (#7092)
a3e678ed3314963883527b588b2b802a5da1d52b refactor(core): reactify pipelineRoles component (#7104)
> chore(core): Bump version to 0.0.375

- app/scripts/modules/core/src/pipeline/config/templates/v2/PipelineTemplatesV2.tsx
- app/scripts/modules/core/src/search/infrastructure/infrastructure.less
https://github.com/spinnaker/spinnaker/issues/4519
Previously, the table did not scroll and hid table entries.
> fix(core): Make template table list scrollable

- app/scripts/modules/azure/src/help/azure.help.ts
- app/scripts/modules/azure/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/azure/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/azure/src/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.html
- app/scripts/modules/azure/src/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.js
- app/scripts/modules/azure/src/serverGroup/serverGroup.transformer.js
Background:
Add a new feature to mount data disk to server group. Please also help to review the related clouddriver PR(https://github.com/spinnaker/clouddriver/pull/3788).
> feat(provider/azure): Enable data disk for server group

- app/scripts/modules/core/package.json
939d608e989c771b225dc2d69cec8a798065c218 fix(pipeline): fix invisible parameter when default is not in options (#7125)
5c4facbddf8f44e6ed78b9f4776397b551c5c3c4 fix(core/pipeline): stop searching stage context, being greedy about parentExecutions (#7127)
8fe74bc56b02baa985b4c71b95a0ea8c30a291f0 fix(core): do not inject default execution window values on render (#7122)
ee6fbe0a3b554437a62f284dc360488997204a6e fix(core/pipeline): use correct visibility default for stage durations (#7121)
c88234c6fcc5730b9e238d97dc85122af8c70c3d refactor(stages): Fixed alias matching, added fallback and unit tests (#7080)
c35880104520faf56736e0121e47e34a45b3e864 refactor(core): Reactify ExecutionWindows component (#7113)
744123debbe6d1615f1781a2f1b9f8e04ca04502 fix(artifact): use artifact icons in server …
> chore(core): Bump version to 0.0.376

- app/scripts/modules/core/src/cloudProvider/providerSelection/ProviderSelectionModal.tsx
- app/scripts/modules/core/src/modal/modals.less
Fixes most of https://github.com/spinnaker/spinnaker/issues/4543
> fix(core): do not stretch provider logos in selection modal

- app/scripts/modules/appengine/src/appengine.module.ts
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/ConfigFileArtifactList.tsx
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFileArtifactList.module.ts
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.html
- app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFiles.component.ts
- app/scripts/modules/appengine/src/serverGroup/transformer.ts
- app/scripts/modules/core/src/artifact/IArtifactAccountPair.ts
enable the new expected artifacts for config artifacts when deploying a new server group.
> feat(appengine): Enable new artifacts for config artifacts in deploy SG

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
058007eaaeadd1ea5f4b9e9ba119bd1b757869b0 fix(core): properly update execution permalink on location change (#7152)
9bd9624e9df2a009eaa85f80a246e1cd49cf308b fix(projects): Fixed project dashboard to application link (#7154)
d6ad8c252c596405cbd0344e82083b67579dec5d feat(appengine): Enable new artifacts for config artifacts in deploy SG (#7153)
a9a927b70917f4867a5d2882312671bc10d1d639 feat(appengine): Enable new artifacts workflow in deploy SG (#7147)
8ee7e118d2865e0629b7a18323a802eb086797ea fix(amazon): Fix SpEL support for load balancers (#7151)
> Bump package core to 0.0.378 and amazon to 0.0.195

- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
A minor optimization in most cases (to avoid re-fetching security groups every time), and otherwise just a way to allow users (generators, really) to reference security groups by name in cluster configurations in deploy stages.
This code was mostly lifted from the same section of the AWS configuration service.
> fix(titus): allow security group in cluster config by name

- app/scripts/modules/titus/package.json
cfe322c810af012025857c167fe8740852a5afb9 fix(runjob): Fixing security group matching by name (#7164)
> chore(titus): Bump version to 0.0.101

- app/scripts/modules/core/package.json
7d3b83a34ed8464462866f66dea57d699c317b47 fix(core): correctly build permalinks for executions (#7167)
ccf080aaf6fe6e887bdb4b71279a6aacf00782b4 fix(core/managed): add docs link to managed infra indicator (#7166)
d23ee1c8fddb7bfb72ca818fdb1f1fde3e9a877c refactor(core/presentation): Refactor FormField components using hooks (#7148)
> chore(core): Bump version to 0.0.381

- app/scripts/modules/kubernetes/src/help/kubernetes.help.ts
The file was moved in this PR https://github.com/kubernetes/community/pull/3145
> fix(core): Fix link to strategic merge patch docs 

- app/scripts/modules/core/package.json
7d2c4e1fd6f99098248281ffc572454e9a0ee7f1 fix(core): fix overrideTimeout behavior on existing stages (#7190)
e26f797774189c3e2c4ae55fd6289d9b7c4f88bf fix(core): fix flickering render of stage labels on hydration (#7181)
> chore(core): Bump version to 0.0.385

- app/scripts/modules/core/src/pipeline/config/stages/common/ExecutionBarLabel.tsx
Hydration occurs at sibling nodes of the graph, but occurs by mutating the execution itself, instead of replacing it altogether, state management is hard, comments help.
> fix(core): check stage label hydration status when mousing over

- app/scripts/modules/core/package.json
83b62db119d8af3363cca0834b8d59b0a1dba256 fix(core): check stage label hydration status when mousing over (#7192)
> chore(core): Bump version to 0.0.386

- app/scripts/modules/core/package.json
6ff736e28a54d41d57cd496c720b6871b112feb0 fix(core): consider stage count when hydrating executions (#7194)
> chore(core): Bump version to 0.0.387

- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
Was refactored away, re-refactoring it back in.
> fix(titus): fix resize from Server Group Actions menu

- app/scripts/modules/titus/package.json
1b1ff2c5d127cfa784730712fa6f95527a527dbd fix(titus): fix resize from Server Group Actions menu (#7201)
> chore(titus): Bump version to 0.0.103

- app/scripts/modules/core/package.json
fc6823f1f0f027384b3fe06658d32ebbe556d250 refactor(core): export ExecutionsTransformer in core module (#7203)
> chore(core): Bump version to 0.0.389

- app/scripts/modules/amazon/src/loadBalancer/configure/classic/CreateClassicLoadBalancer.tsx
Did this for ALBs, never suspecting we'd need to do the same for CLBs.
> refactor(amazon): allow custom CLB config when ejecting from a wizard

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
> feat(core): Allow filtering PAUSED executions

- app/scripts/modules/core/src/pipeline/index.ts
Export pipeline stage execution details for use elsewhere
> Export PipelineStageExecutionDetails

- app/scripts/modules/core/package.json
d4d71bc33c483b4d87554df6288c66d5920b7dfb refactor(pipeline): Export PipelineStageExecutionDetails (#7230)
18a839b5d86e185f030533be2cd25f566019d6d7 fix(core): Render templated pipeline params in the pipeline run stage (#7228)
> chore(core): Bump version to 0.0.393

- app/scripts/modules/core/package.json
73d4f4cf9051aaca2ee3a01a31177e4bfe31145a fix(core): Changing switch to a map (#7236)
> chore(core): Bump version to 0.0.394

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
> fix(kubernetes): fix radio button alignment in deploy manifest stage

- app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
Also switch from tethered=true/false to mode='TETHERED' | 'VIRTUALIZED'
Also explicitly add 'children' prop to IFieldLayoutProps
Also fix reactSelectOnChangeAdapter to support `clearable`
> feat(core/presentation): Add virtualized support to ReactSelectInput

- app/scripts/modules/core/src/domain/IStageOrTriggerTypeConfig.ts
- app/scripts/modules/core/src/pipeline/config/triggers/BaseTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/RefreshableReactSelectInput.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/TriggerFieldLayout.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/artifactory/ArtifactoryTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/cron/CronTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/git/GitTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pipeline/PipelineTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/pubsub/PubsubTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/webhook/WebhookTrigger.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTrigger.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
This is the next step towards moving triggers to use Formik
> refactor(core/pipeline): Refactor most trigger to use <FormField/> components

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ConfigureOidcConfigModal.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/application/ConfigureRedirectConfigModal.tsx
- app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/presentation/pipeline/stages/CloudfoundryLoadBalancersStageConfig.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/mapLoadBalancers/CloudFoundryMapLoadBalancersModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/mapLoadBalancers/CloudFoundryUnmapLoadBalancersModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/resize/CloudFoundryResizeServerGroupModal.tsx
- app/scripts/modules/cloudfoundry/src/serverGroup/details/rollback/CloudFoundryRollbackServerGroupModal.tsx
- app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
- app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
- app/scripts/modules/core/src/notification/modal/EditNotificationModal.tsx
- app/scripts/modules/core/src/pipeline/config/stages/FormikStageConfig.tsx
- app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
- app/scripts/modules/core/src/presentation/forms/SpinFormik.tsx
- app/scripts/modules/core/src/presentation/forms/index.ts
- app/scripts/modules/core/src/task/modal/TaskMonitorModal.tsx
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/WindowPicker.tsx
- app/scripts/modules/titus/src/serverGroup/details/disruptionBudget/EditDisruptionBudgetModal.tsx
- app/scripts/modules/titus/src/serverGroup/details/resize/TitusResizeServerGroupModal.tsx
This is a drop-in replacement for the `<Formik/>` component
cc: @erikmunson @maggieneterval
> feat(core/presentation): Add a <Formik/> wrapper which applies fixes and opinions that we want in Spinnaker

- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
https://github.com/spinnaker/spinnaker/issues/4682
> fix(core): Prevent reloads when hitting enter in create pipeline modal

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/titus/package.json
d73fc997ebac87d8dc4643506d2f72c756103652 fix(core): Prevent reloads when hitting enter in create pipeline modal (#7277)
96e1b08e8e5d48c3ba46f4aa0ccc4c8e6326f27a feat(ui): add spinnaker version to UI, addresses #4383 (#7254)
592392f9bbbaba6b2a76e4cbaa10cb83fa887eed fix(core): remove the logic to initialize after props change (#7271)
d60b3bcf585a9d72970aeff4ebf6cd9bdc91fcde refactor(core/pipeline): Remove TriggerFieldLayout and BaseTrigger - Switch from TriggerFieldLayout to StandardFieldLayout - Switch to rendering Trigger description inside the dropdown
9c9faf4fbdd6249f7f075fe3c68690652d5f16c4 fix(core/presentation): StandardFieldLayout: add top margin, flex first element, render blank label - Add margin-top between fields - Flex-fill the first element in the input content area - Render …
> Bump package core to 0.0.396 and kubernetes to 0.0.28 and docker to 0.0.44 and appengine to 0.0.8 and amazon to 0.0.206 and titus to 0.0.106

- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
Plans mptv2 templated pipelines before showing the manual execution modal. Changes needed after the [manual execution modal change](https://github.com/spinnaker/deck/pull/7075).
https://github.com/spinnaker/spinnaker/issues/4686
> fix(core): plan templated pipelines when triggering manual exec

- test/functional/tests/core/pages/ManualExecutionModalPage.ts
fixed tests caused by https://github.com/spinnaker/deck/pull/7075
> fix(tests): fix tests for the refactored manual execution

- app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
The execution details (aka permalink) view did not have a button to re-run the execution. This was because the `<SingleExecutionDetails>` component was not passing in an `onRerun` prop.
This will pop up the manual execution modal from the single execution view, then transition upon submission.
> fix(execution): Adding rerun option to execution details view

- app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
Closes https://github.com/spinnaker/spinnaker/issues/4691
> fix(kubernetes): allow base64 manifests in deploy stage

- app/scripts/modules/ecs/src/placementStrategy/placementStrategy.service.ts
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html
> feat(ecs): Add CPU-binpack placement strategies

- app/scripts/modules/core/package.json
40c31972129a1c74f5087fb5a8a7a181b2144c33 refactor(core/presentation): use render props everywhere (#7316)
cef1c099e2bdbd6bdcb4db55179edd48afe992f3 fix(core/presentation): prevent the hover jitters on pipeline graph labels (#7311)
74ea2e7ef0cc71d03510fd5f7fb6ea8fa02af3dd fix(ui): require application, pipeline, and a status when adding a pipeline trigger (#7308)
f3de1671dbb57214b8b09816a541e99ca8d0e1a5 fix(ui): require type on the stage (#7304)
834f4eafc75ace3529f51c0bddd928efa05b7dd2 feat(helm): allow manual execution overrides for helm charts (#7312)
ea29d8d13417fed4ae6851717e6590d4e3fe0c92 fix(tasks): Not bothering with null user when we have an authed one (#7305)
> chore(core): Bump version to 0.0.398

- app/scripts/modules/amazon/package.json
- app/scripts/modules/titus/package.json
40c3197 refactor(core/presentation): use render props everywhere (#7316)
> Bump package amazon to 0.0.208 and titus to 0.0.108

- app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
Also do not repeat '* required' text
> fix(core/pipeline): make dropdown option labels always be strings

- app/scripts/modules/core/package.json
598b5b3d46393f262c10e067c5aa9a26280aa10d refactor(hooks): Pulling out useData (#7325)
0fbafe6f87dde6b2f9400a3d4999894a19f16f5b fix(core/pipeline): Refresh jenkins jobs component when manual execution trigger is changed (#7323)
12511594b582512dfd76efc2c6274a67fe775fff fix(core/pipeline): make dropdown option labels always be strings (#7322)
1e779ef9a01d32a2740680f413346226738e0e48 perf(core): avoid nested looping in execution transformation (#7217)
bec54dfa5f0b9c55b7fc8062cf47784f972a0107 refactor(core): Reactify the pipeline trigger configuration (#7318)
> chore(core): Bump version to 0.0.399

- app/scripts/modules/core/package.json
20109da7a0819dac957561a4af955614420b38b2 fix(pipelines): Correct text about cancelling (#7332)
7125c73048fbdd72f387cf4c4c15828baeb7adf9 fix(executions): Fixing execution marker ordering (#7331)
c39bf0ba07a1ed544a58fe452ab9891b3d3b5ab6 fix(artifacts): fix artifact account default logic (#7324)
> chore(core): Bump version to 0.0.401

- app/scripts/modules/core/package.json
7f0fdb4da0af985e0f9312fd6b510fdc5e574df8 fix(execution): Parameter names should be treated as strings (#7334)
> chore(core): Bump version to 0.0.402

- app/scripts/modules/core/package.json
593370e0556506721386f2bc433b411c6f0738f4 fix(core/forms): revert legacy MapEditor adapter to old component (#7340)
8361c0ad31d03e54aee82fb7e4e0cd75be9f4204 fix(core/pipeline): fix side menu rendering for trigger config (#7337)
> chore(core): Bump version to 0.0.403

- halconfig/settings.js
add the ability to turn on the artifacts rewrite through halyard.
depends on https://github.com/spinnaker/halyard/pull/1398
> feat(artifacts): add artifactsRewrite flag to halconfig

- app/scripts/modules/core/package.json
a7896bf406722141b2f2435d947940e5c2270d75 fix(notifications): Fixing custom message text shape (#7349)
8bdca89075a5f16f4f318f7fafe9980dfdf3956e  fix(core): fix vertical alignment of radio buttons (#7344)
d00f2a4b7de890c8e137a5509d2630b8e91b143e fix(artifacts): set the artifacts on trigger before the pipeline to sync problems with Angular (#7345)
b6ea1de57645430b9e739c42470a568959e40d74 fix(core): fix produces artifacts UI (#7343)
9812469a653d7302a6b006f7c1195416b5371469 feat(bakeManifest): add kustomize support (#7342)
> chore(core): Bump version to 0.0.404

- app/scripts/modules/core/src/pipeline/status/Artifact.tsx
- app/scripts/modules/core/src/pipeline/status/ResolvedArtifactList.tsx
fix display issues with artifacts for pipeline execution, spinnaker/spinnaker#4781
current:
fix:
> fix(core): pipeline execution was not displaying all resolvedArtifacts

- app/scripts/modules/core/src/pipeline/config/preconditions/modal/editPrecondition.controller.modal.js
- app/scripts/modules/core/src/pipeline/config/preconditions/modal/editPrecondition.html
- app/scripts/modules/core/src/pipeline/config/preconditions/preconditionList.directive.js
- app/scripts/modules/core/src/pipeline/config/preconditions/selector/preconditionSelector.directive.js
- app/scripts/modules/core/src/pipeline/config/preconditions/types/stageStatus/StageStatusPreconditionConfig.tsx
- app/scripts/modules/core/src/pipeline/config/preconditions/types/stageStatus/additionalFields.html
- app/scripts/modules/core/src/pipeline/config/preconditions/types/stageStatus/stageStatus.precondition.type.module.ts
- app/scripts/modules/core/src/pipeline/config/preconditions/types/stageStatus/stageStatusOptions.ts
- app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/checkPreconditionsStage.html
- app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/checkPreconditionsStage.ts
- app/scripts/modules/core/src/pipeline/pipeline.module.ts
UI for https://github.com/spinnaker/spinnaker/issues/4768 (Orca PR coming soon)
@louisjimenez I was kinda surprised that this took editing so many files to make work so let me know if you notice that I'm doing something dumb, I don't really remember how to use angular.
> feat(core): add stage status precondition type

- app/scripts/modules/core/src/pipeline/config/actions/lock/LockPipelineModal.tsx
Fixes eslint issues from https://github.com/spinnaker/deck/pull/7366
> fix(core): Fix shadowed var usage

- app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx
- app/scripts/modules/core/src/pipeline/executions/execution/execution.less
- app/scripts/modules/core/src/pipeline/status/ExecutionCancellationReason.tsx
- app/scripts/modules/core/src/pipeline/status/executionCancellationReason.less
Closes https://github.com/spinnaker/spinnaker/issues/4772
Before:
After:
> feat(core): improve readability of pipeline cancellation message

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
6a47557397866f2a611232fd0ae1667df0fef22f refactor(core): Reactify rename pipeline modal (#7368)
0d8864414b8ee2d225648302689a153e306eec37 feat(notifications): Add additional fields for Github and get config from halyard (#7239)
902c0b3defc6a196249944c7d210fe900bf50b55 refactor(core): use a fieldLayout for manualExecution (#7356)
9f5a860fba02f7db13e916b567ca2de9da0fc263 fix(core/pipeline): fix date picker for manual execution parameters where constraint == 'date'
744cf19f452de48f783554549755a7f5841c0e4b feat(core/presentation): Add DayPickerInput form input component
5a354b1df6a5f64f90a3f3b883ba89dfe7b993b5 feat(core): improve readability of pipeline cancellation message (#7369)
b88985763c8f28c8417f8bb1ac23273e5f1b4e40 fix(artifacts): fix uncaught undefined exception with artifacts (#7362) …
> Bump package core to 0.0.405 and titus to 0.0.109

- app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx
> refactor(amazon): choices prop is actually optional

- app/scripts/modules/amazon/package.json
c93f7e82327e1eabc1b0ff3bb644dddefd692999 refactor(amazon): choices prop is actually optional (#7379)
> chore(amazon): Bump version to 0.0.210

- app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx
Adds direct links to stderr and stdout links to the titus ui
> feat(titus): direct link to stdout and stderr in RUn Job stages

- app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts
> fix(core): Sanitize confirmation modal body

- app/scripts/modules/core/package.json
68cc18f fix(core): Sanitize confirmation modal body (#7407)
f8267a4 feat(core/managed): add Managed Resources section to app config, allow opting out (#7409)
> chore(core): Bump version to 0.0.410

- app/scripts/modules/core/src/pipeline/status/ExecutionStatus.tsx
> feat(core/pipeline): Add timestamp for failed executions

- app/scripts/modules/core/package.json
91e4c42d33caf4a944786cf1c356a2b6a251286e fix(tasks): (re)-enable durations on canceled tasks (#7433)
4d3454c87ec15fcd065af43766190ac114b3e30c fix(core/pipeline): migrate more manual execution field layouts
15de4a81bd594fd960757decbaf5e9cdb27a881a fix(core/forms): MapEditorInput: Add validation for empty keys and empty values. Remove `errors` prop in favor of using `validation.validationMessage` which is passed from FormField/FormikFormField
70dee3f22e486c976784a4b51865801747c9cc49 fix(core/pipeline): Don't break templated pipelines when updating config (#7428)
b942b5b5d3a9ce45255236ab2aa106fcbe91d37a fix(core/pipeline): Fix revert button regression for templated pipelines (#7427)
d7490f9dd63a1dda16d226ae3cd3c74c466a2db5 feat(core): rerun child pipelines with artifacts (#7422)
> chore(core): Bump version to 0.0.412

- app/scripts/modules/core/package.json
2b7b60c384e5d29454fa4553402960c6fe0d7701 fix(core/pipeline): Fixes UX of saving non-templated pipelines (#7437)
6ccc8cd1c5c20a5274c68c4123b06fdd91971796 feat(core/forms): Remove all async support from the spinnaker validation apis (#7435)
bfa0d1731cc34a4ef5f0cf3cc37466d303726d32 fix(pipeline): Fix NPE in stage requisiteStageRefIds (#7417)
a125b03c26f486e41651f490f8ed3aea270b18ea fix(core/pipeline): Fix execution details chevron for grouped stages (#7421)
> chore(core): Bump version to 0.0.413

- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
name is only a required field for manifest baked with helm so we should
only validate that it's supplied if the rendering engine is of type
HELM2.
> fix(bake/kustomize): fix name validation

- app/scripts/modules/core/src/presentation/forms/validation/FormValidator.ts
- app/scripts/modules/core/src/presentation/forms/validation/FormValidatorField.ts
- app/scripts/modules/core/src/presentation/forms/validation/index.ts
- app/scripts/modules/core/src/presentation/forms/validation/validation.spec.ts
- app/scripts/modules/core/src/presentation/forms/validation/validation.ts
Create a file for FormValidator and FormValidatorField.
Keep interfaces and helpers in validation.ts.
> refactor(core/validation): move FormValidator classes to separate files

- package.json
- yarn.lock
For changelog of each library, see dependabot-generated commit messages for each commit of this PR.
> chore(deps): consolidate dependabot-suggested security dependency bumps

- app/scripts/modules/core/package.json
57d28c9c0b15611b6b4aeceb37d17c47aab1e128 fix(core/task): properly cleanup TaskMonitor polling, fix digest thrashing (#7458)
564af8847915288f5db3c9baaafcee72bb0c13e7 feat(displayName): Adding display name property for the bakery baseOS options (#7464)
e0c57aff7768361fe0d1c0fa7777f0b07b54e0b9 fix(bakeManifest): fix bake manifest UI rendering (#7463)
f41d95544c563d8814ba4d6ce730162c21fd1c1d fix(core/infrastructure): Fix deep links with filters (#7459)
01bc0dae2b61aa03bd38d87958c462199517a53b fix(help text): update webhook help text (#7456)
53300b154ab526b057d197dca23033e75a735403 refactor(core/validation): move FormValidator classes to separate files (#7460)
1873094fa886f96ab29dac5b551123043a450c05 feat(core/utils): Add `traverseObject` which deeply walks object properties (#7452) …
> chore(core): Bump version to 0.0.414

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
b55a49a7337ff9db8f435be7437877adc1184b79 feat(monitored deploy): add basic monitored deploy UI (#7426)
5e255016aeac4bceae09fb152de5bf6be127ea54 fix(artifacts/bitbucket): Allow updates to bitbucket default artifact text input Allows updates to the artifact text input even when the regex pattern does not match the bitbucket cloud regex Create regex pattern for bitbucket server to match input against Fixes https://github.com/spinnaker/spinnaker/issues/4958
b55a49a7337ff9db8f435be7437877adc1184b79 feat(monitored deploy): add basic monitored deploy UI (#7426)
cfe9731f5a4977c12ee5f3e5d3f63263d943934c feat(aws): Add copy-to-clipboard button to copy instance id (#7388)
> Bump package core to 0.0.415 and amazon to 0.0.213

- app/scripts/modules/core/src/utils/json/traverseObject.spec.ts
- app/scripts/modules/core/src/utils/json/traverseObject.ts
This addresses [a comment](https://github.com/spinnaker/deck/pull/7452#pullrequestreview-294592678) @erikmunson had in #7452
> fix(core/utils): Support traversing keys which contain dots in them using array notation

- app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/BitbucketArtifactEditor.tsx
Fixes the help text to use the correct reference.
> fix(artifacts/bitbucket): Update the help key to the correct reference

- package.json
- yarn.lock
Updates to latest styleguide to get fresh CSS colors
> chore(package): update to "@spinnaker/styleguide": "^1.0.13"

- app/scripts/modules/core/package.json
a5f192e84c3294b40aabec5980dc6b122ea9c456 feat(core/presentation): Add helper functions for generating categorized validation messages (#7488)
7d91de697e9d653064924aa37fa577fb8926f06c fix(pipeline): triggers were not reverting in the ui (#7485)
5c3fcc749c307f642a50271c44532af344fda910 refactor(core/help): Migrate HelpContext to react hooks style (#7487)
3c08b388e6a00d4c9d14ad9babeb857e99d3d0e2 feat(core/presentation): Migrate ValidationMessage to new CSS styles (#7481)
523c6bb5bfdd5e95fd884321c4eec49023fa3b47 fix(triggers): fix a few minor issues with manual execution triggers (#7484)
0d0caa994f2fa70b75e8d6d62b28ef7fca8d2e8a fix(monitored deploy): properly initialize defaults (#7473)
dc2a74bbccf74e30d050f5c77309bc34d92c298c feat(core/presentation): Put margin between StandardFieldLayout's …
> chore(core): Bump version to 0.0.416

- app/scripts/modules/core/package.json
829c2951108404f434c325360e2771b97f18595b fix(core/pipeline): KLUDGE: use react 'key' to reinitialize formik when pipeline reverted
> chore(core): Bump version to 0.0.418

- app/scripts/modules/core/package.json
438d22cd77057028157bc03df1e5a358e0baf55f fix(ui): Add icon when target group registration in progress (#7502)
babbe889c25ef401668d716d24798cd0954ed922 refactor(application): reactify delete application section (#7501)
> chore(core): Bump version to 0.0.419

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
c18f307e555a07b0088fa72aab54e2ae48feae3a fix(core/presentation): fix null reference in ReactSelectInput (#7515)
075bce18b42af069d153bcaa6cbcb723a19964c6 feat(core/presentation): allow markdown in ValidationMessage
aef69cfc321a0a3569895d04e3c7548afee2c70d fix(core/presentation): Make all DOMPurify'd links open in a new window (#7511)
a0829090fb576a36c173dced5d15af8a68c6db84 fix(bakeManifest/helm): rawOverrides option (#7514)
752b1ab713b6ed478afb585b4844c71ecb0619a6 fix(deck): Show fail fast status code only if they are not pre-configured (#7512)
d03ce4848f37c09341474a0a2b79a778767b8e88 fix(core/pipeline): fix Artifactory and Nexus trigger NPE These were throwing upon initial mount because 'error' wasn't defined.
a9469e9723fb5b5e539ce5400e7a7077549b4245 refactor: Migrate user code to new …
> Bump package core to 0.0.420 and amazon to 0.0.215

- app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionField.tsx
> fix(core/presentation): Fix FormikExpressionInput initial state

- app/scripts/modules/core/package.json
088f50b290f143e71edcfe635f67ce25089f1c2d fix(core/presentation): Fix FormikExpressionInput initial state
> chore(core): Bump version to 0.0.422

- test/functional/tests/google/pages/CreateServerGroupModalPage.ts
> fix(google): replace missing character in functional test

- app/scripts/modules/core/src/projects/ProjectHeader.tsx
A member of the Kubernetes SIG [requested](https://docs.google.com/document/d/1db_yw1uru99Byvin4lQgm7aUZ9xMmvsARtEiiNUrmBo/edit?ts=5daf30c0#heading=h.ilm7rdxf4d42) that application names be alphabetized in the Project Dashboard header.
> feat(core): alphabetize applications in project config dropdown

- app/scripts/modules/core/src/config/settings.ts
- halconfig/settings.js
- settings.js
I believe this is unused.  However, it is configured by halyard.
> chore(settings): Remove unused feature toggle: 'jobs'

- app/scripts/modules/amazon/src/aws.settings.ts
- app/scripts/modules/core/src/config/settings.ts
- add pubsub in notifications
- add disableManualOidcDialog in amazon loadBalancers
> fix(config): Fix typings for SpinnakerSettings

- app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
This fix was first introduced in #5854, but went MIA when the manual execution modal was converted to React.
> fix(core/pipeline): Force rebake not displayed for templated pipelines

- app/scripts/modules/core/src/pipeline/config/stages/pipeline/PipelineStageExecutionDetails.tsx
Today, when a pipeline stage never starts or otherwise doesn't kick off an execution, the experience is... pretty bad. We not only show you a broken execution link, we also use the _execution name_ to show which pipeline the stage is configured to run, which means you get a blank value there too. This adds an indicator that there is no execution to link out to, and also looks up the actual name of the appropriate pipeline so that we can show it instead of nothing.
**Before:**
**After:**
> fix(core/pipeline): make UX less bad when a pipeline stage never happened

- app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
Turns out we've been using raw array index values to render the list of triggers in pipeline configs, [which is almost always bad](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318). The impact this has on us today is that when you delete a trigger that's not the last one in the list (and therefore shift the indices on the other array elements), React checks the index keys, sees they're the same as before, and leaves whatever HTML was sitting around for that index intact. Because of that, we _appear_ to delete a different trigger from the one you clicked delete on, even though under the hood we did the correct thing to the JSON.
The reason this is hard is because we don't have a good way to generate a stable key for a trigger object that doesn't change when …
> fix(core/pipeline): fully re-render list of trigger configs after a delete

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
d71daa55481e3ba1895b25831c26f01d9e981b53 fix(core/pipeline): fully re-render list of trigger configs after a delete (#7571)
629a98f62a9c8b12dad4337e34ef60b46ecfef4d fix(core/pipeline): make revision dropdown usable, layout tweaks (#7569)
ca176fc325edc41ee90d22b2c3d1aaa041a9c434 feat(provider/aws): Functions (listing and searching) (#7568)
e49ffaf4d5896294cf66300167aefdecbf36499c Revert "feat(provider/aws): Functions (listing and searching) (#7536)" (#7567)
114303aca9804c2300f2554a5702644b32d3f481 fix(kubernetes): disable project cluster filtration by stack/detail (#7562)
86a365bd406125498c1bbc45de2ee4d67f9fd0d5 feat(provider/aws): Functions (listing and searching) (#7536)
6236a9fdabf968954155ee3c75eeff99d98cfff3 fix(core/pipeline): make UX less bad when a pipeline stage never happened …
> Bump package core to 0.0.427 and docker to 0.0.48 and amazon to 0.0.220

- app/scripts/modules/cloudfoundry/src/loadBalancer/details/CloudFoundryLoadBalancerActions.tsx
- app/scripts/modules/cloudfoundry/src/loadBalancer/details/CloudFoundryLoadBalancerDetails.tsx
delete load balancer was not displaying.  should've used `ReactInjector.confirmationModalService` to display the modal
> fix(cf): delete lb confirmation not displaying

- app/scripts/modules/core/package.json
5acb0d07501d950f46bb715864fa00b0df4b7629 feat(managed): Add status popovers, new props for HoverablePopover
88b8e6c35d2374f1f4617588295624b029e34683 feat(managed): add resource status indicator to security groups
f02b70deb3bc8bc647bb75f2b408dd9b03893aa1 feat(managed): add managed resource data to security group groups
14283b2bdd095045c20aafd63ee8c680f8819585 feat(managed): add resource status indicator to load balancers
aaa349b4db4212acfb9a04b414a4807af9cdf889 feat(managed): add managed resource data to load balancer groups
a6d77563030ee30917a171db851a7a49e16459ac feat(managed): add resource status indicator to clusters
8453260ddbdf53a40b10a7c05076c0623e8a5a16 feat(managed): add managed resource data to cluster groups
167a1512fdc6bb2fefa0f47a1ce309e56392011e feat(dataSources): add runtime …
> chore(core): Bump version to 0.0.429

- app/scripts/modules/core/src/pipeline/config/stages/script/ScriptStageConfig.tsx
Seems that this was available at one point because the help text already exists.
> feat(script): expose propertiesFile field

- app/scripts/modules/core/package.json
822af5118046f9e0d9a30727ebe2fb540ce42ff8 feat(core/pipeline): Evaluate Variables: show message if no previous executions were found
804d2f9674010b935958c41027c274bda4e81616 feat(core/pipeline): Added execution/stage picker and some help text to the Evaluate Variables stage - add "column" labels to Evaluate Variables stage - add one variable by default when the component loads
554f32723d354bb32654633b1f5af0d80fb03c88 feat(core/pipeline): Added an ExecutionAndStagePicker component Used in Evaluate Variables to choose the stage to preview Spel Expressions against
5eef3e74e28c5b3789c6393bd9055725be46d2d6 feat(core/pipeline): Add spel preview to Evaluate Variables stage - Migrate EvaluateVariablesStageConfig from MapEditor to SpelInputs
> chore(core): Bump version to 0.0.431

- app/scripts/modules/core/package.json
e4b432dd71f8928bcc0386351e525737639c9952 fix(core/pipeline): Use markdown to render evaluated variables as JSON (#7628)
f93a2788caa861f3ab4a844c729eaa9ef4e7631d test(core/presentation): Re-add removed isInitialValid logic (#7627)
956b43bc05e1bbe471c60cacb994d460af6f74df feat(provider/aws): Function create/update/delete feature. (#7586)
> chore(core): Bump version to 0.0.432

- app/scripts/modules/amazon/src/aws.validators.ts
- app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/cloudFormationTemplateEntry.component.ts
- app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackConfig.controller.ts
- app/scripts/modules/cloudfoundry/src/domain/ICloudFoundryServerGroup.ts
- app/scripts/modules/core/src/ci/igor.service.ts
- app/scripts/modules/core/src/domain/IPipeline.ts
- app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts
- app/scripts/modules/core/src/pipeline/config/actions/rename/RenamePipelineModal.tsx
- app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgmentStage.js
- app/scripts/modules/core/src/pipeline/config/stages/savePipelines/PipleineRefList.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/cron/CronDaily.tsx
- app/scripts/modules/core/src/pipeline/config/triggers/cron/CronTrigger.tsx
- app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx
- app/scripts/modules/core/src/pipeline/manualExecution/PipelineOptions.tsx
- app/scripts/modules/core/src/widgets/spelText/SpelAutocompleteService.ts
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/container.component.js
- app/scripts/modules/kubernetes/src/v1/serverGroup/configure/configuration.service.js
Fixes for eslint rules: `no-case-declarations`, `@spinnaker/strictdi`, `no-useless-escape`, `@typescript-eslint/ban-types` `@typescript-eslint/no-inferrable-types`
> Fixes for lint errors

- app/scripts/modules/core/package.json
> chore(core): Bump to version 0.0.433

- app/scripts/modules/core/src/application/config/applicationAttributes.directive.html
- app/scripts/modules/core/src/application/config/applicationAttributes.directive.js
- app/scripts/modules/core/src/config/settings.ts
- settings.js
1. Abstract Slack url to settings so it is configurable
2. Link to channel based on id in case of name change
> fix(core/slack): Abstract Slack base url 

- app/scripts/modules/core/package.json
- fix(core/slack): Abstract Slack base url  (#7693)
- test(core): Fix intermittent Executions test (#7691)
- refactor(core): move managed entity fields to separate interface (#7686)
- refactor(core): convert security groups views to React (#7676)
- chore(package): update to react-tether@1.0.5 (#7684)
> chore(core): Bump core to 0.0.434

- app/scripts/modules/core/package.json
refactor(core/managed): switch from ApplicationVeto to pause API (#7695)
> chore(core): bump to 0.0.435

- package.json
> chore(eslint): lint the entire app/ directory not just modules/

- app/scripts/modules/core/package.json
-  fix(core): updateStageField should not update reserved fields (#7722)
-  refactor(core): remove unused parameter options from confirmation modal (#7716)
-  fix(core): allow scroll in main view when content has extra stuff (#7712)
-  fix(core): increase CSS specificity on select2 overrides (#7719)
-  (origin/master) fix(plugins): Fix linter error and rename file
-  feat(plugins): Expose sharedLibraries on the Spinnaker global object
-  fix(core/utils): Only set window.spinnaker if the window object is present
-  chore(core): upgrade to latest prettier (#7713)
-  fix(core): derive security group view options from filterModel (#7711)
> chore(core): Bump to 0.0.437

- app/scripts/modules/amazon/package.json
upgrade to latest prettier (#7713) 
Remove unused AmazonTemplates (#7707)
refactor(eslint): Fix all '@spinnaker/ng-no-component-class' eslint rule violations
refactor(core): convert security groups views to React (#7676)
fix(titus): Remove default metricName (#7680)
chore(typescript): update to typescript 3.7.x (#7668)
refactor(*): Remove exports-loader from n3-chart import
fix(amazon/instance): don't blow up on standalone instances (#7666)
fix(lint): Fixes for no-useless-escape linter rule
fix(angularJS): Fix all remaining non-strict angularJS DI code via @spinnaker/strictdi linter rule
chore(react-select): Update react-select type modules (#7660)
chore(tsconfig): standardize all tsconfig.json files to es2017 (#7656)
fix(amazon): Update load balancer validations to match user …
> chore(amazon): Bump amazon to 0.0.226

- app/scripts/modules/amazon/package.json
- feat(aws/additionalIpRules): Add a component for aws security group a… (#7726)
> chore(amazon): Bump amazon version to 0.0.227

- app/scripts/modules/amazon/package.json
> chore(amazon): Bump Amazon version to 0.0.228

- app/scripts/modules/core/package.json
edacd08419e97e7f265538c3015c6e2789bf238b feat(core): offer to pause managed resources before performing actions (#7728)
10b34915860ed46f21d0179bf87c3b456de49c56 refactor(\*): use consistent styles on modal headers
9560304a063e7afb3af6deca7c64c4684baf78f3 feat(core): add pause/resume to managed resource menu
5b7c9cf76aad5552a1d2d3353a566a00349ab8d9 feat(core): add validator for stage/trigger providing repository info
c76ca2f152d843958c8092437537e8055396c05a Apply suggestions from code review
dc2b3d7419c79159a89ad346bd64e2f4cc9fde75 refactor(\*): favor optional chaining over lodash.get
ecd7d708f57ce61c51fa2f87c9e9dbbd23659d7f fix(core): do not try to render task monitor if monitor is missing (#7744)
bbf87f9fa4dbc284f570f1a923af488bb926e810 refactor(core): use useForceUpdate hook instead of …
> chore(core): bump package to 0.0.438

- app/scripts/modules/amazon/package.json
edacd08419e97e7f265538c3015c6e2789bf238b feat(core): offer to pause managed resources before performing actions (#7728)
10b34915860ed46f21d0179bf87c3b456de49c56 refactor(\*): use consistent styles on modal headers
9560304a063e7afb3af6deca7c64c4684baf78f3 feat(core): add pause/resume to managed resource menu
c76ca2f152d843958c8092437537e8055396c05a Apply suggestions from code review
dc2b3d7419c79159a89ad346bd64e2f4cc9fde75 refactor(\*): favor optional chaining over lodash.get
a59b2c3264500080fad7caeb05054eef6f51d52c refactor(core): convert confirmation modal to react
abf39e70e72c3231da29d4c81966aa47ad15fd87 refactor(core/amazon): remove unused CSS rules (#7732)
65488728e4ef08c2034123a88a9a4b96cb0e4bd9 refactor(core): provide wrapper for dangerously setting html (#7721) …
> chore(amazon): bump package to 0.0.229

- app/scripts/modules/titus/package.json
10b34915860ed46f21d0179bf87c3b456de49c56 refactor(*): use consistent styles on modal headers
a59b2c3264500080fad7caeb05054eef6f51d52c refactor(core): convert confirmation modal to react
d2838d80c7f14989368fc490a2d842b2d4952a42 refactor(core): remove unused parameter options from confirmation modal (#7716)
6291f858cb111d9c65affeb82ddd840f05c57b65 chore(core): upgrade to latest prettier (#7713)
90aa47754bc8815eb1bdfcceb4d05c9e1cdf325f refactor(eslint): Fix all 'prefer-const' eslint rule violations
d070bd45ff3e185999e863e3f48c01f63eb45733 refactor(eslint): Fix all 'one-var' eslint rule violations
174870161a5a09ab7f15c74cb84d0f3e196cd7cb refactor(eslint): Fix all 'no-var' eslint rule violations
9400826bcb119cf7681e1ce37092b9fdd8b76b1b chore(eslint): remove tslint …
> chore(titus): bump package to 0.0.122

- app/scripts/modules/core/package.json
ff87bda72eed677b6e1b792bc5fae346ca459336 feat(core/amazon/titus): restrict menu items on managed resources, fix confirmation modal resolve/reject (#7750)
> chore(core): bump package to 0.0.439

- app/scripts/modules/amazon/package.json
ff87bda72eed677b6e1b792bc5fae346ca459336 feat(core/amazon/titus): restrict menu items on managed resources, fix confirmation modal resolve/reject (#7750)
> chore(amazon): bump package to 0.0.230

- app/scripts/modules/titus/package.json
ff87bda72eed677b6e1b792bc5fae346ca459336 feat(core/amazon/titus): restrict menu items on managed resources, fix confirmation modal resolve/reject (#7750)
> chore(titus): bump package to 0.0.123

- app/scripts/modules/core/package.json
- feat(managed-delivery): Add UI for importDeliveryConfig stage (#7733)
- fix(core): do not log all help contents to the console (#7755)
> chore(core): Bump version to 0.0.440

- app/scripts/modules/amazon/package.json
e6c6c662b5326fcb184772c99f2212ce4336a1cb refactor(\*): de-angularize confirmationModalService (#7759)
4302a0fc90d2b1679dee204d15e59d3e53b3d0a0 feat(core/amazon/titus): do not allow create/clone in managed clusters (#7754)
> chore(amazon): bump package to 0.0.231

- app/scripts/modules/core/package.json
fix(core/pipeline): use fresh trigger + stage list for upstream flag validation (#7765)
fix(core): catch cancelling of resource pause from server group modal (#7764)
> chore(core): bump to 0.0.441

- halconfig/settings.js
See explanation here: https://github.com/spinnaker/deck/pull/7730#issuecomment-573729170
Note that this will get cherry picked into release 1.18
cc @bpowell
> fix(plugins): Remove plugins entry that is causing runtime errors

- app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
Adds the same visual treatment we have for Amazon server groups managed by Spinnaker.
> feat(titus): add Managed by Spinnaker section to details

- app/scripts/modules/core/package.json
73fa66ee0d22b35997dc987135f2033825aef500 fix(core): do not render the server group warning message in \<pre> (#7774)
a8cc869875e1a27dc84d6b7fb584104ff565f824 fix(core): display task monitor above page navigator chrome (#7772)
fc1ae74e50e289da890c119afae9c5614ab0f770 fix(appconfig): Fix error thrown when slack object is not defined (#7770)
73838f7b453df77ca466df8344844a414bb37ec2 feat(aws/cfn): Cloudformation ChangeSet execution (#7671)
> chore(core): bump package to 0.0.442

- app/scripts/modules/titus/package.json
5cd46be3fd70ef04532409f8a5bfce25711f6633 feat(titus): add Managed by Spinnaker section to details (#7776)
a020a96cb225eefc38656b7494982b0056e1ec1f fix(titus): Blank IAM profile unclickable (#7775)
> chore(titus): bump package to 0.0.125

- app/scripts/modules/core/src/pagerDuty/Pager.tsx
- app/scripts/modules/core/src/pagerDuty/pager.less
- app/scripts/modules/core/src/presentation/main.less
The checkbox was there for..."accessibility"?
Anyway, there is already a handler on the row, and it has the `disabled` check and other logic. Let's remove the checkbox, eh.
> fix(core): fix pager checkbox click behavior

- app/scripts/modules/core/package.json
* PagerDuty fixes
* PagerDuty perf fixes
* CSS fixes for main layout
> chore(core): bump package to 0.0.443

- app/scripts/modules/core/src/help/help.contents.ts
Related to https://github.com/spinnaker/spinnaker/issues/3011, https://github.com/spinnaker/spinnaker/issues/5233
Link to expected artifacts docs updated with https://github.com/spinnaker/spinnaker.github.io/pull/1672
> feat(artifacts): link to updated docs from Match Artifact tooltip

- app/scripts/modules/amazon/src/securityGroup/configure/EditSecurityGroupCtrl.js
- app/scripts/modules/amazon/src/securityGroup/configure/additionalIpRules.component.ts
- app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
- app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupIngress.html
- app/scripts/modules/amazon/src/securityGroup/configure/securityGroupDetailsCustom.component.ts
- app/scripts/modules/amazon/src/securityGroup/configure/securityGroupDetailsCustom.tsx
- app/scripts/modules/amazon/src/securityGroup/securityGroup.module.ts
- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
- Component for additional security group details
> fix(aws): Component for additional security group details 

- app/scripts/modules/core/package.json
> chore(core): Bump to version v0.0.444

- app/scripts/modules/amazon/package.json
> chore(aws): Bump aws to version v0.0.232

- app/scripts/modules/amazon/package.json
411fda5eba15363a792a5dc36873246d6a0f870c fix(core/confirmationModal): Supply the 'source' location when canceling (#7816)
b632e29b9c5624d43df4b3a312fc9fb2432d6aa1 tests(core): Introduce entity mocks into deck (#7781)
607a6c46519d4079e37afc6238a57bfc33a33c54 fix(amazon): Prevent error if target group is undefined (#7819)
b51dce46be3df14070f06e06de874108dcf23569 chore(lint): Run eslint on typescript files
38a6324aa9f116c70c7644113f5f84214fd95679 chore(lint): Run eslint on javascript files
e15b7964ac7c3025cf4567dbaf803fbf61d28d6b feat(deck): Add execution error details to Task Status in Cloud foundry Stage (#7814)
> chore(package): bump amazon to 233

- app/scripts/modules/core/package.json
411fda5eba15363a792a5dc36873246d6a0f870c fix(core/confirmationModal): Supply the 'source' location when canceling (#7816)
0feb8249948a167de8a74ae6482f7f34eae09b9d Re-exporting types from ExecutionMarkerIcon to make it available elsewhere (#7829)
0ff0ade384230201048c2aac81cf2f4945f6645a feat(travis): Enable Travis stage as an artifact producer (#7831)
71cda71c27392d7ff21f9bd4a90267c07b680703 feat(codebuild): Add AWS CodeBuild Stage (#7798)
b632e29b9c5624d43df4b3a312fc9fb2432d6aa1 tests(core): Introduce entity mocks into deck (#7781)
65b9463b8f4a7d9ce83fd1c1415539dce5d469ab feat(core): enable the "Override Helm chart artifact" checkbox in manual execution by default (#7818)
b51dce46be3df14070f06e06de874108dcf23569 chore(lint): Run eslint on typescript files …
> chore(package): bump core to 445

- app/scripts/modules/assert_clean_master.sh
- app/scripts/modules/assert_package_bumps_standalone.sh
- app/scripts/modules/build_order.sh
- app/scripts/modules/github_actions_publish.sh
- app/scripts/modules/show_dirty_modules.sh
- app/scripts/modules/show_unpublished_commits.sh
Most of these changes were switching from backticks to `$()` and quoting paths
> refactor(bash): Run our bash scripts through bash linter and make recommended changes

- app/scripts/modules/amazon/src/instance/details/instanceDetails.html
- app/scripts/modules/core/src/presentation/LinkWithClipboard.tsx
- app/scripts/modules/core/src/presentation/index.ts
- app/scripts/modules/core/src/presentation/linkWithClipboard.component.ts
- app/scripts/modules/core/src/presentation/presentation.module.js
A repeated code pattern in angular is the use of a link with a clipboard next to it. This component turns that code pattern into a react component and implements it on the instance details panel.
> react(core): Introduce LinkWithClipboard component

- app/scripts/modules/core/package.json
react(core): Introduce LinkWithClipboard component (#7847)
feat(plugins): Load plugins and plugin manifest from gate (#7842)
> chore(core): Bump core to 0.0.446

- app/scripts/modules/amazon/package.json
react(core): Introduce LinkWithClipboard component (#7847)
feat(amazon): Expose addresses for IPv6 instances (#7817)
> chore(amazon): Bump amazon to 0.0.234

- .travis.yml
> fix(travis): use the right grep argument (for quiet mode) so travis doesn't skip CI

- app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
Add reserved memory and compute units to container inputs.
Fixes: https://github.com/spinnaker/spinnaker/issues/5425
> fix(ecs): add memory and cpu properties to container inputs

- app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/awsCodeBuildStage.ts
This PR depends on https://github.com/spinnaker/orca/pull/3431 and https://github.com/spinnaker/igor/pull/624
> feat(codebuild): Allow AWS CodeBuild stage to produce artifacts

- app/scripts/modules/amazon/package.json
> chore(amazon): Bump amazon to 0.0.237

- app/scripts/modules/assert_package_bumps_standalone.sh
> fix(npm): Fixing assert script slightly

- app/scripts/modules/amazon/package.json
> chore(bump): Bump amazon to v.238

- app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
- app/scripts/modules/core/src/plugins/plugin.registry.ts
If deck has a plugin-manifest which includes a plugin ID that is also served by gate, prefer the one in deck.
This can happen for two reasons:
- Deck has baked in manifest and plugins
- Developer is updating a plugin and is running in dev mode
> feat(plugins): Prefer plugins from deck manifest (over gate) if they have the same ID

- app/scripts/modules/core/src/securityGroup/SecurityGroups.tsx
If managed resources endpoint fails, the `applications/{app}/firewalls` page shows a ***'No security groups match the filters you've selected'*** message.
The [cause](https://github.com/spinnaker/deck/blob/bc00902d6aef54f209640fbe03d9ee46690a3b1e/app/scripts/modules/core/src/securityGroup/SecurityGroups.tsx#L98) of the issue is that we're waiting for the managed resources data to be merged into the security groups data before making it available in the component's local state to be rendered by the view. 
In this PR, we're making sure we render the plain undecorated security group data when managed resources endpoint fails.
> fix(core/securityGroups): Render view if managed resources can't be loaded

- app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
> fix(ecs): add memory and cpu to container inputs

- packages/eslint-plugin/package.json
move `jest` to `devDependencies` and release 1.0.4
> Eslint plugin release 1.0.4

- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManualExecutionBakeManifest.tsx
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
Part of https://github.com/spinnaker/spinnaker/issues/5474
This PR adds HELM3 option as Bake Manifest Stage template renderer.
> feat(helm): Add HELM3 as Render Engine in Bake Manifest Stage

- app/scripts/modules/core/package.json
> chore(package): bump core

- app/scripts/modules/core/src/core.module.ts
- app/scripts/modules/core/src/managed/Environments.tsx
- app/scripts/modules/core/src/managed/index.ts
- app/scripts/modules/core/src/managed/managed.module.js
- app/scripts/modules/core/src/managed/managed.states.ts
Bare minimum for the new route so we can iterate. Not yet exposed via nav.
Up next: probably data sources
> feat(managed): Scaffolding environments route

- app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx
I'm clearly not a UI expert... 😝
> fix(managed-delivery): Yet another fix for rendering import delivery config errors

- app/scripts/modules/core/src/account/AccountSelectInput.tsx
- app/scripts/modules/core/src/presentation/forms/inputs/SelectInput.tsx
- app/scripts/modules/core/src/slack/SlackReader.spec.ts
3 commits:
- Fix an async test
- Support disabled options in `<SelectInput />`
- Delegate to `SelectInput` and `ReactSelectInput` in `AccountSelectInput`
> refactor(core/account): In AccountSelectInput, delegate to SelectInput and ReactSelectInput

- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
- app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
Add help text to CodeBuild stage
> feat(codebuild): Add help text to CodeBuild stage

- app/scripts/modules/amazon/src/securityGroup/details/IPRangeRules.tsx
- Add description to IPRangeRule interface used by custom component
> fix(aws): Add description to IPRangeRule interface

- app/scripts/modules/amazon/package.json
> chore(amazon): Bump to version 0.0.240

- app/scripts/modules/core/package.json
testing the auto-approval process!
> chore: bump core to 454

- app/scripts/modules/amazon/src/securityGroup/details/index.ts
- app/scripts/modules/amazon/src/securityGroup/index.ts
Export security group interfaces
> fix(aws): Export security group interfaces

- app/scripts/modules/amazon/package.json
- Version bump Amazon to  0.0.241
> chore(bump): Bump Amazon to 0.0.241

- app/scripts/modules/amazon/package.json
- Bump Amazon version to 0.0.242
> chore(bump): Amazon package bump to 0.0.242

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.243 core 0.0.456

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.457

- app/scripts/modules/core/src/domain/IManagedEntity.ts
- app/scripts/modules/core/src/managed/ManagedReader.ts
- app/scripts/modules/core/src/managed/managed.dataSource.ts
> Revert "feat(md): Types and new data source for environments"

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.244 core 0.0.458

- packages/pluginsdk/package.json
- packages/pluginsdk/yarn.lock
just released a new core, bumping in pluginsdk
> chore(pluginsdk): bump to @spinnaker/core@0.0.459

- packages/pluginsdk/package.json
- packages/pluginsdk/yarn.lock
why is this so hard to get right the first time?
> release pluginsdk 0.0.5

- app/scripts/modules/core/src/application/service/applicationDataSource.ts
Some detective work from @alanmquach uncovered that apparently all the member initialization on classes is getting transpiled at the _top_ of the constructor, above any user-supplied constructor code. The way `ApplicationDataSource` initializes is leading to some things we setup in the constructor (`this.data`, `this.defaultData`) being undefined at times where it's important to have their initial value. The most obvious symptom of this issue is that subscribing to the `data$` BehaviorSubject actually emits `undefined` as its first value, _not_ the value of `defaultData` as is intended.
This change continues to define `private` / `public` and type info on the class directly, but moves the actual assignment of an initial value inside the constructor below the code for populating other …
> fix(core/application): rearrange init ordering of member variables on data sources

- app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
- app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.html
- enabled previously disabled and broken titus previous image rollback
> chore(titus): Reenable previous image rollbacks for titus

- app/scripts/modules/amazon/package.json
- app/scripts/modules/titus/package.json
fix(titus/instance): Temporary workaround to get IPv6 for Titus instances (#8054)
refactor(svg): add SVGR loader for inlined react SVG support (#8055)
> chore(titus/amazon): Bump to amazon@0.0.246, titus@0.0.131

- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish core 0.0.462 kubernetes 0.0.35

- app/scripts/modules/titus/package.json
> chore(titus): Bump to 0.0.132

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.463

- app/scripts/modules/core/src/managed/ArtifactDetail.tsx
- app/scripts/modules/core/src/managed/EnvironmentRow.less
- app/scripts/modules/core/src/managed/EnvironmentRow.tsx
- app/scripts/modules/core/src/managed/EnvironmentsList.tsx
- app/scripts/modules/core/src/managed/Frigga.ts
- app/scripts/modules/core/src/managed/ObjectRow.module.css
- app/scripts/modules/core/src/managed/ObjectRow.tsx
Grouping children under a `<EnvironmentRow>` collapsible parent component + polishing up a bunch of styling.
Environments (before)
Environments (after)
Artifact Detail (before)
Artifact Detail (after)
> feat(core/managed): Group resources under EnvironmentRow

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.247 core 0.0.464

- app/scripts/modules/show_changelog.sh
example:
feat(core/managed): swap progress direction on artifact rollouts [#8087](https://github.com/spinnaker/deck/pull/8087) ([c9587ac1](https://github.com/spinnaker/deck/commit/c9587ac177847108ed4aa98cfecd62e9aada6f4b))
fix(core/deploymentStrategy): Handle missing rollback property in command [#8082](https://github.com/spinnaker/deck/pull/8082) ([ebe411c0](https://github.com/spinnaker/deck/commit/ebe411c02d8bafda7831f434f28effd36fa8ec2f))
feat(core/presentation): adds svg icons for new ui designs [#8083](https://github.com/spinnaker/deck/pull/8083) ([7ae41774](https://github.com/spinnaker/deck/commit/7ae4177453ea11c24d89d8f0b50bbfc008198c2f))
fix(core): Stop propagation of task monitor close event [#8085](https://github.com/spinnaker/deck/pull/8085) …
> feat(scripts): switch show_changelog.sh --expand-links to --markdown

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.465

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.466

- app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
I made a git oopsie and didn't actually include this in #8107. Sawry.
> fix(core/managed): add originally intended error handling on ConstraintCard

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish amazon 0.0.249 core 0.0.468 ecs 0.0.254 google 0.0.12 kubernetes 0.0.36

- app/scripts/modules/core/package.json
feat(core): Add svg name to dataSource (#8120)
feat(core/managed): Deep link resources to their infrastructure view (#8115)
> chore(core): Bump to core@0.0.469

- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/managed/Environments.tsx
- app/scripts/modules/core/src/presentation/hooks/useDataSource.hook.ts
Depends on https://github.com/spinnaker/deck/pull/8118
Adding loading, error, and zero (onboarding) states for the Environments route.
With the useDataSource PR (https://github.com/spinnaker/deck/pull/8118) merged, this PR should effectively reduce to just the [last commit](https://github.com/spinnaker/deck/commit/775eb7a9179adf77d084749e2f174226182253ce).
> feat(core/managed): Adding loading, error, and zero states.

- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx
Remove atlas health check poller in JDB
> fix(titus): Remove atlas health check poller in JDB

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
> chore(package): publish amazon 0.0.250 core 0.0.470 titus 0.0.134

- packages/mocks/src/mockEntityTags.ts
A few lint errors were preventing publishing the new version
> fix(mocks): Remove some tslint errors

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/ecs/package.json
> chore(package): publish core 0.0.471 docker 0.0.55 ecs 0.0.255

- packages/mocks/src/mockTask.ts
> fix(mocks): Fix tslint error

- package.json
- yarn.lock
> chore(core): Upgrade @spinnaker/mocks to 1.0.4

- app/scripts/modules/publish.js
If you have 2fa enabled, you cannot push to github via https (you have to use git protocol).  Add a pre-check to `publish.sh` and help the user update their git repo config
> fix(publish): Pre-check the upstream remote is configured to use the git ssh protocol

- build.gradle
> chore(build): keep the release part of the version if provided

- app/scripts/modules/core/src/application/nav/NavSection.spec.tsx
- app/scripts/modules/core/src/application/nav/NavSection.tsx
- app/scripts/modules/core/src/application/nav/verticalNav.less
Dependent on https://github.com/spinnaker/deck/pull/8150.
A simple component that takes a list of navigation categories and maps them to the `NavCategory`. The list of categories are formatted into a component.
> feat(core/nav): Add sections for vertical nav

- app/scripts/modules/core/src/pipeline/config/stages/managed/importDeliveryConfigStage.ts
Fix broken doc link in Import Delivery Config stage.
> fix(stage): fix import delivery config doc link

- app/scripts/modules/core/src/application/nav/NavSection.tsx
This fixes the "duplicates in a repeater" errors in unit tests for #8203
> fix(core/nav): fix NavSection react key

- app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.tsx
Use flexbox layout to reduce special cases
> Radio button input css

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish amazon 0.0.252 core 0.0.473 ecs 0.0.257 kubernetes 0.0.38

- app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.spec.tsx
- app/scripts/modules/core/src/presentation/forms/hooks/useSaveRestoreMutuallyExclusiveFields.hook.ts
Adds a formik hook to save/restore mutually e…xclusive form fields when toggling between two or more modes in a form
See the .spec.tsx file for example usage
> feat(core/presentation): Add a formik hook to save/restore data

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.474

- package.json
- yarn.lock
> chore(core): Upgrade to @spinnaker/mocks@1.0.5

- packages/mocks/package.json
- packages/mocks/src/index.ts
> chore(mocks): Expose amazon folder

- package.json
- yarn.lock
> chore(mocks): Update @spinnaker/mocks

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish amazon 0.0.253 core 0.0.475 kubernetes 0.0.39

- app/scripts/modules/core/src/cluster/index.ts
> feat(core): Export FilterSection

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.476

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish amazon 0.0.254 appengine 0.0.12 core 0.0.477 ecs 0.0.258 google 0.0.14 kubernetes 0.0.40

- app/scripts/modules/core/package.json
- app/scripts/modules/tencentcloud/package.json
> chore(package): publish core 0.0.478 tencentcloud 0.0.2

- app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.html
- app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
- app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroup.html
- app/scripts/modules/amazon/src/securityGroup/configure/editSecurityGroup.html
- Include custom component form state to disable submit button
> fix(amazon): Include custom component form state for validation

- app/scripts/modules/core/src/cluster/index.ts
> fix(core): Export filter search component

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.255 core 0.0.479

- app/scripts/modules/core/src/presentation/details.less
- app/scripts/modules/core/src/presentation/main.less
> fix(core): Details panel height when in multiselect

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/tencentcloud/package.json
- app/scripts/modules/titus/package.json
> chore(package): publish amazon 0.0.256 core 0.0.480 tencentcloud 0.0.3 titus 0.0.136

- .storybook/.babelrc
- .storybook/main.js
- app/scripts/modules/core/src/config/settings.ts
- app/scripts/modules/core/src/presentation/modal/Modal.stories.tsx
- package.json
- yarn.lock
Adding storybook in deck. This PR adds the minimum changes needed to get storybook running and I'm going to add more addons to improve the experience shortly.
<details>
<summary>Storybook running locally on port 9001</summary>
</details>
> feat(storybook): Add storybook support

- app/scripts/modules/core/src/pagerDuty/Pager.tsx
- app/scripts/modules/core/src/presentation/illustrations/illustrationsByName.ts
A new banner needs to be added to pager page, so making it overridable here and later adding it in `-nflx` repo.
> feat(core/page): Add support to add banner to pager view

- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish appengine 0.0.13 core 0.0.481 ecs 0.0.259 kubernetes 0.0.41

- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
The `SpinnakerHeader` needs to be a functional component to use recoil hooks, but `@Overrides` only works on a class component. This wrapper is temporary to enable what we need until we have time to refactor the override component to work for functional components.
> refactor(core): Refactor SpinnakerHeader to functional component

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.482

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.483

- app/scripts/modules/core/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish core 0.0.484 google 0.0.15 kubernetes 0.0.42

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.485

- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
> feat(core/pipeline): Add sort pipelines alphabetically button

- .dockerignore
- Dockerfile.slim
- Dockerfile.ubuntu
* Improvement docker build with more cache for fast build.
* Add unused in docker image folder to .dockerignore  for reduce start build
> chore(core): improvement docker build

- app/scripts/modules/core/package.json
- app/scripts/modules/google/package.json
> chore(package): publish core 0.0.486 google 0.0.16

- app/scripts/modules/core/src/presentation/icons/iconsByName.ts
> feat(core): Export meme icon

- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfigView.html
- app/scripts/modules/core/src/presentation/navigation/PageNavigator.tsx
- app/scripts/modules/core/src/presentation/navigation/PageSection.tsx
Apply flex display to nested pipeline config components
> fix(core): Flex on pipeline config

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.487

- app/scripts/modules/core/src/application/nav/navAtoms.ts
- app/scripts/modules/core/src/application/nav/verticalNav.less
- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
- app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.less
- app/scripts/modules/core/src/presentation/details.less
- app/scripts/modules/core/src/presentation/navigation/pageNavigator.component.ts
- app/scripts/modules/core/src/task/tasks.less
A batch of fixes from the layout rollout: 
1. Update `collapsibleSectionStateCache` to preserve toggling nav when refreshing
2. Set pipeline graph width, and make container scrollable
3. Make pipeline stage container flex
4. Prevent task exception from overflow by adding a word break
5. Add padding to details panel so text isn't truncated when there is overflow
6. `cursor: pointer` on new app refresh icon
> fix(core): Layout v1 feedback

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.488

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.489

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.490

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.257 core 0.0.491

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
Add options for showing up to 100 and 200 executions.
> config(pipeline/executions): Increase executions per pipeline options

- app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
- app/scripts/modules/azure/src/pipeline/stages/bake/bakeStage.html
Show Checkbox so users can select the view the "Advanced options" section.
> fix(bake): show advanced options

- app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
- app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
- app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
> fix(titus): Make iamProfile a required field in the UI and offer to fill in the default value if it's missing.

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
> chore(package): publish amazon 0.0.258 azure 0.0.252 core 0.0.493 titus 0.0.137

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
> chore(package): publish amazon 0.0.259 core 0.0.494 docker 0.0.57 titus 0.0.138

- app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
> fix(core/nav): Apply new class to Page App Owner

- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish core 0.0.495 kubernetes 0.0.43

- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
> fix(core/securityGroup): Clone cached data before mutating it

- app/scripts/modules/core/package.json
> chore(package): publish core 0.0.496

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/titus/package.json
> chore(package): publish amazon 0.0.260 appengine 0.0.14 core 0.0.497 kubernetes 0.0.44 titus 0.0.139

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish amazon 0.0.261 core 0.0.498 kubernetes 0.0.45

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
> chore(package): publish amazon 0.0.262 core 0.0.499

- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/google/package.json
> chore(package): publish core 0.0.500 docker 0.0.58 google 0.0.17

- app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx
I think this tiny change will make a big difference in conveying the meaning we want to.
> chore(messages): Replace the word "previous" with "prerequisite" in depends-on constraint text

- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish core 0.0.501 kubernetes 0.0.46

- app/scripts/modules/core/src/cluster/allClusters.controller.js
- app/scripts/modules/core/src/pipeline/config/stages/deploy/deployStage.js
- app/scripts/modules/core/src/presentation/main.less
- app/scripts/modules/ecs/src/serverGroup/details/serverGroupDetails.ecs.controller.js
- app/scripts/modules/ecs/src/serverGroup/events/events.component.ts
Fixes: https://github.com/spinnaker/spinnaker/issues/5971
> fix(ecs): update z-index for uibModal

- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
> chore(package): publish core 0.0.502 ecs 0.0.260 google 0.0.18 kubernetes 0.0.47

- app/scripts/modules/core/src/application/nav/verticalNav.less
Support long nav items that also require an alert icon.
> fix(core/nav): Increase nav width for long text with alerts

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
95674d34d0aceb8f73e4c44df805b182dc89107b feat(amazon/asg): Add help info and constraints for defaulting IMDSv2 (#8490)
f358e5e8f8615a47ba98ade8b465246054d0c917 refactor(aws/titus): Refactor instance status section to react (#8497)
0de610ed199168375752481199b15e345dc8d3d6 fix(amazon/firewall): Ensure we use a valid default vpc instead of none (#8524)
ba093b7595ebf31130b6027dd4d0d2de488c073e fix(core/nav): Increase nav width for long text with alerts (#8542)
f358e5e8f8615a47ba98ade8b465246054d0c917 refactor(aws/titus): Refactor instance status section to react (#8497)
e508a6f83c67d9e336e16262ceee35d5fabf754c chore(core): Remove old nav css (#8481)
fbe0e54b29c452797a43aaea9f2fab0d7c0fe8d8 feat(core/notifier): Make notifier service work with react components (#8521) …
> chore(package): amazon@0.0.264 core@0.0.505 titus@0.0.141

- app/scripts/modules/core/package.json
9d0cf54405a491b2e84170789104ceac9790f78b feat(core/managed): surface git metadata on version list (#8580)
2a11216f57f2250c194cfd9eb372b9340ee3ad84 feat(notification): Add Microsoft Teams notification support (#8503)
> chore(package): core@0.0.509

- app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx
> fix(amazon/instance): Update language for IMDSv2

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
4a4285a7ce28f07570a878e4917b7bb8b84d7569 fix(amazon/instance): Show instance type for amazon (#8592)
65dd935cdffdcee16667e62cdcc5c727a844cc24 feat(helm): Add Helm Chart pipeline trigger (#8475)
519dfc010598de6428b833f1a63e2ee12baaf4f2 feat(storybook/SpinFormik): Create a story for SpinFormik
> chore(package): amazon@0.0.268 core@0.0.511

- app/scripts/modules/core/src/presentation/forms/SpinFormik.stories.mdx
Continuing from https://github.com/spinnaker/deck/pull/8590, I've added two new stories for `SpinFormik` and adjusted the format of the documentation a little bit.
1. Validation example
2. Custom Input Field example
> feat(storybook/formik): More formik stories

- app/scripts/modules/core/src/widgets/spelText/SpelNumberInput.tsx
Broke this in https://github.com/spinnaker/deck/pull/8553
> fix(core/spelNumberInput): Fix broken html escaping

- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
f3324c69f141d427d46708e9f264905fbd788de5 fix(core/spelNumberInput): Fix broken html escaping (#8604)
f38e674f5a115903d5ec2db022891b263ba436c3 feat(core/managed): tighten up layout on environments header (#8601)
caff6d2070ca96e770c7c013d7c935b2849d0d80 feat(stages): Add monitorPipeline stage execution details (#8561)
e57714c08b41f65c6a214b7f82e917e71992c5a1 feat(storybook/formik): More formik stories
15b6ec62e957ed410ab46647bbc711f1d195a04c fix(kubernetes): Hide load balancers stage from Kubernetes provider (#8598)
> chore(package): core@0.0.512 kubernetes@0.0.51

- app/scripts/modules/core/package.json
c71e950c33bc5b99f8fbc33edf8a2d6a6c61f831 feat(core/managed): visual re-treatment of statuses, constraints, and more (#8600)
> chore(package): core@0.0.513

- app/scripts/modules/core/src/help/help.contents.ts
Describe behavior when it is omitted.
Related: https://github.com/spinnaker/orca/pull/3933
> feat(webhooks): document stausJsonPath is now optional

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/tencentcloud/package.json
f1bb04e867e68e53f4e4edb22192afbcd9715d5d fix(appname): encodeURIComponent for app name (#8586)
f1bb04e867e68e53f4e4edb22192afbcd9715d5d fix(appname): encodeURIComponent for app name (#8586)
f1bb04e867e68e53f4e4edb22192afbcd9715d5d fix(appname): encodeURIComponent for app name (#8586)
80858e771cf041d4de4347c6e701606af152d09a feat(core/managed): limit artifact versions to 30 (#8623)
90a2819a34d5f42acc6a5d60233282ef0d508dbc feat(core/managed): put constraints in a 'skipped' state on skipped versions (#8620)
815742d4a93c4eec0faf404bd5d086916c55abe5 feat(core/managed): scroll to selected version in sidebar, update scroll containers (#8618)
de24ef322c39f1199cad50fd9264f973c8ea99ac feat(core/managed): apply consistent sorting to resources (#8622)
3735483477f2a1ba6eaad437c617412221836aaa …
> chore(package): amazon@0.0.269 azure@0.0.255 cloudfoundry@0.0.101 core@0.0.516 docker@0.0.60 google@0.0.21 oracle@0.0.9 tencentcloud@0.0.6

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/tencentcloud/package.json
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627)
885cd169ad0dca8e7e6683bc96d2c131af6b3a1e Revert "fix(appname): encodeURIComponent for app name (#8586)" (#8627) …
> chore(package): amazon@0.0.270 azure@0.0.256 cloudfoundry@0.0.102 core@0.0.517 docker@0.0.61 google@0.0.22 oracle@0.0.10 tencentcloud@0.0.7

- packages/eslint-plugin/README.md
I figured writing eslint rules is pretty intimidating.  Here's a little write up with some of the basics.
> feat(eslint-plugin): Add a README.md with instructions on creating eslint rules

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/tencentcloud/package.json
- app/scripts/modules/titus/package.json
- amazon 0.0.271 
- azure 0.0.257 
- cloudfoundry 0.0.103
-  core 0.0.518 
- docker 0.0.62 
- google 0.0.23 
- oracle 0.0.11 
- tencentcloud 0.0.8 
- titus 0.0.147
> Package bump amazon 0.0.271 azure 0.0.257 cloudfoundry 0.0.103 core 0.0.518 docker 0.0.62 google 0.0.23 oracle 0.0.11 tencentcloud 0.0.8 titus 0.0.147

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/oracle/package.json
a7e8847db53289a3dd8803523096ae4a91710184 fix(aws): Support cross zone load balancing for NLB (#8557)
068518d8ac8917be9f1676067094e266888c450a fix(core/managed): respect line breaks in commit messages (#8653)
a7e8847db53289a3dd8803523096ae4a91710184 fix(aws): Support cross zone load balancing for NLB (#8557)
7f266fbf79f2e13d875bb030b5f8afa831616a3d fix(oracle): enforce valid oracle load balancer subnet choices
> chore(package): amazon@0.0.273 core@0.0.520 oracle@0.0.13

- app/scripts/modules/core/package.json
97bd615b565bf03623f64d92c3f124177670bc16 feat(core/pipeline): Rename "Source" link to "View as JSON" (#8658)
d7e357e5228089afa1de1bedb64930b3d00ae2ea fix(core/managed): surface artifact reference on details pane (#8656)
> chore(package): core@0.0.521

- app/scripts/modules/core/src/manifest/PodNameProvider.ts
Addresses issue https://github.com/spinnaker/spinnaker/issues/6111
> fix(core): Check if manifest event is null from k8s.

- app/scripts/modules/core/src/application/nav/verticalNav.less
> fix(core/nav): Add shading to active route

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/titus/package.json
03194e73aaaf3fb092ef47048f730360528574c6 fix(amazon/securityGroup): Initialize all accounts while cloning security groups (#8710)
37483823071dfbc76491b77004c5435479207cc6 refactor(core/instance): Create generic header for instance details panel (#8706)
d53136ad7b40fed858a17cbac878344ee10e904d refactor(core): Remove componentWillUpdate and componentWillMount methods
37483823071dfbc76491b77004c5435479207cc6 refactor(core/instance): Create generic header for instance details panel (#8706)
37483823071dfbc76491b77004c5435479207cc6 refactor(core/instance): Create generic header for instance details panel (#8706)
37483823071dfbc76491b77004c5435479207cc6 refactor(core/instance): Create generic header for instance details panel (#8706)
53490381accc124a467e7dfd6c4b8188920d2bff fix(core/nav): Add …
> chore(package): amazon@0.0.278 appengine@0.0.24 azure@0.0.262 core@0.0.526 ecs@0.0.271 google@0.0.28 kubernetes@0.0.56 oracle@0.0.17 titus@0.0.153

- app/scripts/modules/core/src/search/global/globalSearch.less
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat(core/search): Make the search results dropdown wider

- app/scripts/modules/core/package.json
cb01e00f0eade9ec596ce3ae1b798cae84063d50 chore(managed): fix new resource versions not showing up in environment view (#8702)
f54db8521c99c737693f58f82b781e92b47cc257 fix(core/pipeline): Handle null restrictionExecutionWindow (#8707)
65a84e5b91f53cb55614b69cc456b0b8042d1aa2 feat(core): Add Registry object to DebugWindow for easier debugging (#8708)
2d56329d8bff450517a5abf1c1570f0087e5a451 feat(core/search): Make the search results dropdown wider (#8709)
> chore(package): core@0.0.527

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
1bf2c95fa7409b7fdda8623fcb1cf37dab5e6456 feat(aws): Automatically enable IPv6 in test clusters (#8716)
c6b23a7ab276269f4338874edca24be75ad308f8 Pager feature in Spinnaker application navigation bar  as an optional feature (#8715)
> chore(package): amazon@0.0.279 core@0.0.528

- app/scripts/modules/core/package.json
f9b4a87cb57aa0f5ad8f2aa4b863f497e326c572 feat(core/managed): support git compare link on versions (#8730)
> chore(package): core@0.0.530

- app/scripts/modules/core/package.json
645b99dc98b291a818c0108e1ec1b4a39f4cd7eb fix(core/loadBalancer): Handle null healthCheckProtocol (#8732)
> chore(package): core@0.0.531

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
815a4864d3e9acf866b9bc3220c3a282134b0fed Titus target healthy percentage (#8734)
b3536fd5102d201356244efa2e8a5342231b0982 fix(core/api): Fix type safety for API.one() builder (#8739)
43d58e84767ce973bef8b7a348965019ed14e86a feat(core/managed): fill some usage logging gaps in Environments (#8738)
abd0da7017efb4313486dce89882b62e182d8035 fix(core): Initialize cache for executions permalink (#8737)
97148a44ad3d6818657359acce91fc1baff3b9a1 fix(config): Make running executions limit configurable (#8713)
7271167b685e32972047eef22e47cbb37dd0f7f5 feat(core/pipelines): Add execution breadcrumbs to the pipeline execution component (#8462)
815a4864d3e9acf866b9bc3220c3a282134b0fed Titus target healthy percentage (#8734)
> chore(package): amazon@0.0.281 core@0.0.532 titus@0.0.154

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
2ec9db04ffc7e2b6c8b426e2ef13203600b29839 fix(titus): Disable edits of step scaling dimensions (#8747)
7a8f9394354c4c5bb75d0bfd98feb2a76bad3a94 feat(aws): added the ability to modify CPU credits (#8736)
f4d7d14e5bff77e381274f634d7134968e0f7293 feat(core/managed): surface pre-deployment steps for versions (#8750)
0cdf8369f4156e09ebcab8f097ec76e2b713936b chore(core): Upload new illustrations (#8744)
e3c80c353d2d10bdf82cafc89dded9fad9fb2125 feat(core): Add a container for migration banners (#8735)
976e958b25d44086b59108367ab038199ffcdc7e feat(bake): include git/repo artifacts in the list of artifacts to choose when baking helm charts (#8743)
7a8f9394354c4c5bb75d0bfd98feb2a76bad3a94 feat(aws): added the ability to modify CPU credits (#8736)
2ec9db04ffc7e2b6c8b426e2ef13203600b29839 fix(titus): …
> chore(package): amazon@0.0.282 core@0.0.533 titus@0.0.155

- app/scripts/modules/core/package.json
f1029669ac91c4f2b0c859a66debdf49d79b7cc5 chore(core): Export all generic instance components (#8755)
530f59c912bc9ef1293b0dfa44a80ad8cef94e08 fix(core): Fix details drawer positioning (#8754)
> chore(package): core@0.0.534

- packages/mocks/package.json
- packages/mocks/src/amazon/index.ts
- packages/mocks/src/amazon/mockAmazonServerGroup.ts
Added mocks for AmazonServerGroup
> feat(mocks) Added mocks for AmazonServerGroup

- packages/mocks/src/amazon/mockAmazonServerGroup.ts
Add missing fields to Amazon mocks
> fix(mocks): Add missing fields to Amazon mocks

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
a22f72525edb3195136b3df55bb78e499fe09dbc fix(amazon/instanceDetails): Fix typo (#8764)
5ae377cedaa29df7b738db9840ef6ac72055415b feat(aws) added instance type options for EC2 (#8745)
cb683081e9e85b313b1ead5936caa2d5950eaa1a feat(core/managed): add pre-deployment events for builds (#8768)
8038dd80d2374bc511524f80a9c02bce805c7b4a refactor(REST): Rename HttpClientBackend interface to HttpClientImplementation
78dee2c1cb852de73900141a4f649342c72ab44b chore(core/api): fix api-no-unused-chaining lint violations
d3327e5ae8e046774e1a171cc395e34c6017df6c chore(core/api): Update plugin.registry.spec.ts and SpelService.spec.ts tests for new http backend
c4e775f540ce031a59bfeab8f28dd87f5fa74ed9 feat(core/api): Create a new REST() client api to replace API.one()
a22f72525edb3195136b3df55bb78e499fe09dbc …
> chore(package): amazon@0.0.283 core@0.0.535 titus@0.0.156

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
This addresses a major annoyance in sharing links to executions that are not the most recent (i.e. Show [2] executions per pipeline) results in losing the linked execution because it was not available to be selected.
Instead of just navigating up (existing behavior) and dropping the executionId from the route:
1. Lands on `#/applications/myawesomeapp/executions/0425LQQ2020FHQWGHADS`
2. Execution not found in already fetched n most recent executions per pipeline
3. Transition up to parent state (executions): `#/applications/myawesomeapp/executions`
We will instead check if the execution exists at all and if so, forward to the SingleExecutionDetails route:
1. Lands on `#/applications/myawesomeapp/executions/0425LQQ2020FHQWGHADS`
2. Execution not found in already fetched n most recent …
> fix(core): Redirecting aged out executions to permalink

- package.json
- yarn.lock
> chore(mocks): Upgrade @spinnaker/mocks

- app/scripts/modules/core/src/help/help.contents.ts
- app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
Take 2...and includes the revert of the [first attempt](https://github.com/spinnaker/deck/pull/8751), but will rebase after the [separate PR to revert that](https://github.com/spinnaker/deck/pull/8773) goes in.
> Fix helm bake manifest

- app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
- app/scripts/modules/google/src/serverGroup/configure/wizard/zones/targetShapeSelector.directive.html
- app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.gce.controller.js
- app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html
This feature has now [launched to GA](https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#setting_a_policy_for_distributing_instances_across_zones).
See #8089
> feat(targetShape): remove the ALPHA conditional on the targetShape

- app/scripts/modules/amazon/src/domain/IAmazonLaunchTemplate.ts
- app/scripts/modules/amazon/src/serverGroup/configure/AccountServiceFixtures.js
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
- app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.spec.js
- Fixed broken unit tests
- Fixed missing types and default
- Added new unit tests
No issue created
> fix(aws): Misc. fixes and new unit tests

- app/scripts/modules/core/src/api/ApiService.ts
- app/scripts/modules/core/src/api/ApiServiceDeprecated.spec.ts
need this for an internal plugin
> feat(core/api): Add 'deleteData' argument to REST().delete(deleteData);

- settings.js
Updating AWS settings with cpu credits.
> config(aws) adding cpu credits settings with default false

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
Amendement for #8830
I somehow missed the `Query` field, so just dropping that in
> feat(amazon): Display updated ALB redirect config

- app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
- app/scripts/modules/core/src/presentation/Popover.tsx
fix popup when hovering a pipeline to show description,
when description does not fit the screen we change the placement to the right
https://share.getcloudapp.com/P8umo6Dl
> fix(pipeline/overlay): fix overlay placement with long desc

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/oracle/package.json
- app/scripts/modules/titus/package.json
ebbb32f9f2782955e54e8f263358e9e2e320d717 fix(amazon/securityGroup): Add stack/detail info to help text (#8852)
f16b0775917242a39ae70e86c5541020c898b872 Deangularize instance writer (#8834)
22c59c185ec3b46e5a50145eba09f8e1be56f8c6 fix(aws): Add Connection termination on deregistration flag on NLB's (#8835)
f16b0775917242a39ae70e86c5541020c898b872 Deangularize instance writer (#8834)
f16b0775917242a39ae70e86c5541020c898b872 Deangularize instance writer (#8834)
21bb427c19c302c70bbd082d159a8b5a135e8aa4 fix(cloudFoundry): Update test fixture to prevent intermittent failure (#8855)
f16b0775917242a39ae70e86c5541020c898b872 Deangularize instance writer (#8834)
5b7d95576976076cdb20561591f1ef77503e03f4 fix(pipeline/overlay): fix overlay placement with long desc (#8848) …
> chore(package): amazon@0.0.287 appengine@0.0.26 azure@0.0.264 cloudfoundry@0.0.110 core@0.0.541 google@0.0.31 oracle@0.0.19 titus@0.0.159

- app/scripts/modules/core/package.json
b0139a61faef57e2274c3263a476cccc912328e8 feat(core/loadBalancer): Filter by load balancer type (#8850)
5e45b8525ad9f248572acd5550dbe1a57b7e69bb feat(core/pipeline): Add the ability to disable base os options (#8851)
dde8513022e45dd593e48b717c92631260509655 fix(core/pipelines): break and wrap long comments text (#8748)
e78115ef849fd10f5d2086095f3f9d9e79c5ff66 fix(API): encodeURIComponent for each path() element (#8646)
> chore(package): core@0.0.542

- packages/eslint-plugin/test/api-deprecation.spec.js
Not sure why these tests didn't fail in the original commit. Fixing the expected error messages to match the actual ones.
> fix(core): Fix eslint failures

- app/scripts/modules/core/package.json
ab2873a2c6cf6787d1e8c4945c895d5c88ebaddc feat(core): allow custom stage summary as React components (#8870)
> chore(package): core@0.0.543

- app/scripts/modules/core/package.json
7972a2e5e6d11bdc8249ad87adf325b683e4e679 feat(core): export StageSummary props in core module (#8873)
17bdf716fb22bfe44979656073d7f1f823601aed fix(core): handle errors on confirmation modal submission
509eb4db136d81460588ee89e2e4914613a259a1 feat(core/serverGroups): Intelligently enable/disable server groups in multiselect (#8865)
> chore(package): core@0.0.544

- app/scripts/modules/core/src/subnet/SubnetTag.tsx
Data is already there so, might as well make it accessible:
> feat(core) Expose raw subnet ID

- packages/pluginsdk-peerdeps/package.json
> chore(peerdeps): Upgrade @spinnaker/core to 0.0.544

- app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
> feat(domain/aws): Extend upsert command

- app/scripts/modules/core/src/application/nav/NavItem.tsx
A very tiny fix - vertical alignment of the tooltip.
> fix(nav): fix tooltip vertical alignment

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
33e0fd377c633f3288512a6630c986a53fbd56ef feat(domain/aws): Extend upsert command (#8895)
1ea504a29ad9aa514bc58d6bd63854591429a02c fix(amazon): Stray 0 showing in component (#8894)
d1ef25ce280d003938eb451c4311c5a30e77310c fix(nav): fix tooltip vertical alignment
> chore(package): amazon@0.0.289 core@0.0.547

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
f86c6f5c30194a739ff9d90abd7f4c2bb01ccf6a fix(amazon): Update NLB dualstack constraints for instance targets
f8d3d432203782f1946db8bc4c1843eb9eea14ef refactor(core/ci): Migrate to builds api v3 (#8892)
8f136eb88790d66ae42cf597f55b88cd2cd2d0e0 refactor(presentation): Refer Icon, Illustration members from @spinnaker/presentation
78a655c03aa1c7d09e64440ce6a586fd906577ec refactor(presentation): Update references to illustration and icon modules
c086f91a10896627d595458f4f4bdb07857d632f refactor(presentation): Move illustrations and icons modules to presentation
26e6067795b65a8ffdc93c8add920c69f50be283 refactor(md): organized files in folders (#8897)
> chore(package): amazon@0.0.290 core@0.0.548

- app/scripts/modules/core/src/ci/igor.service.ts
> fix(core/ci): Fix endpoint url typo in getJobConfig()

- app/scripts/modules/core/src/serverGroup/configure/common/ServerGroupNamePreview.tsx
While creating the deployment payload, it is possible to provide SpEL expressions for stack, detail etc and if these expressions evaluate to invalid values, then that could lead to deployment failures. This commit introduces a warning in the server group create/clone wizard when failsafe SpEL expressions are not provided.
> fix(core/serverGroup): Ensure failsafe SpEL expressions are provided

- app/scripts/modules/core/src/application/ApplicationComponent.tsx
- app/scripts/modules/core/src/application/ApplicationContext.tsx
- app/scripts/modules/core/src/domain/IManagedEntity.ts
- app/scripts/modules/core/src/managed/Button.less
- app/scripts/modules/core/src/managed/Environments.tsx
- app/scripts/modules/core/src/managed/EnvironmentsList.tsx
- app/scripts/modules/core/src/managed/ObjectRow.less
- app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
- app/scripts/modules/core/src/managed/StatusCard.less
- app/scripts/modules/core/src/managed/StatusCard.tsx
- app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.less
- app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
- app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
- app/scripts/modules/core/src/managed/artifactDetail/VersionStateCard.tsx
- app/scripts/modules/core/src/managed/artifactDetail/constraints/constraintRegistry.tsx
- app/scripts/modules/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
- app/scripts/modules/core/src/managed/environment/EnvironmentRow.tsx
- app/scripts/modules/core/src/managed/utils/logging.ts
- app/scripts/modules/core/src/presentation/hooks/useApplicationContext.hook.ts
- app/scripts/modules/core/src/presentation/hooks/useInterval.hook.ts
- app/scripts/modules/core/src/utils/timeFormatters.spec.ts
- app/scripts/modules/core/src/utils/timeFormatters.ts
- package.json
- yarn.lock
This PR introduces the new verifications feature:
In addition, it removes styling a bit by removing some of the lines and polishing styles a bit
> feat(md): Environment verification tasks

- packages/eslint-plugin/base.config.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/yarn.lock
Adding prettier eslint plugin to ensure all checked-in code follows prettier formatting.
> feat(lint): Add prettier linter

- app/scripts/modules/amazon/src/instance/index.ts
- app/scripts/modules/core/src/instance/details/InstanceLinks.tsx
- app/scripts/modules/titus/src/domain/ITitusInstance.ts
Updating some interfaces and exports that are needed for a happy build when converting some angular to react w/ typescript.
> fix(domain): Update Titus domain and exports

- app/scripts/modules/core/src/account/AccountService.ts
> fix(core/account): Update AccountDetails interface

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/titus/package.json
8bab7d06f90838ef032a222751c00bfd1ae7fb12 fix: broken link to renamed BlockDeviceConfig.groovy (#8924)
474d03da6f24b14dff3620ea31e2d8c49ef0b5a9 Merge branch 'master' into titus-type-updates
c3cd53c23dae97470f753612a8eb1c949b977f0f Merge branch 'master' into external-vpc-warning
06585c586e33f8c88cd191f03eefde54d7180858 refactor(titus): Create component wrapper with generic functionality
908585b28ef43c304724ea8a5ed459aff492de7d Merge branch 'master' into ipv6-account-conditional
5c7eac6e2228c7f8d9c065b1e1ef768cb7438e47 feat(amazon): Add configurable warnings for subnets
780ad5792b639b81aeb512027168962fc562d75b Update app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
a29792e83d723711b1a7a5f35581b488b037be07 fix(amazon): Remove conditional for …
> chore(package): amazon@0.0.291 core@0.0.550 ecs@0.0.277 titus@0.0.161

- app/scripts/modules/core/src/pipeline/executions/Executions.tsx
#8770 added an automatic redirect to the permalink when users opened an execution under `/executions/` but the specific executionId had already aged out.
This behavior happened any time it ages out, even on a refresh, which after some more thought feels undesirable. Say for example:
1. You expand an execution
2. A few more executions of the same pipeline have run, causing your expanded execution to age out of `Show n executions per pipeline`
3. **What should we do now?**
My original assumption was that the user was looking at the execution that was expanded, so it would be nice if we could keep them in that context.
However, it seems that redirecting them out of the `/executions/` route now feels too jarring, so this PR will revert back to the old behavior where we simply navigate up (to …
> fix(core): Only forward to permalink on initial load

- app/scripts/modules/amazon/src/aws.settings.ts
> fix(aws): Update type for recommended subnets

- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.spec.ts
- app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts
If we're trying to fetch again while fetching the security groups, we now return a promise the will be resolved once the first get request returns. 
Future TODO: This feature is built-in in some packages. Consider using them instead :)
> fix(core): avoid fetching security groups twice

- package.json
- yarn.lock
Upgrading to the latest version and removing unnecessary packages.
> chore(lint): Upgrade @spinnaker/eslint-plugin

- app/scripts/modules/core/src/search/global/GlobalSearch.tsx
- app/scripts/modules/core/src/search/global/GlobalSearchResults.tsx
- app/scripts/modules/core/src/search/global/globalSearch.less
- app/scripts/modules/core/src/search/global/utils.ts
Initiate search on enter. If an exact app match was found, open the app directly.
Bonus: replaced the deprecated "which" with "key"
> feat(core): global search box - search on enter

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
c344366c98ff9a4ea74f6d8e9d6793ae65bf4d31 Merge branch 'master' into aws-secGroups
bd2f60fecb0143328de4bc0e3aac16c207f7f440 fix(aws): Simplify security group extraction
a9be53854a31f3fe7d0fa5d9b5db56de7ca137d5 fix(amazon): Update logic for subnet warning
bbee13dcd7851b4b0388e0c4d449456509570ac4 fix(amazon/loadBalancer): Fix text for cross-zone load balancing
fd516bafc785bd7e40b5f6d21ffb001af7912510 fix(amazon): Instance DNS hrefs when Instance Port is not defined
eb38aba4293c2f67ee7c44a37e28725dacdad03a feat(core): global search box - search on enter (#8948)
14ec907c276c04f4d804f4a1e16a04f008e6ae77 Merge branch 'master' into save-app-notifications
fa96f320ba616511a40ddd95de831740663655bd chore(md): enable strict null check on the editor level (it won't be enforced during compilation) …
> chore(package): amazon@0.0.293 core@0.0.552 titus@0.0.163

- app/scripts/modules/core/src/managed/managed.dataSource.ts
> fix(md): remove beta tag

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
5c26ecc6a9c53e52b23f34dc1305a4286e94b0f9 fix(amazon/subnet): fix NPE when AWSProviderSettings.serverGroups is undefined (#8976)
c3af1842fbef73d3075a281520d2b832fe69b2ef feat(core/application): Export the ApplicationContext values (#8977)
f1efe8246d4ca1435f5a1e21682bf8975a64cab7 feat(core): Allow function components to be overridden (#8970)
687ac675330feacfe07d3b5b120aa802e5b4df54 feat(titus): Add placeholder for custom scaling policy details (#8975)
> chore(package): amazon@0.0.295 core@0.0.554 titus@0.0.164

- app/scripts/modules/core/src/application/search/ApplicationsTable.tsx
- app/scripts/modules/core/src/application/service/ApplicationReader.ts
Show slack channel in Application search if the feature is enabled.
> feat(core): Show slack channel on app search if feature enabled

- app/scripts/modules/core/package.json
ddfc7566af125003889c4f43456b2be6495a5eec feat(core): Show slack channel on app search if feature enabled (#8984)
b175773778f1777aba1f05bdaed5b054e3de8fcf fix(pr): remove config call
ebe8937382423bafd5720434f57c57730d0f42fd feat(md): store resource kinds without version number, and fallback to it if version is missing
55444b84cadc1a2207d232bd05c62381d3290e86 fix(md): missing elb version
> chore(package): core@0.0.555

- app/scripts/modules/core/src/insight/InsightMenu.spec.tsx
- app/scripts/modules/core/src/insight/InsightMenu.tsx
Adds code to make the InsightMenu component overridable.
> feat(core/InsightMenu): Make component overridable

- app/scripts/modules/core/src/domain/IInstance.ts
> fix(core): Update IInstance with some commonly used attributes

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
da315f59ecec9bddf9e31e5af11bda349fd202c0 fix(core): Export ConsoleOutputLink (#8998)
867a0aeb06ef3c9df6bc20ccaf76a9b5f8315f04 fix(core/presentation): Change standard field layout flex to  justify-content: space-between; to align formfield actions on the right hand side (#8995)
3a287e23d32ca48c0b6f14f19d69b9706254329e fix(core): Update IInstance with some commonly used attributes (#9005)
da315f59ecec9bddf9e31e5af11bda349fd202c0 fix(core): Export ConsoleOutputLink (#8998)
2451d83f6f0532cb5be76183e8b66a9c5c6796ce fix(core): Running tasks popover surpassing screen dimensions (#8986)
4862fd3e51da6111d9f4b6224f2cd63969b66f31 feat(pipeline): Render lineage in permalink view
c506d97579e5ea2df35c01437940b0dcdca9f66b feat(pipeline): Refactored SingleExecutionDetails …
> chore(package): amazon@0.0.296 core@0.0.556 titus@0.0.165

- app/scripts/modules/core/package.json
8186440f92bb7af1e35d8ba2fa132a7b021b7fa4 fix(md): constraint status was using the global status var (#9010)
680eddc786064733750941fcf7deb7dbdbb05d53 fix(core): Trim cloud providers after splitting (#9009)
> chore(package): core@0.0.557

- app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
see: https://github.com/spinnaker/front50/pull/915
> feat(core/pipeline): Validate that submitted pipeline is not stale (hasn't been changed by another user)

- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
2ebdb9b fix(pr): added a warning
8bd72b5 fix(pr): only register MD plugin if necessary
c3139a7 refactor(pr): Updated render functions type and moved files around
301b002 feat(pr): add a separate function for rendering the description
6236351 fix(pr): missing docs
0a7f528 fix(pr): renaming
931c885 fix(pr): simplified types
84185ef fix(pr): missing optional
421a7f8 feat(md): new constraint plugin registry
0d83fb3 refactor(md): move constraintRegistry to another folder
c6fd509 feat(core/pipeline): Validate that submitted pipeline is not stale (hasn't been changed by another user) (#9027)
0061587 fix(core/projects): Recent projects: only save the link to project dashboard (#9024)
ba9835a feat(core/ExecutionGroup): make component overridable (#8999)
7e0bfd2 feat(core/Execution): make component …
> Package bump chris berry appengine 0.0.29 core 0.0.559

- app/scripts/modules/amazon/src/domain/IAmazonInstance.ts
- app/scripts/modules/titus/src/domain/ITitusInstance.ts
The attributes added in this PR are referenced in javascript files, but do not exist on the domain. This will cause issues during a very near future migration to react and typescript.
> feat(domain): Extend instance domains

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
2a291a0b381c574365ae88f0307905d2bdee2cb0 feat(domain): Extend instance domains (#9028)
fa681fd264d443e18ec076a58e7fa186f3c01d88 feat(amazon): Show bake warning for migrated pipelines (#9023)
9f3d454c1ae6891f7aa554ebf2a485e7d4d2c248 fix(deck): Handles an undefined reference on `TaskMonitorWrapper`. (#9031)
2a291a0b381c574365ae88f0307905d2bdee2cb0 feat(domain): Extend instance domains (#9028)
> chore(package): amazon@0.0.297 core@0.0.560 titus@0.0.167

- app/scripts/modules/core/package.json
9fe0ed5ece095084812c9f88c98b83445cce2ff2 feat(pipelines): Enable filtering on dynamic categories (#8849)
7e5c836e0cc95de27b1376ef8ab42508902cf43d feat(core/Executions): Make component overridable (#9002)
> chore(package): core@0.0.561

- app/scripts/modules/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
Plus, updated verification texts (not in use at the moment)
> feat(md): change pending verification icon color to blue

- app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
- app/scripts/modules/core/src/application/nav/BottomSection.tsx
- app/scripts/modules/core/src/application/nav/verticalNav.less
This is intended for adding help menus at the bottom of the bar. 
In addition, the navigation bar is now scrollable.
Note: there aren't as many changes as Github shows. Apply the whitespace filter before reviewing :)
> feat(nav): new overridable section at the bottom of the left navigation bar

- .github/workflows/approve_package_bumps.yml
- .github/workflows/ci.yml
> fix(build): pass branch to github workflow - revert

- app/scripts/modules/core/src/ci/components/builds.less
I did this because it's super annoying when running tests
and still annoying (but somewhat less) when running deck locally
> chore(ci): replace hex colors with closes css variables

- app/scripts/modules/core/package.json
80454d37e024bb8b37d1a8d46ad475c2ff6fab65 feat(md): Show resource history link on hover (#9063)
9de0098b7f23083baab31fb2695781bdbd60e92c feat(pipeline): Pipeline Tags config UI (#9056)
> chore(package): core@0.0.564

- app/scripts/modules/core/src/managed/ManagedReader.ts
- app/scripts/modules/core/src/managed/constraints/DependsOn.tsx
This only fixes the order in the artifacts list view
> fix(md): fix order of environments based on the constraints

- app/scripts/modules/core/package.json
7785f840fd5bd31279047efc8c660aa7760ba80b fix(md): fix order of environments based on the constraints (#9069)
> chore(package): core@0.0.565

- app/scripts/modules/core/src/managed/ManagedReader.ts
- app/scripts/modules/core/src/managed/utils/sortEnvironments.spec.ts
- app/scripts/modules/core/src/managed/utils/sortEnvironments.ts
> feat(md): sort environments based on constraints on the main page

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/titus/package.json
3ae687e51992d1294672f78bbb1a041481044fc0 feat(titus): Finish migrating instance details to react (#9034)
3ae687e51992d1294672f78bbb1a041481044fc0 feat(titus): Finish migrating instance details to react (#9034)
0bb9263502188fcbadd4b1d1218f345229e0d184 feat(infrastructure/buttons): Add a new property configurable on sett… (#7822)
b311fbdfa1f7560a83325f1001dc50391bdf047a feat(md): sort environments based on constraints on the main page (#9071)
0bb9263502188fcbadd4b1d1218f345229e0d184 feat(infrastructure/buttons): Add a new property configurable on sett… (#7822)
0bb9263502188fcbadd4b1d1218f345229e0d184 feat(infrastructure/buttons): Add a new property configurable on sett… (#7822)
3ae687e51992d1294672f78bbb1a041481044fc0 feat(titus): Finish migrating instance details to react (#9034) …
> chore(package): amazon@0.0.299 core@0.0.566 ecs@0.0.280 kubernetes@0.0.59 titus@0.0.169

- app/scripts/modules/core/src/managed/constraints/ManualJudgement.tsx
> fix(md): Manual judgement failed text

- app/scripts/modules/core/src/domain/IManagedEntity.ts
- app/scripts/modules/core/src/managed/constraints/AllowedTimes.less
- app/scripts/modules/core/src/managed/constraints/AllowedTimes.spec.ts
- app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
> feat(md): allowed times constraints - add times group and fixed timezone

- app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
Graph links with the same names were causing errors
> fix(core): unique pipeline graph ids

- app/scripts/modules/core/package.json
eacb254fbef47a1dfd8916f1da03a43094c4106a fix(core): unique pipeline graph ids
c3d4601400cb481404707f47d97967ad768348ee feat(md): allowed times constraints - add times group and fixed timezone (#9072)
c92110315030f555358817278123fd6804ec1721 fix(md): Manual judgement failed text (#9075)
> chore(package): core@0.0.567

- app/scripts/modules/titus/src/domain/ITitusInstance.ts
- app/scripts/modules/titus/src/instance/details/TitusInstanceDetails.tsx
> fix(titus/domain): Add titusUiEndpoint to ITitusInstance

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
fb0ad5726b1321bbc9cae378f4a50f388fe5c611 feat(aws): Adding support to view details of an ASG with MixedInstancesPolicy(MIP) (#8960)
a465f7e38bc57d40f45dc436d7347151aac49704 fix(core/pipeline): Avoids checkStale error when saving a pipeline after renaming
30151b53d35a4f4ad5c81fcc0264ce009eb9a970 fix(core/pipeline): Fixes "stale check" failures when saving pipelines twice, also fixes revert behavior of pipeline tags/description
61f10377d21a67826d97f78fb6265f6f091dae71 feat(trigger): Add an optional link to configure a stash trigger (#9035)
cb93996170ccd3438f5deedc8770ae1c2196086b fix(core): Fix lint error
e5aa34f89fad4af9c60ed5a6c020163cc1bd1765 feat(core/taskExecutor): Adds failure message to error (#9083)
fb0ad5726b1321bbc9cae378f4a50f388fe5c611 feat(aws): Adding support to view details …
> chore(package): amazon@0.0.300 core@0.0.568 titus@0.0.170

- app/scripts/modules/core/src/filterModel/IFilterModel.ts
- app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
- app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx
- app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts
See #9022 for rationale, this fixes some bugs and reorganizes the code to match the existing paradigm better.
Supersedes #9022 
Closes #9022
> feat(core/pipeline): filter by stages awaiting judgement

- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
38c9dd168b48f4672e874f559af4cf2c43145de4 chore(cloudfoundry): Implements map load balancer modal. (#9086)
1a6ae753bacc92f32c4d66ff98314a667713ce67 feat(core): updated notifications to react-toastify (#9103)
a0056e2e7cebc1ba71295a4bbd2db9659722049a chore(core): bumped date-fns version (#9101)
> chore(package): cloudfoundry@0.0.115 core@0.0.571

- packages/pluginsdk/package.json
- packages/pluginsdk/scaffold/.lintstagedrc.json
- packages/pluginsdk/scaffold/package.json
- packages/pluginsdk/scripts/check-plugin/asserters/assertJsonFile.js
- packages/pluginsdk/scripts/check-plugin/linters/lint.lintstaged.json.js
- packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
- packages/pluginsdk/scripts/check-plugin/util/readWriteJson.js
- packages/pluginsdk/scripts/husky-install.sh
- packages/pluginsdk/scripts/write-json.js
- feat(pluginsdk): Adds support for asserting a json field should be deleted
- feat(pluginsdk): installs husky git hooks and lint-staged pre-commit hook
> pluginsdk husky lint staged

- app/scripts/modules/amazon/package.json
- app/scripts/modules/appengine/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/kubernetes/package.json
- app/scripts/modules/titus/package.json
496e44af5fb9abf304d9f4e1b08a2f4f0d2a634e chore(rxjs): Migrate to static combineLatest and fix typing errors
a4fc97f3abfa4395079e70c52e856dad4d0ecc68 chore(rxjs): Remove now unused imports of Observable from 'rxjs'
30c3ee8d593973b0c6a87fd0a2dd9a15b10470f0 chore(rxjs): Manually migrate rxjs code in .js files
2a9e2a4bbfbc07f2d5fb8cca4e67276aa3e2c8ea chore(rxjs): Fix combineLatest deprecated calls
c11835cfef079d5d6af8dcfbafa4fe416a059a3e chore(rxjs): Run rxjs 5-to-6 migration tooling
b9a8b58e3499702dad7381d5f19a3cab17dd3e1c fix(redblack): Update redblack fields for angular DeploymentStrategyS… (#9105)
8b9187bc39a7a080edf02fd94be6ccf633cf0ebb fix(titus/serverGroup): Fix height of metrics line chart
a4fc97f3abfa4395079e70c52e856dad4d0ecc68 chore(rxjs): Remove now unused imports of Observable …
> chore(package): amazon@0.0.303 appengine@0.0.32 cloudfoundry@0.0.116 core@0.0.572 docker@0.0.72 google@0.0.35 kubernetes@0.0.62 titus@0.0.173

- app/scripts/modules/core/src/presentation/main.less
This issue happens if addition divs are added above the main page
> fix(style): Ensure that the main div won't overflow the page

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/google/package.json
- app/scripts/modules/titus/package.json
7360252e1a44b2c76c67b9741289a523bbd799c3 chore(eslint): yarn eslint --fix
95a3fecb913f26d1969dae91fa1d4ee8db89cafd feature(loadbalancer): Add the ability to configure 'preserve client IP' on NLBs (#9125)
22859bea9a4a1f2ecbcb7d131f204e9131b756cc fix(core): pushed modal overlay to the background (#9111)
8aeeaf7a470f5704a04c9b54728e5548402cd705 fix(core): fix issue in console log modal (#9134)
716f7b78cf5300dbdddcbb981c622b8b0d9437dc fix(style): this ensure that the main div won't overflow the page (#9130)
408f0ebaa7ebbd942ac369b4cde98cf5887cb08c feat(pipeline): Show completed time in stage details (#9126)
9aeb398ba3a6a49ad9677f2d8b5ba6f8840f2b21 chore(prettier): Just Update Prettier™️
22859bea9a4a1f2ecbcb7d131f204e9131b756cc fix(core): pushed modal overlay to the background (#9111) …
> chore(package): amazon@0.0.304 azure@0.0.269 core@0.0.573 google@0.0.36 titus@0.0.174

- app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBAdvancedSettings.tsx
- app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
- app/scripts/modules/core/src/help/help.contents.ts
Waiting on some clouddriver pieces to roll out. 
Remove constraints on ALBs for dualstacking.
> feat(aws/lb): Internal ALBs can be dualstacked

- webpack.config.js
hundreds of warnings in the console that are driving me nuts and killing my browser...
> chore(webpack): ignore source maps of some packages that are generating warnings

- packages/pluginsdk-peerdeps/package.json
> chore(pluginsdk-peerdeps): Upgrade to 0.0.15

- app/scripts/modules/appengine/package.json
- app/scripts/modules/core/package.json
936c3a1110ac946a3ad1a3b9efc6b675fdbd960c fix(appengine): Allows ng to be injected. (#9156)
94bfcf4e0dee133deed6b216239be8ac4e5a678f fix(deck): Attempt to fix `Cannot read property 'length' of undefined` (#9153)
31e8303623b11505e075ae589b3a7e9a4c3f2f1d fix(core): fix state update for pipeline tags (#9163)
f0086f6d3e04b1bc95df93225bf56651ed1e7528 feat(md): application management (#9154)
> chore(package): appengine@0.0.33 core@0.0.575

- app/scripts/modules/amazon/src/serverGroup/details/sections/LaunchTemplateDetailsSection.tsx
Fixed display of server group without monitoring
Issue: https://github.com/spinnaker/spinnaker/issues/6427
> fix(provider/aws): Fix display of server group without monitoring

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
63ee241037ea1a296e25ba79f2191bd68eb94d83 fix(provider/aws): Fix display of server group without monitoring (#9162)
9a33c5751e60b510de7b1e9becce394fc01851ef feat(md): handle BLOCKED state for constraints (#9168)
f47cc5bf5539592d8ae3fca7c0583ffeb10cfba5 feat(md): show post deploy tasks (#9166)
839dc56c9a0a2f108f063463adc4deae0a30a96d chore(titus): Remove outdated code (#9169)
> chore(package): amazon@0.0.306 core@0.0.576 titus@0.0.176

- app/scripts/modules/core/src/presentation/SpinErrorBoundary.tsx
- app/scripts/modules/core/src/utils/Logger.ts
- app/scripts/modules/core/src/utils/index.ts
A centralized component that will be used to log events in deck. 
The component provides an API to add new loggers and to log events.
> feat(core): logger component

- app/scripts/modules/core/package.json
c751dba6600c586db4526865926d94a8d733d0df fix(core/popover): Scope css back to running tasks popover (#9175)
> chore(package): core@0.0.577

- app/scripts/modules/core/package.json
834af1ed2b5af9dd417347d1e21717ec2e14792d fix(md): check if should use the new ui (#9179)
91e864c19e6e24260bda386f4939d67a08302ce3 feat(core/ManualJudgment): Enhanced ManualJudgment (#8818)
4940c482732b95030164e23abd72e91d3a781bca fix(core): classnames package cleanup (#9173)
> chore(package): core@0.0.578

- app/scripts/modules/core/src/managed/Environments2.tsx
- app/scripts/modules/core/src/managed/managed.states.ts
hotfix to make sure the feature is disabled for everyone
> fix(md): renamed feature flag

- app/scripts/modules/core/package.json
7f6cbad0d9c38c06701ddd3a72878ec21b917992 fix(md): renamed feature flag (#9181)
> chore(package): core@0.0.579

- .eslintignore
- app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
- app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx
Update .eslintignore file to skip `node_modules` and `dist` directories.
> fix(lint): Fix lint errors

- app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
> feat(md): added commit sha to text and a link the tooltip

- app/scripts/modules/amazon/package.json
- app/scripts/modules/amazon/yarn.lock
- app/scripts/modules/docker/package.json
- app/scripts/modules/docker/yarn.lock
- app/scripts/modules/titus/package.json
- app/scripts/modules/titus/yarn.lock
Upgrade all packages to use latest version of @spinnaker/scripts
> chore(bump): Bump packages

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
fcdc3f76605a73a138d9db8dfa5b54a77f1d128a chore(bump): Bump packages
47b520dc04465b9b37aea76d470d49d90f23568a feat(md): added commit sha to text and a link the tooltip (#9213)
fcdc3f76605a73a138d9db8dfa5b54a77f1d128a chore(bump): Bump packages
fcdc3f76605a73a138d9db8dfa5b54a77f1d128a chore(bump): Bump packages
f22396ddf9f61ec4ef7a3a5860330f0b93651abb feat(titus/serverGroup): Add package details section (#9201)
> chore(package): amazon@0.0.309 core@0.0.582 docker@0.0.74 titus@0.0.179

- app/scripts/modules/amazon/package.json
- app/scripts/modules/amazon/yarn.lock
- app/scripts/modules/docker/package.json
- app/scripts/modules/docker/yarn.lock
- app/scripts/modules/titus/package.json
- app/scripts/modules/titus/yarn.lock
- packages/scripts/config/rollup.config.base.module.js
- packages/scripts/package.json
> fix(build): Fix external field for rollup

- app/scripts/modules/amazon/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
26bc67dfb113842093a1d9b57c53ae0d7744e9b3 chore(package): Upgrade @spinnaker/scripts package
26bc67dfb113842093a1d9b57c53ae0d7744e9b3 chore(package): Upgrade @spinnaker/scripts package
26bc67dfb113842093a1d9b57c53ae0d7744e9b3 chore(package): Upgrade @spinnaker/scripts package
> chore(package): amazon@0.0.310 docker@0.0.75 titus@0.0.180

- app/scripts/modules/core/src/managed/Environments2.less
- app/scripts/modules/core/src/managed/overview/Resource.tsx
- app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
- app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
- app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
People complained that they have too many versions and it's hard to see the rest of the environments
> feat(md): only show first two pending versions (with expandable section)

- app/scripts/modules/core/src/managed/overview/artifact/Constraints.less
- app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
added margin to chevron + added padding below the actions properly
> style(md): fix constraints style

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/docker/package.json
- app/scripts/modules/titus/package.json
285c19428b631318f51435f9972cafa71830dab4 chore(packages): Upgrade @spinnaker/scripts
c39f74d3bd5e07178903b5611a9a5c9c973438ae fix(aws/lambda): Shows function details and actions menu. (#9199)
2c547cdb5ed69ef241e3617eeb956065874c9be3 style(md): fix constraints style - adding margin to chevron + add padding below the actions properly (#9227)
7845147c536c0b1eea63e7668a63e043d0d7c4d4 fix(md): environments are now sorted on the backend. We only need to reverse the order in the history heading (#9228)
c40745d0979a2bee32d948b8a9e59fdd8c76d0bc feat(md): added judgedAt time to constraints + switched to CollapsibleSection (#9215)
cca5ad602ee9f9bae74ce3084eb7c2877ea0bc10 fix(md): refetch version on constraint (works in all cases) (#9225)
844ee30b899ec27eb8b4c755aafad4d7251797a9 feat(md): show …
> chore(package): amazon@0.0.311 core@0.0.583 docker@0.0.76 titus@0.0.181

- app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
- app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
> feat(md): build version tooltip

- app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
- app/scripts/modules/core/src/managed/graphql/schema.graphql
- app/scripts/modules/core/src/managed/overview/queries.graphql
- app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
- app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
- app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
- graphql.schema.json
> feat(md): version veto info

- app/scripts/modules/core/package.json
12ed317c16f1c59f87fc770cea23f0a50ebf8918 feat(md): version veto info (#9234)
28f35bcf08fec2069575a730183230073bb5db53 fix(md): lifecycle data was missing in the query (#9233)
5a177192f40b1c317b003565aa2165d7e44a54eb feat(md): limit history versions to 100 (#9232)
78730b1f907bed31e904b473a636aff3718cd4c6 feat(md): build version tooltip (#9231)
f0235b3d076fe5b55b56bea3aeb11cc44f0f19be feat(md): pinned data tooltip info (#9208)
> chore(package): core@0.0.584

- app/scripts/modules/amazon/package.json
10534f5ce2663e107ce304a48743c3cdfca38399 fix(amazon): Add back ng template handling
> chore(package): amazon@0.0.313

- app/scripts/modules/core/package.json
1bb91d2e5f7b20615e980b8e998f6d89bf5eea3a fix(md): wrap tooltip content with span (#9241)
0ecc87de2690dc9b5f0d0f3f94571c76cb52e4bf refactor(core): Reactify scaling activities modal (#9214)
> chore(package): core@0.0.585

- app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
- app/scripts/modules/core/src/managed/overview/artifact/ArtifactActionModal.tsx
- app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
- app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
- app/scripts/modules/core/src/managed/overview/artifact/hooks.ts
- app/scripts/modules/core/src/managed/overview/artifact/utils.ts
- app/scripts/modules/core/src/managed/overview/queries.graphql
- app/scripts/modules/core/src/managed/utils/ActionModal.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
- package.json
- yarn.lock
> feat(md): Added mark as good + refactor actions to mutations and hooks

- app/scripts/modules/core/package.json
f78f141f229153be81cf45056258a0dda665fcd0 feat(md): History - scroll to version + share link (#9222)
9437dcc3eedd705e33a7a4fdff0643148a8315d0 refactor(core): Reactify scaling activities modal (#9248)
34764ed64fc738ab997bfb6b6850e37e5c3f5f40 feat(core): Link to Build and Image in server group header (#9236)
0dd557c0232428b1b89ab49777361da29fddf47c feat(md): Added mark as good + refactor actions to mutations and hooks (#9245)
> chore(package): core@0.0.586

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
50e06cb421402b4c36fbb0810c4704061aefcd71 feat(core): add google analytics to logger (#9246)
50e06cb421402b4c36fbb0810c4704061aefcd71 feat(core): add google analytics to logger (#9246)
50e06cb421402b4c36fbb0810c4704061aefcd71 feat(core): add google analytics to logger (#9246)
> chore(package): amazon@0.0.314 core@0.0.587 kubernetes@0.0.64

- app/scripts/modules/core/src/ci/components/BuildInfoDetails.tsx
- app/scripts/modules/core/src/ci/components/BuildInfoLogsTab.tsx
- app/scripts/modules/core/src/ci/components/BuildInfoSummaryCard.tsx
- app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
- app/scripts/modules/core/src/pipeline/triggers/NextRunTag.tsx
- app/scripts/modules/core/src/presentation/spel/SpelToggle.tsx
- app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx
Making some minor changes to imports that are failing when building using `rollup`.
> fix(core): Fix imports in core for rollup

- app/scripts/modules/core/src/managed/Environments2.less
- app/scripts/modules/core/src/managed/environmentBaseElements/BaseEnvironment.less
- app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
- app/scripts/modules/core/src/managed/overview/baseStyles.less
- app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
- app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.less
- app/scripts/modules/core/src/presentation/main.less
Per @luispollo's request, some improvements for the mobile view + fixes for safari (arrrgggh)
> feat(md): improve styles on mobile

- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
0647665d47a38a3430cac431dcf67360a7a55199 feat(md): improve styles on mobile + large screen (#9260)
7cfaca1271517302b70164d4ddb47e312867d375 fix(core/stage): Remove string interpolation token from ng template for rollup
8d8e8a5997fd6b0f81907b05d8606167817ba350 fix(core): Fix imports in core for rollup
8b6478f18088e31531377b1baf606f81a1817fec refactor(core): Convert alias imports to relative imports in less
6ed36898e83c3620b7622e0cc79599dbaa99aabe feat(md): log ui toggling (#9254)
a2b79f240b46e726c795c6d96d5ea1e731e1adae fix(md): constraint icon size (#9253)
c20da7a67c9dcf178d05c6a886bcd4d026b55fb7 fix(ecs): Cannot see instance details for ecs cluster (#9157)
> chore(package): core@0.0.588 ecs@0.0.287

- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
- app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
- package.json
- yarn.lock
Based on @christopherthielen's comment that the plus/minus icon is confusing.
> feat(md): version history collapsible icon - switch to arrow and cross icon

- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
acc1243f41e08333cfc7728d24ba9d83e90ddcbe fix(style): shrink padding on stage details tabs (#9274)
e6d020ccf028ee4e40d870a8dc685efa81fd8137 fix(core): Re-order imports and remove requires
18039b9000160406b2b9c85a17e695078df22c10 feat(md): version history collapsible icon - switch to arrow and cross icon (#9268)
e5375f0d4122e081bc764cdd79c62b352761d81d feat(core/spinner): Consolidate spinners (#9255)
8a1c8557fbaf94dafb250cc0e9e66baa557e0574 feat(kubernetes/job): Use mostRecentPodName from response (#9170)
> chore(package): core@0.0.589 kubernetes@0.0.65

- app/scripts/modules/core/src/managed/overview/Resource.tsx
> feat(md): show resource account in metadata

- app/scripts/modules/core/src/managed/Environments2.tsx
- app/scripts/modules/core/src/managed/config/Configuration.tsx
- app/scripts/modules/core/src/managed/overview/Resource.tsx
- app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx
- app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
- app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
- app/scripts/modules/core/src/managed/overview/artifact/utils.ts
- app/scripts/modules/core/src/managed/resources/ResourceTitle.tsx
- app/scripts/modules/core/src/managed/utils/ActionModal.tsx
- app/scripts/modules/core/src/managed/utils/logging.ts
- app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
- app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.tsx
Examples:
- Opening modals
- Version actions (pinning, marking as bad)
- Opening builds
- Opening resources
- Opening git links
- Constraint actions
> feat(md): added logs to the important actions and events

- app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
- app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
- app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
- app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
- app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
- app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
- app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
- app/scripts/modules/core/src/presentation/horizontalTabs/HorizontalTabs.less
- app/scripts/modules/core/src/presentation/main.less
The createAt is now a link instead of the share link
> feat(md): moved createdAt to the metadata instead of on the left

- app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
The previous code was re-subscribing again instead of unsubscribing
> fix(nav): fix unsubscribe on unmount

- app/scripts/modules/core/package.json
4d689b5b85efa73c2ec90476ffd2e3135a129ab7 feat(md): New option to display environments side by side (#9269)
ae43ad0102faaf0a35dc4a2984c513f22bb22e2f fix(nav): fix unsubscribe on unmount (#9285)
d998362c672522c01d7ad31dddba61c7f08914bf fix(md): properly redirect the old ui links to the new ui (#9287)
> chore(package): core@0.0.591

- app/scripts/modules/core/package.json
33708ee93ef675d7a074e12691e811847bbed2c7 feat(md): change the deploying state blinking green instead of teal (#9291)
995d622a4bfe30704f7f938a44bbae4368ab5f91 feat(md): set the new UI as the default one, and allow users to opt out (#9290)
3bb4ffea15aa62efb74c4f14891bf0e59b188084 feat(md): show delivery config yml in the configuration tab (#9286)
75a3a251f7226b9e896baa8101dced957099d7cc fix(md): minor improvements based on feedback from #9269 (#9289)
> chore(package): core@0.0.592

- app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
This also includes a small fix for versions with multiple builds
> feat(md): added branch details to the history branch

- app/scripts/modules/core/package.json
- app/scripts/modules/ecs/package.json
f926f9b0d2c300cb2d589f41bedeee31f680c3db feat(md): added branch details to the history branch (#9305)
14588473dfbb8921a78f8e3ad4b1f9662e4e8132 feat(md): Preview environments v0 (#9302)
5292c11c415ed091e88edcb98908f62eb99cb3a9 feat(core): Add type definition for png files
e5a953b0bc53bdffb6546be970102116eb48c13e feat(build): Add custom rollup config for core
6f6add0e68fc3b7c415978dfe4613af68ba8811c fix(ecs): Switch to securityGroupNames and update on subnet change in server group wizard (#9032)
> chore(package): core@0.0.593 ecs@0.0.288

- app/scripts/modules/core/src/managed/managed.states.ts
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
- app/scripts/modules/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
It replaces the url in history to avoid spamming the history page
> feat(md): change url when expanding a version

- app/scripts/modules/core/src/header/SpinnakerHeader.tsx
Added some logging to the navbar menu items, to have a better understanding of their usage
> feat(core): navbar logging

- app/scripts/modules/core/package.json
b75fb8c8fe09cae13541bdbe11366018ff7b22aa feat(core): added navbar logging (#9309)
537bc9dede2342b42d8b27f7cb601ff5d1d7e254 feat(md): change url when expanding a version (#9307)
> chore(package): core@0.0.594

- app/scripts/modules/core/package.json
9da3751a3b7420eb83ee6b589c1f73b12faed572 refactor(packages): Migrate packages to make them independent
> chore(package): core@0.0.595

- app/scripts/modules/amazon/package.json
- app/scripts/modules/docker/package.json
9a9ff96a5f12b02759c6adbd6ee0d1fdf0d870fb chore(package-bump): Update core versions in amazon and docker
9da3751a3b7420eb83ee6b589c1f73b12faed572 refactor(packages): Migrate packages to make them independent
9a9ff96a5f12b02759c6adbd6ee0d1fdf0d870fb chore(package-bump): Update core versions in amazon and docker
9da3751a3b7420eb83ee6b589c1f73b12faed572 refactor(packages): Migrate packages to make them independent
> chore(package): amazon@0.0.316 docker@0.0.78

- app/scripts/modules/titus/package.json
072829df4e1d129ba8cbe2ad9fb411ae8ba373bd chore(bump): Upgrade titus
9da3751a3b7420eb83ee6b589c1f73b12faed572 refactor(packages): Migrate packages to make them independent
> chore(package): titus@0.0.184

- app/scripts/modules/core/package.json
- app/scripts/modules/core/yarn.lock
Temporarily removing storybook dependency to `core` to fix `core-js` imports in `deck-nflx`.
> fix(core): Remove storybook to fix corejs imports

- app/scripts/modules/core/package.json
3566e2e00f1ecedd3313e7e36b1ce1f3573a2837 fix(core): Remove storybook to fix corejs imports
> chore(package): core@0.0.596

- app/scripts/modules/core/src/pipeline/config/stages/common/ServerGroupStageContext.tsx
- app/scripts/modules/core/src/pipeline/config/stages/disableCluster/DisableClusterExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/scaleDownCluster/ScaleDownClusterExecutionDetails.tsx
- app/scripts/modules/core/src/pipeline/config/stages/shrinkCluster/ShrinkClusterExecutionDetails.tsx
Adds clearer descriptions for execution details in `disableCluster` `scaleDownCluster` and `shrinkCluster` stages
> fix(core): Clearer execution details in ServerGroupStageContext

- app/scripts/modules/core/src/managed/Environments2.less
- app/scripts/modules/core/src/managed/Environments2.tsx
- app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx
- app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentItem.tsx
- app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
- app/scripts/modules/core/src/managed/overview/baseStyles.less
feat(md): set grid view as the default option
fix(md): clean warning in config viewer
feat(md): hide grid-list button on the config page
style(md): hide the blue timeline dots on the left to save space in grid view
> feat(md): set grid view as default and improve styles

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/kubernetes/package.json
0a3f56b94821a5d7d80bfc722ec6b2b98e5e5e85 chore(core/amazon): Remove ViewScalingPolicies link from NgReact (#9271)
1adb2245eee324957f9debc82b849517df215fa8 fix(md): constraint time position (#9332)
ce4bfa2513fe2ec6ac3c38ed1a1190e2b357b0a6 feat(md): set grid view as default and improve styles (#9306)
0a3f56b94821a5d7d80bfc722ec6b2b98e5e5e85 chore(core/amazon): Remove ViewScalingPolicies link from NgReact (#9271)
d45b7ea2894bf0186ca3ba1237dc2b41b12a83e1 refactor(core/help): Point angular and ngReact to HelpField (#9258)
0d5d4c492907a1fba151ef0cefaba3f37e460380 fix(md): grid icon (#9331)
8a0f46076eea19db5d29384671cec9617e1a758e feat(md): improve error handling for non-managed applications (#9293)
915274dffd7497d20bfc86787df1676fd3f9079c fix(core): Clearer execution details in …
> chore(package): amazon@0.0.317 core@0.0.598 kubernetes@0.0.67

- app/scripts/modules/amazon/package.json
- app/scripts/modules/docker/package.json
a042c02e9e692b3efb41cc95c54bb08dd020bb17 chore(bump): Upgrade core
a042c02e9e692b3efb41cc95c54bb08dd020bb17 chore(bump): Upgrade core
> chore(package): amazon@0.0.318 docker@0.0.79

- app/scripts/modules/titus/package.json
78e1f8d4c87e146e3330ba83d85edc1a15ac4beb chore(bump): Bumping packages in titus
> chore(package): titus@0.0.186

- app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
- app/scripts/modules/core/src/managed/graphql/schema.graphql
- app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.less
- app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
- app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
- app/scripts/modules/core/src/managed/overview/artifact/VersionOperation.tsx
- app/scripts/modules/core/src/managed/overview/baseStyles.less
- app/scripts/modules/core/src/managed/overview/queries.graphql
- app/scripts/modules/core/src/managed/overview/types.ts
- app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
- app/scripts/modules/core/src/widgets/notifier/notifier.service.ts
- graphql.schema.json
> feat(md): retry version actions (verifications and post deploy)

- app/scripts/modules/core/src/managed/ApplicationQueryError.tsx
- app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
- app/scripts/modules/core/src/managed/utils/logging.ts
- app/scripts/modules/core/src/utils/Logger.ts
Log all errors except for un-managed app error
> fix(md): improve error logging

- app/scripts/modules/docker/package.json
f8d60eeb89c3415f5de8f2a79e8f9644b2cca3d4 fix(docker): Fix @types/angular version
> chore(package): docker@0.0.81

- app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
- app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
> fix(md): fix pin icon from cropping due to overflow-x: auto

- app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
Allowed times is now stateful, this PR updates the statuses to match it
> feat(md): change allowed times fail message

- app/scripts/modules/core/src/authentication/index.ts
fix regression to expose UserMenu so it can be imported from ```@spinakker/core```
> fix(core): expose user menu

- app/scripts/modules/amazon/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
ee2ab2f2a8a4b35210f8da40318bbca857bae1aa chore(*): Remove references to ButtonBusyInidicator (#9283)
b423fe591246fa6583220543cf7fcb95f9fdf928 feat(aws): Adding helper text to indicate priority (#9330)
1eda3e3c1931e3df66ddbc24ba5b5aac9294565c fix(cloudfoundry/mapLoadBalancer): Remove validation on Route in order to allow to save Spel Expressions (#9243)
a3025b41b5c26b8acee36e9891f27449b27ebe56 fix(core): expose user menu (#9360)
f14885d15d17417ca2ba50e0151c79cb01ad6cfd refactor(core/entityTag): Convert entity source components to React (#9340)
233279ed4a1c51f3e7e14c3fb318394e03a47ddc refactor(core): Convert UserMenu to React (#9298)
ff6f32ee317a8f534ca5c33f3c1f385827d23dcb chore(core): Export TaskMonitorWrapper (#9296)
2ce86a34e9e3c04cb5563b24d8ea2cd3b260e3ad feat(md): ignore allowed-time …
> chore(package): amazon@0.0.320 cloudfoundry@0.0.120 core@0.0.601

- app/scripts/modules/core/src/domain/IManagedEntity.ts
- app/scripts/modules/core/src/managed/constraints/AllowedTimes.tsx
In some cases, the backend returns null :(
We should also fix the backend
> fix(md): make allowed time attributes nullable

- app/scripts/modules/core/package.json
1d21f80b7b443e6e9e3af368acd5e578e835d1f4 fix(md): make attributes nullable (#9365)
> chore(package): core@0.0.602

- app/scripts/modules/core/src/managed/overview/baseStyles.less
less converted `1 / 3` to `0.3333` :(
> fix(md): css fix for no artifacts

- app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html
Show the Security Groups for an NLB if there are any:
> feat(amazon/loadBalancer): Show NLB security groups if they exist

- app/scripts/modules/amazon/package.json
- app/scripts/modules/core/package.json
66b7ce860e2116ea2d19e491e1268b5860fe946b feat(aws): Adding support for capacity rebalance (#9369)
d9fd6672141c1584638a2b33730e526841cfaac4 feat(amazon/loadBalancer): Show NLB security groups if they exist (#9371)
1406c2f28070ad33b3538dfe7e5dc93b3dbfe4f5 fix(core/help): Do not render conditionally for angular compatibility (#9373)
d83f60025a40c12dde11158948bdfb15e2eb5f0e refactor(core): Reactify ViewChangesLink, ChangesModal, CommitHistory and JarDiff (#9359)
57ce3d30e26125fed60bb33259137cd95197cde0 feat(md): backend messages  (#9366)
4469f0bf0621e0195dfa46341b600b8f39009ffb feat(md): added links to resources (#9356)
8180812dabd6c54d5ea271f79836fad4351745a4 fix(core/modal): Make SubmitButton compatible with flex display (#9368)
c18b86a7f80f1601a6acb62a3c32a726d89dcbb0 fix(md): css fix for …
> chore(package): amazon@0.0.321 core@0.0.603

- app/scripts/modules/app/package.json
- app/scripts/modules/core/package.json
d4d25f6a4ec1e615d29942193bfd5ddd6273440f fix(build): Fix gradle builds
2a9e13ef1faf047db165cbce2736310cd9bcf616 fix(core/diffs): NPE on ViewChangesLink, minor style tweak (#9375)
> chore(package): app@1.0.1 core@0.0.604

- app/scripts/modules/amazon/src/serverGroup/details/sections/AmazonInfoDetailsSection.tsx
- app/scripts/modules/amazon/yarn.lock
- app/scripts/modules/core/src/reactShims/ngReact.ts
> chore(core): Remove deps on ngReact for EntitySource and ViewChangesLink

- app/scripts/modules/core/src/reactShims/ngReact.ts
This is being imported directly from `@spinnaker/core` now
> chore(core): Remove EntitySource from NgReact

- app/scripts/modules/core/src/utils/Logger.ts
This will allow sentry to share the same list
> fix(core): make ignored errors public

- app/scripts/modules/amazon/src/index.ts
> chore(amazon): Export subnet files

- app/scripts/modules/amazon/package.json
acbfe30e9251321a0ba19a637f1a180f9388a05d chore(amazon): Export subnet files (#9394)
> chore(package): amazon@0.0.323

- app/scripts/modules/core/src/managed/overview/EnvironmentOverview.tsx
- app/scripts/modules/core/src/managed/overview/baseStyles.less
No resources or artifacts should not be represented as error
> fix(md): convert error message to simple text

- app/scripts/modules/app/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
e1176195b4eb72f049b7901f719a1a9144c4a2b2 fix(app): Remove resolutions from app
11a01e77f1ee11ef79fc1980fc507e14f5701665 feat(cloudfoundry): add flag to destroy service stage (#9400)
5d5185d7827d53d0f9a91e4b6f0143c1802aa615 feat(md): Display the raw delivery config instead of the processed one (#9399)
55c97d9c556de3847a975511b35d8bf130ba16d2 fix(md): convert error message to simple text (#9393)
> chore(package): app@1.0.3 cloudfoundry@0.0.122 core@0.0.606

- app/scripts/modules/cloudfoundry/src/pipeline/stages/deleteServiceBindings/cloudFoundryDeleteServiceBindingsStageForm.spec.tsx
This issue wasn't caught by test run executed by CI unfortunately.
> fix(cloudfoundry): Fix failing unit test

- app/scripts/modules/amazon/package.json
- app/scripts/modules/azure/package.json
- app/scripts/modules/cloudfoundry/package.json
- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
b3a4c9c6e58e547fef366226f9a6234ae033eb7d fix(amazon/securityGroup): Prevent cloning security groups into regions they already exist in (#9381)
cce5473b600f173f9df41c7dabe6e2fceb29999f chore(*): Import TaskMonitorWrapper from core instead of NgReact (#9406)
cce5473b600f173f9df41c7dabe6e2fceb29999f chore(*): Import TaskMonitorWrapper from core instead of NgReact (#9406)
cce5473b600f173f9df41c7dabe6e2fceb29999f chore(*): Import TaskMonitorWrapper from core instead of NgReact (#9406)
e3bc17c856e0906bcb70f3fa5f4b2dcd24eab279 fix(cloudfoundry): Fix failing unit test
f75a54bc69bccd883df621c3b9ea29b26c3706cb feat(cloudfoundry): show baked manifest (#9187)
45e8b9fcddc84a5476e1382a78d6e38a59c65f1d feat(cloudfoundry/unbind): Delete Service Bindings stage (#9384) …
> chore(package): amazon@0.0.324 azure@0.0.273 cloudfoundry@0.0.123 core@0.0.607 titus@0.0.189

- app/scripts/modules/core/src/managed/overview/Resource.tsx
> fix(managed-delivery): Fix resource deleting icon

- app/scripts/modules/core/package.json
- app/scripts/modules/titus/package.json
84b21758d9ffd50924e191eb7fa2f742626f4957 fix(managed-delivery): Fix resource deleting icon (#9416)
0f15bb5726b8d6b6d113c27b4d70e49cf29de0d9 chore(core): React CopyToClipboard is the source of truth (#9405)
47f4aa45b0f83a5d56f52f1dbf85f8ec2fcefc5a feat(titus/serverGroup): Add a subnet selector which automatically sets some container attributes (#9398)
PR created via `scripts/publish.js`
> chore(package): core@0.0.608 titus@0.0.190

- .github/release-please-config.json
- feat(release-please): Consolidate all releases into a single PR
- fix(release-please): Fix typo :(
> release please single pr

- packages/titus/src/serverGroup/details/TitusCapacityDetailsSection.tsx
- packages/titus/src/serverGroup/details/scalingActivity/TitusScalingActivitiesModal.tsx
- packages/titus/src/titus.settings.ts
> feat(titus/serverGroup): View server group scaling activities

- packages/scripts/.eslintrc.js
- packages/scripts/config/rollup.config.base.js
fix(rollup): do not log quotes around NODE_ENV
> unweirdify node env logging

- packages/amazon/src/instance/awsInstanceType.service.spec.js
- packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
- packages/core/src/pipeline/config/preconditions/preconditionList.directive.js
- packages/core/src/pipeline/config/preconditions/preconditionType.service.js
- packages/core/src/pipeline/config/stages/manualJudgment/manualJudgmentStage.js
- packages/core/src/pipeline/config/stages/stage.module.js
- packages/core/src/pipeline/config/triggers/git/GitTrigger.tsx
- packages/google/src/serverGroup/details/autoscalingPolicy/modal/upsertAutoscalingPolicy.modal.controller.js
- packages/oracle/src/pipeline/stages/bake/ociBakeStage.js
- packages/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
- packages/titus/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
Remove direct usages of lodash without imports.
> fix(all): Fix lodash global usage

- packages/core/src/managed/ManagedReader.ts
- packages/core/src/managed/config/Configuration.tsx
- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/config/ManagementWarning.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/graphql/schema.graphql
- packages/core/src/managed/overview/queries.graphql
the schema now exposes the rawConfig, it's nicer to grab everything from there
> fix(md): fetch raw delivery config via graphql

- packages/core/src/application/config/dataSources/applicationDataSourceEditor.component.ts
- packages/core/src/pipeline/config/preconditions/types/stageStatus/StageStatusPreconditionConfig.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageConfig.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildValidator.ts
- packages/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSecondarySourceVersionModal.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/IAwsCodeBuildSource.tsx
- packages/core/src/pipeline/config/stages/awsCodeBuild/awsCodeBuildStage.ts
- packages/core/src/pipeline/config/stages/bakeManifest/BakeManifestDetailsTab.tsx
- packages/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecution.controller.ts
- packages/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageConfig.tsx
- packages/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
- packages/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildStage.ts
- packages/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildValidators.ts
- packages/core/src/pipeline/config/stages/savePipelines/SavePipelinesStageConfig.tsx
- packages/core/src/serverGroup/configure/common/wizard/fields/ServerGroupDetailsField.tsx
- packages/core/src/serverGroup/details/scalingActivities/viewScalingActivitiesLink.component.ts
- packages/core/src/slack/SlackChannelSelector.tsx
- packages/core/src/slack/SlackReader.ts
> chore(core): Fix a batch of circular dependencies

- packages/core/src/managed/config/Configuration.tsx
- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/overview/queries.graphql
The config stored via the pipeline is still broken. We need to get rid of this pipeline :)
> fix(md): the raw delivery config is not showing up properly. Hiding it for now

- packages/eslint-plugin/.eslintignore
- packages/eslint-plugin/package.json
- packages/eslint-plugin/rules/ng-no-module-export.js
- packages/eslint-plugin/rules/ng-strictdi.js
- packages/eslint-plugin/test_rule_against_deck_source.sh
- packages/eslint-plugin/tsconfig.json
- packages/eslint-plugin/utils/mockModule.js
- yarn.lock
- feat(eslint-plugin): add typescript support to eslint-plugin
- fix(eslint-plugin): update test_rule_against_deck_source.sh to allow colocated tests and checking packages/*
- fix(eslint-plugin): fix eslint violations inside eslint rules :inception:
> eslint plugin add typescript support

- packages/core/src/managed/ManagedReader.ts
- packages/core/src/managed/config/Configuration.tsx
- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/config/GitIntegration.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/graphql/schema.graphql
- packages/core/src/managed/messages/Messages.tsx
- packages/core/src/managed/overview/queries.graphql
- Show message link if exists
- Add text and link to repo
- Show raw delivery config and last update
- Show messages on the config page (except for the management warning)
> fix(md): git integration improvements

- packages/core/src/managed/config/Configuration.tsx
- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/config/GitIntegration.less
- packages/core/src/managed/config/GitIntegration.tsx
- packages/core/src/presentation/forms/inputs/CheckboxInput.tsx
> style(md): small updates for the git integration styles

- packages/core/src/managed/environmentBaseElements/BaseEnvironment.less
- packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/graphql/schema.graphql
- packages/core/src/managed/overview/EnvironmentOverview.tsx
- packages/core/src/managed/overview/queries.graphql
- packages/core/src/managed/versionsHistory/VersionContent.tsx
- packages/core/src/managed/versionsHistory/VersionHeading.tsx
- packages/core/src/managed/versionsHistory/VersionsHistory.less
- packages/core/src/managed/versionsHistory/VersionsHistory.tsx
- packages/core/src/managed/versionsHistory/types.ts
> feat(md): updated preview environment titles to use the branch name, link to the PR, and show basedOn

- packages/core/src/domain/IManagedEntity.ts
- packages/core/src/managed/constraints/AllowedTimes.less
- packages/core/src/managed/constraints/AllowedTimes.tsx
> feat(md): support max and actual deploys in allowed times constraint

- packages/core/package.json
- packages/core/src/managed/environmentBaseElements/BaseEnvironment.less
- packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/overview/EnvironmentOverview.tsx
- packages/core/src/managed/overview/baseStyles.less
- packages/core/src/managed/overview/queries.graphql
- yarn.lock
> chore(core): show "Deleting" when environment gets deleted

- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/overview/artifact/Artifact.tsx
- packages/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
- packages/core/src/managed/overview/artifact/CurrentVersion.tsx
- packages/core/src/managed/overview/queries.graphql
- packages/core/src/managed/versionsHistory/VersionContent.tsx
- packages/core/src/managed/versionsHistory/VersionHeading.tsx
- packages/core/src/managed/versionsHistory/VersionsHistory.less
- packages/core/src/managed/versionsHistory/VersionsHistory.tsx
> feat(md): use isCurrent to identify the current version + show secondary status when needed (deploying/vetoed)

- packages/app/package.json
- packages/core/src/fonts/icons.css
- packages/scripts/config/rollup.config.base.js
- packages/scripts/package.json
- postcss.config.js
- yarn.lock
- fix(core/fonts): fix 'speak: never' css
- feat(build): remove postcss-nested postcss plugin
> remove postcss nested

- packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/StepPolicyAction.tsx
- packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.ts
- packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.html
Next up: 
- add to titus module
-  delete extra prop
> fix(amazon): Pass in entire step policy object

- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/messages/MessageBox.less
- packages/core/src/managed/messages/MessageBox.tsx
- packages/core/src/managed/messages/Messages.tsx
- packages/core/src/managed/overview/queries.graphql
This PR allows dismissing notifications if `md_debug` is enabled.  
(the tooltip was removed)
> chore(md): dismiss notifications when debug mode enabled

- .prettierignore
- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/graphql/schema.graphql
- packages/core/src/managed/overview/queries.graphql
> feat(md): added "import now" to delivery config

- packages/core/src/managed/config/DeliveryConfig.tsx
- packages/core/src/managed/config/GitIntegration.tsx
Added some logs for a couple of buttons
> chore(md): added logging to git integration

- packages/core/src/widgets/notifier/notifier.component.less
> fix(core): break words in notifications to prevent overflow

- packages/core/src/managed/versionsHistory/VersionHeading.tsx
`status` is one of those awful global variables :(
> fix(md): replaced status with statusSummary

- packages/amazon/src/function/details/AmazonFunctionDetails.tsx
Add Event Source Details for Lambda
> fix(aws/lambda): Lists Event Source details for functions

- packages/amazon/src/function/details/AmazonFunctionDetails.tsx
> fix(aws/lambda): revert for typo and backport for event source

- packages/core/src/config/settings.ts
- packages/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
- packages/core/src/managed/graphql/graphql-sdk.ts
- packages/core/src/managed/graphql/schema.graphql
- packages/core/src/managed/overview/EnvironmentsOverview.tsx
- packages/core/src/managed/overview/PreviewEnvironments.tsx
- packages/core/src/managed/overview/queries.graphql
- packages/core/src/managed/utils/defaults.ts
The link to the docs is optional and will appear only if configured
> feat(md): added a default component if preview environments configured but don't exist

- packages/core/src/managed/environmentBaseElements/BaseEnvironment.tsx
- packages/core/src/managed/versionMetadata/MetadataComponents.tsx
- packages/core/src/managed/versionMetadata/VersionMetadata.less
- packages/core/src/managed/versionMetadata/VersionMetadata.tsx
- packages/core/src/managed/versionsHistory/VersionContent.tsx
- packages/core/src/managed/versionsHistory/VersionsHistory.tsx
> feat(md): clean artifact version details by moving the bake and build details to a popover

- packages/amazon/src/aws.module.ts
- packages/amazon/src/serverGroup/details/scalingPolicy/StepPolicySummary.less
- packages/amazon/src/serverGroup/details/scalingPolicy/index.ts
- packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/TargetTrackingSummary.less
- packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/TargetTrackingSummary.tsx
- packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/targetTrackingPopover.html
- packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/targetTrackingSummary.component.ts
React version of target tracking policy summary that is compatible with multiple cloud providers. Integrated with `@spinnaker/amazon` provider. 
Next steps: 
- integrate with `@spinnaker/titus`
- delete angular files and converters
> refactor(amazon): Target tracking policy summary and popover

- packages/amazon/package.json
- packages/app/package.json
- packages/appengine/package.json
- packages/azure/package.json
- packages/cloudfoundry/package.json
- packages/core/package.json
- packages/core/src/presentation/hooks/useMountStatusRef.hook.ts
- packages/docker/package.json
- packages/ecs/package.json
- packages/google/package.json
- packages/kubernetes/package.json
- packages/tencentcloud/package.json
- packages/titus/package.json
- yarn.lock
- fix(eslint): remove eslint config from packages/app/package.json
- fix(yarn.lock): deduplicate yarn.lock using 'npx yarn-deduplicate yarn.lock'
> deduplicate yarnlock

- packages/amazon/src/domain/IAmazonFunctionSourceData.ts
- packages/amazon/src/function/details/AmazonFunctionDetails.tsx
Added Alias Configuration Details to the Lambda infrastructure view.
> feat(lambda): add alias details to infra view

- packages/amazon/src/serverGroup/details/scalingPolicy/ScalingPolicySummary.tsx
- packages/amazon/src/serverGroup/details/scalingPolicy/StepPolicySummary.tsx
- packages/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/AlarmConfigurer.less
- packages/titus/src/serverGroup/details/serverGroupDetails.html
- Incorporate `ScalingPolicySummary` into `@spinnaker/titus`. 
- Update some layout/style inconsistencies with previous version.
> refactor(titus): Incorporate ScalingPolicySummary

- packages/core/src/managed/versionMetadata/MetadataComponents.tsx
This is a temp fix until the new design lands
> fix(md): build links

- packages/pluginsdk-peerdeps/package.json
Probably need to think longer term about how this package is released, as I can't see many feature commits coming here
> chore(release): bump peerdeps version

- .mergify.yml
Turns out multiple queues is a premium feature.
> chore(build): single Mergify queue

- .mergify.yml
Similar to https://github.com/spinnaker/clouddriver/pull/5617
Read more about strict mode deprecation: https://blog.mergify.com/strict-mode-deprecation/
> fix(aws/lambda): Lists Event Source details for functions (

- .mergify.yml
when they succeed, and request a review on failure
> chore(mergify): automatically merge autobump PRs

- packages/core/src/presentation/forms/validation/validators.ts
Updating email validation to allow for longer domains per [issue-6636](https://github.com/spinnaker/spinnaker/issues/6636)
> Updating email validation to allow for longer domains per issue-6636

- packages/appengine/src/pipeline/stages/deployAppengineConfig/DeployAppengineConfigForm.tsx
- packages/cloudfoundry/src/pipeline/stages/bakeCloudFoundryManifest/BakeCloudFoundryManifestConfigForm.tsx
- packages/cloudfoundry/src/pipeline/stages/createServiceBindings/CloudFoundryCreateServiceBindingsStageConfigForm.tsx
- packages/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
This Pull request addresses a customer reported issue
https://github.com/spinnaker/spinnaker/issues/6648
Spinnaker configuration issue with Oracle object storage
> fix(Oracle): Fixes Spinnaker configuration issue with Oracle object storage

- packages/core/src/config/settings.ts
- packages/core/src/help/HelpMenu.tsx
https://github.com/spinnaker/spinnaker/issues/6744
> fix(links): update link to spinnaker release changelog

- packages/amazon/src/serverGroup/AvailabilityZoneSelector.tsx
Fixing AWS AZ auto rebalancing section by setting the default zones
https://user-images.githubusercontent.com/3614196/199836676-0154c36e-abe7-42c8-a8bf-5500e29bef14.mov
https://user-images.githubusercontent.com/3614196/199836683-2b262537-4645-4c51-8cb9-aebfbc03900f.mov
> fix(aws): Fixing AWS AZ auto rebalancing section by setting the default zones

- packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
The timeout value is now configurable from the UI. If the value is not set in the UI the hardcoded value is used.
Testing:
The rollback failed after 20 min and 8 sec with a timeout of 20min.
To be merged after: https://github.com/spinnaker/orca/pull/4353
> Aws rollback timeout v2

- packages/core/src/help/help.contents.ts
Fix the tooltip to not include the Chart.yaml.
> fix(helm): update tooltip to not include Chart.yaml

- packages/amazon/src/pipeline/stages/rollbackCluster/rollbackClusterStage.html
> fix(timeout): Added feature flag for rollback timeout ui input.

- packages/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.html
As part of resolving issue [6784](https://github.com/spinnaker/spinnaker/issues/6784).Adding changes to correct typo errors.
> fix(google): Resolved typo errors in GCE Autoscaler feature

- packages/kubernetes/src/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
- packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.spec.tsx
- packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.tsx
- packages/kubernetes/src/pipelines/stages/traffic/ManifestTrafficStageConfig.tsx
Reverts spinnaker/deck#9928
reverting this due to reverting the feature, see https://github.com/spinnaker/clouddriver/pull/5865#issuecomment-1426315921
> Revert "feat(Blue/Green): Add warning label and enhance disable/enable manifest stage with Deployment kind."

- .github/workflows/build.yml
> chore(build): fix typo in GHA

- .github/workflows/build.yml
Fixing more typos from https://github.com/spinnaker/deck/pull/9952.
> Node 14 fix

- packages/core/src/deploymentStrategy/strategies/rollingredblack/rollingredblack.strategy.ts
Removing the Experimental from 'Rolling Red/Black'
https://github.com/spinnaker/spinnaker/issues/6832
> update(Rolling Red/Black) remove experimental label

- docker/ports.conf.gen
Closes https://github.com/spinnaker/spinnaker/issues/6839
> fix(security): don't expose server information on error pages
