spinnaker/deck

app/scripts/modules/google/src/image/ImageSelect.tsx
app/scripts/modules/google/src/serverGroup/configure/serverGroup.configure.gce.module.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html

Closes https://github.com/spinnaker/spinnaker/issues/4510
- The problem that this PR is trying to solve is a very slow or totally unresponsive server group modal UI for users with tens of thousands of images per account.
- Replaces Angular `ui-select` component with new React `ImageSelect` component, which uses an `Async` dropdown from the `react-select` library with several custom performance enhancements: 1) Only loads options when three or more characters have been typed 2) Only loads the first 20 matches for a given search string. (I also tested `react-virtualized`, but with tens of thousands of images the virtualization seemed ineffective.)
- Removes all the logic for toggling between searching all images and images that contain the current application's name. Since we are already …

perf(google): improve performance of GCE image selection

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

0e5e66a3fae50abddb98cb2d97036a32907ea811 feat(titus): Adding support for service job processes (#7186)
68ee670d5993c9649bd9cc1c6b312512132dcdac feat({core,amazon}/pipeline): add support per-OS AWS VM type choices (#7187)
68ee670d5993c9649bd9cc1c6b312512132dcdac feat({core,amazon}/pipeline): add support per-OS AWS VM type choices (#7187)

Bump package core to 0.0.391 and amazon to 0.0.203

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifest.validator.ts

Closes https://github.com/spinnaker/spinnaker/issues/4446
- Removes validation preventing multi-manifests to be deployed as part of a Spinnaker-coordinated rollout strategy. Still expects exactly one ReplicaSet, but now permits other resources to be deployed alongside the ReplicaSet. (Also, the designated Service must still be deployed prior to the rollout.)
Related PRs:
Clouddriver: https://github.com/spinnaker/clouddriver/pull/3874
Orca: spinnaker/orca#3034
Example (ReplicaSet + ConfigMap):

feat(kubernetes): allow multi-manifest for rollout strategies

---

app/scripts/modules/amazon/src/loadBalancer/configure/classic/Listeners.tsx

No idea why we defaulted to 0 for the internal port, but this seems to fail silently somewhere in the backend, basically with a task completion that ends up with no listener created (probably because 0 isn't really a port).
80 seems more reasonable since we already default to HTTP anyways. This way if someone forgot to actually configure their desired internal port, at least they'll get a listener created to the wrong port instead of wondering why the listener didn't get created

fix(amazon): Update default internalPort for CLBs to 80

---

app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.controller.spec.js
app/scripts/modules/core/src/pipeline/manualExecution/manualPipelineExecution.html

V2 Templated Pipeline configs require a plan step with the template to find all the parameters, notifications, and triggers. The plan was not being used to render the manual execution modal so inherited items such as parameters were missing. This uses the plan when entering a manual execution flow.
https://github.com/spinnaker/spinnaker/issues/4565

fix(core): Render template triggers, notif, params for manual execution

---

docker/ports.conf.gen

The Deck pod was failing to start after a recent apache2 version bump in the image(2.4.25 to 2.4.38): `(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:9000`
Happening only when SSL was enabled.
Starting from apache2 2.4.28, having multiple `Listen` directive listening to the same socket is forbidden:
- https://svn.apache.org/repos/asf/httpd/httpd/branches/2.4.x/CHANGES
- https://httpd.apache.org/docs/2.4/mod/mpm_common.html#listen
In this case, no need for multiple Listen directive as we always listen on one socket whether SSL is enabled or not.

fix(ssl/apache2): Port conflict in ports.conf.gen

---

app/scripts/modules/core/src/cluster/cluster.service.spec.ts
app/scripts/modules/core/src/cluster/filter/ClusterFilterModel.ts
app/scripts/modules/core/src/cluster/filter/ClusterFilterService.spec.ts
app/scripts/modules/core/src/filterModel/FilterModelService.ts
app/scripts/modules/core/src/filterModel/IFilterModel.ts
app/scripts/modules/core/src/filterModel/filter.model.service.spec.js
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterModel.ts
app/scripts/modules/core/src/navigation/state.provider.ts
app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
app/scripts/modules/core/src/reactShims/react.injector.ts
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterModel.ts

This refactor tries to simply the logic that handles saving and restoring of filters when switching between the tabs of an app.    It does away with most of the manual reading and writing of the URL's query parameters in favor of some router hooks.  I believe the URL manipulation was responsible for most of the "crazy celery" bugs we have witnessed so far, although I think we've addressed most of those bugs separately.
There is more than can be done to simply further (such as avoiding statefulness in FilterModel altogether, and reducing collaborators that try to manually drive the FilterModel lifecycle), but we are currently held back by the AngularJS code that mutates objects and responds to object mutations.
Additionally, there is more work to be done regarding saving and restoring …

Simplify filtering logic

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/google/package.json
app/scripts/modules/kubernetes/package.json
app/scripts/modules/titus/package.json

2dbc696243b4d4a068b182f9bee64256e4d0db25 test(core/filterModel): Add tests for restoring filters on router transitions, remove tests for removed functionality
f6dbdf5150fc6f5b62546248cd151fd083182370 refactor(core/filterModel): Simplify the AngularJS compatibility code which syncs the 'sortFilter' object and the router params - Removed the FilterModelServiceConverters code which duplicates the router param types code
d39ab96f71ac1a023a9aa17ff75eeeb182ced293 refactor(core/filterModel): Use router hooks to save/restore filters
39a27e6cd4332c11c7a93b662711364b35bbc319 fix(core/reactShims): Fix the state.go wrapper such that it correctly exposes the `transition` (it's been inconsequentially broken a long time and nobody noticed)
ac2f61c3a182823d445c9f6e047358504d04e801 fix(core/pipeline): …

Bump package core to 0.0.392 and kubernetes to 0.0.26 and google to 0.0.8 and amazon to 0.0.204 and titus to 0.0.105

---

app/scripts/modules/core/src/filterModel/FilterModelService.ts

Something in our bundling was considering the switch statement as something that can be minified out. Changing it to a map so that this doesn't happen while we continue digging.

fix(core): Changing switch to a map

---

app/scripts/modules/core/src/pagerDuty/PageModal.tsx
app/scripts/modules/core/src/pagerDuty/pager.states.ts

This change allows more than just a single default subject/details combination to pre-populate the Send Page modal.
I'm not loving the URL reading/syncing but still settled on this approach because it is the most frictionless for users.

feat(pager): Allow providing pager duty subject/details in URL

---

app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx

- I think the conversion of the trigger component to React may have introduced an issue where we fail to save the `type` of a trigger. This manifested as the validation being missing from the pipeline config, and the trigger not being visible if you were to save/exit the pipeline config, and then click back into the pipeline config.
- Resolved this by updating the trigger model on type change instead of only the state of this component. Also ended up removing the component state altogether to prevent other bugs that could result from it getting out of sync. LMK what you think, thanks!

fix(core): save and validate trigger type in pipeline config

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx

if the logs capture selector changes to `none` we should null out the
`propertyFile` field. the `consumeArtifactSource` field is used as a
flag for deck to determine which option is selected but it isn't taken
into account in orca. so, if `propertyFile` is non-null, orca will still
try to find properties even if we have `consumeArtifactSource = none`.
Fixes spinnaker/spinnaker#4642

fix(k8s/runJob): null property file if value none

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/kubernetes/package.json

f38580f3c4d04bb554d25dbdad2b3e573d84c046 fix(core): save and validate trigger type in pipeline config (#7241)
f37ccf05a02e5248849a2d8d2459a1c6535d60b2 feat(pager): Allow providing pager duty subject/details in URL (#7242)
af4a1ad9d2bc66922ddd0127c05725670893e29a fix(k8s/runJob): null property file if value none (#7243)
70ea40b2781333b0591ba822cfb8a631ed8781ee fix(kubernetes): fix radio button alignment in deploy manifest stage (#7240)
d3249c9e2173cfd3652f6fb8a95c2fb5f2367984 feat(aws): Support new artifact model for deploy cloudformation (#7180)

Bump package core to 0.0.395 and kubernetes to 0.0.27 and amazon to 0.0.205

---

app/scripts/modules/core/src/presentation/forms/FormField.tsx
app/scripts/modules/core/src/presentation/forms/interface.ts

This fixes a bug which blocked usage of the `FormField` component without a name prop. 
```js
<FormField
input={TheInput}
// no name specified
/>
```
Also fixes the typing for onChange handler allowing (formik provides two overloads, and the correct one cannot be inferred)
Previously, `e` had implicity `any` type
```js
<FormField onChange={e => handleEvent(e)} />
```

fix(core/presentation): Default FormField 'name' prop to '', not noop

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx

Fixes spinnaker/spinnaker#4656

fix(k8s): fix bake manifest selector

---

app/scripts/modules/core/src/manifest/stage/JobManifestPodLogs.tsx

adding a couple flex fills to ensure that the model fills the screen
without overflowing. now the log output scrolls when it overflows and
the rest of the modal stays static.

fix(k8s): fix job log modal overflow

---

app/scripts/modules/kubernetes/src/pipeline/stages/runJob/configureJob.controller.js

Using a v2 account would have `com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubernetesRunJobOperation` be called and throw an NPE at line 70, because there's no manifest.

fix(k8s/runJob): Allowing only v1 accounts for v1 runJob

---

app/scripts/modules/core/src/manifest/stage/JobStageExecutionLogs.tsx
app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/PreconfiguredJobExecutionDetails.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx

When the manifest had no namespace explicitly provided, the external logs URL couldn't be prepared.
Now sourcing the namespace from `context.jobStatus.location`, reusing the existing variable.
Also removed the `manifest` property from `JobStageExecutionLogs` because unused.

fix(k8s/runJob): External logs URL support manifest with implicit default namespace

---

app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts

The stage execution detail UI components that are customized per cloudProvider could only be displayed if `stage.cloudProvider` or `stage.cloudProviderType` was set, otherwise defaulting to `aws`.
The RunJob stage status was always defaulting to the AWS UI even the stage was configured for another cloud provider. The stage configurations which aren't force-setting unknown fields (like "cloudProvider") in their `IStage` instance would not have their cloudProvider resolved.
A long term solution would be to add the the `IStage.cloudProvider` field in the IStage type or to make every stage configs use stage.context.

fix(core/pipeline): stage executionDetailsSections resolving the wrong cloudProvider

---

app/scripts/modules/appengine/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

Closes https://github.com/spinnaker/spinnaker/issues/4676
- Fixes longstanding bug that manifests as the default appengine account always being displayed in server group modals, even if another account is actually associated with that server group.
- Will patch into 1.13, 1.14, and 1.15.

fix(appengine): handle multiple cluster accounts in server group modal

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.ts

for webhooks that have `waitForCompletion=true` (i.e. monitored webhook) it is
desirable to have an indication of cancellation (either user cancels execution
or the execution is terminated due to some failure)
corresponding `orca` PR: https://github.com/spinnaker/orca/pull/3069

feat(webhooks): add support for cancellation to webhooks

---

app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts

Executions that never started wrecked havoc on time boundary sorting because we didn't use `buildTime` as a fallback and only sorted by `startTime`:
No more! With this, we can safely go 88 mph again.

fix(executions): Fix time grouping with never started executions

---

app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx

... because it's super duper slow
When using the `ReactSelectInput` component, we will disable `ignoreAccents` logic by default.

feat(core/form): Disable ReactSelect ignoreAccents by default

---

app/scripts/modules/core/src/pipeline/config/triggers/RunAsUser.tsx
app/scripts/modules/core/src/presentation/forms/FormField.tsx
app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useLatestPromise.ts
app/scripts/modules/core/src/presentation/index.ts

This PR does two things to the `useLatestPromise` react hook:
- Adds `refresh()` api
```js
const fetchStuff = useLatestPromise(() => fetch('http://stuff.com').then(res => res.json())), []);
return (
<>
<pre>{JSON.stringify(fetchStuff.result, null, 2)}</pre>
<button onClick={fetchStuff.refresh()}>Refresh</button>
</>
```
- Changes the return value from an Array of tuples to an object with properties
before: 
```js
const [thingData, status, error, requestId] = useLatestPromise(() => getThings(), [])
```
after:
```js
const { result, status, error, requestId } = useLatestPromise(() => getThings(), [])
```

feat(core/presentation): Add refresh() api to useLatestPromise react hook

---

app/scripts/modules/core/src/forms/index.ts
app/scripts/modules/core/src/forms/mapEditor/MapEditor.tsx
app/scripts/modules/core/src/forms/mapEditor/MapEditorInput.tsx
app/scripts/modules/core/src/forms/mapEditor/MapPair.tsx

This PR migrates the `MapEditor` component to a `MapEditorInput` component which roughly conforms to the controlled input api.  As an `Input`, this component can now be used with the `FormField`/`FormikFormField` API.  The state has been removed and pulled up.  For backwards compatibility, a new `MapEditor` component that is compatible with non-controlled usage has been added.
Usage of this `MapEditorInput` component (see the Triggers PR) highlights a gap in the `FormikFormField` api.  This input returns an object with multiple keys/values, not a primitive.  In order for this to work with the current api, the `errors` object has to be passed into the input separately as `formik.errors.[property]`.  I think this may prompt a change to the API where a "Composite Input" (something that …

Migrate Map Editor to be a React controlled input

---

app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/cloudFormationTemplateEntry.component.ts

When paired with the changes in https://github.com/spinnaker/orca/pull/3024 and https://github.com/spinnaker/clouddriver/pull/3849, this makes it possible to use Yaml instead of Json in the editor, and it will also accept CloudFormation specific functions like `!Ref` and `!Join`. Since Json is a subset of Yaml, Json will still be accepted and parsed correctly.
Cloudformation specific YAML:
This will be parsed as a string because of the `!Join`:
"Valid" Json and Yaml will be parsed into a map/list as before.

feat(cloudformation): Make the template editor more lenient

---

app/scripts/modules/cloudfoundry/src/serverGroup/configure/serverGroupCommandBuilder.service.cf.ts

When the imported server group had no routes, the routes property would be undefined where it should have been an empty array. spinnaker/spinnaker#4711

fix(cf): Deploy stage config template import missing routes

---

app/scripts/modules/core/src/application/config/applicationAttributes.directive.html
app/scripts/modules/core/src/application/modal/editApplication.html
app/scripts/modules/core/src/application/modal/newapplication.html
app/scripts/modules/core/src/application/modal/upsertApplication.help.ts
app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx

Felt like a weird ask but the use-case actually behind this is users just want to resubmit a new execution with the same parameters as an existing one _regardless of whether the existing one is active or not_.
Most of the time this is not necessary and we wouldn't want to globally add clutter by showing the rerun button even on active executions so hiding it behind an application attribute seemed like a good compromise.

feat(executions): Allow rerun on active executions

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManualExecutionBakeManifest.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts

Closes https://github.com/spinnaker/spinnaker/issues/4628
Allows helm chart artifact names and version to be overridden during manual execution under the following conditions:
- The pipeline has exactly one Bake (Manifest) stage
- The pipeline has exactly one expected artifact of type `helm/chart`
The specific type of workflow this unblocks is users setting either the helm chart Match Artifact name and/or version as a regular expression (for example, `.*` to match all versions) who want to manually test and select a certain name and/or version at pipeline run time. I only tested this with artifacts rewrite _off_ but since it's supposed to be backwards compatible this should work with it on as well.

feat(helm): allow manual execution overrides for helm charts

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/RunJobExecutionDetails.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/runJobStage.ts

adds support for artifacts in the v2 run job stage. very similar to
deploy manifest.

feat(provider/k8s): support artifacts in run job

---

app/scripts/modules/amazon/src/loadBalancer/configure/classic/HealthCheck.tsx
app/scripts/modules/cloudfoundry/src/presentation/forms/serverGroup/Services.tsx
app/scripts/modules/core/src/pipeline/config/stages/entityTags/ApplyEntityTagsStageConfig.tsx
app/scripts/modules/core/src/pipeline/config/stages/entityTags/TagEditor.tsx
app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
app/scripts/modules/core/src/presentation/forms/FormField.tsx
app/scripts/modules/core/src/presentation/forms/FormikFormField.tsx
app/scripts/modules/core/src/presentation/forms/README.md
app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionField.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionRegexField.tsx
app/scripts/modules/core/src/presentation/forms/fields/renderContent.tsx
app/scripts/modules/core/src/projects/configure/FormikApplicationsPicker.tsx
app/scripts/modules/core/src/projects/configure/ProjectAttributes.tsx
app/scripts/modules/google/src/serverGroup/details/stateful/UpdateBootImageButton.tsx

In `FormField` and `FormikFormField`, always use render prop to render the input and layout.  Do not pass class references.

refactor(core/presentation): use render props everywhere

---

app/scripts/modules/core/src/pipeline/manualExecution/Triggers.tsx

In Manual Execution dialog, we have a dropdown where a user selects the desired trigger.
When they change the selected trigger, we now force the trigger's custom component to remount.
This is a kludge and some day we should remove it.
Instead, all the trigger type components should properly respond to changes in the props passed to it.

fix(core/pipeline): Refresh jenkins jobs component when manual execution trigger is changed

---

app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useData.ts

Pulling `useData` out so it can be reused in all the places.
Credit to @christopherthielen who actually wrote this.
Me? I just move bits back and forth to pad my commit count.

refactor(hooks): Pulling out useData

---

app/scripts/modules/core/src/domain/ITask.ts
app/scripts/modules/core/src/notfound/NotFound.tsx
app/scripts/modules/core/src/pipeline/pipeline.states.ts
app/scripts/modules/core/src/task/TaskNotFound.tsx
app/scripts/modules/core/src/task/task.states.ts

Similar to #7076 
Redirects from `/#/tasks/8675309` to `/#/applications/sandgnat/tasks/8675309`

feat(tasks): Adding redirect for task by id without application

---

app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
app/scripts/modules/core/src/pipeline/manualExecution/Triggers.tsx

Adding `key={trigger.description}` to `Triggers.tsx` in a recent PR had an unexpected side effect of remounting the component when this submit method deletes the trigger 'description' field.
Clone the trigger before mutating to stop this.
Also pass the correct trigger object reference to `triggerChanged` invoke in `Triggers.tsx`

fix(core/pipeline): Fix github trigger manual execution missing 'hash' property

---

app/scripts/modules/core/package.json

6d53fafe17d993233884ca6e8767be4c8882ca4a fix(core/pipeline): Fix github trigger manual execution missing 'hash' property Adding `key={trigger.description}` to `Triggers.tsx` in a recent PR had an unexpected side effect of remounting the component when this submit method deletes the trigger 'description' field. Clone the trigger before mutating to stop this.
a67226c10c5994a0210e826024d9026c39a8c54c feat(tasks): Adding redirect for task by id without application (#7307)

chore(core): Bump version to 0.0.400

---

app/scripts/modules/core/src/artifact/react/ArtifactEditor.tsx
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/ExpectedArtifact.tsx

Fixes the logic to default an artifact account to the correct type. The previous logic always set the first one from the list.

fix(artifacts): fix artifact account default logic

---

app/scripts/modules/core/src/pipeline/service/ExecutionsTransformer.ts

Oh boy, this was a fun one.
Reverting a tiny piece of https://github.com/spinnaker/deck/pull/7217/ which regressed the ordering of the execution markers due to incorrect calculation of the phases.
Basically, sorting stages unconditionally before each recursive called guaranteed that in subsequent recursions, parents are iterated over before their children. This is important because otherwise, in the terminal condition (`allPhasesResolved`), we could get a buggy not-so-corner-case where:
1. Child is iterated over before its parent
2. Child's phase is set to its parent + 1 (lets say parent=2 so child is now 3)
3. Parent's phase is incremented (parent is now 3)
4. Child's phase doesn't get updated to 4 (parent + 1) and could get sorted before it's parent because when `phase` is identical, we …

fix(executions): Fixing execution marker ordering

---

app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx

Otherwise we'll get unexpected behavior on crazy pipelines that have things like `foo.bar.baz` as the name.

fix(execution): Parameter names should be treated as strings

---

app/scripts/modules/core/src/presentation/navigation/PageNavigator.tsx

Shouldn't rely on `child.type.name` when adding the menu items because the nightly build does not contain the name `PageSection` but `PageSection_ PageSection` instead.

fix(core/pipeline): fix side menu rendering for trigger config

---

app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js

Fixes https://github.com/spinnaker/spinnaker/issues/4585
In general, there's more to work to done here re: making templated ECS server group creation useful. Example: right now we're limited to copying over fields provided by [IServerGroup](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/domain/IServerGroup.ts), which omits many ECS-specific values.
However, this change DOES copy over what we can at the time `buildServerGroupCommandFromExisting` is called, vs. not working at all (current state).

fix(ecs): Fix creation of new ECS server group from existing

---

app/scripts/modules/core/src/forms/mapEditor/MapEditor.tsx

This effectively reverts the changes to `MapEditor` made in https://github.com/spinnaker/deck/pull/7299, while retaining the new `MapEditorInput` as-is.
We observed an issue with the `TitusRunJobStageConfig` component where `DockerImageAndTagSelector` was failing to properly fetch and display image org/name autocomplete data, which we eventually tracked back to a change in behavior (`onChange` gets called immediately on mounting) between the legacy `MapEditor` and the new, hook-based adapter that took `MapEditorInput` and made it appear to work like `MapEditor`.
After looking at the usage of the legacy `MapEditor` and the way in which the behavior change broke things, we feel it's appropriate to do two things:
1) Fix the immediate-term regression we know about — and guard against …

fix(core/forms): revert legacy MapEditor adapter to old component

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/kustomize/BakeKustomizeConfigForm.tsx

adds support for kustomize in the UI. the main user input is a single
kustomize file which tells the bakery what it needs to do to render the
manifests. broke the helm config form into a new component as well.
putting this behind a feature flag because the backend isn't complete
yet. will remove once we merge the backend.

feat(bakeManifest): add kustomize support

---

app/scripts/modules/core/src/pipeline/config/triggers/triggers.module.ts

[This commit](https://github.com/spinnaker/deck/commit/bec54dfa5f0b9c55b7fc8062cf47784f972a0107) removed the artifacts module as an explicit dependency of the triggers module. This manifested as a broken Produces Artifacts UI when artifacts rewrite is disabled, since the Produces Artifact component is still in angular and expects the angular Expected Artifact component to be there.

fix(core): fix produces artifacts UI

---

app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/PatchManifestStageForm.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx

fix(core): fix vertical alignment of radio buttons
- Previously, even if the `inline` prop to `RadioButtonInput` was falsy, the radio buttons would not display vertically. Moves the relevant classes to directly wrap the input to resolve this.
fix(kubernetes): make all kubernetes v2 stages use vertically aligned
- For visual consistency, makes all horizontal radio buttons in Kubernetes V2 stages vertical.

 fix(core): fix vertical alignment of radio buttons

---

app/scripts/modules/core/src/notification/modal/NotificationDetails.tsx

Echo expects the custom message structure to be:
```
message: {
"pipeline.starting": {
text: 'foo'
}
}
```
So we have to set the path to be `message["pipeline.starting"].text` instead of `message.pipeline.starting.text`, which would result in:
```
message: {
pipeline: {
starting: {
text: 'foo'
}
}
}
```

fix(notifications): Fixing custom message text shape

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/kubernetes/KubernetesArtifactEditor.tsx

the match artifact editor used for kubernetes match artifacts wasn't
working right. previously, you were only presented with a single
reference field which didn't capture all of the data we needed to match
on artifacts. instead of something like `kubernetes/configMap` the
default artifact type was `kubernetes/REFERENCE` which is not a valid
type but there was no way to change it.

fix(artifacts/k8s): fix rewrite k8s artifact edit

---

app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html
app/scripts/modules/titus/src/serverGroup/details/serviceJobProcesses/ServiceJobProcessesSection.tsx

Just running the service job processes through `robotToHuman` so they're not just raw camelCase.
Also correcting the section title from Service Job `Policies` to Service Job `Processes`. Whoops!

refactor(titus): Making service job processes human friendly

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/kustomize/BakeKustomizeConfigForm.tsx

when `artifactsRewrite` is enabled the `setArtifactAccount` method on
the delegate isn't fired. so we need to set the artifact account
manually.

fix(kustomize): fix artifact selector

---

app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
app/scripts/modules/core/src/presentation/forms/inputs/DayPickerInput.less
app/scripts/modules/core/src/presentation/forms/inputs/DayPickerInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/index.ts

This fixes a regression in the date picker for date parameters in the manual execution dialog.  The core bug was a simple typo of `parameter` vs `parameters`.
I also switched to `FormikFormField` and added a `DatePickerInput` compatible with the spinnaker `FormField` system.  This enables surfacing of `required` validation.  There's still some work to do determining how to add classnames to the nested `input` component.  In the meantime, I added a css kludge that looks ugly, but is better than nothing.
I'm going to merge this optimistically, but please review at your leisure.

Fix date picker parameters in manual execution dialog

---

app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.less
app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx

There's a couple bits of data about a resource we expect folks to care about early on: the event history of a resource, and the underlying config/definition for the resource that Keel has on file. This adds a dropdown to managed resources in the infrastructure views that lets folks see both, as new tabs with the raw JSON payload (opting for JSON instead of YAML to start, as we already do that across spinnaker and JSON is easy to use with the API ad-hoc). Design is quick and dirty for now, as we're not sure what we'll need in the coming months.

feat(core/managed): Add resource dropdown with links to history + source JSON

---

app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

Seems like in some cases we can end up with `pipeline.triggers` undefined.
While I believe this is fixed in front50, instead of having deck break whenever triggers are `undefined`, we can easily just protect against it instead.

fix(triggers): Protecting from undefined triggers

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

d8f1a51e910e5f1ff6008ba14f78c56e9df80d77 fix(triggers): Protecting from undefined triggers (#7377)
ad4c1447c6134b8c823d9b92f12364754a11168a feat(core/managed): Add resource dropdown with links to history + source JSON (#7376)
3665d3ec9387764573162a62c20f938e94002073 fix(typos): fix a few typos in help messages (#7373)
373f581e0689a0e1d3873c7b4cc6948fafadcf8e fix(titus): Removing NLB as it is not compatible with Titus (#7317)

Bump package core to 0.0.406 and amazon to 0.0.209

---

app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

We recently added the ability to re-run active executions (#7293). Turns out there are some junk fields in execution triggers that have historically been fine to accidentally include when manually triggering (e.g. `executionId`, `eventId`), _but_ when an execution is running there's a `correlationId` field that will thwart any attempts to trigger another pipeline. This just strips out those junk fields when a re-run modal is mounted, which seems to do the trick.

fix(core/pipeline): exclude correlation IDs (and more) when re-running

---

docker/run-apache2.sh
docker/setup-apache2.sh
docker/spinnaker.conf.gen
docker/spinnaker.conf.ssl

Apache is configured by default to log to `/var/log...` which fills up real quick with logs from kubernetes health checks and regular traffic, eventually the pod runs out of space.  This modifies the config to log to stdout/stderr instead inline with docker/kubernetes best practices and should help protect the filesystem of the containers/pods.
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

configure apache to log to stdout/stderr

---

app/scripts/modules/google/src/instance/gceInstanceType.service.js
app/scripts/modules/google/src/instance/gceInstanceTypeDisks.ts

Band-aid for https://github.com/spinnaker/spinnaker/issues/4859.
Should be reverted pending investigation of root cause.

fix(google): add default gce instance type disk constants to front end

---

app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

Allows pipelines to provide extra information/context to users manually triggering the pipeline.
Can also be injected when we're programatically opening the start manual execution modal.

feat(pipeline): Custom alert for start manual execution dialog

---

app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

- Fixes regression introduced by https://github.com/spinnaker/deck/pull/7406 caught by functional tests that run with the nightly build
- When opening the manual execution modal from the top level of Deck's Pipelines view (rather than on a specific pipeline), `props.pipeline` is undefined.

fix(core): fix manual execution

---

app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx

Refactored this method a couple times and accidentally ended up with the wrong boolean.
As the comment states, when cloudProviders is missing (as in an empty array), we want to assume it is compatible. This means `isIncompatibleWithAllProviders` should be `false`. Accidentally left it as `true` from when this method was "is compatible" instead of "is incompatible".

fix(amazon): Fix compatibility when cloudProviders missing

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

b396658cc8a0f400bb2dadd474bb3e355573284c fix(core): fix manual execution (#7408)
476ad6255f4e871d8d6d7de3672f42b683533eaf feat(pipeline): Custom alert for start manual execution dialog (#7406)
ec1d32f27ce1ca9d04a4c6bde0c44227a9eb74fd fix(help): reflect reality in rollingredblack help text bubble-things (#7405)
23540b61003d8eb08c73ee9e53d6ff15e69c5ecd fix(nexus): nexus trigger selectable in UI (#7381)
2821438ce34f1676620bad6f66b13feec7b95f07 fix(amazon): Fix compatibility when cloudProviders missing (#7410)
f491ac69f3ed00b3afed738d4ffba0e5f34b8259 feat(titus): direct link to stdout and stderr (#7400)

Bump package core to 0.0.409 and amazon to 0.0.212 and titus to 0.0.111

---

app/scripts/modules/core/src/artifact/react/ArtifactEditor.tsx
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/ArtifactEditor.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/index.ts

Some recent changes to the Expected Artifacts feature has severely broken backwards compatibility with artifacts that have a custom type (for instance Igor can create artifacts with type `deb` or `rpm`). This commit will make Deck be more lenient when it encounters legacy artifacts that does not strictly adhere to the new standard. It will also add back the UI fields `type`, `name`, `version` and `location` for custom artifacts.

fix(artifacts): Support custom artifacts with custom type

---

app/scripts/modules/core/src/pipeline/config/stages/bake/ManualExecutionBake.tsx
app/scripts/modules/core/src/pipeline/manualExecution/DryRun.tsx
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
app/scripts/modules/core/src/pipeline/manualExecution/NotificationDetails.tsx
app/scripts/modules/core/src/pipeline/manualExecution/PipelineOptions.tsx
app/scripts/modules/core/src/pipeline/manualExecution/Triggers.tsx

Most of the fields that end up inside a manual execution modal are currently either:
- A vanilla bootstrap layout + input with hand-rolled logic for everything
- A `FormField`/`FormikFormField` that sets up the input + state management, but doesn't have a label and uses vanilla bootstrap grids to add labels and layout.
When the modal itself got moved to react, one of the sub-components that got migrated was the dry run option, which got moved to a full-on `FormikFormField` with a `StandardFieldLayout`. Turns out that layout really does not play nicely with the existing standard bootstrap columns for the modal in a variety of ways — widths are off, flex layouts don't match, and snapping things to a stacked layout at small widths isn't consistent.
To get this fixed cosmetically for now, I'm …

fix(core/pipeline): standardize manual execution field layouts

---

app/scripts/modules/titus/src/migration/titusMigrationConfigurer.component.html

This will eventually be removed, but for now the ask is to make it not configurable.

chore(titus): Deprecating pipeline container migration strategy

---

app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

5d2e469 feat(core/pipeline): Add timestamp for failed executions (#7419)
3cfb3f1 feat(core/pipeline): Make custom artifacts more readable (#7418)
0034fa8 fix(core/pipeline): Add space before Source-link for failed executions (#7420)
bce3ac5 fix(core/pipeline): standardize manual execution field layouts (#7413)
9c0a994 fix(artifacts): Support custom artifacts with custom type (#7415)
97c85d9 chore(titus): Deprecating pipeline migration strategy (#7414)

Bump package core to 0.0.411 and titus to 0.0.112

---

app/scripts/modules/core/src/domain/IExecutionTrigger.ts
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

Closes https://github.com/spinnaker/spinnaker/issues/4410
- As a user configuring pipeline B to run as a stage of pipeline A, I expect artifacts from pipeline A to be included when retrying an execution of pipeline B. In other words, I expect the retry logic to be the same as if I had configured pipeline B to be triggered by pipeline A.
- This change shims a pipeline trigger for a pipeline when it has run as a stage of a parent pipeline, so that the pipeline trigger manual execution component will render.
- While testing this, I realized that we were rendering the `ArtifactList` component even when the list of artifacts were empty, so I also fixed that.
<details><summary>[Existing Functionality] Pipeline A triggers Pipeline B</summary>
<p>
</p>
</details>
<details><summary>[Before] …

feat(core): rerun child pipelines with artifacts

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

When pressing the revert button for a templated pipeline, the original pipeline got merged with the rendered pipeline, resulting in a strange frankenstein pipeline that you couldn't save.

fix(core/pipeline): Fix revert button regression for templated pipelines

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

When updatePipelineConfig is called on a templated pipeline, it breaks the UI rendering of the pipeline (since it is based on `$scope.plan`, not `$scope.pipeline`). This happens when you open the pipeline config screen for some pipelines (for instance if you have expected artifacts defined in the old format without artifact account).
Removing the line in this PR solves the problem, while it seems like the functionality still works (because angular watches `$scope.pipeline` and calls `updatePipeline()` when it changes).

fix(core/pipeline): Don't break templated pipelines when updating config

---

app/scripts/modules/core/src/forms/mapEditor/MapEditorInput.tsx
app/scripts/modules/core/src/pipeline/config/triggers/pubsub/PubsubTrigger.tsx
app/scripts/modules/core/src/pipeline/config/triggers/webhook/WebhookTrigger.tsx

```js
<FormField
label="Map Editor"
value={mapEditorData}
onChange={(e: any) => setMapEditorData(e.target.value)}
input={props => <MapEditorInput {...props} allowEmptyValues={false} />}
/
```

fix(core/forms): MapEditorInput: Add validation for empty keys and empty values.

---

app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
app/scripts/modules/core/src/pipeline/manualExecution/layout/ManualExecutionFieldLayout.tsx

so... in #7413 I made a pretty glaring exception in migrating over fields to `ManualExecutionFieldLayout`. Spoiler alert: it's parameters.
Parameters ended up in a double-nested bootstrap grid, which is obviously great. This PR moves them over to the context-provided layout just like the other fields covered in #7413:

fix(core/pipeline): migrate more manual execution field layouts

---

app/scripts/modules/core/src/task/tasks.html

long, long ago (it was 2015), [a change was made to hide the duration of canceled tasks](https://github.com/spinnaker/deck/pull/844/files#diff-09a97886cae0dcb44dcb7c22fe7641cfR78-R84). I don't know why, and nobody else seems to know either. It seems useful to have a duration even on things you've canceled, so let's try turning it on 🤷‍♂
before:
after:

fix(tasks): (re)-enable durations on canceled tasks

---

app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx

The Execution Details link in the pipeline view doesn't work if the first stage in the pipeline is a group. I think this was by design, but it has been a major cause of confusion for our users, so I think it makes sense to just expand the first stage with the first substage selected.

fix(core/pipeline): Fix execution details chevron for grouped stages

---

app/scripts/modules/kubernetes/src/loadBalancer/configure/wizard/basicSettings.html
app/scripts/modules/kubernetes/src/validation/applicationName.validator.js

This PR removes the 24 character limitation on application name length for Kubernetes providers that got into deck with PR #2102 
According to various ressource (some of them mentioned in the code) that limitation is not in place since May 2016 or k8s > 1.4.0.
This change has been discussed in Slack prior to it being opened.

fix(kubernetes): remove former 24-char limit on services names

---

app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts

Some pipelines that where generated in some older version of deck (or maybe someone what carving them manually), if the `requisiteStageRefIds` in a stage object does not exist it will throw a NPE in the console and fail to render the pipeline.
Evaluating if the variable is defined before calling a function on it fixes the issue.

fix(pipeline): Fix NPE in stage requisiteStageRefIds

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

Previously, a fix for saving Templated pipelines was applied which removed the assigment of the updated pipeline to 'renderablePipeline'.  This fix re-applies the assignment of the 'renderablepipeline' variable but only if the pipeline is non-templated.

fix(core/pipeline): Fixes UX of saving non-templated pipelines

---

app/scripts/modules/core/src/notification/modal/EditNotificationModal.tsx
app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildValidators.ts
app/scripts/modules/core/src/pipeline/config/stages/script/ScriptStageConfig.tsx
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx
app/scripts/modules/core/src/presentation/forms/README.md
app/scripts/modules/core/src/presentation/forms/validation/validation.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/validation.ts
app/scripts/modules/core/src/presentation/forms/validation/validators.ts

This is an iteration on the form validation API.  The primary changes are:
- Migrate from `buildValidators(values)` to `new FormValidator(values)`
- Make fields optional by default
- Migrate from `.required([validator1, validator2], 'field is required')`
  to `.required('field is required').withValidators(validator1, validator2)`
- Add `spelAware()` to ValidatableField which allows validation to pass
  when the value contains a SpEL expression, even if other validators
  would fail the validation.
- Add a magic string that can be used to short circuit validation of a field
  - Used to implement optional() and spelAware()

Validation refactor

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

I accidentally broke this in #7427. Adding the removed line back, but only for non-templated pipelines.

fix(core/pipeline): Fix revert button for non-templated pipelines

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

Reverting these lines to pre #7318 fixes the issue

fix(core/pipeline): "Depends On" doesn't always update when reverting

---

app/scripts/modules/core/src/utils/consoleDebug.ts

This just exposes the `API` class on the global object `window.spinnaker`.    This can be useful to interactively explore the API from the javascript console.
```
window.spinnaker.api.all('/credentials').get().then(accounts => console.log(accounts));
```

feat(core/utils): Add 'api' to window.spinnaker object for interactive debugging

---

app/scripts/modules/core/src/pipeline/config/actions/history/showHistory.less

Safari renders the viewport of the revision history with a height of 34px, which leaves a lot of whitespace unused, and also makes it hard to review the revision history as only two lines can be displayed at once.
The `padding-left` override also makes the revision history stop cropping the pluses and minuses (in all browsers).

fix(core/pipeline): Revision history is vertically challenged in Safari

---

app/scripts/modules/core/src/utils/index.ts
app/scripts/modules/core/src/utils/json/traverseObject.spec.ts
app/scripts/modules/core/src/utils/json/traverseObject.ts

A utility function I intend to use when adding some form validation enhancements.
```js
it('walks nested objects inside array properties of an object', () => {
const object = { foo: 1, bar: [{ name: 'abc' }, { name: 'def' }, { name: 'ghi' }] };
traverseObject(object, defaultCallback);
expect(keysWalked).toEqual(['foo', 'bar[0].name', 'bar[1].name', 'bar[2].name']);
expect(valsWalked).toEqual([1, 'abc', 'def', 'ghi']);
});
```

feat(core/utils): Add `traverseObject` which deeply walks object properties

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/PatchManifestStageConfig.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/PatchManifestStageForm.tsx

Manual cherry pick of #7455 to 1.15.  The only conflict was that #7344 removed `inline={true}` on a line adjacent to a changed line; manually resolved this.
* fix(kubernetes): Properly dirty patch stage on resource update
We're not currently not marking the stage dirty upon chaning the
resource to be selected, which makes it impossible to save (without
making some other change or waiting for a digest cycle to happen
for another reason).
* fix(kubernetes): Fix manifest source defaulting in patch manifest
When creating a new patch manifest stage, we default the 'Manifest
Source' selector to 'Text' but the 'Manifest' text box is not visible;
the user needs to choose 'Artifact' then 'Text' again to make the
text box visible.
* fix(kubernetes): Fix merge strategy field
We've been incorrectly …

fix(kubernetes): Fix merge strategy field (#7455)

---

app/scripts/modules/core/src/cluster/filter/ClusterFilterModel.ts
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterModel.ts
app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterModel.ts

This fixes a problem where deep links to infrastructure items (such as an instance chiclet) where filters are applied will lose the filters when the deep link is activated.  This was due to a but introduced when refactoring the filter save/restore code a few months back.  We started using router hooks to manage saving/restoring the filters.  However, the case where a user was navigating deeply was not accounted for in the router trigger criteria.  It only took effect when the top level view was activated.
This change switches to triggering the router hook on a wildcard glob on the beginning and end of the state names.
This causes the AngularJS compatibility code to be run whether you're activating the clusters tab, or deep linking to an instance _within_ the clusters tab.

fix(core/infrastructure): Fix deep links with filters

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx

rendering was messed up when kustomize was disables via settings.
previously it would render both forms when no rendering option was
selected.

fix(bakeManifest): fix bake manifest UI rendering

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/BitbucketArtifactEditor.tsx

Fixes https://github.com/spinnaker/spinnaker/issues/4958
Updated regex to include the bitbucket server regex pattern, allows updates to the text input box (value) even when the regex does not match to allow natural user input versus forcing copying and pasting the full URL.

fix(artifacts/bitbucket) Allow updates to the artifact text input even when the regex pattern does not match

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/core/src/deploymentStrategy/deploymentStrategy.module.ts
app/scripts/modules/core/src/deploymentStrategy/strategies/monitored/AdditionalFields.tsx
app/scripts/modules/core/src/deploymentStrategy/strategies/monitored/monitored.strategy.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/monitoreddeploy/DeploymentMonitorExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/config/stages/monitoreddeploy/DeploymentMonitorReader.ts
app/scripts/modules/core/src/pipeline/config/stages/monitoreddeploy/evaluateHealthStage.ts
app/scripts/modules/core/src/pipeline/config/stages/monitoreddeploy/notifyDeployStartingStage.ts
app/scripts/modules/core/src/pipeline/pipeline.module.ts

* Add stage execution details for `notifyDeploymentStarted` and `evaluateDeploymentHealth` stages
* Add monitored deploy to selectable strategies
<details>
<summary>Execution details view</summary>
<p>
</p>
</details>
<details>
<summary>Strategy configuration view</summary>
</details>

feat(monitored deploy): add basic monitored deploy UI

---

app/scripts/modules/core/src/presentation/forms/fields/FormikExpressionRegexField.tsx
app/scripts/modules/core/src/presentation/forms/interface.ts
app/scripts/modules/core/src/presentation/forms/validation/categorizedErrors.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/categorizedErrors.ts
app/scripts/modules/core/src/presentation/forms/validation/validation.ts
app/scripts/modules/core/src/validation/ValidationMessage.tsx

This PR introduces initial support for two features:
1) The ability to embed validation categories _inside_ a validation message and extract them later.
Validation categories are pre-defined by the validation API.
A validator can return a validation message prefixed with the category.
The `categorizeErrorMessage` function categorizes an error message into a pre-defined category.
Example:
the message `'Error: This is an error'` is processed into:
category: `'error'`
message: `'This is an error'`
--- 
2) The ability to categorize validation messages from a raw Errors object (Formik style) into category buckets.
Given an errors object, the `categorizeErrors` function returns an object with category keys.
Each error message from the raw errors object is first categorized and then stored …

feat(core/presentation): Begin adding support for error categories in validation API

---

app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js

We typically sort the list of available regions in stage configs (e.g. `AccountRegionClusterSelector`), but we don't in the AWS bake stage. This is not only somewhat confusing (we've observed people accidentally select the wrong regions because they were relying on order rather than reading the region name), it also has the side effect of making pipeline JSON 'different' from it's saved state if the API decides to return a different ordering for some reason.
That very thing _seems_ to have happened with some of our internal users, who noticed a prompt to save because the order our `checklist` component used stopped matching the saved JSON ordering, resulting in a diff (even though the same regions were selected).
This PR does two small things:
- Enforce a client side sort
- Change the way …

fix(amazon/pipeline): sort list of available bake regions

---

app/scripts/modules/core/src/presentation/flex-layout.less
app/scripts/modules/core/src/presentation/forms/layouts/StandardFieldLayout.tsx

Adding margin in prep for switching to the newer form field validation styles

feat(core/presentation): Put margin between StandardFieldLayout's input and validation

---

package.json
yarn.lock

This styleguide bump supersedes #7477 
The color scheme changes to `danger` and `success`  colors in #7477 was particularly jarring, so we reverted that change.  The new validation status colors were added under a tighter scoped namespace, e.g., `--color-validation-success`

chore(package): update  @spinnaker/styleguide@1.0.14

---

app/scripts/modules/titus/src/pipeline/stages/bake/titusBakeStage.js

Most Titus users at Netflix use the option to pull git repository information from the pipeline trigger, which uses expressions to build up a git URL which is passed to our internal bakery.
Turns out that when *not* using that option and specifying a branch/hash/etc. yourself in the stage, we weren't putting the appropriate query string `?` before the hash component of the URL.

fix(titus/pipeline): use proper git ssh URL for docker bakes

---

app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

While investigating a bug with manual re-runs of pipelines triggered on Docker images (that turned out to be an [Echo issue](https://github.com/spinnaker/echo/pull/669)), I also found a few small regressions in Deck:
- Point "Artifact Constraints" field at correct help text
- When attempting to match a pipeline trigger to an execution trigger, use deep equality to compare properties (currently, there will never be a match because the pipeline trigger's `expectedArtifactIds`, a list, will never triple-equal the execution trigger's `expectedArtifactIds`). Also, only compare the pipeline trigger to the modified execution trigger, which if a manual trigger, has had its type changed from `manual` (which will never match the type of a pipeline trigger).
- When hydrating the matched pipeline …

fix(triggers): fix a few minor issues with manual execution triggers

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/PolicyTypeSelectionModal.tsx
app/scripts/modules/core/src/presentation/forms/forms.less
app/scripts/modules/core/src/presentation/forms/layouts/ResponsiveFieldLayout.tsx
app/scripts/modules/core/src/presentation/forms/validation/categorizedErrors.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/validation.ts
app/scripts/modules/core/src/validation/ValidationMessage.less
app/scripts/modules/core/src/validation/ValidationMessage.tsx
app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx

mockups of new styles from here: 
https://gallery.io/projects/MCHbtQVoQ2HCZcM1NWkzJjWA/files/MCGOQ33-FuyCnqx3ZnbHf9sO
Also migrated the CSS from forms.css to a component-scoped css file.

feat(core/presentation): Migrate ValidationMessage to new CSS styles

---

app/scripts/modules/core/src/presentation/forms/validation/categories.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/categories.ts
app/scripts/modules/core/src/presentation/forms/validation/index.ts
app/scripts/modules/core/src/presentation/forms/validation/validation.ts

example: 
```js
const v = new FormValidator(values);
v.field('foo').withValidators(value => {
return value === 'foo' && errorMessage('NO, NOT FOO!!!')
});
```
also moved all category stuff into categories.ts

feat(core/presentation): Add helper functions for generating categorized validation messages

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/namespaces.ts

We whitelist the CloudWatch namespaces you can pick from when setting up a custom scaling policy metric, and recently got asked to include an additional one. We pass these on untouched through orca/clouddriver and on to AWS, so no additional work needed on the backend.

feat(amazon/serverGroup): add AmazonMQ CloudWatch namespace

---

app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/domain/IPipelineTemplateV2.ts
app/scripts/modules/core/src/domain/ITrigger.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigView.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigView.js
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.controller.spec.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/docker/src/pipeline/trigger/DockerTrigger.tsx
app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerConfig.tsx
app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx
app/scripts/modules/docker/src/pipeline/trigger/IDockerTrigger.ts

This adds some testing for configuring v2 templated pipelines. 
It also make sure that the pipeline config shown when editing as JSON does not display inherited items and only shows what is directly saved to the config. To see the pipeline plan, including its inherited template items, the user can go into the "Rendered Pipeline" view.
https://github.com/spinnaker/spinnaker/issues/4887

fix(core): Separate how config and plans are updated, add tests

---

app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx

Previously, triggers would all send partial updates (i.e., one field has changed)and the handler code would mutate the object, updating the fields.
Now, however, all triggers are written in React (and mostly in formik).  We no longer need to support object mutation for angularjs.  This changes the update handler to replace the entire object reference with the updated trigger.

fix(core/pipeline): When a trigger is updated, replace the entire object

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/titus/package.json

3192f2cf246de552a79e32387d53ecba24e32b13 fix(core/pipeline): When a trigger is updated, replace the entire object (#7496)
64e47b4a294c1ff39b4ff724715b0d8a09f55451 feat(core): filter out providers that don't support creating security groups (#7370)
2ef878860df5d9c2135ff68400fa57fab3e17cc0 fix(core): Separate how config and plans are updated, add tests (#7491)
2ef878860df5d9c2135ff68400fa57fab3e17cc0 fix(core): Separate how config and plans are updated, add tests (#7491)
3c08b388e6a00d4c9d14ad9babeb857e99d3d0e2 feat(core/presentation): Migrate ValidationMessage to new CSS styles (#7481)
980581a91cc8bc0982822f53b77f6f719475f05d feat(amazon/serverGroup): add AmazonMQ CloudWatch namespace (#7489)
3c08b388e6a00d4c9d14ad9babeb857e99d3d0e2 feat(core/presentation): Migrate ValidationMessage to new …

Bump package core to 0.0.417 and docker to 0.0.46 and amazon to 0.0.214 and titus to 0.0.113

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigView.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
app/scripts/modules/core/src/pipeline/config/triggers/Triggers.tsx
app/scripts/modules/core/src/pipeline/config/triggers/triggers.module.ts

This is a workaround for angular/react interactions.
Previously, we had turned on `enableReinitialize` for trigger formik forms.
This allowed angular code to revert the pipeline and the changes would flow through through to formik via 'initialValues'.
However, turning on that prop had the unwanted side effect of reinitializing the form whenever _anything_ changed.
This caused problems with the validation logic.
This workaround causes the triggers component to be remounted whenever the pipeline is rolled back.
I think a longer term solution is to refactor the pipeline configuration screen to purely React, then adding adapter code for stages that are written in angularjs.  This would basically flip the angular/react adapter direction.

fix(core/pipeline): KLUDGE: use react 'key' to reinitialize formik when pipeline reverted

---

app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx

A trigger type can register a 'validateFn'.
This validateFn is run against its trigger data by the PipelineConfigValidator.
If any errors are found, the little triangle shows up next to the save pipeline button.
However, those same trigger validation errors didn't show up on the form fields themselves.
This PR wires the validateFn into the Trigger's Formik validate prop.
Validation is run twice (once by formik, once by PipelineConfigValidator).
Not ideal, but acceptable.
Before:
After:

fix(core/pipeline): Pass Trigger validateFn to the trigger's Formik

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js
app/scripts/modules/core/src/pipeline/config/triggers/TriggersWrapper.tsx
app/scripts/modules/core/src/pipeline/config/triggers/triggers.module.ts
app/scripts/modules/core/src/pipeline/index.ts
app/scripts/modules/core/src/pipeline/manualExecution/ManualPipelineExecutionModal.tsx

As reported by @battlecow in [this PR](https://github.com/spinnaker/deck/pull/7483), controlled inputs such as `SpelText` in the pipeline config view have cursors that will jump to the end of the input whenever the input is edited.
I _think_ this is because we were updating the angular model with `$scope.$applyAsync`, and controlled React inputs are expecting their `onChange` handlers to be synchronous. I fixed this by implementing a wrapper component, similar to the one @alanmquach built for [stage configs](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/config/stages/StageConfigWrapper.tsx), that updates the angular model synchronously and then calls `forceUpdate` on the React component.
<details><summary>Before</summary>
<p>
</p>
</details> …

fix(core): fix jumping cursor in trigger inputs

---

package.json
yarn.lock

Updating this Spring Expressions lib. 
This is a step towards client side SpEL syntax validation.

chore(package): bump spel2js to 0.2.6

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html

This fixes spinnaker/spinnaker#5009
Check whether `failFastStatusCodes` field should be shown based on the preconfigured properties list.  This is needed because currently there is no way of pre-configuring this field.
Please refer to the above mentioned issue for more details.
This PR contains the front end changes. Backend changes are made in `orca` as part of https://github.com/spinnaker/orca/pull/3223

fix(webhook): Hide fail fast status code if they are pre-configured

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx

adds an option for rawOverrides. this will trigger the use of `--set` in
the bake manifest stage.

fix(bakeManifest/helm): rawOverrides option

---

app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html

The "type" field is missing in the loadbalancer details view for CLBs. 
Before: 
After:

fix(ui): Type field missing for CLB detail view

---

app/scripts/modules/core/src/presentation/domPurifyOpenLinksInNewWindow.ts
app/scripts/modules/core/src/presentation/presentation.module.js

https://github.com/cure53/DOMPurify/tree/master/demos#hook-to-open-all-links-in-a-new-window-link
This makes it so `DOMPurify.purify(html)` will add `target="_blank"` to all links.  
The assumption here is that whenever we use DOMPurify, we're likely rendering user-provided content, and that any links provided should not blow away the spinnaker session.

fix(core/presentation): Make all DOMPurify'd links open in a new window

---

app/scripts/modules/core/src/presentation/Markdown.less
app/scripts/modules/core/src/presentation/Markdown.tsx
app/scripts/modules/core/src/presentation/forms/validation/ValidationMessage.tsx
app/scripts/modules/core/src/presentation/forms/validation/categories.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/categories.ts

This renders markdown in the `ValidationMessage` component
```
const markdown = errorMessage(`A thing happened\n\n[Click here](http://internal.service.com/error?id=12345) for deets`);
return <ValidationMessage message={markdown} type={'error'} />
```

feat(core/presentation): allow markdown in ValidationMessage

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

c1a28fef4097b5b5bd3f1c7c45f4140d82f65f1e fix(core/presentation): Do not use a regexp with /test/s because it's not supported in firefox (#7518)
74e829d0d3d0de32fd2d9e624a5ee88dbbe96e28 feat(provider/aws): Add roleARN to the deploy cloudformation stage (#7492)

Bump package core to 0.0.421 and amazon to 0.0.216  

---

app/scripts/modules/core/src/presentation/forms/layouts/ResponsiveFieldLayout.tsx
app/scripts/modules/core/src/presentation/forms/layouts/StandardFieldLayout.tsx

The fix was adding a default value when destructuring the validation prop
```
const { label, help, input, actions, validation = {} } = props;
const { hidden, messageNode, category } = validation;
```
Also converted to functional components

fix(core/presentation): Fix null reference in FieldLayout components

---

app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/titus/package.json

64d88ccadf0d25f9271882ef1dbf4858a20149db fix(core/presentation): Fix null reference in FieldLayout components
c7feedd666342a0cc00b7ff913f3cc405ad80814 fix(docker,titus): re-align digest field on image + tag selector (#7526)
c7feedd666342a0cc00b7ff913f3cc405ad80814 fix(docker,titus): re-align digest field on image + tag selector (#7526)

Bump package core to 0.0.423 and docker to 0.0.47 and titus to 0.0.114

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

c8c06e4f3c4d4f8372e0ffd9fb6226d0f42fee03 fix(artifact/bitbucket): Bitbucket Use Default Artifact (#7523)
ed7c44589cfbf482047a0f47d30df97165053aa4 feat(ui): Show health check url beside target group (#7520)
ed7c44589cfbf482047a0f47d30df97165053aa4 feat(ui): Show health check url beside target group (#7520)
ed7c44589cfbf482047a0f47d30df97165053aa4 feat(ui): Show health check url beside target group (#7520)

Bump package core to 0.0.424 and amazon to 0.0.217 and titus to 0.0.115

---

app/scripts/modules/core/src/deploymentStrategy/strategies/monitored/AdditionalFields.tsx
app/scripts/modules/core/src/deploymentStrategy/strategies/monitored/monitored.strategy.ts
app/scripts/modules/core/src/help/help.contents.ts

Note: `Manual` type is not yet implemented in orca, hence it's not used in deck, other then the enum definition

fix(monitored deploy): fix the rollback config to match what orca expects

---

app/scripts/modules/core/src/manifest/ManifestWriter.ts
app/scripts/modules/kubernetes/src/v2/kubernetes.v2.module.ts
app/scripts/modules/kubernetes/src/v2/manifest/rollout/RollingRestart.tsx
app/scripts/modules/kubernetes/src/v2/serverGroupManager/details/details.html

Closes spinnaker/spinnaker#4757
As the many comments/emojis on this [Kubernetes feature request](https://github.com/kubernetes/kubernetes/issues/13488) indicate, there are several valid user stories around issuing a rolling restart of a Deployment. The `kubectl rollout restart` command was released with kubectl version 1.15, and we currently use kubectl version 1.16 in Clouddriver. Like the other kubectl rollout commands, it is valid for Deployments, StatefulSets, and DaemonSets. We currently only expose the ad-hoc rollout commands for Deployments in Deck, but could at a later date expose them for StatefulSets and DaemonSets if there is evidence from users that it would be useful.
Related PRs:
Clouddriver: spinnaker/clouddriver#4100
Orca: https://github.com/spinnaker/orca/pull/3233

feat(kubernetes): support rolling restart operation for deployments

---

app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx

There is no UI impact nor functional change.  We want to custom the 'Resize' to point to an internal feature in our fork.

refactor(aws): move Resize item in the AmazonServerGroupAction dropdown into separate component

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormField.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/interface.ts
app/scripts/modules/core/src/presentation/forms/inputs/utils.ts
app/scripts/modules/core/src/presentation/forms/layouts/ResponsiveFieldLayout.tsx
app/scripts/modules/core/src/presentation/forms/layouts/StandardFieldLayout.tsx

In the system of `FormField`, `FormikFormField`, validation, and `Input` components:
`FormField` and `FormikFormField` provide a `validation` prop to Input components (such as `TextInput`) with information about the current "touched" status, validation message, category, etc.  This enables the input to do things like It also provides an API to register _internal validators_ specific to the input type.  For example, a `SpelInput` may add spel validator.
This PR augments this interface  with a `revalidate()` prop which allows the input itself to trigger revalidation based on some external event (such as async data being loaded for autocompletion).  The parent component (`FormField`/`FormikFormField`) is then responsible for retriggering its validation logic.
example:
```js
function …
```

feat(core/presentation): add revalidate api to IFormInputValidation prop

---

app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/config/stages/concourse/ConcourseStageConfig.tsx
app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsExecutionDetails.html
app/scripts/modules/core/src/pipeline/config/stages/jenkins/jenkinsStage.html
app/scripts/modules/core/src/pipeline/config/stages/travis/travisExecutionDetails.html
app/scripts/modules/core/src/pipeline/config/stages/travis/travisStage.html
app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerExecutionDetails.html
app/scripts/modules/core/src/pipeline/config/stages/wercker/werckerStage.html
app/scripts/modules/core/src/pipeline/config/triggers/baseBuild/BaseBuildTrigger.tsx
app/scripts/modules/core/src/pipeline/config/triggers/concourse/ConcourseTrigger.tsx
app/scripts/modules/core/src/pipeline/config/triggers/wercker/WerckerTrigger.tsx

Currently we reference the Jenkins controller as 'master' in the config for both a Jenkins stage and trigger. This terminology has been deprecated by Jenkins and we need to reference the updated terminology of 'controller'.

feat(core/jenkins): Refer to Jenkins controller instead of master

---

app/scripts/modules/amazon/src/loadBalancer/details/LoadBalancerActions.tsx

When using load balancers from a different application and that other application does not exist, the previous behavior of "just using the current application" leads to unexpected behavior.
So we should prevent edits instead, if the application is not configured.

fix(awslb): Preventing edits against orphaned load balancers

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

f57c70b40468e7b7f574fc2a71aab07ec328a12c feat(core): alphabetize applications in project config dropdown (#7549)
78cbe1561e0d5961d15b5dae4c437686de355089 feat(core/jenkins): Refer to Jenkins controller instead of master (#7531)
8c0d087a0ae7d7e4bd2f1ca7e2e3d99c36518feb feat(core/presentation): add revalidate api to IFormInputValidation - Make all fields on IFormInputValidation non-optional
b3840382a2006637fc10e174af3986899910a776 feat(core/presentation): Add useDebouncedValue react hook renamed hooks files to '.hook.ts' and exported all from an index.ts
17be6af0ce874a98ce07ece879c0e4f8522ed78b feat(kubernetes): support rolling restart operation for deployments (#7538)
7e8cb7e0e1ef58d315e0cfe83e3f3e199979f908 fix(monitored deploy): fix the rollback config to match what orca expects (#7532) …

Bump package core to 0.0.425 and amazon to 0.0.218

---

app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx

Turns out that the `<OverlayTrigger>` component needs whatever you give it as children to be a single node. With the change introduced in #7520, the code path that runs when the health status is `UP` works fine, but any non-UP status hits the `<OverlayTrigger>` path and blows up/fails to render because there's two root nodes. This just wraps those two nodes in a fragment.

fix(core/instance): use fragment on non-UP health code path

---

app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx
app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerConfig.tsx

Closes https://github.com/spinnaker/spinnaker/issues/4929
Disallows manual entry of a Docker image when configuring a trigger.

fix(triggers): do not allow manual definition of docker image in trigger

---

app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/projects/configure/Clusters.tsx

Closes https://github.com/spinnaker/spinnaker/issues/4880, https://github.com/spinnaker/spinnaker/issues/3490
When configuring a Spinnaker project with Kubernetes V2 accounts, only filtering by `*` for stack and detail will return any clusters. This is because unlike with the VM-based providers, an application cluster itself is not associated with a single stack/detail, and each of its workloads can be associated with different stacks/details depending on the moniker annotations added to each manifest. This violates some assumptions in the Clouddriver logic shared by all providers and would be non-trivial to fix. We brought this issues to the SIG and there was not a ton of interest in further investment in the Projects view at this time, so this fix is a bandaid so at least the …

fix(kubernetes): disable project cluster filtration by stack/detail

---

app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/azure/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/google/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js

This allows deck to be configured to compute `roscoMode` on a per stage/execution basis via an optional `roscoSelector` in settings:
```
roscoMode: false,
roscoSelector: (stage) => stage && stage.roscoMode,
snapshots: false,
```

feat(rosco): Allow roscoMode per stage/execution

---

app/scripts/modules/core/src/pipeline/config/actions/history/ShowPipelineHistoryModal.tsx
app/scripts/modules/core/src/pipeline/config/actions/history/showHistory.less

When the pipeline revision history dropdown got moved to react, we started using `StandardFieldLayout` which has a pesky min width on its label. That caused some "fun" usability challenges with the width of the dropdown itself, which this fixes. I've also taken the liberty of improving some other layout nits, as the diff summary was both vertical misaligned and had a bunch of excess padding/margin that made it look a little funky.
**Before:**
**After:**

fix(core/pipeline): make revision dropdown usable, layout tweaks

---

app/scripts/modules/amazon/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/azure/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/docker/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/google/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/oracle/src/pipeline/stages/bake/bakeExecutionDetails.controller.js
app/scripts/modules/titus/src/pipeline/stages/bake/bakeExecutionDetails.controller.js

And of course will fail back to just using bakeryDetailUrl if `roscoDetailUrl` is not defined.

feat(rosco): Allow optional roscoDetailUrl for roscoMode bakes

---

app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js

Minor fix, `roscoMode` only got evaluated once, but if `roscoSelector` is used, we should really evaluate every time the stage is updated so that changes that cause the result to flip between `true` and `false` appropriately flip `roscoMode` and the bake stage config is updated appropriately (rosco fields toggled).

fix(rosco): Re-evaluate roscoSelector on stage updates

---

app/scripts/modules/amazon/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/titus/package.json

dae00c87adc5e69ac232a2145d35e73072cf5766 feat(rosco): Allow optional roscoDetailUrl for roscoMode bakes (#7575)
d620e057e1c0d85984caa9a8ff0639d17ea9309c fix(rosco): Re-evaluate roscoSelector on stage updates (#7577)
dae00c87adc5e69ac232a2145d35e73072cf5766 feat(rosco): Allow optional roscoDetailUrl for roscoMode bakes (#7575)
dae00c87adc5e69ac232a2145d35e73072cf5766 feat(rosco): Allow optional roscoDetailUrl for roscoMode bakes (#7575)

Bump package docker to 0.0.49 and amazon to 0.0.221 and titus to 0.0.117

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

34a3b00beea0287a68a05014862351c0f5904afa feat(managed): Update resource indicators to use new data source
7b33d2b490987a070febbd3478e902dd37c6b7b7 feat(managed): Join managed data to infra data, add moniker to Security Groups
d4c89ceffd2f14eca7660a930d1d675a737da150 feat(managed): Use new data source for 'Managed Resources' config section
efcceb34a541ad71d887f0957fe43741a4ed1de4 feat(managed): add 'managedResources' data source
4ed015a07c028eb58807601a0b0fb9783b02b0d9 feat(dataSources): widen + parameterize types, add default values
8c29cbae0278695316ba493a9f0cb7ae52b51d10 Reactify titus launch configuration (#7581)
5d89a04465f911d49bf171ef47b9d88aa2b8c4a9 feat(google): add gce scale-down controls (#7570)
f88254455238b566936fcca02e0a9e7f0a647958 feat(git/repo): add git/repo artifact …

Bump package core to 0.0.428 and amazon to 0.0.222 and titus to 0.0.118

---

app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useDebouncedValue.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useDebouncedValue.hook.ts
app/scripts/modules/core/src/presentation/hooks/useIsMountedRef.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useIsMountedRef.hook.ts
app/scripts/modules/core/src/presentation/hooks/useLatestPromise.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useLatestPromise.hook.ts

- Reduced unnecessary renders in `useLatestPromise` and `useDebouncedValue`
- Extracted new `useIsMountedRef` hook
- Added unit tests

Hooks improvements

---

app/scripts/modules/core/src/application/service/applicationDataSource.ts

Since this is a new required field and might unexpectedly mess up someone's custom data source in a non-obvious way, let's log an error with some context to make the resolution more obvious.
I originally wanted to just throw a full-on `Error`, but those always get swallowed and end up making the application fail to load without showing up in the console.

feat(dataSources): log runtime error when defaultData isn't provided

---

app/scripts/modules/core/src/cluster/ClusterPod.tsx
app/scripts/modules/core/src/cluster/DefaultClusterPodTitle.tsx
app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
app/scripts/modules/core/src/cluster/filter/mockApplicationData.js
app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/domain/ILoadBalancer.ts
app/scripts/modules/core/src/domain/ISecurityGroup.ts
app/scripts/modules/core/src/loadBalancer/LoadBalancer.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancerPod.tsx
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterService.spec.ts
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterService.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.less
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
app/scripts/modules/core/src/managed/index.ts
app/scripts/modules/core/src/managed/managedResourceStatusIndicator.component.ts
app/scripts/modules/core/src/presentation/HoverablePopover.tsx
app/scripts/modules/core/src/securityGroup/AllSecurityGroupsCtrl.js
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterService.spec.js
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterService.ts
app/scripts/modules/core/src/securityGroup/securityGroup.directive.js
app/scripts/modules/core/src/securityGroup/securityGroup.html
app/scripts/modules/core/src/securityGroup/securityGroupPod.html

We recently [added the ability to calculate a summarized "status"](https://github.com/spinnaker/keel/pull/433) for every declaratively managed resource. This status can indicate a variety of different states from the keel perspective, and provide valuable transparency into what's going on during normal operations and especially when something is wrong / abnormal. This PR adds iconography and explanatory text to Clusters, Load Balancers, and Firewalls with roughly similar visual style (screenshots below).
The PR itself is split into pretty atomic commits, I recommend going through them in order as a lot of the code is similar for each type of infrastructure and you can pattern match after the first couple of commits.
**Example of what this looks like when _all regions_ for a particular …

feat(managed): add resource status to infrastructure views

---

app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.less
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
app/scripts/modules/core/src/presentation/HoverablePopover.css
app/scripts/modules/core/src/presentation/HoverablePopover.tsx

[As previously discussed](https://github.com/spinnaker/deck/pull/7590#discussion_r341455641) in the PR that added them, expanding the HoverablePopover API to include `style` and `wrapperClassName` felt like bloat and I was hoping to find a way to avoid that expansion before they caught on and became popular 😄 
The approach is to take a small specificity risk in moving from inline -> class styles for the popover target wrapper, and then do overrides in the consuming component. I'm guessing there will be one or two places that eventually pop up with slightly weird styling because of specificity silliness, but didn't see anything alarming with a brief trip around the main views / some forms / etc.

fix(core/presentation): remove style + wrapperClassName from HoverablePopover

---

app/scripts/modules/core/src/application/ApplicationComponent.tsx
app/scripts/modules/core/src/application/application.model.ts
app/scripts/modules/core/src/application/application.state.provider.ts
app/scripts/modules/core/src/application/applicationModel.builder.ts
app/scripts/modules/core/src/application/config/DeleteApplicationSection.tsx
app/scripts/modules/core/src/application/config/applicationConfig.controller.js
app/scripts/modules/core/src/application/config/applicationSnapshotSection.component.js
app/scripts/modules/core/src/application/config/dataSources/applicationDataSourceEditor.component.ts
app/scripts/modules/core/src/application/config/links/applicationLinks.component.js
app/scripts/modules/core/src/application/config/trafficGuard/trafficGuardConfig.component.ts
app/scripts/modules/core/src/application/nav/ApplicationHeader.tsx
app/scripts/modules/core/src/application/nav/ApplicationNavSection.tsx
app/scripts/modules/core/src/application/service/applicationDataSource.ts
app/scripts/modules/core/src/chaosMonkey/chaosMonkeyConfig.component.ts
app/scripts/modules/core/src/insight/insightLayout.component.html
app/scripts/modules/core/src/pipeline/config/pipelineConfig.controller.js
app/scripts/modules/core/src/pipeline/config/pipelineConfig.html
app/scripts/modules/core/src/pipeline/details/SingleExecutionDetails.tsx
app/scripts/modules/core/src/pipeline/executions/Executions.tsx
app/scripts/modules/core/src/task/tasks.controller.js

Historically if _anything_ threw while an application model was being created in the main "we need to load a view" code path, we'd silently catch the error, toss it out, and then show the 'Application not found' message. This makes it very hard to debug when something goes wrong in between fetching the application from Front50 and having a fully hydrated application model with data sources, etc. — that model setup process is really quite a lot of work/steps and there are tons of opportunities for exceptions that are hard to pinpoint. It's also misleading because it claims we couldn't find an app, even though there's really something _wrong_.
This does a few things:
- Log out the caught exception (including the original stack trace before it got caught in a promise handler)
-  Add an …

fix(core/application): add error state to application models, log exceptions

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/Base64ArtifactEditor.tsx

Closes https://github.com/spinnaker/spinnaker/issues/5102
The [artifacts rewrite commit](https://github.com/spinnaker/deck/pull/6634) added support for a React base64 artifact editor. In the [Angular implementation](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/defaultBase64.artifact.ts#L83), the textarea value is bound to the value of the decoded base64, so does not need to be updated manually. In the React implementation, we are storing the value of the decoded base64 on state and need to manually update it in the textarea change handler.

fix(artifacts): enable inline editing of base64 artifacts

---

app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx

Depends on https://github.com/spinnaker/spinnaker.github.io/pull/1585 and https://github.com/spinnaker/deck/pull/7610.
Support for the newly-added `RESUMED` status — feedback on wording / etc is welcome. Until #7610 gets merged there will be an extra commit at the beginning, this PR is only one commit.

feat(core/managed): add RESUMED resource status

---

app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterService.ts
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilterService.ts

tl;dr I mistakenly thought that these filter services generated new grouping data and then pushed that out to consumers, but in reality the new data gets generated and then is used to diff + patch the original objects from the first time the grouping was created. Because I didn't implement this logic in previous PRs, changes to the `isManaged` and `managedResourceSummary` fields were not being picked up until a full reload.
Normally I would say this is a horrible kludge, but I suppose it's just the (gross) way of things while there's still some angular floating around since we need stable object references for those directives/components to behave correctly.

fix(core/managed): properly diff/patch mutable infra groupings

---

app/scripts/modules/core/src/domain/IStage.ts
app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesStageConfig.less
app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesStageConfig.tsx
app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/ExecutionAndStagePicker.tsx
app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/evaluateVariablesStage.ts

Everyone, meet the new Evaluate Variables stage:
Lots of changes here, this is a full rewrite:
- Swap out MapEditor in favor of FormikFormFields.  Note how the `label` prop is a nested `FormikFormField` 🤷‍♂ 
- Added Variable Preview and Validation via `SpelInput`
- Better field validation via Formik
- Added a Preview Execution/Stage picker.  This enables us to evaluate the previews against a previous execution and at the right spot in that execution.
- Prepopulate new stages with a blank row
Future work:
- Rewire autocomplete feature
- There are some backend changes coming from @marchello2000 (SpEL v4) that will cause these variables to get evaluated in order, enabling us to provide clear variable dependency rules.  For example, `host` variable is …

Evaluate variables stage updates

---

app/scripts/modules/core/src/presentation/forms/SpinFormik.tsx

Turns out this wasn't as unnecessary as I thought.
isInitialValid is _always_ used if the form when `formik.dirty === false`
It doesn't matter if you have validated the form once or twice or a million times.

test(core/presentation): Re-add removed isInitialValid logic

---

app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/EvaluateVariablesExecutionDetails.tsx

fix(core/pipeline): Use markdown to render evaluated variables as JSON

---

app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js

Somehow ended up with the string `SETTINGS.feature.roscoMode` duplicated, probably while copy/pasting #7564 to other providers resulting in 
```
SETTINGS.feature.roscoModeSETTINGS.feature.roscoMode
```
Which causes a javascript exception trying to access the second `feature` because `SETTINGS.feature.roscoModeSETTINGS` is likely never defined.

fix(azure,gce): Fix typo breaking bake stage

---

app/scripts/modules/amazon/src/securityGroup/configure/ingressRuleGroupSelector.component.html
app/scripts/modules/amazon/src/securityGroup/configure/ingressRuleGroupSelector.component.ts

Allows the UI (via configuration) to remove options from cross-account ingress selection.
[Ingress across accounts typically requires the VPCs to be peered](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#SecurityGroupRules), so if there are accounts that are known to not be peered, we can filter them out of the list.
Otherwise, users will select them and submit the security group create/update task only to have it inevitably fail.
``` 
aws: {
crossAccountIngressExclusions: {
"foo": ['bar'],
"bar": ['foo'],
},
}
```

feat(aws): Allow filtering cross account ingress

---

app/scripts/modules/assert_package_bumps_standalone.sh

Neat!
In #7646 the new checks _almost_ worked:
```
===================================================
Checking amazon
===================================================
[ YES  ] Version change detected in package.json
[ PASS ] Version change must be the only line changed in package.json
[ FAIL ] package.json (in apps/scripts/modules) must be the only files changed in a pull request with version bumps
===========================================
Failure details (list of all files changed)
===========================================
app/scripts/modules/amazon/package.json
===========================================
```
Except for a few typos that caused the last check to fail incorrectly.

fix(travis): Fixing typos in package bump checks

---

app/scripts/modules/core/src/pipeline/config/stages/evaluateVariables/ExecutionAndStagePicker.tsx

This fixes auto-selection of a execution/stage in the evaluate expressions stage.  
This code looks for a matching stage between the pipeline source stages and the executed stages found in the selected previous execution.  This filters out any non-numeric stage ref ids, i.e. "waitForAuthorizationContext".  
Before:

fix(core/pipeline): ExecutionAndStagePicker Fix auto selection of stage

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx

When editing a Titus deploy stage and setting the capacity to "Copy the capacity form the current server group" in advanced mode, the state does not persist after saving + reloading. This PR fixes this so that the situation below does not happen. 
Example:

fix(amazon): Copy capacity from current server group does not persist

---

app/scripts/modules/amazon/package.json

This has not been published yet.
Instead, trying a new workflow where the package bump(s) are authored first, then the exact commits on master shall be published when they land.
Still working out the kinks for that piece.
Also, no more changeset here because it may not always reflect reality (i.e. of additional commits landed on master)

chore(amazon): Bump version to 0.0.224

---

.gitignore
app/scripts/modules/core/package.json
app/scripts/modules/core/webpack.config.js
package.json
webpack.config.js
yarn.lock

Don't be fooled by the line/file count, this PR was the product of a full 1.5 days of discovery and glorious learning.
At the most recent UI SIG meeting, we aligned around the idea of experimenting with CSS Modules in a manner that would limit the blast radius of changes in the event we decided to change course after experimentation. The current thinking is that we'll:
1. Setup CSS Modules in `@spinnaker/core` (but not across all packages)
2. Use CSS Modules to build upcoming reusable presentation components (modals first, then maybe tables and/or navigation, etc.)
3. Use those presentation components in real-world views and learn about where CSS Modules are good/bad/ugly
4. Re-evaluate in a few months once we've done 1-3 and decide on the next set of experimentation / work
This PR …

feat(core): add support for CSS modules to dev server + lib build

---

app/scripts/modules/amazon/src/aws.validators.ts

[Firefox does not support lookbehind assertions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility) so the RegExp `^[0-9A-Za-z\.\-_]*(?<!\.)$` causes a syntax error and deck will not load at all in Firefox.
I think all this is trying to do is ensure the string does not end in a `.`, so I replaced with with a compatible expression that I _think_ does the same thing.
@sidmuls FYI in case I inadvertently altered the behavior.

fix(amazon): Removing unsupported negative lookbehind

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/help/amazon.help.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/common/configure.less
app/scripts/modules/amazon/src/loadBalancer/configure/common/targetGroupValidators.spec.ts
app/scripts/modules/amazon/src/loadBalancer/configure/common/targetGroupValidators.ts
app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
app/scripts/modules/core/src/presentation/forms/validation/validators.spec.ts
app/scripts/modules/core/src/presentation/forms/validation/validators.ts
app/scripts/modules/core/src/widgets/spelText/SpelNumberInput.tsx
app/scripts/modules/core/src/widgets/spelText/spel.less

Addressing validation issues on the create/edit load balancer user flow: 
1. Form validation for health check values was invoked on the user string, causing the validation to fail. ("Must be a number")
2. Inconsistent with [AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html) rules. The summary is below, but more details can be found in the doc I linked. 
**HealthCheckTimeoutSeconds**
For target groups with TCP/TLS protocols - it must be 6 seconds for HTTP healthchecks and 10 seconds for TCP/HTTPS healthchecks.
For target groups with HTTP/HTTPS protocols, the range of values 2-120 should be acceptable.
**HealthCheckIntervalSeconds**
For TCP healthchecks, the interval must be 10 or 30 seconds.

fix(amazon): Update load balancer validations to match user expectations

---

.github/workflows/publish_titus.yml
app/scripts/modules/github_actions_publish.sh

I believe the bits are in place, but would like to try this out with Titus first before adding all the other modules.
Many bits were taken from `publish.sh`. We basically verify a few things, then publish:
1. Only continue if there even was a version bump
2. Enforce that a version bump was not bundled up with other changes (files) in the same commit
3. Enforce that no other lines in package.json were changed either
The script will only look back as far as the most recent commit to the `package.json` of interest.
This should be good enough for PRs that get merged or squashed, but doesn't work great for PRs that get rebased.
However this should be fine because the checks we do at PR time (`assert_package_bumps_standalone.sh`) overlap with these checks and encompasses all changes in the PR. …

chore(npm): Enabling module publishes via GitHub actions

---

app/scripts/modules/titus/package.json

Looks like there are no unpublished commits in titus.
I would still like to do an artificial bump to ensure npm publishing via GitHub Actions work before rolling it out broadly to all the other providers.

chore(titus): Bump version to 0.0.119

---

app/scripts/modules/amazon/tsconfig.json
app/scripts/modules/appengine/tsconfig.json
app/scripts/modules/azure/tsconfig.json
app/scripts/modules/cloudfoundry/tsconfig.json
app/scripts/modules/core/tsconfig.json
app/scripts/modules/docker/tsconfig.json
app/scripts/modules/ecs/tsconfig.json
app/scripts/modules/google/tsconfig.json
app/scripts/modules/huaweicloud/tsconfig.json
app/scripts/modules/oracle/tsconfig.json
app/scripts/modules/titus/tsconfig.json

On another feature branch I was using `Object.values` and ran into a TS error — turns out while our root `tsconfig.json` was on `es2017` most of them are on `es2016`. This just standardizes all of the configs on `es2017`, which should theoretically be harmless 🤷‍♂

chore(tsconfig): standardize all tsconfig.json files to es2017

---

app/scripts/modules/core/src/presentation/hooks/useContainerClassNames.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useContainerClassNames.hook.ts
app/scripts/modules/core/src/presentation/hooks/useEventListener.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useEventListener.hook.ts
app/scripts/modules/core/src/presentation/hooks/useLatestCallback.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useLatestCallback.hook.ts
app/scripts/modules/core/src/presentation/hooks/usePrevious.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/usePrevious.hook.ts

I'm currently working on building out a `Modal` component that will be part of our slowly growing design system/component library and hopefully replace our use of `Modal` from `react-bootstrap`. In doing that, I ended up wanting three new hooks to accomplish some underlying behavior and are relatively generic/reusable:
- **usePrevious**: This is a hook that [the react docs actually gives an example for](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state), and says they might bring into the core library later. I wanted it for one of the other two hooks in this PR. It's basically a way to get the value from the _last render_ for any value you care about
- **useContainerClassNames**: This one is interesting and specific to our app/presentation needs. I had a need …

feat(core/presentation): add four new hooks + tests

---

app/scripts/modules/amazon/src/instance/details/instance.details.controller.js

Turns out the reference to `app.loadBalancers.data` we added is an NPE when an instance isn't attached to an ASG ("standalone"). Most of this file already dances around not touching any of the data sources when the app model is in standalone mode, so just doing the same thing to fix.

fix(amazon/instance): don't blow up on standalone instances

---

app/scripts/modules/kubernetes/src/v1/serverGroup/configure/configure.kubernetes.module.js
app/scripts/modules/kubernetes/src/v1/serverGroup/configure/wizard/loadBalancers.controller.js

Please check if `kubernetesServerGroupLoadBalancersController` is something that should exist, because it currently does not.

fix(kubernetes/serverGroup): Remove unused controller file for 'kubernetesServerGroupLoadBalancersController'

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js
app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
app/scripts/modules/amazon/webpack.config.js
app/scripts/modules/appengine/webpack.config.js
app/scripts/modules/azure/webpack.config.js
app/scripts/modules/cloudfoundry/webpack.config.js
app/scripts/modules/ecs/webpack.config.js
app/scripts/modules/kubernetes/webpack.config.js
app/scripts/modules/titus/webpack.config.js
package.json
yarn.lock

We were using `exports-loader` so we could `require()` and resolve to a string.  but y tho?  I just put the string inline.
Also I removed `exports-loader` dep because it's no longer used.

refactor(*): Remove exports-loader from n3-chart import

---

app/scripts/modules/core/src/pagerDuty/PageModal.tsx

Because this can complete so fast that users don't even see the task monitor, auto-closing causes users to not know whether their page even went through successfully.

fix(page): Do not auto-close modal on success

---

karma.conf.js
package.json
webpack.config.js
yarn.lock

The loader I had originally added to generate type declarations for CSS Module files seemed like it was working fine, but on Travis has been running into a race where the TS loader tries to lookup defs for the CSS Module files before their declarations are generated on the filesystem. That results in CI builds failing with errors re: not knowing about a module.
This switches to a [different webpack tool](https://github.com/dropbox/typed-css-modules-webpack-plugin) that runs during the plugin phase, before loaders kick in. Tested locally and it seems like it will be less race-y, but need to test on Travis to be sure.

fix(webpack): use a less race-y way of generating CSS Module TS files

---

app/scripts/modules/core/src/ci/igor.service.ts
app/scripts/modules/core/src/domain/IGcbTrigger.ts
app/scripts/modules/core/src/domain/index.ts
app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageConfig.tsx
app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/GoogleCloudBuildStageForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/googleCloudBuild/googleCloudBuildValidators.ts

Added ability to call existing GCB triggers.
This is part of: spinnaker/spinnaker#5076
Added a new `Build Definition Source` to the `GoogleCloudBuild` stage.
When this type is selected, new set of fields are shown:
- Trigger Name: A list of triggers populated when `GoogleCloudBuild` account changes.
- Trigger Type: It has to be one of `commitSHA`, `tagName` or `branchName`. Opted for a dropdown list because google api will fail if we send more than one trigger type.
- Value: The value for the trigger type.
<kbd>![](https://user-images.githubusercontent.com/3589427/68738919-b05ddd00-063b-11ea-859f-6b4e13e85a2b.png)</kbd>

feat(gcb): Ability to invoke existing GCB triggers

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/metricSelector.component.ts
app/scripts/modules/titus/src/serverGroup/serverGroup.transformer.js

When we can't find any CloudWatch metrics, we automatically throw the user into advanced mode. 
However, the presence of a default metricName gives the user a false impression that maybe the can set up that autoscaling policy of the default metricName was the metric they wanted to track against anyways.
This is FALSE. If there are no metrics in CloudWatch, autoscaling will not happen.
I've changed the default metricName to be blank instead of `CPUUtilization` (which is anyways wrong), so that the user does not get this false impression and hope that they see the text that has been there all along to tell them that they need to make metrics available in CloudWatch.
Also added a tweak so that if metrics are available and we are creating a new policy, we try to auto-select a metric like …

fix(titus): Remove default metricName

---

app/scripts/modules/core/src/cluster/filter/ClusterFilterService.ts
app/scripts/modules/core/src/domain/ILoadBalancer.ts
app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/domain/ISecurityGroup.ts
app/scripts/modules/core/src/domain/IServerGroup.ts
app/scripts/modules/core/src/domain/index.ts
app/scripts/modules/core/src/loadBalancer/filter/LoadBalancerFilterService.spec.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
app/scripts/modules/core/src/managed/managed.dataSource.ts
app/scripts/modules/core/src/managed/managedResourceDecorators.ts

It's getting to the end of the year and I'm concerned about my GH stats, so I wanted to get those numbers up and this seemed like an easy way to do it.
Just kidding! When we start adding pause/resume behavior at the resource level, and a resource gets paused, we'll need an indicator of where the pausing comes from: either the resource itself, or the application. If the resource is explicitly paused, we'll provide a way for the user to resume actuation. If it's at the application level, we'll tell the user that the entire application is paused, and they can resume actuation from the config view.
Not sure what the API is going to return to indicate that (cc @emjburns), but when it does, we'll just need to update the one interface, instead of all three domain classes.

refactor(core): move managed entity fields to separate interface

---

package.json
test/functional/tools/StaticServer.ts
yarn.lock

The new CSS loading plugin TypedCssModulesPlugin is causing webpack-dev-server to compile the application twice; the first generates the co-located .css.ts.d files and the second recompiles because of a change in sources.
This is breaking the functional tests, as the server reports healthy, causing the tests to start, but then immediately recompiles. This means that the first tests needs to wait for this second compilation pass, which is leading to intermittent (but frequent) errors.
The fix here is to turn off hot reloading of the app. There does not appear to be a way to do this using webpack-dev-server, so switch to using webpack-dev-middleware to set up the test server.

fix(tests): Use webpack-dev-middleware for functional tests

---

app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.controller.js
app/scripts/modules/titus/src/serverGroup/details/rollback/rollbackServerGroup.html

`PREVIOUS_IMAGE` rollbacks for Titus were incompletely implemented making them dangerous to allow at this point.
Temporarily disabling them from being performed in the UI until they are addressed.

fix(titus): Temporarily disabling previous image rollbacks for Titus

---

app/scripts/modules/core/src/pipeline/executions/Executions.spec.tsx

Looks like this test is intermittently blowing up on master because `app.getDataSource('runningExecutions')` is undefined and blowing up:
```
this.activeRefresher.subscribe(() => {
app.getDataSource('runningExecutions').refresh();
});
```

test(core): Fix intermittent Executions test

---

app/scripts/modules/core/src/application/config/managedResources/ManagedResourceConfig.tsx
app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedWriter.ts
app/scripts/modules/core/src/managed/managed.dataSource.ts

Couple changes:
- Switch to using the new pause APIs added via https://github.com/spinnaker/keel/pull/644 and https://github.com/spinnaker/gate/pull/983
- Little bit of "fun" data-munging where we add a `PAUSED` status to every resource in an app if the app is paused. I did this for now because we want to swap over to the new APIs as soon as possible and I didn't want to go threading state (specifically data source updates) into the stateless components that currently render statuses. I suspect we'll change either the API or the client soon to where that munging doesn't happen

refactor(core/managed): switch from ApplicationVeto to pause API

---

app/scripts/modules/core/src/application/application.model.ts
app/scripts/modules/core/src/application/config/managedResources/ManagedResourceConfig.tsx
app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/managed.dataSource.ts

Nothing big here, just adding some shorthand fields: `isPaused` to managed resource summaries, and `isManagementPaused` to the application. I'm going to use those flags pretty heavily in some subsequent PRs, and it's a lot easier to read:
`resource.isPaused` 
than 
`resource.status === ManagedResourceStatus.PAUSED`
and
`application.isManagementPaused`
than
`application.managedResources.data.applicationPaused`
The latter is also a little safer, as we're not getting type checks on data source references on the application. I kept typing `application.managedResource.data.applicationPaused` and then getting a JS error at runtime since Typescript wasn't able to catch it.

refactor(core): add pause status flags to managed resources

---

app/scripts/app.ts

I think [CI is upset](https://travis-ci.org/spinnaker/deck/jobs/624469904?utm_medium=notification&utm_source=github_status) about this `require`? Happy Friday! :taco:

fix(eslint): dcos import must conform to new eslint rules

---

app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts

I think maybe the `forEach(sortUsages)` was meant to be run after `forEach`ing through the serverGroups and building up the `securityGroups` array and not during?
Doing it during runs it (1 + 2 + 3 + 4 .. + n) times with everything but the last pass being redundant, I think?

fix(core): Fix security group load performance

---

app/scripts/modules/core/src/presentation/forms/inputs/expression/spel2js.templateParser.ts

Spel2js is published as UMD module but has the `__esModule: true` marker.
Because of the marker and because it doesn't have any default exports, if you `import spel2js from 'spel2js'` you get `undefined`

fix(spel2js): Use named exports

---

app/scripts/modules/core/src/securityGroup/SecurityGroup.tsx
app/scripts/modules/core/src/securityGroup/SecurityGroups.tsx

When I refactored this, I only tested loading the firewalls view from the firewalls view. If you come into the firewalls view from some other tab, the server groups and load balancers are hidden until the next refresh cycle. 
This whole thing where we derive state from a model that is set by state transitions, which is sometimes driven by URL changes, but not necessarily...it's not great. But it's also outside the scope of this change. This change...just fixes the view in all use cases I can find.

fix(core): derive firewalls view options from filterModel

---

app/scripts/modules/amazon/src/index.ts
app/scripts/modules/amazon/src/templates.ts

Looks like this was used at netflix for a month or two to customize scaling policies, but it's no longer needed.

chore(amazon): Remove unused AmazonTemplates

---

app/scripts/modules/core/src/pipeline/config/stages/stage.module.js

Changes to reserved fields (namely the stage name) were getting reverted because updating a field in formik would effectively freeze it's values into formik state.
This is because
1. these fields are **mutated** in Angular land
2. formik's `setIn` util works by merging the new slice into the object a la spread operator `const result = { ...obj, ...res }`
This means Angular was free to update the name and the mutated object made it all the way into formik's initial state, but as soon as `setIn` is called (implicitly via`handleChange` or explicitly via `setFieldValue`), a shallow copy was made and cemented those values in formik's state forever.
This fix is still not great as the stage config would be looking at stale values for name/type/etc. but our current patterns don't really allow for …

fix(core): updateStageField should not update reserved fields

---

app/scripts/modules/core/src/application/config/managedResources/ManagedResourceConfig.tsx
app/scripts/modules/core/src/cluster/ClusterPod.tsx
app/scripts/modules/core/src/cluster/DefaultClusterPodTitle.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancer.tsx
app/scripts/modules/core/src/loadBalancer/LoadBalancerPod.tsx
app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx
app/scripts/modules/core/src/managed/ManagedWriter.ts
app/scripts/modules/core/src/managed/managedResourceDecorators.ts
app/scripts/modules/core/src/managed/toggleResourceManagement.ts
app/scripts/modules/core/src/securityGroup/SecurityGroup.tsx
app/scripts/modules/core/src/securityGroup/SecurityGroupPod.tsx

We now have the ability to pause individual resources 😺via the REST API. This adds the ability to pause/unpause resources from the popover badge on the various components:
If the resource is in multiple regions, we'll warn the user of that. If the resource is being actuated, we'll warn the user that the current actuation will continue.
If we find it useful to add more context to the modal when the resource is in other states, we can do that pretty easily.
Most of the file changes here are to add the application to the status indicator (so we can refresh the `managedResources` data source).
I don't love putting all this text into strings, but the confirmation modal is Angular and only deals with strings for the body text. I'm working on making a React option that would take a component, …

feat(managed): allow pausing/resuming managed resources via indicator

---

app/scripts/modules/core/src/config/settings.ts

While the default configs (halyard and non-halyard) were updated to set plugins to an empty array, users who have a custom config will get an NPE unless we add this defaulting here.

fix(plugins): Default plugins to empty list to prevent NPE

---

app/scripts/modules/kubernetes/package.json

- d2838d80c refactor(core): remove unused parameter options from confirmation modal (#7716)
- 6291f858c chore(core): upgrade to latest prettier (#7713)
- 90aa47754 refactor(eslint): Fix all 'prefer-const' eslint rule violations
- d070bd45f refactor(eslint): Fix all 'one-var' eslint rule violations
- 174870161 refactor(eslint): Fix all 'no-var' eslint rule violations
- 9400826bc chore(eslint): remove tslint
- 88b8f4ae0 refactor(angularjs): use ES6 to import angular - migrate from `const angular = require('angular')` to `import * as angular from 'angular'` - Where possible, migrate from `import angular from 'angular'; angular.module('asdf')`   to `import { module } from 'angular'; module('asdf')`
- a076dc128 refactor(angularjs): use ES6 imports for angularjs module deps - migrate from …

chore(kubernetes): Bump version to 0.0.30

---

app/scripts/modules/amazon/src/loadBalancer/configure/AmazonLoadBalancerChoiceModal.tsx

Fixes https://github.com/spinnaker/spinnaker/issues/5271
I'm not sure why the `ecs` module doesn't register/need a `loadBalancer` block, but now protecting this code from providers without a `loadBalancer` balancer attribute since it was originally written with the (incorrect) assumption that ALL providers have that attribute.

fix(ecs): Fixes AmazonLoadBalancerChoiceModal for ecs

---

app/scripts/modules/core/src/task/monitor/TaskMonitorWrapper.tsx

There are a few places (or at least one: entity tag editor) where the task monitor is not configured yet on initial render, so we should guard against that.

fix(core): do not try to render task monitor if monitor is missing

---

app/scripts/modules/docker/package.json

6291f858cb111d9c65affeb82ddd840f05c57b65 chore(core): upgrade to latest prettier (#7713)
90aa47754bc8815eb1bdfcceb4d05c9e1cdf325f refactor(eslint): Fix all 'prefer-const' eslint rule violations
174870161a5a09ab7f15c74cb84d0f3e196cd7cb refactor(eslint): Fix all 'no-var' eslint rule violations
9400826bcb119cf7681e1ce37092b9fdd8b76b1b chore(eslint): remove tslint
88b8f4ae0b9e96ac8d8dbdeff592f3787f0617cb refactor(angularjs): use ES6 to import angular - migrate from `const angular = require('angular')` to `import * as angular from 'angular'` - Where possible, migrate from `import angular from 'angular'; angular.module('asdf')`   to `import { module } from 'angular'; module('asdf')`
a076dc1280b56affcd30cdbea68a84fb7d5ba3f1 refactor(angularjs): use ES6 imports for angularjs module deps - migrate …

chore(docker): bump package to 0.0.50

---

app/scripts/modules/amazon/src/loadBalancer/details/LoadBalancerActions.tsx
app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js
app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
app/scripts/modules/amazon/src/serverGroup/details/resize/AmazonResizeServerGroupModal.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/AdvancedSettingsDetailsSection.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/ScalingProcessesDetailsSection.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx
app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx
app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts
app/scripts/modules/core/src/managed/ManagedMenuItem.tsx
app/scripts/modules/core/src/managed/index.ts
app/scripts/modules/core/src/managed/toggleResourceManagement.tsx
app/scripts/modules/titus/src/serverGroup/details/TitusCapacityDetailsSection.tsx
app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js

This adds a pretty simple component to prevent menu item actions on managed resources. If the user clicks an action, they'll get an interstitial modal asking them to pause management.
I started to make a similar component for the angular world, but...the bootstrap CSS for the dropdown menu includes a bunch of immediate child selectors so it didn't really work, and...we want to convert this stuff to React at some point, anyway, so for now, we're just handling that functionality manually.

feat(core/amazon/titus): restrict menu items on managed resources

---

app/scripts/modules/core/src/help/HelpField.tsx

I don't think we need to git blame this, let's just all agree it's a good change to make and move on.

fix(core): do not log all help contents to the console

---

test/functional/tests/google/pages/CreateServerGroupModalPage.ts

Modal elements were standardized on `<h4>` in https://github.com/spinnaker/deck/pull/7743. This updates a breaking a functional test to look for that el.

fix(core): Update functional tests with new modal heading el

---

app/scripts/modules/core/src/cluster/rollups.less
app/scripts/modules/core/src/healthCounts/HealthCounts.tsx
app/scripts/modules/core/src/healthCounts/healthCounts.less
app/scripts/modules/core/src/pipeline/config/stages/deploy/deployExecutionDetails.html
app/scripts/modules/core/src/serverGroup/ServerGroupHeader.tsx

This is bad (and what it looks like right now):
It would be nice if it looked like this (i.e. this PR):
Also, when there is a running task, and some load balancers, right now it looks like this:
And it would be better like this:

fix(core): keep health counts on one line in server group title

---

app/scripts/modules/core/src/confirmationModal/confirmationModal.service.ts

I removed this yesterday, thinking we didn't want it, but, uh, we do. Without this, every call to `confirmationModal.confirm` needs to add a `catch` block to handle the rejection, or Angular will complain and log an error to the console.
With it, they can still catch the rejection! They just don't need to.
*Edit*: It's a pain to catch the rejection with this change. You need to `.then` the result of the `.confirm` call and catch that. I don't see any cases in code where that matters, since we are not catching calls to `.confirm` anywhere (I looked at all 109 calls)

fix(core): catch/handle confirmation modal dismissal

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/core/src/managed/DeployingIntoManagedClusterWarning.tsx
app/scripts/modules/core/src/managed/index.ts
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts
app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

In the UI, we're doing a pretty good job preventing users from performing actions that will just get stomped. The create/clone server group flow is a little tricky: we want to let them select "Clone" on a managed server group: they might want to use it as a base to create a different (non-managed) cluster. And we can't disable the "Create server group" button.
This PR adds an alert that invalidates the command whenever they have configured the new server group to be in a managed cluster.
When the user clicks the button to pause management, there's that modal-over-a-modal experience, which I don't like, but it's important to really confirm that the user wants to pause management.
(forgive the deprecated region warning also being here, I am having trouble with my sandbox environment so …

feat(core/amazon/titus): do not allow create/clone in managed clusters

---

app/scripts/modules/core/src/managed/DeployingIntoManagedClusterWarning.tsx

A day will come when there is no Angular to yell about uncaught promise rejections

fix(core): catch cancelling of resource pause from server group modal

---

app/scripts/modules/core/src/pipeline/config/validation/upstreamHasFlagValidator.builder.ts

turns out when you register triggers/stages outside the point where normal triggers in `core` et al are registered (like in our internal-only modules at Netflix), this validator never sees them today because it has a stale list of triggers/stages from the registry. Instead, let's just deref the registry on every validator run.

fix(core/pipeline): use fresh trigger + stage list for upstream flag validation

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/amazon/src/help/amazon.help.ts
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/CloudFormationChangeSetInfo.tsx
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackConfig.controller.ts
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackConfig.html
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackStage.ts
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecution.service.ts
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecutionApproval.tsx
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecutionDetails.tsx
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecutionDetailsAsk.less
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecutionLabel.tsx
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/evaluateCloudFormationChangeSetExecutionMarkerIcon.tsx
app/scripts/modules/amazon/src/reactShims/aws.react.injector.ts
app/scripts/modules/core/src/domain/IExecutionStage.ts
app/scripts/modules/core/src/pipeline/config/stages/common/index.ts
app/scripts/modules/core/src/pipeline/executions/execution/ExecutionMarker.tsx
app/scripts/modules/core/src/pipeline/executions/execution/executionMarker.less

Add components for aws cloudformation change set execution.
* Reorganize and add forms for the ChangeSet Name, default action and execution tick.
* Helper for the default action on replacement.
* In case of replacement there is a hold task much like manual judgement stage, asking for user input to continue:
Thing is that we cannot know if a change set has a replacement until it's created, so this will allow the user to choose the behavior in advance or what to do at runtime.
Liked issue:
https://github.com/spinnaker/spinnaker/issues/5091

feat(aws/cfn): Cloudformation ChangeSet execution

---

app/scripts/modules/core/src/forms/mapEditor/MapPair.css
app/scripts/modules/core/src/forms/mapEditor/MapPair.tsx
app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
app/scripts/modules/core/src/presentation/forms/validation/useValidationData.spec.tsx
app/scripts/modules/core/src/presentation/forms/validation/useValidationData.ts

Closes https://github.com/spinnaker/spinnaker/issues/5279
Manual cherry-pick of each of the three commits from [this PR](https://github.com/spinnaker/deck/pull/7601) into the 1.17 release branch.
- fix(core/presentation): MapEditor: Make errors fill the entire row width.
- fix(core/presentation): FormikFormField: call revalidate whenever internal validators change
- fix(core/presentation): pass objects through in useValidationData

fix(core): manual cherry-pick of MapEditor fixes

---

app/scripts/modules/core/src/application/config/applicationAttributes.directive.js

Fixes https://github.com/spinnaker/spinnaker/issues/5306
Needs to be cherry picked for 1.18

fix(appconfig): Fix error thrown when slack object is not defined

---

app/scripts/modules/core/src/modal/modals.less

When I refactored this four weeks ago, I changed the z-index from `2` to `6` because I didn't see any reason for it to be `6`.
It's come to our attention that there was, in fact, a reason it was `6` and not `2`.

fix(core): display task monitor above page navigator chrome

---

app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx

Believe it or not, the `Use default` (IAM profile) checkbox covered the text field basically rendering it unclickable:
The checkbox interaction also feels awkward so instead I switched to a clickable link below the check box instead:
Et voila, problems solved.

fix(titus): Blank IAM profile unclickable

---

app/scripts/modules/appengine/src/loadBalancer/details/details.controller.ts
app/scripts/modules/appengine/src/serverGroup/details/details.controller.ts
app/scripts/modules/core/src/pipeline/details/stageSummary.component.ts
app/scripts/modules/core/src/serverGroup/details/serverGroupWarningMessage.service.ts

The body is now run through the markdown compiler, which treats 3+ leading spaces as a preformatted text block, which is not what we want.

fix(core): do not render the server group warning message in <pre>

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/LineChartHack.css
app/scripts/modules/core/src/presentation/modal/ModalFooter.module.css
app/scripts/modules/core/src/presentation/modal/ModalHeader.module.css
app/scripts/modules/core/src/search/widgets/search.less

These red warnings have been driving me a little crazy when I run deck locally:
This change gets rid of those warnings.
The only thing that changes visually is the border/shadow on the v2 search input when it's focused:
_Current_
_This PR_
The CSS for the box-shadow is kind of kludgy. I set the `spread-radius` to a negative value to emulate a faded color. Realistically, our users are not going to notice this change, and it's all going to be rewritten in year so these styles will go away.

chore(core): convert colors to stylesheet variables

---

app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx

What the title says... Silly mistake.

fix(stage): Remove extraneous $ character from Import Delivery Config details

---

app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupIngress.html

When adding a new security group ingress rule, selecting ICMP protocol defaults to port 7001. This is out of range for ICMP. Users recommended defaulting the start and end port to 0.

fix(aws): Icmp port range should default to a port in range

---

app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts

I don't know why I ran into this, and it doesn't matter much (nothing blows up, no compiler errors or warnings), but every place this is implemented provides a default value for `mode`, and it's frequently called with just two arguments, so let's reflect that here.

fix(core): correct method signature for buildServerGroupCommandFromExisting

---

app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.spec.tsx
app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx

1. The text input replaces newline characters with single spaces, which is no good with YAML.
2. Explicitly setting the position on the hidden input keeps it from taking up space. I was running into a situation where I had a textarea in a modal and, when I clicked the copy to clipboard button, it put the input next to the textarea, which threw off the layout.
3. Someone added the `className` prop for the button attribute but never wired it up, so I wired it up.

fix(core): allow newlines in CopyToClipboard

---

app/scripts/modules/core/src/api/ApiService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts

Managed Delivery export returns `application/x-yaml;charset=utf-8` as its `content-type` header, so let's allow that.

feat(core): allow yaml responses from ApiService

---

app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.spec.tsx
app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx

I think we always want to provide user feedback when clicking a "Copy to Clipboard" button that something was copied — especially since we do it almost every time (except one, and soon another).
This change lets you add a "Copy to Clipboard" button with custom text and still get the "Copied!" tooltip when clicking the button.

feat(core): always show copied tooltip on CopyToClipboard

---

app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
app/scripts/modules/core/src/presentation/forms/inputs/JsonEditor.tsx
app/scripts/modules/kubernetes/src/v2/manifest/editor/json/JsonEditor.tsx

Still tracking down one of the noisy ones...
**Before**
**After**

fix(core/kubernetes): clean up console noise in tests

---

app/scripts/modules/core/src/modal/index.ts
app/scripts/modules/core/src/modal/wizard/ModalWizard.ts
app/scripts/modules/core/src/modal/wizard/WizardPage.tsx
app/scripts/modules/core/src/modal/wizard/index.ts
app/scripts/modules/core/src/modal/wizard/v2wizardPage.component.ts
app/scripts/modules/core/src/pagerDuty/Pager.tsx

This cleans up the last of the console noise when running tests:
```
WARNING in ./app/scripts/modules/core/src/modal/index.ts 5:0-82
"export 'IWizardPage' was not found in './wizard/ModalWizard'
WARNING in ./app/scripts/modules/core/src/modal/index.ts 5:0-82
"export 'IWizardPageState' was not found in './wizard/ModalWizard'
WARNING in ./app/scripts/modules/core/src/pagerDuty/Pager.tsx 369:88-105
"export 'SortDirectionType' was not found in 'react-virtualized'
WARNING in ./app/scripts/modules/core/src/pagerDuty/Pager.tsx 369:125-142
"export 'SortDirectionType' was not found in 'react-virtualized'
```
The `ModalWizard` ones are (I think) related to duplicate interface names found in `WizardPage`.
I don't know why TS is having trouble with `SortDirectionType`. As far as I can tell, it's only …

chore(core): clean up import warnings

---

app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx

If you're out there tabbing around on the screen, you can end up with your cursor hidden away in a textarea and you can't see why. It's no good.

fix(core): prevent tabbing into CopyToClipboard hidden input

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/defaultBase64.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/bitbucket.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/bitbucket/defaultBitbucket.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/defaultDocker.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/docker/docker.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/defaultGcs.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gcs/gcs.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/defaultGithub.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/github/github.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/defaultGitlab.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitlab/gitlab.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/helm/helm.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/defaultHttp.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/http/http.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/ivy/ivy.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/jenkins/jenkins.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/maven/maven.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/defaultS3.artifact.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/s3/s3.artifact.ts

The find artifacts from execution stage is not able to load the widget for each artifact type; creating the controller is broken because the constructors are not annotated with dependency injection information and we are running in strict-di mode.
Fix this by extracting the anonymous controller for each artifact type into a function and annotating it with injection information. (I'm not aware of a way to annotate an anonymous function, except
by doing Object.assign(function() {}, { $inject: 'abc' }) which
seemed less readable.)

fix(artifacts): Fix find artifacts from execution stage

---

app/scripts/modules/core/src/pipeline/pipeline.states.ts

Adds onto #7076 
Basically allows all the usual params to get propagated through. For example: from `/#/executions/ABC123?stage=43&step=0` to `/#/applications/egg/executions/details/ABC123?stage=43&step=0`

feat(core): Forward params through execution lookup

---

app/scripts/modules/core/src/pipeline/manualExecution/Parameters.tsx
test/functional/tests/core/manual_execution_smoke_test.spec.ts.mountebank_fixture.json
test/functional/tests/core/pages/ManualExecutionModalPage.ts

@maggieneterval @ethanfrogers 
fixes the lost functionality mentioned in https://github.com/spinnaker/spinnaker/issues/4890 during angular -> react migration by displaying supplied labels on the manual execution gui.
@maggieneterval I was tracking down how to get the labels to display in the execution details and tracked it down to https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/ApplicationController.groovy#L124 . The problem is, it looks like this is returning a list of linkedhashmaps and the parameters themselves are just a map of name->values for the parameters. Do you have any thoughts on how we could easily get the labels returned as well? Would it be good to push this to a later PR?
Lastly, I updated …

fix(deck): use label for parameters in manual execution if supplied

---

app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationExecutionDetails.tsx
app/scripts/modules/amazon/src/pipeline/stages/deployCloudFormation/deployCloudFormationStackStage.ts
app/scripts/modules/core/src/pipeline/config/stages/common/index.ts

The CFN Stage is not showing the error when failing. With this feature the error is shown.
Before:
After:

feat(deck): Add execution error details to Task Status in Cloud Formation Stage

---

app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html

Sometimes the bugs Angular templates manage to silently hide all the way into production are truly awe-inspiring.

fix(titus/serverGroup): use correct prop name for managed resource banner

---

app/scripts/modules/titus/package.json

fix(titus/serverGroup): use correct prop name for managed resource banner (#7820)
refactor(titus): Removing container migration as it is no longer used (#7807)

chore(titus): bump package to 0.0.126

---

app/scripts/modules/amazon/src/instance/details/utils.ts

The instance details panel was showing "Instance not found" when an instance in application A was attached to a load balancer in application B. Throwing `error: group is undefined`. 
The bug causing the group to be `undefined` was fixed in a prior PR, so this PR adds an extra layer of safety if the `group` is not found.

fix(amazon): Prevent error if target group is undefined

---

.github/workflows/ci.yml
karma.conf.js

In the process of doing this, I added a dependency on [Puppeteer](https://github.com/puppeteer/puppeteer), which is the Chrome Dev Tools team-maintained version that pulls in everything needed to run Chrome in CI (see https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer).

chore(builds): Adds GHActions as CI job (PRs, master, release branches

---

app/scripts/modules/core/src/index.ts

[Recent changes](https://github.com/spinnaker/deck/commit/b51dce46be3df14070f06e06de874108dcf23569#diff-1edca6440bc3b35b161749f95923b0cc) introduced a type error. The types from `ExecutionMarkerIcon` were not made available outside `core`.  Re-exporting types from this module to make them available outside `core`.

fix(core): Re-exporting types from ExecutionMarkerIcon to make it available outside core

---

README.adoc

Per discussion at the UI SIG, let's add information about the UI SIG to Deck's README. Let's simply reference the governance page instead of duplicating the meeting details here.
I also [updated the governance README](https://github.com/spinnaker/governance/pull/99) to include the meeting link, so hopefully there will be less confusion there.

feat(readme): add UI SIG link to README

---

app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx
app/scripts/modules/ecs/src/serverGroup/configure/wizard/taskDefinition/TaskDefinition.tsx

Enable filtering on container image and target group when creating or updating a server group.
Fixes: https://github.com/spinnaker/spinnaker/issues/5309

fix(ecs): enable filtering on container image and target group

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/index.ts
app/scripts/modules/core/src/plugins/index.ts
app/scripts/modules/core/src/plugins/plugin.module.ts
app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
app/scripts/modules/core/src/plugins/plugin.registry.ts

Load manifest from gate URL: `/plugins/deck/plugin-manifest.json`
Continue to load pre-baked manifest from the local deck asset `/plugin-manifest.js`
*BREAKING CHANGE*: IPluginManifest renamed to IPluginMetaData and shape changed
from: `{ name, version, devUrl }` to: `{ id, version, url }`
*Migrate plugin-manifest.js to use `id` and `url`*
IPluginManifest now describes the shape of plugin-manifest.js
*BREAKING CHANGE*: Plugins are no longer loaded from settings.js or settings-local.js
*Migrate pre-baked plugin metadata to plugin-manifest.js*

feat(plugins): Load plugins and plugin manifest from gate

---

app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
app/scripts/modules/amazon/src/instance/details/instanceDetails.html

Amazon supports instances with IPv6 addresses, so Spinnaker should expose those addresses in the instance details section. 
IP addresses from the v6 family are all public. Also, multiple interfaces can be attached to a v6 instance, so each may have N number of IPv6 addresses. Here are some possible scenarios for an aws instance:
1. One Private IPv4 with one public IPv4 (currently supported)
2. One Private IPv4 with one or more IPv6
3. Only IPv6 addresses, maximum one per network interface
4. One private IPv4, one public IPv4, and one or more IPv6 address (rare edge case)
This PR enables support for the last 3 scenarios.

feat(amazon): Expose addresses for IPv6 instances

---

.github/workflows/ci.yml
.travis.yml
app/scripts/modules/assert_package_bumps_standalone.sh
app/scripts/modules/build_modules.sh
app/scripts/modules/build_order.sh
app/scripts/modules/oracle/src/pipeline/stages/bake/ociBakeStage.js
app/scripts/modules/oracle/webpack.config.js

this change to the github actions workflow bypasses unit tests and builds if all that changed was package bumps.
I removed the separate "Ensure package bumps are pure" job in favor of running this check before each check.  This is because I couldn't find a way to make the other jobs conditional on the purebump job.  This adds a lot of extra boilerplate (an if block on every step).  Hopefully in the future we'll have other options.

Fast package bumps

---

.github/workflows/approve_package_bumps.yml

This needs a `GITHUB_TOKEN`  ~added to Deck's Settings Tab which can only be done by a member of the TOC.~
~https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#about-encrypted-secrets~
apparently this token is provided by default.
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

feat(package): auto-approve and merge pure package bumps

---

app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/CheckPreconditionsExecutionDetails.tsx

@maggieneterval @ethanfrogers this PR closes https://github.com/spinnaker/spinnaker/issues/5097 by showing the expression in the check precondition stage execution details .
When doing this I also noticed the expression itself was being escaped when displayed (eg parameters["not"] != "hello" -> parameters[\\"not\\"] != \\"hello\\"). This looks to be due to using JSON.stringify and the values being strings not objects. I didn't see any reason this would be needed otherwise, so I removed it. Let me know if you think it should stay and I can drop that commit.

feat(deck): show expression in check precondition execution details

---

app/scripts/modules/assert_package_bumps_standalone.sh

This was previously having false positives if the 'version' wasn't bumped but something within 3 lines in package.json was changed. 
```
--- a/app/scripts/modules/core/package.json
+++ b/app/scripts/modules/core/package.json
@@ -3,6 +3,7 @@
"version": "0.0.448",
"main": "lib/lib.js",
"typings": "lib/index.d.ts",
+  "comment": "This is a comment",
"scripts": {
"clean": "../../../../node_modules/rimraf/bin.js lib",
"lib": "npm run clean && npm run css-types && ../../../../node_modules/typescript/bin/tsc && node ../../../../node_modules/webpack/bin/webpack.js",
```

fix(purebump): Fix purebump detection script to not false positive

---

.github/workflows/ci.yml
.mergify.yml

This is an attempt to simplify the status checks for branch protection and also for mergify.

chore(actions): Create a master job that 'needs' all the other CI jobs

---

app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js

- Setting `state.isNew` to `true` during clone which is used in the overridden component

fix(aws): Fix to set right state while cloning security group

---

app/scripts/modules/amazon/src/help/amazon.help.ts
app/scripts/modules/amazon/src/loadBalancer/configure/network/TargetGroups.tsx

NLBs require that the healthy and unhealthy threshold are equal so the UI only has one user input for this value. This is confusing for users as they expect to see healthy threshold and unhealthy threshold, like ALBs. 
This PR adds a `HelpField` to explain why the UI does not delineate between the healthy and unhealthy threshold.

fix(amazon): Clarify NLB healthcheck threshold requirements

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx

When authenticating an ALB listener rule, the select field is empty if there are no configs found. This is due to configuration being nonexistent or being configured improperly for the application. This PR adds a warning in the dropdown (in addition to the help field), so it does not look like an error rendering the options.

fix(amazon): Add a warning when no oidc conifgs are found

---

app/scripts/modules/amazon/src/instance/details/utils.ts

null check when a servergroup is reported to have a target group (but that target group doesn't actually exist)

fix(amazon/instance): fix npe when applying health to instances

---

app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx

Add support for image overriding, which allows user to build with an image from
upstream stages or triggers.
Add support for buildspec overriding, which allows user to parameterize his/her
buildspec.
Add heading for each section to make the UI more clear.

feat(codebuild): Add support for overriding image and buildspec

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts

Otherwise existing policies get dropped on edit operations

fix(amazon): Preserve policyNames in CLB descriptions

---

app/scripts/modules/core/src/account/AccountSelectInput.tsx

```
Warning: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
undefined
Formik cannot determine which value to update. For more info see https://github.com/jaredpalmer/formik#handlechange-e-reactchangeeventany--void
```

fix(core/account): AccountSelectInput pass 'name' in synthetic event

---

app/scripts/modules/amazon/package.json

fix(amazon/loadBalancer): Fix the default dereg delay value in help text (#7894)
fix(amazon): Preserve policyNames in CLB descriptions (#7897)
fix(amazon/instance): fix npe when applying health to instances (#7893)
fix(amazon): Add a warning when no oidc conifgs are found (#7883)
fix(amazon): Clarify NLB healthcheck threshold requirements (#7890)

chore(amazon): Bump to 0.0.239

---

app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts

This case never worked correctly for Titus because we would set `command.region = null` then try to do `command.region.includes('${')` which would always blow up.
Protecting it against null allows it to actually reset the region when the new account is not in that region.

fix(titus): Fix resetting region when updated account is not in region

---

app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx

now that spel v4 is live and glorious in orca let's make deck create new pipelines with that as default

feat(spel): default new pipelines to spel v4

---

app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js

The stage config for a pipeline stage starts off with all parameters having `Use default` checked.
In addition to this, we also render the default parameter value (if any) in a disabled text box.
When unchecking `Use default`, we clear out the text box, making the user think that this is now set to something (say an empty string).
Regardless of what the user thinks happened, the fact we cleared out the default value would communicate that when the stage executes, the child pipeline will NOT be executed with the default value.
This is not the case because we did not default to an empty string and we do not set a value for that parameter until something is typed into the text box.
This change makes it so that as soon as `Use default` is unchecked, the parameter is set to an empty string.

fix(pipeline): Not 'Use default' should be empty string

---

app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildSourceList.tsx
app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/EditAwsCodeBuildSourceModal.tsx
app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/IAwsCodeBuildSource.tsx

Refactor the stage definition so that all source related fields go into one single structure.
This is helpful when it comes to multiple sources because of the reusability that the single
structure provides. For primary source, artifact is not required. Users can override source
version without touching source artifact. However, in secondary sources, users must specify
an artifact. Otherwise, there's no way to link a secondary source version to a secondary source
defined in the project configuration.

feat(codebuild): Add support for multiple sources

---

app/scripts/modules/core/src/plugins/plugin.module.ts

Otherwise deck will not go to the default route until the next digest cycle (kicked by the version checker).

fix(core): Letting angular know when the promises resolve

---

app/scripts/modules/core/src/ci/igor.service.ts
app/scripts/modules/core/src/pipeline/config/stages/awsCodeBuild/AwsCodeBuildStageForm.tsx

Change text input field to select input field for project name
so that user could select project name from a dropdown list
instead of manually type in the name.
Fix a null pointer issue when creating a new CodeBuild stage.

feat(codebuild): List project names

---

app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useDeepObjectDiff.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useDeepObjectDiff.hook.ts

Useful when you want to do a deep equals on an object that's used as a dependency in a hook. Test has a small usage example.
Both the hook itself and the test are basically lifted right out of UI Router as a result of [this comment](https://github.com/spinnaker/deck/pull/7903#discussion_r380361946)

feat(core/presentation): add useDeepObjectDiff hook for easier memoization of objects

---

app/scripts/modules/core/src/presentation/index.ts
app/scripts/modules/core/src/presentation/tables/Table.tsx
app/scripts/modules/core/src/presentation/tables/TableCell.tsx
app/scripts/modules/core/src/presentation/tables/TableContext.tsx
app/scripts/modules/core/src/presentation/tables/TableRow.tsx
app/scripts/modules/core/src/presentation/tables/index.ts
app/scripts/modules/core/src/presentation/tables/minimalNativeTableLayout.less
app/scripts/modules/core/src/presentation/tables/minimalNativeTableLayout.tsx
app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx

Don't merge, depends on #7899 and #7901. CI will likely fail until those are merged.
This is another chapter of adding some re-usable components to match @gcomstock's new design work, in support of a Managed Delivery view. My goal was to provide a high-level component API for creating tables which — similar to previous work on form fields — could serve as a generic scaffold with pluggable points for different kinds of table layouts. I'm starting with two (very different) layout implementations because that's what my current work calls for, but the idea is that adding or iterating on layouts themselves should be pretty isolated from actual usage (vs. requiring refactors of all consuming code).
To start, here's some example screenshots of the end result:
<details>
<summary>"Mobile" display …

feat(core/presentation): add Table components, multiple table layouts

---

app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx

Currently when there's an issue with the trigger used for the `importDeliveryConfig` stage and some fields are missing, we throw trying to call `substring()` on the `hash` field and the entire executions view goes blank (along with permanently busting the entire UI until a full page reload).
This change uses a `Not found` fallback for all the trigger-related fields we surface, so things render and the page continues to work. Looks like this:

fix(core/pipeline): handle missing trigger fields in importDeliveryConfig stage

---

app/scripts/modules/core/src/presentation/modal/ModalBody.module.css
app/scripts/modules/core/src/presentation/modal/ModalHeader.module.css

Couple small tweaks to the existing `Modal` component family:
- I'm adding `display: flex` to the actual content container for modals (what your view code ends up in). It's been a huge pain trying to get child containers to fill vertical space appropriately (among other frustrations), and making the body a flex container makes things much less gross. I expect at some point some thing we try to put inside here will go against that trend, but we can always adjust later
- The browser-default focus outline on the close button was getting cut off and mangled in weird ways and generally looked strange when you clicked the button. I'm removing it entirely for now, though it might be nice to add a real focus outline of our own

fix(core/modal): display: flex on body, remove outline on close button

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
app/scripts/modules/core/src/managed/ManagedResourceDiffTable.tsx
app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.less
app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx

**Depends on #7936 and #7937, don't merge yet.**
We've had a nifty API for a while that lets you see an event history of all the things that have happened to a managed resource over time — changes in desired/actual state, tasks being launched, etc. Now it's time to make all that available to folks directly in deck while they're looking at a resource. As a fun bonus, this is also one of the first views in deck that has full (for some definition of "full") mobile/small screen support. Here's what it looks like:
<details>
<summary>Smaller screen</summary>
</details>
<details>
<summary>Larger screen</summary>
</details>
<details>
<summary>Interactions on small screens</summary>
</details>
<details>
<summary>Interactions on larger screens</summary>
</details>
<details>
<summary>Expanding all …

feat(core/managed): add managed resource history modal

---

app/scripts/modules/core/src/presentation/forms/inputs/NumberInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/utils.ts

This reverts https://github.com/spinnaker/deck/pull/7881 and fixes it in the `orEmptyString` helper method

fix(core/presentation): Fix controlled/uncontrolled warning for number input

---

app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.controller.js

- Add `description` to IP Range rules , this will be used in the custom component.

fix(aws): Support security group ip range rule description

---

app/scripts/modules/core/src/account/AccountSelectInput.tsx

We got bit again by the issue with extending interfaces that were imported using one of our package aliases (`core`, `amazon`, etc.). This just moves to using a relative import to get around it. The interface in question only extends one other interface which is defined in the same file.

fix(core/account): use relative import for IFormInputProps interface

---

app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html

Use preferSourceCapacity instead of useSourceCapacity when configuring a serverGroup to use the previous server groups capacity.
Fixes: https://github.com/spinnaker/spinnaker/issues/4690

fix(ecs): use preferSourceCapacity instead of useSourceCapacity when configuring a serverGroup

---

app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.less
app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx

We've consistently gotten feedback that the grey arrow on each resource in the `Where` column is confusing because it _looks_ like an expand/collapse arrow, but it isn't. That combined with folks needing to re-learn that expand/collapse controls are on the right has been leading to a bit of awkwardness. Since for now there's really only two sections to the hierarchy in the `Where` column (account + resource name) I'm just removing it. We can figure out what visual treatment works better to communicate hierarchy better separately.
Before: 
After:

fix(core/managed): remove arrow visual treatment on history modal

---

.github/workflows/ci.yml
package.json
test/functional/tests/core/pages/Page.ts

Looks like we can "fix" the functional tests by bumping up the timeout.  I'd like to merge this before the migration to cypress lands.

fix(test/functional): fix functional tests by increasing the timeout to 60 seconds

---

app/scripts/modules/core/src/presentation/forms/fields/FormikFormField.tsx
app/scripts/modules/core/src/presentation/hooks/useIsFirstRender.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useIsFirstRender.hook.ts

Problem:
When a FormikFormField mounted, it was always forcing a `validateForm` call.
Each field in a form would make this same call, and each revalidate would cause a full re-render.
These revalidate/rerenders stack up and cause a noticeable delay to initially loading the form.
Forcing revalidation of the form is only necessary if the formfield added new validations.
This PR does two things:
1) It avoids revalidating on the first render if there are no actual `internalValidators`
2) It coalesces revalidate calls from multiple form fields within the same form into a single call.
It waits for the next tick, then invokes `validateForm` once.

feat(core/presentation): Perf optimization to avoid unnecessary re-renders

---

app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx

Adds a bit more logic to the Import Delivery Config stage's execution details component so it displays more user-friendly error messages when the error is in parsing a delivery config.
Closes https://github.com/spinnaker/keel/issues/818

feat(managed-delivery): Improve errors displayed from unparseable delivery configs

---

app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx

`standardGridTableLayout` makes rows sticky when expanded, so they're still visible when looking at large amounts of expanded content. Previously the header and its expanded content were siblings without a container which led to some jankiness on scroll (the GIF makes the colors a bit hard to differentiate, but watch the "Drift detected" header stay on top of subsequent rows):
<details>
<summary>Before</summary>
</details>
This change sticks both those elements in a container and moves some margins around so that the header is kept where it belongs:
<details>
<summary>After</summary>
</details>

fix(core/presentation): properly contain sticky row headers on scroll

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/TargetGroups.tsx
app/scripts/modules/core/src/authentication/AuthenticationInitializer.ts

The `port` and `protocol` fields were duplicated in the target group health check section of the modal. This PR removes the extra fields so that there is only one.

fix (amazon/target group): Remove duplicate form fields for target group health

---

app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx

**Depends on #7987 and #7988**
Now that we have a way of viewing historical resource events in the UI, it makes sense to offer a quick way to jump into that view when learning about a resource's current status in the infrastructure view. This PR adds a "History" button to all status popovers that looks like this:
In addition, I've tweaked the language on a few of the statuses to offer guidance around when it makes sense to check the History (e.g. `DIFF`, `ACTUATING`, `ERROR`, etc.).
As a bonus, I fixed the deep-linking to the docs which broke when they moved from Reference to Guides. I'll be opening up a separate PR to modify the spinnaker.io doc page with updated screenshots for each status as well.
(cc @gcomstock)

feat(core/managed): add history modal button to status popovers, revise language

---

app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
app/scripts/modules/core/src/presentation/hooks/index.ts

**Depends on ~~https://github.com/spinnaker/deck/pull/7984~~ and https://github.com/spinnaker/keel/pull/842**
When folks are looking at the resource history modal and trying to get a sense of what's been happening with their resource, it's valuable to update the view in real time. This change uses the [`usePollingData`](https://github.com/spinnaker/deck/pull/7984) hook to poll for new events every 10 seconds. The bulk of the changes are actually for optimizing rendering, not for wiring up the polling itself.
Rendering the event table itself isn't that much work, but when event rows are expanded the diff tables inside them can have complex component trees which in aggregate consume an unacceptable amount of rendering time. That problem is pretty simple to work around with memoization, it …

feat(core/managed): poll for new history events in modal

---

app/scripts/modules/amazon/src/index.ts

- Export securityGroup interfaces , missed updating `index.ts` for @spinnaker/amazon  in the last PR #8001

fix(amazon): Export securityGroup interfaces

---

app/scripts/modules/core/src/pipeline/filter/executionFilter.service.ts

While there could be an argument to be made that it's nice to see more recently running things, overall sorting by anything other than `startTime` is mostly unexpected and confusing to the user.
Because the executions endpoint returns a limited number of things ordered by `startTime` not `endTime`, ordering by`endTime` is only more confusing because requesting newer items could get sandwiched between existing items, which is just plain weird.

fix(core): Order executions by startTime not endTime

---

app/scripts/modules/core/src/pipeline/config/PipelineRegistry.spec.ts
app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts

- refactor(core/pipeline): Simplify logic finding matching stage types
this is a pure refactor
- fix(core/pipeline): fall back to 'unmatched' stage (JSON editor) instead of null
this changes fallback behavior

Pipeline stage tweaks

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/managedResourceDecorators.ts
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts

As part of trying to auto-generate OpenAPI schemas for resources, we're moving from a `kind` like `cluster` or `security-group` to a compound `kind` that includes both the concept of a 'group' and a version (so basically merging `apiVersion` and `kind`). This means kinds now look like `ec2/cluster@v1` or `ec2/security-group@v1`. We rely on `kind` in various places for matching infrastructure with a resource definition, so this PR attempts to get us ready for that change in a backwards-compatible way to avoid any temporary downtime/bad behavior.
In short, I'm adding a `getKindName()` function that tries to regex its way into returning what we were operating on before (the "name" part of the compound string). This means we can keep most of our code the same for now and only worry about the …

fix(core/managed): support new group/name@version syntax for kind field

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/managed.dataSource.ts

Opening a new PR for #8020 which got unintentionally merged (then reverted).
Depends on https://github.com/spinnaker/keel/pull/848
The types are probably the most interesting thing in this PR. There's a fair amount of duplication in different views of an entity, for example:
* `environments` vs `artifact.version.environments`
* `environments`: a light summary of all resources and all artifacts related to those resources
* `artifact.version.environments`: a view of each environment as it relates to the artifact's specific version (i.e. time that version was deployed in that specific environment)
* `artifacts` vs `environment.artifacts` vs `resource.artifact`
* `artifacts`: summary of all artifacts and all versions also including a join between a specific version and it's environment
* …

feat(md): Types and new data source for environments

---

app/scripts/modules/core/src/pipeline/config/PipelineRegistry.spec.ts
app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts
app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/index.ts
app/scripts/modules/core/src/pipeline/config/stages/preconfiguredJob/preconfiguredJobStage.ts
app/scripts/modules/core/src/pipeline/index.ts
app/scripts/modules/core/src/plugins/plugin.registry.ts

This allows registration of a preconfigured job stage UI. The parameter configuration for the stage is fetched from gate.  
This PR also enables plugins to export preconfiguredJob stages

Preconfigured job stage

---

app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useDataSource.hook.ts
app/scripts/modules/core/src/presentation/hooks/useObservable.hook.ts
app/scripts/modules/core/src/presentation/hooks/useObservableValue.hook.ts

This introduces 3 new hooks, each one builds off the former:
**useObservable**
Calls a callback every time an observable emits a value. When you get that value is determined by the observable — if it immediately emits, you'll receive a value then, but if it only emits when something changes you might not get called for a while (or ever)
**useObservableValue**
Delegates to `useObservable` for subscribing to an observable, but returns the value directly from the hook and takes care of triggering a component re-render when the value changes. Also accepts a default value so you can avoid an initial `undefined` value on renders before the first observable value is emitted
**useDataSource**
Delegates to `useObservableValue`. When given a data source, immediately returns an object …

Add hooks for observables, data sources

---

app/scripts/modules/core/src/managed/Environments.tsx

Thanks to #8042 we can finally use the `useDataSource` hook in a meaningful way (not having to deal with `undefined` as long as we have `defaultData`).

refactor(md): Use useDataSource hook

---

app/scripts/modules/core/src/instance/loadBalancer/InstanceLoadBalancerHealth.tsx

The health failure reason used to be a popover, but the functionality was lost during a refactor.
Instead of restoring the popover functionality, always surface error reasons below a target group.
Also change the layout to flexbox to avoid weird line wrapping issues.

fix(amazon/instance): Show health status failure reason for load balancers

---

app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/Frigga.ts

This is temporary.
The following pieces of information is much more meaningful to users of the environments UI than the currently available raw artifact version string:
* A meaningful artifact version number (usually the CI build number)
* Commit hash
Until keel builds proper support for returning rich artifact metadata, Queen of Asgard will parse that information out from the artifact version string for some artifact types.
Before
After

feat(md): Generate fallback artifact info using Frigga

---

app/scripts/modules/core/src/managed/ArtifactDetail.less
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx

Most of the changes here are for adding a detail pane to the right column of Environments when a specific artifact version is selected:
There are some other tweaks I'll call out in comments given they're pretty contextual.

feat(core/managed): add artifact detail pane to environments

---

app/scripts/modules/ecs/src/ecs.help.ts

Fixes https://github.com/spinnaker/spinnaker/issues/5541
Screen shot:

fix(ecs): Update tooltip for using previous server group capacity

---

app/scripts/modules/kubernetes/src/shared/help/kubernetes.help.ts
app/scripts/modules/kubernetes/src/v2/manifest/wizard/BasicSettings.tsx
app/scripts/modules/kubernetes/src/v2/manifest/wizard/ManifestWizard.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx

There is currently a readonly input field displaying the name of the application in Deploy (Manifest) and Run Job (Manifest) stages, and in the ad-hoc Deploy wizard. Since we already display the name of the application prominently in the nav bar and define a Spinnaker application in our documentation, let's remove this unnecessary input.
<details><summary>Before</summary>
<p>
</p>
</details>
<details><summary>After</summary>
<p>
</p>
</details>

feat(kubernetes): remove readonly application input

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/helm/BakeHelmConfigForm.tsx

Related to: https://github.com/spinnaker/spinnaker/issues/5589
Previously, we permitted all artifact types as input to Bake (Manifest) stage with the Helm render engine specified. However, this has led to confusion since only certain artifact types are appropriate. For example, the Git Repo artifact type does not yet support Helm (open feature request [here](https://github.com/spinnaker/spinnaker/issues/5249)), but it was available for selection. Let's explicitly whitelist acceptable artifact types for Helm bakes.

fix(kubernetes): whitelist helm artifact types for bake manifest stage

---

app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx

There are a whole bunch of different field names on history event objects which need to be checked in order to find out whether an event has something to provide for display. I recently found out about `exceptionMessage` in addition to the others, but missed a spot when adding it. That meant `ResourceCheckError` events weren't expandable, even if they had a message.

fix(core/managed): fix check for row expandability on history table

---

app/scripts/modules/amazon/src/instance/details/instanceDetails.html
app/scripts/modules/titus/src/instance/details/instance.details.controller.js
app/scripts/modules/titus/src/instance/details/instanceDetails.html

Currently, Titus instances do not expose IPv6 addresses. As a temporary workaround to unlock other IPv6 work, we will leverage the `agentId` and `awsAccount` to make a secondary call for this information. In the future we will remove the `addIpv6Addresses` function, since the instance will natively have an `ipv6Addresses` attribute.
Also, I have separated DNS headers for Public v4 addreses and Ipv6 Addresses (which are all public) based on some feedback.

fix(titus/instance): Temporary workaround to get IPv6 for Titus instances

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/managed/ArtifactsList.tsx

We were hard-coding all these progress bar steps as green because the API couldn't tell us what to show yet, but now it can!

feat(core/managed): use real data for version progress in Environments

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
app/scripts/modules/core/src/managed/ObjectRow.tsx

~~**Depends on https://github.com/spinnaker/deck/pull/8060, diff will be bloated and CI will fail until merged**~~
This does a very light refactoring pass to pull out our existing use of `ObjectRow` into a shared spot, adds some data massaging for getting a breakdown of environments + resources for a particular artifact version, and then shows that on the detail view:
Right now only environments that reference the artifact are displayed, **but** within those environments all resources are shown. Right now on the Keel side proper resource <--> artifact linkage is in the works and when that drops we'll filter down to just the compute resources that use that artifact.

feat(core/managed): add resource breakdown to artifact details

---

app/scripts/modules/kubernetes/src/v2/manifest/ManifestSource.ts
app/scripts/modules/kubernetes/src/v2/manifest/manifestCommandBuilder.service.ts

Closes https://github.com/spinnaker/spinnaker/issues/5596
👩 📈 🐛 😢 (This bug is my fault!)
Prior to this [refactor](https://github.com/spinnaker/orca/pull/3402), Orca assumed Kubernetes manifest operations with an unspecified `source` were `text`-based manifests. However, post-refactor, Orca expects clients to specify whether a manifest operation is `text` or `artifact` based. Stage-based operations already default to `text`, but ad-hoc applies from the Infrastructure view did not specify a `source`. Instead of defaulting to `text` in Orca, let's continue to require clients to specify a valid `source` and update the one client (ad-hoc applies) that left this field unspecified.
This commit is intended for cherry-picking into the 1.19 release branch. However, in a follow-up commit that is …

fix(kubernetes): specify manifest source as text for ad-hoc applies

---

app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageConfig.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifest.validator.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/PatchManifestStageConfig.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/PatchManifestStageForm.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx

Let's replace all Kubernetes stage-specific manifest source constants with the enum added as part of this change: https://github.com/spinnaker/deck/pull/8065

rerrefactor(kubernetes): replace duplicated manifest source constants with enum

---

app/scripts/modules/core/src/task/monitor/TaskMonitorWrapper.tsx

Without `monitor` in the effect's deps, If `monitor` did not exist on the initial render, the effect would only run once with a null monitor meaning we would never actually subscribe to the `statusUpdatedStream`, rendering a blank screen instead of the task monitor.

fix(core): Fix effect in TaskMonitorWrapper

---

app/scripts/modules/titus/src/instance/details/instance.details.controller.js

Titus instances were using the `awsAccount` field to fetch the host instance network interface information. The best field to use is the `environment` field since this is will always evaluate to a known host account-type (`test` or `prod`), whereas `awsAccount` can evaluate to anything and cause errors (e.g.: `workstation_test` instead of `test`).

fix(titus): Update host account environment

---

app/scripts/modules/core/src/artifact/ArtifactReferenceService.spec.ts
app/scripts/modules/core/src/artifact/ArtifactReferenceService.ts

- refactor(artifacts): clean up and add docs to `ArtifactReferenceService`
In the next commit, we will add a new method to this class. Let's add JSDoc comments to the existing methods to clarify their purpose. Let's also add a few missing types and change a couple of parameter names for clarity.
- feat(artifacts): add method for removing multiple artifact references from stages
In an upcoming PR, we will simplify some of the logic around updating triggers and associated artifacts. When a trigger is removed, we will need to handle removing each of its associated artifacts from consuming stages. Let's add a simple method that calls the existing `removeReferenceFromStages` method for each of a list of references.

refactor(artifacts): clean up ArtifactReferenceService

---

app/scripts/modules/core/src/managed/ArtifactDetail.less
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/NoticeCard.module.css
app/scripts/modules/core/src/managed/NoticeCard.tsx
app/scripts/modules/core/src/managed/ObjectRow.module.css

This is an early stab at some status indicators for each environment in an artifact's journey, along with explanatory cards for a subset of statuses. It's likely to change significantly in the very near future as @gcomstock and I flesh out the details, and for now I picked some random icons to use in lieu of the real ones.
**Current**
**Deploying (data is faked for this one so things don't line up between cards/sidebar):**
**Previous**
**Vetoed**
**Pending (never deployed)**

feat(core/managed): status indicators, explanation cards on artifacts

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx

Up until today we did not have the ability to tell whether a resource referenced a given artifact. [Now we do](https://github.com/spinnaker/keel/pull/905), so this change filters out all the non-referenced resources when looking at a particular version's journey. For example, here we only see one cluster resource per environment even though each environment actually contains many other resources (security groups, LBs):
Later I will likely add some sort of treatment that clarifies why you're only seeing those instead of every resource (e.g. a "4 other resources exist in this environment" link that goes to the overview of that environment).
Because the modeling for a resource's `artifact` field changed I also had to mess with resource rows on `EnvironmentList`, so I stuck a pill in for the …

feat(core/managed): show relevant resources on version details

---

app/scripts/modules/core/src/task/monitor/TaskMonitor.ts

This seemed to have been propagating and trigger other `onClick` handlers.

fix(core): Stop propagation of task monitor close event

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
app/scripts/modules/core/src/managed/ColumnHeader.module.css
app/scripts/modules/core/src/managed/ColumnHeader.tsx
app/scripts/modules/core/src/managed/EnvironmentRow.less
app/scripts/modules/core/src/managed/EnvironmentRow.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
app/scripts/modules/core/src/managed/NoticeCard.module.css
app/scripts/modules/core/src/managed/NoticeCard.tsx
app/scripts/modules/core/src/managed/ObjectRow.module.css
app/scripts/modules/core/src/managed/ObjectRow.tsx

Now that @gcomstock has very generously taken the time to move a bunch of icons over to our new SVG-powered `<Icon/>` component, it's time to give Environments UI a more polished look with more finalized icons:
**Before**
**After**
As a bonus while I was in here I added a tiny border radius tweak to the column headers (result of a discussion with @gcomstock) and fixed a `key` prop error that was totally my fault and I should've noticed earlier.

feat(core/managed): add real icons to Environments view

---

app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.controller.ts
app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookExecutionDetails.html

This change addresses how the "Wait for completion" Webhook feature displays progress. https://github.com/spinnaker/spinnaker/issues/4639
Progress is defined as so in the Webhook stage config UI:
> JSON path to a descriptive message about the progress in the webhook's response JSON.
However, when actually returned by a webhook, the progress is seemingly always displayed as a "Warning" with the text "Webhook failed". This is clearly not always the case. In the following screenshot, the webhook ended up returning SUCCESS and Orca passed the stage and kept going. Deck is making up the "failed" aspect:
<kbd><img width="532" alt="Screen Shot 2020-03-25 at 3 36 52 PM" src="https://user-images.githubusercontent.com/40628/77554594-928c6880-6eb6-11ea-83d2-71f08964ef57.png"></kbd>
This PR changes …

fix(webhook): Show 'Progress' as Info instead of Warning in webhookExecutionDetails

---

app/scripts/modules/core/src/artifact/ArtifactsModeService.ts
app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
app/scripts/modules/core/src/artifact/imageSourceSelector.component.ts
app/scripts/modules/core/src/artifact/index.ts
app/scripts/modules/core/src/artifact/react/StageArtifactSelectorDelegate.tsx
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js
app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
app/scripts/modules/core/src/pipeline/config/triggers/Triggers.tsx
app/scripts/modules/core/src/pipeline/config/triggers/TriggersPageContent.tsx
app/scripts/modules/core/src/pipeline/status/ParametersAndArtifacts.tsx
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/ManifestBindArtifactsSelectorDelegate.tsx
app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/runJob/KubernetesV2RunJobStageConfig.tsx

Related to: https://github.com/spinnaker/governance/pull/111
The `artifacts` and `artifactsRewrite` flags were intended to be [mutually exclusive](https://github.com/spinnaker/deck/pull/6694), but it is possible that this was not fully thought through, as there are several workflows (Find Artifact from Resource stage, Find Artifact from Execution stage) that currently require both flags to be enabled in order to use with the new UI. This PR addresses that bug and consolidates the artifacts feature flag checks to a single service.
- refactor(artifacts): consolidate artifacts feature flags checks
Adds `ArtifactsModeService`, which is responsible for the mapping between the four possible feature flag configuration states and the three possible UI experiences. Replaces each instance of logic …

refactor(artifacts): consolidate artifacts feature flags checks

---

app/scripts/modules/core/src/pipeline/config/stages/bake/bakeStageChooseOs.component.ts

When adding a new VM `Bake` stage, I noticed a bunch of console errors (`TypeError: Cannot read property 'displayName' of undefined`), because `baseOsOption` will be `undefined` for the first n render cycles. Let's read off it more safely and default the description to an empty string.

fix(core): fix NPE in getBaseOsDescription

---

app/scripts/modules/core/src/managed/ArtifactDetail.less
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx

After looking at them in the wild we decided we don't really like having indicators on the left side of every resource for every artifact state. It gets pretty busy:
Instead we're now removing them entirely for all states except `deploying`. Right now we can't show deployment progress at the resource level, so these indicators are kind of silly and static, but once we get there we'll treat them as pie chart progress indicators and some fanciness will ensue.
I also took the liberty of making the remaining indicator line up better with its surroundings, so the resource + notice card icons are back in proper alignment and the left edge of the indicator lines up with the left edge of environment rows:
(cc @gcomstock )

feat(core/managed): remove non-deploying state indicators

---

app/scripts/modules/titus/src/securityGroup/securityGroup.read.service.js
app/scripts/modules/titus/src/serverGroup/serverGroup.transformer.js

By adding an `awsAccount` attribute onto the Titus server group, we can get rid of the dirty `String.replace()` logic that was trying to derive the AWS account name from the Titus account name, which doesn't work perfectly if accounts are not created following strict convention.
More specifically, this addresses cases where the string logic failed and we basically fail resolving the security group because we were looking up the wrong account, or rather, we constructed an account string that didn't even exist.

fix(titus): Solidify mapping of titus to awsAccount

---

app/scripts/modules/core/src/cloudProvider/skin.service.ts
app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
app/scripts/modules/core/src/pipeline/config/stages/savePipelines/savePipelinesStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/deployManifest/deployManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/patchManifest/patchManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/scaleManifest/scaleManifestStage.ts
app/scripts/modules/kubernetes/src/v2/pipelines/stages/undoRolloutManifest/undoRolloutManifestStage.ts
halconfig/settings.js
settings.js

Since we already support `unsupportedStageTypes` to differentiate between Kubernetes V1 and V2 stages (and we will be removing V1 for release 1.21 anyway), I do not think there is a need for a `versionedProviders` feature flag to gate V2-specific stages. It is not configurable in Halyard, so this should be the only change necessary to remove the feature flag.

chore(core): remove versionedProviders flag

---

app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
app/scripts/modules/core/src/managed/ObjectRow.module.css
app/scripts/modules/core/src/managed/ObjectRow.tsx

Adding the ability to deep-link resources to their infrastructure view by applying the filters such as `q=name`, `stack`, `detail`. This is done via parsing `kind` and `id` from `resource` object.
[edit: adding screenshots]

feat(core/managed): Deep link resources to their infrastructure view

---

app/scripts/modules/core/src/application/config/appConfig.dataSource.js
app/scripts/modules/core/src/application/nav/navigationCategory.registry.ts
app/scripts/modules/core/src/application/service/applicationDataSource.ts
app/scripts/modules/core/src/loadBalancer/loadBalancer.dataSource.ts
app/scripts/modules/core/src/managed/managed.dataSource.ts
app/scripts/modules/core/src/pipeline/pipeline.dataSource.js
app/scripts/modules/core/src/securityGroup/securityGroup.dataSource.ts
app/scripts/modules/core/src/serverGroup/serverGroup.dataSource.ts
app/scripts/modules/core/src/task/task.dataSource.js

Given the svg icon loader (https://github.com/spinnaker/deck/pull/8056) and the upcoming Nav restructure, it is a good time to migrate the nav bar icons to svgs.
In order to do this, the `ApplicationDataSource` type now has an `iconSvg` attribute. Once this change propagates to all data sources in `deck` and `deck-kayenta`, a follow-up PR will update the `NavIcon` component to utilize `dataSource.iconSvg` instead of the current `dataSource.icon`, which points to the font awesome icon.

feat(core): Add svg name to dataSource

---

app/scripts/modules/core/src/application/application.model.ts
app/scripts/modules/core/src/application/service/applicationDataSource.ts
app/scripts/modules/core/src/presentation/hooks/useDataSource.hook.ts

Without tapping into the status stream in the hook, we actually can't handle error or loading states.
This change basically just exposes the `loaded`, `loading`, `loadFailure` convenience properties of the `dataSource`. Tapping into the `status$` allows the hook to run whenever the status changes.
Example of how these are leveraged is in https://github.com/spinnaker/deck/pull/8119

feat(core/presentation): Expose status in useDataSource hook

---

app/scripts/modules/core/src/pipeline/config/stages/failOnFailedExpressions/failOnFailedExpressions.directive.html

In the "Evaluate variables" stage, if you uncheck "Fail stage on failed expressions", rather than saving the field `failOnFailedExpressions` to false, it removes it.
So if you then exit the pipeline editor and re-open it, it shows up as checked again.
This PR changes the behavior so that when the checkbox is unchecked, it is set to `false`.
Old behavior:
New behavior:

fix(deck): Evaluate Variables Stage: Update checkbox behavior so 'unchecked' saves correctly

---

app/scripts/modules/core/src/pipeline/config/stages/travis/travisExecutionDetails.controller.ts

Probably this could be handled better... the issue is that Travis build info is set in the controller constructor, so any pipeline with more than one travis stage. It only shows execution details for the stage fetched at load time for all the stages.
Just added a refresh method that is called on each render of the execution details.
https://github.com/spinnaker/spinnaker/issues/5601

fix(travis): Refresh travis build information on each render

---

app/scripts/modules/core/src/pipeline/config/triggers/RunAsUser.tsx
app/scripts/modules/core/src/pipeline/config/triggers/Trigger.tsx
app/scripts/modules/core/src/serviceAccount/ServiceAccountReader.ts

Allows for filtering service accounts to include only those relevant to the specific application.
This is implemented server-side in spinnaker/gate#1130 and spinnaker/fiat#629 however the gate
PR is not blocking as this will just fall back to the current behavior if the new endpoint
has not yet been deployed.

feat(serviceAccounts): supply application when populating run as user dropdown

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestConfig.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManifestRenderers.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/ManualExecutionBakeManifest.tsx
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/bakeManifestStage.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/base64/base64.artifact.ts

Closes https://github.com/spinnaker/spinnaker/issues/5624
* refactor(core): clean up Bake (Manifest) stage 
Before resolving a long-standing regression, let's give the Bake (Manifest) code some TLC. This commit cleans up import statements per convention, abstracts the manifest renderer constants into an enum, refactors stage validation per new Formik conventions, and simplifies components that are unnecessarily class components into functional components.
* fix(core): default and validate Bake (Manifest) produced artifacts 
[This PR](https://github.com/spinnaker/deck/pull/7138) unintentionally removed the functionality that added a default base64 expected artifact to Bake (Manifest) pipelines. Let's re-add that functionality, and add an additional validator to ensure that users catch this …

fix(core): default and validate Bake (Manifest) produced artifacts

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/ManagedWriter.ts
app/scripts/modules/core/src/managed/NoticeCard.module.css
app/scripts/modules/core/src/managed/NoticeCard.tsx
app/scripts/modules/core/src/managed/constraints/ConstraintCard.less
app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx

Today is the day! This is a pretty rough first pass at interactively approving/rejecting manual judgements via the UI 🌈 
I would show you a nice gif of actually doing a judgement, but sadly Netflix isn't running the version of Gate with the appropriate endpoint yet and I didn't want to go through the hassle of running it locally today. In the case of the endpoint failing we show a pretty lame (but hopefully soon to be improved!) error state with an option to go back and try again:
There were some choices I made that are either temporary or require a little additional context, for those not already commented I'll add some PR comments.

feat(core/managed): add support for overriding constraints via Environments

---

app/scripts/modules/core/src/presentation/main.less

This addresses a Netflix customer concern that the width on the pipeline wait stage > wait time form field was too narrow. I took a look and saw the 60px style is used throughout deck, but I don't think it's necessary. I think a placeholder value or tooltips go further to instruct a user on the expected input vs the width of the form field. I wanted to get feedback from folks more familiar with the codebase than me though, so I'm just nudging up the width as a safe first step/conversation starter.
Here's a screen shot of the new width

fix(core): bump up width on numerical form fields

---

app/scripts/modules/core/src/application/ApplicationComponent.tsx

... on a per app basis based on application attributes.
⚠️  KLUDGE ALERT: this is temporary until performance improvements land ⚠️ 
The global default application refresh cycle could be too low for applications with large footprints, that is, applications where the refresh payloads are large enough that `( request time + parse time + transform time )` ends up taking a non-trivial chunk of the interval.
In many cases, for applications with footprint larger than `insert arbitrary threshold here` (aka more than `x` number of `y` resources), most of that refresh/parse/transform time is likely wasted because a user cannot meaningfully make use of all that data.
These cases may be better served by a filtered experience where users need to specify what subset of the data they're actually …

fix(core): Temporarily allow disabling refresh cycle

---

app/scripts/modules/ecs/src/serverGroup/details/serverGroupDetails.html

The server group detail pane currently contains a metrics section with hard-coded, dummy values. Removing this to avoid confusion until real metrics are added (see https://github.com/spinnaker/spinnaker/issues/5605).
screen shot of pane w/o metrics section:

fix(ecs): Remove dummy metrics values from cluster detail pane

---

app/scripts/modules/core/src/managed/ManagedResourceObject.tsx

Turns out that [I was wrong](https://github.com/spinnaker/deck/pull/8115#discussion_r401156580) when I suggested @vigneshm could leave out stack + detail filters when linking to managed resources in #8113. 
The reason this is necessary is because filtering by name may include other stacks or details depending on the name itself — e.g. if have 3 cluster resources:
- `keel`
- `keel-test`
- `keel-test-b`
If I click on the link for `keel`, the substring search query for `keel` will return all three clusters. If I click on `keel-test`, I'll get `keel-test` and `keel-test-b`. Filtering on stack + detail _and/or their absence_ is the only way to get just the single resource that's relevant.

fix(core/managed): add stack + detail filtering on resource links

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactRow.module.css

We recently came to the realization that the `approved` and `pending` states an artifact can have in a particular environment were a bit conceptually overloaded, because they both contained versions that had been skipped over due to later versions becoming available. This meant it was very challenging to explain what `approved` and `pending` meant in the UI because a version could _either_ be in a state of approved-ness / pending-ness, or it could've been skipped and have no chance of ever being deployed.
[We've now split out a totally new state](https://github.com/spinnaker/keel/pull/959) — `skipped` — to help clarify the semantics of the other two states, freeing up `approved` to mean "this version is about to start deploying" and `pending` to mean "this version is actively under …

feat(core/managed): add proper support for skipped, approved artifact states

---

app/scripts/modules/docker/src/pipeline/trigger/DockerTriggerTemplate.tsx

As discussed in the #clouddriver-perf Slack channel, many users enable Clouddriver's `--sort-tags-by-date` flag so that they don't have to sift through potentially thousands of tags in Deck when doing a manual execution. At least a couple of these users were not aware that this input was searchable; this is because the UI always selects by default the first tag in the list (which will not even be the newest if you don't have the flag enabled). Let's remove that default and add placeholder text to clarify this (since the default placeholder text is `Select...`, I added ellipsis to the new text as well 🤷‍♀).

feat(docker): clarify searchability of docker tags on manual execution

---

app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.tsx

Previously, we were rendering components defined inside the render function.  Since they get a new reference each time, the buttons were getting unmounted/remounted.  This also caused the radio buttons to be unfocusable, so keyboard navigation was impossible.
Now, the radiobutton component is defined as a separate component at the top level.
before: (pressing tab)
after: (pressing tab and selecting with spacebar)

fix(core/presentation): Avoid excessive RadioButton remounts by moving the component outside the render function

---

app/scripts/modules/core/src/pipeline/config/stages/managed/ImportDeliveryConfigExecutionDetails.tsx

Tiny changes to break error details on words, not characters, and to change the wording in the error box label.

fix(managed-delivery): Minor cosmetic fixes in import delivery config stage

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/BakeManifestStageForm.tsx

Closes https://github.com/spinnaker/spinnaker/issues/5668
* fix(kubernetes): clear renderer-specific fields on renderer change in bake manifest 
* feat(kubernetes): remove kustomize feature flag

fix(kubernetes): fix outstanding Bake (Manifest) bug and remove Kustomize feature flag

---

app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/presentation/icons/Icon.tsx

Just moving from colors that were hard-coded to the same colors (with the exception of `--color-status-success`) exposed via `@spinanker/styleguide`.

refactor(core): custom -> styleguide colors for icons, artifact status bars

---

app/scripts/modules/core/src/pipeline/config/actions/pipelineConfigActions.module.ts

Pretty self explanatory lol.
Luckily `pinnaker.core.pipeline.config.actions` and `spinnaker.core.pipeline.config.actions` isn't used directly, the common usage is `PIPELINE_CONFIG_ACTIONS` constant.

fix(core/pipelines): typo with PIPELINE_CONFIG_ACTIONS

---

app/scripts/modules/core/src/managed/StatusBubble.less
app/scripts/modules/core/src/managed/StatusBubble.tsx
app/scripts/modules/core/src/managed/StatusCard.less
app/scripts/modules/core/src/managed/StatusCard.tsx

This change introduces two new components for displaying 'status', which in our new design system is a first class concept. We expect we'll be using both of these a lot, so while it's in `core/managed` for experimentation right now I'm actively working toward graduating them into `core/presentation` sooner rather than later (hence the level of polish). 
- `StatusBubble` is an icon with a colored circle behind it which can take on a predefined set of status colors/appearances. This "bubble" is ubiquitous in @gcomstock's designs therefore supports the same size portfolio as `Icon`. There's also a spiffy transition for icons entering/leaving, which helps visually call out changing statuses in lists of bubbles/cards
- `StatusCard` is the successor to our early-stage `NoticeCard`, and will …

feat(core/managed): add StatusBubble, StatusCard components

---

app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts

By using a local `Set` to prevent duplicates (but still returning an `Array`).
We were redundantly adding the same security group into the `securityGroups` array multiple times when it is used by multiple server groups. This is not necessary and results in performing operations redundantly:
https://github.com/spinnaker/deck/blob/35fcebbcdd2c6dea2397a90a48db975293096054/app/scripts/modules/core/src/securityGroup/securityGroupReader.service.ts#L211
...which is not expensive in and of itself, but becomes expensive as the number of `serverGroups` increases as we were pushing duplicate securityGroup objects on every iteration of a `serverGroup`.
We basically had ( `number of security groups` x `number of server groups` ) in the array, which is now reduced to only `number of security groups`.

fix(core): Do not add security group multiple times

---

app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
app/scripts/modules/core/src/managed/ColumnHeader.module.css
app/scripts/modules/core/src/managed/EnvironmentRow.less
app/scripts/modules/core/src/managed/Environments.module.css
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/ObjectRow.module.css
app/scripts/modules/core/src/managed/ObjectRow.tsx

A couple _very_ related changes:
**First,** the overall layout for the two-column Environments view is a mix of some prototype flexbox markup/styles, some ad-hoc 'make it work' layout code from porting over the prototype, and then some layering on top of stuff we did to accommodate a particular feature/component. I'd like to simplify that markup, prepare it to become something more re-usable (i.e. some kind of standard list/detail layout we can use elsewhere), and fix the sizing/scroll overflow wonkiness we've deferred polishing. As part of this first chunk of changes I've:
- Swapped out the flexbox rules which implicitly depended on each other's size in favor of a two-column grid layout, which has the pleasant side effect of filling the available space in the route container
- Tweaked …

feat(core/managed): add scrolling grid layout, detail pane transition

---

app/scripts/modules/core/src/artifact/react/ArtifactAccountSelector.tsx

Adds `valueKey` of `name` so that the `ArtifactAccountSelector` dropdown is filterable by account name.

feat(core): make artifacts account selector searchable by name

---

app/scripts/modules/core/src/pipeline/manualExecution/Triggers.tsx

a pubsub trigger
Retrying a pipeline with a pubsub trigger + any other trigger doesn't work because the pubsub trigger type doesn't implement a `manualExecutionComponent`. Wrote out a larger description of the problem here: https://github.com/spinnaker/spinnaker/issues/5682
This PR "solves" the problem by preventing the retry modal from blowing up, but eventually would love to see the attached issue solved.

fix(pubsub): prevent NPE when retrying a pipeline execution with

---

app/scripts/modules/titus/src/pipeline/stages/runJob/RunJobExecutionDetails.tsx

Originally this was just fixing a missing `key` in a repeater.  But might as well migrate to the `<LabeledValueList>`/`<LabeledValue/>` components while I'm in there.

fix(titus/stages): Migrate runjob execution details to LabeledValueList

---

webpack.config.js

It turns out more threads isn't necessarily better.  Anecdotally, the additional overhead for running more threads can be more costly than the benefits from parallelization.  I saw no consistent improvements (on my 8 core macbook pro 16") moving beyond 2 threads, and build times generally worsened beyond 3 threads.  The new logic disables thread-loader unless at least 4 physical cpus are detected.
It's worth noting that thread-loader is currently configured twice in webpack.config.js (once for typescript and once for javascript).  Each copy was launching the configured number of threads, so we were previously using 2x what is printed to the console.
It's also worth noting that the `fork-ts-checker-webpack-plugin` spawns at least one other thread.  On a 2-cpu system (such as travis or GHA) …

feat(webpack): use max 2 threads for thread-loader

---

app/scripts/modules/core/src/artifact/expectedArtifact.service.spec.ts
app/scripts/modules/core/src/pipeline/config/PipelineRegistry.ts
app/scripts/modules/core/src/pipeline/config/triggers/artifacts/custom/custom.artifact.ts

Instead of separately registering two `custom` artifact types, let's use the existing `merge` functionality. Also updates the wonderful tests that already existed!

fix(artifacts): dedupe custom artifact types

---

app/scripts/modules/core/src/artifact/ArtifactsModeService.ts
app/scripts/modules/core/src/artifact/expectedArtifactMultiSelector.component.ts
app/scripts/modules/core/src/artifact/imageSourceSelector.component.ts
app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/core/src/pipeline/config/stages/findArtifactFromExecution/findArtifactFromExecutionStage.ts
app/scripts/modules/core/src/pipeline/status/ParametersAndArtifacts.tsx
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/kubernetes/src/v2/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceStage.ts
halconfig/settings.js
settings.js

Related to: https://github.com/spinnaker/governance/blob/master/rfc/legacy_artifacts_ui_removal.md 
This change removes `artifacts` and `artifactsRewrite` feature flags in preparation for release 1.20, in which the standard artifacts UI will be enabled by default. Provides a temporary flag that can be enabled in order to revert to the legacy UI, which will be removed in release 1.21.
Corresponding Halyard and Docs changes coming soon!

feat(core): enable standard artifacts UI by default

---

packages/mocks/src/mockTask.ts

Added `SUCCEEDED` status since that should also be included in the enum.

feat(core): Include SUCCEEDED status in ITaskStatus

---

app/scripts/modules/core/src/managed/ManagedResourceStatusIndicator.tsx

we deep-link to slugs in the docs that are dashed, but until now all the enum values for these statuses have been single words. [Now that we have `CURRENTLY_UNRESOLVABLE`](https://github.com/spinnaker/deck/pull/8189) we need to map to the right casing to make the link work.

fix(core/managed): make snake case enum values link properly to dashed URLs

---

app/scripts/modules/core/src/pipeline/service/execution.service.ts

When hydrating an execution, we don't add the stage summaries to it. This results in some of the fields not showing, like stage comments.
This PR should fix the problem.

fix(UI): add stage summaries to hydrated graphs

---

app/scripts/modules/ecs/src/domain/IEcsLoadBalancer.ts
app/scripts/modules/ecs/src/ecs.module.ts
app/scripts/modules/ecs/src/loadBalancer/EcsLoadBalancerClusterContainer.tsx
app/scripts/modules/ecs/src/loadBalancer/TargetGroup.tsx
app/scripts/modules/ecs/src/loadBalancer/details/loadBalancerDetails.tsx
app/scripts/modules/ecs/src/loadBalancer/details/targetGroupDetails.tsx
app/scripts/modules/ecs/src/loadBalancer/listener.tsx
app/scripts/modules/ecs/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/ecs/src/loadBalancer/targetGroup.states.ts

Implements https://github.com/spinnaker/spinnaker/issues/4797
Depends on: https://github.com/spinnaker/clouddriver/pull/4526
Adds basic ECS load balancer and target group views to deck.
* ECS load balancers on */loadBalaners* page
* ECS load balancers detail pane
* ECS target group detail pane
* ECS load balanced server group display (SG pane unchanged, notice center highlight)
* ECS load balanced server group display for service with multiple target groups (SG pane unchanged, notice center highlight)

feat(ecs): Implement load balancer views

---

packages/pluginsdk/package.json
packages/pluginsdk/scaffold/package.json
packages/pluginsdk/scripts/check-plugin.js
packages/pluginsdk/scripts/check-plugin/asserters/assertFileExists.js
packages/pluginsdk/scripts/check-plugin/asserters/assertJavascriptFile.js
packages/pluginsdk/scripts/check-plugin/asserters/assertJsonFile.js
packages/pluginsdk/scripts/check-plugin/linters/index.js
packages/pluginsdk/scripts/check-plugin/linters/lint.eslintrc.js
packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
packages/pluginsdk/scripts/check-plugin/linters/lint.prettierrc.js
packages/pluginsdk/scripts/check-plugin/linters/lint.rollup.config.js
packages/pluginsdk/scripts/check-plugin/linters/lint.tsconfig.json.js
packages/pluginsdk/scripts/check-plugin/util/readWriteJson.js
packages/pluginsdk/scripts/check-plugin/util/restoreFile.js
packages/pluginsdk/tsconfig.json
packages/pluginsdk/yarn.lock

This is a script intended to keep plugin repositories up to date with the latest opinions published in the `@spinnaker/pluginsdk` package.
A plugin author scaffolds a deck plugin, but then we update the opinions (for example, I'll be adding example unit tests to the plugin scaffold).  Whenever the plugin author runs `yarn`, this script will be run.  It will inform the plugin author that there is a newer version of `@spinnaker/pluginsdk` and offer to upgrade the repo.  After the repo is updated, the latest version of this script is run and any missing or changed opinions will be pointed out.  The plugin author then has the opportunity to run the script again using `--fix` to fix anything that can be automated.
```
❯ npx check-plugin --help
Options:
--help              Show help …
```

feat(pluginsdk): Add support for checking if an existing plugin is using the latest opinions.

---

.github/workflows/ci.yml

This is the [same set up we have on all the Java repositories](https://github.com/spinnaker/clouddriver/blob/10cf7883cb30209492ac660b31fd40c3fc0901ae/.github/workflows/build.yml#L15).

chore(ci): don't run CI on forks

---

packages/pluginsdk/package.json
packages/pluginsdk/scaffold/package.json
packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
packages/pluginsdk/scripts/scaffold.js
packages/pluginsdk/tsconfig.json

npm v6.x under the hood uses `npm-packlist` to generate a tarball of the package contents via `npm pack`.  In `npm-packlist` version 1.x, it parses the nested `scaffold/package.json` and processes the `files: ["build/dist"]` entry.  This caused the scaffolding contents to be ignored (because they don't match the `files` list).
This fix changes the scaffold command so it adds the `files: ["build/dist"]` entry to the scaffolded `package.json` in a post-process.
When `npm` updates to `npm-packlist` v2.x (perhaps in npm v7.x?) we can remove this workaround.

Npm packlist fix

---

packages/pluginsdk/package.json
packages/pluginsdk/scaffold/package.json
packages/pluginsdk/scripts/check-plugin/asserters/assertJsonFile.js
packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js

Tweaks the scaffold `postinstall` script a bit so it doesn't exit with a failure code.   
Use lodash `set` to deeply set configuration values

Pluginsdk 0.0.10

---

packages/pluginsdk/pluginconfig/tsconfig.json

This embed the typescript sources into the sourcemap files (index.js.map)

fix(pluginsdk): Fix sourcemaps in typescript config

---

app/scripts/modules/core/src/managed/EnvironmentRow.tsx

itty bitty icon tweak now that Greg has changed the size of the paths for expand/collapse arrows to fill more of their svg canvas.
i would include screenshots, but in an exciting turn of events switching to the `extraSmall` icon size actually look **_identical_** to the way that things looked before the SVG path itself was changed (back when we were using the `medium` size). The paths did switch to rounded ends, but it's not really that visible at that size. Props to Greg for working his designer magic! 🧙‍♂️ 
cc @gcomstock

fix(core/managed): use smaller icon size for expand/collapse arrows

---

app/scripts/modules/core/src/presentation/modal/Modal.module.css

Turns out I made a bit of an oopsie on https://github.com/spinnaker/deck/pull/8237 by not moving the _height_ rules out to the new wrapper element when I moved the width rules. That resulted in the height of modals basically always regressing to min-content on smaller height screens (which I didn't notice on my new ginormous monitor). This does some rejiggering to get things back to the right state, mostly by tweaking the height layout to use the same grid mechanics (though not using `minmax()`). There should be effectively zero changes from the behavior we had before https://github.com/spinnaker/deck/pull/8237.
I'd add screenshots for this, but it's really nuanced and has to do with flexing vertically so really multiple before/after videos would be required which seems like a lot of …

fix(core/presentation): properly handle vertical grow/shrink on Modal

---

app/scripts/modules/core/src/managed/EnvironmentRow.less
app/scripts/modules/core/src/managed/EnvironmentRow.tsx
app/scripts/modules/core/src/managed/ObjectRow.module.css
app/scripts/modules/core/src/managed/ObjectRow.tsx

We're starting to see the use of flexbox on ObjectRow/EnvironmentRow break down a bit as things get more complicated. We just added some new code to show a StatusBubble on both kinds of rows, and the fact that each section is sized differently depending on its content was making it to where the bubbles were looking... not so great when they happened to show up together:
For now I do not have the time nor the mental capacity to try to iron things out in a holistic, long-term viable way. This PR really just band-aids the situation with some changes to the DOM + flex rules to get things to line up a little better. While it does look _better_, it's still not great, as the indent of StatusBubbles on parent/child rows isn't exactly the same as the rows themselves, nor does it make the bubbles …

fix(core/managed): mitigate layout jank on ObjectRow + EnvironmentRow

---

app/scripts/modules/core/src/managed/ManagedResourceObject.tsx

tiny visual regression i noticed this afternoon, a result of some of my DOM structure changes in https://github.com/spinnaker/deck/pull/8246
Before:
After:

fix(core/managed): fix vertical alignment on deploy pills

---

app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.spec.tsx
app/scripts/modules/core/src/presentation/forms/inputs/RadioButtonInput.tsx
app/scripts/modules/core/src/presentation/forms/inputs/SelectInput.spec.tsx
app/scripts/modules/core/src/presentation/forms/inputs/SelectInput.tsx
package.json

Applies the default value using 'onChange' when the current value is undefined, or is not an actual value in the options array
The motivation for this new prop is to keep the radio button/select in a valid state.  I'm working on a form where depending on form state, the list of options might change.  If the previous `value` is no longer valid, I want to be able to easily provide a new (valid) value.
Another option is to manage these defaults externally, via state management.  However, as I was writing code like that, it seemed bespoke and not very re-usable.  
```jsx
<SelectInput value={value} defaultValue={options[0]} options={options} />
```

feat(core/presentation): Add a 'defaultValue' prop to SelectInput and RadioButtonInput to apply a default value

---

packages/mocks/package.json
packages/mocks/src/amazon/index.ts
packages/mocks/src/amazon/mockAmazonBlockDeviceMapping.ts
packages/mocks/src/amazon/mockAmazonLaunchTemplate.ts
packages/mocks/yarn.lock

Introduce base and customizable mock data. This will be used in test fixtures through development of the launch template feature.

feat(mocks): Add Launch Template data mocks

---

packages/pluginsdk/package.json
packages/pluginsdk/yarn.lock

Publishing a new release of pluginsdk with a `@spinnaker/core` bump

chore(pluginsdk): bump to 0.0.11

---

app/scripts/modules/core/src/notification/modal/WhenChecklistInput.tsx

This was somewhat of a perfect storm of small bugs that led to the page locking up in an infinite loop and eventually crashing whenever we showed the edit experience for a custom notification message:
The initial culprit was an extremely common, straightforward bug that I see come up frequently with form inputs (but it can occur with any kind of component) — defining a component function in another component, and then rendering it. The reason that's bad is because React uses a referential equality check (i.e. `oldFunction === newFunction`) when rendering a component to tell whether that component is the same one, or a different one that happened to get rendered into the same spot in the virtual DOM tree. When it sees the reference change, it assumes the component has changed and it needs …

fix(core/notification): stop infinite-looping on custom notification input

---

app/scripts/modules/core/src/managed/EnvironmentRow.less

I was getting pretty annoyed using the expand/collapse toggle on environments because whenever i clicked it just _slightly_ too fast it seemed to select all the text in the object rows below it. Turns out if you turn off `user-select` on the element being clicked, it will also prevent that selection from bubbling out to other elements (TIL).

fix(core/managed): prevent expand/collapse from selecting text

---

app/scripts/modules/core/src/filterModel/FilterCollapse.tsx

Reduce the z-index to `layer-medium` so that the modal backdrop will dim the `FilterCollapse` button. 
Creating a separate PR for this since the layout v1 PR is dependent on a couple react refactors now. 
Fixes this problem:

fix(core): Reduce FilterCollapse z-index

---

app/scripts/modules/core/src/insight/InsightLayout.tsx

`@uirouter/react-hybrid` inserts a component `<react-ui-view-adapter>` between the `UIView` and the component that is being rendered. In certain situations, a nested `UIView` triggers an error:
```
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```
I presume this occurs when the UI Router inserts the adapter. It happens when one UI view is a direct child of another. The fix (unclear why) is to wrap the `UIView` in a div.

fix(core): UIView insertBefore error

---

app/scripts/modules/core/src/presentation/hooks/useData.hook.ts

One nice thing about useData is that the `result` reference is stable and can be used as a dependency for other hooks.  For example, one could transform the data later in a `useMemo`.
```
const { result } = useData(() => fetch(), [], []);
const transformed = useMemo(() => transform(result),  [result]);
```
For example:
https://github.com/spinnaker/deck/blob/cc7001d9739a5fd42c5a0f3b2f83360e904e3abb/app/scripts/modules/core/src/widgets/ApplicationsPickerInput.tsx#L20-L22
However, the `useData` default value is probably *not* stable, because the default is generally passed as a literal to useData and gets re-created each render if it's an empty array or object.  
I considered having the caller memoize the default value before calling useData, but I couldn't think of a case where the default …

fix(core/presentation): Memoize defaultResult in useData.hook.ts

---

app/scripts/modules/core/src/managed/Environments.tsx

I've heard a couple different forms of feedback that seemed to come from a bit of ambiguity around what "Artifacts" means in the sidebar. In your app's delivery manifest you define an `artifacts` list that specifies the artifact you care about (oftentimes just a single image/deb), I'm sort of wondering if the name being the same here for something that's a list of lots of versions causes a little bit of a mismatch.
Thoughts? I'm honestly a bit torn but figured it was worth trying out and considering. Looks like this:
fyi @gcomstock

feat(core/managed): switch 'Artifacts' header to 'Versions'

---

app/scripts/modules/core/src/managed/managed.dataSource.ts

Managed Delivery is officially in beta — let's make Environments available to opt in for anyone who tries it!

feat(core/managed): make Environments tab visible on config screen

---

app/scripts/modules/amazon/src/aws.settings.ts

With the upcoming launch template support, server groups will be able to opt instances into IPv6 and/or IMDSv2. If enabled in `aws.settings`, these options will be available in the server group configuration `Advanced Settings` modal.

feat(aws): Add IPv6 and IMDSv2 to aws settings

---

app/scripts/modules/core/src/insight/InsightLayout.tsx

Improper use of `appIsReady` flag for the master view. The angular version of this component did not have this conditional, and it is causing render errors when loading large apps.

fix(core): Remove conditional for master UI View

---

app/scripts/modules/ecs/src/loadBalancer/loadBalancer.transformer.ts

Addresses part of https://github.com/spinnaker/spinnaker/issues/5800
Specifically: [this part](https://github.com/spinnaker/spinnaker/issues/5800#issuecomment-637008783).
After returning an `IPromise`, load balancer and firewall infa pages now show up. 
* NOTE: still seems to be something off/missing from the top of the search/filter panel?

fix(ecs): return promise from normalizeLoadBalancer

---

app/scripts/modules/ecs/src/instance/details/instanceDetails.html

Currently terminating tasks fails as it tries to use the instance id to terminate the task. As discussed in this [issue](https://github.com/spinnaker/spinnaker/issues/5383), removing the terminate instance button as it doesn't currently work.

fix(ecs): disable terminate instance

---

app/scripts/modules/core/src/presentation/forms/forms.less

Currently, using any of the react-select components within a `<FormikStageConfig>` component results in some unpleasant styles when making a selection:
These overrides restore existing styles that are getting overridden by the styleguide.
**Entering the select box, nothing selected**
_current_
_PR_
**Entering the select box, something already selected**
_current_
_PR_
**Entering something in the select box**
_current_
_PR_

fix(core): override styleguide styles on react-select input

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/core/src/serverGroup/configure/common/wizard/fields/ServerGroupDetailsField.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

AWS and Titus ASGs are case sensitive, but Spinnaker is not. This causes issues when ASGs characters are identical, but casing is different. The fix is to normalize stack and detail fields to lowercase characters to prevent this issue for ASGs created via the UI.

fix(aws/titus): Server group names should be lower case

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/core/src/serverGroup/configure/common/wizard/fields/ServerGroupDetailsField.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

Reverts spinnaker/deck#8332. We would like to take a different approach. Instead of normalizing server groups to be lowercase (which could have some downstream effects) we would like to ensure that the db/caching is also case sensitive.

Revert "fix(aws/titus): Server group names should be lower case"

---

app/scripts/modules/core/src/cluster/allClusters.controller.js

There is a fix to prevent the filter bar flash for on-demand apps. With the upcoming `InsightLayout` changes, this fix is now causing a flash for non-on-demand apps.
The fix initializes the `filtersHidden` property to `false` if `fetchOnDemand = false` and `true` if `fetchOnDemand = true` in an attempt to prevent a flash altogether.

fix(core): Filter flashes on non-on-demand apps

---

app/scripts/modules/core/src/utils/timeFormatters.ts

Upon investigation, the module we use to calculate stage duration has a maximum value that we do not currently impose. It only honors up to 100 million days after epoch start, or 8.64x10^15. 
Fix: Add max value to the validator so a large value does not impact rendering.

fix(core): Validation for max luxon duration

---

packages/pluginsdk/package.json
packages/pluginsdk/yarn.lock

There was a regression in 11.1.0 that causes funky behavior loading some modules (lodash-es?)

pluginsdk: Pin rollup/plugin-commonjs to 11.0.2

---

app/scripts/modules/core/src/help/HelpMenu.tsx

Since [this change](https://github.com/spinnaker/buildtool/pull/48) to spinnaker/buildtool, the OSS release changelog gists have been published with one top-level gist per minor release and individual files for each patch release. Since we can now stably link to each patch release changelog on spinnaker.io, let's point the Help --> Version link there rather than the general Releases page, which just links out ot each individual changelog anyway.

feat(core): link to specific version changelog

---

packages/pluginsdk/package.json
packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js
packages/pluginsdk/scripts/dev-proxy/livereload.js
packages/pluginsdk/scripts/dev-proxy/server.js
packages/pluginsdk/yarn.lock

dev-proxy: a development proxy for doing local development on a Deck Plugin
This proxy allows a Deck Plugin Developer to load their Deck plugin into an existing Spinnaker installation.
Point the proxy to the URL of a live spinnaker installation.
It will serve the deck assets over http://localhost:9000.
It serves a custom copy of `/plugin-manifest.json` which instructs spinnaker to load the plugin assets locally.
It also enables live reloading (whenever the plugin assets change) via a websocket connection between the browser and proxy.
This means there's no need to run local services such as `gate` nor any need to build `deck` locally

feat(pluginsdk): Create a dev-proxy for doing local deck plugin development

---

app/scripts/modules/kubernetes/src/loadBalancer/details/details.html

This should close https://github.com/spinnaker/spinnaker/issues/4271
It will add a list of hostname rules that will look like this:
Reading from an ingress spec that could look like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
(...)
spec:
rules:
- host: service.spinnaker.io
http:
paths:
- backend:
serviceName: myservice
servicePort: 80
path: /
- host: service.namespace.cluster.spinnaker.io
http:
paths:
- backend:
serviceName: myservice
servicePort: 80
path: /
status:
loadBalancer:
ingress:
(...)
```

feat(kubernetes) Add host rules to the ingress information

---

app/scripts/modules/core/src/pipeline/config/stages/checkPreconditions/CheckPreconditionsExecutionDetails.tsx

Checks the status before displaying a `<StageFailureMessage>` in the execution details pane of a Check Preconditions stage. If the status is `SUCCEEDED`, as opposed to `STOPPED` or some other condition, the execution details pane no longer displays a failure warning message.
```json
{
"id": "01EAX3ZRRC5T5XSFJJ8B3F8ERC",
"refId": "2",
"type": "checkPreconditions",
"name": "Check Preconditions - SUCCEED",
"startTime": 1592262648660,
"endTime": 1592262648779,
"status": "SUCCEEDED",
"context": {
"preconditions": [
{
"context": {
"expression": true,
"failureMessage": "This message should NOT appear since the expression is TRUE."
},
"failPipeline": false,
"type": "expression"
}
]
},
"outputs": {},
"tasks": [],
"requisiteStageRefIds": []
}
```

fix(stages/evaluateVariables): Display failures conditionally

---

app/scripts/modules/core/src/application/config/dataSources/applicationDataSourceEditor.component.spec.ts
app/scripts/modules/core/src/application/config/dataSources/applicationDataSourceEditor.component.ts

In application configuration, the cluster option would allow an unauthorized user the ability to enable/disable clusters without waiting for the task to finish. In reality, it should only enable/disable the clusters tab if the task successfully finishes. Even if the task ends up being rejected because the user doesn't have write access, there would still be a window that would allow the user to see the cluster tab under infrastructure. This fix ensures that the task would only show the clusters tab once the task has successfully finished. Otherwise, it will remain its current state. The inverse is also true here which will now not allow an unauthorized user the ability disable the clusters tab momentarily.

fix(core/application): ensure disable cluster tab waits for task to finish

---

app/scripts/modules/core/src/config/settings.ts
app/scripts/modules/google/src/autoscalingPolicy/components/basicSettings/basicSettings.component.html
app/scripts/modules/google/src/gce.module.ts
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.js
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceAutoScalingFieldLayout.tsx
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceScaleInControls.tsx
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/gceScaleInControls.less
settings.js

This is now on prod, so I think it's okay to remove this flag.
I also updated methods, variables, filenames, etc. to use the new terminology and the updated clouddriver API for this feature.
See spinnaker/clouddriver#4705

feat(gce): remove the scale-in control feature flag

---

app/scripts/modules/core/src/application/nav/ApplicationNavigation.spec.tsx
app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
app/scripts/modules/core/src/application/nav/NavItem.spec.tsx
app/scripts/modules/core/src/application/nav/NavItem.tsx
app/scripts/modules/core/src/application/nav/NavRoute.tsx
app/scripts/modules/core/src/application/nav/NavSection.spec.tsx
app/scripts/modules/core/src/application/nav/NavSection.tsx

Convert `NavCategory` to `NavItem` and the `category` prop to `dataSource`. This is less confusing and consistent with the new architecture of the vertical navbar.

fix(core): Improve navigation terminology

---

app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsHeader.less
app/scripts/modules/core/src/managed/EnvironmentsHeader.tsx
app/scripts/modules/core/src/managed/ToggleManagedResourceForApplication.tsx
app/scripts/modules/core/src/managed/managed.dataSource.ts
app/scripts/modules/core/src/presentation/illustrations/illustrationsByName.ts

Adding application level pause/resume functionality in the environments view by introducing
- A new header section that contains some high-level description of the current state along with an actions dropdown.
- A modal for completing the pause/resume action.
Note that the texts used in the header and the modal are accurate but temporary and will be updated to reinforce the idea that pause functionality should be used sparingly.
<details>
<summary>Header in running state</summary>
</details>
<details>
<summary>Header in paused state</summary>
</details>
<details>
<summary>Modal for resuming</summary>
Note: A more detailed list of artifact versions that will be deployed to each environment will be added in a different PR.
</details>
<details>
<summary>Modal for pausing</summary>
</details>

feat(core/managed): Application pause/resume functionality

---

app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/StatusBubbleStack.less
app/scripts/modules/core/src/managed/StatusBubbleStack.tsx

In this PR, I'm adding support to show the following if an artifact matches the following state in any of the environments.
- Manual Judgement Required
- Is Pinned
- Is Vetoed
- ~~Is Deploying~~
This can show a total of 3 states in a row. If there's more than 3, then we show two 2 states and show a count bubble to denote the number of states that are hidden.
Note that the priority order of the statuses is not final yet and I’m looking for opinions. If there are more states that could be shown other than the 4 I listed above, please let me know.
<details>
<summary>Example</summary>
</details>
<details>
<summary>Made-up Example</summary>
</details>

feat(core/managed): Add status bubble in artifact list

---

app/scripts/modules/core/src/application/ApplicationFreshIcon.tsx
app/scripts/modules/core/src/application/nav/AppRefresher.tsx
app/scripts/modules/core/src/application/nav/AppRefresherIcon.tsx
app/scripts/modules/core/src/application/nav/verticalNav.less
app/scripts/modules/core/src/presentation/icons/iconsByName.ts
app/scripts/modules/core/src/presentation/main.less

This will replace `ApplicationRefresher`, `ApplicationIcon` and `Refresher` once the new navigation rolls out. 
The icon will toggle between `ApplicationFreshIcon` (or overridden Icon) and the stale icon. When it clicks it will refresh the page.
Fresh (not overridden):
Stale w/ Tooltip:

feat(core): New App Icon with refresher

---

app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
app/scripts/modules/core/src/presentation/modal/Modal.module.css
app/scripts/modules/core/src/presentation/modal/Modal.tsx
app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.less
app/scripts/modules/core/src/presentation/tables/standardGridTableLayout.tsx

Recently an issue was exposed with how both `Modal` and `StandardGridTableLayout` handle content that overflows their intended width ([temporary hotfix PR](https://github.com/spinnaker/deck/pull/8378)). This PR attempts to protect against content overflow on both components, so that regardless of what's being displayed inside a table or modal overflowing works as one would expect:
1. Unclear to me whether it's always been this way vs. it being a regression from [my recent changes](https://github.com/spinnaker/deck/pull/8237), but as of this moment `Modal` will grow beyond both the viewport width and its own intended max width if something inside the modal gets greedy and forces itself to be a larger width. While the grid layout stuff I added in #8237 generally works, it turns out the …

fix(core/presentation): protect against width overflow on Modal + StandardGridTableLayout

---

app/scripts/modules/google/src/instance/custom/customInstance.filter.js
app/scripts/modules/google/src/instance/custom/customInstanceBuilder.gce.service.js
app/scripts/modules/google/src/instance/gceInstanceType.service.js
app/scripts/modules/google/src/instance/gceInstanceTypeDisks.ts
app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/google/src/serverGroup/configure/wizard/cloneServerGroup.gce.controller.js
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/CustomInstanceConfigurer.tsx
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceBuilder.html
app/scripts/modules/google/src/serverGroup/configure/wizard/customInstance/customInstanceConfigurer.component.ts

* Fix support multi family custom instance types like e2-custom/n2-custom https://github.com/spinnaker/clouddriver/pull/4559
* Add new instance type for n1(64 and 96 cores) + e2 micro/small/medium
**Screenshots before:**
LAUNCH CONFIGURATION menu
**Screenshots after:**
LAUNCH CONFIGURATION menu

feat(gce): add support multi instance family type for custom instances,

---

app/scripts/modules/core/src/pipeline/config/graph/pipelineGraph.less
app/scripts/modules/core/src/pipeline/executions/executions.less

The executions view is different than the other views. In order to support a variable width pipeline graph with a scrolling out container, more strict `max-widths` need to be enforced on the broader parent containers.

fix(core): Executions css causing overflow

---

app/scripts/modules/core/src/deploymentStrategy/strategies/monitored/AdditionalFields.tsx

This protects failure in rendering the Edit Deploy Stage modal. It is an edge case, but if the `deploymentMonitor` is `undefined` then the modal will not open - this could happen if using the API.

fix(core): Protect rendering when deploymentMonitor is null

---

app/scripts/modules/core/src/presentation/main.less

Add padding to counteract custom banners pushing the detail content down. This also aligns the content with the bottom of the filters and main panels.

fix(core): Custom banner pushes details panel off screen

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx

When adding a ALB new listener rule then re-prioritizing the rules, the UI did not render the correct prioritization even though the priority was updated correctly in AWS. The load balancer transformer already sorts by `rule.priority`. This same sort logic was added to the render portion of the component in order to prevent this bug.

fix(amazon): ALB listener rules are not sorted properly

---

app/scripts/modules/core/src/projects/dashboard/dashboard.html
app/scripts/modules/core/src/projects/dashboard/dashboard.less

When adding clusters to the project dashboard, it often ends up overlapping on the application pipelines side as discussed here:  https://github.com/spinnaker/spinnaker/issues/4925
Added a subclass to make the columns on the project dashboard scrollable.

fix(project dashboard) columns not overlapping

---

app/scripts/modules/core/src/cluster/filter/ClusterFilters.tsx
app/scripts/modules/core/src/securityGroup/filter/SecurityGroupFilters.tsx

Filters were being reset from a custom url because they were rendering too many times before the datasource was finished loading. The `useEffect` was updated to prevent this.

fix(core): Filters should not re-render multiples times after loading

---

app/scripts/modules/amazon/src/instance/details/instance.details.controller.js

We have a Spinnaker application where we deploy both in AWS and Kubernetes. When I try to display the details of an AWS instance, I get "Instance not found." in the UI and this error in the console:
```
TypeError: "g is undefined"
_a utils.ts:20
applyHealthCheckInfoToTargetGroups utils.ts:20
applyHealthCheckInfoToTargetGroups utils.ts:19
applyHealthCheckInfoToTargetGroups utils.ts:17
retrieveInstance instance.details.controller.js:68
retrieveInstance instance.details.controller.js:192
Angular 7
Possibly unhandled rejection: {} angular.js:14961:40
```
While investigating, I found out that get the variable `app.loadBalancers.data` contains data coming from both of the providers and led to store `undefined` in `allTargetGroups` [array](https://github.com/spinnaker/deck/blob/master/app/scripts …

fix(amazon): Instance details is not displayed

---

app/scripts/modules/core/src/insight/InsightMenu.spec.tsx
app/scripts/modules/core/src/insight/InsightMenu.tsx
app/scripts/modules/core/src/projects/projects.controller.js
app/scripts/modules/core/src/projects/projects.html
app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
app/scripts/modules/core/src/search/infrastructure/infrastructure.html
test/functional/cypress/integration/core/create_application.js

The motivation for this change is to better surface an action for the user to
take when they are on the search, project, and application pages. The current
UX obscures the next appropriate action behind a drop down menu that visually
blends into the page, making it difficult for users to know what to do next.
The proposed change is to replace the drop down menu with buttons rendered
appropriately for each page. When on the search page, both create project and
application buttons are rendered, with a call to action for create application.
When on project or application pages, only render those buttons. Finally, if a
cache refresh is needed, render this on all pages when appropriate.
At a technical level, this unifies the three dropdowns which currently depend
on 2 separate angular …

feat(core): refactor insight menu from dropdown to buttons

---

app/scripts/modules/core/src/managed/Environments.tsx

Currently the code looks at the `hasManagedResources` flag from the API response to determine if an app is managed, however the app may have a delivery config with just artifacts, which is a valid state, but the page won't render. This PR makes a tiny change such that we look at the sizes of the `resources` and `artifacts` arrays instead of that flag to avoid that problem.

fix(environments): Allow environments view to render when there are managed artifacts and/or resources

---

app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/presentation/main.less

The fixed footer for pipelines is now partially hidden by the new nav, preventing some buttons from being used. This PR reformats the footer so that the buttons are all on the right side of the footer.

fix(core/pipeline): Reformat fixed footer

---

gradle.properties

All the java project required some changes for this to work, so I killed
the autobump job. I forgot there would be two where it could have gone
through without a hitch. Oh well.

chore(gradle): upgrade spinnaker gradle plugin

---

app/scripts/modules/core/src/presentation/details.less
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/projects/project.less

Two css fixes: 
1. The project header being full-width was being overwritten by custom styles. This moves the `width: 100%` to a more specific set of classes to ensure there are no issues.
2. Tweaking the height of the details panel so there are no scrolling issues.

fix(core): CSS for details panel

---

app/scripts/modules/core/src/application/nav/NavItem.tsx
app/scripts/modules/core/src/application/nav/verticalNav.less

This PR renames a class on the vertical navbar. 
This prevents a FOUC from a custom datasource. The custom datasource has the same class and renders its own CSS before it pulls in `verticalNav.less`. The datasource uses this class in many places, so it is more efficient to change the name in one place in @spinnaker/core.

fix(core): Rename nav item class to prevent FOUC

---

app/scripts/modules/appengine/src/serverGroup/configure/wizard/advancedSettings.html

- Fix a typo in the Server Group advanced settings for Appengine.

style(appengine): Fix typo in Server Group settings

---

app/scripts/modules/core/src/projects/ProjectHeader.tsx

this fixes a problem viewing a pipeline execution in the context of a project where the details content width was 30,000px wide

fix(core/projects): fix layout for projects view

---

app/scripts/modules/kubernetes/src/instance/details/details.controller.ts
app/scripts/modules/kubernetes/src/serverGroup/details/details.html
app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html

* fix(kubernetes): Don't overwrite namespace on instance
The namespace is already set on the instance details object; as we're about to remove region from the instance view (in favor of zone, which is the correct field for an instance) leaving this code will cause the namespace to be cleared.
* fix(kubernetes): Use account instead of accountName in details view
Only security groups set accountName; the convention for all others is to only set account. To prepare for removing accountName from these two objects, read account instead.

fix(kubernetes): Don't overwrite namespace on instance

---

app/scripts/modules/core/src/help/help.contents.ts

Discovered that two of the Manual Judgment help texts were accidentally collapsed into one while reviewing [this PR](https://github.com/spinnaker/deck/pull/8368).

fix(core/help): fix Manual Judgment help text

---

app/scripts/modules/amazon/src/domain/IAmazonLoadBalancer.ts
app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/core/src/task/monitor/TaskMonitor.ts

Enable support for listener rules that have conditions of type `http-request-method`. 
These conditions have a different model than `path-pattern` or `host-header` conditions. Prior to this PR, these conditions could only be created in the aws console, and would fail to render when editing an ALB.

feat(amazon/alb): Support for http-request-method rule conditions on ALBs

---

app/scripts/modules/core/src/pipeline/filter/ExecutionFilters.tsx

`ExecutionFilters.tsx` component has a state variable `searchString` to hold the current search/filter term entered by the user, but uses `ExecutionState.filterModel.asFilterModel.sortFilter.filter` to render the search term in the input. This results in a poor experience since `ExecutionState.filterModel.asFilterModel.sortFilter` is updated via debounce.
In this PR, I'm making `searchString` the source of truth for the currently rendered search term in the UI to avoid the above issue.

fix(core/pipeline): Fix dropping of characters while filtering

---

app/scripts/modules/core/src/cluster/filter/FilterSearch.tsx

The cluster filter already filters by responding to key changes and hitting enter refreshes the whole page. Preventing the form submit so that whole page doesn't get refreshed.

fix(core/cluster): Prevent cluster filter from submitting when enter key is pressed

---

app/scripts/modules/kubernetes/src/manifest/manifest.service.ts
app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/DeployStatus.tsx
app/scripts/modules/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/ManifestStatus.tsx

Preparation for: https://github.com/spinnaker/spinnaker/issues/5909
* refactor(kubernetes/pipelines): make ManifestStatus props more specific 
ManifestStatus component does not require the entire stage, only the account name to pass to one of its children; update the contract accordingly.
* refactor(kubernetes/pipelines): make ManifestStatus functional component 
This component does not rely on any React lifecycle hooks, and we are encouraging all new contributions to prefer functional components. The @Overridable annotation only works on class components, and we are not sure if their were ever any custom extensions relying on it, so remove this for now. (Any custom extensions are unlikely to still work as expected anyway after the upcoming refactor in which data fetching is pushed down …

refactor(kubernetes/pipelines): clean up ManifestStatus and DeployStatus components.

---

package.json
yarn.lock

usually I'd let Dependabot handle it, but I'm impatient today.

chore(deps): bump @spinnaker/styleguide from 1.0.20 to 1.0.21

---

app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx

There's been some confusion around how docker registry trigger works when tag is provided. The detailed help content clears up the confusion but since it is hidden beside the label, I'm making it explicit by placing it below the field.

fix(docker/tag): Make help content explicit for tag field by placing it below the field.

---

app/scripts/modules/core/src/managed/ArtifactRow.module.css
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/StatusBubble.less
app/scripts/modules/core/src/managed/StatusBubble.tsx
app/scripts/modules/core/src/managed/StatusCard.less
app/scripts/modules/core/src/managed/StatusCard.tsx
app/scripts/modules/core/src/managed/VersionStateCard.tsx

We've had some mockups in the pipeline for a long while now based on early customer feedback, this PR is the smallest chunk I could bite off of that larger redesign while still delivering something of value.
Most notable changes are:
1) **Showing environment names when you hover** over a version
2) **Using _way_ more obvious hover + selected state colors** and treatments so it's extremely clear what's selected
3) **Switching to a brown color scheme I'm calling 'archived' for versions that are in a `previous` state** (a.k.a 'decommissioned') across both the version list and the status cards in the detail view — this will hopefully resolve a bunch of the visual ambiguity we've been hearing is painful today
Screenshots:
<details>
<summary>New version sidebar states</summary>
**Initial / …

feat(core/managed): new visual iteration for version sidebar, 'decommissioned' cards

---

app/scripts/modules/core/src/managed/EnvironmentBadge.less
app/scripts/modules/core/src/managed/EnvironmentBadge.tsx
app/scripts/modules/core/src/managed/EnvironmentRow.less
app/scripts/modules/core/src/managed/EnvironmentRow.tsx
app/scripts/modules/core/src/managed/icons/star.svg

We've had many discussions about how to visually re-treat the environment badges we currently have to move away from 'production red' — this PR implements the initial attempt we settled on.
Note that I chose to directly use the SVG star symbol vs. adding it via `<Icon/>` — this is because we need it at an extremely small size which doesn't match any of the available icon sizes. After talking with @gcomstock it became clear that this is a slightly different kind of graphic (we've been calling it a 'symbol' vs an icon) which may later get it's own kind of component (e.g. `<Symbol/>`). For now we're trying it out inline and will re-evaulate if we discover further places for this treatment.
Screenshots:

feat(core/managed): new visual treatment for environment badges

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ManagedWriter.ts
app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx

Related to https://github.com/spinnaker/keel/pull/1417 — this change always includes a reference when updating the status of a constraint so updates can be uniquely mapped to an artifact version. Once this is live we can make the reference field non-nullable on the API.

fix(core/managed): supply references when updating constraints

---

app/scripts/modules/kubernetes/src/interfaces/infrastructure.types.ts

Each resource template tries to read this field.
Requires: https://github.com/spinnaker/clouddriver/pull/4791

fix(kubernetes): add nullable createdTime to base resource interface

---

app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html

Closes: https://github.com/spinnaker/spinnaker/issues/5962
Oddly, the `kubernetes-rolling-restart` component was rendering as expected, but each of the remaining elements in the list of actions (Edit and Delete) were not. Self-closing tags are not allowed in Angular templates, so I likely broke this when I added support for rolling restarts.

fix(kubernetes): do not self-close element in angular template

---

app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
app/scripts/modules/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts
app/scripts/modules/google/src/serverGroup/configure/wizard/location/basicSettings.html
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html

As [reported in Slack](https://spinnakerteam.slack.com/archives/CGXLE1BGW/p1597182222006500), several components of the GCE deploy modal disappeared for users upon upgrading from 1.20.x to 1.21.x. It appears that any subsequent siblings of self-closing `react2Angular`-generated elements are no longer rendered, and this seems to be a known issue when [upgrading](https://jquery.com/upgrade-guide/3.5/) from jquery 3.4.x to 3.5.x, which [Deck did](https://github.com/spinnaker/deck/pull/8222) between the 1.20.x and 1.21.x releases.

fix(google): do not self-close react2Angular-created elements

---

app/scripts/modules/google/src/autoscalingPolicy/GceAutoScalingFieldLayout.tsx
app/scripts/modules/google/src/autoscalingPolicy/IGceAutoscalingPolicy.ts
app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/GcePredictiveAutoscaling.tsx
app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.html
app/scripts/modules/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.js
app/scripts/modules/google/src/autoscalingPolicy/gceAutoscalingFieldLayout.less
app/scripts/modules/google/src/autoscalingPolicy/index.ts
app/scripts/modules/google/src/gce.module.ts
app/scripts/modules/google/src/gce.settings.ts
app/scripts/modules/google/src/help/gce.help.ts
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.html
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/autoscalingPolicy.directive.js
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/GceScaleInControls.tsx
app/scripts/modules/google/src/serverGroup/details/autoscalingPolicy/modal/upsertAutoscalingPolicy.modal.html

<details><summary>Enabling predictive autoscaling</summary>
<p>
</p>
</details>
<details><summary>Server group details for enabled autoscaling</summary>
<p>
</p>
</details>
Requires:
- https://github.com/spinnaker/clouddriver/pull/4794 (Will be released with Spinnaker 1.22)
- An `alphaListed` GCE account
- The following added to `settings-local.js`:
```
window.spinnakerSettings.providers.gce.feature.predictiveAutoscaling = true;
```
* feat(google): add feature flag for predictive autoscaling 
* refactor(google): move autoscaling policy interfaces and layout components to autoscalingPolicy directory 
Currently, the only Typescript/React components of the autoscaling policy modal are specific to the scale-in control feature. In the next commit, we will add support for predictive …

feat(google): add predictive autoscaling support

---

app/scripts/modules/kubernetes/src/instance/details/details.controller.ts

* refactor(kubernetes): Flip an if condition
retrieveInstance has a really long if block that would be clearer if we just returned null immediately if the data is missing (rather than have the usual path in a long block). Make that change separately to make the next diff smaller.
* perf(kubernetes): Load manifest and instance details in parallel
When opening an instance tab, we currently wait for the reqeust to
/instances to finish before starting the request to /manifests even though we have the required information for both.
This PR updates the Kubernetes instance provider to send both requests immediately, reducing the amount of time the user needs to wait for the instance tab to load.

perf(kubernetes): Load manifest and instance details in parallel

---

app/scripts/modules/kubernetes/src/securityGroup/details/details.controller.ts
app/scripts/modules/kubernetes/src/serverGroup/details/details.controller.ts

Similar to the change I just made for instances, let's request the details and the manifest at the same time so that we reduce the amount of time the user has to wait.
For server group managers and load balancers, we are not making a request for the details at all, so we don't need to make the same change to those controllers.

perf(kubernetes): Send server group and firewall requests in parallel

---

app/scripts/modules/core/src/pipeline/config/stages/runJob/runJobStage.js

This is supposed to fix this issue:
https://github.com/spinnaker/spinnaker/issues/5461
Is there a reason why the RunJobStage doesn't have the `restartable` property on it?

fix(RunJobStage): Make RunJobStage restartable

---

app/scripts/modules/core/src/instance/details/instanceLinks.component.js

Instance links were not rendering when the cloud providers array was empty. The constraints only checked for `!section.cloudProviders`

fix(core/instance): Instance links should render when no cloud providers

---

app/scripts/modules/kubernetes/src/pipelines/stages/runJob/runJobStage.ts

I already submitted this to fix the problem:
https://github.com/spinnaker/deck/pull/8492
But it didn't
It seems there are multiple files for `runJobStage`, but the one I change in this PR is the correct one. I have tested it and it works perfectly.
Apologies for the confusion
@maggieneterval FYI

fix(RunJobStage): Add restartability to Kubernetes RunJobStage

---

app/scripts/app.ts

Reinstate Oracle module after enabling the Oracle Clouddriver.
See https://github.com/spinnaker/clouddriver/pull/4808#issuecomment-675672693

feat(oracle): Reinstate oracle module

---

app/scripts/modules/core/src/pipeline/config/triggers/artifacts/gitrepo/GitRepoArtifactEditor.tsx

Currently, there are some issues with the `git/repo` artifact because we store `subpath` as metadata, for users that define artifacts with the same URL and branch but different subpath, Orca is not able to match artifacts correctly.
This PR is about move the subpath value of a `git/repo` artifact to be saved in the `location` field.
It will look at `location` field first, then if it is missing will look at `metadata.subPath`

fix(gitRepoArtifact): move subpath value to location field.

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/ManagedResourceHistoryModal.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
app/scripts/modules/core/src/managed/displayNames.ts

Following up #8513, this change switches the way we deal with resource objects to use the [newly added `displayName` field](https://github.com/spinnaker/keel/pull/1456) instead of assuming a resource will have a `moniker` object. That's important for resource plugins/extensions as it doesn't always make sense for a resource to conform to the moniker contract.
I refactored most of this via whack-a-mole-ing the TS compiler errors after making `moniker` optional, so it's possible there's a spot I missed. We'll find out.

feat(core/managed): use displayName for resources in place of moniker

---

app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.ts

This [commit](https://github.com/spinnaker/deck/commit/62e6878756def592f1faad0c5db1b6aa62c3e20e#diff-d55ad7e7e519cd7a0cbad31b2eba3ab1L206) accidentally removed the `type` when submitting the job.

fix(core/securityGroup): Add job type while updating security groups via infrastructure view

---

app/scripts/modules/core/src/application/service/InferredApplicationWarningService.tsx
app/scripts/modules/core/src/config/VersionChecker.tsx
app/scripts/modules/core/src/widgets/notifier/Notifier.tsx
app/scripts/modules/core/src/widgets/notifier/notifier.service.ts

`notifier.service.ts` currently only accepts string inputs to render as messages. There's a request to open application configuration modal for non-configured applications via the notifications message and it can't be done without making `notifier.service.ts` accept a react component as content. This PR includes this change and updates the existing usages of this service in spinnaker.
NOTE that I'm not removing the old prop `body` from `notifier.service.ts` as I'm not sure if it is used in other customized spinnaker implementations.

feat(core/notifier): Make notifier service work with react components

---

app/scripts/modules/amazon/src/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js

For certain accounts, `vpc0` is not a valid VPC but the defaults provided in `AWSProviderSettings.defaults.vpc` points to `vpc0` resulting in no default vpc being selected. When the application has a creation date of earlier than `AWSProviderSettings.classicLaunchLockout`, we end up defaulting to `none` which points to ec2 classic resulting in undesired behavior.
In this PR, I'm attempting to default to the first available vpc for the account if all of the earlier default attempts have failed.

fix(amazon/firewall): Ensure we use a valid default vpc instead of none

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx

Http-request-method conditions have a different modal for values. It is either an empty array or an array of REST methods. Currently, the validator only checks for an empty string within the values array, so this edge case needs to be accounted for.

fix(amazon/alb): Update rule condition validation for edge case

---

app/scripts/modules/cloudfoundry/src/serverGroup/details/sections/EvironmentVariablesSection.tsx

Small fix for enviornment variables within cloudfoundry. The map function was incorrect for the type so this fix ensures they are displayed correctly.

fix(provider/cf): fix env variables section

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/package.json
packages/eslint-plugin/yarn.lock

Newer version of typescript linter is uncovering more errors/warnings in deck. So temporarily disabling them here.

chore(typescript): Upgrade typescript to v4

---

app/scripts/modules/core/src/managed/StatusBubbleStack.less
app/scripts/modules/core/src/managed/StatusBubbleStack.tsx

I noticed that when certain status bubbles stack in Environments, they move backward/forward in the z-index stack independently of their other status bubbles. Turns out there's a `transform` CSS rule on the ones that move forward which is letting them bust out of their container's stacking context and into their own:
This change adds a no-op `transform: translate(0px, 0px)` to force the entire StatusBubbleStack component onto its own stacking context, so that when elements create their own there is no risk of moving out of the container in the process:

fix(core/managed): give StatusBubbleStack its own z-index context

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js

Moving assignment of launch template userData in a cloned serverGroup to the backend.

fix(amazon/serverGroup): Do not clone launch template userData

---

app/scripts/modules/amazon/package.json
app/scripts/modules/appengine/package.json
app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/titus/package.json

03367a08eacb947314e13e07ee9dcbd081db2f51 fix(amazon/serverGroup): Do not clone launch template userData (#8562)
fa8fa7f7449a46f9e9243012ed61ec77f4203eb0 fix(aws/serverGroup): Optimize cloning logic (#8560)
469a2d0169752cb8801dd742e3de2b744b346ca1 fix(amazon/alb): Update rule condition validation for edge case (#8544)
1a20a4a4ec7d9c6bf291366dbab59752f270a66f fix(appengine): fix rendering of StageArtifactSelector when artifacts are created (#8516)
680906fe30ccd083d5c67359179b63a262f28602 fix(provider/cf): fix env variables section (#8549)
040b0717b7fb7f18f078d1aa61ec6348c9ecf53d feat(provider/cf): add bake cf manifest stage (#8529)
25e1c5f55894fccd8510ab987c21683310db3cfc fix(aws): Get imageId and imageName from server group info (#8548)
08419c1dff7768aa0a7c26009622cce80f0cf6b8 …

chore(package): amazon@0.0.265 appengine@0.0.16 cloudfoundry@0.0.98 core@0.0.506 ecs@0.0.262 titus@0.0.142

---

app/scripts/modules/amazon/src/aws.settings.ts
app/scripts/modules/amazon/src/deploymentStrategy/AdditionalFields.tsx
app/scripts/modules/amazon/src/deploymentStrategy/rollingPush.strategy.ts
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
settings.js

- specifies `setLaunchTemplate` when rolling push strategy is selected by user
- adds a settings to conditionally use `launch templates` in help text depending on whether or not launch templates or launch configurations are activated.

fix(amazon/serverGroup): Enable launch templates for rolling push

---

app/scripts/modules/amazon/src/pipeline/stages/bake/bakeStage.html

The `baseLabel` field was hidden from Rosco-enabled bake stages in #2727 but is valid as Rosco does support the `baseLabel` concept (and it can even be added/modified in the stage JSON).
This will be required for Netflix internal adoption of Rosco. (Internal JIRA SPIN-5625)

fix(aws): expose baseLabel to Rosco-powered bake stages

---

app/scripts/modules/amazon/src/domain/IAmazonFunction.ts
app/scripts/modules/amazon/src/domain/IAmazonFunctionSourceData.ts
app/scripts/modules/amazon/src/function/configure/FunctionEnvironmentVariables.tsx
app/scripts/modules/amazon/src/function/function.transformer.ts

KMS Keys used to encrypt environment variables are not displayed in the function form on edit.
Function form expects key `KMSKeyArn` while function cache is providing `kmskeyArn`
_Fix_: Change form to consume the correct cache key `kmskeyArn`

fix(functions): change KMSKeyArn to match function cache data model

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

1e6da6357891803443043c22bfafb5b18cf8dc33 fix(functions): change KMSKeyArn to match function cache data model (#8566)
efee5f229206efad189e57cc9adf3303160c6d9a fix(aws): expose baseLabel to Rosco-powered bake stages (#8559)
547780c92df0f29ee3f766c281d07634ee003f55 fix(amazon/serverGroup): Enable launch templates for rolling push (#8563)
09439726a3abfb1d8f4843d654b8253f90213a8a chore(core): remove CSS module code + build/test scaffolding (#8567)

chore(package): amazon@0.0.266 core@0.0.507

---

app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFileArtifactList.spec.tsx

This was causing 1626 tests to be skipped since [this PR](https://github.com/spinnaker/deck/pull/8516) was merged (but not fail, which is why CI didn't catch it.)

fix(appengine): remove extraneous "f" from assertion

---

app/scripts/modules/core/src/help/help.contents.ts

A number of hint messages in AWS CodeBuild stage contain incorrect grammar 
Example: `"(Optional) Source of the build. It will be overrided..."`
Fixes spinnaker/spinnaker#5973

refactor(hint): Change incorrect grammar for hint

---

app/scripts/modules/core/src/pipeline/config/stages/bakeManifest/kustomize/BakeKustomizeConfigForm.tsx

I'm exploring what it would look like to add additional artifact sources
for Kustomize bakes to an existing extension project. Rather than build
a plugin or fork Deck, I'd rather do this in an existing extension
project so I can tweak things in Rosco at the same time as I'm making
changes to Deck!

feat(core): add overridable decorator to BakeKustomizeConfigForm

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.less
app/scripts/modules/core/src/managed/ArtifactDetail.tsx

Quick, low-effort follow up to the work recently done on keel to expose git + build metadata for artifact versions. This only adds data about git, because I need to do a little more work on the build data to tie it together with Netflix's internal build UI. I'll be following this up with more thorough/higher effort work around getting a visually rich treatment done for the version sidebar on the left.
I settled on a way of representing "Author" that is consistent with the mockups (having it's own line item), but I also tried out listing it as part of the commit like we do in our internal builds UI. I'm not sure I love that option, but figured I'd show it:
**Current PR (author on its own line):**
**Alternative (author consolidated into commit):**
fyi @gcomstock

feat(core/managed): add git metadata to version details pane

---

app/scripts/modules/appengine/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/kubernetes/package.json
app/scripts/modules/titus/package.json

6d0bfc6ad63e5fe548fab96a8e2593aedaaad8d3 fix(appengine): remove extraneous "f" from assertion (#8571)
edc190cae0ee468ac31701547a0f63f4e5eb5706 feat(core/managed): add git metadata to version details pane (#8576)
439617d2bed5a215a007d8660a19ea3ad02a6d54 feat(core): add overridable decorator to BakeKustomizeConfigForm (#8575)
57771e64f3e6e6ce37300235e9721844cd0eb25b refactor(hint): Change incorrect grammar for hint (#8568)
249aa8e0a16ae3fad7421dec654901f278c4cd4e fix(ecs): set container name to empty when using container inputs #8527 (#8527)
02085ce1ced2ac8bba846bb853545ec04b293b61 fix(kubernetes/serverGroup): use the actual server group manager's kind in name (#8570)
30da1a5b82f04d30e86ba0db5ac0c8d38e88c892 fix(titus/instance): Construct discovery health info in controller (#8572)
PR …

chore(package): appengine@0.0.17 core@0.0.508 ecs@0.0.263 kubernetes@0.0.49 titus@0.0.143

---

app/scripts/modules/core/src/managed/ArtifactRow.less
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/StatusBubbleStack.tsx

Now that we've got git metadata, let's show it off at a glance in the list of versions! We'll now be able to show commit messages, branches, pull requests, and authors without even a single click. Screenshots:
Only thing that's a bit gross is the experience of _not_ having git metadata for a version — it's a bit of a step down in layout/UX right now. I feel strongly we should optimize for making the git metadata case great, so I'm shipping this now and will polish the other case next. I've swapped out the relatively meaningless commit sha we were lifting from versions to instead use the `displayName`. Here's what it looks like:
cc @gcomstock

feat(core/managed): surface git metadata on version list

---

app/scripts/modules/core/src/managed/EnvironmentsHeader.tsx

The masthead/summary thing at the top of the environments overview is a little bloated right now in terms of padding and illustration size, I'm just quickly tightening it up to match the mocks (including tweaks to the drop shadow + text weight) while I'm already in there working on #8600.
**Before**
**After**
cc @gcomstock

feat(core/managed): tighten up layout on environments header

---

app/scripts/modules/core/src/presentation/hooks/index.ts
app/scripts/modules/core/src/presentation/hooks/useInterval.hook.spec.tsx
app/scripts/modules/core/src/presentation/hooks/useInterval.hook.ts

I have a PR for Managed Delivery coming up in a moment that needed to run some callback code on an interval, but shouldn't be tied to any of our usual stuff for polling that tries to be clever about page visibility and online/offline states (`SchedulerFactory`, etc.). `useInterval` is a pretty commonly written custom hook so I didn't try to reinvent the wheel, it's pretty rudimentary. Some unit tests to go along with it as well.

feat(core/presentation): add useInterval hook

---

app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/ColumnHeader.less

We've had some code for a while that will look for `manual-judgement` constraints in a `PENDING` status and throw them into status bubbles on the version sidebar. This change expands that logic in two ways:
1. We'll now surface _any_ constraint types, not just `manual-judgement`
2. We'll now show constraints with a `FAIL` or `OVERRIDE_FAIL` status using an error-colored bubble
As a bonus, I also threw in a one-liner to fix the z-index issue that made for an awkward scrolling experience (before and after below)
**Failed & rejected constraints**
**Scrolling (before and after)**
cc @gcomstock

feat(core/managed): show failed, pending bubbles for any constraint type

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
app/scripts/modules/core/src/managed/StatusCard.tsx
app/scripts/modules/core/src/managed/VersionStateCard.tsx
app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx

Couple of tightly related updates:
- We've been playing around with making time formatting less noisy and easier to scan. Today cards for constraints and deployment states include _a lot_ of text describing times, which are useful if you're very interested in the timing of that specific thing but tough to scan and process at a glance. What we're trying out first is a new relative timestamp which looks a lot like social media platforms (Twitter, Instagram, etc.) — things like `25s`, `1hr`, `3d`. When it gets beyond a month we switch to `Jan 28`, and when it moves into a different year we add `Jan 28, 2019`. The 'full' timestamp that is traditionally used across Spinnaker is available on hover, and in most places you can click on the abbreviated timestamp to copy the full one to your …

feat(core/managed): switch to abbreviated timestamp format, add version timestamps

---

app/scripts/modules/appengine/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/titus/package.json

d36922b4843945f694a659c156ce511935ae5ea3 feat(provider/appengine): add deploy global configuration stage (#8599)
34bc7e9f250e922a352a90c1b2ff417aff70ffb8 feat(core/managed): switch to abbreviated timestamp format, add version timestamps (#8610)
012b004842c53cac4fe427ba1d4ae01026c25132 feat(core/managed): show failed, pending bubbles for any constraint type (#8611)
7604b3d4bf7fb3ee795ea7720eb34b722f3a0f67 feat(webhooks): document stausJsonPath is now optional (#8608)
0463ecb5c4f2146635378746bb49c3c9551a595d feat(core/presentation): add useInterval hook (#8609)
748da07923941dc1ccdcbbcfcab840ddea805b0c feat(ecs): Enable embedded artifacts for Deploy stage (#8603)
61cf058f04ce81b33037eff89cb417669dd531fc feat(ecs): add Amazon ECS Cypress tests
619ad9c1dd1cae3858ad07eb8b2b87461f0ca09e (fix): …

chore(package): appengine@0.0.19 core@0.0.514 ecs@0.0.265 titus@0.0.145

---

app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

2c4a272f65a52ff35ae45a72a3618b682debb713 fix(cf): naming typo in EnvironmentVariables (#8613)
d38e7c54e8aed27a52c1282ed55128bd445f859d fix(Oracle): Fixed Oracle object storage selection (#8588)
7400d6fcc94e0dc1234122e1837ab96571c113cd fix(titus): Do not check for autoscaling feature flag, always enable autoscaling (#8615)

chore(package): cloudfoundry@0.0.100 core@0.0.515 titus@0.0.146

---

app/scripts/modules/core/src/managed/StatusBubble.tsx
app/scripts/modules/core/src/managed/StatusCard.tsx

Cleaning up a couple one-line messes I made with some previous PRs:
- There's a 1px border on the 'inactive' status bubble now, which was making it 2px bigger in diameter than other bubbles and causing some layout jank when switching between versions. Removed a pixel of padding to compensate
- When relative timestamps grow to three characters (e.g. `21d`) they're busting out of the minimum width of the timestamp column on status cards, which leads to text misalignment. I explicitly chose to be ok with that for timestamps that cross into the longer format (e.g. `Jan 28`) for now, but I'm bumping the minimum width so that any abbreviated timestamps retain the standard column size
cc @gcomstock

fix(core/managed): fixup some details from new layout

---

app/scripts/modules/core/src/pipeline/config/actions/PipelineConfigActions.tsx
app/scripts/modules/core/src/pipeline/config/actions/history/ShowPipelineHistoryModal.tsx
app/scripts/modules/core/src/pipeline/config/actions/pipelineConfigActions.module.ts
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.html
app/scripts/modules/core/src/pipeline/config/pipelineConfigurer.js

Looks like this for a freshly created pipeline:
And any edits show up as a diff:
But this is far more important for pipelines created via API.  Previously, the first edit _to a pipeline which was initially created via API_ would not show up in pipeline diff UI.

fix(core/pipeline): Always enable "show revision history" in edit pipeline dialog

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx

Teeny tiny sorting tweak: let's sort resources by their `kind`, and then their `displayName` within that. This means that resources of the same kind will be grouped together, and within each group they'll be sorted alphabetically.
(cc @gcomstock)

feat(core/managed): apply consistent sorting to resources

---

app/scripts/modules/core/src/managed/ArtifactDetail.less
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactRow.less
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/ColumnHeader.less
app/scripts/modules/core/src/managed/Environments.less
app/scripts/modules/core/src/managed/Environments.tsx

Boy was this some "fun". Couple changes:
- Add some pretty 🙄 logic for scrolling to the currently selected version in the sidebar. This is especially helpful when clicking on a link to a version that's not in the most recent ~5-10, or in similar situations like clicking on the new "another version is pinned" warning to jump you to a different version. **I made an explicit decision to go with the lowest-effort approach here because I expect this code to change very quickly and didn't want to invest in optimizations yet**. I have expectations that we'll move to paging + virtualization in the foreseeable future, and at that point leaning on the virtualization library for this will probably make sense
- As part of doing the first thing, I tripped over a thing I've been putting off forever: …

feat(core/managed): scroll to selected version in sidebar, update scroll containers

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/StatusBubble.less
app/scripts/modules/core/src/managed/StatusBubble.tsx
app/scripts/modules/core/src/managed/StatusCard.less
app/scripts/modules/core/src/managed/StatusCard.tsx
app/scripts/modules/core/src/managed/VersionStateCard.tsx
app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx
app/scripts/modules/core/src/managed/constraints/constraintRegistry.tsx

When a version becomes `skipped` in an environment, constraints are no longer evaluated and version is mostly forgotten, never to be heard from again. The exception would be if you manipulate the normal flow of versions via pinning/marking as bad, which would forcefully switch their state to something else.
Despite this relative irrelevance, constraints on skipped versions continue to appear very meaningful and important because they don't actually change state in any way. [We've discussed adding a `SKIPPED` status on the backend](https://github.com/spinnaker/keel/issues/1267), but there are some pretty big, pretty urgent fish to fry in keel that should get attention first. This change makes a low-effort attempt to patch over the lack of a `SKIPPED` status by checking for the `skipped` …

feat(core/managed): put constraints in a 'skipped' state on skipped versions

---

app/scripts/modules/core/src/managed/ManagedReader.ts

As part of trying to do some short-term tweaks to improve Environments performance, this change caps the maximum number of artifact versions we fetch to 30. Above 30 I begin to see increased variability in latency that I'm not super comfortable with (i.e. getting >3s latency on a percentage of calls).

feat(core/managed): limit artifact versions to 30

---

app/scripts/modules/amazon/src/image/image.reader.ts
app/scripts/modules/azure/src/image/image.reader.js
app/scripts/modules/cloudfoundry/src/image/image.reader.cf.ts
app/scripts/modules/core/src/api/ApiService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts
app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.ts
app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
app/scripts/modules/core/src/pipeline/service/execution.service.ts
app/scripts/modules/core/src/plugins/plugin.registry.ts
app/scripts/modules/core/src/slack/SlackReader.spec.ts
app/scripts/modules/core/src/slack/SlackReader.ts
app/scripts/modules/dcos/image/image.reader.js
app/scripts/modules/docker/src/image/DockerImageReader.ts
app/scripts/modules/google/src/image/image.reader.ts
app/scripts/modules/oracle/src/image/image.reader.js
app/scripts/modules/tencentcloud/src/image/image.reader.ts

Reverting [the PR](https://github.com/spinnaker/deck/pull/8586).

Revert "fix(appname): encodeURIComponent for app name (#8586)"

---

app/scripts/modules/amazon/src/image/image.reader.ts
app/scripts/modules/azure/src/image/image.reader.js
app/scripts/modules/cloudfoundry/src/image/image.reader.cf.ts
app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.ts
app/scripts/modules/core/src/pipeline/config/stages/gremlin/GremlinStageConfig.tsx
app/scripts/modules/core/src/plugins/plugin.registry.ts
app/scripts/modules/core/src/slack/SlackReader.spec.ts
app/scripts/modules/core/src/slack/SlackReader.ts
app/scripts/modules/dcos/image/image.reader.js
app/scripts/modules/docker/src/image/DockerImageReader.ts
app/scripts/modules/google/src/image/image.reader.ts
app/scripts/modules/oracle/src/image/image.reader.js
app/scripts/modules/tencentcloud/src/image/image.reader.ts

Applies the auto-fixes for new `api-no-slashes` eslint rule from #8629
Duplicates work originally done in #8586
via:
```eslint --fix```

chore(eslint): eslint --fix api-no-slashes

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/eslint-plugin.js
packages/eslint-plugin/rules/api-no-slashes.js
packages/eslint-plugin/test/api-no-slashes.spec.js
packages/eslint-plugin/yarn.lock

Pushing this out as an eslint rule to give plugin authors a chance to fix their code before we flip the new `API` encoding on.
This is first pass at this rule and it doesn't detect literals passed in as variables. Also it probably wont pass CI, heh.  I'm going to run this on the OSS repo and see what happens.

feat(eslint-plugin): Add a new rule api-no-slashes that forbids using string literals with slashes to API.one() 

---

app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx
app/scripts/modules/core/src/application/nav/NavItem.spec.tsx
app/scripts/modules/core/src/application/nav/NavItem.tsx
app/scripts/modules/core/src/application/nav/NavRoute.tsx

Related to [issue #6009](https://github.com/spinnaker/spinnaker/issues/6009)
Chrome's drag-n-drop for links only works when there is a `span` directly under the anchor tag. This PR refactors `NavItem` so drag-n-drop works in the navigation.

Drag n drop nav

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js

Supporting the edge case where `networkInterfaces` are undefined or empty. (And a lot of prettier changes)

fix(amazon/serverGroup): Additional null safety for networkInterfaces

---

app/scripts/modules/core/src/application/service/ApplicationDataSourceRegistry.ts

We've gotten some feedback that when Environments is turned on, having it sorted higher than pipelines is useful because typically that's the more common landing point for those users.
(fyi @gcomstock)

feat(core/application): sort Environments first for users with it enabled

---

app/scripts/modules/core/src/config/settings.ts

setting defaults for `defaultManifest` name and `manifestBasePath` for managed delivery in the code

feat(keel): set defaults for managed delivery config

---

app/scripts/modules/core/src/application/application.state.provider.ts
app/scripts/modules/core/src/application/applications.state.provider.ts
app/scripts/modules/core/src/application/modal/createApplication.modal.controller.js
app/scripts/modules/core/src/application/search/ApplicationsTable.tsx
app/scripts/modules/core/src/application/service/ApplicationDataSourceRegistry.ts
app/scripts/modules/core/src/insight/InsightMenu.tsx
app/scripts/modules/core/src/navigation/UrlBuilder.ts
app/scripts/modules/core/src/pagerDuty/Pager.tsx
app/scripts/modules/core/src/projects/ProjectHeader.tsx
app/scripts/modules/core/src/projects/projects.states.ts
app/scripts/modules/core/src/search/infrastructure/infrastructure.controller.js
app/scripts/modules/core/src/serverGroup/serverGroup.states.ts

When users migrate to Managed Delivery, we turn on the Environments route for them. Our internal customers have given us feedback that once they migrate it's much more useful to route directly to Environments when hitting `/application/{application}` vs. the standard default (clusters). As a result @gcomstock and I are looking to try out changing the default route _only for apps with Environments enabled_ — any other apps ought to continue to behave the way they already do.
Based on my limited knowledge of UI Router I've taken a stab at doing this, PLEASE give any feedback you may have as I'm more than happy to take a different approach — my primary concern is just getting the end result this PR achieves.
Today we use the static `addRewriteRule` method to redirect to `/clusters`, but now …

feat(core): make Environments the default route if enabled

---

Dockerfile.compile

The Spinnaker gradle plugin is compiled against Java 11, so we can't use Java 8 anymore. This uses the same OS to compile as the other Spinnaker projects.

chore(java11): use Java 11 to run Gradle

---

Dockerfile.compile

The move to `alpine` caused build failures when attempting to use the
`node` binary provided by the `nebula.node` Gradle plugin. The binary
was built assuming the presence of `glibc` while Alpine is based on
`musl`, so the build would always fail.
Moving to openjdk:11-slim appears to get us around these build issues,
we'll see in the final build in gcloud if that's correct!

chore(build): change Dockerfile.compile base to openjdk:11-slim

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx

The commit message in the version details pane currently doesn't respect newlines/carriage returns in the message, so it all gets garbled together in a big wrapping line. This just sets the right combination of magical incantations to properly handle those breaks while still wrapping when a single line overflows.

fix(core/managed): respect line breaks in commit messages

---

packages/eslint-plugin/rules/api-no-slashes.js
packages/eslint-plugin/test/api-no-slashes.spec.js
packages/eslint-plugin/utils/utils.js

Simplified the detection logic for slashes.
Now detects slashes in the following new cases:
some arg is template string or string concatenation with a slash
```
var prefix = 'proxies/foo/v1';
API.one(`${prefix}/endpoint`);
API.one(prefix + "/endpoint"`);
```
some arg is reference to a template string or concatenated string with a slash
```
var prefix = 'proxies/foo/v1';
var url = prefix + "/endpoint";
var url = `${prefix}/endpoint`;
API.one(url);
```

fix(eslint-plugin): Cast a wider net in api-no-slashes.js

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactDetailHeader.less
app/scripts/modules/core/src/managed/ArtifactDetailHeader.tsx
app/scripts/modules/core/src/managed/Environments.tsx

We have a pretty nice new way of showing artifact reference names inside version pills, which we've added in both the sidebar and the environments overview. Recently it was noticed that the header for the version details pane still uses the _name_ of the artifact, which isn't unique and can cause confusion (e.g. you could have the same artifact name configured to pull from PR builds and master builds). This change switches to using the reference, and modifies the visual treatment to look the exact same as the other version pills (reference if there are > 1 artifacts and you need them, no reference if you only have 1 artifact).
Before:
After:
fyi @gcomstock

fix(core/managed): surface artifact reference on details pane

---

halconfig/settings.js

fix(halyard): settings.js doesn't have Oracle default settings 
This settings.js is being used as template by halyard and gets hydrated with default settings. Without these settings, oracle default settings were not getting populated, causing at least one know failure while creating OCI load balancer template.

fix(halyard): Bugfix 6112: settings.js doesn't have Oracle default settings

---

app/scripts/modules/kubernetes/src/validation/applicationName.validator.spec.ts
app/scripts/modules/kubernetes/src/validation/applicationName.validator.ts

Related to: https://github.com/spinnaker/spinnaker/issues/6082
* test(kubernetes): add test for KubernetesApplicationNameValidator.validate 
Demonstrates existence of unnecessary warning for dash-containing application names, which are now always valid since the removal of the legacy (V1) Kubernetes provider.
* fix(kubernetes): remove unneeded application validation warning

 fix(kubernetes): remove unneeded application validation warning 

---

app/scripts/modules/core/src/region/RegionSelectInput.tsx
app/scripts/modules/oracle/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/oracle/src/oracle.settings.ts
halconfig/settings.js

fix(deck): settings.js doesn't have Oracle default settings
Since the Halyard is planned to sunset, as suggested by @maggieneterval we are moving the config defaults into the microservices themselves rather than have Halyard supply them.

fix(deck): Bugfix 6112: provide default settings for oracle provider in deck microservice to remove Halyard dependency.

---

app/scripts/modules/amazon/package.json
app/scripts/modules/appengine/package.json
app/scripts/modules/azure/package.json
app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/google/package.json
app/scripts/modules/huaweicloud/package.json
app/scripts/modules/kubernetes/package.json
app/scripts/modules/oracle/package.json
app/scripts/modules/tencentcloud/package.json
app/scripts/modules/titus/package.json

Running scripts from `node_modules/.bin/foo` is more idiomatic than `node_modules/foo/path/to/script`

chore(package): use node_modules/.bin/* in module scripts, add 'build' script (the old 'lib' script)

---

.github/workflows/approve_package_bumps.yml

The previous action `actions/github` [is deprecated](https://github.com/actions/github) and stopped working

fix(githubactions): Migrate approve_package_bumps to actions/github-scripts action

---

.github/workflows/approve_package_bumps.yml

Switch from 'ready to merge' to 'ready to rebase' to retain the original commit message with changelog

fix(githubactions): switch approve_package_bumps to rebase

---

app/scripts/modules/amazon/src/pipeline/stages/bake/awsBakeStage.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/azure/src/pipeline/stages/bake/azureBakeStage.js
app/scripts/modules/azure/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/azure/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/core/src/pipeline/pipeline.dataSource.js
app/scripts/modules/dcos/pipeline/stages/runJob/runJobStage.js
app/scripts/modules/dcos/serverGroup/configure/CommandBuilder.js
app/scripts/modules/docker/src/pipeline/stages/bake/dockerBakeStage.js
app/scripts/modules/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/pipeline/stages/bake/gceBakeStage.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/google/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/oracle/src/pipeline/stages/bake/ociBakeStage.js
app/scripts/modules/oracle/src/serverGroup/configure/serverGroupConfiguration.service.js
app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts

angularjs's `$q.all()` supports passing in objects with promises as properties, such as:
```
$q.all({
foo: fetch('/foo'),
bar: fetch('/bar'),
});
```
But no feature exists in native promises.  This PR migrates all uses of `$q.all({})` to array style.

When using $q.all(), pass arrays of promises, not an object

---

app/scripts/modules/show_changelog.sh

fix 1) picks one version when multiple commits have package bump (startsha: earliest, endsha: latest)
fix 2) fix grep wildcards (0.0.3 also matches 0.0.330)
In a220af588e194762757be534cce2d7ae9dc508d5 a package bump was reverted due to github actions automation failures.
After re-applying the package bumps, the changelog generator was broken because there were two commit shas that matched each package bump's version number.
This fix just picks the earliest commit for the startsha and the latest commit for the endsha when computing the change log.

fix(packages): fix show_changelog.sh to work when a package bump is reverted

---

app/scripts/modules/core/src/cluster/filter/ClusterFilters.tsx
app/scripts/modules/core/src/filterModel/dependentFilter/DependentFilterService.spec.ts
app/scripts/modules/core/src/filterModel/dependentFilter/DependentFilterService.ts

- Filter values like `detail`, `stack` are [alphabetically sorted](https://github.com/spinnaker/deck/blob/95e43d430b434157e00f7f462768ecae4bde5173/app/scripts/modules/core/src/cluster/filter/ClusterFilters.tsx#L51), so making the other ones alphabetically sorted as well in this PR. 
- Fixed the annoying react warning about missing keys in `ClusterFilters`

feat(core/clusterFilter): Sort cluster filter values alphabetically

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/titus/package.json

deab22f34fe0cd82fc797a553732a148b72405b8 refactor(aws/titus): Reactify instance insights (#8698)
ade00f79934e011f6a4c5afe3897e1dc19bb340c fix(core): Remove less override after react refactor (#8695)
deab22f34fe0cd82fc797a553732a148b72405b8 refactor(aws/titus): Reactify instance insights (#8698)
62b81bf027ea6fc6c3bb250abe79f2ec64004d71 fix(core/clusterFilter): Use filterModel object to retrieve filter values (#8693)
4a4f47218b21e79fca92217999e89e5f2a185a9c fix(core/cronTrigger): Fix regex for weekly cron triggers (#8690)
10b17b965cd2611b98c0bd069eed8218128bc867 Rename networking module to ECS Networking React
5283f9f926af94d4cc88d7f2be09e674a45f10e1 feat(ecs): migrate networking server group wizard to react
deab22f34fe0cd82fc797a553732a148b72405b8 refactor(aws/titus): Reactify instance …

chore(package): amazon@0.0.277 core@0.0.525 ecs@0.0.270 titus@0.0.152

---

app/scripts/modules/amazon/src/function/details/FunctionActions.tsx
app/scripts/modules/core/src/pagerDuty/Pager.tsx
app/scripts/modules/core/src/pipeline/create/CreatePipelineModal.tsx

React 17 upgrade [requires removing](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) `componentWillUpdate`, `componentWillMount` and `componentWillReceiveProps` lifecycle methods. In this PR, I'm removing `componentWillUpdate`, `componentWillMount` methods from `deck`.
`componentWillReceiveProps` is used in around 70 different files and requires a broader migration effort.

refactor(core): Remove componentWillUpdate and componentWillMount methods

---

app/scripts/modules/amazon/src/securityGroup/clone/cloneSecurityGroup.controller.js

Following what we already do in [`CreateSecurityGroupCtrl`](https://github.com/spinnaker/deck/blob/35fcebbcdd2c6dea2397a90a48db975293096054/app/scripts/modules/amazon/src/securityGroup/configure/CreateSecurityGroupCtrl.js#L45) and [`EditSecurityGroupCtrl`](https://github.com/spinnaker/deck/blob/35fcebbcdd2c6dea2397a90a48db975293096054/app/scripts/modules/amazon/src/securityGroup/configure/EditSecurityGroupCtrl.js#L113) to initialize all the accounts and make them available in the dropdown selector.

fix(amazon/securityGroup): Initialize accounts while cloning security groups

---

app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts

This [change](https://github.com/spinnaker/deck/commit/37ff2df776e761dbb286fde994259e288cf0add3) resulted in the broken experience.

fix(titus/pipeline): Set backingData before accessing it

---

app/scripts/modules/core/src/registry/Registry.ts

I often find myself adding `pipelineRegistry` to `window` while debugging something in my machine, so I thought it would be helpful to make it available in `DebugWindow`.

feat(core): Add Registry object to DebugWindow for easier debugging

---

app/scripts/modules/core/src/managed/resources/registerNativeResourceKinds.ts

We added v1.1 of ALBs (ages ago), and clusters (recently) and they currently do not show up as managed resources in the environments view. This was missed in main because nobody has updated their delivery config to these new versions. However, today I made a query fix (https://github.com/spinnaker/keel/pull/1635) that means the resources will be migrated on-the-fly by the query that backs the API endpoint the environment view uses.

Fix new resource versions not showing up in environment view

---

packages/eslint-plugin/package.json

fix(pluginsdk-peerdeps): Move eslint peer deps to plugin-eslint package ([64d57086](https://github.com/spinnaker/deck/commit/64d57086d31a5599c64a7fd9e302186327981c39))
chore(eslint-plugin): bump jest and lodash ([96b2b869](https://github.com/spinnaker/deck/commit/96b2b86925c20910f6a839b55b8895fc980dc988))
feat(eslint-plugin): Add a new rule prefer-promise-like to help migrate off of ng.IPromise [#8673](https://github.com/spinnaker/deck/pull/8673) ([3dc0309d](https://github.com/spinnaker/deck/commit/3dc0309d795946edebef5ebc80836d14b12df0d1))
feat(eslint-plugin): Auto-fix arbitrary expressions with slashes in api-no-slashes lint rule ([28e95ee0](https://github.com/spinnaker/deck/commit/28e95ee003c194b429448f980e6fe501e6b797e9))
fix(eslint-plugin): Allow .split('/') in API.one() calls in …

chore(eslint-plugin): publish 1.0.9

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json

5cd460e824c477a8144c4cf6ddba53432f3a3a1e fix(amazon/targetGroups): Handle empty healthCheckPath (#8727)
f2c6b4ff16f20603d0c58497d83166924a7c65ef fix(core/instance): Optional copyable sshLink to InstanceDetailsHeader (#8728)
5cd460e824c477a8144c4cf6ddba53432f3a3a1e fix(amazon/targetGroups): Handle empty healthCheckPath (#8727)

chore(package): amazon@0.0.280 core@0.0.529

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/VersionStateCard.tsx

Once https://github.com/spinnaker/keel/pull/1656 is merged, versions in the `PENDING`, `DEPLOYING`, `PREVIOUS`, or `CURRENT` states in an environment will include a link directly to a git compare view (Bitbucket/Stash at Netflix) that shows the commits between that version and what we believe is the appropriate comparison version. For example, a `DEPLOYING` version would compare against the version it's currently replacing in that environment.
This PR adds support in the Environments UI for showing a `See changes` button on each environment where applicable, that links out to the compare URL in a new tab. Also includes some analytics so we can see if it's popular.
cc @gcomstock

feat(core/managed): support git compare link on versions

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupCapacity.tsx
app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/src/serverGroup/configure/wizard/TitusCloneServerGroupModal.tsx

Apparently this works for Titus when specified in the JSON so no reason to have to hide it.

Titus target healthy percentage

---

app/scripts/modules/core/src/pipeline/filter/ExecutionFilterModel.ts

The router hook registered against `entering: '**.application.pipelines.executions'` does not get run when someone opens a single execution permalink, so the shared code doesn't get to used values stored in the cache.
Not sure if there is a better way register against both states.

fix(core): Initialize cache for executions permalink

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/MarkArtifactAsBadModal.tsx
app/scripts/modules/core/src/managed/PinArtifactModal.tsx
app/scripts/modules/core/src/managed/UnpinArtifactModal.tsx
app/scripts/modules/core/src/managed/constraints/ConstraintCard.tsx

Correcting an oversight of mine — I hadn't yet added usage tracking to the meaningful/important behaviors in Environments. Focusing first on the behaviors that are most meaningful to the customer value we seek to provide from MD:
- **Pinning, unpinning, and mark as bad (same events for each flow)**: opening/seeing the modal, dismissing the modal without taking action, taking action successfully (pin/unpin/mark), trying to take action and hitting an error
- **Version metadata**: clicking the link to a version's commit, clicking the link to a version's PR
- **Constraints**: clicking a 'constraint action', which is just what we call the buttons on constraints in the UI like "Approve"/"Reject" for manual judgements. The events we log will include the type of constraint and which action was …

feat(core/managed): fill some usage logging gaps in Environments

---

app/scripts/modules/core/src/api/ApiService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts
app/scripts/modules/core/src/image/image.reader.ts
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/network/NetworkReader.ts
app/scripts/modules/core/src/notification/NotificationService.ts
app/scripts/modules/core/src/plugins/plugin.registry.ts
app/scripts/modules/core/src/search/search.service.ts
app/scripts/modules/core/src/task/task.read.service.ts
app/scripts/modules/core/src/task/task.write.service.ts

Previously, `API.one()` returned `any` so all type safety and auto-complete was lost.  Now, those methods return `IRequestBuilder` interface.
- I've cleaned up the calling code whereever it was relying on `any` type being returned
- I added generic parameter to `.get<ReturnType>()` (and `.post`/`.put`/etc)

fix(core/api): Fix type safety for API.one() builder

---

app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js

Just making `dimensions` an empty array if it's undefined to prevent this reduce from throwing:
https://github.com/spinnaker/deck/blob/976e958b25d44086b59108367ab038199ffcdc7e/app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/chart/metricAlarmChart.component.js#L42

fix(titus): Fallback dimensions for target tracking policy

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/dimensionsEditor.component.html
app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js
app/scripts/modules/titus/src/serverGroup/serverGroup.transformer.js

Not the cleanest, but the least invasive way to temporarily disable editing of dimensions in step scaling policies for Titus.

fix(titus): Disable edits of step scaling dimensions

---

packages/pluginsdk-peerdeps/package.json

Bumping to use some newly exported core components in a plugin.

chore(pluginsdk-peerdeps): Publish 0.0.4

---

packages/eslint-plugin/newrule.sh

This script scaffolds a new eslint rule into the eslint-plugin
```
./newrule.sh my-rule-name
```
- Creates a basic rule in `rules/my-rule-name.js`
- Creates a basic test in `test/my-rule-name.spec.js`
- Publishes the rule in the `@spinnaker/eslint-plugin` plugin
- Adds the new rule to the base eslint config

feat(eslint-plugin): Add a newrule.sh scaffolding script

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/eslint-plugin.js
packages/eslint-plugin/package.json
packages/eslint-plugin/rules/api-deprecation.js
packages/eslint-plugin/rules/api-no-unused-chaining.js
packages/eslint-plugin/rules/rest-prefer-static-strings-in-initializer.js
packages/eslint-plugin/test/api-deprecation.spec.js
packages/eslint-plugin/test/api-no-unused-chaining.spec.js
packages/eslint-plugin/test/rest-prefer-static-strings-in-initializer.spec.js
packages/eslint-plugin/utils/utils.js
packages/eslint-plugin/yarn.lock

This PR introduces three new eslint rules:
- `api-deprecation`: Migrates from `API.one()` to `REST()`
- `api-no-unused-chaining`: Finds `var foo = API.one();  foo.withParams()` chained method calls with unused return values
- `rest-prefer-static-strings-in-initializer`: Migrates from `REST().path('foo', 'bar', id')` to `REST('/foo/bar').path(id)`

Introduce new linter rules deprecating API.one()

---

app/scripts/modules/core/src/api/ApiService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts
app/scripts/modules/core/src/api/ApiServiceDeprecated.spec.ts
app/scripts/modules/core/src/cluster/cluster.service.ts
app/scripts/modules/core/src/plugins/plugin.registry.spec.ts
app/scripts/modules/core/src/plugins/plugin.registry.ts
app/scripts/modules/core/src/presentation/spel/SpelService.spec.ts
app/scripts/modules/core/src/search/search.service.ts
app/scripts/modules/core/src/task/task.read.service.ts
app/scripts/modules/core/src/utils/consoleDebug.ts

I've been doing some thinking about our `API` rest builders and how it could be improved.
Things I don't like:
1) `.one()` vs `.all()`
What do these mean?  They are borrowed from the Restangular API but don't actually do anything different.
2) `.get()` vs `.getList()`
Again, borrowed from Restangular, but they do the same thing.
3) `.data(obj).post()` vs `.post(obj)` ...  `.data(obj).put()` vs `.put(obj)`
Whats the difference?
4) `.withParams({ param: value }).get()` vs `.get({ param: value })`
Whats the difference?
5) encodeUriComponent in .one() and .all()
this PR https://github.com/spinnaker/deck/pull/8646 aims to encode path parameters, such as 'appname'  in `.one('applications', appname)`.  However, this makes it less convenient to append a string like `/proxies/pandora/api/v1`.
With …

Deprecate API.one('foo').all('bar').get() in favor of REST('/foo/bar').get()

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/PreDeploymentStepCard.tsx
app/scripts/modules/core/src/managed/VersionStateCard.tsx

We recently added support for ['pre-deployment' events](https://github.com/spinnaker/deck/pull/8750), starting with baking. We're now ready to add the same for builds. A couple notable bits that have evolved since the last PR:
- In order to handle the cases that can show up in the build context there's a new status: `ABORTED`. Unfortunately our internal build system (Jenkins) doesn't seem to differentiate between builds that entered this status because of a timeout (bad/error) or because a user manually canceled it (fine/not an error), so we have to be somewhat hand-wavey about this status and our use of colors. For now I've made the decision to show it the same way we show successful builds (neutral color, no badge in the sidebar) because I have a hunch the manual cancellation use case …

feat(core/managed): add pre-deployment events for builds

---

app/scripts/modules/ecs/src/ecs.help.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.html
test/functional/cypress/integration/ecs/server_group.spec.js

Basic UI changes to support https://github.com/spinnaker/spinnaker/issues/5400
* NOTE: Does not (yet) look up capacity providers per cluster and provide them as a drop down. This work is anticipated as a near term enhancement.
* Related PR: https://github.com/spinnaker/clouddriver/pull/5123
* With launch type (default)
* With capacity provider strategies
* Successful deployment w/ https://github.com/spinnaker/clouddriver/pull/5123 :

feat(ecs): Add basic capacity provider UI 

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx
app/scripts/modules/core/src/managed/PreDeploymentStepCard.tsx

The API data for build events introduced via #8768 has proved to be a bit wonky in the first iteration, and is going to take a little more implementation time on the Keel side to resolve. Events get stuck in the `RUNNING` status — which looks pretty sketchy/untrustworthy in the Environments UI — so I'm going to temporarily disable them here until we're confident the data will look right.

fix(core/managed): temporarily hide build pre-deployment events

---

app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json

8a8698145e64a5644045c2e622f214189663b105 fix(core/managed): temporarily hide build pre-deployment events (#8776)
7a723c980fabb5265dbb66251c1ae4c62b2ea01b Revert "feat(bake): add UI element for helmChartFilePath to bake manifest stage, when using a git/repo artifact for the helm chart (#8751)" (#8773)
54097588e543bc62981f35bd19d811be93b0f64b fix(core): Redirecting aged out executions to permalink (#8770)
38b31387459b548d8b44caeee24bbcd251eeedc5 feat(bake): add UI element for helmChartFilePath to bake manifest stage, when using a git/repo artifact for the helm chart (#8751)
1e49b1c5171284ddd88b5d0cade785c22c5ea869 feat(ecs): Add basic capacity provider UI (#8767)

chore(package): core@0.0.536 ecs@0.0.272

---

app/scripts/modules/core/src/pipeline/config/stages/monitorPipeline/MonitorPipelineStageExecutionDetails.tsx

Wrapping the link with a `span` tag results in the following html and breaks the link.

fix(core/pipeline): Fix linking to pipeline execution

---

app/scripts/modules/core/src/application/service/ApplicationReader.ts
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/ManualJudgmentApproval.tsx
app/scripts/modules/core/src/pipeline/config/stages/stage.html
app/scripts/modules/core/src/pipeline/config/stages/stage.module.js

This is part of: spinnaker/spinnaker#4792.
Enhanced stage.html to
Get the roles of the application. Display the roles of the application as a list, only if the stage is Manual Judgment.
Enhanced stage.module.js to
Fetch the permissions of the application from the gate application url. populate the list with only the roles of the application with no duplicates.
Enhanced ApplicationReader.ts to
Fetch the permissions of the application from the gate application url.
Enhanced ManualJudgmentApproval.tsx to
Fetch the roles of the application, stage and the user during the execution. Iterate through each of the user role to check if the role exists in the stage and application. If the role exists in the stage roles added in the manual judgment stage, then we check for role permissions added in …

feat(manual judgment/deck): Added ability to add roles to manual judgment stage

---

app/scripts/modules/ecs/src/ecs.help.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/CloneServerGroup.ecs.controller.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html

Rename capacityProviderStrategies to capacityProviderStrategy to align with [CreateService api](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-capacityProviderStrategy). As this is a new feature for 1.24, this will not be backwards incompatible if patched.
* requires https://github.com/spinnaker/clouddriver/pull/5154
* UI screenshot
* update JSON for stage
* deployment success

fix(ecs): rename capacityProviderStrategies to capacityProviderStrategy

---

app/scripts/modules/core/src/cloudProvider/CloudProviderLogo.tsx
app/scripts/modules/core/src/cloudProvider/cloudProviderLogo.less

An `svg` used in for cloud provider logos can now be configured while registering the cloud provider via `cloudProviderLogo`. The current implementation uses css to put an image mask over a span. For plugin-based cloud providers, the plugin will load the svg when it registers the plugin on initilization.

chore(core): Allow cloud provider logos in registry

---

app/scripts/modules/core/src/managed/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/ArtifactsList.tsx

as described in https://github.com/spinnaker/deck/pull/8776, we temporarily disabled build pre-deployment steps in the UI to handle a data issue. We're now ready to flip the switch back on.

fix(core/managed): re-enable build events

---

app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/google/package.json

06aca3a951b32c0ae6bad4aac3a760824b46202f fix(core/managed): re-enable build events (#8786)
728939d7957997b4756467123415024a18d4395b chore(core): Allow cloud provider logos in registry (#8782)
38568a3f9c94af42e71fda0dd6229f458a71b443 feat(manual judgment/deck): Added ability to add roles to manual judgment stage (#8779)
aa201bba182ff009676913ac40422d057eb9f647 fix(core/pipeline): Fix linking to pipeline execution (#8778)
a53e32cfcd045bfbabf9b5a46c46ead352f585ee feat(bake): add UI element for helmChartFilePath to bake manifest stage, when using a git/repo artifact for the helm chart (#8774)
43e2f120b67a1446249a5b22faaf49c0afbb3658 fix(ecs): rename capacityProviderStrategies to capacityProviderStrategy
1446faca4d7e6d24079722c8dd56f51c35f4d010 feat(targetShape): remove the ALPHA conditional …

chore(package): core@0.0.537 ecs@0.0.273 google@0.0.29

---

app/scripts/modules/core/src/pipeline/config/graph/PipelineGraph.tsx
app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx

Fixes these warnings:
```
export 'IPipeline' was not found in 'core/domain'
```

fix: use 'import type {} from package' to fix the webpack warnings for missing interface imports

---

app/scripts/modules/amazon/src/image/image.reader.spec.js
app/scripts/modules/amazon/src/instance/awsInstanceType.service.js
app/scripts/modules/amazon/src/vpc/VpcReader.spec.js
app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFileArtifactList.spec.tsx
app/scripts/modules/azure/src/image/image.reader.spec.js
app/scripts/modules/azure/src/instance/azureInstanceType.service.js
app/scripts/modules/azure/src/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/src/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/canary/canary/actions/endCanary.controller.js
app/scripts/modules/canary/canary/actions/generateScore.controller.js
app/scripts/modules/canary/canary/canaryExecutionSummary.controller.js
app/scripts/modules/core/src/account/AccountService.spec.ts
app/scripts/modules/core/src/api/ApiService.ts
app/scripts/modules/core/src/authentication/AuthenticationInitializer.spec.ts
app/scripts/modules/core/src/cluster/cluster.service.spec.ts
app/scripts/modules/core/src/function/function.read.service.spec.ts
app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.spec.ts
app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.spec.ts
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgment.service.spec.ts
app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
app/scripts/modules/core/src/pipeline/service/execution.service.ts
app/scripts/modules/core/src/securityGroup/securityGroupReader.service.spec.ts
app/scripts/modules/core/src/subnet/subnet.read.service.spec.ts
app/scripts/modules/core/src/task/monitor/taskMonitor.spec.ts
app/scripts/modules/core/src/task/task.read.service.spec.js
app/scripts/modules/core/src/widgets/spelText/SpelText.tsx
app/scripts/modules/dcos/image/image.reader.spec.js
app/scripts/modules/google/src/instance/gceInstanceType.service.js
app/scripts/modules/oracle/src/loadBalancer/configure/createLoadBalancer.controller.spec.ts

While migrating tests away from `$httpBackend` I noticed that there is still some direct usage of `$http`.  Where possible, I migrated these to `API`.
I also migrated `$http.expectGET()` calls to `$httpBackend.expectGET` to enable an upcoming migration of tests from`$httpBackend` to `MockHttpClient`
This PR is organized into 3 separate commits for easier reading

Avoid raw "$http" usage

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/eslint-plugin.js
packages/eslint-plugin/rules/migrate-to-mock-http-client.js
packages/eslint-plugin/test/migrate-to-mock-http-client.spec.js

This migrates to the mock HTTP client introduced in #8775
```ts
describe('service', () => {
it('fetches a foo', () => {
$httpBackend.expectGET('/rest/foo').respond(200, { fooData: [] });
const fooPromise = service.fetchFoo();
$httpBackend.flush();
});
```
```ts
import { mockHttpClient } from 'core/api/mock/jasmine';
describe('service', () => {
it('fetches a foo', async () => {
const http = mockHttpClient();
http.expectGET('/rest/foo').respond(200, { fooData: [] });
const fooPromise = service.fetchFoo();
await http.flush();
});
```
This migration isn't expected to work out of the box in all cases.  Manual rewrite of some tests will be necessary.

feat(eslint-plugin): Add a new rule to migrate from $httpBackend to MockHttpClient

---

app/scripts/modules/amazon/src/loadBalancer/details/loadBalancerDetails.html

Just exposing a load balancer's scheme in the details pane:
(options are `internal` or `internet-facing`)

feat(aws): Add scheme to load balancer details

---

app/scripts/modules/core/src/pipeline/details/executionDetailsSection.service.spec.ts
app/scripts/modules/core/src/pipeline/details/executionDetailsSection.service.ts

This fixes some annoying situations where certain location records are lost because when navigating to a React stage, we are replacing the wrong history record. 
1. Go to executions
2. Navigate to a stage that is not the same type as the first stage of a pipeline
3. Navigate to the permalink
4. Use the back icon to navigate up, back to the executions (with the same execution selected)
5. Use the browser's back feature to go back to the permalink
For pipelines where the first stage of the pipeline is a React stage (that is, the execution details is a React component), #5 will not take you to the permalink. In fact, the permalink is entirely missing from the browser's history stack.
1. Clicking on a stage will `toggleDetails` which transitions to a stage, but its available detail sections …

fix(pipeline): Fixing lost history record for React stages

---

app/scripts/modules/ecs/src/ecs.help.ts
app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/networking/Networking.tsx

Add support for multiple subnet types in the ECS Provider. 
This change is dependent on https://github.com/spinnaker/clouddriver/pull/5087 being merged in first!
Closes: https://github.com/spinnaker/spinnaker/issues/6097

feat(ecs): support selecting multiple subnet types

---

app/scripts/modules/amazon/src/image/image.reader.spec.js
app/scripts/modules/amazon/src/instance/awsInstanceType.service.spec.js
app/scripts/modules/amazon/src/serverGroup/configure/AmazonImageSelectInput.spec.tsx
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupCommandBuilder.aws.service.spec.js
app/scripts/modules/amazon/src/vpc/VpcReader.spec.js
app/scripts/modules/appengine/src/serverGroup/configure/wizard/configFileArtifactList.spec.tsx
app/scripts/modules/azure/src/image/image.reader.spec.js
app/scripts/modules/azure/src/loadBalancer/configure/createLoadBalancer.controller.spec.js
app/scripts/modules/azure/src/securityGroup/configure/CreateSecurityGroup.controller.spec.js
app/scripts/modules/core/src/account/AccountService.spec.ts
app/scripts/modules/core/src/cluster/cluster.service.spec.ts
app/scripts/modules/core/src/function/function.read.service.spec.ts
app/scripts/modules/core/src/pagerDuty/pagerDuty.read.service.spec.ts
app/scripts/modules/core/src/pipeline/config/services/PipelineConfigService.spec.ts
app/scripts/modules/core/src/pipeline/config/stages/manualJudgment/manualJudgment.service.spec.ts
app/scripts/modules/core/src/pipeline/service/execution.service.spec.ts
app/scripts/modules/core/src/securityGroup/securityGroupReader.service.spec.ts
app/scripts/modules/core/src/serverGroup/serverGroupWriter.service.spec.ts
app/scripts/modules/core/src/subnet/subnet.read.service.spec.ts
app/scripts/modules/core/src/task/monitor/taskMonitor.spec.ts
app/scripts/modules/core/src/task/task.read.service.spec.js
app/scripts/modules/core/src/task/task.write.service.spec.ts
app/scripts/modules/dcos/image/image.reader.spec.js
app/scripts/modules/oracle/src/loadBalancer/configure/createLoadBalancer.controller.spec.ts

This PR includes all the commits from #8775.  #8775 should be merged separately before this PR gets merged.
Migrates all use of `$httpBackend` to `MockHttpClient` except for:
- `APIServiceDeprecated.spec.ts`
- `AuthenticationInitializer.ts`

Migrate tests to MockHttpClient

---

app/scripts/modules/core/src/projects/projects.states.ts

The recent history service uses the state's `.data` field to configure recent history behavior.
```
$rootScope.$on('$stateChangeSuccess', (_event: IAngularEvent, toState: Ng1StateDeclaration, toParams: any) => {
if (toState.data && toState.data.history) {
const params = omit(toParams || {}, ['debug', 'vis', 'trace']);
RecentHistoryService.addItem(toState.data.history.type, toState.name, params, toState.data.history.keyParams);
}
});
```
It uses `.data.history.keyParams` to check if a recent entry is already recorded.  It compares the configured router params with the stored values.
```
private static getExisting(items: IRecentHistoryEntry[], params: any, keyParams: string[]): IRecentHistoryEntry {
if (!keyParams || !keyParams.length) {
return find(items, { params: omitBy(params, …
```

fix(core/projects): Fix duplicate Projects appearing in recent history (on search screen)

---

app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupResources.tsx

Just like we do for `Capacity`:
I wonder if we'll need to do something to prevent the SpEL toggle when thess fields are used outside of a pipeline context, i.e. server group clone modal.
Either way, probably shouldn't hold out on adding this just to figure that out.

feat(titus): Support SpEL for Resources number inputs

---

app/scripts/modules/titus/src/pipeline/stages/runJob/TitusRunJobStageConfig.tsx

Forgot to check the Titus Run Job stage when I originally did https://github.com/spinnaker/deck/pull/8808
Apparently it is not using `ServerGroupResources` so it didn't come along for the ride.
I originally wanted to move this whole stage over to `Formik`, so that it could share that component with the Titus deploy dialog, but there are other things I want to spend time thinking through for that so would prefer to migrate that separate from bringing SpEL support to the run job stage.

feat(titus): Support SpEL for Run Job stage inputs

---

app/scripts/modules/core/src/application/nav/verticalNav.less
app/scripts/modules/core/src/domain/IPipeline.ts
app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroup.tsx
app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroups.tsx
app/scripts/modules/core/src/pipeline/executions/executionGroup/MigrationTag.tsx
app/scripts/modules/core/src/pipeline/executions/executionGroup/executionGroup.less
app/scripts/modules/core/src/presentation/stickyHeader.less

- Add optional `migrationStatus` to `IPipeline`
- Add an `in-migration` class to add unique styling to the newly migrated execution group
- Sort newly migrated groups to the top of the list
- A generic migration tag component, that can be overriden with a migration-specific component if needed

feat(core/executions): Render newly migrated execution groups 

---

app/scripts/modules/core/src/api/ApiService.ts

Increase the timeout seconds from
**1.24.0 default timeout**
```javascript
(SETTINGS.pollSchedule || 3000) * 2 + 5000,
```
to 
**< 1.24.0 default timeout**
```javascript
(SETTINGS.pollSchedule || 30000) * 2 + 5000,
```
Solves https://github.com/spinnaker/spinnaker/issues/6246.
This change was released in 1.24.0 in this PR ([Deprecate API.one('foo').all('bar').get() in favor of REST('/foo/bar').get() ](https://github.com/spinnaker/deck/pull/8760/files)). I think this changed happened intentionally during this refactor and I want to revert it because GetManifest request often requires duration of seconds.
When I upgraded to Spinnaker 1.24.0, the server group detail page often hung with loading because the browser GetManifest request is timeouts and retries again and again.

Revert API request default timeout seconds

---

app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js
app/scripts/modules/amazon/src/securityGroup/configure/createSecurityGroupIngress.html

Add `ICMPv6` as an option for ingress rule protocol types. This is already supported on the BE.

feat(aws): Allow ICMPv6 type ingress rules for security groups

---

app/scripts/modules/core/src/deploymentStrategy/strategies/highlander/HighlanderPreview.tsx
app/scripts/modules/core/src/deploymentStrategy/strategies/highlander/highlander.strategy.ts

Finally got around to implementing this feature request for Highlander strategy.  We could add a similar preview for Red/Black if we can predict the behavior accurately enough in Deck.

feat(core/deploymentStrategy): Add a preview for Highlander deploys

---

app/scripts/modules/amazon/src/vpc/VpcTag.tsx

The class component called setState in the constructor if the VPC is unknown.  It could also potentially call setState after the component was unmounted.  
Migrated to `useData` to avoid both cases.

fix(amazon/vpc): Fix error: "cannot call setState on an unmounted component" by migrating to FC/useData

---

app/scripts/modules/amazon/src/domain/IAmazonHealth.ts
app/scripts/modules/amazon/src/instance/details/utils.ts
app/scripts/modules/amazon/src/loadBalancer/amazonLoadBalancerDataUtils.ts

Fix target group health interface to match the shape returned from the back end.
This surfaced a bug in passing instance counts for target groups (in the load balancer icon popover in a server group)
Missing health counts 👇

fix(amazon/loadBalancer): Fix target group health interface

---

app/scripts/modules/amazon/src/securityGroup/configure/configSecurityGroup.mixin.controller.js

For a standalone security group, the app's name is the security group name. When cloning a standalone security group, the previewer show `app-stack-detail-newstack-detail` instead of `app-newstack-newdetail`. This causes some confusion for users who need to clone their security group.

fix(amazon): Security group names for standalone apps render incorrectly

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBListeners.tsx

After configuring a redirect in the ConfigureRedirectConfigModal, the new (or updated) config is not shown in the Edit Load Balancer modal. This makes it difficult to review your changes for mistakes, or even know whether your config actually took effect.

feat(amazon): Display updated ALB redirect config

---

app/scripts/modules/amazon/package.json
app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/kubernetes/package.json
app/scripts/modules/titus/package.json

169c601301a2f759cefdb3e414fcd5e7038c0b21 feat(amazon): Display updated ALB redirect config (#8830)
6904cb064db6733db513f44147a6344dc1cf89da fix(amazon): Security group names for standalone apps render incorrectly (#8816)
d005ea506316e413a8b044b902c58f8a772cedcb fix(amazon/loadBalancer): Fix target group health interface to match the back end, fix instance counts for target groups in the load balancer icon popover in a server group (#8828)
34b68b8f5a07e65fc343cfe75d06b72c6277dd59 fix(amazon/vpc): Fix error: "cannot setState on an unmounted component" by migrating to FC/useData (#8827)
cb30f14f27678c4c8f945676525eec203656c011 feat(aws): Allow ICMPv6 type ingress rules for security groups (#8814)
95eacfb6f5cea460677aa0907b18555dedae4135 refactor(core/deployment): Update redblack fields …

chore(package): amazon@0.0.285 cloudfoundry@0.0.109 core@0.0.539 ecs@0.0.275 kubernetes@0.0.57 titus@0.0.157

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/core/src/serverGroup/configure/common/ServerGroupNamePreview.tsx
app/scripts/modules/core/src/serverGroup/configure/common/index.ts
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

The preview of the server group name is duplicated for every cloud provider. This PR creates a core component, `ServerGroupNamePreview`, to take the place of these duplicates. The angular templates needed some additions to the controller to make it react-friendly.

refactor(core): Extract server group name previewer into its own component

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

ddbe1d65ba77aa9c2bed2501311596f69127f205 feat(aws): Automatically enable IPv6 in test environments when IPv6 f… (#8813)
a130ca87b28fa563cccf8ed447a8395bc6561b2b feat(amazon): Display updated ALB redirect config (#8844)
a35e8bf29007e928374e79eb95eaf91d0f8d5f25 refactor(core): Extract server group name previewer into its own component (#8842)
a35e8bf29007e928374e79eb95eaf91d0f8d5f25 refactor(core): Extract server group name previewer into its own component (#8842)
625ba6fc5613d4d28f4da701a99b6f690cd72e08 fix(pipeline): fix error message handling (#8843)
ccf8c0021b712cb76d9936b3d751044b1744c35b fix(core/pipeline): Remove note that pipelines are only paused for 72 hours
a35e8bf29007e928374e79eb95eaf91d0f8d5f25 refactor(core): Extract server group name previewer into its own component (#8842) …

chore(package): amazon@0.0.286 core@0.0.540 titus@0.0.158

---

app/scripts/modules/core/src/pipeline/executions/executionGroup/ExecutionGroups.tsx

If the pipeline config is `null`, an error is thrown while sorting pipelines by their `migrationStatus`. This adds optional chaining to prevent that.

fix(core/executions): Protect migrationStatus sorting if config is null

---

app/scripts/modules/core/src/cluster/cluster.service.spec.ts
app/scripts/modules/core/src/cluster/cluster.service.ts

Since forever, it appears that we've been incorrectly removing `serverGroup`s when merging the response into the `serverGroups` datasource (to preserve referential equality and save on some, hopefully many, rerenders).
It all boils down these few lines:
```
data.forEach((serverGroup: IServerGroup, idx: number) => {
...
toRemove.push(idx);
...
toRemove.forEach((idx) => data.splice(idx, 1));
```
Since we are pushing into `toRemove` while `forEach`ing data, the indices will naturally be in ascending order. However, as we iterate through the array of ascending indices to splice (remove) those elements out of `data`, we start from the left causing everything to the right to shift left by 1 every iteration. For example:
```
const toRemove =      [0, 1];
const data =          [0, 1, 2, 3, 4, 5]; …
```

fix(core): Fix incorrect removal when merging serverGroups response

---

app/scripts/modules/core/src/domain/IStageTypeConfig.ts
app/scripts/modules/core/src/pipeline/details/StageSummary.tsx

Developers can customize the stage summary for a given stage, but only in AngularJS. This provides a way to customize the stage summary with a React component, instead.

feat(core): allow custom stage summary as React components

---

app/scripts/modules/core/src/serverGroup/details/multipleServerGroups.controller.js
app/scripts/modules/core/src/serverGroup/details/multipleServerGroups.controller.spec.js

We got feedback that when selecting many server groups to enable/disable and accidentally choosing one that is opposite of the desired state, you cannot perform the action you want. It takes too much time to scroll through and de-select the invalid server groups. The suggestion was to make this more intelligent (i.e. if we know the user is disabling a group of server groups only allow the selected _and_ enabled server groups to be disabled).
Before:
- User cannot choose to bulk enable/disable all selected server groups if they are all already disabled/enabled. This option is hidden from server group actions
After:
- User can choose enable/disable in server group actions if some of the selected server groups match the desired state
- Invalid server groups are automatically filtered out …

feat(core/serverGroups): Intelligently enable/disable server groups in multiselect

---

app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx

It's not clear why we are not catching any errors if the `submitJustWithReason` flag is set but I am pretty sure it was an oversight when this was converted to React (it was being caught in the AngularJS version) and I am the one who converted it about a year ago so I can't really blame anyone else.

fix(core): handle errors on confirmation modal submission

---

app/scripts/modules/core/src/pipeline/details/index.ts

Having the props for the StageSummary component is useful when overriding the component. This should have been done as part of my earlier PR today, but I didn't realize they weren't exported already, so...here they are.

feat(core): export StageSummary props in core module

---

app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/container/Container.tsx

This PR fixes the issue [#5248](https://github.com/spinnaker/spinnaker/issues/5248)
For the ECS Provider in deck, an Alert have been added when there is a target group(s) that was previously selected and is no longer available.
Dirty Target Groups
Working Target Groups

fix(ecs): Determine invalid target groups for the ECS provider

---

app/scripts/modules/ecs/src/ecsCluster/IEcsCapacityProviderDetails.ts
app/scripts/modules/ecs/src/ecsCluster/ecsCluster.read.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx
app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/capacityProvider.html
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.html
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.component.js
app/scripts/modules/ecs/src/serverGroup/configure/wizard/horizontalScaling/horizontalScaling.html
test/functional/cypress/fixtures/ecs/shared/ecsClusters.json
test/functional/cypress/fixtures/ecs/shared/ecsDescribeClusters.json
test/functional/cypress/integration/ecs/server_group.spec.js

This PR adds a new enhanced version of UI to support Capacity Providers.
Currently, Capacity Provider UI section provides input fields to enter details about Capacity Provider Strategy for the server group.
But new UI will have a drop down list for selecting a Capacity Provider. Plus now users can add default Capacity providers without typing in the details of default Capacity Provider by just clicking on the use cluster default option. Please refer the following screenshots for the more details.
When set custom capacity provider startegy
When set default capacity provider startegy
When default capacity provider is not available on the cluster
When Custom capacity providers are not available on the cluster
Addresses [spinnaker/spinnaker#6242](https://github.com/spinnaker/spinnaker/issues/6 …

feat(ecs): improve the Capacity Providers configuration UI

---

app/scripts/modules/core/src/application/nav/ApplicationNavigation.tsx

fix(core): add vertical padding on page owner nav link

---

app/scripts/modules/core/src/instance/details/InstanceLinks.tsx

Sometimes the `ipAdress` needs to be delimited by dashes in links. Adding `embeddableIpAddress` as a way to use this value in links.
ipAddress = 127.0.0.1
embeddableIpAddress = 127-0-0-1

feat(core): Add a new variable that is interpolated in instance links

---

app/scripts/modules/core/src/cluster/AllClustersGroupings.tsx

The `AutoSizer` was only listening to a window resize, but when an instance or server group is selected, rows also need to be resized. This caused the server group views to render on top of each other once the details panel was opened.
This PR adds a subscription to listen for opening/closing the details panel so that the cluster pods can re-render with appropriate heights.

fix(core/cluster): Clicking an instance breaks rendering of cluster pods

---

app/scripts/modules/ecs/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/ecs/src/serverGroup/configure/wizard/capacityProvider/CapacityProvider.tsx

This PR fixes [#6317](https://github.com/spinnaker/spinnaker/issues/6317)
For the ECS Provider in deck, an Alert have been added when there is capacity provider(s) that was previously selected and is no longer available.
Dirty Capacity Provider
Active Capacity Providers

feat(ecs): Determine invalid capacity providers

---

webpack.config.js

Hot reloading allows us to update styles without refreshing and speeds up the dev process.
This feature is disabled in production.

feat(dev): Added webpack hot reloading

---

app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json

274944fb9bd0f04b69a6b634e332a0eea73ed75f feat(md): Collasible metadata elements  (#8880)
c7a58cd4657054b2b1333057333f6aed0151741f fix(core/cluster): Clicking an instance breaks rendering of cluster pods (#8866)
76cd8cdfd6d381fb0c4ad15181026e27b923cff1 feat(core): Add a new variable that is interpolated in instance links (#8868)
b3ae753aab84e0c471355d1ee5ac69f572b81808 fix(core): add vertical padding on page owner nav link (#8876)
7d94b690fef08aee08ed724f4d99ee300e9670c1 feat(core): Expose raw subnet ID (#8877)
760c20f6937ec17f70d2f784087b0adb21effe39 feat(ecs): Determine invalid capacity providers for the ECS provider (#8878)
53a0102118fc08a7d0845034e195cf6e8e8485dc feat(ecs): Add support for Capacity providers - enhanced Deck UI (#8875)
2d913a376ec54bbec493b0f3c24fe93dfa437fd2 fix(ecs): …

chore(package): core@0.0.545 ecs@0.0.276

---

app/scripts/modules/amazon/src/loadBalancer/configure/application/ALBAdvancedSettings.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/application/CreateApplicationLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/network/CreateNetworkLoadBalancer.tsx
app/scripts/modules/amazon/src/loadBalancer/configure/network/NLBAdvancedSettings.tsx
app/scripts/modules/amazon/src/loadBalancer/loadBalancer.transformer.ts
app/scripts/modules/core/src/help/help.contents.ts

ALBs and NLBs can have an `ipAddressType` of `ipv4` or `dualstack` if:
- The ALB is external
- The NLB is external, but all targets are of type `ip`.
This option is now an advanced setting the server group configuration. If nothing is selected it will default to `ipv4` (which is the current behavior). 
This also refactors the ALB/NLB advanced settings to functional components.

feat(amazon/loadBalancer): Enable dualstacking in ALBs/NLBs with constraints

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/amazon/src/instance/details/InstanceDns.tsx
app/scripts/modules/amazon/src/instance/details/InstanceStatus.tsx
app/scripts/modules/amazon/src/instance/details/instance.details.controller.js
app/scripts/modules/amazon/src/instance/details/instanceDetails.html
app/scripts/modules/amazon/src/instance/details/instanceDns.component.ts
app/scripts/modules/amazon/src/instance/index.ts
app/scripts/modules/core/src/instance/details/InstanceLinks.tsx
app/scripts/modules/titus/src/instance/details/TitusInstanceDns.tsx
app/scripts/modules/titus/src/instance/details/instanceDetails.html
app/scripts/modules/titus/src/instance/details/titusInstanceDns.component.ts
app/scripts/modules/titus/src/titus.module.ts

Converting the DNS section to React. The `react2angular` will be temporary until the containing instance details component is refactored as well.

refactor(aws/titus): Convert instance DNS to react

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/capacity/CapacitySelector.tsx

Adjusting some misleading text for the advanced mode of the `CapacitySelector` It is necessary to use the advanced mode if you want to use auto-scaling features, but it is not true that doing so sets up auto-scaling.

fix(serverGroup): Update capacity text to be more accurate

---

app/scripts/modules/amazon/package.json
app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

1e64d9093d864476616248c60a710f0c407f686a fix(serverGroup): Update capacity text to be more accurate (#8891)
745e1bf5592b768e733f32b6fe6d6852b955c227 refactor(aws/titus): Convert instance DNS to react (#8884)
4c6617492ad0e70e913c1608241cb0c0870e4f4e feat(amazon/loadBalancer): Enable dualstacking in ALBs/NLBs with constraints (#8859)
5713c91c5e6a18cb23b6c2de125f64e418f8fbf1 feat(cloudfoundry): support docker deployments on cloudfoundry (#8864)
745e1bf5592b768e733f32b6fe6d6852b955c227 refactor(aws/titus): Convert instance DNS to react (#8884)
b4584689dd15f66d03fed420fb62a175724b1989 feat(core): Toggle to show or hide many filter tags (#8869)
4c6617492ad0e70e913c1608241cb0c0870e4f4e feat(amazon/loadBalancer): Enable dualstacking in ALBs/NLBs with constraints (#8859) …

chore(package): amazon@0.0.288 cloudfoundry@0.0.111 core@0.0.546 titus@0.0.160

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/eslint-plugin.js
packages/eslint-plugin/rules/import-sort.js
packages/eslint-plugin/test/import-sort.spec.js

Adding a new eslint rule to ensure a standardized ordering of imports. The following order will be maintained.
1. npm package
2. @spinnaker package
3. relative path module
4. css imports
Within each of the above partitions, individual import declarations will be sorted alphabetically based on the module/package name.

feat(eslint): New eslint rule for ensuring import order

---

app/scripts/modules/amazon/src/loadBalancer/configure/network/CreateNetworkLoadBalancer.tsx

Flipping this constraint based on current AWS limitations.

fix(amazon): Update NLB dualstack constraints for instance targets

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/eslint-plugin.js
packages/eslint-plugin/rules/import-from-presentation-not-core.js
packages/eslint-plugin/test/import-from-presentation-not-core.spec.js

If a presentation module is migrated to `@spinnaker/presentation` package, they should not be imported from `@spinnaker/core` anymore.

refactor(eslint): Lint rules to prevent presentation import from core

---

app/scripts/modules/core/package.json

205e164eeee964b6ede0f56d840215078760da10 fix(core/ci): Fix endpoint url typo in getJobConfig() (#8904)
e63b2abe48e65d343a369a30b66995be6c23ce03 fix(CiBuild): Allow for empty SCM information when pulling builds (#8890)

chore(package): core@0.0.549

---

packages/eslint-plugin/rules/import-sort.js
packages/eslint-plugin/test/import-sort.spec.js

Non-import declaration nodes found between the first and last import statements are currently just removed leading to unexpected behavior. In this commit, such nodes are collected and written back to the end of the import declarations.

fix(lint): Handle non-import declaration nodes in import-sort rule

---

app/scripts/modules/amazon/src/help/amazon.help.ts

[This PR](https://github.com/spinnaker/clouddriver/pull/5020) converted the `BlockDeviceConfig.groovy` to java. The linked file is now broken because of this.

fix: broken link to renamed BlockDeviceConfig.groovy

---

app/scripts/modules/core/src/notification/NotificationsList.tsx
app/scripts/modules/core/src/notification/modal/EditNotificationModal.tsx

These updates are not compatible with the pipeline notifications. App level notifications and pipeline level notifications are persisted differently. The path of promise chaining to avoid a dual-save for applications, was not consistent with updating the pipeline notification then later saving the entire pipeline config. 
I will revisit this later. It probably requires a different set of methods for each notification level.

fix(core): Revert notifications saving changes

---

package.json
yarn.lock

Ensure eslint is run before commit so that eslint fixes are automatically applied.
Since lint-staged takes care of running commands for staged files, I'm removing pretty-quick and using prettier directly.

chore(lint): Run lint before commit

---

app/scripts/modules/amazon/src/instance/details/InstanceDns.tsx

When the instance port is not defined, the href looks like this: `http://{ip}:undefined`. This PR fixes that.

fix(amazon): Instance DNS hrefs when Instance Port is not defined

---

packages/eslint-plugin/base.config.js
packages/eslint-plugin/package.json
packages/eslint-plugin/yarn.lock

IDEs run eslint eagerly and seeing prettier lint errors pop-up aggressively results in a poor dev experience. So removing the prettier linter here.

chore(lint): Remove lint rule for prettier

---

packages/eslint-plugin/base.config.js

1) When doing local development, it's annoying that webpack-dev-server doesn't reload if there are any eslint errors. 
2) Marking this rule as a warning seems reasonable anyway

chore: make sort-imports rule a warning, rather than an error

---

app/scripts/modules/core/src/domain/IManagedEntity.ts
app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
app/scripts/modules/core/src/managed/Button.tsx
app/scripts/modules/core/src/managed/DeployingIntoManagedClusterWarning.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/EnvironmentsList.tsx
app/scripts/modules/core/src/managed/ManagedMenuItem.tsx
app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/ManagedResourceDetailsIndicator.tsx
app/scripts/modules/core/src/managed/ManagedResourceObject.tsx
app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
app/scripts/modules/core/src/managed/StatusCard.tsx
app/scripts/modules/core/src/managed/ToggleManagedResourceForApplication.tsx
app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetail.tsx
app/scripts/modules/core/src/managed/artifactDetail/ArtifactDetailHeader.tsx
app/scripts/modules/core/src/managed/artifactDetail/EnvironmentCards.tsx
app/scripts/modules/core/src/managed/artifactDetail/MarkArtifactAsBadModal.tsx
app/scripts/modules/core/src/managed/artifactDetail/PinArtifactModal.tsx
app/scripts/modules/core/src/managed/artifactDetail/PinnedCard.tsx
app/scripts/modules/core/src/managed/artifactDetail/PreDeploymentStepCard.tsx
app/scripts/modules/core/src/managed/artifactDetail/UnpinArtifactModal.tsx
app/scripts/modules/core/src/managed/artifactDetail/VersionStateCard.tsx
app/scripts/modules/core/src/managed/artifactDetail/constraints/constraintRegistry.tsx
app/scripts/modules/core/src/managed/artifactDetail/verifications/VerificationCard.tsx
app/scripts/modules/core/src/managed/artifactsList/ArtifactsList.tsx
app/scripts/modules/core/src/managed/environment/EnvironmentRow.tsx
app/scripts/modules/core/src/managed/managedResourceDecorators.ts
app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
app/scripts/modules/core/src/managed/toggleResourceManagement.tsx
app/scripts/modules/core/src/managed/tsconfig.json

I added a `tsconfig.json` file to `managed`. We can't run and enforce it during compilation (unfortunately) as we'll have to fix all of the imports from other folders. However, it allows us to enforce null checking via the IDE. 
It's not perfect, but it's a start. 
Another option is to add the config file to `gitignore`, and use it only for local dev, but I'm not sure it's better. 
@erikmunson can you review this briefly and make sure I didn't do anything stupid?

chore(md): Enable TS strict null check in MD (only in IDE)

---

app/scripts/modules/core/src/notification/NotificationsList.tsx
app/scripts/modules/core/src/notification/modal/EditNotificationModal.tsx

**Current Behavior**
1. In application config the user clicks add/edit notification and a modal opens
2. The user makes changes and clicks "Update" in the modal, which updates the pipelin config locally
3. The modal closes
4. The user also has to click "Save" to persist these changes on the BE
Have to click and "Update" and "Save" often leads to confusion. The users will "Update" via teh modal then navigate away from the page before actually persisting the new information. The current user flow makes more sense for the pipeline and stage notifications, so this PR only updates the user flow for application-level notifications.
**New Behavior**
1. In application config the user clicks add/edit notification and a modal opens
2. The user makes changes and clicks "Update" in the modal, which …

feat(core/notifications): Save app notifications when modal is submitted

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/amazon/src/subnet/SubnetSelectField.tsx

- Do not show this warning for subnets when this component is rendered in the LB create flow. 
- Update logic to verify if subnet is recommended.

fix(amazon): Update logic for subnet warning

---

app/scripts/modules/amazon/src/serverGroup/details/sections/SecurityGroupsDetailsSection.tsx

Simplify security group extraction by removing [redundant logic ](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/model/AmazonServerGroup.groovy#L111)from Deck.

fix(aws): Simplify security group extraction

---

app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.spec.ts
app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupLoadBalancers.tsx
app/scripts/modules/core/src/serverGroup/configure/common/serverGroupCommandBuilder.service.ts

When we switch between regions or accounts, the ui validates that the requested load balancers/target groups exist in the new account/region.  If the new region/account doesn't have the load balancer, it's removed from the UI and a message is shown.  However, spel expressions are treated differently and are never removed.  
This change moves the UI state from the command object to the viewState object so these values are not sent to the server

fix(amazon/serverGroup): Move spelLoadBalancers and spelTargetGroups to viewState

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx

Some older, partially-deprecated AMIs are having trouble with IPv6. This PR prevents auto-enabling IPv6 if  an image is listed as `disabled` (i.e. almost deprecated).  A user can still manually enable this option in Advanced Settings.

fix(amazon): Do not automatically assign IPv6 for disabled images

---

app/scripts/modules/docker/src/image/DockerImageAndTagSelector.tsx

This just adds a nasty `unmounted` kludge to all the async setState codepaths

fix(docker): DockerImageAndTagSelector.tsx: do not setState when unmounted

---

app/scripts/modules/core/src/forms/mapEditor/MapEditor.less
app/scripts/modules/core/src/forms/mapEditor/MapEditor.tsx
app/scripts/modules/core/src/forms/mapEditor/MapEditorInput.tsx
app/scripts/modules/core/src/forms/mapEditor/MapPair.css
app/scripts/modules/core/src/forms/mapEditor/MapPair.tsx

Before:
Note the entire modal is scrolling down all the way to the last `position: absolute` element (which is from the `class="sr-only"` bootstrap screenreader only css class)

fix(core/forms): MapEditor: make trash icon position: relative to avoid scrollbars

---

app/scripts/modules/core/src/pipeline/executions/execution/ExecutionBreadcrumbs.tsx

The `parentExecutions` was `useMemo`'d with an empty deps array `[]` which means it is never invalidated.
This meant that when navigating from child to child to child, the parentExecutions never got recomputed and certain parts of the lineage would be missing.

fix(pipelines): Add deps to breadcrumbs useMemo

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json

35215bcbfbc7efd25124a2e5623aae5bf9fc939b Merge branch 'master' into disable-ipv6-images
eb4394f8f97bb7958a23c75f3f40cd00111317b6 fix(amazon/serverGroup): Move spelLoadBalancers and spelTargetGroups to viewState (#8957)
84bd0f1f5ae5c6301be067b715284d91eb55c6cc Use native .some instead of lodash
36b7feca2dde7defd6ea1acfb7378044d7c62300 fix(amazon): Do not automatically assign IPv6 for disabled images
3d0ddbd9b97be84d87b8e1439e38383ccb116f93 fix(md): remove beta tag (#8968)
765499fdadec89131359bc089e4a9c090368eb14 fix(pipelines): Add deps to breadcrumbs useMemo (#8967)
4c02d1c5bdc051e20c6a8e5a0f785b82c637822a fix(pr): added explicit log level (#8966)
273966d86d1cefe35378c842a3a334e03f5fd606 fix(core/forms): MapEditor: make trash icon position: relative to avoid scrollbars (#8964) …

chore(package): amazon@0.0.294 core@0.0.553 docker@0.0.69

---

app/scripts/modules/core/src/bootstrap/SpinnakerContainer.tsx
app/scripts/modules/core/src/header/SpinnakerHeader.tsx
app/scripts/modules/core/src/overrideRegistry/Overridable.tsx
app/scripts/modules/core/src/overrideRegistry/Overrides.tsx
app/scripts/modules/core/src/overrideRegistry/override.registry.ts

React function components cannot use decorators, so the dev experience hasn't been ideal using `@Overridable` as we try and move toward function components. (the `OverridableComponent` renders a wrapper class component, which renders a functioning function component). 
This ended up being mostly a Typescript update, but now we can utilize the existing `overrideableComponent` function to produce an HOC, which is a better pattern for function components. 
What is in this PR:
- type updates
- A new function `overridesComponent` that is equivalent to the `@Overrides` decorator, but can be used for function components
- An example of utilizing `overrideableComponent` to create an HOC

feat(core): Allow function components to be overridden

---

packages/pluginsdk/scaffold/src/WidgetizeStage.tsx

On newer versions of Spinnaker the `Widgetize` stage that is provided by the scaffold command no longer works OOB. I've added the required fields on the stage itself and verified this works in 1.24.
I also noticed that `check-plugin` and `check-peer-deps` aren't running successfully on first scaffold, but they do when you have `check-plugin` fix unmet deps after initial scaffold. I won't fix that in this PR, but may in an upcoming PR.

chore(pluginsdk): fix scaffold tmpl for newer spinnaker versions

---

app/scripts/modules/core/src/application/application.state.provider.ts
app/scripts/modules/core/src/history/recentHistory.service.ts
app/scripts/modules/core/src/search/infrastructure/RecentlyViewedItems.tsx

Before, the recent applications list would link you to the deepest link in that view.  Now it links to the default route, i.e., http://spinnaker/#/applications/appname
Also refactored RecentlyViewedItems.tsx to a functional component cause I was in there

Always link to /applications/appname from the recent applications list

---

app/scripts/modules/core/src/presentation/forms/inputs/ReactSelectInput.tsx

This PR allows the ReactSelectInput to use the `react-select` 1.x `Creatable` component which allows you to type an arbitrary value and hit Enter, even if it's not an existing option in the list.

feat(core/presentation): add `mode="CREATABLE"` to the ReactSelectInput

---

app/scripts/modules/amazon/src/instance/details/InstanceStatus.tsx
app/scripts/modules/core/src/instance/details/index.ts

- export `ConsoleOutputLink`
- make key on `InstanceLoadBalancerHealth` unique to avoid console warnings (warning appears when target group and load balancer have similar names)

fix(core): Export ConsoleOutputLink

---

app/scripts/modules/core/src/presentation/forms/layouts/StandardFieldLayout.tsx

... to align formfield actions on the right hand side
This fixes a StandardFieldLayout problem where form actions were not being lined up on the right hand side:
This change justifies the horizontal layout putting space between the input and actions.
Most of the time this wasn't an issue, but the `NumberInput` sets a max-width and so doesn't flex to fill the entire available space.

fix(core/presentation): Change standard field layout flex to  justify-content: space-between

---

app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.less
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/TitusMapLayout.less
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/TitusMapLayout.tsx

Two commits: 
1) Migrate to Spinnaker Forms
2) Migrate validation to ValidateForm and validate Environment Variables.
Some notes re: the Forms migration:
- I wired up a `TitusMapLayout` to mimic the existing layout of the titus deploy stage with the form input label as a header above the `MapEditor`
- Extracted some [FormInputs](https://github.com/spinnaker/deck/blob/abbce18f6221146d13889df3e3edc5f0c96b6c4e/app/scripts/modules/core/src/presentation/forms/README.md#inputs) to their own components
- ServiceJobProcesses: this is a checklist, but the known list of options is augmented with the values in the existing stage JSON
- IPv6Checkbox: `'true'`/`undefined` values when checked/unchecked
- IamInstanceProfile: Shows the account and "apply default" button

Validate Titus Environment Variables

---

app/scripts/modules/appengine/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

9038090a1e7a80341cf10a2dc71bea4c8e22c804 fix(appengine/docker): Allow save the Artifact in the Pipeline JSON f… (#8961)
9a5ea31abf82e014c4a603fbfa12a50a1f2dd117 chore: eslint --fix (#9015)
b286fd65f8f87c651dfd5518249a6c65502e56ba fix(titus/serverGroup): allow underscores in the first character of environment variables (#9016)
9a5ea31abf82e014c4a603fbfa12a50a1f2dd117 chore: eslint --fix (#9015)

chore(package): appengine@0.0.28 core@0.0.558 titus@0.0.166

---

app/scripts/modules/core/src/pipeline/executions/execution/Execution.tsx

Just buying some more vertical screen real estate by having parameters collapsed instead of expanded by default on initial render.
This is only for the ancestor executions. For the main execution, it will still be expando by default

fix(pipeline): Collapse parameters in ancestry

---

.git-blame-ignore-revs

TIL you can ignore specific revisions in `git blame` output.  These revs can be stored in a file, then you can configure git to read the ignore list from the file.
`git config blame.ignoreRevsFile .git-blame-ignore-revs`
This is pretty great, because I'm regularly seeing sweeping code reformat commits when I do a `git blame`.  I want to determine the intention/history of some code but the reformats get in the way.
---
Before -- notice much of the changes are attributed to "Just Use Prettier" reformatting commit:
After -- the code is attributed to the previous committer:

feat(git): Add a .git-blame-ignore-revs file

---

app/scripts/modules/core/src/projects/projects.states.ts

When following a link to the recently used project, we now always link to `home.project` which will redirect to the project dashboard.

fix(core/projects): Recent projects: only save the link to project dashboard

---

app/scripts/modules/core/src/managed/artifactsList/ArtifactsList.tsx

The PR removes the depends-on icon from the artifact versions list (the example below is showing MJ). I'm not a fan of remove only this constraint, as it creates inconsistency in user expectations but we will deal with it later.

fix(md): remove depends-on icon from the artifacts list

---

package.json

This makes the eslint rules run first, then the prettier reformat.  Some eslint rule fixers will leave the source code in a un-pretty format, so let's run prettier AFTER eslint --fix.

chore: update commit hook to run eslint first, then prettier

---

app/scripts/modules/amazon/package.json
app/scripts/modules/azure/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/titus/package.json

0ff5c18c3fb947800460d32241e8b31d6720c760 test: fix typing errors introduced by stricter types in updated @types/jasmine package
84e4fe6b24592c9bbb65fe45339ccf2a930b2c50 test: switch some imports to `import type` to eliminate certain warnings during karma runs
d58cb46d9559c0c83e7642e0eb79687f9887e586 refactor(amazon/serverGroup): Delete unused metricAlarmChart angularjs component
0861d2dcd07135c45c8e3baf54b0ccdebff9ae6e feat(amazon/serverGroup): Replace angular metric-alarm-chart with react MetricAlarmChart
802cb2eea59c858fc4cb216325b6ae78a0cd9aef feat(amazon/serverGroup): Introduce MetricAlarmChart.tsx using Chart.js
807830424a51219b7aecf2cf7240039237e5a7af test: fix usage of httpMock
ecbd4e2e96066a00dc85ac2cc7302dcc6f16b7e2 test: remove async/done combination which is now deprecated …

chore(package): amazon@0.0.298 azure@0.0.266 core@0.0.563 ecs@0.0.279 titus@0.0.168

---

packages/pluginsdk-peerdeps/package.json
packages/pluginsdk/package.json
packages/pluginsdk/pluginconfig/rollup.config.js
packages/pluginsdk/scaffold/package.json
packages/pluginsdk/scripts/check-plugin/linters/lint.package.json.js

Lots of new build tooling features in this release of pluginsdk
- feat(pluginsdk): support sharing libraries (i.e., react) with commonjs plugin dependencies
- feat(pluginsdk): support importing JSON files via rollup
- feat(pluginsdk): add support for replacing literal process.env.NODE_ENV with the current environment variable value
- feat(pluginsdk): Emit bundle size stats when ROLLUP_STATS environment variable is set
- feat(pluginsdk): Minify the plugin bundles when NODE_ENV is 'production' or ROLLUP_MINIFY is 'true'
- feat(pluginsdk): support importing content from html/svg/png/jpg/gif
- chore(pluginsdk-peerdeps): release 0.0.11
- chore(pluginsdk): release 0.0.25

pluginsdk enhance

---

app/scripts/modules/amazon/src/domain/IAmazonHealth.ts
app/scripts/modules/core/src/instance/details/index.ts
app/scripts/modules/titus/src/index.ts
app/scripts/modules/titus/src/instance/details/TitusInstanceDetails.tsx
app/scripts/modules/titus/src/instance/details/index.ts
app/scripts/modules/titus/src/instance/details/titusInstanceDetailsUtils.spec.ts
app/scripts/modules/titus/src/instance/details/titusInstanceDetailsUtils.ts
app/scripts/modules/titus/src/titus.module.ts

This PR completes the Titus instance details react migration. What this PR includes:
- **`TitusInstanceDetails`** - This component captures all common behavior. It fetches, transforms and passes all needed information to the presentational `TitusInstanceDetailsContent` component.  It will also show any error or loading states.
- **`OverridableTitusInstanceDetailsContent`** - This is mainly a presentational component composed of different instance details sections. It is meant to be overridden and augmented with custom behavior or collapsible sections. 
- **`utils`** to help generate common instance information.
- `extractHealthMetrics` - Gets all displayable metrics, and augments health metrics with additional data
- `buildTaskActions` - Returns an array of actions based on the health …

feat(titus): Finish migrating instance details to react

---

app/scripts/modules/titus/src/serverGroup/configure/ServerGroupCommandBuilder.js
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx

**Before:** 
The container attribute `titusParameter.agent.assignIPv6Address`, did not exist if IPv6 wasn't needed.
**After:**
The container attribute will exist and be `false` if the user states that IPv6 isn't needed. 
**Why**
After this PR, if I user has explicitly interacted with IPv6, the value will be `true` or `false`. If they haven't interacted with this config, it will be `null`, and the backend can make some inferences about when to automatically assign an IPv6. 
For now this is based on the `test` environment, but more rules will be added as the rollout progresses. Eventually, this will just default to `true` for everything.

feat(titus): Update logic for auto-assigning IPv6 to containers

---

app/scripts/modules/core/src/pipeline/status/ExecutionUserStatus.tsx

This is simply not true.
Especially for executions triggered by a pipeline trigger without a runAs user, they are in actuality executing as anonymous, but we incorrectly display them as being run with the same auth as the parent.
Additionally, we should rely on front50/echo/orca to propagate these from parent to child rather than infer them in deck.

fix(pipeline): Do not infer user from parent

---

app/scripts/modules/core/src/widgets/notifier/Notifier.tsx
app/scripts/modules/core/src/widgets/notifier/notifier.component.less
app/scripts/modules/core/src/widgets/notifier/notifier.service.ts
package.json
yarn.lock

API changes: 
- Removed the `body` option as it wasn't in use (verify that)
- Added an `options` field for react toastify option

feat(core): updated notifications to react-toastify

---

app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/targetTracking/upsertTargetTracking.modal.html
app/scripts/modules/titus/src/serverGroup/details/scalingPolicy/targetTracking/upsertTargetTracking.modal.html

I missed this when switching from c3 to chart.js.

fix(titus/serverGroup): Fix height of metrics line chart

---

app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.titus.controller.js

Server groups with no instances have an empty key/pair `{ "": "" }`. This causes validation issues in the UI when a user wants to clone an empty server group. 
To fix, the empty key/pair is deleted where the other labels are deleted.

fix(titus/serverGroup): Remove empty key/pairs from job attributes

---

package.json
yarn.lock

kayenta 1.0.4 bundles its own copy of rxjs 5.x
this is in prep for migrating deck to rxjs 6 in https://github.com/spinnaker/deck/pull/9113

chore: update to kayenta 1.0.4

---

app/scripts/modules/core/src/instance/details/console/ConsoleOutputModal.tsx

We were hitting issues testing this out in 2.26 and this resolve the failed behavior we were seeing

fix(core): fix issue in console log modal

---

app/scripts/modules/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx
app/scripts/modules/core/src/help/help.contents.ts
app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx

Add help field for Titus and AWS Ipv6 field in server group settings.

feat(aws/titus): Add help text to IPv6 field

---

app/scripts/modules/amazon/src/function/details/FunctionActions.tsx
app/scripts/modules/amazon/src/loadBalancer/details/LoadBalancerActions.tsx
app/scripts/modules/amazon/src/securityGroup/details/securityGroupDetail.html
app/scripts/modules/amazon/src/serverGroup/details/AmazonServerGroupActions.tsx
app/scripts/modules/cloudfoundry/src/serverGroup/details/cloudFoundryServerGroupActions.tsx
app/scripts/modules/core/src/entityTag/AddEntityTagLinks.tsx
app/scripts/modules/core/src/entityTag/addEntityTagLinks.component.ts
app/scripts/modules/core/src/entityTag/entityTags.module.ts
app/scripts/modules/core/src/reactShims/ngReact.ts
app/scripts/modules/ecs/src/serverGroup/details/serverGroupDetails.html
app/scripts/modules/google/src/loadBalancer/details/loadBalancerDetails.html
app/scripts/modules/google/src/securityGroup/details/securityGroupDetail.html
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.html
app/scripts/modules/kubernetes/src/loadBalancer/details/details.html
app/scripts/modules/kubernetes/src/securityGroup/details/details.html
app/scripts/modules/kubernetes/src/serverGroup/details/details.html
app/scripts/modules/kubernetes/src/serverGroupManager/details/details.html
app/scripts/modules/titus/src/serverGroup/details/serverGroupDetails.html

- Convert `AddEntityTagLinks` to React
- remove dependency on `NgReact` for injected component
- import entity tag help text into `entityTags.module`

refactor(core): Convert AddEntityTagLinks to React

---

app/scripts/modules/amazon/package.json
app/scripts/modules/cloudfoundry/package.json
app/scripts/modules/core/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/google/package.json
app/scripts/modules/kubernetes/package.json
app/scripts/modules/titus/package.json

39fa77303b75ca6e5b0af96d1e011bcff452cede refactor(core): Convert AddEntityTagLinks to React (#9147)
bf89842715ac05cf09e888a24643560f95f536d2 fix(aws): Avoid showing an incorrect 'EC2 Classic' subnet (#9151)
7499271c1eb45f88aae3265a48f7e9148bf5d3ea feat(aws/lb): Internal ALBs can be dualstacked (#9144)
01aef56e4d9d645caa7f82a814b4b9be5d5d5ae1 feat(aws/titus): Add help text to IPv6 field (#9139)
39fa77303b75ca6e5b0af96d1e011bcff452cede refactor(core): Convert AddEntityTagLinks to React (#9147)
70a2b9985d947216ac3c2559232eff9eb5b49ded refactor(core/serverGroup): Convert running tasks popover to react (#9152)
39fa77303b75ca6e5b0af96d1e011bcff452cede refactor(core): Convert AddEntityTagLinks to React (#9147)
7499271c1eb45f88aae3265a48f7e9148bf5d3ea feat(aws/lb): Internal ALBs can be …

chore(package): amazon@0.0.305 cloudfoundry@0.0.117 core@0.0.574 ecs@0.0.283 google@0.0.37 kubernetes@0.0.63 titus@0.0.175

---

app/scripts/modules/core/src/pipeline/config/triggers/MetadataPageContent.tsx

Current behavior in 1.26 breaks the description field for users that attempt to use the tags feature introduced in this release

fix(core): fix state update for pipeline tags

---

app/scripts/modules/core/src/utils/classnames.d.ts
app/scripts/modules/core/src/utils/index.ts
package.json
yarn.lock

- Removed an old `classname` package that no one used
- Removed the empty `classnames` types file
- Added `classnames` to deps

fix(core): classnames package cleanup

---

tsconfig.base.json

In order to convert deck to a mono-repo, we need to make each spinnaker package independently specify their dependencies and make them self-sufficient. The foundational build changes are completed now and in this PR, a base `tsconfig` file is created which will be used by these packages.
NOTE: This PR is pulling just the `tsconfig.base.json` file from https://github.com/spinnaker/deck/pull/9185

feat(build): Add base tsconfig for independent packages

---

app/scripts/modules/amazon/src/serverGroup/configure/AmazonImageSelectInput.tsx
app/scripts/modules/amazon/src/serverGroup/details/sections/LaunchTemplateDetailsSection.spec.tsx
yarn.lock

`@types/react` was set to `16.8.0`, but many of the dependencies were using `16.0.40` due to how yarn set up the dependencies in the first run. So fixing that to point to `16.8.0` and also fixing a few typescript issues that cropped up.

fix(dependency): Fix @types/react version

---

packages/scripts/helpers/rollup-plugin-angularjs-template-loader.js

The existing pattern missed cases like `require('../foo/bar.html')`

fix(build): Fix condition to handle html requires

---

app/scripts/modules/github_actions_publish.sh

Since the packages are independent now, they need to install their dependencies before running `npm publish`.

fix(build): Fix package publish github actions

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/ecs/package.json
app/scripts/modules/titus/package.json

494add310c89f2cfbb88b3b8bf9380e2d6c82c7a feat(amazon/serverGroup): export datelinechart and MetricAlarmChart (#9211)
6c3838eca864a816d16e435b0856ef9b13e9a443 refactor(amazon): Make amazon package independent
d62bd8cb141035ea3b8590625cd8cf8d92c45700 fix(md): fix order of environments (#9207)
7791003a487a2f261db0c3f9af32e2081773f3dc feat(md): show error message if there are no artifacts or resources (#9205)
edec92b4860e53e43b9dc4fd613af98fc5450eac fix(core/pipeline): Warn if concurrency disabled on stage restart (#9143)
5561db048f69d671225521a00fd2aeb5442fc6b6 fix(lint): Fix lint errors
5a4247fb146a96820fbcd5346b8c80ecbfe30bb2 refactor(docker): Make docker package independent
5a4247fb146a96820fbcd5346b8c80ecbfe30bb2 refactor(docker): Make docker package independent …

chore(package): amazon@0.0.308 core@0.0.581 docker@0.0.73 ecs@0.0.285 titus@0.0.178

---

packages/scripts/config/rollup.config.base.module.js
packages/scripts/package.json

`rollup-plugin-auto-external` plugin doesn't automatically take care of imports like `rxjs/operators`, so explicitly adding it to list of externals here.

fix(build): Add rollup externals

---

app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx

When no current version exists, we didn't order the versions and the backend returned the versions in the wrong order

fix(md): sort versions even when no current exists

---

app/scripts/modules/core/src/managed/overview/artifact/Constraints.tsx

The previous query worked only for the overview page while this fetches the version itself and therefore works for all views

fix(md): refetch version on constraint action (works in all cases)

---

app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx

environments are now sorted on the backend. We only need to reverse the order in the history heading

fix(md): order of environments 2

---

app/scripts/modules/amazon/package.json
app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/amazon/yarn.lock
app/scripts/modules/docker/package.json
app/scripts/modules/docker/src/docker.module.ts
app/scripts/modules/docker/yarn.lock
app/scripts/modules/titus/package.json
app/scripts/modules/titus/yarn.lock
packages/scripts/config/rollup.config.base.js
packages/scripts/package.json
packages/scripts/yarn.lock

`@rollup/plugin-url` only takes care of bundling images that are directly imported from ts/js files and ignores images that are imported from css files. So adding this new postcss plugin to handle bundling of images specified in css files.
Additionally, this ensures that we do not rely on postcss.config.js to be present in the directory.
NOTE: The `inline` option is chosen rather than `copy` since the latter expects the `assetPath` to be provided and rewrites the `url(..)` patterns with that asset path. This is not ideal since these assets will be moved over to a different location when bundled with a distribution like `deck-nflx` and will result in 404s.

fix(build): Handle image bundling from css

---

app/scripts/modules/core/src/managed/AbsoluteTimestamp.tsx
app/scripts/modules/core/src/managed/RelativeTimestamp.tsx
app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentItem.tsx
app/scripts/modules/core/src/managed/overview/artifact/Artifact.less
app/scripts/modules/core/src/managed/overview/artifact/Artifact.tsx
app/scripts/modules/core/src/managed/overview/artifact/ArtifactVersionTasks.tsx
app/scripts/modules/core/src/managed/overview/artifact/CurrentVersion.tsx
app/scripts/modules/core/src/managed/overview/artifact/GitLink.less
app/scripts/modules/core/src/managed/overview/artifact/GitLink.tsx
app/scripts/modules/core/src/managed/overview/artifact/PendingVersion.tsx
app/scripts/modules/core/src/managed/overview/artifact/utils.ts
app/scripts/modules/core/src/managed/overview/baseStyles.less
app/scripts/modules/core/src/managed/utils/defaults.ts
app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.less
app/scripts/modules/core/src/managed/versionMetadata/VersionMetadata.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
app/scripts/modules/core/src/managed/versionsHistory/types.ts
app/scripts/modules/core/src/presentation/main.less

This PR is based on #9206.
Commit 5bde855 adds the pinned data and switches to the white hoverable tooltip
Commit 2d8b7c9 switches back to the black tooltip with a relative timestamp. I'm keeping the commit separate because I haven't decided which tooltip is better. 
Commit ab7cc04 moves the pinned data to a separate row to make it more prominent.
Bonus: use relative time instead of absolute

feat(md): pinned data tooltip info

---

app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/Environments2.less
app/scripts/modules/core/src/managed/Environments2.tsx
app/scripts/modules/core/src/managed/managed.states.ts
app/scripts/modules/core/src/managed/versionMetadata/MetadataComponents.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionHeading.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.less
app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx
app/scripts/modules/core/src/managed/versionsHistory/types.ts
app/scripts/modules/core/src/presentation/main.less
app/scripts/modules/core/src/utils/clipboard/CopyToClipboard.tsx

This PR includes two features:
- Share button to copy a link to a specific version
- Expand and scroll to a version based on the `sha` query params.
What's missing?
Linking to /reference/version to support the existing notification links (@christopherthielen, I'd love to get your help with that)

feat(md): History - scroll to version + share link

---

packages/scripts/helpers/rollup-plugin-angularjs-template-loader.js
packages/scripts/index.js
packages/scripts/package.json
packages/scripts/yarn.lock

Handling a couple of improvements to build tooling.
- Angular template URLs across different packages share similar names (such as `./findAmiStage.html`) between `titus` and `amazon`, and this leads to issues when both these packages are imported into deck. This commit fixes it by expanding the identifier for the template to include the spinnaker package name.
- In the new setup with individual spinnaker packages, it becomes harder to manage linking packages. This adds a new capability where `yalc` is used internally to automatically push updated builds to packages that link spinnaker packages.

feat(scripts): Improve build tooling

---

app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.html
app/scripts/modules/core/src/pipeline/config/stages/pipeline/pipelineStage.js

Rollup has some trouble bundling ng templates that have string interpolation token `${` in them. So fixing it by removing some occurrences in `core`.

fix(core): Remove string interpolation token from ng template for rollup

---

app/scripts/modules/core/src/core.module.ts

- Move all css imports to the top of `core.module.ts`.
- Replace `require`s with `imports` since imports also seem to guarantee the order in which files are bundled together.
All the above changes will make it easier to move to rollup.

fix(core): Re-order imports and remove requires

---

app/scripts/modules/core/src/pipeline/details/stageExecutionDetails.less

I think this was a side effect of the navigation overhaul from last summer. It inadvertently added a bunch of padding around the tabs in the stage details section.
Currently, it looks like this:
With this PR, it looks like this, which is what I think it looked like before:
This is minor (guessing nobody else noticed and it's been like this for ~11 months now) and CSS is a nightmare, so it's understandable it broke.

fix(style): shrink padding on stage details tabs

---

app/scripts/modules/amazon/src/serverGroup/details/sections/multipleInstanceTypesSubSection.less
app/scripts/modules/core/src/pipeline/config/stages/templates/index.ts
app/scripts/modules/titus/src/serverGroup/configure/serverGroupConfiguration.service.ts

There's some issues when migrating packages to have their own dependency and using rollup. This fix is going to make it smoother to introduce rollup and other changes in a much simpler PR.

refactor(build): Fix paths for rollup

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/titus/package.json

9a9468a2e1da465d5b95ae996395f4e59b116a09 refactor(build): Fix paths for rollup
bf5e954eb4aba329b50a1a85894a1df26763a86f feat(md): moved createdAt to the metadata instead of on the left (#9279)
9a9468a2e1da465d5b95ae996395f4e59b116a09 refactor(build): Fix paths for rollup
915b3421b9a7070cad57ac8612406df5b71ad38c feat(md): added logs to the important actions and events (#9281)
2917d7b5de10488bc8df20d2f1db71dc60413316 fix(md): allowed time default timezone (#9280)
8524b0eafee5a4fe238ae6a233752de89ab399ec fix(md): only show git link if the commit message is not a link (#9278)
8b1e1f8e9724ed8fd726e8bd1687c109d5e495c9 feat(md): show resource account in metadata (#9277)
23103b0d66333ffc2cedecd38a249d16fabf34af style(md): add spacing above the actions if there is a description (#9276) …

chore(package): amazon@0.0.315 core@0.0.590 titus@0.0.183

---

app/scripts/modules/core/src/managed/managed.states.ts

The previous solution was dropping the application param and therefore failed to work in some cases

fix(md): properly redirect the old ui links to the new ui

---

app/scripts/modules/core/rollup.config.js

Depends on https://github.com/spinnaker/deck/pull/9295
The `core` package has some unique characteristics that need a custom rollup config file rather than using the generic one from `@spinnaker/scripts`. This includes
- copying over typescript definition files
- defining an alias mapping for `root`
- a plugin to fix typescript's path auto-rewrites.

feat(build): Add custom rollup config for core

---

app/scripts/modules/core/src/managed/environmentBaseElements/EnvironmentsRender.tsx
app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
app/scripts/modules/core/src/managed/graphql/schema.graphql
app/scripts/modules/core/src/managed/overview/EnvironmentOverview.tsx
app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
app/scripts/modules/core/src/managed/overview/queries.graphql
app/scripts/modules/core/src/managed/versionsHistory/VersionContent.tsx
app/scripts/modules/core/src/presentation/hooks/useDimensions.hook.ts
graphql.schema.json
package.json
yarn.lock

This PR adds support for preview environments on the overview page. 
To do that, I refactored the code a bit and added `useOrderedEnvironment` to handle the sorting better. 
I also renamed the directions to `DIRECTIONS = ['listView', 'gridView']`. This means that users will have to set their setting again, but it's not a big deal imo...

feat(md): Preview environments v0

---

packages/scripts/config/rollup.config.base.module.js
packages/scripts/package.json
packages/scripts/yarn.lock

There's some webpack related code in spinnaker packages that are still needed as the codebase is being migrated, but needs to be stripped when bundled through rollup, so adding support for that.

feat(build): Add support for stripping during bundling

---

app/scripts/modules/core/src/managed/ApplicationQueryError.tsx
app/scripts/modules/core/src/managed/Environments.tsx
app/scripts/modules/core/src/managed/UnmanagedMessage.tsx
app/scripts/modules/core/src/managed/config/Configuration.tsx
app/scripts/modules/core/src/managed/overview/EnvironmentsOverview.tsx
app/scripts/modules/core/src/managed/versionsHistory/VersionsHistory.tsx

I originally wanted to consolidate this error handling to the `Environments` component, but I had some issues with removing the `UIView`, and this solution gives us more flexibility anyway. We might want to revisit it again in the future

feat(md): improve error handling for non-managed applications

---

app/scripts/modules/bumpPackage.js

Adding a temporary utility script that shall be used to bump packages to the latest version across all spinnaker packages until lerna migration is complete.

feat(build): Add utility for package bumps

---

packages/scripts/config/rollup.config.base.js
packages/scripts/package.json

Having `[dirname]` specified in the output `filename` puts the asset in a new directory named `[dirname]` under the `dist` folder. This gets copied over to the bundled output in netflix's deck distribution, but doesn't get served correctly. In this commit, this is changed so that the asset is emitted directly under `dist` folder.
The `limit` is also increased to allow inlining of images for plugins.

fix(build): Emit assets directly to dist folder

---

app/scripts/modules/amazon/package.json
app/scripts/modules/core/package.json
app/scripts/modules/docker/package.json
app/scripts/modules/titus/package.json

db9f47df6eae4e87319586721c1dc95cc86290a9 chore(bump): Upgrade @spinnaker/scripts
db9f47df6eae4e87319586721c1dc95cc86290a9 chore(bump): Upgrade @spinnaker/scripts
78497fd7e1f948e2310e3588aa7e5b606c337677 feat(md): remove loadingIndicator.svg and use Spinner instead (#9338)
db9f47df6eae4e87319586721c1dc95cc86290a9 chore(bump): Upgrade @spinnaker/scripts
db9f47df6eae4e87319586721c1dc95cc86290a9 chore(bump): Upgrade @spinnaker/scripts

chore(package): amazon@0.0.319 core@0.0.599 docker@0.0.80 titus@0.0.187

---

app/scripts/modules/azure/src/azure.module.ts
app/scripts/modules/azure/src/securityGroup/configure/CreateSecurityGroupCtrl.js
app/scripts/modules/azure/src/securityGroup/configure/EditSecurityGroupCtrl.js
app/scripts/modules/azure/src/serverGroup/configure/serverGroupCommandBuilder.service.js
app/scripts/modules/azure/src/serverGroup/configure/wizard/CloneServerGroup.azure.controller.js
app/scripts/modules/azure/src/serverGroup/configure/wizard/tags/tagsSelector.directive.js
app/scripts/modules/azure/src/serverGroup/details/serverGroupDetails.azure.controller.js
app/scripts/modules/azure/src/serverGroup/serverGroup.transformer.js
app/scripts/modules/google/src/serverGroup/details/serverGroupDetails.gce.controller.js
app/scripts/modules/tencentcloud/src/search/searchResultFormatter.js

The build tooling is now changed to rollup and we now prefer using imports over requires for modules. So updating the existing call sites that still use requires.

fix(imports): Convert requires to imports

---

app/scripts/modules/core/src/utils/Logger.ts

This allows us to ignore noisy ghost errors, such as the resize observer errors.
More details: https://stackoverflow.com/a/50387233/5737533

fix(logging): ignore noisy errors

---

app/scripts/modules/core/src/managed/constraints/registry.tsx

Since the `allowed-times` constraint is now stateful, you can override the judgment. This PR adds a little button to the constraint to let you ignore the window. 
Wording options:
`Ignore time window`
`Skip time window`
`Override time window`
`Skip constraint`
Here is what it looks like when it's visible, and when it was overridden.

feat(md): ignore allowed-time window

---

app/scripts/modules/core/src/confirmationModal/ConfirmModal.tsx
app/scripts/modules/core/src/entityTag/EntityTagEditor.tsx
app/scripts/modules/core/src/modal/wizard/WizardModal.tsx
app/scripts/modules/core/src/pagerDuty/PageModal.tsx
app/scripts/modules/core/src/task/index.ts
app/scripts/modules/core/src/task/modal/TaskMonitorModal.tsx

- Exports `TaskMonitorWrapper`
- Moves `core` imports of this component from NgReact to the new import

chore(core): Export TaskMonitorWrapper

---

app/scripts/modules/core/src/modal/buttons/SubmitButton.tsx

Fixing this issue: 
Adding `flex-container-h` directly to the `button` really messes up all the angular modal footers. Instead I made a new container within the button that allows the button to be flex and the footer to be compatible with the rest of the modal.

fix(core/modal): Make SubmitButton compatible with flex display

---

app/scripts/modules/core/src/help/HelpField.tsx

Some instances of the angular rendered `help-field` were rendering no matter what. This helps with angular compatibility.

fix(core/help): Do not render conditionally for angular compatibility

---

app/scripts/modules/app/webpack.config.js
build.gradle
test/functional/package.json

- Webpack build output is now shifted back to the top level from `app/scripts/modules/app` to make sure other tooling that relies on this path is not broken.
- Updated gradle build script to run npm commands rather than directly invoking node scripts. This makes it easier to make changes in package json file and have them working in gradle automatically.

fix(build): Fix gradle builds

---

app/scripts/modules/core/src/diffs/ChangesModal.tsx
app/scripts/modules/core/src/diffs/ViewChangesLink.tsx

- Fix NPE when `changeConfig.metadata` is null
- Add flex style to modal
- Hide build numbers when they are missing

fix(core/diffs): NPE on ViewChangesLink, minor style tweak

---

app/scripts/modules/core/src/managed/config/ManagementWarning.tsx
app/scripts/modules/core/src/managed/messages/Messages.tsx

The previous implementation was showing the bottom border even when there is no warning

fix(md): only show messages section if not empty

---

app/scripts/modules/amazon/src/aws.module.ts
app/scripts/modules/appengine/src/appengine.module.ts
app/scripts/modules/azure/src/azure.module.ts
app/scripts/modules/core/src/core.module.ts
app/scripts/modules/ecs/src/ecs.module.ts
app/scripts/modules/google/src/gce.module.ts
app/scripts/modules/kubernetes/src/kubernetes.module.ts
app/scripts/modules/oracle/src/oracle.module.ts
app/scripts/modules/tencentcloud/src/tencentcloud.module.ts
app/scripts/modules/titus/src/titus.module.ts
packages/scripts/config/rollup.config.base.module.js
packages/scripts/package.json
packages/scripts/yarn.lock

Ng template caching was needed for webpack when building locally. But now that all packages are migrated to use workspaces, `app` now depends on the build outputs of each package instead which already contains template cache built using rollup.
So removing custom template building for webpack along with removing custom strip code used in rollup.

chore(all): Remove ng template cache for webpack

---

app/scripts/modules/core/src/core.module.ts
app/scripts/modules/core/src/reactShims/react.ga.ts

We weren't loading ReactGA and relied on angular. As a result, we also skipped subscribing GA to the main logger. 
This means that we load GA twice now - in React and Angular - but it should cause any issues afaik.

fix(core): properly load ReactGA 

---

app/scripts/modules/app/package.json

After moving to yarn workspaces, resolutions in app's package.json is no longer necessary.

fix(app): Remove resolutions from app

---

app/scripts/modules/core/src/managed/ManagedReader.ts
app/scripts/modules/core/src/managed/config/DeliveryConfig.tsx

The new endpoint returns the delivery config from the app repo instead of the one processed by keel

feat(md): Display the raw delivery config instead of the processed one

---

.github/workflows/ci.yml

With the integration of yarn workspaces, spinnaker package builds are done as part of 'Production Build' github action already and 'Build Packages' action is redundant.

feat(build): Remove 'Build Packages' action in github ci

---

app/scripts/modules/core/src/managed/graphql/graphql-sdk.ts
app/scripts/modules/core/src/managed/graphql/schema.graphql
app/scripts/modules/core/src/managed/overview/Resource.tsx

Adds a new `MdResourceActuationStatus` and corresponding icon to represent a resource currently being deleted.

feat(managed-delivery): Add resource deleting status and icon

---

scripts/assert_package_bumps_standalone.sh
scripts/buildModules.js
scripts/build_order.sh
scripts/github_actions_publish.sh

- Removing temporary switch that turned off assertions in `assert_package_bumps_standalone.sh`.
- Some fixes to `build_order.sh` and `github_actions_publish.sh`

fix(scripts): Fix build scripts

---

packages/amazon/src/securityGroup/details/securityGroupDetail.controller.js

The `body.modal-open` class was not being applied to the angular Edit Security Group modal because it was competing with the React MD confirmation modal. This caused the z-index of everything to be thrown off after the user pauses management. 
The fix is a hack that forces a 500ms wait so the react modal actually closes before the angular one opens. We use this hack for both MD managed Titus and AWS server groups. 
**Problem**

fix(amazon/securityGroup): Resolve angular/react modal-body conflict

---

packages/amazon/src/serverGroup/configure/wizard/pages/advancedSettings/ServerGroupAdvancedSettingsCommon.tsx

Small PR to change IMDSv2 verbiage from "Enable IMDSv2" to "Require IMDSv2"
Context: IMDSv2 is already enabled by default on EC2 instances. Requiring IMDSv2 prevents legacy IMDSv1 calls from being made.

chore(verbiage): Change verbiage from 'Enable IMDSv2' -> 'Require IMDSv2'

---

.github/workflows/release-please.yml

Release please doesn't support creation of two PRs from the same source branch (master).  I created two aliases to the master branch: `release-please-app` and `release-please-tools` to allow release please to open two separate PRs.
These aliases are [git symbolic refs](https://git-scm.com/docs/git-symbolic-ref) created with the following commands:
```
git symbolic-ref refs/heads/release-please-app refs/heads/master
git symbolic-ref refs/heads/release-please-tools refs/heads/master
git push upstream release-please-app
git push upstream release-please-tools
```

fix(release-please): use separate source branch names for app and tools (git symbolic-ref refs/heads/release-please-app refs/head/smaster)

---

.github/release-please-config.json
.github/release-please-config.tools.json
.github/release-please-manifest.json
.github/release-please-manifest.tools.json
.github/workflows/release-please.yml

I couldn't get release-please to generate separate PRs for app packages (core/amazon/kubernetes, etc) and tooling (eslint-plugin, plugins, etc)

feat(release-please): Consolidate all releases into a single PR

---

app/scripts/modules/app/src/canary/canary/canaryScore.component.less
packages/core/src/config/VersionChecker.tsx
packages/core/src/modal/modalPage.directive.js
packages/core/src/pipeline/config/stages/deploy/deployExecutionDetails.controller.js
packages/core/src/utils/json/JsonUtils.ts
packages/core/src/widgets/spelText/spelText.decorator.js
packages/dcos/src/search/resultFormatter.js
packages/oracle/src/pipeline/disableAsg/disableAsgStage.js

As we are slowly migrating towards using `vite` as our dev server, we need to convert all our existing require calls to imports.

fix(all): Convert requires to imports

---

packages/scripts/helpers/rollup-plugin-angularjs-template-loader.js

While using rollup plugins with vite, the files are first transpiled using esbuild and then passed to plugin transformation. It looks like esbuild converts single quotes to double quotes in require calls and that breaks the rollup plugin.

fix(scripts): Handle double quotes in require calls

---

app/scripts/modules/app/CHANGELOG.md
app/scripts/modules/app/package.json
packages/titus/CHANGELOG.md
packages/titus/package.json

**Note:** Version bump only for package @spinnaker/titus
---
This Pr bumps each package to the next semver version (patch/minor/major) based on the commit messages of unpublished changes using [Conventional Commits](https://conventionalcommits.org).
- fix: patch release
- feat: minor release
- BREAKING CHANGE: major release
It also updates dependency versions in other packages in the monorepo which depend on the bumped package(s).
After this PR is merged, Github Actions will publish any bumped packages to the NPM registry.
_Auto-generated by `.github/workflows/package-bump-pr.yml`_

Publish packages to NPM

---

app/scripts/modules/app/package.json
app/scripts/modules/app/vite.config.js
packages/scripts/helpers/rollup-plugin-angularjs-template-loader.js
yarn.lock

Enabling the ideal dev experience where linked app packages such as `core` are treated as source files by `vite` instead of relying on the package specific build output. 
Also adding `react-refresh` and `svgr` plugins to enable HMR, SVG imports.
NOTE: Only `core` is handled in this commit. Other packages will be included later once `core` is made to work without any issues.

fix(vite): Link app to core source files during dev

---

.github/workflows/package-bump-pr.yml

- not sure why actions/checkout@v2 isn't checkout master already ?

fix(publishing): checkout master explicitly.  do not try to close PR when no PR was matched by create-pull-request.

---

packages/core/src/application/service/applicationDataSource.ts
packages/core/src/cloudProvider/providerSelection/ProviderSelectionModal.tsx
packages/core/src/cluster/filter/ClusterFilterService.ts
packages/core/src/function/filter/FunctionFilterService.ts
packages/core/src/loadBalancer/filter/LoadBalancerFilterService.ts
packages/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx
packages/core/src/modal/wizard/WizardModal.tsx
packages/core/src/modal/wizard/WizardStepLabel.tsx
packages/core/src/orchestratedItem/orchestratedItem.transformer.ts
packages/core/src/overrideRegistry/Overridable.tsx
packages/core/src/overrideRegistry/Overrides.tsx
packages/core/src/pipeline/config/services/PipelineConfigService.ts
packages/core/src/pipeline/config/stages/common/AsgActionExecutionDetailsSection.tsx
packages/core/src/pipeline/config/stages/common/ExecutionBarLabel.tsx
packages/core/src/pipeline/config/triggers/artifacts/custom/CustomArtifactEditor.tsx
packages/core/src/pipeline/config/triggers/artifacts/singleFieldArtifactEditor.tsx
packages/core/src/pipeline/details/stageSummary.component.ts
packages/core/src/pipeline/executions/execution/ExecutionMarkerInformationModal.tsx
packages/core/src/pipeline/filter/executionFilter.service.ts
packages/core/src/plugins/plugin.registry.ts
packages/core/src/presentation/TabBoundary.tsx
packages/core/src/presentation/collapsibleSection/CollapsibleSection.tsx
packages/core/src/task/TrafficGuardHelperLink.tsx
packages/core/src/task/monitor/TaskMonitorError.tsx
packages/core/src/task/monitor/TaskMonitorStatus.tsx
packages/core/src/widgets/ApplicationsPickerInput.tsx

Removing circular dependencies in `core` module to ensure deck loads correctly via `vite`. There are some more occurrences left that aren't affecting deck yet but may need to get fixed soon.

fix(core): Remove circular dependency of modules

---

packages/core/src/managed/overview/ResourceTask.tsx

No reason to show the progress bar and the current stage if the task is completed and has a checkmark next to it.

fix(md): hide completed task status and progress bar if completed

---

packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/StepPolicyAction.less
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/StepPolicyAction.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/awsStepPolicyAction.component.ts
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/stepPolicyAction.component.ts
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.html

A few temporary changes with this PR that are not my favorite but necessary to rollout smoothly. 
1.  **Dual components until `@spinnker/amazon` is bumped and the new component can be imported elsewhere.** 
`awsStepPolicyAction.component.ts` - the old controller that is just renamed. It will be removed after updating other modules
`stepPolicyAction.component.ts - the new `react2angular wrapper` for `ScalingPolicyAction.tsx`
2. **Dual updates in `ScalingPolicyAction.tsx`**
The propagation of changes via props between the angular parent and new React component takes several seconds. To avoid this delay in rendering, I had to add `useState` for each input. This will be removed once the parent component refactored/optimized.

refactor(amazon/scalingPolicy): Reactify step policy actions

---

packages/azure/src/loadBalancer/details/loadBalancerDetail.html
packages/azure/src/serverGroup/configure/wizard/loadBalancers/ServerGroupLoadBalancers.controller.js
packages/azure/src/serverGroup/configure/wizard/loadBalancers/serverGroupLoadBalancersSelector.directive.html
packages/azure/src/serverGroup/configure/wizard/networkSettings/ServerGroupNetworkSettingsSelector.directive.html

Azure health settings can be placed directly on scale sets. If client-
side load balancing (e.g. through Eureka) is used, a load balancer
is not necessary.
This change is dependent on https://github.com/spinnaker/clouddriver/pull/5494.
**Testing done**:
1. Modified an existing pipeline to remove load balancer
2. Modified pipeline from 1) to re-add load balancer
3. Created a new pipeline without a load balancer
4. Created a new pipeline with a load balancer

feat(provider/azure): Allow empty load balancer for Azure scale sets

---

packages/app/src/app.ts

It looks like Azure did not survive [this move](https://github.com/spinnaker/deck/commit/69ff222cecb35572b8e6df8aaaa4c6e2872dbb4b) on 6/24. This change registers the azure module in `app.ts`.
Trying to do anything on an Azure provider will result in this error:
```
Error: No "serverGroup.commandBuilder" service found for provider "azure"
at ProviderServiceDelegate.getDelegate (index.js:1025)
at ServerGroupCommandBuilderService.getDelegate (index.js:1832)
at ServerGroupCommandBuilderService.buildServerGroupCommandFromPipeline (index.js:1832)
at Object.editCluster (index.js:4258)
at fn (eval at compile (angular.js:1), <anonymous>:4:360)
at callback (angular.js:27956)
at Scope.$eval (angular.js:18796)
at Scope.$apply (angular.js:18895)
at HTMLAnchorElement.eval (angular.js:27961)
at …
```

fix(provider/azure): Re-expose Azure provider in deck

---

packages/azure/src/loadBalancer/configure/advancedSettings.html
packages/azure/src/loadBalancer/configure/createLoadBalancer.controller.js
packages/azure/src/loadBalancer/loadBalancer.transformer.js

Azure released App Gateway v2 which allows certs from key vault. In order to take advantage of this, allow the user to select v2 or v1 (Standard_Small) skus from the UI.
This change is dependent on https://github.com/spinnaker/clouddriver/pull/5510.
**Screenshots**:
**Testing Done**:
1. Tested (together with changes in deck) the following:
1. Modify existing v1-sku App Gateways
2. Create new v1-sku App Gateways
3. Create new v2-sku App Gateways
4. Delete v1-sku App Gateways
5. Delete v2-sku App Gateways
6. Deploy to v1-sku App Gateway
6. Deploy to v2-sku App Gateway

feat(provider/azure): Allow specifying App Gateway sku

---

packages/amazon/src/subnet/SubnetSelectField.tsx
packages/amazon/src/subnet/SubnetSelectInput.spec.tsx
packages/amazon/src/subnet/SubnetSelectInput.tsx
packages/titus/src/serverGroup/configure/wizard/pages/ServerGroupBasicSettings.tsx
packages/titus/src/titus.settings.ts

- Migrates AWS `SubnetSelectInput` to functional component
- `SubnetSelectInput` now uses the default subnet any time the account/region is changed
- Adds support to Titus for default subnet types (merges with AWS default subnet type)
- Adds support to Titus for recommended subnet types

Titus: Support default subnets

---

packages/core/src/serverGroup/details/scalingActivities/ScalingActivitiesModal.tsx

Removes the "0" when there are no scaling activities:
(I still make this mistake at least once a month)

fix(core): do not show "0" when no scaling activities detected

---

packages/core/src/pipeline/config/stages/deploy/deployStage.js
packages/core/src/pipeline/config/validation/imageProviderBeforeType.validator.ts

Expanding the `imageProviderBeforeType` validator to check for any find image stages.

feat(core): Expand Image Provider validation to find image stages

---

packages/amazon/src/serverGroup/details/scalingPolicy/ScalingPolicyWriter.ts
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/ScalingPolicyAdditionalSettings.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.controller.js
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.html
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/upsertScalingPolicy.modal.less

Creates a component with the additional settings section of the step scaling policy modal. This component will be used for both AWS and Titus.

refactor(amazon): Scaling policy additional settings

---

packages/core/src/modal/buttons/submitButton.component.ts

This only affects old-timey Angular submit buttons. The React ones look fine.
Before:
After:

fix(style): keep submit button status indicator inline with label

---

packages/amazon/src/serverGroup/details/scalingPolicy/index.ts
packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/TargetTrackingAdditionalSettings.tsx

This component is not used anywhere yet. It will work for both Amazon and Titus `UpsertTargetTrackingModals` once they are converted to React.

refactor(amazon): Additional settings for target tracking policies

---

packages/amazon/src/domain/IAmazonServerGroup.ts
packages/amazon/src/serverGroup/details/scalingPolicy/chart/MetricAlarmChart.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/MetricSelector.tsx

Fallback to `awsAccount` if cloudprovider is not `aws`.

fix(amazon): Use account or awsAccount for cloud metrics reader

---

packages/core/src/pipeline/details/SingleExecutionDetails.tsx
packages/core/src/pipeline/service/execution.service.ts

We were indiscriminately fetching `pipelineConfig`s on `getExecution` even though we might already have it locally under the `pipelineConfigs` data source.
This especially hurts when running `mergeRunningExecutionsIntoExecutions` doesn't find an `isActive` execution in the `runningExecutions` data source so it decides to fetch it individually (multiplied by the number of running executions that weren't found):
https://github.com/spinnaker/deck/blob/d28eac29c463069358e8c07413a56b290af9f7ce/packages/core/src/pipeline/service/execution.service.ts#L403-L409
This became especially apparent today when I saw an app with 71 running executions making 71 requests to refresh those executions where another 71 fetches for pipelineConfigs (many duplicate as there are only 5 unique).
Why were so many …

fix(pipelines): Reduce pipelineConfig fetches

---

packages/amazon/src/serverGroup/details/scalingPolicy/chart/MetricAlarmChart.tsx

It turns out that only some server groups have `cloudProvider` set, but they all have `type` set. This fixes an error where the incorrect parameter was being passed to the `CloudMetricsReader`.

fix(amazon): Scaling policy data fetch failure from undefined cloud provider

---

packages/app/tsconfig.json

I moved this from app/scripts/modules/app  to packages/app a bit ago.  I just noticed that this config used (basically) all the same settings as `tsconfig.app.base.json`

chore(app): make packages/app/tsconfig.json extend ../tsconfig.app.base.json

---

packages/core/src/cloudProvider/CloudProviderLogo.tsx
packages/core/src/cloudProvider/CloudProviderRegistry.ts

I happened to be in these files and noticed that they could be simplified
- refactor(core/cloudProvider): use lodash get/set path functions
- refactor(core/cloudProvider): replace the no-longer-necessary Providers class with a plain old Map
- fix(core/cloudProvider): remove unused ICloudProviderLogoState interface

lil cloudprovider refactors

---

packages/core/src/utils/clipboard/CopyToClipboard.tsx

In an edge case, `text` prop was a boolean (from the webhook stage). This would bypass defaulting the prop to an empty string, and cause `text.replace()` to fail.

fix(core): Ensure text is string in CopyToClipboard

---

packages/titus/src/serverGroup/configure/wizard/pages/disruptionBudget/JobDisruptionBudget.tsx

When the disruption budget policy is self managed, there is really no requirement for the budget to contain any of the rate or container health fields, so while the UI will add them in, users may have also previously configured the budget with something as minimal as:
```
"disruptionBudget": {
"selfManaged": {
"relocationTimeMs": 3600000
}
},
```
Thus, deck should be able to deal with their absence.

fix(titus): Deal with absence of non-required fields

---

packages/amazon/src/aws.module.ts
packages/amazon/src/serverGroup/details/scalingPolicy/StepPolicySummary.less
packages/amazon/src/serverGroup/details/scalingPolicy/StepPolicySummary.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/alarmBasedSummary.template.html
packages/amazon/src/serverGroup/details/scalingPolicy/index.ts
packages/amazon/src/serverGroup/details/scalingPolicy/popover/AlarmSummary.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/popover/StepPolicyPopoverContent.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/scalingPolicy.module.ts
packages/amazon/src/serverGroup/details/scalingPolicy/stepPolicySummary.component.ts
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/alarm/AlarmConfigurer.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/upsert/index.ts

- `StepPolicyContent` and `StepPolicySummary` components
- Utilize components in `@spinnaker/amazon`
- Register upsert modals with cloud provider so `StepPolicySummary` can be used across providers
- temporary `react2angular` converter until parent is converted to react

refactor(amazon): Step Policy popover and details

---

packages/core/package.json
packages/core/src/core.module.ts
yarn.lock

Bumping select2 dependencies to versions that are in NPM. I couldn't get an answer on why these are currently fixed at Git tags, so please let me know if you know why.

chore(deps):  bump select2 to npm versions

---

packages/core/src/config/settings.ts
packages/core/src/pipeline/triggers/QuietPeriodBadge.tsx
packages/core/src/pipeline/triggers/TriggersTag.tsx
packages/core/src/pipeline/triggers/useQuietPeriod.hook.ts

Previously,  quiet periods start/end ranges were configured in Echo and in Deck settings.js.  Now, deck fetches the current quiet period date range from Echo via Gate.  The Deck feature flag is still used to toggle "respectQuietPeriod" on and off in a pipeline config.

feat(core/pipeline): Load quiet period configuration from Gate, not from SETTINGS

---

packages/core/src/pipeline/details/StageFailureMessage.tsx

The ternary as written would allow a singleton list containing a single
`null` to propagate throughout the render method of this warning
message. This would result in a menacing "warning: no reason provided"
message appearing on all stage executions.
The assignment now states that a singleton list will only be provided
iff `message` is non null and the `messages` array is empty.

fix(core): ensure that users are not warned of their success

---

docker/spinnaker.conf.gen
docker/spinnaker.conf.ssl
packages/app/index.deck
packages/app/src/settings.js
packages/app/webpack.config.js
packages/core/src/bootstrap/angular.config.ts

This adds configuration to enable HTML5 (aka path-based, not hash-based) routing for Deck.
The default remains unchanged, and is still hash-based.
To enable this feature:
- Add `window.spinnakerSettings.feature.html5Routing = true;` to your `settings-local.js` file.
- Or, set `HTML5_ROUTING=true` in your Deck container, in whichever way you prefer.

feat(core): HTML5 Routing

---

packages/cloudfoundry/src/pipeline/stages/runJob/cloudFoundryRunJob.module.ts

Account extractor is [supposed to return an array](https://github.com/spinnaker/deck/blob/554367925d9111c88e04610adb1097236ce48646/packages/core/src/domain/IStageTypeConfig.ts#L10) but this stage returns a string, which breaks the execution history parsing in Deck.

fix(cf): return credentials in an array

---

packages/scripts/config/rollup.config.base.js
packages/scripts/package.json
yarn.lock

`rollup-plugin-esbuild` changed their exports in version 4.6.0, which meant any plugin that didn't explicitly pin it to `4.5.0` would fail to build. Bumping the version and fixing the import allows builds to succeed.
Thanks to @vigneshm for helping find the issue!

fix(scripts): update rollup-plugin-esbuild

---

packages/core/src/application/config/applicationAttributes.directive.html

Applications in the config view always show up as unconfigured, fix the
broken reference to the controller so applications properly display
their attributes.
https://github.com/spinnaker/deck/blob/master/packages/core/src/application/config/applicationAttributes.directive.js#L31

fix(core): apps always display as unconfigured

---

packages/core/package.json
packages/core/src/application/nav/navAtoms.ts
packages/core/src/cache/collapsibleSectionStateCache.ts

Introduce an atom effect which is registering as a listener to CollapsibleSectionStateCache. If there is a listener for the key, the handler function will be called to update the atom value

feat(core): Synchronize the verticalNavExpandedAtom using an atom effect

---

packages/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

This line `defaults: { account?: string; region?: string; subnet?: string; mode?: string } = {}` was not creating an empty object when `buildNewServerGroupCommand()` was being called, causing `defaults` to be `null` and break the whole function. 
This adds the manual check and sets `defaults` to empty `{}`if it's null or undefined.

fix(aws): Fix Create Server Group button

---

packages/core/package.json
packages/core/src/pipeline/config/graph/PipelineGraph.tsx
packages/core/src/pipeline/config/services/PipelineConfigService.ts
packages/core/src/pipeline/config/stages/stage.html
packages/core/src/pipeline/config/stages/stage.module.js

Change how the downstream stages are computed: 
- In the current implementation, the recursive method `PipelineConfigService.getDownstreamStageIds` filtered the complete stages list on every call. The process was slow when dealing with many stages and links between them. 
- With my implementation, I group the list of stages into a `map`. The map's key is the child ref id, and the value is an array containing the child's parents. 
With this approach, retrieval/searching is much faster than the list filtering on each call of the recursive function. 
I also decided to memoize the result of the getDependencyCandidateStages (in stage.module.js). I did it because the method is called four times (with the same input) when clicking on a stage.

perf(pipelinegraph): Improve the performance of the pipeline graph rendering 

---

scripts/gha_bump_packages.sh
scripts/gha_common.sh
scripts/gha_output_bumped_packages.sh
scripts/gha_output_changelog.sh

The script logged an error,
> ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', or 'prerelease'.
Testing locally found this was because the commit message had the word publish in it and lerna was trying to treat it as a command.
Quoting all variables resolved the issue locally.

chore(gha): Fix bump packages script

---

packages/core/src/pipeline/config/stages/stage.html

Small change:
* Changed `ui-select` property from "onselect" to "on-select". This was changed about a month ago and seems to cause stage configurations to not render when a new stage is selected. Based on the ui-select documentation the actual property is meant to be "on-select" and this is likely what caused it to break.
Similarly, ui-select tags use "on-select" everywhere else in the repo.
Example:

Fix(core/pipelines): Fix syntax error on ui-select causing stage configuration to not load

---

packages/presentation/package.json
yarn.lock

Bumping Formik in Presentation module to address Lodash vulnerability
See:
https://snyk.io/vuln/SNYK-JS-LODASH-567746
Note:
Other modules might also have this vulnerability, but I had difficulty patching them due to Formik migrating to functional components and it interfering with usage of SpinFormik component in other modules (I'm not very prolific in front-end). However, this is not the case in the presentation module. 
If anyone fancys giving that a go at least in the core module that would be much appreciated!

chore(dependencies): Updating Formik in @spinnaker/presentation

---

packages/app/index.deck
packages/core/src/bootstrap/angular.config.ts

The previous change to enable optional path-based routing (#9802) added a `<base>` tag, which regressed serving hash-based routing at non-root public paths.
This change returns to AngularJS's default behavior when using hash-based routing.  Note that path-based routing will continue to only function when served from a domain root.
Resolves spinnaker/spinnaker#6723

fix(core): Do not set static document base URL

---

packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.spec.tsx
packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.tsx
packages/kubernetes/src/rolloutStrategy/bluegreen.strategy.ts
packages/kubernetes/src/rolloutStrategy/index.ts

Introduce blue/green strategy as this is a terminology used more often in the industry compared to the Neflix-specific phrasing Display a warning label if red/black is selected from the dropdown
**Red/Black** selection displays a warning label and **blue/green** is selected instead
For any other selection, there is no warning label displayed
Relates to: 
https://github.com/spinnaker/clouddriver/pull/5811
https://github.com/spinnaker/orca/pull/4332
https://github.com/spinnaker/front50/pull/1176

feat(kubernetes): Introduce blue/green traffic management strategy

---

package.json
yarn.lock

We noticed our deck builds started to fail with the following error in the tests:
```
Chrome Headless 78.0.3882.0 (Linux x86_64) ERROR
An error was thrown in afterAll
Uncaught TypeError: Cannot read property 'Tag' of undefined
TypeError: Cannot read property 'Tag' of undefined
at eval (webpack:///./node_modules/domhandler/lib/node.js?:32:35)
at Object../node_modules/domhandler/lib/node.js (/tmp/_karma_webpack_700123/commons.js:15444:1)
at __webpack_require__ (/tmp/_karma_webpack_700123/runtime.js:85:30)
at eval (webpack:///./node_modules/domhandler/lib/index.js?:19:14)
at Object../node_modules/domhandler/lib/index.js (/tmp/_karma_webpack_700123/commons.js:15432:1)
at __webpack_require__ (/tmp/_karma_webpack_700123/runtime.js:85:30)
at eval …
```

fix(dependencies): Pin correct cheerio version

---

packages/kubernetes/src/pipelines/stages/deployManifest/DeployManifestStageForm.tsx
packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.spec.tsx
packages/kubernetes/src/pipelines/stages/deployManifest/ManifestDeploymentOptions.tsx
packages/kubernetes/src/pipelines/stages/traffic/ManifestTrafficStageConfig.tsx

Add warning label for Deployment kind. 
Add Deployment in kind dropdown for enable/disable manifest stage.
…manifest stage
Screenshots bellow:
Deployment
ReplicaSet

feat(Blue/Green): Add warning label and enhance disable/enable manifest stage with Deployment kind.

---

packages/core/src/help/help.contents.ts
packages/core/src/pipeline/config/stages/pipeline/pipelineStage.html

The https://github.com/spinnaker/orca/pull/3989 introduced a flag to opt-out from passing outputs to child executions. 
However, Deck does not provide any option to select this flag from the UI. 
This PR adds a new checkbox to select if skipping the output from child pipelines in the pipeline stage config settings.
The checkbox is disabled by default for backward compatibility and the field `skipDownstreamOutput` is not set unless the user selects the checkbox.

feat(core/pipeline): Add missing flag `skipDownstreamOutput` in pipeline stage

---

packages/core/src/widgets/accountNamespaceClusterSelector.component.js
packages/core/src/widgets/accountRegionClusterSelector.component.js

After the upgrade to Angular 1.8 in #9836, the account/regions/cluster picker was missing (e.g. in the Scale Down Cluster stage and the Resize Server Group stage). Quick fix was to wrap the existing controller code in an `$onInit` function.

fix(core): Missing config elements after Angular 1.8 update

---

packages/ecs/src/ecs.module.ts

ECS deployments don't need a Bake or Find Image from Resource stage upstream, so don't show an error that one is required.

fix(ecs): skip checking for upstream stages for ECS deploy

---

packages/core/src/pipeline/config/graph/PipelineGraph.tsx

This change prevents iterating over child nodes as it has already been checked and as a result greatly reduces the number of interactions and increases speed.

fix: UI crashes when running pipeline(s) with many stages.

---

packages/core/src/region/regionSelectField.directive.js
packages/dcos/src/job/general.component.js
packages/dcos/src/job/labels.component.js
packages/dcos/src/job/schedule.component.js
packages/google/src/autoscalingPolicy/components/metricSettings/metricSettings.component.js
packages/google/src/autoscalingPolicy/components/scalingSchedules/scalingSchedules.component.js
packages/google/src/loadBalancer/configure/http/backendService/backendService.component.js
packages/google/src/loadBalancer/configure/http/basicSettings/basicSettings.component.js
packages/google/src/loadBalancer/configure/http/healthCheck/healthCheck.component.js
packages/google/src/loadBalancer/configure/http/hostRule/hostRule.component.js
packages/google/src/loadBalancer/configure/http/listeners/listener.component.js
packages/google/src/loadBalancer/details/loadBalancerType/loadBalancerType.component.js

Fixing the missed bindings from https://github.com/spinnaker/deck/pull/9836
Reference https://github.com/spinnaker/deck/pull/9936

fix(angular): fix missed AngularJS bindings

---

packages/ecs/src/serverGroup/configure/wizard/networking/Networking.tsx

In the initial state, when a new application was created and when the user is trying to create a Server group for ECS Instance, the credentials related to the aws account and the state of the subnet in the code were not updating properly and returning as undefined. As a result during the filtering of the subnet types, we are getting empty array [] as the output, which is causing the issue for the VPC subnets drop down while creating the server group.
https://github.com/spinnaker/deck/assets/61963157/6bff6865-b9f7-434f-b272-920fd210fe7b
https://github.com/spinnaker/deck/assets/61963157/eaf3a877-a8c0-4cde-b1b6-2362175a558e

fix(ecs): VPC Subnet dropdown fix in ecs server group creation.

---

.github/workflows/package-bump-pr.yml

The upgrade to actions/github-script in https://github.com/spinnaker/deck/pull/9962 broke the package bump PR action. Breaking change in the README here https://github.com/actions/github-script#breaking-changes-in-v5.

chore(build): fix package bump PR action

---

packages/core/src/pipeline/config/actions/PipelineConfigActions.tsx

Click on any option dropdown from pipeline action not closing properly Pipeline builder screen . Closing outside the popup only close the dropdown.
https://github.com/spinnaker/deck/assets/61963157/831ead5b-6648-44eb-a939-4b1bd4731dcd
https://github.com/spinnaker/deck/assets/61963157/3670565a-83a8-4985-8eb1-1c5c4605dfac

fix(core/pipeline): Pipeline builder-pipeline action dropdown closing not properly

---

packages/presentation/src/icons/Icon.tsx
packages/presentation/src/types/svg.d.ts

Enables plugins to use the Icon component with a custom icon.
Currently the Icon component is limited to only icons defined in iconsByName.

feat(icons): allow plugins to provide custom icon components

---

packages/core/src/artifact/ArtifactIconService.ts
packages/core/src/artifact/ArtifactTypes.ts
packages/core/src/domain/IArtifact.ts
packages/core/src/manifest/ManifestYaml.tsx
packages/core/src/pipeline/config/stages/bakeManifest/BakeManifestDetailsTab.tsx
packages/core/src/pipeline/config/stages/bakeManifest/utils/getBakedArtifacts.ts
packages/core/src/pipeline/config/stages/bakeManifest/utils/getContentReference.ts
packages/core/src/pipeline/config/triggers/artifacts/ArtifactService.ts
packages/core/src/pipeline/index.ts

/artifacts/content-address/{reference} is a new API that allows for requests to be made to get full artifacts.
Also adds support for new artifact type of remote/base64

feat(artifacts): Add support for artifact store views and calls

---

packages/amazon/package.json
packages/appengine/package.json
packages/azure/package.json
packages/cloudfoundry/package.json
packages/cloudrun/package.json
packages/core/package.json
packages/docker/package.json
packages/ecs/package.json
packages/eslint-plugin/package.json
packages/google/package.json
packages/huaweicloud/package.json
packages/kubernetes/package.json
packages/mocks/package.json
packages/oracle/package.json
packages/pluginsdk-peerdeps/package.json
packages/pluginsdk/package.json
packages/presentation/package.json
packages/scripts/package.json
packages/tencentcloud/package.json
packages/titus/package.json
yarn.lock

Deck project in master is not able to publish packages to NPM due to `cloudrun` is consider private package. [GHA failing](https://github.com/spinnaker/deck/actions/runs/6235062087/job/16923496957). As we are not publishing all the packages I start seeing build issues in master for deck.
To avoid this problem I set the access level in the `package.json` for each library publish to NPM registry.
Once we merge this change we need to publish packages again to validate and ensure latest changes are publish correctly to NPM registry.

fix(publish): set access config in deck libraries

---

packages/amazon/src/function/configure/FunctionBasicInformation.tsx

Having the Lambda available Runtimes defined in 2 places creates a drift between what is available in the deploy stage vs what it is available for manual creation of a Lambda function through the Functions tab.

fix(lambda): available Runtimes shared between Deploy stage and Functions tab

---

packages/amazon/src/function/configure/FunctionBasicInformation.tsx

Updating Functions available runtimes to match the OSS Lambda plugin ones

fix(functions): Updating Lambda functions available Runtimes to match the Lambda plugin runtimes

---

packages/amazon/src/serverGroup/details/scalingPolicy/upsert/step/StepPolicyAction.tsx
packages/amazon/src/serverGroup/serverGroup.transformer.spec.ts

Follow up to https://github.com/spinnaker/deck/pull/10026
It is necessary to add the standard HTML `step` prop in `NumberInput` to allow floats as inputs.

fix(amazon): Allow scaling bounds to use floats between input steps

---

packages/core/src/domain/IOrchestratedItem.ts
packages/core/src/orchestratedItem/orchestratedItem.transformer.ts
packages/core/src/presentation/CollapsibleElement.tsx
packages/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/DeployStatus.less
packages/kubernetes/src/pipelines/stages/deployManifest/manifestStatus/DeployStatus.tsx

In the context of the deploy manifest stage, numerous failure messages are currently consolidated into a single message, rendering the information less user-friendly. This is primarily attributed to the necessity of scrolling through the lengthy message and attentively discerning where one exception concludes and another commences. The proposed resolution in this pull request involves segregating failure messages into distinct blocks. For a more comprehensive understanding of this enhancement, kindly refer to the attached video demonstration.
https://github.com/spinnaker/deck/assets/106548537/b8886a99-bcda-4044-a869-2267b211539f

feat: Split deployment failure messages.

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Only used for Gradle, as we're not actually compiling any Java here.

feat(java17): use Java 17

---

packages/amazon/src/pipeline/stages/deployCloudFormation/CloudFormationChangeSetInfo.tsx

https://github.com/spinnaker/spinnaker/issues/6889
When you use the "Deploy (CloudFormation Stack)", the default name for the CloudFormation ChangeSet is invalid, this prevents the stage from succeeding.
n/a
n/a
Amazon -> "Deploy (CloudFormation Stack)"
The default CloudFormation changeSet name has a space in it and is invalid. The code is on [this](https://github.com/spinnaker/deck/blob/8c112bbe6c1a5298eb7c69b6f09927413c8affbb/packages/amazon/src/pipeline/stages/deployCloudFormation/CloudFormationChangeSetInfo.tsx#L16) line:
```
(stage as any).changeSetName ? (stage as any).changeSetName : "ChangeSet-${ execution['id']}",
```
Notice there is a space before "execution" in the `ChangeSetName`: `ChangeSet-${ execution['id']]"`
This is an invalid name and the pipeline fails.  Without the …

fix(deck/cloudformation): Invalid default name for CloudFormation changeSet

---

packages/ecs/src/ecs.help.ts
packages/ecs/src/serverGroup/configure/serverGroupCommandBuilder.service.js
packages/ecs/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.component.html

This is my first contribution, and I tried to implement https://github.com/spinnaker/spinnaker/issues/6225
This change comes together with this PR from clouddriver: https://github.com/spinnaker/clouddriver/pull/6132
It implements a new checkbox to activate ECS Deployment Circuit Breaker for the ECS service; the default is false to not change any existing behavior.
The checkbox looks like this. I thought it should go under "Advanced settings".
If enabled, it adds the attribute `enabledDeploymentCircuitBreaker` to the server group:
Running the Deploy stage will create an ECS service with Deployment Circuit Breaker enabled:
I'm open for your comments and your thoughts, also on the implementation - I mainly "mimicked" how other attributes/feature were implemented and tried my best …

feat(ecs): Add support for ECS deployment circuit breaker

---

packages/core/src/pipeline/config/stages/wait/waitStage.ts

I think, It is necessary to make Wait stage restartable, because if you cancel release pipeline, while Wait Stage is running, you won't be able to restart pipeline where it stopped, you will be forced to restart pipeline from the very beginning.
Before:
After:

Make Wait Stage restartable

---

packages/core/src/manifest/stage/JobStageExecutionLogs.tsx

After the deletion of the runjob (for any reason) Deck instead of persisting the External system link for the logs it falls back to the default Console Output.
Since the user is linking the logs of a Runjob to an external system it makes sense that the link for the previous executions should persist in Deck. 
Fixes this old issue: https://github.com/spinnaker/spinnaker/issues/5717

fix(runJobs): Persist External Log links after the deletion of the pods

---

packages/core/src/pipeline/config/services/PipelineConfigService.ts

Deck prior to 1.27.x was rendering the pipelines when the first stages didnt have defined the requisiteStageRefIds. 
Although this was not ideal it allowed users to template their first stages without the key. After the pipelineGraph updates this is causing an exception and breaking the rendering of the pipelines causing issues to users upgrading.
With this fix it is checked if the key is not defined and defaulting it to a empty array.

fix(pipelineGraph): Handling exception when requisiteStageRefIds is not defined

---

packages/amazon/src/pipeline/stages/invokeLambda/components/InvokeLambdaOperation.tsx

Lambda Invoke Stage after the implementation of the remote/base64 as an artifact type is not including the embedded-artifact account in the expected artifacts since the REMOTE_BASE64 artifact type was not added in the except list.
Before the change:
After the change:

fix(lambda): Invoke stage excludedArtifactTypes not including the embedded-artifact type

---

packages/core/src/pipeline/config/stages/overrideTimeout/OverrideTimeout.tsx
packages/core/src/pipeline/config/validation/PipelineConfigValidator.ts

Deck is throwing an exception when stageTimeoutMs is templated with a Spel Expression although Orca can handle the evaluation during runtime. 
This PR fixes the exception in Deck and also modifies the validator to accept a Spel expression. 
Before the change: 
After the change: 
Recording with a pipeline that uses input with Spel to determine the stageTimeoutMs:
https://github.com/spinnaker/deck/assets/28927773/8f550f45-e2b4-4abf-8ee6-ff6a9fe8c182

fix(pipeline): Handle render/validation when stageTimeoutMs is a Spel expression

---

packages/amazon/src/aws.module.ts

After the Lambda import to OSS the lambda stages where not correctly exported through the module. This was fixed by https://github.com/spinnaker/deck/pull/10085 but i missed the LambdaRoute stage.

fix(lambda): Export LambdaRoute stage on aws module

---

packages/google/src/loadBalancer/configure/common/sessionAffinityNameMaps.ts

Although STRONG_COOKIE_AFFINITY is a beta feature for GCP LB adding it to the model as an option.
Related clouddriver PR https://github.com/spinnaker/clouddriver/pull/6259

chore(gcp): Adding STRONG_COOKIE_AFFINITY in gcp LB model

---

packages/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

Fixes issue [6771](https://github.com/spinnaker/spinnaker/issues/6771).

fix(aws): Fix userData getting lost when cloning an AWS server group that uses launch templates (#6771)

---

packages/amazon/src/serverGroup/configure/serverGroupCommandBuilder.service.ts

This is a fix for [#6979](https://github.com/spinnaker/spinnaker/issues/6979).
The IPv6 checkbox was previously checked when it should not have been.
This line:
```
associateIPv6Address: shouldAutoEnableIPv6 || Boolean(ipv6AddressCount),
```
Was casting the entire object below to Boolean, which ALWAYS resulted in a value of `true`:
```json
[
{
"deviceIndex": 0,
"groups": [
"sg-0a1a8a45acf3192b8"
],
"ipv4Prefixes": [],
"ipv6AddressCount": 0,
"ipv6Addresses": [],
"ipv6Prefixes": [],
"privateIpAddresses": []
}
]
```
The change casts the value of `ipv6AddressCount` within the object to Boolean instead of the object itself.

fix(aws): Fix IPv6 addresses being incorrectly associated when cloning server groups that have launch templates enabled (#6979)

---

README.md

The [Spinnaker UI/UX SIG no longer exists](https://github.com/spinnaker/governance/pull/272).
It would still be nice to have a place to discuss the Spinnaker UI. Maybe enable discussions for this repo?

chore: Remove dead link from README

---

packages/app/src/settings.js
packages/core/src/config/settings.ts
packages/core/src/pipeline/config/stages/evaluateVariables/ExecutionAndStagePicker.tsx

Evaluate Variables stage on pipeline config view loads previous 100 pipeline execution history to show the evaluated variable values on previous execution.
The size of execution context is too huge if the pipeline is lengthy and it has a lot of artifacts and have a lot of previous executions. One of our pipeline is not accessible evaluate variables stage in the pipeline config as it timed out on `executionService.getExecutionsForConfigIds()` executions always due to size of the response (~400MB) and slowness of the VPN network.
Spinning circle UI is keep going and then timed out usually due to slowness of the network and size of the http get response.
This change can make the number of fetching history configurable on `settings-local.js`
``` …
```

feat(evaluateVariables stage) Made fetch exec history on evaluateVariables stage configurable

---

packages/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
packages/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettings.directive.html
packages/google/src/serverGroup/configure/wizard/advancedSettings/advancedSettingsSelector.directive.spec.js
yarn.lock

Add support for `resourceManagerTags` in GCE. For more details, refer to: https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert.
Enable [Resource Manager Tags](https://cloud.google.com/resource-manager/docs/tags/tags-overview) in the configuration of Deploy stages for the Google provider in GCE.
When setting up a GCE deployment, the resource-manager-tags input option can be found under the Advanced settings.
Resource manager tags must have the following structure: `tagKeys/xxxxxxxx` and `tagValues/xxxxxxx` and resource tags needs to be created before add them to the GCE cluster.
The resourceManagerTags are added in the cluster info:
Once the deployment is successful, the resourceManagerTags will be attached to both the InstanceTemplate and the Instance in GCE: …

feat(gce): support resourceManagerTags in instance template

---

packages/google/src/instance/gceInstanceTypeDisks.ts
packages/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
packages/google/src/serverGroup/configure/serverGroupConfiguration.service.js
packages/google/src/serverGroup/configure/wizard/advancedSettings/diskConfigurer.component.ts

Adds support for `hyperdisk-balanced` in Spinnaker for GCE. See: https://cloud.google.com/compute/docs/disks/hyperdisks
In the following changes, I added `hyperdisk-balanced` as option for Persistent Disk in the deploy stage when using GCE in Spinnaker.
This allows any user to configure their GCE instance to use hyperdisk. The backend already supports this new persistent disk type with the following PR: https://github.com/spinnaker/clouddriver/pull/6288

feat(gce): add support for hyperdisk in GCE

---

packages/kubernetes/src/help/kubernetes.help.ts
packages/kubernetes/src/pipelines/stages/deployManifest/DeployManifestStageForm.tsx

Adding the UI piece for the feature https://github.com/spinnaker/clouddriver/pull/6254 included in 1.35.x release
For existing stages the pipeline json wont be changed however if the user opts-in to the skipSpecTemplateLabels and sets it true it will be included in the pipeline json. Disabling it will put the skipSpecTemplateLabels as false.

feat(deployManifest): Adding skipSpecTemplateLabels option

---

packages/core/src/config/settings.ts
packages/kubernetes/src/help/kubernetes.help.ts
packages/kubernetes/src/pipelines/stages/deployManifest/DeployManifestStageForm.tsx

Adding support in the deployManifest stage for the Label Selectors features introduced in 1.35.x (see https://github.com/spinnaker/clouddriver/pull/6220) 
https://github.com/user-attachments/assets/8d86f2bd-d5b6-427d-bb22-91c11c362ed9

feat(deployManifest): Adding Label Selectors feature support

---

packages/kubernetes/src/pipelines/stages/deleteManifest/deleteManifestStage.ts
packages/kubernetes/src/pipelines/stages/deployManifest/deployManifestStage.ts
packages/kubernetes/src/pipelines/stages/findArtifactsFromResource/findArtifactsFromResourceStage.ts
packages/kubernetes/src/pipelines/stages/scaleManifest/scaleManifestStage.ts

For reference, see other stages:
- https://github.com/spinnaker/deck/blob/c96faa581482d251c07132bdcc023e04fc8e869b/packages/cloudfoundry/src/pipeline/stages/runJob/cloudFoundryRunJob.module.ts#L8
- https://github.com/spinnaker/deck/blob/c49d9b545642f511bfd2e14588b78fdf76385c5a/packages/amazon/src/pipeline/stages/cloneServerGroup/awsCloneServerGroupStage.js#L18
During execution, the account is stored in the context
Screenshot after fixing:
<kbd>![](https://github.com/user-attachments/assets/bd1cf653-78b2-4409-ad98-9e8f1bdf5e4c)</kbd>

fix(stages): accountExtractor in k8s stages should extract data from a context

---

packages/google/src/serverGroup/configure/serverGroupCommandBuilder.service.js
packages/google/src/serverGroup/details/serverGroupDetails.gce.controller.js

**ISSUE**
When cloning a server group using the UI. The resourceManagerTags and partnerMetadata are not populated even if the deployment is configured with resourceManagerTags and partnerMetadata.
**Expected Behavior**
If the server group has resourceManagerTags and partnerMetadata configured. Cloning the server group should populate these fields automatically.
The main issue comes from Clouddriver because the instanceTemplate doesn't include the partner metadata. See: https://github.com/spinnaker/clouddriver/pull/6334
In Deck, we just populate the resourceManagerTags and partnerMetadata in the instanceTemplateProperties under the lauchConfiguration.

fix(google): Add partner metadata on clone

---

packages/amazon/src/domain/ITargetTrackingPolicy.ts
packages/amazon/src/serverGroup/details/scalingPolicy/chart/MetricAlarmChart.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/TargetMetricFields.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/TargetTrackingChart.tsx
packages/amazon/src/serverGroup/details/scalingPolicy/targetTracking/UpsertTargetTrackingModal.tsx
packages/core/src/domain/ICloudMetric.ts
packages/titus/src/serverGroup/details/scalingPolicy/targetTracking/UpsertTargetTrackingModal.tsx

The UI for TargetTracking scaling policies didn't support ALBRequestCountPerTarget. This was the only missing metric documented here: https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html
This requires setting the resourceLabel parameter which is a combination of part of both the ALB and target group ARNs. This metric also only works with the Sum statistic. I found that the chart component hard coded average so that had to be fixed up as well.
Here are some screenshots
Summary before and after:
UpsertModal before and after:
(before the ALBRequestCountPerTarget isn't available)

feat(amazon): support ALBRequestCountPerTarget scaling policies
